# Swedish rows: (definition, friendly, exampleGloss, root1, root2)
ROWS = [
    ("Att söta eller rena; att ta bort strävhet från något.",
     "Att ta udden eller bitterheten ur något — bokstavligen genom att söta det, eller bildligt genom att mjuka upp en hård idé så att den går ner lättare.",
     "Redaktören mildrade den hårda recensionen innan den gick i tryck.",
     "ut, grundligt", "söt"),
    ("Överdrivet eller tillgjort religiös eller from.",
     "Beskriver någon vars religiösa hängivenhet känns iscensatt för syns skull, mer föreställning än genuin tro.",
     "Hans pietistiska suckande under predikan irriterade resten av bänkraden.",
     "fromhet, plikttrohet", "som har karaktären av"),
    ("Tvetydighet som uppstår ur den grammatiska strukturen — en mening som kan läsas på två sätt.",
     "En mening som är grammatiskt korrekt men kan läsas på två helt olika sätt, som \"I saw the man with the telescope.\"",
     "\"Visiting relatives can be tiring\" är en klassisk amfiboli — är släktingarna tröttande, eller är det att hälsa på dem?",
     "båda, på båda sidor", "att kasta"),
    ("Skarp, träffsäker, skär rakt till poängen.",
     "Skär rakt genom utfyllnaden — en skarp kommentar eller ett skarpt intellekt når sakens kärna snabbt, utan onödiga ord.",
     "Hennes skarpa kritik lämnade ingen av filmens luckor i handlingen någonstans att gömma sig.",
     "att skära", "görande, som har kvaliteten av"),
    ("Precis i början; i ett tidigt eller rudimentärt skede.",
     "Fortfarande i sina öppningsögonblick — en plan, en känsla eller en process som bara just har börjat ta form.",
     "De inledande stadierna av fördraget var lovande, men många detaljer återstod att lösa.",
     "att börja, att starta", "som strävar mot"),
    ("Ett formellt tal eller en text som prisar någon högt.",
     "En fullödig, formell hyllning — tänk ett lysande minnestal eller ett anförande som sjunger någons bedrifter från taken.",
     "Den avgående professorn skickades av med ett lovtal från sina närmaste studenter.",
     "allt", "församling, sammankomst"),
    ("Som rör verklig existens eller faktiskt varande, till skillnad från abstrakt teori.",
     "Om ting som de faktiskt finns i verkligheten, inte bara som idéer eller teorier om dem.",
     "Filosofer debatterar om tal har någon ontisk status eller bara finns i våra sinnen.",
     "varande, det som finns", "som rör"),
    ("Att bära frukt, eller att bli produktiv.",
     "Att äntligen ge utdelning — en insats, idé eller investering som bär frukt har växt från frö till något användbart.",
     "År av tyst forskning bar till sist frukt: ett vaccin som fungerade.",
     "frukt", "att göra, att framkalla"),
    ("Som föregriper eller framställer något som redan gjort innan det faktiskt har hänt.",
     "Att springa i förväg på ett litterärt sätt — att beskriva en framtida händelse som om den redan vore avslutad, för att poängen ska slå hårdare.",
     "Generalens proleptiska skål för \"segern\" utbringades en hel vecka före slaget.",
     "före", "att ta, att gripa"),
    ("Drivet av lufttryck; även relaterat till ande eller andedräkt.",
     "Betyder oftast \"drivet av tryckluft\" — men kan också syfta på ande eller andedräkt.",
     "De pneumatiska bromsarna väste när bussen stannade vid trottoarkanten.",
     "vind, andedräkt, ande", "som hör till"),
    ("Att beskriva Gud eller det gudomliga genom positiva påståenden — motsatsen till apofatisk.",
     "Ett sätt att tala om Gud genom att säga vad Gud är — \"God is love\" — snarare än bara vad Gud inte är.",
     "Katafatisk teologi talar tryggt om Gud som kärleksfull, rättvis och barmhärtig.",
     "ned, enligt", "att tala, att säga"),
    ("Grundat på tillit eller tro; även använt som en fast referenspunkt.",
     "Något du tar på tillit och sedan använder som ankare — ett referensmärke är den fasta punkt allt annat mäts mot.",
     "Lantmätarna satte ett referensmärke i berggrunden innan de kartlade platsen.",
     "att lita", "tillit, förtroende"),
    ("Ett försvar av Guds godhet givet ondskans existens.",
     "Det urgamla försöket att svara på \"If God is good, why does evil exist?\"",
     "Hennes uppsats undersökte teodicén genom Jobs bok.",
     "gud", "rättvisa"),
    ("Ömsesidigt inneboende — en teologisk term för hur Treenighetens personer finns i varandra.",
     "Ett teologiskt ord för tre-i-ett-samhörighet så fullständig att varje del helt rymmer och ryms av de andra.",
     "Läran om perikores försöker förklara hur Fader, Son och Ande är åtskilda men oskiljaktiga.",
     "runtom", "att gå, att vandra"),
    ("Att få en följd som gynnar eller slår tillbaka på någon.",
     "När äran (eller skulden) studsar tillbaka på den ansvariga — goda gärningar som lyfter ditt rykte kommer tillbaka och belönar dig.",
     "Lagets framgång kommer att falla tillbaka på den tyste, hårt arbetande tränaren som heder.",
     "tillbaka, åter", "våg"),
    ("Omöjlig att undvika eller undkomma.",
     "Dömt att ske oavsett vad du gör — det går inte att slingra sig ur ett oundvikligt utfall.",
     "Ålderdomen kommer till alla; den är helt enkelt oundviklig.",
     "inte", "att kämpa sig ur"),
    ("Som använder omständliga, ordrika formuleringar i stället för en direkt form.",
     "Att ta omvägen med orden — att säga \"make a decision\" i stället för \"decide.\"",
     "Hans omständliga mejl hade kunnat säga på en rad vad som tog honom tre stycken.",
     "runtom", "att förkunna, att berätta"),
    ("Andlig slöhet eller letargi.",
     "Det där dimmiga, tröga sinnestillståndet där tänkandet känns som att vada genom sirap.",
     "En våg av slöhet slog till i klassen precis efter lunchen.",
     "slö, trubbig", "tillstånd eller egenskap"),
    ("Inte gynnsam; som bådar illa.",
     "Ett dåligt tecken — förhållanden eller timing som tycks arbeta emot dig innan du ens har börjat.",
     "Grå himmel och ett dött bilbatteri gav en ogynnsam start på roadtripen.",
     "inte", "gynnsam, nådig"),
    ("Kött stuvat eller bräserat i sås — rättstavas \"fricasseed.\"",
     "En ombonad gammal matlagningsterm för kött som skurits upp och sjötts långsamt i sin egen sås tills det är mört.",
     "Mormors frikasserade kyckling var höjdpunkten på varje söndagsmiddag.",
     "att steka", "att bryta (i bitar)"),
    ("Ett konstgjort eller sämre substitut.",
     "En kopia som står in för originalet — den gör jobbet tekniskt sett, men alla ser att det inte är äkta vara.",
     "Krigstidens kunder nöjde sig med ersättningskaffe bryggt på rostad cikoria.",
     "ut, ersättningsprefix", "att sätta, att placera"),
    ("Att behandla en abstrakt idé som om den vore ett konkret ting.",
     "Att få en idé att kännas verklig och solid — att vända något luddigt, som \"the economy,\" till ett ting man kan peka på.",
     "Att kalla en nations \"ande\" för ett eget väsen är att tingliggöra något som egentligen bara är miljoner enskilda val.",
     "ting", "att göra"),
    ("Undkom eller undvek skickligt.",
     "Gled undan rent — smet från något, ofta listigt eller nätt och jämnt, vare sig det var ett gripande, en fråga eller ett svar.",
     "Svaret undgick henne i timmar tills det plötsligt klickade i duschen.",
     "ut, bort", "att leka"),
    ("Som uttrycker tvivel, förvirring eller en olöst motsägelse.",
     "Fast i en verklig tankeåtervändsgränd — inte förvirrad av lättja, utan för att frågan själv motstår ett prydligt svar.",
     "Sokrates avslutade ofta sina dialoger på en aporetisk ton, med fler frågor än svar.",
     "utan", "passage, väg"),
    ("Ett stilfigur som namnger något genom en förknippad term, t.ex. \"the crown\" för monarken.",
     "Att använda ett närbesläktat ord i stället för saken själv — att säga \"the White House announced\" när man menar administrationen.",
     "\"Wall Street had a rough day\" är metonymi — det betyder egentligen att börsen hade det.",
     "ändring, efter", "namn"),
    ("Att rycka upp med rötterna; att slita ur en naturlig miljö.",
     "Att dra upp något (eller någon) med rötterna, bort från den plats eller kultur de hör hemma i.",
     "Kriget ryckte upp en hel generation med rötterna och spred familjer över gränserna.",
     "bort, av", "rot"),
    ("Välljudande.",
     "Helt enkelt skönt att höra — ett välljudande ord, namn eller en mening rullar mjukt längs örat, nästan musikaliskt.",
     "\"Murmuring brook\" är en välljudande liten fras, mjuk och lätt att säga.",
     "god, väl", "ljud, röst"),
    ("Allmänt antagen eller förmodad att vara.",
     "Allmänt trodd vara sann, även om det inte egentligen är bevisat — den \"supposed\" versionen av något.",
     "Den förmodade författaren till brevet visade sig senare vara en total främling.",
     "att tänka, att anse", "som har naturen av"),
    ("Ett nybildat ord eller uttryck.",
     "Ett alldeles nytt ord — nyss uppfunnet, ännu inte (eller knappt) i ordboken.",
     "\"Doomscrolling\" började som ett nyord och blev snabbt vardagsslang.",
     "ny", "ord, tal"),
    ("Arg eller vresig.",
     "I ett surt, irriterat humör — snabb att smälla till, så som man en gång trodde att mjälten styrde lynnet.",
     "Han skickade iväg ett bittert svar på mejlet inom sekunder efter att ha läst det.",
     "mjälte (vredeens säte)", "påverkad av"),
    ("Benägen att moralisera på ett pompöst eller tillgjort sätt.",
     "Älskar att dela ut små livsläxor på ett självupptaget sätt, som om varje mening vore en lyckokaka.",
     "Hans salvelsefulla skål om \"vänskapens sanna innebörd\" fick alla att kolla klockan.",
     "åsikt, sentens", "full av"),
    ("Överdrivet pratsam, särskilt om triviala saker.",
     "Slutar bara inte prata — raljerar om småsaker långt efter att alla andra har slut på samtalsämnen.",
     "Den pratsamma taxichauffören berättade hela sitt liv innan vi hade lämnat flygplatsen.",
     "att pladdra, att tjattra", "benägen att"),
    ("Dårskap, fånighet.",
     "Ren dårskap — en kommentar eller plan så fånig att den knappt förtjänar ett seriöst svar.",
     "Planens rena dåraktighet blev uppenbar i samma ögonblick de prövade den.",
     "dåraktig, fånig", "tillstånd att vara"),
    ("Den avslutande delen av ett tal, ofta sammanfattande.",
     "Talets stora avslutning — sista avsnittet där talaren samlar allt och slår in poängen.",
     "Vid slutappellen stod halva publiken på fötterna.",
     "igenom, till slutet", "att tala, att plädera"),
    ("Onödig upprepning av samma idé med andra ord.",
     "Att säga samma sak två gånger utan att lägga till något nytt, som \"free gift\" eller \"end result.\"",
     "\"It is what it is\" är en favorittautologi bland folk som undviker en riktig förklaring.",
     "densamma", "ord, tal"),
    ("Bruket av mycket få ord; knapphändigt tal.",
     "Att säga mycket med väldigt lite — konsten av det korta, raka svaret, uppkallad efter de beryktat fåordiga spartanerna i Lakonien.",
     "\"Molon labe\" — \"kom och hämta dem\" — är historiens mest berömda stycke lakonism.",
     "en spartan från Lakonien", "sed, sätt"),
    ("Tama, överförenklade idéer; ursprungligen tam mat eller välling.",
     "Tunt, urvattnat tänkande — innehåll så förenklat och säkert att det saknar näring för sinnet.",
     "Politikerns tal var mest tomt prat: vaga löften utan något att ta på.",
     "att föda", "medel eller redskap"),
    ("Som framkallar sömn eller dåsighet.",
     "Så tråkigt — eller så bokstavligt sövande — att det gör en sömnig. Tänk varm mjölk, eller ett tre timmar långt budgetmöte.",
     "Föreläsningens sövande surr fick halva rummet att kämpa för att hålla ögonen öppna.",
     "djup sömn", "görande, framkallande"),
    ("Överdrivet smickrande eller oljig i sättet.",
     "Så slätt charmig att det känns halt — smicker lagt på så tjockt att man nästan känner fettet.",
     "Den inställsamma säljaren fortsatte berömma min \"utsökta smak\" före varje merförsäljning.",
     "att smörja, att olja", "full av"),
    ("Snabb att anmärka, överdrivet kritisk mot triviala saker.",
     "Petig till ett fel — typen som hittar fel i allt, även när det inte spelar någon roll.",
     "Hans småaktiga anmärkningar på rapporten handlade bara om kommatering.",
     "att gripa, att ta", "en fälla, ett sofism"),
    ("Trög, mentalt eller fysiskt overksam.",
     "Långsam och halvsovande, som en björn i ide — knappt i rörelse, knappt i tanke.",
     "Kontoret föll i dvala i augustivärmen.",
     "att vara domnad, att vara trög", "i ett tillstånd av"),
    ("En förvaltare eller ämbetsman som skötte ett medeltida hushåll.",
     "Medeltidens motsvarighet till en stabschef — den betrodda tjänstemannen som drev en herres hushåll och gods från dag till dag.",
     "Borgens seneskalk skötte allt från skördeböcker till gästlistan.",
     "gammal, senior", "tjänare"),
    ("Att tala eller skriva utförligt om ett ämne.",
     "Att verkligen komma igång om ett ämne — tala eller skriva på och på, och täcka det från varje vinkel.",
     "Fråga honom om veteranbilar så kommer han att breda ut sig i en timme i sträck.",
     "ut", "rum"),
    ("Utan värde, obetydlig; även ogiltig eller verkningslös.",
     "Värt i princip ingenting — en verkningslös klausul i ett kontrakt är en som inte egentligen gör något.",
     "Domstolen dömde den gamla stadgan verkningslös, eftersom den aldrig hade tillämpats.",
     "bagateller, strunt", "tillhörande"),
    ("Visdom, skarpsinnigt omdöme.",
     "Skarp, praktisk visdom — det goda omdöme som kommer av erfarenhet, inte bara boklig bildning.",
     "Den gamle kaptenens klokskap höll besättningen undan från trubbel mer än en gång.",
     "skarpluktande, skarpsinnig", "egenskap av"),
    ("Pöbeln eller massorna, använt föraktfullt.",
     "Ett snobbigt, avfärdande ord för \"the rabble\" eller vanligt folk, använt med förakt.",
     "Greven hånlog åt patrasket som samlades utanför palatsgrindarna.",
     "hund", "kollektiv, flock"),
    ("Fräck, förödmjukande behandling eller språk.",
     "Grym, hånfull behandling avsedd att förödmjuka — den sortens skymf som är gjord för att svida.",
     "Han uthärdade år av smädelser från kritiker innan hans verk äntligen erkändes.",
     "med, grundligt", "att svälla (av stolthet)"),
    ("Med misstänksamhet eller ogillande; en sidoblick.",
     "Den där sidoblicken du ger något du inte riktigt litar på — en blick laddad med tvivel.",
     "Läraren såg snett på den misstänkt prydliga läxan.",
     "åt, till", "sned, bias"),
    ("En dum person; ett träskalle.",
     "En gammaldags, nästan öm skymf för någon som är trög eller tjockskallig — en träskalle.",
     "\"Din dumbom,\" skrattade hon, \"du har haft kartan upp och ner hela tiden.\"",
     "jordklump", "huvud"),
    ("Att sätta i rörelse eller handling; att motivera.",
     "Att vara gnistan som sätter något i rörelse — vare sig det är en maskin som slås på eller en person som äntligen handlar på en idé.",
     "Rädslan att förlora kontraktet drev hela laget till en helg med övertid.",
     "ett görande, ett drivande", "att driva, att göra"),
    ("Förskingring av medel anförtrodda ens vård.",
     "Att tyst stjäla pengar man var betrodd att sköta — förskingring i en gammaldags kappa.",
     "Kassörens förskingring gick obemärkt i nästan ett decennium.",
     "privat egendom", "boskap, rikedom"),
    ("En grupp som anses stå i utkanten av den respektabla societeten.",
     "Den glamorösa men skumma sociala undervärlden — folk som lever strax utanför reglerna för \"respectable\" societet.",
     "Romanen följer en sångerska som navigerar 1920-talets kabaréers halvvärld.",
     "halv", "värld, societet"),
    ("Fortfarande existerande; inte utdöd eller förstörd.",
     "Fortfarande kvar i dag — används om gamla ting (handskrifter, arter, byggnader) som har lyckats överleva.",
     "Bara tre bevarade exemplar av den första tryckningen är kända.",
     "ut", "att stå"),
    ("Svekfullhet; svek mot förtroende.",
     "Djupt, avsiktligt svek — att bryta ett förtroende som någon hade rätt att vänta att du skulle hålla.",
     "Generalen förlät aldrig sin gamle väns trolöshet vid förhandlingsbordet.",
     "igenom, emot", "tro, tillit"),
    ("En regional dialekt, särskilt en icke-standardspråklig.",
     "Det särpräglade, lokala sättet folk talar på i en viss trakt — fullt av ord och rytmer en utomstående kanske inte fångar.",
     "Hennes mormor talade fortfarande öns dialekt vid familjemiddagar.",
     "grovt tal, dialekt", "tass — klumpigt tal"),
    ("En särskild rätt som tillhör en person eller grupp.",
     "Ett privilegium som är ditt och bara ditt — en rätt som följer med din roll, ställning eller status.",
     "Att välja familjens semestermål är farfars företrädesrätt, och det vet alla.",
     "före", "att fråga, att rösta"),
    ("Djärvhet, oförvägenhet; även tålighet eller uthållighet.",
     "Rå, modig motståndskraft — nerverna att gå vidare och tuffheten att fortsätta när du väl gör det.",
     "Det krävdes verklig oförvägenhet att korsa passet i snöstorm utan karta.",
     "djärv, härdad", "tillstånd, läge"),
    ("Att slå ut i blom; även att utvecklas eller gradvis framträda.",
     "Att slå ut i fullt uttryck — som en blomma som öppnar sig, eller en idé som äntligen kommer till sin rätt.",
     "Hennes tysta målarbegåvning slog ut i full blom när hon väl fick en egen ateljé.",
     "ut", "att börja blomma"),
    ("En tyngd på ett snöre som används för att avgöra lodrätthet; bildligt, en måttstock för omdöme.",
     "En tyngd på ett snöre som hänger helt rakt ner, för att kolla om något är lodrätt — och i vidare mening varje fast måttstock du mäter allt annat mot.",
     "Han använde sin egen farfars ärlighet som ett slags sänklod för varje beslut.",
     "bly", "snöre, mått"),
    ("Gärna, villigt (ålderdomligt).",
     "Ett gammaldags sätt att säga \"gladly\" eller \"with pleasure.\"",
     "\"Jag skulle gärna vila här en stund,\" suckade resenären.",
     "glad, ljuvlig", "gärna, villigt"),
    ("Hård offentlig kritik eller vanära.",
     "Offentlig skam som hopas på någon på ett stort, synligt sätt — vanäran som kommer av utbrett ogillande.",
     "Skandalen drog offentlig vanära över hela firman.",
     "emot", "vanära, förebråelse"),
    ("Skarpt sarkastisk, bitande i kvickhet eller kritik.",
     "Kvickhet med riktiga tänder — en bitande kommentar svider lite just för att den är så träffsäkert riktad.",
     "Hennes bitande filmrecensioner fruktades av regissörer och älskades av läsare.",
     "att bita", "bitande, görande"),
    ("En formell proklamation, ofta politisk eller militär.",
     "Ett stort, officiellt tillkännagivande — vanligen ett som utropar en ny regering, ett uppror eller ett stort dekret.",
     "Generalens proklamation tillkännagav den nya regeringen i gryningen.",
     "fram", "att tillkännage"),
    ("En person med ytlig kunskap som låtsas vara expert.",
     "Någon som har skummat ytan av ett ämne och sedan pratar som om de skrev läroboken om det.",
     "Middagsbjudningens halvbildade besserwisser rättade självsäkert den faktiska astrofysikern vid bordet.",
     "att veta", "diminutiv — en liten vetare"),
    ("Avtagande av de mentala förmågorna på ålderns höst.",
     "Den dimmiga, glömska sträckan av hög ålder när sinnets skärpa börjar falna.",
     "På sin ålders höst berättade han samma tre historier varje besök, varje gång som om de vore nya.",
     "att dota, att vara dåraktig", "tillstånd eller resultat"),
    ("Sidan som är skyddad från vinden.",
     "Den lugna, skyddade sidan av något — en kulle, ett skepp, en mur — där vinden inte riktigt når dig.",
     "Vandrarna slog upp tältet på åsens läsida för att slippa byarna.",
     "skydd, värn", "flank, sida"),
    ("Att avvärja eller slå undan ett slag, en fråga eller ett argument.",
     "Att mjukt slå undan något — ett svärdshugg, en besvärlig fråga eller en anklagelse — utan att tappa takten.",
     "Hon parerade reporterns knepiga fråga med ett lätt skämt.",
     "att avvärja", "att bereda, att försvara"),
    ("Illaluktande, skadlig.",
     "Stinkande på ett sätt som känns nästan giftigt — en stank så illa att det tycks farligt att andas.",
     "En stinkande lukt drev upp från träsket när solen gick ner.",
     "skadlig ånga", "som har naturen av"),
    ("En person hängiven lyx och njutning.",
     "Någon som lever för bekvämlighet och njutning — fin mat, mjuka sängar, lätt liv — uppkallad efter den antika grekiska staden Sybaris, känd för sitt överflöd.",
     "En sann sybarit, han vägrade vilket hotellrum som helst utan badkar.",
     "antik grekisk stad känd för lyx", "invånare i"),
    ("Att medvetet lägga åt sidan eller ignorera en del av något.",
     "Att mentalt lägga en pusselbit åt sidan med flit, så att du kan fokusera rent på resten.",
     "Låt oss bortse från kostnaden ett ögonblick och bara fråga om planen faktiskt fungerar.",
     "före, bort", "att skära"),
    ("Att kritisera hårt; även att flå huden av.",
     "Att slita i någon med hård kritik — verbalt, som om du bokstavligen flådde huden av.",
     "Kritikerna sågade uppföljaren för att ha svikit allt fansen älskade med originalet.",
     "av", "skinn, hud"),
    ("Att anföra som bevis eller belägg.",
     "Att föra fram ett faktum eller exempel till stöd för din poäng — det du pekar på när någon frågar \"what's your evidence?\"",
     "Advokaten åberopade tre vittnen till stöd för klientens alibi.",
     "till, mot", "att leda"),
    ("Resor eller vandringar, särskilt långa eller omfattande.",
     "Långa, kringflackande färder — den sortens omfattande vandring som för dig långt hemifrån en god stund.",
     "Hans vandringar över tre kontinenter fyllde en hel hylla med resedagböcker.",
     "igenom", "fält, land (peregrinus: främling)"),
    ("En tiggare, eller en som lever på allmosor.",
     "Någon som lever av att be om välgörenhet — historiskt beskrev detta också munkar som tog fattigdomslöften och levde på gåvor.",
     "De tiggande bröderna ägde ingenting och förlitade sig helt på bybornas godhet.",
     "att tigga", "tiggare"),
    ("Ytterst generös.",
     "Generös i en stor, nästan prålig skala — den sortens gåva som får folk att flämta till.",
     "Den frikostiga donationen finansierade hela bibliotekets nya flygel.",
     "gåva, tjänst", "görande, givande"),
    ("Utmattning av brist på näring; även brist på livskraft.",
     "Ett svagt, tömt tillstånd av att inte ha fått mat eller bränsle — bokstavligen av hunger, eller bildligt av att inte ha något kvar att gå på.",
     "Vid belägringens slut var soldaterna nära utmattning.",
     "tom, vakum", "handlingen eller resultatet av"),
    ("Bitter, skymfande kritik.",
     "Kritik som har gått långt förbi det sakliga och förvandlats till ett vredgat, bittert utbrott.",
     "Nätkommentarerna upplöstes i rena skällsord inom minuter.",
     "fel", "att bereda, att förse"),
    ("Fientlig, skadlig i verkan.",
     "Arbetar emot dig, även tyst — förhållanden eller attityder som är ovänliga mot dina intressen.",
     "Den nya politiken var fientlig mot småföretag, även om det inte var avsikten.",
     "inte", "vän"),
    ("Benägen att väcka förbittring eller missnöje, ofta genom orättvisa jämförelser.",
     "Dömt att få någon att känna sig åsidosatt — oftast för att det ställer folk eller ting mot varandra på ett orättvist sätt.",
     "Att ranka syskonen efter \"vem mamma tycker bäst om\" är ett förargligt spel som ingen borde leka.",
     "avund", "att se på (med illvilja)"),
    ("En person av lägre rang eller status; en underordnad.",
     "Någon längre ner i kommandokedjan eller den sociala stegen — en junior, som arbetar under någon med mer makt.",
     "Som ung underordnad officer tog han order länge innan han någonsin gav dem.",
     "under", "växelvis, annan"),
    ("Att känna eller uttrycka starkt hat för.",
     "Att avsky något så mycket att du förbannar det högt — ren, högljudd avsky.",
     "Byborna förbannade skatteindrivaren varje gång hans vagn rullade genom byn.",
     "ur", "helig (att förbanna ut ur det heliga)"),
    ("Ett naturligt yttre hölje, som hud eller ett skal.",
     "Naturens eget skyddande omslag — hud, skal, hylsa eller skal, vad som än täcker och skyddar något levande.",
     "En sköldpaddas skal är ett anmärkningsvärt tåligt hölje.",
     "på, över", "att täcka"),
    ("Oskyldig, naiv, med barnslig enkelhet; motsatsen till \"disingenuous.\"",
     "Öppet tillitsfull och lite naiv, utan dold agenda — lätt att blanda ihop med \"ingenious,\" som betyder klok.",
     "Hennes godtrogna fråga — \"varför skulle någon ljuga om det?\" — visade hur lite list hon hade.",
     "i, infödd", "att avla (frifödd, uppriktig)"),
    ("Överdriven omsorg om smådetaljer eller regler.",
     "Att gå vilse i de små reglerna och missa den större bilden — att älta det finstilta som ingen annan bryr sig om.",
     "Hans pedanteri om Oxford-komman spårade ur hela mötet.",
     "barnens lärare", "praxis eller egenskap"),
    ("En grundlig, omsorgsfull undersökning.",
     "En djup, ingen-sten-orörd blick på något — att gå igenom varje detalj med verklig omsorg.",
     "Först efter en noggrann genomgång av liggarna dök avvikelsen upp.",
     "igenom, grundligt", "att söka, att undersöka"),
    ("Att resa invändningar; att visa motvilja.",
     "Att artigt backa eller tveka i stället för att haka på direkt — ett mjukt \"I'd rather not.\"",
     "När hon ombads skriva under utan att läsa, invände hon.",
     "från, bort", "att dröja"),
    ("Ytligt plausibel men i själva verket fel.",
     "Låter övertygande vid första ögonkastet men faller isär så fort du faktiskt granskar det.",
     "\"Everyone's doing it\" är ett bestickande argument som aldrig riktigt håller vid närmare granskning.",
     "utseende, uppsyn", "full av (skenbart skön)"),
    ("Oärligt, hycklande tal, ofta moraliserande.",
     "Predikande tal som låter dygdigt men inte backas av någon riktig känsla — moralisk posering på autopilot.",
     "Han var trött på det korporativa tomma pratet om \"familj\" från ett företag som aldrig gav någon ledigt.",
     "att sjunga (senare: sjungande jargong)", "tiggares gnällande tal, sedan hyckleri"),
    ("Som saknar mod, feg.",
     "Räddhågad till ryggradslöshet — för rädd för att stå upp även när det uppenbart spelar roll.",
     "Styrelsens fega tystnad lät skandalen skena ur kontroll.",
     "mycket liten", "ande, mod"),
    ("Rävlik; slug, listig.",
     "Slug och klok som en räv — kvicktänkt, lite smygande, alltid ett steg före.",
     "Han log ett rävaktigt leende i samma ögonblick han såg kryphålet.",
     "räv", "av eller lik"),
    ("En efter en, i följd.",
     "Tagna strikt en i taget, i ordning — inget hopp framåt, inget av två på en gång.",
     "Domaren behandlade vart och ett av de tolv kraven i tur och ordning.",
     "rad, följd", "en i taget"),
    ("Extrem sparsamhet; snålhet.",
     "Att vara knusslig med pengar (eller ord, eller resurser) långt förbi rimlig sparsamhet.",
     "Hans snålhet var legendarisk — han återanvände tepåsar tre gånger om.",
     "att spara, att vara sparsam", "tillstånd eller praxis"),
    ("En rättelse, särskilt i en text.",
     "En lagning i en skrift — en lärd justering som rättar ett fel i en gammal eller viktig text.",
     "Den nya utgåvan rymmer dussintals rättelser av originalmanuskriptet.",
     "ur", "fel, misstag"),
    ("Måttlig i ätande och drickande.",
     "Medvetet återhållsam kring mat och dryck — aldrig överdrivet, alltid lämnar lite på tallriken.",
     "Hans återhållsamma vanor höll honom skarp länge efter att hans jämlikar hade saktat ner.",
     "bort från", "berusande dryck"),
    ("Ett grammatiskt misstag eller ett brott mot etiket.",
     "Ett misstag i grammatik eller manér — den sortens lilla fel som får en pedant att ryna på näsan.",
     "\"Between you and I\" är ett vanligt språkfel som fortfarande får grammatiker att rygga.",
     "kilikisk stad känd för 'dålig' grekiska", "sed, sätt"),
    ("Som rör konflikt inom en grupp; ömsesidigt förödande.",
     "Inbördes strid som river sönder en grupp inifrån — en kamp där alla förlorar, för det är familj mot familj.",
     "Partiets inbördes käbbel gjorde mer skada än någon yttre motståndare kunde.",
     "mellan, bland", "att döda"),
    ("Likgiltig, vårdslös attityd.",
     "En axelryckning vänd till en hel personlighet — att bry sig så lite om saker som brukade spela roll att inget längre verkar värt mödan.",
     "Hans likgiltiga attityd till prisceremonin förvånade alla som visste hur hårt han hade arbetat.",
     "litet", "att bry sig"),
    ("En förvirrad, komplicerad situation eller tvist.",
     "En trasslig, rörig situation som är svår att begripa — delvis missförstånd, delvis drama, helt förvirring.",
     "Hela härvan kring bordsplaceringen började med ett felplacerat namnkort.",
     "i", "att trassla, att förvirra"),
    ("Hotfull, hotande.",
     "Bärande en omisskännlig luft av hot — en hotfull blick eller ett hotfullt brev gör det mycket tydligt att något illa kan följa.",
     "Brevets hotfulla ton gjorde hyresgästen nervös innan hon ens öppnat kuvertet.",
     "att hota", "tjänande till"),
    ("Stark offentlig kritik eller verbal skymf.",
     "Högljudd, offentlig fördömelse — den sortens svidande kritik som utspelar sig inför alla.",
     "Visselblåsaren mötte år av offentligt smutskastande innan historien gav henne rätt.",
     "emot", "att tala"),
    ("Ett plötsligt våldsamt utbrott, av känsla eller handling.",
     "En plötslig, intensiv stöt som överväldigar dig på en gång — ett skrattanfall, raseri eller hosta som slår som en våg.",
     "Hon greps av ett skrattanfall hon inte kunde förklara för någon annan i rummet.",
     "bortom", "skarp, akut"),
    ("Tillagd från en yttre källa, inte inneboende.",
     "Skruvad på utifrån i stället för inbyggd från början — ett extra, inte en kärndel.",
     "Kommentaren känns tillagd utifrån, som om den klistrats på en redan färdig text.",
     "till, dessutom", "att godkänna, att anta"),
    ("Brist på kunskap, okunnighet.",
     "Enkelt inte-vetande — en kunskapslucka, utan någon värdering fäst vid den.",
     "Han medgav sin okunnighet om franskt vin och lät sommelieren välja.",
     "inte", "att veta"),
    ("Överdrivet intresse för sexuella angelägenheter.",
     "En överivrig, gloende nyfikenhet på allt pikant — intresse som har gått förbi det sunda och blivit närgånget.",
     "Tabloidens lystenhet kring parets privatliv gränsade till det tvångsmässiga.",
     "att klia, att längta efter", "tillstånd av"),
    ("Sotig, mörk, disig.",
     "Mörk och rökig till utseendet, som om allt vore täckt av ett tunt lager sot.",
     "En sotig dis hängde över fabriksstaden i skymningen.",
     "sot", "full av"),
    ("Att förneka eller motsäga.",
     "Att rakt tala emot något någon annan sagt — att säga \"that's not so.\"",
     "Ingen vågade motsäga den gamle kaptenens skildring av stormen.",
     "emot", "att tala"),
    ("Lathet, lättja (från latin).",
     "Ett gammalt latinskt ord för ren lathet — släpet i att inte vilja göra någonting alls.",
     "Munkarna predikade mot lättjan som en av själens tysta faror.",
     "inte", "upptagen, flitig"),
    ("En sköld som visar ett vapen.",
     "Den sköldformade emblem som visar en familjs vapen — dess heraldiska \"nameplate.\"",
     "Familjens vapensköld hänger fortfarande ovanför den gamla herrgårdens ytterdörr.",
     "sköld", "diminutiv / föremål"),
    ("Föråldrad, obsolet, eller pensionerad på grund av ålder.",
     "Förbi sin nyttiga topp och satt på bete — för gammaldags eller utsliten för att fortsätta göra jobbet.",
     "Den utrangerade skrivaren byttes äntligen ut efter femton års pappersstopp.",
     "bortom", "år"),
    ("Substitut, särskilt inom medicin.",
     "Ersättningsmedel som används när den riktiga behandlingen inte finns — medicinska understudies, i grund och botten.",
     "Krigstidens läkare förlitade sig ofta på ersättningsmedel när de rätta medicinerna tog slut.",
     "i stället för", "att gå, att vika"),
    ("Skrytsam, skrävlande prat.",
     "Stort, blåsigt skryt — högljutt tal om din egen storhet som mest är tom luft.",
     "Hans skrytsamma prat om att \"på egen hand\" ha räddat projektet lurade ingen som faktiskt hade varit där.",
     "skrytsam riddare i Orlando Furioso", "handling, uppvisning"),
    ("Att använda knep eller svek för att uppnå något.",
     "Att slingra sig till ett mål genom smygknep snarare än schysst spel.",
     "Han slingrade sig in i affären med ett kontrakt fullt av finstilt.",
     "att käbbla, att lura", "knep; senare en skarp sväng"),
    ("Den rena eller abstrakta vetenskapen om lärande eller kunskap, ofta matematik.",
     "Lärande i sin renaste, mest abstrakta form — kunskapens djupa struktur själv, särskilt den matematiska sorten.",
     "Filosofen drömde om en universell mathesis som kunde ena varje kunskapsfält.",
     "att lära", "handlingen att lära"),
    ("Överdrivet upptagen av formella regler eller triviala detaljer.",
     "Överdrivet strikt om småsakerna — rättar små teknikaliteter som inte egentligen ändrar något.",
     "Det kändes lite pedantiskt att bråka om \"who\" kontra \"whom\" i ett textmeddelande.",
     "barnledare, handledare", "som har sättet av"),
    ("Ett blixtrande, gnistrande ljus.",
     "En snabb, glittrande ljusglimt — tänk solljus som studsar mot vatten, eller en diamant som fångar ljuset.",
     "Kristallkronans glitter strödde ljus över varje hörn av balsalen.",
     "att glittra, att blixtra", "handlingen av"),
    ("En nybörjare, novis.",
     "Någon alldeles ny i en färdighet eller ett fält — fortfarande i färd med att lära sig grunderna, ännu inte expert.",
     "Även en nybörjare i schack kan se den där grodan.",
     "rekryt, novis", "en rå ung soldat"),
    ("Ytterst dålig, avskyvärd.",
     "Dålig på ett sätt som förtjänar verklig avsky — inte bara \"mediocre,\" utan verkligt avskyvärd.",
     "Recensenten kallade uppföljaren avskyvärd, och biografsiffrorna höll med.",
     "att förbanna", "värd, i stånd att bli"),
    ("Blodsröd till färgen.",
     "Ett djupt, livfullt rött — färgen av färskt blod, berömt använt av Shakespeares Macbeth.",
     "Solnedgången vände hela himlen till en blodröd glöd.",
     "in i", "kött (kött-röd)"),
    ("Ett litet mellanrum eller en spalt mellan ting.",
     "Det lilla mellanrummet som är lätt att förbise — springan mellan golvtiljorna, luckan i ett schema.",
     "Ogräs trängde upp genom varje springa i den gamla tegelgången.",
     "mellan", "att stå"),
    ("Kritiska eller klandrande anmärkningar.",
     "Spetsiga, ogillande kommentarer — den sortens kritik som bär en smula skällande ton.",
     "Professorns anmärkningar på uppsatsen fyllde marginalerna med rött bläck.",
     "sinne", "att vända mot"),
    ("Omöjlig att vederlägga, obestridlig.",
     "Så solidt bevisad att det inte går att argumentera emot — fallet är helt enkelt stängt.",
     "DNA-beviset var ovedersägligt, och rättegången var över inom timmen.",
     "inte", "att motstå, att sätta sig emot"),
    ("Komplexitet, inveckladhet; även en invridning.",
     "En trasslig, invikt-i-sig-själv sorts komplexitet — saker virade så tätt att de är svåra att dra isär.",
     "Handlingens invecklade knut lämnade halva publiken kvar att nysta upp den efter eftertexterna.",
     "in, inåt", "att rulla, att vända"),
    ("Kraft eller möda, som i \"by dint of.\"",
     "Ren möda eller kraft — överlever mest i dag i frasen \"by dint of.\"",
     "Han klarade examen tack vare ren, envis övning.",
     "ett slag, en stöt", "med kraft av"),
    ("Hopfogad med tappskarv; stadigt infogad.",
     "Låst ihop på det gammaldags snickarsättet — en bit som glider tätt in i ett hål skuret just för den.",
     "Den gamla ladans balkar var tappade i varandra utan en enda spik.",
     "ett urtag, ett hål", "ett bett, ett grepp"),
    ("Högst relevant, träffande.",
     "Precis rätt för stunden — en kommentar, ett citat eller ett exempel som landar helt på pricken.",
     "Hennes träffande anmärkning sammanfattade hela debatten i en mening.",
     "till", "att placera"),
    ("Mjukt glödande eller fladdrande (ljus); även lätt kvickhet.",
     "Glödande milt snarare än flammande — ett mjukt, fladdrande ljus, eller en kvickhet som är lekfull snarare än skarp.",
     "Stearinljus kastade ett fladdrande sken över det gamla matrummet.",
     "att slicka", "görande (ljus som 'slickar')"),
    ("En religiös eremit som lever i ensamhet.",
     "Någon som drar sig undan världen helt för att leva ensam i bön och eftertanke.",
     "Eremiten bodde i en liten cell fäst vid kyrkan i över trettio år.",
     "tillbaka, bort", "att dra sig undan"),
    ("Att stilla törst; att släcka.",
     "Att helt stilla ett begär — oftast törst, men bildligt vilket djupt behov som helst.",
     "Ett kallt glas vatten släckte hans törst efter den långa vandringen.",
     "slak, lös", "att slappa, att stilla"),
    ("Nålformad.",
     "Lång, tunn och spetsig som en nål — formen av en tallbarr eller en skarp liten kristall.",
     "Tallar är lätta att känna igen på sina nålformiga blad.",
     "nål", "liten"),
    ("Uttömd på livskraft, svag, överförfinad.",
     "Utsliten och mjuk — har förlorat sin ursprungliga styrka eller spänst genom för mycket bekvämlighet eller förfining.",
     "Kritiker kallade den en gång så djärva tidskriften utlevad, en skugga av sina tidiga djärva år.",
     "ut", "fruktbar, som har burit"),
    ("Ett tillbehör eller ett mindre vidhängande föremål eller rättighet.",
     "Ett litet extra som följer med något större — tillbehören och påhängena som hör till huvudsaken.",
     "Hyresavtalet omfattade garaget och alla dess tillbehör.",
     "till", "att tillhöra"),
    ("Att skyla över eller förminska ett fel.",
     "Att släta över ett misstag med mjuka ord, så att det låter mindre än det egentligen är.",
     "Han försökte släta över den missade deadlinen med vagt prat om \"oförutsedda utmaningar\".",
     "en glosa, en förklaring", "att kommentera — sedan att släta över"),
    ("I ett tidigt skede, precis i början.",
     "Precis på väg att visa sig — det allra första, knappt synliga stadiet av något större som kommer.",
     "Läkarna fångade de begynnande tecknen på sjukdomen innan den kunde sprida sig.",
     "på, in i", "att ta (att ta upp, att börja)"),
    ("Kreativ inspiration, särskilt gudomlig.",
     "En plötslig rusning av inspiration som känns större än du — som om idén andades in i dig någon annanstans ifrån.",
     "Poeten beskrev att hela stycket kom i en enda stöt av ingivelse klockan tre på natten.",
     "till, på", "att blåsa (ett andedräkt-på)"),
]
