# Turkish rows: (definition, friendly, exampleGloss, root1, root2)
ROWS = [
    ("Tatlandırmak veya arındırmak; bir şeyden sertliği gidermek.",
     "İğneyi veya acılığı çıkarmak — sözcük anlamıyla tatlandırmak, ya da mecazen sert bir fikri yumuşatıp yutulur kılmak.",
     "Editör, sert eleştiriyi basıma gitmeden önce yumuşattı.",
     "dışarı, kökten", "tatlı"),
    ("Aşırı veya yapmacık dindar.",
     "Dini bağlılığı gösteriş gibi duran, samimi inançtan çok performans olan kişiyi anlatır.",
     "Vaaz sırasındaki sofuca iç çekişleri sıranın geri kalanını rahatsız etti.",
     "dindarlık, vazife", "niteliğine sahip"),
    ("Dilbilgisel yapıdan doğan belirsizlik — iki türlü okunan cümle.",
     "Dilbilgisi doğru ama tamamen farklı iki yoldan okunabilen cümle, örneğin \"Visiting relatives can be tiring\".",
     "\"Visiting relatives can be tiring\" klasik bir anlam ikiliğidir — yorucu olan akrabalar mı, yoksa onları ziyaret etmek mi?",
     "her ikisi, iki yanda", "atmak"),
    ("Keskin, delici, doğruca noktaya kesen.",
     "Laf kalabalığını keser — keskin bir yorum veya zihin, boşa söz olmadan işin özüne hızla varır.",
     "Onun keskin eleştirisi filmin kurgu boşluklarına saklanacak yer bırakmadı.",
     "kesmek", "yapmak, niteliğe sahip"),
    ("Yeni başlayan; erken veya ilkel evrede.",
     "Hâlâ açılış anlarında — henüz biçim almaya başlamış plan, duygu veya süreç.",
     "Antlaşmanın başlangıç evreleri umut vericiydi ama birçok ayrıntı açık kalmıştı.",
     "başlamak, girişmek", "yönelme eğilimi"),
    ("Birini yüksekçe öven resmi konuşma veya yazı.",
     "Tam teşekküllü, resmi bir övgü — parlak bir methiye veya başarıları çatıdan söyleyen bir nutuk düşünün.",
     "Emekli olan profesör, en yakın öğrencilerinden bir övgü söyleviyle uğurlandı.",
     "tümü", "toplantı, toplanma"),
    ("Soyut kuramın karşıtı olarak gerçek varlık veya olgusal oluşla ilgili.",
     "Şeylerin gerçekte nasıl var olduğu hakkında, yalnızca onlar hakkındaki fikir veya kuramlar değil.",
     "Filozoflar sayıların varlıksal bir statüsü olup olmadığını, yoksa yalnızca zihnimizde mi durduğunu tartışır.",
     "varlık, var olan", "ile ilgili"),
    ("Meyve vermek veya verimli olmak.",
     "Sonunda karşılığını almak — çaba, fikir veya yatırımın tohumdan yararlı bir şeye büyümesi.",
     "Yıllarca süren sessiz araştırma sonunda meyve verip çalışan bir aşıya dönüştü.",
     "meyve", "yapmak, neden olmak"),
    ("Bir şeyi gerçekten olmadan önce bitmiş gibi öngörmek veya göstermek.",
     "Edebi şekilde acele etmek — gelecek bir olayı sanki bitmiş gibi betimleyerek noktayı daha sert vurmak.",
     "Generalin \"zafer\" için peşinen kaldırdığı kadeh, savaştan tam bir hafta öncesineydi.",
     "önce", "almak, yakalamak"),
    ("Hava basıncıyla çalışan; ayrıca ruh veya solukla ilgili.",
     "Genellikle \"sıkıştırılmış havayla çalışan\" demektir — ruh veya solukla da ilgili olabilir.",
     "Otobüs kaldırıma yanaşınca havalı frenler tısladı.",
     "rüzgâr, soluk, ruh", "ait"),
    ("Tanrı'yı veya ilahî olanı olumlu önermelerle betimlemek — apofatikin karşıtı.",
     "Tanrı'nın ne olmadığını değil, ne olduğunu söyleyerek konuşmak — \"God is love\" gibi.",
     "Olumlayıcı teoloji Tanrı'dan seven, adil ve merhametli diye güvenle söz eder.",
     "aşağı, göre", "konuşmak, demek"),
    ("Güven veya imana dayalı; ayrıca sabit referans noktası olarak kullanılır.",
     "Güvenip sonra çapa yaptığınız şey — dayanak işareti, her şeyin ölçüldüğü sabit noktadır.",
     "Haritacılar sahayı çizmeden önce anakayaya bir dayanak işareti koydu.",
     "güvenmek", "güven, itimat"),
    ("Kötülüğün varlığı karşısında Tanrı'nın iyiliğinin savunusu.",
     "Eski soruyu yanıtlama denemesi: \"Tanrı iyiyse neden kötülük var?\"",
     "Tezi teodise konusunu Eyüp Kitabı merceğinden araştırdı.",
     "tanrı", "adalet"),
    ("Karşılıklı içte durma — Teslis kişilerinin birbirinin içinde var oluşuna dair teoloji terimi.",
     "Her parçanın diğerlerini tam içerdiği ve içerildiği üç-birlikte duruş için teoloji sözcüğü.",
     "Karşılıklı içkinlik öğretisi Baba, Oğul ve Ruh'un nasıl ayrı ama ayrılmaz olduğunu açıklamaya çalışır.",
     "çevresinde", "gitmek, yürümek"),
    ("Birine yarar sağlayan veya yansıyan sonuç doğurmak.",
     "Övgü (veya yergi) sorumluya geri sektiğinde — itibarınıza yazılan iyilikler dönüp sizi ödüllendirir.",
     "Takımın başarısı, sessiz ve çalışkan antrenörünün hanesine yazılacak.",
     "geri, yine", "dalga"),
    ("Kaçınılmaz veya kaçınılamaz.",
     "Ne yaparsanız yapın olacak — kaçınılmaz bir sonuçtan kıvırtarak çıkılmaz.",
     "Yaşlılık herkese gelir; bu yalnızca kaçınılmazdır.",
     "değil", "çıkmak için çabalamak"),
    ("Dolambaçlı, sözü uzatan anlatım kullanmak, dolaysız biçim yerine.",
     "Sözle uzun yol — \"decide\" demek yerine \"make a decision\" demek gibi.",
     "Onun dolambaçlı e-postaları üç paragrafta söylediğini bir satırda söyleyebilirdi.",
     "çevresinde", "bildirmek, anlatmak"),
    ("Zihinsel donukluk veya uyuşukluk.",
     "Düşünmenin şurupta yürümek gibi geldiği sisli, ağır zihin hali.",
     "Öğle yemeğinden hemen sonra sınıfa bir zihin uyuşukluğu dalgası çarptı.",
     "kör, küt", "durum veya nitelik"),
    ("Elverişsiz; uğursuz belirti.",
     "Kötü işaret — henüz başlamadan koşulların veya zamanlamanın aleyhinize çalışması.",
     "Gri gökyüzü ve ölü akü, yolculuğa uğursuz bir başlangıç yaptı.",
     "değil", "elverişli, lütufkâr"),
    ("Sosta haşlanmış veya kavrulmuş et — doğru yazımı \"fricasseed\".",
     "Kendi sosunda yavaşça pişirilip yumuşayana dek kesilmiş et için sıcak, eski bir mutfak sözü.",
     "Büyükannenin soslu haşlama tavuğu her Pazar akşam yemeğinin yıldızıydı.",
     "kızartmak", "kırmak (parçalara)"),
    ("Yapay veya daha düşük nitelikli yedek.",
     "Gerçeğin yerini tutan taklit — işi görür ama herkes asıl olmadığını bilir.",
     "Savaş zamanı alışverişçiler kavrulmuş hindibadan yapılan sahte kahveyle idare etti.",
     "dışarı, yerine koyma öneki", "koymak, yerleştirmek"),
    ("Soyut bir fikri somut bir şeymiş gibi ele almak.",
     "Fikri gerçek ve katı hissettirmek — \"the economy\" gibi bulanık bir şeyi işaret edilebilir nesneye çevirmek.",
     "Bir ulusun \"ruhunu\" kendi varlığı diye adlandırmak, aslında milyonlarca bireysel seçim olan şeyi şeyleştirir.",
     "şey", "yapmak"),
    ("Ustaca kaçtı veya savuşturdu.",
     "Temizce sıyrılmak — yakalanmayı, bir soruyu veya yanıtı kurnazca veya kıl payı savuşturmak.",
     "Yanıt saatlerce onu atlattı, ta ki duşta birden yerine oturana dek.",
     "dışarı, uzağa", "oynamak"),
    ("Kuşku, şaşkınlık veya çözülmemiş çelişki ifade eden.",
     "Düşüncenin gerçek bir çıkmazında — tembellikten değil, sorunun kendisi düzgün yanıtı reddettiği için.",
     "Sokrates diyaloglarını sıkça çıkmaza varan bir tonda bitirir, yanıttan çok soru bırakırdı.",
     "olmadan", "geçit, yol"),
    ("Bir şeyi ilişkili terimle adlandıran söz sanatı, örn. hükümdar için \"the crown\".",
     "Gerçek şeyin yerine ilişkili söz kullanmak — yönetimi kastederek \"the White House announced\" demek.",
     "\"Wall Street had a rough day\" bir ad aktarmasıdır — aslında borsa kötü gün geçirdi demektir.",
     "değişim, sonra", "ad"),
    ("Kökünden sökmek; doğal ortamından koparmak.",
     "Bir şeyi (veya birini) kökünden çekip ait olduğu yerden veya kültürden ayırmak.",
     "Savaş bütün bir kuşağı kökünden söktü, aileleri sınırların ötesine savurdu.",
     "uzağa, kopuk", "kök"),
    ("Kulağa hoş gelen.",
     "Sadece dinlemesi güzel — kulağa hoş gelen bir söz, ad ya da cümle neredeyse müzikal biçimde akar.",
     "\"Murmuring brook\" kulağa hoş gelen küçük bir öbek, yumuşak ve söylenmesi kolay.",
     "iyi, güzel", "ses, ün"),
    ("Genelde varsayılan veya öyle sanılan.",
     "Kanıtlanmasa da yaygınca doğru kabul edilen — \"supposed\" sürümü.",
     "Mektubun sözde yazarı sonradan tamamen yabancı çıktı.",
     "düşünmek, saymak", "niteliğine sahip"),
    ("Yeni uydurulmuş sözcük veya öbek.",
     "Yepyeni bir söz — taze icat, henüz (veya neredeyse) sözlükte yok.",
     "\"Doomscrolling\" yeni bir sözcük olarak başladı ve hızla gündelik argo oldu.",
     "yeni", "söz, konuşma"),
    ("Öfkeli veya huysuz.",
     "Kötü, sinirli bir ruh hali — bir zamanlar öfkeyi dalağın yönettiğine inanıldığı gibi çabuk patlar.",
     "E-postayı okuduktan saniyeler içinde öfkeli bir yanıt yolladı.",
     "dalak (öfke yeri)", "etkilenmiş"),
    ("Kibirli veya yapmacık biçimde ahlak dersi vermeye yatkın.",
     "Her cümle fal kurabiyesiymiş gibi kendini beğenmiş hayat dersleri dağıtmayı sever.",
     "\"Dostluğun gerçek anlamı\" üzerine ahkâm kesen kadeh konuşması herkesin saatine bakmasına yol açtı.",
     "görüş, vecize", "dolu"),
    ("Özellikle önemsiz şeyler hakkında aşırı konuşkan.",
     "Sohbeti kesmez — başkaları sözü tükettikten çok sonra da küçük şeyleri gevezelik eder.",
     "Geveze taksi şoförü havaalanından çıkmadan önce bütün hayatını anlattı.",
     "gevezelik etmek", "eğilimli"),
    ("Aptallık, saçmalık.",
     "Düz aptallık — ciddi yanıtı hak etmeyecek kadar saçma bir yorum veya plan.",
     "Planın düpedüz ahmaklığı denedikleri anda ortaya çıktı.",
     "aptal, saçma", "olma hali"),
    ("Konuşmanın kapanış bölümü, çoğu kez özetler.",
     "Nutkun büyük finali — konuşmacının her şeyi toplayıp noktayı çaktığı kapanış.",
     "Bitiriş bölümüne gelindiğinde dinleyicinin yarısı ayağa kalkmıştı.",
     "boyunca, sonuna dek", "konuşmak, savunmak"),
    ("Aynı fikrin farklı sözcüklerle gereksiz tekrarı.",
     "Yeni bir şey katmadan aynı şeyi iki kez söylemek — \"free gift\" veya \"end result\" gibi.",
     "\"It is what it is\" gerçek açıklamadan kaçınanların sevdiği bir totolojidir.",
     "aynı", "söz, konuşma"),
    ("Çok az sözcük kullanma; kısa konuşma.",
     "Çok azla çok söylemek — Laconia Spartalılarının ünlü kısalığından adını alan kısa, sert yanıt sanatı.",
     "\"Molon labe\" — \"gelin ve alın\" — tarihin en ünlü lakonik sözüdür.",
     "Laconia'lı bir Spartalı", "alışkı, tarz"),
    ("Yavan, aşırı basitleştirilmiş fikirler; aslen yavan yiyecek veya lapa.",
     "Sulandırılmış düşünce — zihin için besin değeri kalmayacak kadar basitleştirilmiş, güvenli içerik.",
     "Politikacının konuşması çoğunlukla yavan sözlerdi: tutturacak bir şey olmayan belirsiz vaatler.",
     "beslemek", "araç veya aygıt"),
    ("Uyku veya uyuşukluk veren.",
     "Sıkıcı — veya sözcük anlamıyla sakinleştirici — olacak kadar uykuya çeker. Ilık süt veya üç saatlik bütçe toplantısı düşünün.",
     "Dersin uyutucu uğultusu odanın yarısını gözünü açık tutmaya zorladı.",
     "derin uyku", "yapmak, neden olmak"),
    ("Aşırı pohpohlayıcı veya yağlı tavırlı.",
     "Kaygan gelecek kadar pürüzsüz çekici — yağlılığı neredeyse hissedilecek kadar kalın pohpohlama.",
     "Yağcı satıcı her ek satıştan önce \"mükemmel zevkimi\" övmeye devam etti.",
     "yağ sürmek, mesh etmek", "dolu"),
    ("Kusur aramaya hızlı, önemsiz şeylere aşırı eleştirel.",
     "Kılı kırk yarmaya varan — gerçekten önemi yokken her şeyde sorun bulan kişi.",
     "Rapordaki kusur arayan notları tamamen virgül yerine odaklanmıştı.",
     "yakalamak, almak", "tuzak, safsata"),
    ("Ağır, zihinsel veya bedensel olarak eylemsiz.",
     "Kış uykusundaki ayı gibi yavaş ve yarı uykulu — neredeyse kıpırdamaz, neredeyse düşünmez.",
     "Ağustos'un ağır sıcağında ofis uyuşukluğa düştü.",
     "uyuşmak, ağırlaşmak", "durumunda"),
    ("Ortaçağ hanesini yöneten kâhya veya görevli.",
     "Ortaçağ versiyonu bir personel şefi — lordun evini ve malikânesini günlük yürüten güvenilir görevli.",
     "Şatonun kâhyası hasat defterinden konuk listesine her şeyi yönetirdi.",
     "yaşlı, kıdemli", "hizmetkâr"),
    ("Bir konuda uzun uzun konuşmak veya yazmak.",
     "Konuya gerçekten dalmak — her açıdan durmaksızın konuşmak veya yazmak.",
     "Ona klasik arabaları sorun, dosdoğru bir saat uzun uzadıya anlatır.",
     "dışarı", "uzay"),
    ("Değersiz, önemsiz; ayrıca geçersiz veya etkisiz.",
     "Temelde hiçbir değeri yok — sözleşmedeki hükümsüz madde aslında hiçbir şey yapmaz.",
     "Mahkeme eski tüzüğü hükümsüz saydı, çünkü hiç uygulanmamıştı.",
     "ıvır zıvır, saçma", "ait"),
    ("Bilgelik, keskin yargı.",
     "Keskin, pratik bilgelik — yalnızca kitaptan değil deneyimden gelen iyi yargı.",
     "Yaşlı kaptanın sağgörüsü mürettebatı birden fazla kez beladan korudu.",
     "keskin kokulu, zeki", "niteliği"),
    ("Aşağılayarak kullanılan avam veya kitle.",
     "\"Ayak takımı\" veya sıradan insanlar için kibirli, küçümseyici söz.",
     "Kont, saray kapısının dışında toplanan ayaktakımına hor baktı.",
     "köpek", "topluluk, sürü"),
    ("Küstah, aşağılayıcı muamele veya dil.",
     "Utandırmak için tasarlanmış zalim, hor muamele — acıtsın diye kurulmuş hakaret.",
     "Eseri tanınmadan önce eleştirmenlerden yıllarca aşağılama çekti.",
     "ile, kökten", "kabarmak (gururla)"),
    ("Şüphe veya onaylamama ile; yan bakış.",
     "Pek güvenmediğiniz şeye attığınız yan bakış — kuşku dolu bir bakış.",
     "Öğretmen şüpheli derecede temiz ödeve yan gözle baktı.",
     "e, doğru", "eğik, yanlı"),
    ("Aptal kişi; küt kafa.",
     "Biraz kalın kafalı biri için eski usul, neredeyse sevecen hakaret — küt kafa.",
     "\"Seni mankafa,\" güldü, \"harita bunca zamandır ters duruyordu.\"",
     "toprak parçası", "kafa"),
    ("Harekete veya eyleme geçirmek; güdülemek.",
     "Bir şeyi harekete geçiren kıvılcım olmak — makinenin açılması veya kişinin nihayet fikir üzerine eyleme geçmesi.",
     "Sözleşmeyi kaybetme korkusu bütün ekibi harekete geçirip hafta sonu mesaisine soktu.",
     "yapma, sürme", "sürmek, yapmak"),
    ("Emanet edilen fonların zimmete geçirilmesi.",
     "Size emanet edilen parayı sessizce çalmak — eski bir palto giymiş zimmet.",
     "Veznedarın zimmeti neredeyse on yıl fark edilmedi.",
     "özel mülk", "sığır, servet"),
    ("Saygın toplumun kenarında görülen grup.",
     "Gösterişli ama karanlık sosyal yeraltı — \"saygın\" toplum kurallarının hemen dışında yaşayanlar.",
     "Roman, 1920'ler kabarelerinin yarı âleminde yolunu bulan bir şarkıcıyı izler.",
     "yarı", "dünya, toplum"),
    ("Hâlâ var olan; soyu tükenmemiş veya yok edilmemiş.",
     "Bugün hâlâ duran — hayatta kalmayı başarmış eski şeyler (elyazması, tür, yapı) için.",
     "İlk baskının günümüze ulaşan yalnızca üç kopyası biliniyor.",
     "dışarı", "durmak"),
    ("Aldatma; güven ihaneti.",
     "Derin, kasıtlı ihanet — birinin haklı olarak beklediği güveni kırmak.",
     "General, müzakere masasındaki eski dostunun ihanetini asla bağışlamadı.",
     "içinden, karşı", "iman, güven"),
    ("Bölgesel ağız, özellikle standart olmayan.",
     "Belirli bir yörede insanların kendine özgü konuşma biçimi — yabancının yakalayamayacağı söz ve ritimlerle dolu.",
     "Büyükannesi aile yemeklerinde hâlâ adanın yerel ağzını konuşurdu.",
     "kaba konuşma, ağız", "pençe — beceriksiz konuşma"),
    ("Bir kişiye veya gruba ait özel hak.",
     "Yalnızca sizin olan ayrıcalık — rol, konum veya statüyle gelen hak.",
     "Ailenin tatil yerini seçmek dedenin ayrıcalığıdır, herkes bunu bilir.",
     "önce", "sormak, oy vermek"),
    ("Cesaret, cüret; ayrıca dayanıklılık veya tahammül.",
     "Kaba, yürekli direnç — ileri gitme cesareti ve gittikten sonra sürme sertliği.",
     "Haritasız kar fırtınasında geçidi aşmak gerçek yüreklilik isterdi.",
     "cesur, dayanıklı", "hal, durum"),
    ("Çiçek açmak; ayrıca gelişmek veya giderek belirmek.",
     "Tam ifadeye açılmak — çiçek gibi, veya bir fikrin sonunda kendisi olması gibi.",
     "Resimdeki sessiz yeteneği kendi atölyesi olunca serpildi.",
     "dışarı", "çiçek açmaya başlamak"),
    ("Düşeyliği belirlemek için ağırlıklı ip; mecazen yargı ölçütü.",
     "Dosdoğru aşağı sarkan ağırlıklı ip, gerçekten dikey mi diye bakmak için — ve uzantısıyla her şeyi ölçtüğünüz sabit ölçüt.",
     "Kendi dedesinin dürüstlüğünü her karar için bir tür çekül yaptı.",
     "kurşun", "ip, ölçü"),
    ("Seve seve, isteyerek (eski).",
     "\"Seve seve\" veya \"memnuniyetle\" demenin eski yolu.",
     "\"Burada bir süre dinlenmeyi pek isterdim,\" diye iç çekti yolcu.",
     "sevinçli, neşeli", "seve seve, isteyerek"),
    ("Sert kamusal eleştiri veya rezalet.",
     "Birinin üzerine büyük, görünür biçimde yığılan kamusal utanç — yaygın onaylamamadan gelen rezalet.",
     "Skandal bütün firmanın üzerine kamusal bir ayıplama yağdırdı.",
     "karşı", "rezalet, kınama"),
    ("Keskin alaycı, zekâ veya eleştiride ısırıcı.",
     "Dişi olan zekâ — iğneleyici bir yorum tam da nişanı iyi olduğu için biraz acıtır.",
     "Onun iğneleyici film eleştirileri yönetmenlerce korkulur, okurlarca sevilirdi.",
     "ısırmak", "ısıran, yapan"),
    ("Resmi bildiri, çoğu kez siyasal veya askerî.",
     "Büyük, resmi duyuru — genellikle yeni hükümet, ayaklanma veya büyük kararname ilan eder.",
     "Generalin askerî bildirisi şafakta yeni hükümeti duyurdu.",
     "ileri", "duyurmak"),
    ("Yüzeysel bilgisi olup uzmanmış gibi yapan kişi.",
     "Konunun yüzeyini sıyırıp sonra ders kitabını yazmış gibi konuşan kişi.",
     "Akşam yemeğindeki çokbilmiş, masadaki gerçek astrofizikçiyi kendinden emin düzeltti.",
     "bilmek", "küçültme — küçük bilen"),
    ("Yaşlılıkta zihinsel yetilerin gerilemesi.",
     "Zihin keskinliğinin solmaya başladığı çok yaşlılığın sisli, unutkan dönemi.",
     "Bunaklık döneminde her ziyarette aynı üç öyküyü anlatırdı, her seferinde yeniymiş gibi.",
     "bunamak, aptallaşmak", "hal veya sonuç"),
    ("Rüzgârdan korunmuş yan.",
     "Tepenin, geminin, duvarın rüzgârın pek ulaşamadığı sakin, korunaklı yanı.",
     "Yürüyüşçüler rüzgârı kaçırmak için sırtın rüzgâraltı yanına çadır kurdu.",
     "sığınak, koruma", "yan, yüz"),
    ("Bir darbeyi, soruyu veya savı savuşturmak.",
     "Ritmi kaçırmadan pürüzsüz savuşturmak — kılıç darbesi, sıkıntılı soru veya suçlama.",
     "Muhabirin çetrefil sorusunu kolay bir şakayla savuşturdu.",
     "savuşturmak", "hazırlamak, savunmak"),
    ("Kötü kokulu, zararlı.",
     "Neredeyse zehirli gelen koku — solumak tehlikeli gelecek kadar kötü koku.",
     "Güneş batınca bataklıktan pis kokulu bir buğu yükseldi.",
     "zararlı buhar", "niteliğine sahip"),
    ("Lüks ve zevke adanmış kişi.",
     "Konfor ve şımartma için yaşayan — güzel yemek, yumuşak yatak, kolay hayat — aşırılığıyla ünlü antik Yunan kenti Sybaris'ten.",
     "Gerçek bir sefa düşkünü olarak küvetsiz otel odasını reddetti.",
     "lüksüyle ünlü antik Yunan kenti", "sakini"),
    ("Bir parçayı kasıtlı olarak bir yana koymak veya yok saymak.",
     "Bulmacanın bir parçasını kasten zihinde kenara koyup gerisine temiz odaklanmak.",
     "Maliyeti bir an bir yana bırakalım ve planın gerçekten işleyip işlemediğini soralım.",
     "önce, uzağa", "kesmek"),
    ("Şiddetle eleştirmek; ayrıca derisini soymak.",
     "Sert eleştiriyle birini parçalamak — sözle, sanki gerçekten derisini soyuyormuş gibi.",
     "Eleştirmenler devam filmini, aslın hayranlarının sevdiği her şeye ihanet ettiği için yerden yere vurdu.",
     "kopuk", "deri, post"),
    ("Kanıt veya delil olarak göstermek.",
     "Noktanızı destekleyecek olgu veya örnek öne sürmek — biri \"what's your evidence?\" diye sorunca işaret ettiğiniz şey.",
     "Avukat müvekkilinin mazeretini desteklemek için üç tanık gösterdi.",
     "e, doğru", "yöneltmek"),
    ("Yolculuklar veya dolaşmalar, özellikle uzun ve geniş olanlar.",
     "Uzun, dolaşan yolculuklar — sizi evden uzun süre uzağa götüren geniş gezinti.",
     "Üç kıtadaki gezip dolaşmaları bir raf dolusu seyahat günlüğünü doldurdu.",
     "içinden", "tarla, toprak (peregrinus: yabancı)"),
    ("Dilenci, veya sadakayla yaşayan.",
     "Hayır dilenerek yaşayan — tarihte yoksulluk yemini edip bağışla yaşayan keşişleri de anlatırdı.",
     "Dilenci keşişler hiçbir şeye sahip değildi ve tamamen köylülerin iyiliğine bel bağlardı.",
     "dilenmek", "dilenci"),
    ("Son derece cömert.",
     "Neredeyse gösterişli ölçekte cömert — insanları biraz nefesini tutturan armağan.",
     "Cömert bağış kütüphanenin bütün yeni kanadını finanse etti.",
     "armağan, hizmet", "yapmak, vermek"),
    ("Besin yokluğundan tükenme; ayrıca canlılık yokluğu.",
     "Beslenmemiş veya yakıtsız kalmaktan zayıf, tükenmiş hal — sözcük anlamıyla açlıktan, mecazen koşacak bir şey kalmamasından.",
     "Kuşatma sonunda askerler bitkinlik eşiğindeydi.",
     "boş, yok", "eylem veya sonuç"),
    ("Acı, küfürlü eleştiri.",
     "Adilin çok ötesine geçip öfkeli, acı bir nutka dönmüş eleştiri.",
     "Çevrimiçi yorumlar dakikalar içinde saf sövgüye dönüştü.",
     "kusur", "hazırlamak, sağlamak"),
    ("Düşmanca, etkisi zararlı.",
     "Sessizce bile size karşı çalışan — çıkarlarınıza dost olmayan koşullar veya tutumlar.",
     "Yeni politika, niyet o olmasa da küçük işletmelere zararlıydı.",
     "değil", "dost"),
    ("Çoğu kez haksız karşılaştırmalarla kin veya hoşnutsuzluk uyandırmaya yatkın.",
     "Birini küçümsenmiş hissettirmeye mahkûm — genellikle insanları veya şeyleri haksız yığdığı için.",
     "Kardeşleri \"Anne kimi en çok seviyor\" diye sıralamak kimsenin oynamaması gereken gücendirici bir oyundur.",
     "kıskançlık", "(kötü niyetle) bakmak"),
    ("Daha düşük rütbe veya statüdeki kişi; ast.",
     "Komuta zincirinde veya toplumsal merdivende daha aşağıda olan — daha güçlü birinin altında çalışan genç.",
     "Genç bir ast subay olarak emir vermeden çok önce emir aldı.",
     "altında", "yedek, diğer"),
    ("Güçlü nefret duymak veya dile getirmek.",
     "Yüksek sesle lanetleyecek kadar tiksinmek — saf, sesli nefret.",
     "Köylüler vergi tahsildarının arabası her geçtiğinde onu lanetledi.",
     "dışına", "kutsal (kutsaldan dışarı lanetlemek)"),
    ("Deri veya kabuk gibi doğal dış örtü.",
     "Doğanın kendi koruyucu paketi — deri, kabuk, kavuz veya kabuk, canlıyı örten ve koruyan ne varsa.",
     "Kaplumbağa kabuğu son derece sağlam bir dış örtüdür.",
     "üzerinde, örten", "örtmek"),
    ("Masum, naif, çocuksu yalınlık gösteren; \"disingenuous\"in karşıtı.",
     "Açıkça güvenen ve biraz naif, gizli gündemsiz — \"clever\" anlamına gelen \"ingenious\" ile karıştırılması kolay.",
     "Onun saf sorusu — \"neden biri bunun hakkında yalan söylesin?\" — ne kadar az hileli olduğunu gösterdi.",
     "içinde, yerli", "doğurmak (özgür doğmuş, açık)"),
    ("Küçük ayrıntılara veya kurallara aşırı düşkünlük.",
     "Büyük resmi kaçırıp küçük kurallarda kaybolmak — kimsenin umursamadığı ince yazıya saplanmak.",
     "Oxford virgülü üzerine bilgiçliği bütün toplantıyı rayından çıkardı.",
     "çocukların öğretmeni", "alışkı veya nitelik"),
    ("İnce, dikkatli inceleme.",
     "Taş bırakmayan derin bakış — her ayrıntıyı gerçek özenle tarama.",
     "Defterlerin dikkatli ve ayrıntılı incelenmesinden sonra tutarsızlık ortaya çıktı.",
     "içinden, kökten", "aramak, incelemek"),
    ("İtiraz yükseltmek; isteksizlik göstermek.",
     "Hemen uymak yerine nazikçe geri itmek veya tereddüt — yumuşak \"I'd rather not\".",
     "Okumadan imzalaması istenince çekindi.",
     "den, uzağa", "geciktirmek"),
    ("Yüzeyde inandırıcı görünen ama aslında yanlış.",
     "İlk bakışta ikna edici durur, gerçekten kontrol edince çöker.",
     "\"Everyone's doing it\" inceleme altında asla durmayan aldatıcı bir savdır.",
     "görünüş, bakış", "dolu (güzel görünen)"),
    ("Samimiyetsiz, ikiyüzlü konuşma, çoğu kez ahlakçı.",
     "Erdemli duran ama gerçek duyguyla desteklenmeyen vaaz — otomatik ahlak pozu.",
     "Kimseye izin vermeyen bir şirketin \"aile\" üzerine kurumsal riyakâr söyleminden bıkmıştı.",
     "şarkı söylemek (sonra: tekdüze jargon)", "dilencilerin sızlanması, sonra ikiyüzlülük"),
    ("Cesaretten yoksun, korkak.",
     "Omurgasızlığa varan ürkek — açıkça önemliyken bile ayağa kalkamayacak kadar korkak.",
     "Kurulun korkak sessizliği skandalın kontrolden çıkmasına yol açtı.",
     "çok küçük", "ruh, cesaret"),
    ("Tilki gibi; kurnaz, açıkgöz.",
     "Tilki gibi kurnaz ve zeki — çabuk zekâlı, biraz sinsi, hep bir adım önde.",
     "Boşluğu görür görmez tilki gibi bir sırıtış verdi.",
     "tilki", "ait veya gibi"),
    ("Birbiri ardına, sırayla.",
     "Sıkı sıkıya birer birer, sırayla ele almak — atlama yok, iki birden yok.",
     "Yargıç on iki talebin her birini sırayla ele aldı.",
     "sıra, dizi", "birer birer"),
    ("Aşırı tutumluluk; cimrilik.",
     "Parayı (veya sözü, kaynağı) makul tutumluluğun ötesinde sıkmak.",
     "Onun cimriliği efsaneydi — çay poşetini üç kez kullandı.",
     "esirgemek, tutumlu olmak", "hal veya alışkı"),
    ("Düzeltme, özellikle metinde.",
     "Bir yazıya yapılan onarım — eski veya önemli bir metindeki hatayı düzelten akademik dokunuş.",
     "Yeni baskı özgün elyazmasına onlarca düzelti içerir.",
     "dışına", "kusur, hata"),
    ("Yeme içmede ölçülü.",
     "Yiyecek ve içecek çevresinde kasıtlı çekingen — asla aşırıya kaçmaz, tabakta biraz bırakır.",
     "Ölçülü alışkanlıkları, yaşıtları yavaşladıktan sonra da onu uzun süre keskin tuttu.",
     "uzağında", "sarhoş edici içki"),
    ("Dilbilgisi hatası veya görgü kuralı ihlali.",
     "Dilbilgisi veya görgüde küçük sürçme — kılı kırk yaranı ürperten türden hata.",
     "\"Between you and I\" dilbilgicileri hâlâ irkilten yaygın bir dil yanlışıdır.",
     "kötü Yunancasıyla bilinen Kilikya kenti", "alışkı, tarz"),
    ("Grup içi çatışmayla ilgili; karşılıklı yıkıcı.",
     "Grubu içeriden parçalayan iç kavga — herkesin kaybettiği, çünkü aile aileye karşı.",
     "Partinin kendi içindeki çekişmesi dışarıdaki herhangi bir rakibin vereceğinden çok zarar verdi.",
     "arasında, içinde", "öldürmek"),
    ("Kayıtsız, umursamaz tutum.",
     "Omuz silkmenin bütün bir kişiliğe dönüşmesi — eskiden önemli olanlara o kadar az aldırır ki hiçbir şey çabaya değmez.",
     "Ödül törenine kayıtsız tutumu, ne kadar çok çalıştığını bilen herkesi şaşırttı.",
     "az", "aldırmak"),
    ("Karışık, karmaşık durum veya uyuşmazlık.",
     "Anlaması zor dolaşık, dağınık durum — bir kısmı yanlış anlama, bir kısmı drama, hepsi kargaşa.",
     "Bütün oturma planı karmaşası yanlış konmuş bir isim kartıyla başladı.",
     "içinde", "dolaştırmak, karıştırmak"),
    ("Tehditkâr, korkutucu.",
     "Yanıltmaz bir tehdit havası taşıyan — tehditkâr bakış veya mektup ardından kötü bir şey gelebileceğini çok açık eder.",
     "Mektubun tehditkâr tonu kiracıyı zarfı açmadan tedirgin etti.",
     "tehdit etmek", "işine yarayan"),
    ("Güçlü kamusal eleştiri veya sözlü sövme.",
     "Yüksek sesli kamusal kınama — herkesin önünde oynanan yakıcı eleştiri.",
     "İhbarcı, tarih onu haklı çıkarmadan önce yıllarca kamusal karalamayla yüzleşti.",
     "karşı", "konuşmak"),
    ("Duygu veya eylemde ani şiddetli patlama.",
     "Bir anda sizi yutan ani, yoğun patlama — gülme, öfke veya öksürük nöbeti dalga gibi gelir.",
     "Odadaki kimseye açıklayamayacağı bir gülme nöbetine yakalandı.",
     "öte", "keskin, akut"),
    ("Dış kaynaktan eklenen, içkin olmayan.",
     "Baştan inşa edilmek yerine dışarıdan vidalanmış — ekstra, çekirdek değil.",
     "Yorum sonradan eklenmiş geliyor, sanki bitmiş bir metne yapıştırılmış.",
     "e, ayrıca", "onaylamak, üstlenmek"),
    ("Bilgi yokluğu, cehalet.",
     "Yalın bilmeme — yargı eklenmemiş bilgi boşluğu.",
     "Fransız şarabı konusundaki bilgisizliğini kabul etti ve seçimi sommeliere bıraktı.",
     "değil", "bilmek"),
    ("Cinsel konulara aşırı ilgi.",
     "Müstehcen her şeye fazla hevesli, süzülen bir merak — sağlıklıyı geçip burnunu sokmaya dönmüş ilgi.",
     "Magazinin çiftin özel hayatına duyduğu şehvetli merak saplantıya yakındı.",
     "kaşınmak, özlemek", "hal"),
    ("İsli, karanlık, bulanık.",
     "Karanlık ve dumanlı görünümlü, her şeyin ince is tabakasıyla kaplı gibi.",
     "Alacakaranlıkta fabrika kasabasının üstünde isli bir pus asılıydı.",
     "is", "dolu"),
    ("Yadsımak veya çelişmek.",
     "Başkasının söylediğine kesin karşı konuşmak — \"that's not so\" demek.",
     "Kimse yaşlı kaptanın fırtına anlatısını yalanlamaya cesaret edemedi.",
     "karşı", "konuşmak"),
    ("Tembellik, üşengeçlik (Latinceden).",
     "Saf tembellik için eski bir Latince söz — hiçbir şey yapmak istememenin çekişi.",
     "Keşişler tembelliği ruhun sessiz tehlikelerinden biri diye vaaz etti.",
     "değil", "meşgul, çalışkan"),
    ("Armayı gösteren kalkan.",
     "Ailenin armasını gösteren kalkan biçimli amblem — heraldik \"isim levhası\".",
     "Ailenin arma kalkanı hâlâ eski malikânenin ön kapısının üstünde asılı.",
     "kalkan", "küçültme / nesne"),
    ("Eskimiş, geçersiz veya yaştan emekli.",
     "Yararlı zirvesini geçmiş ve meraya çıkarılmış — işi sürdürmek için fazla eski moda veya yıpranmış.",
     "Eskimiş yazıcı on beş yıllık kâğıt sıkışmasından sonra nihayet değiştirildi.",
     "öte", "yıl"),
    ("Yedekler, özellikle tıpta.",
     "Asıl tedavi yokken kullanılan yedek ilaçlar — esasen tıbbi yedek oyuncu.",
     "Savaş doktorları uygun ilaçlar bitince sıkça ikame ilaçlara bel bağlardı.",
     "yerine", "gitmek, boyun eğmek"),
    ("Övüngen, palavracı konuşma.",
     "Büyük, palavracı övünme — kendi büyüklüğü hakkında çoğu hava olan yüksek ses.",
     "Projeyi \"tek başına\" kurtardığına dair palavrası orada gerçekten bulunan kimseyi kandırmadı.",
     "Orlando Furioso'daki övüngen şövalye", "eylem, gösteriş"),
    ("Bir şeye hile veya aldatmayla ulaşmak.",
     "Adil oyun yerine sinsi triklerle hedefe kıvırarak varmak.",
     "İnce yazıyla dolu bir sözleşmeyle anlaşmaya hileyle sızdı.",
     "kılı kırk yarmak, aldatmak", "hile; sonra keskin viraj"),
    ("Öğrenme veya bilginin salt veya soyut bilimi, çoğu kez matematik.",
     "En salt, en soyut haliyle öğrenme — bilginin kendisinin derin yapısı, özellikle matematiksel türü.",
     "Filozof her bilgi alanını birleştirecek evrensel bir mathesis düşledi.",
     "öğrenmek", "öğrenme eylemi"),
    ("Biçimsel kurallara veya önemsiz ayrıntıya aşırı düşkün.",
     "Küçük şeylerde fazla katı — aslında hiçbir şeyi değiştirmeyen teknik ayrıntıları düzeltmek.",
     "Bir metin iletisinde \"who\" ile \"whom\" tartışmak biraz bilgiçlik geldi.",
     "çocuk kılavuzu, öğretmen", "tavrına sahip"),
    ("Parıldayan, kıvılcımlanan ışık.",
     "Hızlı, parıldayan bir ışık çakması — suda sıçrayan güneş veya ışığı yakalayan elmas düşünün.",
     "Avizenin parıltısı balo salonunun her köşesine ışık saçtı.",
     "parıldamak, çakmak", "o eylem"),
    ("Acemi, çömez.",
     "Bir beceri veya alana yepyeni biri — hâlâ ipin ucunu öğreniyor, henüz uzman değil.",
     "Acemi bir satranç oyuncusu bile o gafı görür.",
     "acemi er, çömez", "ham genç asker"),
    ("Son derece kötü, iğrenç.",
     "Gerçek tiksinti hak edecek kadar kötü — yalnızca \"orta\" değil, gerçekten iğrenç.",
     "Eleştirmen devamı berbat diye niteledi, gişe rakamları da katıldı.",
     "lanetlemek", "değer, olabilir"),
    ("Kan kırmızısı renkte.",
     "Derin, canlı kırmızı — taze kan rengi, Shakespeare'in Macbeth'iyle ünlü.",
     "Günbatımı bütün gökyüzünü kan kırmızısı bir ışıltıya çevirdi.",
     "içine", "et (et kırmızısı)"),
    ("Şeyler arasındaki küçük boşluk.",
     "Gözden kaçması kolay ara boşluk — döşeme tahtası çatlağı, programdaki ara.",
     "Eski tuğla yoldaki her aralıktan otlar fışkırdı.",
     "arasında", "durmak"),
    ("Eleştirel veya kınayıcı sözler.",
     "Keskin, onaylamayan yorumlar — azar tonu taşıyan türden eleştiri.",
     "Profesörün deneme üzerine sitemleri kenarları kırmızı mürekkeple doldurdu.",
     "zihin", "doğru dönmek"),
    ("Çürütülemez, yadsınamaz.",
     "Öyle sağlam kanıtlanmış ki tartışılacak bir şey yok — dava kapanmıştır.",
     "DNA kanıtı çürütülemezdi ve duruşma bir saat içinde bitti.",
     "değil", "karşı çıkmak, direnmek"),
    ("Karmaşıklık, dolambaç; ayrıca içe kıvrılma.",
     "Kendi içine katlanmış, çözülmesi zor karmaşıklık — o kadar sıkı sarılmış ki ayırmak zor.",
     "Konunun giriftliği seyircinin yarısını jenerikten sonra çözmeye bırakmıştı.",
     "içe, içeri", "sarmak, döndürmek"),
    ("Güç veya çaba, \"by dint of\" deyiminde olduğu gibi.",
     "Salt çaba veya güç — bugün çoğunlukla \"by dint of\" deyiminde yaşar.",
     "Sınavı salt inatçı çalışmanın gücüyle geçti.",
     "darbe, vuruş", "gücüyle"),
    ("Zıvana-geçme eklemiyle birleştirilmiş; sıkı oturtulmuş.",
     "Eski usul marangoz yolunda kilitlenmiş — bir parça tam kendisi için kesilmiş deliğe sıkı oturur.",
     "Eski ahırın kirişleri tek çivi olmadan zıvanayla birleşmişti.",
     "yuvası, delik", "ısırık, tutuş"),
    ("Son derece ilgili, yerinde.",
     "O ana tam oturan — noktaya kusursuz düşen yorum, alıntı veya örnek.",
     "Onun yerinde sözü bütün tartışmayı bir cümlede toparladı.",
     "e", "koymak"),
    ("Yumuşakça parlayan veya titreyen (ışık); ayrıca hafif zekâ.",
     "Yanmak yerine nazikçe parlamak — yumuşak titreşen ışık, veya keskin değil oyuncu zekâ.",
     "Mum ışığı eski yemek odasına titrek bir ışıltı düşürdü.",
     "yalama", "yapmak ('yalayan' ışık)"),
    ("Yalnızlıkta yaşayan dinsel münzevi.",
     "Dua ve tefekkürle yalnız yaşamak için dünyadan tamamen çekilen kişi.",
     "Münzevi otuz yılı aşkın kiliseye bitişik küçük bir hücrede yaşadı.",
     "geri, uzağa", "çekilmek"),
    ("Susuzluğu gidermek; yatıştırmak.",
     "Bir özlemi tamamen doyurmak — çoğu kez susuzluk, mecazen her derin istek veya ihtiyaç.",
     "Uzun yürüyüşten sonra bir bardak soğuk su susuzluğunu giderdi.",
     "gevşek, boş", "gevşetmek, yatıştırmak"),
    ("İğne biçiminde.",
     "Uzun, ince ve iğne gibi sivri — çam iğnesi veya keskin küçük kristal biçimi.",
     "Çamlar iğne yapraklarıyla kolay tanınır.",
     "iğne", "küçük"),
    ("Canlılığı tükenmiş, zayıf, aşırı incelmiş.",
     "Eskimiş ve yumuşak — fazla konfor veya incelikten öz gücünü ve coşkusunu yitirmiş.",
     "Eleştirmenler bir zamanlar cesur dergiyi gücünü yitirmiş, erken yıllarının gölgesi diye niteledi.",
     "dışarı", "verimli, doğurmuş"),
    ("Eklenti veya küçük bağlı hak.",
     "Daha büyüğüne yapışık gelen küçük ekstra — asıl şeye ait aksesuar ve ekler.",
     "Kira, garajı ve bütün eklentilerini kapsıyordu.",
     "e", "ait olmak"),
    ("Bir kusuru örtmek veya küçültmek.",
     "Yumuşak sözlerle hatayı düzleştirmek, gerçekten küçükmüş gibi göstermek.",
     "Kaçırılan teslim tarihini \"öngörülemeyen zorluklar\" üzerine belirsiz sözlerle geçiştirmeye çalıştı.",
     "dipnot, açıklama", "yorumlamak — sonra örtmek"),
    ("Erken evrede, yeni başlayan.",
     "Yeni yeni belirmeye başlayan — daha büyük bir şeyin ilk, neredeyse görünmez evresi.",
     "Doktorlar hastalık yayılmadan başlangıç belirtilerini yakaladı.",
     "üzerinde, içine", "almak (kaldırmak, başlamak)"),
    ("Yaratıcı esin, özellikle ilahî.",
     "Sizden büyük gelen ani esin — fikir başka bir yerden size üflenmiş gibi.",
     "Şair bütün parçanın gece 3'te bir esin patlamasıyla geldiğini anlattı.",
     "e, üzerine", "üflemek (üzerine üfleme)"),
]
