# Estonian rows
ROWS = [
    ("Magustada või puhastada; eemaldada millegi karedus.",
     "Võtta millegi torge või kibedus — sõna-sõnalt magustades või ülekantud tähenduses pehmendades karmi ideed, et see paremini alla läheks.",
     "Toimetaja pehmendas karmi arvustuse enne, kui see trükki läks.",
     "välja, põhjalikult", "magus"),
    ("Liiga või teeseldult usklik või vaga.",
     "Kirjeldab kedagi, kelle usuline pühendumus tundub näitemänguna — rohkem etendus kui ehtne usk.",
     "Tema pietistlikud ohked jutluse ajal ärritasid ülejäänud pingirida.",
     "vagadus, kohusetunne", "mille iseloom on"),
    ("Grammatilisest struktuurist tekkiv kahemõttelisus — lause, mida saab kahel moel lugeda.",
     "Lause, mis on grammatiliselt korras, kuid mida saab lugeda kahel täiesti erineval moel, nagu \"I saw the man with the telescope.\"",
     "\"Visiting relatives can be tiring\" on klassikaline amfibolia — kas sugulased on väsitavad või on väsitav neid külastada?",
     "mõlemad, mõlemalt poolt", "viskama"),
    ("Terav, tabav, lõikab otse asja juurde.",
     "Lõikab otse täidise läbi — terav märkus või mõistus jõuab asja tuumani kiiresti, ilma tarbetute sõnadeta.",
     "Tema terav kriitika ei jätnud filmi süžeelünkadele peidupaika.",
     "lõikama", "tegev, mille omadus on"),
    ("Alles alguses; varajases või algelises staadiumis.",
     "Ikka veel avamishetkedes — plaan, tunne või protsess, mis on alles hakanud kuju võtma.",
     "Lepingu algusjärgud olid paljulubavad, kuid paljud üksikasjad olid veel lahtised.",
     "alustama, käivitama", "mis kaldub poole"),
    ("Formaalne kõne või kirjutis, mis kedagi kõrgelt kiidab.",
     "Täiemahuline, formaalne austusavaldus — mõtle säravale mälestuskõnele või kõnele, mis laulab kellegi saavutusi katustelt.",
     "Lahkuv professor saadeti teele kiidukõnega oma lähimatelt üliõpilastelt.",
     "kõik", "kogu, kogunemine"),
    ("Puudutab tegelikku olemasolu või faktilist olemist, vastandina abstraktsele teooriale.",
     "Asjadest nii, nagu need tegelikult olemas on, mitte ainult ideede või teooriatena nende kohta.",
     "Filosoofid vaidlevad, kas arvudel on mingi ontiline staatus või eksisteerivad need ainult meie mõtetes.",
     "olemine, see mis on", "mis puudutab"),
    ("Kandma vilja või muutuma produktiivseks.",
     "Lõpuks vilja kandma — pingutus, idee või investeering, mis vilja kannab, on kasvanud seemnest millekski kasulikuks.",
     "Aastate vaikne uurimistöö kandis lõpuks vilja: toimiva vaktsiini.",
     "vili", "tegema, põhjustama"),
    ("Ennustab või kujutab midagi juba tehtuna enne, kui see tegelikult on juhtunud.",
     "Jookseb ette kirjanduslikult — kirjeldab tulevast sündmust nii, nagu see oleks juba möödas, et punkt tabaks kõvemini.",
     "Kindrali ennetav toost \"võidule\" tõsteti terve nädal enne lahingut.",
     "enne", "võtma, haarama"),
    ("Õhurõhuga töötav; ka vaimu või hingamisega seotud.",
     "Tähendab tavaliselt \"suruõhuga töötavat\" — kuigi see võib tähendada ka vaimu või hingamist.",
     "Pneumaatilised pidurid sisisesid, kui buss äärekivi juurde peatus.",
     "tuul, hingamine, vaim", "mis kuulub"),
    ("Jumalat või jumalikku positiivsete väidetega kirjeldav — apofaatilise vastand.",
     "Viis rääkida Jumalast öeldes, mis Jumal on — \"God is love\" — mitte ainult, mis Jumal ei ole.",
     "Katafaatiline teoloogia räägib kindlalt Jumalast kui armastavast, õiglasest ja halastavast.",
     "alla, vastavalt", "rääkima, ütlema"),
    ("Usaldusel või usul põhinev; ka kindel võrdluspunkt.",
     "Midagi, mida võtad usaldusel ja kasutad siis ankruna — võrdlusmärk on kindel punkt, mille vastu kõike muud mõõdetakse.",
     "Maamõõtjad panid kindla võrdlusmärgi kaljupinda enne ala kaardistamist.",
     "usaldama", "usaldus, kindlus"),
    ("Jumala headuse kaitse kurja olemasolu valguses.",
     "Igivana katse vastata küsimusele \"If God is good, why does evil exist?\"",
     "Tema väitekiri uuris teodiiket Iiobi raamatu kaudu.",
     "jumal", "õiglus"),
    ("Vastastikune teineteises elamine — teoloogiline termin selle kohta, kuidas Kolmainsuse isikud teineteises on.",
     "Teoloogia sõna kolme-ühes-koosolemisele, mis on nii täielik, et iga osa sisaldab teisi ja sisaldub neis.",
     "Perikoreesi õpetus püüab selgitada, kuidas Isa, Poeg ja Vaim on eraldi, ent lahutamatud.",
     "ümber", "minema, kõndima"),
    ("Omama tagajärge, mis kedagi kasu toob või temale tagasi peegeldub.",
     "Kui au (või süü) põrkab tagasi vastutajale — head teod, mis tulevad sinu mainele kasuks, tulevad tagasi sind premeerima.",
     "Meeskonna edu toob au tema vaiksele, usinale treenerile.",
     "tagasi, jälle", "laine"),
    ("Vältimatu; millest ei saa pääseda.",
     "Juhtub paratamatult, mida sa ka ei tee — vältimatust tulemusest ei lipsata välja.",
     "Vanadus tuleb kõigile; see on lihtsalt vältimatu.",
     "ei", "välja rabelema"),
    ("Kasutab kaudset, sõnarikast sõnastust otsevormi asemel.",
     "Pikk ringtee sõnadega — öelda \"make a decision\" selle asemel et öelda \"decide.\"",
     "Tema ümberütlevad e-kirjad oleksid võinud ühe reaga öelda selle, milleks tal kulus kolm lõiku.",
     "ümber", "kuulutama, jutustama"),
    ("Vaimne tuimus või letargia.",
     "See udune, visav meeleseisund, milles mõtlemine tundub siirupis kahlamisena.",
     "Tuimuse laine tabas klassi kohe pärast lõunat.",
     "nüri, tömp", "seisund või omadus"),
    ("Ebasoodne; ennustab halba.",
     "Halb märk — olud või ajastus, mis tunduvad sinu vastu töötavat juba enne, kui oled alustanud.",
     "Hall taevas ja surnud autoaku andsid teekonnale ebasoodsa alguse.",
     "ei", "soodne, armuline"),
    ("Kastmes hautatud või braseeritud liha — õigesti kirjutatud \"fricasseed.\"",
     "Kodusoojane vana toidutermin lihale, mis on tükkideks lõigatud ja aeglaselt oma kastmes pehmeks hautatud.",
     "Vanaema frikassee-kana oli iga pühapäevase lõunasöögi kõrghetk.",
     "praadima", "murdma (tükkideks)"),
    ("Kunstlik või kehvem asendaja.",
     "Jäljend päris asja asemel — teeb töö tehniliselt ära, aga kõik näevad, et see pole ehtne kaup.",
     "Sõjaaegsed ostjad leppisid röstitud sigurist keedetud aseainekohviga.",
     "välja, asendusliide", "panema, paigutama"),
    ("Kohelda abstraktset ideed nii, nagu see oleks konkreetne asi.",
     "Panna idee tunduma tegeliku ja kindlana — muuta udune asi, nagu \"the economy,\" millekski, millele saab osutada.",
     "Rahva \"vaimu\" nimetamine omaette olevuseks esemestab midagi, mis on tegelikult lihtsalt miljonid üksikud valikud.",
     "asi", "tegema"),
    ("Põgenes või hoidis osavalt kõrvale.",
     "Libises puhtalt minema — hiilis millestki, sageli kavalalt või napilt, olgu see tabamine, küsimus või vastus.",
     "Vastus libises tal käest tunde, kuni see äkki duši all klõpsatas.",
     "välja, minema", "mängima"),
    ("Väljendab kahtlust, hämmingut või lahendamata vastuolu.",
     "Kinni ehtsas mõtte umbteel — mitte laiskusest segaduses, vaid sest küsimus ise seisab puhta vastuse vastu.",
     "Sokrates lõpetas dialoogid sageli aporeetilisel toonil, rohkem küsimusi kui vastuseid.",
     "ilma", "käik, tee"),
    ("Kõnekujund, mis nimetab asja seostuva terminiga, nt \"the crown\" valitseja kohta.",
     "Kasutada seostuvat sõna asja enda asemel — öelda \"the White House announced,\" kui mõeldakse valitsust.",
     "\"Wall Street had a rough day\" on metonüümia — see tähendab tegelikult börsi.",
     "muutus, pärast", "nimi"),
    ("Juuri järgi välja kiskuma; looduslikust keskkonnast rebima.",
     "Kiskuda miski (või keegi) juuri järgi välja, eemale paigast või kultuurist, kuhu nad kuuluvad.",
     "Sõda juuris terve põlvkonna välja ja pillutas pered üle piiride.",
     "eemale, maha", "juur"),
    ("Meelepäraselt kõlav.",
     "Lihtsalt kena kuulata — kaunikõlaline sõna, nimi või lause veereb kõrvas pehmelt, peaaegu muusikaliselt.",
     "\"Murmuring brook\" on kaunikõlaline väike fraas, pehme ja kerge öelda.",
     "hea, hästi", "heli, hääl"),
    ("Üldiselt oletatud või arvatud olevat.",
     "Laialt usutud tõeseks, isegi kui seda pole tegelikult tõestatud — millegi \"supposed\" versioon.",
     "Kirja oletatav autor osutus hiljem täiesti võõraks.",
     "mõtlema, pidama", "mille loomus on"),
    ("Värskelt loodud sõna või väljend.",
     "Upouus sõna — just leiutatud, veel mitte (või vaevu) sõnaraamatus.",
     "\"Doomscrolling\" algas uudissõnana ja sai kiiresti argikeeleks.",
     "uus", "sõna, kõne"),
    ("Vihane või pahur.",
     "Halvas, ärritunud tujus — kiire plahvatama, nagu vanasti usuti, et põrn juhib iseloomu.",
     "Ta tulistas sapise vastuse e-kirjale sekunditega pärast selle lugemist.",
     "põrn (viha asukoht)", "mille võimuses"),
    ("Kalduvus moraliseerida pompöösselt või teeseldult.",
     "Armastab jagada väikeseid elutunde ennasttäis moel, nagu iga lause oleks õnneküpsis.",
     "Tema moraliseeriv toost \"sõpruse tõelisest tähendusest\" pani kõik kella vaatama.",
     "arvamus, mõttetera", "täis"),
    ("Liiga jutukas, eriti tühiste asjade kohta.",
     "Ei lakka lihtsalt rääkimast — jahvatab pisiasjadest kaua pärast seda, kui teistel teemad otsas.",
     "Jutukas taksojuht rääkis kogu eluloo enne, kui olime lennujaamast lahkunud.",
     "loba, jahvatus", "kalduv"),
    ("Rumalus, narrus.",
     "Puhas rumalus — kommentaar või plaan nii tobe, et vaevu väärib tõsist vastust.",
     "Plaani paljas rumalus sai selgeks hetkel, kui nad seda proovisid.",
     "rumal, tobe", "olemise seisund"),
    ("Kõne lõpuosa, sageli kokkuvõttev.",
     "Kõne suur lõpp — lõiguosa, kus kõneleja koondab kõik ja lööb punkti koju.",
     "Lõppsõna ajaks oli pool publikust juba jalul.",
     "läbi, lõpuni", "rääkima, paluma"),
    ("Sama idee tarbetu kordamine teiste sõnadega.",
     "Öelda sama kaks korda, lisamata midagi uut, nagu \"free gift\" või \"end result.\"",
     "\"It is what it is\" on lemmiktautoloogia neil, kes väldivad päris seletust.",
     "sama", "sõna, kõne"),
    ("Väga väheste sõnade kasutamine; napisõnaline kõne.",
     "Öelda palju vähesega — lühikese, otsekohese vastuse kunst, nime saanud Lakoonia kuulsalt napisõnalistelt spartalastelt.",
     "\"Molon labe\" — \"tulge ja võtke\" — on ajaloo kuulsaim lakonism.",
     "Lakoonia spartalane", "komme, viis"),
    ("Lahjad, üli lihtsustatud ideed; algselt lahja toit või puder.",
     "Õhuke, vesine mõtlemine — sisu nii lihtsustatud ja turvaline, et sellel pole vaimule toiteväärtust.",
     "Poliitiku kõne oli peamiselt tühi jutt: ähmased lubadused, millest ei saanud kinni võtta.",
     "toitma", "vahend või riist"),
    ("Uinutav või uimasust tekitav.",
     "Nii igav — või nii sõna-sõnalt uinutav — et teeb uniseks. Mõtle soojale piimale või kolmetunnisele eelarvekoosolekule.",
     "Loengu uinutav sumin pani pooled toasolijad silmi lahti hoidmise nimel võitlema.",
     "sügav uni", "tegev, põhjustav"),
    ("Liiga meelitav või õline kommetelt.",
     "Nii siledalt võluv, et tundub libe — meelitus nii paksult peale, et rasva peaaegu tunned.",
     "Lipitsev müüja kiitis mu \"suurepärast maitset\" enne iga juurdemüüki.",
     "võidma, õlitama", "täis"),
    ("Kiire vigu leidma, liiga kriitiline tühiste asjade suhtes.",
     "Näägutav veani — tüüp, kes leiab probleemi kõiges, isegi kui see ei loe.",
     "Tema norivad märkused raportile keskendusid täielikult komadele.",
     "haarama, võtma", "lõks, sofism"),
    ("Loiult, vaimselt või kehaliselt tegevusetu.",
     "Aeglane ja poolunes, nagu karu talveunes — vaevu liigub, vaevu mõtleb.",
     "Kontor vajus augustikuumuses tuimusse.",
     "olla tuim, olla loi", "mingis seisundis"),
    ("Kojamees või ametnik, kes juhtis keskaegset majapidamist.",
     "Keskaja versioon personalijuhist — usaldusväärne ametnik, kes ajas isanda maja ja mõisa asju päevast päeva.",
     "Lossi kojaülem haldas kõike saagiarvestusest külaliste nimekirjani.",
     "vana, vanem", "teenija"),
    ("Rääkida või kirjutada teemast pikalt.",
     "Tõeliselt hoogu sisse saada teemal — rääkida või kirjutada ja katta see igast nurgast.",
     "Küsi temalt vanade autode kohta ja ta laiutab teemal täistunni.",
     "välja", "ruum"),
    ("Väärtusetu, tühine; ka kehtetu või mõjutu.",
     "Praktiliselt mitte midagi väärt — tühine lepingupunkt on selline, mis tegelikult midagi ei tee.",
     "Kohus kuulutas vana määruse tühiseks, kuna seda polnud kunagi jõustatud.",
     "pisiasjad, jama", "kuuluv"),
    ("Tarkus, terav otsustusvõime.",
     "Terav, praktiline tarkus — selline hea otsustus, mis tuleb kogemusest, mitte ainult raamatutest.",
     "Vana kapteni arukus hoidis meeskonna hädast eemal rohkem kui korra.",
     "teravahaisteline, terav", "omadus"),
    ("Rämps või massid, põlglikult kasutatuna.",
     "Upsakas, tõrjuv sõna \"the rabble\" või lihtrahva kohta, kasutatud põlgusega.",
     "Krahv irvitas pööbli peale, kes kogunes palee väravate taha.",
     "koer", "kogu, kari"),
    ("Üleolev, alandav kohtlemine või keel.",
     "Julm, pilkav kohtlemine, mille eesmärk on alandada — selline solvang, mis on tehtud kipitama.",
     "Ta talus aastate teotust kriitikutelt, enne kui tema töö lõpuks tunnustati.",
     "koos, põhjalikult", "paisuma (uhkusest)"),
    ("Kahtlustavalt või taunivalt; kõõrdi pilk.",
     "See kõõrdi pilk, mille annad millelegi, mida sa päris ei usalda — pilk täis kahtlust.",
     "Õpetaja vaatas viltu kahtlaselt korralikku kodutööd.",
     "poole, juurde", "kaldus, kallutatus"),
    ("Rumal inimene; puupea.",
     "Vanamoodne, peaaegu hell solvang kellelegi, kes on aeglane või pakspealine — puupea.",
     "\"Sa tainapea,\" naeris ta, \"sul on kaart kogu aeg tagurpidi olnud.\"",
     "mullakamakas", "pea"),
    ("Panema liikvele või teole; motiveerida.",
     "Olla säde, mis paneb midagi liikuma — olgu see masin, mis käivitub, või inimene, kes lõpuks idee järgi tegutseb.",
     "Hirm lepingu kaotamise ees ajendas kogu meeskonna nädalavahetuse ületunnile.",
     "tegemine, ajamine", "ajama, tegema"),
    ("Hoolde usaldatud vahendite omastamine.",
     "Varastada vaikselt raha, mille hooleks sind usaldati — omastamine vanamoodsas mantlis.",
     "Kassiiri omastamine jäi peaaegu kümnendiks märkamata.",
     "eraomand", "kari, rikkus"),
    ("Rühm, keda peetakse auväärse seltskonna äärel.",
     "Hiilgav, ent hämar sotsiaalne allilm — inimesed, kes elavad napilt \"respectable\" seltskonna reeglite väljaspool.",
     "Romaan jälgib lauljannat, kes navigeerib 1920. aastate kabareede poolilmas.",
     "pool", "maailm, seltskond"),
    ("Veel olemas; mitte välja surnud või hävitatud.",
     "Veel täna siin — kasutatakse vanade asjade (käsikirjad, liigid, hooned) kohta, mis on suutnud ellu jääda.",
     "Ainult kolm säilinud eksemplari esmatrükist on teadaolevalt olemas.",
     "välja", "seisma"),
    ("Petlikkus; usalduse reetmine.",
     "Sügav, tahtlik reetmine — usalduse murdmine, mida teine võis oodata, et sa hoiad.",
     "Kindral ei andnud kunagi andeks vana sõbra reetlikkust läbirääkimiste laua taga.",
     "läbi, vastu", "usk, usaldus"),
    ("Piirkondlik murre, eriti mittestandardne.",
     "Eripärane, kohalik viis, kuidas inimesed teatud kandis räägivad — täis sõnu ja rütme, mida võõras ei pruugi tabada.",
     "Tema vanaema rääkis veel saare murrakut peresöögil.",
     "kare kõne, murre", "käpp — kohmakas jutt"),
    ("Eriline õigus, mis kuulub isikule või rühmale.",
     "Eesõigus, mis on sinu ja ainult sinu — õigus, mis tuleb sinu rolli, positsiooni või staatusega.",
     "Pere puhkusesihtkoha valimine on vanaisa eesõigus ja kõik teavad seda.",
     "enne", "küsima, hääletama"),
    ("Julgus, uljus; ka sitkus või vastupidavus.",
     "Kare, sisukas vastupidavus — närvi edasi minna ja sitkust jätkata, kui kord alustad.",
     "Päris vaprust oli vaja kuru ületamiseks lumetormis ilma kaardita.",
     "julge, karastunud", "seisund, olukord"),
    ("Puhkema õide; ka arenema või tasapisi ilmuma.",
     "Avada täielikuks väljenduseks — nagu lill, mis avaneb, või idee, mis lõpuks omaks saab.",
     "Tema vaikne maalimisanne puhkes õide, kui ta sai oma ateljee.",
     "välja", "hakkama õitsema"),
    ("Kaaluga nöör püstloodisuse määramiseks; ülekantult, otsustuse mõõdupuu.",
     "Kaal nööril, mis ripub täiesti sirgelt alla — sellega kontrollitakse, kas miski on tõeliselt püstloodis — ja laiemalt iga kindel mõõdupuu, millega kõike muud mõõdetakse.",
     "Ta kasutas oma vanaisa ausust omamoodi loodijoonena iga otsuse juures.",
     "tina", "nöör, mõõt"),
    ("Meelsasti, vabatahtlikult (vanamoodne).",
     "Vanamoodne viis öelda \"gladly\" või \"with pleasure.\"",
     "\"Puhkaksin siin meelsasti veidi,\" ohkas rändur.",
     "rõõmus, rõõmus", "meelsasti, vabatahtlikult"),
    ("Karm avalik kriitika või häbi.",
     "Avalik häbi, mida kuhjatakse kellegi peale nähtavalt — häbi, mis tuleb laialdasest taunimisest.",
     "Skandaal tõi avaliku häbi kogu firma peale.",
     "vastu", "häbi, etteheide"),
    ("Teravalt sarkastiline, salvav vaimukuses või kriitikas.",
     "Vaimukus, millel on päris hambad — söövitav märkus kipitab just seetõttu, et see on nii tabavalt sihitud.",
     "Tema söövitavaid filmiarvustusi kartsid režissöörid ja armastasid lugejad.",
     "hammustama", "salvav, tegev"),
    ("Formaalne kuulutus, sageli poliitiline või sõjaline.",
     "Suur, ametlik teadaanne — tavaliselt selline, mis kuulutab uue valitsuse, ülestõusu või tähtsa dekreedi.",
     "Kindrali manifest kuulutas uue valitsuse koidikul.",
     "ette", "kuulutama"),
    ("Isik pealiskaudsete teadmistega, kes teeskleb asjatundjat.",
     "Keegi, kes on teema pinna üle libistanud ja räägib siis, nagu oleks kirjutanud selle õpiku.",
     "Õhtusöögi poolharitlane parandas enesekindlalt laua päris astrofüüsikut.",
     "teadma", "diminutiiv — väike teadja"),
    ("Vaimsete võimete langus vanaduses.",
     "Udune, unustav lõik kõrges eas, kui mee teravus hakkab tuhmuma.",
     "Oma raugaeas rääkis ta samu kolme lugu igal külastusel, iga kord nagu uut.",
     "johmima, olla rumal", "seisund või tulemus"),
    ("Tuule eest varjatud külg.",
     "Millegi rahulik, varjatud külg — künka, laeva, müüri — kus tuul sind päris kätte ei saa.",
     "Matkajad püstitasid telgi harja tuulevarju, et pääseda iilidest.",
     "varjupaik, kaitse", "külg, nurk"),
    ("Tõrjuda löök, küsimus või argument.",
     "Lüüa midagi sujuvalt kõrvale — mõõgalöök, piinlik küsimus või süüdistus — rütmi kaotamata.",
     "Ta tõrjus ajakirjaniku kiusliku küsimuse kerge naljaga.",
     "tõrjuma", "valmistuma, kaitsma"),
    ("Haistev, kahjulik.",
     "Haiseb peaaegu mürgiselt — hais nii halb, et hingamine tundub ohtlik.",
     "Haisev lõhn tõusis soost, kui päike loojus.",
     "kahjulik aur", "mille loomus on"),
    ("Isik, kes on pühendunud luksusele ja naudingule.",
     "Keegi, kes elab mugavuse ja naudingute pärast — hea toit, pehmed voodid, kerge elu — nime saanud antiikse kreeka linna Sybarise järgi, mis oli kuulus ülekülluse poolest.",
     "Tõeline sübariit, ta keeldus igast hotellitoast ilma vannita.",
     "antiikne kreeka linn, kuulus luksuse poolest", "elanik"),
    ("Jätta meelega osa millestki kõrvale.",
     "Panna pusletükk meelega kõrvale, et saaksid puhtalt ülejäänule keskenduda.",
     "Jätame kulu hetkeks kõrvale ja küsime vaid, kas plaan tegelikult töötab.",
     "enne, eemale", "lõikama"),
    ("Kritiseerida karmilt; ka nahka maha kiskuda.",
     "Kiskuda keegi karmis kriitikas tükkideks — sõnadega, nagu nülgiksid naha sõna-sõnalt.",
     "Kriitikud tegid järjega maatasa, sest see reetis kõik, mida fännid originaalis armastasid.",
     "maha", "nahk, nahk"),
    ("Tsiteerida tõendina või tõestuseks.",
     "Tuua esile fakt või näide oma punkti toetuseks — see, millele osutad, kui keegi küsib \"what's your evidence?\"",
     "Advokaat esitas kolm tunnistajat kliendi alibi toetuseks.",
     "juurde, poole", "juhtima"),
    ("Rännakud või uitamised, eriti pikad või ulatuslikud.",
     "Pikad, uitavad teekonnad — selline ulatuslik rändamine, mis viib sind kauaks kodust kaugele.",
     "Tema rännakud üle kolme mandri täitsid terve riiuli reisikirju.",
     "läbi", "väli, maa (peregrinus: võõras)"),
    ("Kerjus või almustel elav.",
     "Keegi, kes elab heategevust paludes — ajalooliselt kirjeldas see ka munki, kes andsid vaesustõotuse ja elasid annetustest.",
     "Kerjusvennad ei omanud midagi ja toetusid täielikult külaelanike headusele.",
     "kerjama", "kerjus"),
    ("Äärmiselt helde.",
     "Helde suurel, peaaegu uhkeldaval skaalal — selline kingitus, mis paneb inimesi natuke ahmima.",
     "Helde annetus rahastas kogu raamatukogu uue tiiva.",
     "kingitus, teenus", "tegev, andev"),
    ("Kurnatus toidu puudusest; ka elujõu puudus.",
     "Nõrk, tühi seisund sellest, et pole toidetud ega kütust saanud — sõna-sõnalt näljast või ülekantult sellest, et pole enam millegagi sõita.",
     "Piiramise lõpuks olid sõdurid kurnatuse äärel.",
     "tühi, tühjus", "tegu või tulemus"),
    ("Kibe, teotav kriitika.",
     "Kriitika, mis on ammu õiglasest mööda läinud ja muutunud vihaseks, kibedaks purskeks.",
     "Võrgukommentaarid lagunesid minutitega puhtaks sõimuks.",
     "viga", "valmistama, varustama"),
    ("Vaenulik, kahjulik mõjult.",
     "Töötab sinu vastu, ehkki vaikselt — olud või hoiakud, mis on ebasõbralikud sinu huvidele.",
     "Uus poliitika oli väikeettevõtetele vaenulik, ehkki see ei olnud kavatsus.",
     "ei", "sõber"),
    ("Omav tekitama vimma või rahulolematust, sageli ebaõiglaste võrdluste kaudu.",
     "Määratud panema kedagi tundma end kõrvalejäetuna — tavaliselt sest see paneb inimesi või asju ebaõiglaselt vastamisi.",
     "Õdede-vendade reastamine selle järgi, \"keda ema kõige rohkem armastab\", on solvav mäng, mida keegi ei peaks mängima.",
     "kadedus", "vaatama (pahatahtlikult)"),
    ("Madalama auastme või staatusega isik; alluv.",
     "Keegi allpool käsu- või sotsiaalsel redelil — noorem, kes töötab mõjuvõimsama all.",
     "Noore nooremohvitserina võttis ta käske kaua vastu, enne kui ta neid ise andis.",
     "all", "vahelduv, teine"),
    ("Tunda või väljendada tugevat viha millegi vastu.",
     "Jälestada midagi nii, et sa needad selle valjusti — puhas, häälekas jälestus.",
     "Külaelanikud needsid maksukogujat iga kord, kui tema vanker külast läbi veeres.",
     "välja", "püha (needma pühast välja)"),
    ("Looduslik välimine kate, nagu nahk või koor.",
     "Looduse enda kaitsv ümbris — nahk, koor, kaun või koorik, mis iganes katab ja kaitseb elavat.",
     "Kilpkonna koorik on tähelepanuväärselt visa kattekiht.",
     "peal, üle", "katma"),
    ("Süütu, naiivne, lapselikku lihtsust näitav; \"disingenuous\" vastand.",
     "Avameelselt usaldav ja veidi naiivne, ilma varjatud agendata — kerge segi ajada \"ingenious\"-ga, mis tähendab nutikat.",
     "Tema siiras küsimus — \"miks peaks keegi selle kohta valetama?\" — näitas, kui vähe kavalust tal oli.",
     "sees, pärismaine", "sigitama (vabalt sündinud, siiras)"),
    ("Liigne mure pisidetailide või reeglite pärast.",
     "Eksimine väikestesse reeglitesse ja suure pildi kaotamine — klammerdumine peenes kirjas, millest keegi teine ei hooli.",
     "Tema pedantsus Oxfordi komade üle viis kogu koosoleku rööbastelt välja.",
     "laste õpetaja", "tava või omadus"),
    ("Põhjalik, hoolikas uurimine.",
     "Sügav, ühtki kivi pööramata vaade millelegi — iga üksikasja läbimine tõelise hoolega.",
     "Alles hoolika läbivaatuse järel kerkis pearaamatutest kõrvalekalle.",
     "läbi, põhjalikult", "otsima, uurima"),
    ("Esitada vastuväiteid; näidata vastumeelsust.",
     "Viisakalt tagasi astuda või kõhkleda, selle asemel et kohe kaasa minna — pehme \"I'd rather not.\"",
     "Kui teda paluti allkirjastada lugemata, tõrkus ta.",
     "eemale, ära", "viivitama"),
    ("Pealiskaudselt usutav, kuid tegelikult vale.",
     "Kõlab veenvalt esimesel pilgul, kuid laguneb kohe, kui sa selle tegelikult üle vaatad.",
     "\"Everyone's doing it\" on näiliselt veenev argument, mis ei pea kontrollile vastu.",
     "välimus, ilme", "täis (näiliselt kaunis)"),
    ("Ebasiiras, silmakirjalik jutt, sageli moraliseeriv.",
     "Jutlustav jutt, mis kõlab vooruslikult, kuid mida ei toeta ükski ehtne tunne — moraalne poseerimine autopiloodil.",
     "Ta oli väsinud ettevõtte tühjast jutust \"perekonnast\" firmalt, kes ei andnud kunagi vaba aega.",
     "laulma (hiljem: laulev släng)", "kerjuste vingumine, siis silmakirjalikkus"),
    ("Julguseta, argpüks.",
     "Arg selgrootuseni — liiga hirmul, et seista isegi siis, kui see selgelt loeb.",
     "Nõukogu argpükslik vaikus laskis skandaalil käest minna.",
     "väga väike", "vaim, julgus"),
    ("Rebase moodi; kaval, salakaval.",
     "Kaval ja nutikas nagu rebane — kiire mõistusega, veidi salalik, alati sammu ees.",
     "Ta naeratas rebaseliku naeratuse hetkel, kui ta augu märkas.",
     "rebane", "millestki või sarnane"),
    ("Ükshaaval, järjekorras.",
     "Võetud rangelt ükshaaval, järjekorras — ei hüpata ette, ei kaht korraga.",
     "Kohtunik käsitles iga kahtteistkümnest nõudest ükshaaval.",
     "rida, jada", "ükshaaval"),
    ("Äärmuslik kokkuhoidlikkus; kitsidus.",
     "Kitsas raha (või sõnade või ressursside) suhtes kaua mõistliku kokkuhoiu mööda.",
     "Tema ihnus oli legendaarne — ta kasutas teekotte kolm korda.",
     "säästma, olla kokkuhoidlik", "seisund või tava"),
    ("Parandus, eriti tekstis.",
     "Parandus kirjutises — õpetatud kohandus, mis parandab vea vanas või tähtsas tekstis.",
     "Uus väljaanne sisaldab kümneid parandusi originaalkäsikirjas.",
     "välja", "viga, eksimus"),
    ("Mõõdukas söömises ja joomises.",
     "Teadlikult tagasihoidlik toidu ja joogi suhtes — mitte kunagi liiga, alati natuke taldrikule jäetud.",
     "Tema karsked harjumused hoidsid teda teravana kaua pärast seda, kui eakaaslased olid aeglustunud.",
     "eemale millestki", "joovastav jook"),
    ("Grammatikaviga või etiketi rikkumine.",
     "Komistus grammatikas või kommetes — selline väike viga, mis paneb näägutaja irvitama.",
     "\"Between you and I\" on tavaline keeleviga, mis paneb grammatikuid ikka võpatama.",
     "Kiliikia linn, tuntud 'halva' kreeka poolest", "komme, viis"),
    ("Puudutab rühmasisest konflikti; vastastikku hävitav.",
     "Sisemine rii, mis rebib rühma seestpoolt — võitlus, milles kõik kaotavad, sest see on pere pere vastu.",
     "Partei omavaheline kisma tegi rohkem kahju, kui ükski väline vastane oleks suutnud.",
     "vahel, seas", "tappa"),
    ("Ükskõikne, hooletu suhtumine.",
     "Õlga kehitus, millest on tehtud terve isiksus — hoolida nii vähe asjadest, mis enne loeti, et miski ei tundu enam vaeva väärt.",
     "Tema ükskõikne suhtumine auhinnatseremooniasse üllatas kõiki, kes teadsid, kui kõvasti ta oli tööd teinud.",
     "natuke", "hoolima"),
    ("Segane, keeruline olukord või vaidlus.",
     "Sassis, räpane olukord, millest on raske sotti saada — osalt vääritimõistmine, osalt draama, täiesti segadus.",
     "Kogu istumiskaardi segadik algas ühest valesse kohta sattunud nimekaardist.",
     "sees", "sassi ajama, segadusse ajama"),
    ("Ähvardav, ähvardav.",
     "Kannab eksimatut ähvarduse õhku — ähvardav pilk või kiri teeb väga selgeks, et midagi halba võib järgneda.",
     "Kirja ähvardav toon tegi üürniku närviliseks juba enne, kui ta ümbriku avas.",
     "ähvardama", "teeniv"),
    ("Tugev avalik kriitika või sõnaline teotus.",
     "Häälekas, avalik hukkamõist — selline kipitav kriitika, mis toimub kõigi silme all.",
     "Vilepuhuja seisis silmitsi aastate avaliku laimuga, enne kui ajalugu talle õiguse andis.",
     "vastu", "rääkima"),
    ("Äkiline vägivaldne purske, tunde või teo.",
     "Äkiline, intensiivne löök, mis valdab korraga — naeru, raevu või köha hoog, mis lööb nagu laine.",
     "Teda tabas naeruhoog, mida ta ei osanud kellelegi teisele toas seletada.",
     "sealpool", "terav, äge"),
    ("Lisatud välisest allikast, mitte olemuslik.",
     "Kruvitud külge väljast, mitte sisse ehitatud algusest peale — lisa, mitte tuumosa.",
     "Kommentaar tundub külge poogitud, justkui oleks see kleebitud juba valmis tekstile.",
     "juurde, lisaks", "heaks kiitma, võtma"),
    ("Teadmiste puudus, teadmatus.",
     "Lihtne mitteteadmine — lünk teadmistes, ilma sellele kinnitatud hinnanguta.",
     "Ta tunnistas oma teadmatust Prantsuse veini kohta ja lasi sommeljeel valida.",
     "ei", "teadma"),
    ("Liigne huvi seksuaalsete asjade vastu.",
     "Üliagar, jõllitav uudishimu kõige pikantse vastu — huvi, mis on läinud tervest mööda nuhkivaks.",
     "Tabloidide iharus paari eraelu vastu piirnes kinnisideega.",
     "sügelama, igatsema", "seisund"),
    ("Nokune, tume, hämar.",
     "Tume ja suitsune välimuselt, justkui oleks kõik õhukese noenaga kaetud.",
     "Tahmane udu rippus tehaseasula kohal hämaruses.",
     "nõgi", "täis"),
    ("Eitada või vastu rääkida.",
     "Rääkida otse vastu sellele, mida teine on öelnud — öelda \"that's not so.\"",
     "Keegi ei julgenud vaidlustada vana kapteni juttu tormist.",
     "vastu", "rääkima"),
    ("Laiskus, loius (ladina keelest).",
     "Vana ladina sõna puhtale laiskusele — lohisemine selles, et ei taha midagi teha.",
     "Mungad jutlustasid laiskuse vastu kui ühe hinge vaikse ohu vastu.",
     "ei", "hõivatud, tubli"),
    ("Kilp, millel on vapp.",
     "Kilbikujuline tunnus, mis näitab suguvõsa vappi — selle heraldiline \"nameplate.\"",
     "Suguvõsa vapp ripub endiselt vana mõisa esiukse kohal.",
     "kilp", "diminutiiv / ese"),
    ("Aegunud, vananenud või vanuse tõttu pensionile saadetud.",
     "Kasuliku tipu möödas ja karjamaale saadetud — liiga vanamoodne või kulunud, et tööd jätkata.",
     "Iganenud printer vahetati lõpuks välja pärast viitteist aastat paberiummistusi.",
     "sealpool", "aasta"),
    ("Asendajad, eriti meditsiinis.",
     "Asendusained, kui päris ravi pole saadaval — meditsiinilised asendajad sisuliselt.",
     "Sõjaaegsed arstid toetusid sageli aseainetele, kui õiged ravimid otsa said.",
     "asemel", "minema, taanduma"),
    ("Kergelev, uhkeldav jutt.",
     "Suur, puhkuv uhkeldamine — vali jutt oma suurusest, mis on enamasti tühi õhk.",
     "Tema hooplemine sellest, kuidas ta \"üksinda\" projekti päästis, ei petnud kedagi, kes tegelikult kohal oli.",
     "uhkeldav rüütel teoses Orlando Furioso", "tegu, etendus"),
    ("Kasutada kavalust või pettust millegi saavutamiseks.",
     "Vingerdada eesmärgini salakavalate trikkidega ausa mängu asemel.",
     "Ta keerutas end tehingusse peenes kirjas täidetud lepinguga.",
     "norima, petma", "trikk; hiljem järsk kurv"),
    ("Õppimise või teadmise puhas või abstraktne teadus, sageli matemaatika.",
     "Õppimine puhtaimas, abstraktseimas vormis — teadmise sügav struktuur ise, eriti matemaatiline liik.",
     "Filosoof unistas universaalsest mathesis'est, mis võiks ühendada iga teadmisala.",
     "õppima", "õppimise tegu"),
    ("Liiga hõivatud formaalsete reeglite või tühiste detailidega.",
     "Liiga range pisiasjade suhtes — parandab väikesi tehnilisi punkte, mis tegelikult midagi ei muuda.",
     "Tundus veidi pedantne vaielda \"who\" versus \"whom\" üle tekstisõnumis.",
     "lapsejuht, juhendaja", "mille viis on"),
    ("Välklev, sädelev valgus.",
     "Kiire, sädelev valgusvälgatus — mõtle päikesevalgusele vee peal või teemandile, mis püüab valguse.",
     "Lühtri sädelus puistas valgust igasse ballisaali nurka.",
     "sädelema, välkuma", "tegu"),
    ("Algaja, noviits.",
     "Keegi upouus oskuses või alal — alles aluseid õppimas, veel mitte asjatundja.",
     "Isegi algaja maletaja märkab seda apsakat.",
     "värbaja, noviits", "toores noor sõdur"),
    ("Äärmiselt halb, jälk.",
     "Halb viisil, mis väärib ehtsat jälestust — mitte ainult \"mediocre,\" vaid tõeliselt jälk.",
     "Arvustaja nimetas järge jälestusväärseks ja kassanäitajad olid nõus.",
     "needma", "vääriv, suuteline saama"),
    ("Veripunane värvilt.",
     "Sügav, elav punane — värske vere värv, Shakespeare'i Macbethi kuulsalt kasutatud.",
     "Päikeseloojang keeras kogu taeva verepunasesse helendusse.",
     "sisse", "liha (lihapunane)"),
    ("Väike vahe või ruum asjade vahel.",
     "Väike vahe, mida on kerge kahe silma vahele jätta — põrandalaudade pragu, ajakava auk.",
     "Umbrohi lükkas end läbi vana tellistee iga prao.",
     "vahel", "seisma"),
    ("Kriitilised või laitvad märkused.",
     "Teravad, taunivad kommentaarid — selline kriitika, millel on veidi noomiv toon.",
     "Professori etteheited esseele täitsid veerised punase tindiga.",
     "meel", "pöörduma poole"),
    ("Võimatu ümber lükata, eitatamatu.",
     "Nii kindlalt tõestatud, et selle üle ei saa vaielda — asi on lihtsalt suletud.",
     "DNA-tõend oli ümberlükkamatu ja kohtuprotsess oli tunni jooksul läbi.",
     "ei", "vastu seisma, vastu panema"),
    ("Keerukus, keerulisus; ka sissepoole keerdumine.",
     "Sassis, endasse keerdunud keerukus — asjad nii tihedalt mässitud, et neid on raske lahti tõmmata.",
     "Süžee keerukus jättis poole publiku pärast lõputiitreid seda lahti harutama.",
     "sisse, sissepoole", "veerlema, pöörama"),
    ("Jõud või pingutus, nagu \"by dint of.\"",
     "Paljas pingutus või jõud — elab tänapäeval enamasti fraasis \"by dint of.\"",
     "Ta sai eksami läbi puhta, kangekaelse harjutamise jõul.",
     "löök, põrge", "jõuga"),
    ("Tapiga ühendatud; kindlalt kokku sobitatud.",
     "Lukustatud kokku vanamoodsa puusepa moodi — tükk, mis libiseb tihedalt just selleks lõigatud auku.",
     "Vana aida talad olid tapiga kokku pandud ilma ühegi naelata.",
     "süvend, auk", "hammustus, haare"),
    ("Väga asjakohane, tabav.",
     "Täpselt õige hetke jaoks — märkus, tsitaat või näide, mis maandub täiuslikult täppi.",
     "Tema tabav märkus võttis kogu arutelu ühte lausesse kokku.",
     "juurde", "paigutama"),
    ("Pehmelt helendav või värelev (valgus); ka kerge vaimukus.",
     "Helendab leebealt pigem kui lõõmab — pehme, värelev valgus või vaimukus, mis on mänguline pigem kui terav.",
     "Küünlavalgus viskas võbeleva helenduse vana söögitoa kohale.",
     "lakkuma", "tegev (valgus, mis 'lakub')"),
    ("Usuline erak, kes elab üksinduses.",
     "Keegi, kes tõmbub maailmast täielikult tagasi, et elada üksi palves ja mõtiskluses.",
     "Erak elas väikeses kiriku külge ehitatud kongis üle kolmekümne aasta.",
     "tagasi, eemale", "taganema"),
    ("Kustutada janu; kustutama.",
     "Rahulda igatsus täielikult — enamasti janu, kuid ülekantult ükskõik milline sügav vajadus.",
     "Üks külm klaas vett kustutas tema janu pika matka järel.",
     "lõtv, lõtv", "lõdvendama, rahustama"),
    ("Nõelakujuline.",
     "Pikk, peenike ja terav nagu nõel — männiokka või terava väikese kristalli kuju.",
     "Mände on kerge tunda nõeljate lehtede järgi.",
     "nõel", "väike"),
    ("Elujõust kurnatud, nõrk, ülipeenutatud.",
     "Kulunud ja pehme — kaotanud algse jõu või sädeme liigse mugavuse või peenutamise kaudu.",
     "Kriitikud nimetasid kunagi julget ajakirja jõuetuks, selle varaste julgete aastate varjuks.",
     "välja", "viljakas, kes on kandnud"),
    ("Lisand või väiksem lisatud ese või õigus.",
     "Väike lisa, mis tuleb millegi suuremaga — lisatarvikud ja lisandid, mis kuuluvad põhiasja juurde.",
     "Üürileping hõlmas garaaži ja kõiki selle juurdekuuluvusi.",
     "juurde", "kuuluma"),
    ("Katmata või vähendada viga.",
     "Siluda viga pehmete sõnadega, et see kõlaks väiksemana, kui see on.",
     "Ta üritas mööda lastud tähtaega ilustada uduse jutuga \"ettenägematutest raskustest\".",
     "glosa, seletus", "kommenteerida — siis siluda"),
    ("Varajases staadiumis, alles algamas.",
     "Alles hakkamas paistma — kõige esimene, vaevu nähtav staadium millestki suuremast, mis tuleb.",
     "Arstid püüdsid kinni haiguse algavad märgid enne, kui see jõudis levida.",
     "peale, sisse", "võtma (vastu võtma, alustama)"),
    ("Loov inspiratsioon, eriti jumalik.",
     "Äkiline inspiratsioonipuhang, mis tundub sinust suurem — justkui oleks idee puhutud sinusse kuskilt mujalt.",
     "Luuletaja kirjeldas, kuidas kogu teos saabus ühe inspiratsioonipuhanguga kell kolm öösel.",
     "juurde, peale", "puhuma (pealepuhumine)"),
]
