# Vietnamese rows: (definition, friendly, exampleGloss, root1, root2)
ROWS = [
    ("Làm ngọt hoặc thanh lọc; lấy đi sự thô ráp khỏi một thứ.",
     "Gỡ nọc hoặc vị đắng — ngọt hóa theo nghĩa đen, hoặc làm dịu một ý tưởng khắc nghiệt cho dễ nuốt.",
     "Biên tập viên đã làm dịu bài điểm sách gay gắt trước khi đưa nó đi in.",
     "ra ngoài, triệt để", "ngọt"),
    ("Quá mức hoặc giả tạo về mặt tôn giáo, đạo đức.",
     "Chỉ người mà lòng sùng đạo trông như diễn cho người khác xem, nhiều sân khấu hơn đức tin.",
     "Tiếng thở dài ra vẻ mộ đạo của ông trong bài giảng làm cả hàng ghế khó chịu.",
     "lòng đạo, bổn phận", "mang tính chất của"),
    ("Sự mơ hồ do cấu trúc ngữ pháp — câu đọc được hai cách.",
     "Câu đúng ngữ pháp nhưng đọc ra hai nghĩa hoàn toàn khác, như \"Visiting relatives can be tiring\".",
     "\"Visiting relatives can be tiring\" là một câu mơ hồ cú pháp kinh điển — bà con làm ta mệt, hay việc đi thăm họ mới mệt?",
     "cả hai, hai phía", "ném"),
    ("Sắc, sắc sảo, cắt thẳng vào điểm chính.",
     "Cắt thẳng qua lớp rườm rà — một nhận xét hay một trí óc sắc bén đi ngay vào trọng tâm, không một lời thừa.",
     "Lời phê bình sắc bén của cô không chừa chỗ nào cho những lỗ hổng cốt truyện của phim ẩn nấp.",
     "cắt", "làm, mang phẩm chất"),
    ("Mới bắt đầu; ở giai đoạn sớm hoặc phôi thai.",
     "Vẫn ở phút mở màn — kế hoạch, cảm xúc hay quá trình vừa mới thành hình.",
     "Các giai đoạn phôi thai của hiệp ước đầy hứa hẹn, nhưng nhiều chi tiết vẫn còn bỏ ngỏ.",
     "bắt đầu, khởi sự", "có khuynh hướng tới"),
    ("Bài nói hay bài viết trang trọng ca ngợi ai đó rất cao.",
     "Lời tôn vinh long trọng đầy đủ — tưởng tượng điếu văn rực rỡ hay bài diễn ca ngợi thành tựu từ nóc nhà.",
     "Vị giáo sư về hưu được tiễn bằng một bài tán tụng từ những học trò thân nhất của bà.",
     "tất cả", "hội họp, tập hợp"),
    ("Liên quan đến sự tồn tại thực hay hữu thể sự thật, đối lập lý thuyết trừu tượng.",
     "Về sự vật như chúng thực sự tồn tại, chứ không chỉ là ý niệm hay lý thuyết về chúng.",
     "Các triết gia tranh luận liệu những con số có địa vị hữu thể nào không, hay chỉ tồn tại trong trí ta.",
     "tồn tại, cái đang có", "liên quan tới"),
    ("Kết trái, hoặc trở nên sinh lợi.",
     "Cuối cùng đơm hoa kết trái — nỗ lực, ý tưởng hay khoản đầu tư lớn từ hạt thành thứ hữu ích.",
     "Nhiều năm nghiên cứu lặng lẽ cuối cùng đã kết trái thành một loại vắc-xin dùng được.",
     "quả", "làm, gây ra"),
    ("Dự liệu hoặc trình bày điều gì như đã xong trước khi thực sự xảy ra.",
     "Vượt rào theo kiểu văn chương — mô tả sự kiện tương lai như đã kết thúc, để luận điểm đậm hơn.",
     "Lời nâng ly đón trước của vị tướng chúc \"chiến thắng\" được nói ra cả tuần trước trận đánh.",
     "trước", "lấy, nắm"),
    ("Vận hành bằng áp suất khí; cũng liên quan đến tinh thần hay hơi thở.",
     "Thường nghĩa là \"chạy bằng khí nén\" — dù cũng có thể chỉ tinh thần hay hơi thở.",
     "Bộ phanh khí nén rít lên khi chiếc xe buýt áp vào lề đường.",
     "gió, hơi thở, tinh thần", "thuộc về"),
    ("Mô tả Thiên Chúa hay thần thánh bằng phát biểu khẳng định — ngược với apophatic.",
     "Cách nói về Chúa bằng điều Chúa là — \"God is love\" — chứ không chỉ điều Chúa không phải.",
     "Thần học khẳng định nói một cách tự tin về Chúa như đấng yêu thương, công chính và nhân từ.",
     "xuống, theo", "nói, bảo"),
    ("Dựa trên tin cậy hay đức tin; cũng dùng làm điểm chuẩn cố định.",
     "Điều bạn nhận lấy bằng lòng tin rồi lấy làm mỏ neo — một dấu chuẩn là điểm cố định để đo mọi thứ khác.",
     "Các nhà trắc địa đặt một mốc chuẩn vào đá gốc trước khi vẽ bản đồ khu đất.",
     "tin cậy", "tin, sự tin"),
    ("Biện hộ cho sự thiện của Thiên Chúa khi vẫn có điều ác.",
     "Nỗ lực nghìn đời trả lời \"Nếu Chúa thiện, sao vẫn có ác?\"",
     "Luận văn của cô khảo sát biện thần luận qua lăng kính Sách Gióp.",
     "thần", "công lý"),
    ("Sự nội trú lẫn nhau — thuật ngữ thần học về các ngôi trong Thiên Chúa Ba Ngôi ở trong nhau.",
     "Chữ thần học cho sự một-trong-ba trọn vẹn đến mức mỗi phần chứa và được chứa bởi các phần kia.",
     "Học thuyết nội trú hỗ tương cố giải thích vì sao Cha, Con và Thánh Linh vừa phân biệt vừa không thể tách rời.",
     "xung quanh", "đi, bước"),
    ("Mang lại hệ quả có lợi hoặc phản chiếu lại ai đó.",
     "Khi công (hay tội) bật ngược lại người chịu trách nhiệm — việc thiện dội lại danh tiếng bạn rồi vòng về mà thưởng cho bạn.",
     "Thành công của đội sẽ dội lại thành công lao của người huấn luyện viên cần mẫn, ít lời.",
     "lại, lần nữa", "sóng"),
    ("Không thể tránh hay thoát.",
     "Chắc chắn xảy ra dù bạn có làm gì đi nữa — không thể lách khỏi một kết cục không tránh nổi.",
     "Tuổi già đến với tất cả mọi người; đơn giản là không thể tránh.",
     "không", "vật lộn thoát ra"),
    ("Dùng cách nói vòng vo, dài dòng thay vì dạng trực tiếp.",
     "Đi đường vòng bằng lời — nói \"make a decision\" thay vì \"decide\".",
     "Những email vòng vo của anh lẽ ra chỉ cần một dòng cho điều đã ngốn của anh ba đoạn.",
     "xung quanh", "tuyên bố, kể"),
    ("Sự đần độn hay uể oải trí óc.",
     "Trạng thái mù sương, chậm chạp khi nghĩ như lội siro.",
     "Một đợt uể oải trí óc ập xuống cả lớp ngay sau bữa trưa.",
     "cùn, không sắc", "trạng thái hay phẩm chất"),
    ("Không thuận lợi; điềm xấu.",
     "Dấu hiệu xấu — điều kiện hay thời điểm dường như chống bạn trước khi bắt đầu.",
     "Trời xám xịt và một bình ắc quy chết khiến chuyến đi đường bắt đầu chẳng lành.",
     "không", "thuận, nhân từ"),
    ("Thịt om hoặc hầm trong sốt — chính tả đúng là \"fricasseed\".",
     "Từ nấu ăn cũ ấm cúng cho thịt thái nhỏ rồi om chậm trong sốt của chính nó cho mềm.",
     "Món gà om sốt của bà là điểm nhấn của mỗi bữa tối Chủ nhật.",
     "chiên", "bẻ (thành miếng)"),
    ("Vật thay thế nhân tạo hoặc kém hơn.",
     "Hàng nhái đứng vào chỗ thật — kỹ thuật thì xong việc, ai cũng biết không phải hàng thật.",
     "Người mua thời chiến tạm dùng thứ cà phê giả nấu từ rễ diếp xoăn rang.",
     "ra, tiền tố thay thế", "đặt, để"),
    ("Đối xử ý niệm trừu tượng như thể là vật cụ thể.",
     "Làm ý tưởng cảm giác chắc và thật — biến thứ mờ, như \"the economy\", thành vật chỉ được.",
     "Gọi \"tinh thần\" của một dân tộc là một hữu thể riêng tức là vật hóa điều vốn chỉ là hàng triệu lựa chọn riêng lẻ.",
     "vật", "làm cho thành"),
    ("Thoát hoặc tránh một cách khéo.",
     "Lẩn sạch — né bắt, câu hỏi hay câu trả lời, thường khéo hoặc sát nút.",
     "Câu trả lời lảng tránh cô hàng giờ liền cho đến khi nó bỗng khớp lại lúc cô đang tắm.",
     "ra, đi", "chơi"),
    ("Biểu lộ nghi ngờ, bối rối, hoặc mâu thuẫn chưa giải.",
     "Kẹt ở ngõ cụt tư duy thật sự — không phải lười, mà câu hỏi tự kháng lời đáp gọn.",
     "Socrates thường kết thúc các cuộc đối thoại ở một giọng bế tắc, để lại nhiều câu hỏi hơn câu trả lời.",
     "không có", "lối, đường"),
    ("Tu từ gọi sự vật bằng từ liên hệ, ví dụ \"the crown\" cho quân vương.",
     "Dùng từ liên quan thay vật thật — nói \"the White House announced\" khi ý là chính quyền.",
     "\"Wall Street had a rough day\" là một phép hoán dụ — thực ra câu ấy nói thị trường chứng khoán.",
     "thay đổi, sau", "tên"),
    ("Nhổ rễ; xé khỏi môi trường tự nhiên.",
     "Kéo vật (hay người) ra tận gốc, khỏi nơi hay văn hóa họ thuộc về.",
     "Chiến tranh bứng rễ cả một thế hệ, rải các gia đình đi khắp các biên giới.",
     "xa, khỏi", "rễ"),
    ("Êm tai.",
     "Chỉ đơn giản là dễ nghe — một từ, một cái tên hay một câu êm tai lướt qua tai êm ru, gần như có nhạc.",
     "\"Murmuring brook\" là một cụm từ êm tai, mềm và dễ đọc.",
     "tốt, hay", "âm, giọng"),
    ("Thường được cho hoặc giả định là.",
     "Được tin rộng rãi là đúng dù chưa chứng minh — phiên bản \"supposed\".",
     "Tác giả được cho là của bức thư về sau hóa ra là một người hoàn toàn xa lạ.",
     "nghĩ, coi", "mang bản chất"),
    ("Từ hay cụm mới đặt.",
     "Từ mới toanh — vừa bịa, chưa (hoặc hầu như chưa) vào từ điển.",
     "\"Doomscrolling\" khởi đầu như một từ mới đặt rồi mau chóng thành tiếng lóng hằng ngày.",
     "mới", "từ, lời"),
    ("Giận dữ hoặc cáu kỉnh.",
     "Tâm trạng tệ, dễ gắt — như người xưa tin lá lách điều khiển tính khí.",
     "Anh bắn đi một hồi đáp cáu kỉnh chỉ vài giây sau khi đọc bức thư.",
     "lá lách (chỗ của giận)", "bị ảnh hưởng bởi"),
    ("Hay lên giọng dạy đời kiểu kiêu kỳ, giả tạo.",
     "Thích phát bài học nhỏ đầy tự quan trọng, như mỗi câu là lời trong bánh may mắn.",
     "Lời nâng ly lên giọng dạy đời của anh về \"ý nghĩa thật của tình bạn\" khiến ai nấy đều nhìn đồng hồ.",
     "ý kiến, châm ngôn", "đầy"),
    ("Nói quá nhiều, nhất là chuyện vặt.",
     "Cứ không ngừng tán — lải nhải chuyện nhỏ lâu sau khi người khác hết lời.",
     "Người tài xế taxi lắm lời kể cả cuộc đời mình trước khi chúng tôi kịp rời sân bay.",
     "lảm nhảm, tám", "có khuynh hướng"),
    ("Sự ngu ngốc, ngớ ngẩn.",
     "Ngu thuần túy — nhận xét hay kế hoạch ngớ đến mức hầu như không đáng đáp nghiêm.",
     "Sự ngớ ngẩn trần trụi của kế hoạch lộ ra ngay khoảnh khắc họ thử nó.",
     "ngu, ngớ", "trạng thái"),
    ("Phần kết của bài nói, thường tóm tắt.",
     "Phần kết lớn của diễn văn — chỗ diễn giả gom hết và đóng đinh luận điểm.",
     "Đến phần kết hùng hồn, nửa khán phòng đã đứng cả dậy.",
     "xuyên, đến cùng", "nói, biện hộ"),
    ("Lặp không cần thiết cùng một ý bằng lời khác.",
     "Nói hai lần mà không thêm gì, như \"free gift\" hay \"end result\".",
     "\"It is what it is\" là lối lặp thừa ưa thích của những người tránh một lời giải thích thật.",
     "cùng một", "từ, lời"),
    ("Dùng rất ít từ; lời ngắn gọn.",
     "Nói nhiều bằng rất ít — nghệ thuật đáp ngắn, cụt lủn, lấy tên từ người Sparta Laconia nổi tiếng kiệm lời.",
     "\"Molon labe\" — \"đến mà lấy\" — là mảnh lời ngắn gọn nổi tiếng nhất trong lịch sử.",
     "người Sparta xứ Laconia", "thói, cách"),
    ("Ý tưởng nhạt, đơn giản hóa quá; gốc là thức ăn nhạt hay cháo.",
     "Tư duy pha loãng — nội dung an toàn, đơn giản đến mức không nuôi trí.",
     "Bài diễn văn của chính trị gia chủ yếu là lời nhạt nhẽo: những hứa hẹn mơ hồ chẳng ghim được vào đâu.",
     "nuôi", "phương tiện, công cụ"),
    ("Gây ngủ hoặc buồn ngủ.",
     "Nhàm — hoặc đúng nghĩa an thần — đến mức buồn ngủ. Nghĩ sữa ấm, hoặc họp ngân sách ba giờ.",
     "Giọng đều đều gây buồn ngủ của bài giảng khiến nửa căn phòng phải chống mí mắt.",
     "giấc sâu", "làm, gây"),
    ("Quá nịnh nọt, thái độ nhờn.",
     "Mượt đến mức trơn — nịnh phủ dày đến mức tưởng sờ thấy mỡ.",
     "Người bán hàng nịnh nhờn cứ khen \"gu tuyệt vời\" của tôi trước mỗi lần mời mua thêm.",
     "xức dầu", "đầy"),
    ("Sẵn sàng bắt lỗi, phê quá mức chuyện vặt.",
     "Bới lông tìm vết đến mức bệnh — người tìm vấn đề ở mọi thứ, dù chẳng quan trọng.",
     "Những ghi chú bắt bẻ của anh trên báo cáo chỉ chăm chăm vào chỗ đặt dấu phẩy.",
     "nắm, lấy", "bẫy, ngụy biện"),
    ("Uể oải, trí hay thân không hoạt động.",
     "Chậm và nửa ngủ, như gấu ngủ đông — hầu như không cử động, không nghĩ.",
     "Văn phòng trở nên uể oải trong cái nóng nặng nề của tháng Tám.",
     "tê, uể", "ở trạng thái"),
    ("Quản gia hay quan chức quản hộ gia đình thời trung cổ.",
     "Phiên bản trung cổ của trưởng nhân sự — viên tin cậy chạy nhà và thái ấp lãnh chúa từng ngày.",
     "Viên quản gia của lâu đài trông coi mọi thứ, từ sổ sách mùa màng đến danh sách khách.",
     "già, cao niên", "đầy tớ"),
    ("Nói hoặc viết dài về một đề tài.",
     "Thật sự vào guồng — nói viết mãi, phủ mọi góc.",
     "Hỏi ông ấy về xe cổ là ông sẽ thao thao suốt cả một tiếng đồng hồ.",
     "ra", "không gian"),
    ("Không giá trị, vụn vặt; cũng vô hiệu hoặc không hiệu lực.",
     "Gần như chẳng đáng gì — một điều khoản vô hiệu trong hợp đồng là điều khoản thực ra chẳng làm được gì.",
     "Tòa phán rằng quy chế cũ là vô hiệu, vì nó chưa từng thực sự được thi hành.",
     "chuyện vặt, vô nghĩa", "thuộc về"),
    ("Trí tuệ, phán đoán sắc.",
     "Trí khôn thực dụng sắc — phán đoán hay từ kinh nghiệm, không chỉ sách vở.",
     "Sự minh mẫn của ông thuyền trưởng già đã giữ thủy thủ đoàn khỏi rắc rối hơn một lần.",
     "khứu giác tinh, sắc sảo", "phẩm chất của"),
    ("Đám đông hạ lưu, quần chúng, dùng khinh bỉ.",
     "Từ kiêu kỳ, khinh để gọi \"đám hạ lưu\" hay dân thường.",
     "Bá tước khinh khỉnh nhìn đám tiện dân tụ tập ngoài cổng cung điện.",
     "chó", "tập thể, bầy"),
    ("Đối xử hoặc ngôn từ xấc xược, làm nhục.",
     "Đối xử tàn nhẫn, khinh nhằm làm nhục — lời sỉ nhục thiết kế để đau.",
     "Ông chịu đựng nhiều năm bị nhục mạ từ giới phê bình trước khi tác phẩm cuối cùng được công nhận.",
     "cùng, triệt để", "phồng (vì kiêu)"),
    ("Với nghi ngờ hoặc không tán thành; cái nhìn nghiêng.",
     "Cái liếc nghiêng bạn dành cho thứ chưa tin — ánh nhìn đầy nghi.",
     "Cô giáo nhìn nghi ngại bài tập về nhà sạch sẽ đến mức đáng ngờ.",
     "tới, về", "nghiêng, lệch"),
    ("Người ngu; đồ đần.",
     "Lời chửi cổ, gần như trìu mến cho kẻ đang đần — đồ đần.",
     "\"Đồ ngốc nghếch,\" cô cười, \"cậu cầm ngược bản đồ suốt từ nãy giờ.\"",
     "cục đất", "đầu"),
    ("Đưa vào chuyển động hay hành động; thúc đẩy.",
     "Là tia lửa khiến thứ gì chuyển — máy bật hay người cuối cùng hành động theo ý.",
     "Nỗi sợ mất hợp đồng đã thúc cả đội vào một cuối tuần tăng ca.",
     "việc làm, sự thúc", "thúc, làm"),
    ("Tham ô quỹ được giao trông.",
     "Lặng lẽ lấy tiền người ta tin bạn giữ — tham ô khoác áo cổ.",
     "Vụ tham ô của viên thủ quỹ suốt gần mười năm không ai hay biết.",
     "tài sản riêng", "gia súc, của cải"),
    ("Nhóm bị coi ở rìa xã hội đàng hoàng.",
     "Thế giới ngầm xã giao lấp lánh-nhưng-mờ ám — người sống sát ngoài luật \"đàng hoàng\".",
     "Tiểu thuyết theo chân một ca sĩ lần bước trong giới bên lề của các quán cabaret thập niên 1920.",
     "nửa", "thế giới, xã hội"),
    ("Vẫn còn tồn tại; chưa tuyệt hay bị hủy.",
     "Vẫn còn hôm nay — dùng cho thứ cũ (bản thảo, loài, nhà) sống sót được.",
     "Người ta chỉ biết đến ba bản còn tồn tại của lần in đầu tiên.",
     "ra", "đứng"),
    ("Sự lừa dối; phản bội lòng tin.",
     "Phản bội sâu, cố ý — phá lòng tin người ta có quyền mong bạn giữ.",
     "Vị tướng không bao giờ tha thứ sự bội tín của người bạn cũ tại bàn đàm phán.",
     "xuyên, chống", "đức tin, tin"),
    ("Phương ngữ vùng, nhất là phi chuẩn.",
     "Cách nói địa phương riêng — đầy từ và nhịp người ngoài có thể không bắt được.",
     "Bà ngoại cô vẫn nói thổ ngữ của đảo trong những bữa tối gia đình.",
     "lời thô, phương ngữ", "chân — lời vụng"),
    ("Quyền đặc biệt thuộc về một người hay nhóm.",
     "Đặc quyền chỉ của bạn — quyền đi kèm vai, chức hay địa vị.",
     "Chọn nơi nghỉ của cả nhà là đặc quyền của ông, và ai cũng biết điều đó.",
     "trước", "hỏi, bỏ phiếu"),
    ("Sự táo bạo, gan; cũng sự bền và chịu đựng.",
     "Sức bền gan góc — can đảm xông tới và sự cứng để tiếp tục khi đã đi.",
     "Phải có gan thật sự mới vượt được con đèo trong bão tuyết mà không có bản đồ.",
     "táo, cứng cỏi", "trạng thái, điều kiện"),
    ("Nở rộ; cũng phát triển hoặc hiện dần.",
     "Nở thành biểu đạt đầy đủ — như hoa mở, hay ý tưởng cuối cùng thành chính nó.",
     "Tài vẽ lặng lẽ của cô nở rộ khi cô có được một xưởng riêng.",
     "ra", "bắt đầu nở"),
    ("Dây có quả nặng để xác định thẳng đứng; ẩn dụ là chuẩn phán đoán.",
     "Quả nặng trên dây treo thẳng xuống, dùng kiểm xem có thật thẳng đứng — và, rộng ra, mọi chuẩn cố định bạn đo thứ khác.",
     "Ông lấy sự ngay thẳng của ông nội mình làm một thứ dây dọi cho mọi quyết định.",
     "chì", "dây, thước"),
    ("Vui vẻ, sẵn lòng (cổ).",
     "Cách nói cổ cho \"vui vẻ\" hay \"sẵn lòng\".",
     "\"Ta những muốn nghỉ lại đây một lát,\" người lữ khách thở dài.",
     "vui, hớn hở", "vui vẻ, sẵn lòng"),
    ("Chỉ trích công khai gay gắt hoặc ô nhục.",
     "Nỗi xấu hổ công khai chất lên ai đó rõ ràng — ô nhục từ sự không tán thành rộng.",
     "Vụ tai tiếng trút sự ô nhục công khai xuống cả hãng.",
     "chống", "ô nhục, trách"),
    ("Mỉa sắc, dí dỏm hay phê có răng cắn.",
     "Trí tuệ có răng — một lời cay sắc làm đau một chút, chính vì nó nhắm quá khéo.",
     "Những bài điểm phim cay sắc của cô bị các đạo diễn sợ và được độc giả yêu.",
     "cắn", "cắn, đang làm"),
    ("Tuyên bố chính thức, thường chính trị hoặc quân sự.",
     "Thông báo lớn, chính thức — thường tuyên bố chính phủ mới, nổi dậy, hay sắc lệnh lớn.",
     "Bản tuyên cáo của vị tướng công bố chính phủ mới vào lúc bình minh.",
     "ra phía trước", "công bố"),
    ("Người kiến thức nông mà giả làm chuyên gia.",
     "Kẻ chỉ lướt mặt đề tài rồi nói như đã viết sách giáo khoa.",
     "Kẻ học đòi trong bữa tiệc tối tự tin sửa lưng nhà vật lý thiên văn thật sự ngồi cùng bàn.",
     "biết", "chỉ nhỏ — kẻ biết bé"),
    ("Suy giảm năng lực trí tuệ tuổi già.",
     "Khoảng già rất muộn, hay quên, khi sự sắc của trí bắt đầu phai.",
     "Trong tuổi lẫn, ông kể cùng ba câu chuyện ấy mỗi lần có khách, lần nào cũng như thể nó mới.",
     "lú lẫn, hóa ngốc", "trạng thái hay kết quả"),
    ("Phía khuất gió.",
     "Phía yên, được che — đồi, tàu, tường — nơi gió không với tới bạn.",
     "Nhóm đi bộ dựng lều ở phía khuất gió của sống núi để tránh những cơn giật.",
     "che, bảo vệ", "sườn, mặt"),
    ("Gạt hay đỡ một đòn, câu hỏi hay luận.",
     "Gạt nhẹ nhàng — nhát kiếm, câu hỏi khó xử hay lời buộc tội — không lệch nhịp.",
     "Cô gạt câu hỏi hiểm của phóng viên bằng một câu đùa nhẹ.",
     "đỡ", "chuẩn bị, phòng"),
    ("Hôi thối, độc hại.",
     "Hôi đến mức gần như độc — mùi tệ đến tưởng nguy hiểm khi thở.",
     "Một mùi hôi thối bốc lên từ đầm lầy khi mặt trời lặn.",
     "hơi độc", "mang bản chất"),
    ("Người tận tụy với xa hoa và khoái lạc.",
     "Sống vì tiện nghi và hưởng thụ — đồ ngon, giường êm, đời dễ — lấy tên thành Hy Lạp cổ Sybaris nổi tiếng thái quá.",
     "Một kẻ ham hưởng lạc đích thực, ông từ chối bất kỳ phòng khách sạn nào không có bồn tắm.",
     "thành Hy Lạp cổ nổi tiếng xa hoa", "cư dân của"),
    ("Cố ý gác hay bỏ qua một phần.",
     "Cố tình để một mảnh ghép sang một bên trong đầu, để tập trung sạch phần còn.",
     "Hãy tạm gác chi phí sang một bên và chỉ hỏi xem kế hoạch có thực sự chạy được không.",
     "trước, xa", "cắt"),
    ("Phê nghiêm khắc; cũng lột da.",
     "Xé ai đó bằng phê gay — bằng lời, như đang lột da thật.",
     "Giới phê bình đả kích phần tiếp theo vì đã phản bội mọi điều người hâm mộ yêu ở bản gốc.",
     "ra khỏi", "da, bì"),
    ("Dẫn ra làm bằng chứng.",
     "Đưa sự kiện hay ví dụ chống lưng luận điểm — thứ bạn chỉ khi ai hỏi \"what's your evidence?\".",
     "Luật sư dẫn ra ba nhân chứng để củng cố bằng chứng ngoại phạm của thân chủ.",
     "tới, về phía", "dẫn"),
    ("Những chuyến đi hay lang thang, nhất là dài và rộng.",
     "Hành trình dài, lang thang — sự đi lang rộng đưa bạn xa nhà khá lâu.",
     "Những chuyến lãng du của ông qua ba châu lục lấp đầy cả một tầng giá nhật ký du hành.",
     "xuyên", "đồng, đất (peregrinus: người ngoại)"),
    ("Kẻ ăn xin, hoặc sống bằng bố thí.",
     "Người sống nhờ xin từ thiện — lịch sử cũng chỉ tu sĩ khấn nghèo, sống nhờ quyên.",
     "Các tu sĩ khất thực không sở hữu gì và hoàn toàn dựa vào lòng tốt của dân làng.",
     "xin", "kẻ ăn xin"),
    ("Cực kỳ hào phóng.",
     "Hào phóng quy mô lớn, gần khoe — món quà khiến người ta hơi nín thở.",
     "Khoản quyên tặng hào phóng đã tài trợ cả cánh mới của thư viện.",
     "quà, phục vụ", "làm, cho"),
    ("Kiệt sức vì thiếu nuôi dưỡng; cũng thiếu sinh lực.",
     "Trạng thái yếu, cạn vì không được nuôi hay tiếp nhiên liệu — đói thật, hoặc không còn gì để chạy.",
     "Đến cuối cuộc vây hãm, những người lính đã gần kiệt lả.",
     "rỗng, trống", "hành vi hay kết quả"),
    ("Phê cay độc, lăng mạ.",
     "Phê đã vượt công bằng thành trận mắng giận, đắng.",
     "Các bình luận trực tuyến tan thành lời lăng mạ thuần túy chỉ trong vài phút.",
     "lỗi", "sắm, cung"),
    ("Thù địch, hại về hiệu quả.",
     "Làm việc chống bạn, dù lặng — điều kiện hay thái độ không thân với lợi ích bạn.",
     "Chính sách mới gây hại cho các doanh nghiệp nhỏ, dù đó không phải là ý định.",
     "không", "bạn"),
    ("Dễ gây oán hay bất mãn, thường qua so sánh bất công.",
     "Chắc chắn làm ai đó cảm thấy bị xem thường — thường vì xếp người hay vật bất công.",
     "Xếp hạng anh chị em theo \"mẹ thương ai nhất\" là một trò gây oán mà không ai nên chơi.",
     "ghen", "nhìn (với ác ý)"),
    ("Người cấp thấp hơn; thuộc cấp.",
     "Người thấp hơn chuỗi mệnh lệnh hay thang xã hội — kẻ dưới quyền người mạnh hơn.",
     "Khi còn là một sĩ quan cấp dưới trẻ tuổi, ông nhận lệnh từ rất lâu trước khi được ra lệnh.",
     "dưới", "thay thế, khác"),
    ("Cảm hoặc bày tỏ lòng căm ghét mạnh.",
     "Ghét đến mức nguyền rủa to — sự ghê tởm thuần, có tiếng.",
     "Dân làng nguyền rủa viên thu thuế mỗi khi chiếc xe của ông lăn qua phố.",
     "ra khỏi", "thiêng (nguyền ra khỏi cái thiêng)"),
    ("Lớp phủ ngoài tự nhiên, như da hay vỏ.",
     "Gói bảo vệ của chính thiên nhiên — da, mai, vỏ, cùi, thứ che và chắn sinh vật.",
     "Mai rùa là một lớp vỏ ngoài bền một cách đáng nể.",
     "trên, phủ", "che"),
    ("Ngây thơ, cả tin, đơn giản như trẻ; ngược \"disingenuous\".",
     "Tin tưởng lộ liễu và hơi ngây, không âm mưu — dễ lẫn với \"ingenious\" nghĩa là khéo.",
     "Câu hỏi ngây thơ của cô — \"sao lại có người nói dối chuyện đó?\" — cho thấy cô ít mánh khóe đến mức nào.",
     "trong, bản địa", "sinh (tự do, thẳng thắn)"),
    ("Bận tâm quá mức chi tiết nhỏ hay quy tắc.",
     "Lạc trong quy tắc nhỏ mà bỏ bức tranh lớn — ám ảnh chữ nhỏ chẳng ai quan tâm.",
     "Sự câu nệ của ông về dấu phẩy Oxford làm trật cả cuộc họp.",
     "gia sư trẻ em", "thói hay phẩm chất"),
    ("Sự xem xét kỹ, cẩn thận.",
     "Cái nhìn sâu, không bỏ viên đá nào — soi từng chi tiết thật sự.",
     "Chỉ sau một cuộc soi xét kỹ lưỡng đống sổ sách, chỗ chênh lệch mới lộ ra.",
     "xuyên, triệt để", "tìm, xét"),
    ("Đưa phản đối; tỏ sự miễn cưỡng.",
     "Lịch sự đẩy lại hoặc do dự thay vì thuận ngay — \"I'd rather not\" mềm.",
     "Khi được yêu cầu ký mà không đọc, cô đã ngần ngại từ chối.",
     "từ, xa", "trì hoãn"),
    ("Thoạt nhìn hợp lý nhưng thực ra sai.",
     "Nghe thuyết phục lúc đầu nhưng sụp ngay khi thật sự kiểm.",
     "\"Everyone's doing it\" là một lập luận nghe xuôi tai mà chẳng bao giờ đứng vững khi bị soi.",
     "bề ngoài, vẻ", "đầy (trông đẹp)"),
    ("Lời không thành, đạo đức giả, thường dạy đời.",
     "Lời giảng nghe đức hạnh nhưng không có cảm xúc thật — tư thế đạo đức chạy tự động.",
     "Anh đã chán những lời đạo đức giả của công ty về \"gia đình\", từ một hãng chưa bao giờ cho ai nghỉ phép.",
     "hát (sau: tiếng lóng đều)", "lời rên của kẻ xin, rồi đạo đức giả"),
    ("Thiếu dũng khí, nhát.",
     "Nhút nhát đến mức không xương sống — quá sợ để đứng lên dù rõ là quan trọng.",
     "Sự im lặng nhát gan của hội đồng để vụ tai tiếng xoáy đi mất kiểm soát.",
     "rất nhỏ", "tinh thần, can đảm"),
    ("Giống cáo; xảo quyệt, mánh.",
     "Láu và khôn như cáo — nhanh trí, hơi lén, luôn hơn một bước.",
     "Anh nhe một nụ cười ranh mãnh ngay khi thấy kẽ hở.",
     "cáo", "của hoặc giống"),
    ("Lần lượt, theo thứ tự.",
     "Lấy từng cái một, đúng thứ tự — không nhảy, không làm hai cái một lúc.",
     "Thẩm phán xử lần lượt từng yêu sách một trong cả mười hai yêu sách.",
     "hàng, dãy", "từng cái một"),
    ("Keo kiệt cực độ; hà tiện.",
     "Siết tiền (hay lời, nguồn) quá mức tiết kiệm hợp lý.",
     "Sự bủn xỉn của ông là huyền thoại — một túi trà ông dùng lại đến ba lần.",
     "tiếc, tiết kiệm", "trạng thái hay thói"),
    ("Sửa chữa, nhất là trong văn bản.",
     "Chỉnh cho một bài viết — chỉnh học thuật sửa lỗi văn bản cũ hay quan trọng.",
     "Ấn bản mới gồm hàng chục chỗ hiệu đính cho bản thảo gốc.",
     "ra khỏi", "lỗi, sai"),
    ("Điều độ trong ăn uống.",
     "Cố ý kiêng quanh đồ ăn thức uống — không bao giờ quá, luôn chừa chút trên đĩa.",
     "Thói quen tiết độ giữ ông sắc sảo rất lâu sau khi bạn bè đồng trang lứa đã chậm lại.",
     "xa khỏi", "đồ uống gây say"),
    ("Lỗi ngữ pháp hoặc phạm phép lịch sự.",
     "Sảy trong ngữ pháp hay phép tắc — lỗi nhỏ làm người khó tính nhíu mặt.",
     "\"Between you and I\" là một lỗi ngữ pháp phổ biến vẫn làm các nhà ngữ pháp giật mình.",
     "thành Cilicia nổi tiếng tiếng Hy Lạp 'xấu'", "thói, cách"),
    ("Liên quan xung đột trong nhóm; hủy diệt lẫn nhau.",
     "Đấu đá nội bộ xé nhóm từ trong — trận mọi người thua vì nhà đánh nhà.",
     "Những cuộc cãi vã nội bộ của đảng gây hại hơn bất kỳ đối thủ bên ngoài nào.",
     "giữa, trong số", "giết"),
    ("Thái độ thờ ơ, cẩu thả.",
     "Cái nhún vai thành cả tính cách — quan tâm ít đến thứ từng quan trọng đến mức chẳng gì đáng sức.",
     "Thái độ thờ ơ của anh với lễ trao giải làm ngạc nhiên tất cả những ai biết anh đã làm việc cực nhọc đến đâu.",
     "ít", "quan tâm"),
    ("Tình huống hay tranh chấp rối, phức tạp.",
     "Tình rối, bẩn khó hiểu — một phần hiểu lầm, một phần kịch, toàn rối.",
     "Cả mớ bòng bong sơ đồ chỗ ngồi bắt đầu từ một tấm thẻ tên đặt sai chỗ.",
     "trong", "vướng, làm rối"),
    ("Đe dọa, hăm dọa.",
     "Mang một luồng khí đe dọa không thể nhầm — một cái nhìn hay một bức thư đe dọa nói rất rõ rằng điều xấu có thể theo sau.",
     "Giọng đe dọa của bức thư làm người thuê nhà lo lắng trước cả khi cô mở phong bì.",
     "đe", "có tác dụng"),
    ("Chỉ trích công khai mạnh hoặc lăng mạ.",
     "Kết án công khai ầm ĩ — phê cháy bỏng diễn ra trước mọi người.",
     "Người tố giác đối mặt nhiều năm bị bêu riếu công khai trước khi lịch sử chứng minh cô đúng.",
     "chống", "nói"),
    ("Cơn bùng nổ đột ngột dữ dội, cảm xúc hay hành động.",
     "Cơn mạnh đột ngột nuốt bạn một lúc — cơn cười, giận hay ho đập như sóng.",
     "Cô bị một cơn cười bùng phát mà cô không giải thích nổi với bất kỳ ai khác trong phòng.",
     "vượt", "sắc, cấp"),
    ("Được thêm từ nguồn ngoài, không vốn có.",
     "Bắt ốc từ ngoài chứ không xây từ đầu — phần thêm, không lõi.",
     "Lời bình có cảm giác thêm thắt từ ngoài, như thể được dán vào một văn bản đã hoàn tất.",
     "tới, thêm", "chuẩn y, nhận lấy"),
    ("Thiếu hiểu biết, sự không biết.",
     "Sự không-biết giản dị — lỗ hổng kiến thức, không gắn phán xét.",
     "Ông thừa nhận sự không biết của mình về rượu vang Pháp và để người phục vụ rượu chọn.",
     "không", "biết"),
    ("Hứng thú quá mức với chuyện tình dục.",
     "Tò mò háo hức, liếc về thứ tục — hứng thú đã qua lành mạnh thành tọc mạch.",
     "Sự tọc mạch dâm tục của tờ lá cải với đời tư của cặp đôi gần như đã thành ám ảnh.",
     "ngứa, khao khát", "trạng thái"),
    ("Đầy muội, tối, đục.",
     "Tối và khói, như mọi thứ phủ lớp muội mỏng.",
     "Một màn mù đầy muội treo trên thị trấn nhà máy lúc chạng vạng.",
     "muội", "đầy"),
    ("Phủ nhận hoặc bác.",
     "Nói ngược phăng phăng điều người khác nói — nói \"that's not so\".",
     "Không ai dám bác lời kể của ông thuyền trưởng già về cơn bão.",
     "chống", "nói"),
    ("Sự lười nhác, biếng nhác (từ Latinh).",
     "Từ Latinh cổ cho sự lười thuần — cái kéo của không muốn làm gì.",
     "Các tu sĩ giảng chống lại sự biếng nhác như một trong những mối nguy lặng lẽ của linh hồn.",
     "không", "bận, siêng"),
    ("Khiên trưng huy hiệu.",
     "Huy hình khiên khoe quốc huy gia tộc — \"biển tên\" huy chương.",
     "Tấm khiên huy hiệu của gia đình vẫn treo trên cửa chính của trang viên cũ.",
     "khiên", "chỉ nhỏ / vật"),
    ("Lỗi thời, lỗi mốt, hoặc nghỉ vì tuổi.",
     "Quá thời hữu ích và bị thả đồng — quá cổ hoặc mòn để còn làm việc.",
     "Chiếc máy in cũ kỹ lỗi thời cuối cùng cũng được thay sau mười lăm năm kẹt giấy.",
     "vượt", "năm"),
    ("Vật thay, đặc biệt trong y khoa.",
     "Thuốc thế khi trị liệu thật không có — về cơ bản là vai phụ y khoa.",
     "Bác sĩ thời chiến thường dựa vào các vị thuốc thay thế khi thuốc đúng đã hết.",
     "thay chỗ", "đi, nhường"),
    ("Lời khoe khoang, hống hách.",
     "Khoe ầm ĩ — nói to về sự vĩ đại của mình, phần lớn là gió.",
     "Lời khoác lác của anh về việc \"một mình\" cứu dự án chẳng lừa được ai từng có mặt ở đó.",
     "hiệp sĩ khoe trong Orlando Furioso", "hành động, khoe"),
    ("Dùng mánh hoặc lừa để đạt điều gì.",
     "Lách tới mục tiêu bằng mánh lén chứ không chơi công bằng.",
     "Anh dùng mánh khóe len vào vụ làm ăn bằng một hợp đồng đầy chữ nhỏ.",
     "bắt bẻ, lừa", "mánh; sau là cua gắt"),
    ("Khoa học thuần hay trừu tượng của học hay tri thức, thường toán.",
     "Học ở dạng thuần nhất, trừu tượng nhất — cấu trúc sâu của chính tri thức, nhất là kiểu toán.",
     "Triết gia mơ về một khoa học phổ quát về tri thức có thể thống nhất mọi lĩnh vực hiểu biết.",
     "học", "hành vi học"),
    ("Quá bận tâm quy tắc hình thức hay chi tiết vụn.",
     "Quá khắt khe chuyện nhỏ — sửa tiểu tiết kỹ thuật chẳng đổi gì.",
     "Cãi nhau về \"who\" với \"whom\" trong một tin nhắn thì hơi câu nệ.",
     "người dẫn trẻ, gia sư", "mang cách của"),
    ("Ánh chớp, lấp lánh.",
     "Tia lấp lánh nhanh — nghĩ nắng nảy trên nước, hay kim cương bắt sáng.",
     "Ánh lấp lánh của chiếc đèn chùm rải sáng khắp mọi góc phòng khiêu vũ.",
     "lấp lánh, chớp", "hành vi ấy"),
    ("Người mới bắt đầu, tập sự.",
     "Người hoàn toàn mới với kỹ năng hay lĩnh vực — còn học đường đi, chưa chuyên gia.",
     "Ngay cả một người mới chơi cờ vua cũng nhận ra nước đi hỏng đó.",
     "lính mới, tập sự", "lính trẻ thô"),
    ("Cực tệ, đáng ghê.",
     "Tệ đến mức đáng ghê thật — không chỉ \"tàm tạm\", mà thật đáng ghét.",
     "Người điểm phim gọi phần tiếp theo là tệ hại, và những con số phòng vé cũng đồng ý.",
     "nguyền", "đáng, có thể bị"),
    ("Màu đỏ máu.",
     "Đỏ sâu, tươi — màu máu tươi, nổi tiếng qua Macbeth của Shakespeare.",
     "Hoàng hôn nhuộm cả bầu trời một ánh đỏ máu.",
     "vào", "thịt (đỏ thịt)"),
    ("Khe nhỏ hay khoảng giữa các thứ.",
     "Khoảng giữa tí hon dễ bỏ qua — khe sàn, lỗ trong lịch.",
     "Cỏ dại đội lên qua từng kẽ hở trên lối gạch cũ.",
     "giữa", "đứng"),
    ("Lời phê hay trách.",
     "Nhận xét sắc, không tán thành — kiểu phê mang giọng mắng nhẹ.",
     "Những lời trách cứ của giáo sư trên bài luận phủ đầy lề bằng mực đỏ.",
     "tâm trí", "quay về phía"),
    ("Không thể bác, không chối cãi.",
     "Chứng vững đến mức không tranh — vụ coi như đóng.",
     "Bằng chứng DNA là không thể bác bỏ, và phiên tòa kết thúc trong vòng một giờ.",
     "không", "chống, kháng"),
    ("Sự phức tạp, rối rắm; cũng sự cuộn vào trong.",
     "Phức tạp gấp vào chính nó — thứ quấn chặt khó kéo rời.",
     "Sự rối rắm của cốt truyện khiến nửa khán giả còn ngồi gỡ mãi sau khi phim đã hết.",
     "vào, hướng trong", "cuộn, xoay"),
    ("Sức hay nỗ lực, như trong \"by dint of\".",
     "Nỗ lực hay sức thuần — ngày nay chủ yếu sống trong cụm \"by dint of\".",
     "Anh đỗ kỳ thi nhờ vào sự luyện tập thuần túy và bướng bỉnh.",
     "một đòn, một nhát", "bằng sức của"),
    ("Được ghép bằng mộng-then; khớp chắc.",
     "Khóa theo cách thợ mộc cũ — một mảnh lọt khít lỗ cắt riêng cho nó.",
     "Những cây kèo của kho thóc cũ được ghép mộng vào nhau mà không cần một cái đinh nào.",
     "ổ, lỗ", "miếng cắn, nắm"),
    ("Rất đúng chỗ, thích hợp.",
     "Vừa khít khoảnh khắc — nhận xét, trích hay ví dụ đáp đúng điểm.",
     "Lời nhận xét đúng chỗ của cô tóm gọn cả cuộc tranh luận trong một câu.",
     "tới", "đặt"),
    ("Phát sáng hay nhấp nháy dịu (ánh); cũng trí tuệ nhẹ.",
     "Sáng dịu chứ không cháy — ánh nhấp nháy mềm, hay trí tuệ vui chứ không sắc.",
     "Ánh nến đổ một quầng sáng dịu khắp căn phòng ăn cũ.",
     "liếm", "làm (ánh \"liếm\")"),
    ("Ẩn sĩ tôn giáo sống cô độc.",
     "Người rút hoàn toàn khỏi đời để sống một mình trong cầu nguyện và suy tưởng.",
     "Vị ẩn sĩ sống trong một căn phòng nhỏ gắn vào nhà thờ suốt hơn ba mươi năm.",
     "lùi, xa", "rút"),
    ("Làm thỏa cơn khát; dập tắt.",
     "Làm thỏa hoàn toàn cơn thèm — thường là khát, ẩn dụ là mọi nhu cầu sâu.",
     "Một cốc nước lạnh làm dịu cơn khát của anh sau chuyến đi bộ dài.",
     "lỏng, chùng", "nới, dịu"),
    ("Hình kim.",
     "Dài, mảnh, nhọn như kim — hình lá thông hay tinh thể nhỏ sắc.",
     "Cây thông dễ nhận ra nhờ những chiếc lá hình kim.",
     "kim", "nhỏ"),
    ("Hết sinh lực, yếu, tinh tế quá mức.",
     "Mòn và mềm — mất sức và khí gốc vì quá tiện nghi hay tinh tế.",
     "Giới phê bình gọi tờ tạp chí từng táo bạo ấy là cạn kiệt sinh lực, chỉ còn là cái bóng của những năm đầu mạnh mẽ.",
     "ra", "nhiều quả, đã sinh"),
    ("Phụ kiện hay quyền nhỏ kèm theo.",
     "Phần thêm nhỏ đi kèm thứ lớn hơn — phụ kiện và phần thêm thuộc về vật chính.",
     "Hợp đồng thuê bao gồm cả nhà để xe và mọi phụ thuộc kèm theo.",
     "tới", "thuộc về"),
    ("Che hoặc giảm nhẹ lỗi.",
     "Làm mượt sai bằng lời mềm, nghe nhỏ hơn thực.",
     "Anh cố lấp liếm cái hạn chót đã lỡ bằng những lời mơ hồ về \"những thách thức không lường trước\".",
     "chú giải, lời giải", "chú — rồi làm mượt"),
    ("Ở giai đoạn sớm, vừa bắt đầu.",
     "Vừa lộ diện — giai đoạn đầu, gần như không thấy, của thứ lớn hơn sẽ đến.",
     "Các bác sĩ bắt được những dấu hiệu chớm phát của căn bệnh trước khi nó kịp lan.",
     "trên, vào", "lấy (nhấc, bắt đầu)"),
    ("Cảm hứng sáng tạo, nhất là thần thánh.",
     "Cơn cảm hứng đột ngột lớn hơn bạn — như ý bị thổi vào từ nơi khác.",
     "Nhà thơ kể rằng cả bài thơ đến trong một đợt cảm hứng thần khải lúc 3 giờ sáng.",
     "tới, trên", "thổi (thổi lên trên)"),
]
