# Filipino (Tagalog) rows: (definition, friendly, exampleGloss, root1, root2)
ROWS = [
    ("Patamisin o linisin; alisin ang tigas sa isang bagay.",
     "Tanggalin ang kagat o pait — talagang patamisin, o sa talinghaga ay palambutin ang magaspang na kaisipan para madaling lunukin.",
     "Pinalambot ng editor ang malupit na rebyu bago ito ipalimbag.",
     "palabas, lubusan", "matamis"),
    ("Sobra o pilit na relihiyoso o deboto.",
     "Parang palabas ang debosyon ng tao — mas teatro kaysa tunay na pananampalataya.",
     "Ang mapagbanal-banalang buntong-hininga niya sa sermon ay nakainis sa buong upuan.",
     "kabanalan, katungkulan", "may katangian ng"),
    ("Kalabuan mula sa kayarian ng balarila — pangungusap na mababasa nang dalawang paraan.",
     "Pangungusap na tama ang balarila pero dalawang magkaibang basahin, tulad ng \"I saw the man with the telescope.\"",
     "Klasikong kalabuan ng balarila ang \"Visiting relatives can be tiring\" — ang mga kamag-anak ba ang nakakapagod, o ang pagdalaw sa kanila?",
     "pareho, sa magkabilang panig", "ihagis"),
    ("Matulis, tumatagos, tumatama agad sa punto.",
     "Tumatawid sa palamuti — ang matalas na puna o isip ay mabilis umabot sa puso ng usapin, walang nasayang na salita.",
     "Ang kanyang matalas na puna ay walang naiwang taguan para sa mga butas ng pelikula.",
     "gupitin", "paggawa, pagkakaroon ng katangian"),
    ("Kakasimula pa lang; nasa maaga o payak na yugto.",
     "Nasa mga unang sandali pa — plano, damdamin, o lakad na kasisimula pa lang magkaroon ng hugis.",
     "Ang pasimulang yugto ng kasunduan ay puno ng pangako, pero maraming detalye ang hindi pa tapos.",
     "magsimula, umpisahan", "humahilig tungo"),
    ("Pormal na talumpati o sulat na lubos na pumupuri sa isang tao.",
     "Buong-buong pormal na parangal — isipin ang nagniningning na papuri sa patay, o talumpating umaawit ng mga nagawa mula sa bubong.",
     "Pinaalis ang retiradong propesor sa isang talumpating pambunyi mula sa pinakamalapit niyang mag-aaral.",
     "lahat", "pagtitipon, pulong"),
    ("Tungkol sa tunay na pag-iral o katotohanang pagiging, hindi teoryang walang laman.",
     "Tungkol sa mga bagay kung paano talaga umiiral, hindi lang bilang kaisipan o teorya tungkol sa kanila.",
     "Pinagdedebatehan ng mga pilosopo kung may katayuang pang-iral ang mga bilang o nasa isip lang natin.",
     "pagiging, ang umiiral", "may kinalaman sa"),
    ("Magbunga, o maging mabunga.",
     "Sa wakas ay magbunga — pagsisikap, kaisipan, o puhunang lumaki mula sa buto tungo sa may silbi.",
     "Ang mga taon ng tahimik na pananaliksik ay sa wakas ay nagbunga ng bakunang gumagana.",
     "bunga", "gawin, magdulot"),
    ("Inaabangan o inilalarawan ang isang bagay na parang tapos na bago pa talaga mangyari.",
     "Pang-aklatang pagmamadali — ilarawan ang hinaharap na pangyayari na parang tapos na, para mas tumama ang punto.",
     "Ang patiunang pagtatagay ng heneral sa \"tagumpay\" ay naihatid isang buong linggo bago ang laban.",
     "bago", "kunin, agawin"),
    ("Pinapatakbo ng presyon ng hangin; may kinalaman din sa espiritu o hininga.",
     "Karaniwang ibig sabihin ay \"pinapatakbo ng siksik na hangin\" — bagaman maaari ring may kinalaman sa espiritu o hininga.",
     "Humuni ang prenong de-hangin nang huminto ang bus sa bangketa.",
     "hangin, hininga, espiritu", "may kinalaman sa"),
    ("Paglalarawan sa Diyos o sa banal sa pamamagitan ng positibong pahayag — kabaligtaran ng apopatiko.",
     "Paraan ng pag-usap tungkol sa Diyos sa pamamagitan ng sinasabi kung ano Siya — \"God is love\" — hindi lang kung ano ang hindi Niya.",
     "Ang katapatikong teolohiya ay nagsasalita nang may tiwala tungkol sa Diyos bilang mapagmahal, makatarungan, at maawain.",
     "pababa, ayon sa", "magsalita, sabihin"),
    ("Nakabatay sa tiwala o pananampalataya; ginagamit din bilang nakapirming pananda.",
     "Isang bagay na tinatanggap mo sa tiwala tapos ginagawang angkla — ang panandang sanggunian ang nakapirming pook na sinusukat ang lahat.",
     "Naglagay ang mga tagasukat ng panandang sanggunian sa batong-ugat bago imapa ang lugar.",
     "magtiwala", "tiwala, pananalig"),
    ("Pagtatanggol sa kabutihan ng Diyos dahil sa pag-iral ng kasamaan.",
     "Ang sinaunang pagtatangka sagutin ang \"Kung mabuti ang Diyos, bakit may kasamaan?\"",
     "Tiningnan ng kanyang tesis ang teodisiya sa lente ng Aklat ni Job.",
     "diyos", "katarungan"),
    ("Pagsasamahang pananahanan — katagang teolohiko kung paano naninirahan ang mga persona ng Trinidad sa isa't isa.",
     "Salitang teolohiya para sa pagiging tatlo-sa-isa na ganap na naglalaman at nilalaman ng bawat isa.",
     "Sinusubukan ng aral ng pagsasamahang pananahanan ipaliwanag kung paano magkakaiba ngunit hindi mapaghihiwalay ang Ama, Anak, at Espiritu.",
     "sa paligid", "lumakad, maglakad"),
    ("Magkaroon ng kahihinatnang nakikinabang o bumabalik sa isang tao.",
     "Kapag ang papuri (o sisi) ay tumalbog pabalik sa responsable — ang mabubuting gawang bumabalik sa pangalan mo ay gantimpala rin.",
     "Ang tagumpay ng koponan ay babalik bilang parangal sa tahimik at masipag na tagasanay.",
     "pabalik, muli", "alon"),
    ("Hindi maiiwasan o matatakasan.",
     "Tiyak na mangyayari anuman ang gawin mo — walang lusot sa kinalabasang hindi maiiwasan.",
     "Darating ang katandaan sa lahat; simpleng hindi ito maiiwasan.",
     "hindi", "makipagbuno palabas"),
    ("Gumagamit ng paikot, mahabang pananalita sa halip na tuwirang anyo.",
     "Dumadaan sa malayong daan ng mga salita — sinasabing \"make a decision\" sa halip na \"decide\".",
     "Ang kanyang paikot na liham ay maaaring nasabi sa isang linya ang kinailangan ng tatlong talata.",
     "sa paligid", "ipahayag, sabihin"),
    ("Pagkapurol o pagkahilo ng isip.",
     "Ang maulap, mabagal na kalagayan ng isip kung saan parang nilalakad mo ang malapot na asukal ang pag-iisip.",
     "Isang alon ng pagkapurol ng isip ang tumama sa klase pagkatapos ng tanghalian.",
     "mapurol, hindi matulis", "kalagayan o katangian"),
    ("Hindi kanais-nais; masamang palatandaan.",
     "Masamang senyales — kundisyon o oras na parang laban sa iyo bago ka pa magsimula.",
     "Ang kulay-abong langit at patay na baterya ay naging di-mapalad na simula ng biyahe.",
     "hindi", "kanais-nais, mapagbiyaya"),
    ("Karne na inihaw o inilaga sa sarsa — tamang baybay ay \"fricasseed\".",
     "Komportableng lumang kataga sa pagluluto para sa karne na hiniwa at dahan-dahang inilaga sa sariling sarsa hanggang lumambot.",
     "Ang nilagang manok sa sarsa ni Lola ang tampok ng bawat hapunan tuwing Linggo.",
     "iprito", "baliin (sa piraso)"),
    ("Pekeng o mas mababang kapalit.",
     "Peke na pumapalit sa totoo — gumagana naman, pero alam ng lahat na hindi tunay.",
     "Ang mga mamimili noong giyera ay nakibagay sa pekeng kape mula sa inihaw na chicory.",
     "palabas, unlaping kapalit", "ilagay, ipwesto"),
    ("Tratuhin ang kaisipang walang laman na parang bagay na nahahawakan.",
     "Gawing totoo at matibay ang kaisipan — gawing bagay na maituturo ang malabo, tulad ng \"the economy\".",
     "Ang pagtawag sa \"espiritu\" ng bansa bilang sariling nilalang ay ginagawang bagay ang totoo'y milyun-milyong indibidwal na pagpili.",
     "bagay", "gawin"),
    ("Nakatakas o naiwasan nang may kasanayan.",
     "Nakatakas nang malinis — umilag sa pagdakip, tanong, o sagot, madalas nang tuso o naiipit.",
     "Umiwas sa kanya ang sagot nang ilang oras hanggang biglang pumitik sa paliguan.",
     "palabas, palayo", "maglaro"),
    ("Nagpapahayag ng pag-aalinlangan, pagkalito, o hindi pa natapos na kontradiksyon.",
     "Nakadikit sa tunay na patay na dulo ng pag-iisip — hindi tamad na pagkalito, kundi dahil mismo ang tanong ay tumatanggi sa malinis na sagot.",
     "Madalas tapusin ni Socrates ang mga diyalogo sa tonong palaisipan, mas maraming tanong kaysa sagot.",
     "wala", "daanan, landas"),
    ("Tayutay na tumatawag sa bagay sa kaugnay na kataga, hal. \"the crown\" para sa hari.",
     "Paggamit ng kaugnay na salita kapalit ng totoo — sinasabing \"the White House announced\" kung ang ibig sabihin ay ang pamahalaan.",
     "Ang \"Wall Street had a rough day\" ay metonimya — ang ibig sabihin talaga ay ang pamilihan ng sapi.",
     "pagbabago, pagkatapos", "pangalan"),
    ("Bunutin sa ugat; punitin mula sa likas na kapaligiran.",
     "Hilahin ang isang bagay (o tao) mula sa ugat, palayo sa lugar o kulturang kinabibilangan.",
     "Binunot sa ugat ng giyera ang buong henerasyon, ikinalat ang mga pamilya sa kabila ng hangganan.",
     "palayo, tanggal", "ugat"),
    ("Kaaya-aya pakinggan.",
     "Masarap lang pakinggan — ang salita, pangalan, o pangungusap na kaaya-ayang pakinggan ay dumudulas sa tenga na parang musika.",
     "Ang \"Murmuring brook\" ay maliit na pariralang kaaya-ayang pakinggan, malambot at madaling bigkasin.",
     "mabuti, maayos", "tunog, tinig"),
    ("Karaniwang ipinapalagay o tinatanggap na.",
     "Malawakang pinaniniwalaang totoo kahit hindi pa napatunayan — ang \"supposed\" na bersyon.",
     "Ang pinaniniwalaang may-akda ng liham ay naging ganap na estranghero pala.",
     "isipin, ituring", "may katangian ng"),
    ("Bagong likhang salita o parirala.",
     "Bagong-bagong salita — kasisilang pa lang, wala pa (o halos wala) sa talahulugan.",
     "Ang \"Doomscrolling\" ay nagsimula bilang neolohismo at mabilis naging pang-araw-araw na salitang-kalye.",
     "bago", "salita, pananalita"),
    ("Galit o masamang-loob.",
     "Nasa masamang kalooban, madaling sumabog — tulad ng dating paniniwala na ang pali ang kumokontrol sa init ng ulo.",
     "Nagpaputok siya ng magalit na sagot ilang segundo pagkabasa ng liham.",
     "pali (upuan ng galit)", "naaapektuhan ng"),
    ("Mahilig magturo ng aral nang may palalo o pilit na paraan.",
     "Mahilig magbigay ng maliliit na aral sa buhay nang may palalo, parang bawat pangungusap ay biskwit ng kapalaran.",
     "Ang kanyang mapagsermong toast tungkol sa \"tunay na kahulugan ng pagkakaibigan\" ay nagtulak sa lahat na tumingin sa orasan.",
     "opinyon, kasabihan", "puno ng"),
    ("Sobrang madaldal, lalo na sa maliliit na bagay.",
     "Hindi tumitigil sa usapan — nagsasalaysay ng maliliit na bagay matagal pagkatapos maubusan ng sasabihin ang iba.",
     "Ang madaldal na tsuper ng taksi ay ikinuwento ang buong buhay niya bago pa kami umalis sa paliparan.",
     "magsalita nang walang tigil", "hilig"),
    ("Kamangmangan, kabobohan.",
     "Payak na kabobohan — puna o planong napakabobo na halos hindi karapat-dapat sagutin nang seryoso.",
     "Ang tahasang kabobohan ng plano ay naging malinaw sa sandaling sinubukan nila.",
     "bobo, hangal", "kalagayan ng pagiging"),
    ("Pangwakas na bahagi ng talumpati, madalas nagbubuod.",
     "Ang malaking tapos ng talumpati — ang pangwakas kung saan tinitipon ng tagapagsalita ang lahat at ipinapako ang punto.",
     "Sa pangwakas na bahagi, kalahati na ng madla ang nakatayo.",
     "sa pamamagitan, hanggang dulo", "magsalita, ipagtanggol"),
    ("Walang-silbing pag-uulit ng parehong kaisipan sa ibang salita.",
     "Sinasabi nang dalawang beses ang pareho nang walang dagdag, tulad ng \"free gift\" o \"end result\".",
     "Ang \"It is what it is\" ay paboritong tautolohiya ng mga umiiwas sa tunay na paliwanag.",
     "pareho", "salita, pananalita"),
    ("Paggamit ng napakakaunting salita; maikling pananalita.",
     "Maraming nasasabi sa kaunti — sining ng maikli, tuwirang sagot, mula sa mga Sparta ng Laconia na kilala sa kaiklian.",
     "Ang \"Molon labe\" — \"halika at kunin ninyo\" — ang pinakatanyag na maikling pananalita sa kasaysayan.",
     "isang Sparta ng Laconia", "gawi, paraan"),
    ("Malabnaw, sobrang pinasimpleng kaisipan; orihinal, malabnaw na pagkain o lugaw.",
     "Manipis, diniluang pag-iisip — nilalamang napakapayak at ligtas na walang nutrisyon para sa isip.",
     "Karamihan sa talumpati ng politiko ay walang-lamang salita: malabong pangako na walang mahawakan.",
     "pakainin", "paraan o kasangkapan"),
    ("Nagpapadala ng tulog o antok.",
     "Napakabagot — o talagang pampakalma — na nakaaantok. Isipin ang mainit na gatas, o tatlong oras na pulong sa badyet.",
     "Ang nakakaantok na ugong ng lektura ay kalahati ng silid ang nakikipaglaban para hindi ipikit ang mata.",
     "malalim na tulog", "paggawa, pagdudulot"),
    ("Sobrang pambobola o madulas ang asal.",
     "Makinis hanggang madulas — pambobolang kapal na parang mararamdaman mo ang taba.",
     "Patuloy na pinupuri ng mapambolang tindero ang aking \"napakagandang panlasa\" bago ang bawat dagdag-benta.",
     "pahiran ng langis", "puno ng"),
    ("Mabilis makakita ng mali, sobrang mapanuri sa maliliit na bagay.",
     "Sobrang mapili — tipo ng taong may problema sa lahat, kahit hindi naman mahalaga.",
     "Ang kanyang mapamintas na tala sa ulat ay nakatuon lamang sa paglalagay ng kuwit.",
     "agawin, kunin", "bitag, maling pangangatwiran"),
    ("Mabagal, hindi gumagalaw sa isip o katawan.",
     "Mabagal at kalahating tulog, parang oso sa pagtulog-taglamig — halos hindi gumagalaw, halos hindi nag-iisip.",
     "Naging tamlay ang tanggapan sa mabigat na init ng Agosto.",
     "manhid, mabagal", "nasa kalagayan ng"),
    ("Katiwala o opisyal na namamahala sa sambahayang medyebal.",
     "Bersiyon medyebal ng pinuno ng tauhan — pinagkakatiwalaang opisyal na nagpapatakbo araw-araw sa tahanan at lupain ng panginoon.",
     "Pinamahalaan ng katiwala ng kastilyo ang lahat mula sa aklat ng ani hanggang sa listahan ng bisita.",
     "matanda, nakatatanda", "alipin"),
    ("Magsalita o magsulat nang mahaba tungkol sa isang paksa.",
     "Talagang magpatuloy sa paksa — magsalita o magsulat nang walang tigil, saklawin ang bawat anggulo.",
     "Tanungin mo siya tungkol sa lumang kotse at magpapahaba siya nang isang oras.",
     "palabas", "espasyo"),
    ("Walang halaga, walang kabuluhan; hindi rin wasto o epektibo.",
     "Halos walang halaga — ang sugnay na walang bisa sa kasunduan ay hindi talaga gumagawa ng anuman.",
     "Idineklara ng hukuman na walang bisa ang lumang utos, dahil hindi naman ito naipatupad kailanman.",
     "kalokohan, walang saysay", "nabibilang sa"),
    ("Karunungan, matalas na paghatol.",
     "Matalas, praktikal na karunungan — mabuting paghatol mula sa karanasan, hindi lang sa aklat.",
     "Ang katalinuhan ng matandang kapitan ay higit sa minsan na nagtanggol sa tripulante sa gulo.",
     "matalas ang pang-amoy, tuso", "katangian ng"),
    ("Karaniwang gulo-gulo o masa, ginagamit nang may hamak.",
     "Mapagmataas, mapanghamak na salita para sa \"gulo-gulo\" o karaniwang tao.",
     "Ngilusan ng konde ang gusgusing madla na nagtitipon sa labas ng tarangkahan ng palasyo.",
     "aso", "kolektibo, kawan"),
    ("Walang-galang, nakakahiyang trato o wika.",
     "Malupit, mapanghamak na trato na layuning hiyain — insultong dinisenyo para sumakit.",
     "Tiniis niya ang mga taon ng pag-alipusta mula sa mga tagapuna bago kilalanin ang kanyang gawa.",
     "kasama, lubusan", "magpalaki (sa pagmamataas)"),
    ("May hinala o hindi pagsang-ayon; sulyap sa gilid.",
     "Ang sulyap sa gilid na ibinibigay mo sa hindi mo lubos pinagkakatiwalaan — tinging puno ng duda.",
     "Tumingin ang guro nang may hinala sa kahina-hinalang malinis na takdang-aralin.",
     "sa, tungo", "tabi, pagkiling"),
    ("Hangal na tao; ulo ng kahoy.",
     "Lumang, halos may lambing na insulto para sa taong medyo makapal ang ulo — ulo ng kahoy.",
     "\"Ulo ng kahoy ka,\" tumawa siya, \"baligtad ang mapa mo buong oras.\"",
     "bukol ng lupa", "ulo"),
    ("Igalaw o isagawa; magbigay ng motibo.",
     "Maging ang kidlat na nagpapagalaw — maging makina o tao na sa wakas ay kumikilos sa kaisipan.",
     "Ang takot mawala ang kasunduan ang nagtulak sa buong koponan sa dagdag-oras sa Sabado't Linggo.",
     "paggawa, pagtutulak", "itulak, gawin"),
    ("Pagnanakaw ng salaping ipinagkatiwala.",
     "Tahimik na ninanakaw ang pera na pinagkatiwalaan sa iyo — pagnanakaw sa lumang damit.",
     "Ang pangungurakot ng ingat-yaman ay hindi napansin nang halos isang dekada.",
     "pribadong ari-arian", "baka, yaman"),
    ("Grupong itinuturing nasa gilid ng kagalang-galang na lipunan.",
     "Ang makinang-pero-kaduda-dudang ilalim ng lipunan — mga taong nabubuhay sa labas mismo ng mga patakaran ng \"kagalang-galang\" na lipunan.",
     "Sinusundan ng nobela ang isang mang-aawit sa gilid-lipunan ng mga cabaret noong 1920s.",
     "kalahati", "daigdig, lipunan"),
    ("Umiiral pa; hindi nalipol o nasira.",
     "Nandito pa ngayon — ginagamit sa lumang bagay (manuskrito, uri, gusali) na nakaligtas.",
     "Tatlo lang ang kilalang natitirang kopya ng unang palimbag.",
     "palabas", "tumayo"),
    ("Panlilinlang; pagtataksil sa tiwala.",
     "Malalim, sinadyang pagtataksil — paglabag sa tiwalang may karapatan ang isang tao asahan mong pananatilihin.",
     "Hindi kailanman pinatawad ng heneral ang pagtataksil ng matandang kaibigan sa mesa ng negosasyon.",
     "sa pamamagitan, laban", "pananampalataya, tiwala"),
    ("Wikang panrehiyon, lalo na ang hindi pamantayan.",
     "Ang natatanging, lokal na paraan ng pagsasalita sa isang lugar — puno ng mga salita at ritmo na maaaring hindi mahuli ng tagalabas.",
     "Nagsasalita pa rin ang kanyang lola ng salitang-bayan ng isla sa hapunan ng pamilya.",
     "magaspang na pananalita, dayalekto", "paa — usapang magaspang"),
    ("Natatanging karapatang pag-aari ng isang tao o grupo.",
     "Pribilehiyong sa iyo lang — karapatang kasama ng tungkulin, posisyon, o katayuan.",
     "Ang pagpili ng bakasyon ng pamilya ay natatanging karapatan ni Lolo, at alam ito ng lahat.",
     "bago", "magtanong, bumoto"),
    ("Katapangan, kapal ng mukha; gayundin katigasan o tibay.",
     "Magaspang, matapang na tibay — lakas ng loob na tumuloy at tibay na magpatuloy kapag nagsimula ka na.",
     "Kailangan ng tunay na tapang para tumawid sa daanan sa bagyo ng niyebe na walang mapa.",
     "matapang, matibay", "kalagayan, kondisyon"),
    ("Mamulaklak nang buo; gayundin umunlad o unti-unting lumitaw.",
     "Mamulaklak sa buong pagpapahayag — parang bulaklak na bumubukas, o kaisipang sa wakas ay naging ganap.",
     "Ang tahimik niyang talento sa pagpinta ay namulaklak nang magkaroon siya ng sariling studio.",
     "palabas", "magsimulang mamulaklak"),
    ("Sinulid na may timbang para malaman ang patayo; sa talinghaga, pamantayan ng paghatol.",
     "Timbang sa sinulid na nakabitin nang tuwid pababa, ginagamit para suriin kung tunay na patayo — at, sa lawak, anumang nakapirming pamantayan na sinusukat mo ang lahat.",
     "Ginamit niya ang katapatan ng sariling lolo bilang uri ng pisi't tingga para sa bawat desisyon.",
     "tingga", "lubid, sukat"),
    ("Masaya, kusang-loob (luma).",
     "Lumang paraan ng pagsabi ng \"masaya\" o \"nang may kasiyahan\".",
     "\"Ibig ko sanang magpahinga rito sandali,\" buntong-hininga ng manlalakbay.",
     "masaya, maligaya", "masaya, kusang-loob"),
    ("Malupit na pampublikong puna o kahihiyan.",
     "Pampublikong kahihiyang ibinunton sa isang tao nang malaki at nakikita — kahihiyan mula sa malawakang hindi pagsang-ayon.",
     "Dinala ng iskandalo ang pampublikong kahihiyan sa buong kumpanya.",
     "laban", "kahihiyan, saway"),
    ("Matulis na mapanuya, kumakagat sa talas o puna.",
     "Talas na may ngipin — ang mapangagat na puna ay medyo masakit dahil sa tumpak na pagpuntirya.",
     "Ang kanyang mapangagat na rebyu ng pelikula ay kinatatakutan ng mga direktor at minamahal ng mga mambabasa.",
     "kagatin", "kumakagat, gumagawa"),
    ("Pormal na proklamasyon, madalas pampulitika o militar.",
     "Malaking opisyal na anunsyo — karaniwang nagdedeklara ng bagong gobyerno, pag-aalsa, o malaking atas.",
     "Inihayag ng proklamasyon ng heneral ang bagong gobyerno sa madaling-araw.",
     "pasulong", "ianunsyo"),
    ("Taong mababaw ang kaalaman ngunit nagpapanggap na dalubhasa.",
     "Taong nagsimot lang sa ibabaw ng paksa tapos nagsasalita na parang siya ang sumulat ng aklat-aralin.",
     "Ang mapagpanggap na marunong sa hapunan ay may tiwalang itinama ang tunay na dalubhasa sa bituin sa mesa.",
     "malaman", "maliit — maliit na nakakaalam"),
    ("Pagbaba ng kakayahan ng isip sa katandaan.",
     "Ang maulap, malilimutin na panahon ng napakatanda kapag nagsisimulang lumabo ang talas ng isip.",
     "Sa kanyang pagkaulyanin, ikinuwento niya ang parehong tatlong kuwento sa bawat pagdalaw, sa bawat pagkakataon na parang bago.",
     "mangmang, maging hangal", "kalagayan o resulta"),
    ("Panig na kanlungan mula sa hangin.",
     "Ang tahimik, kanlungang panig — burol, barko, pader — kung saan hindi ka abot ng hangin.",
     "Nagkampo ang mga maglalakad ng tolda sa panig na kanlungan sa hangin ng tagaytay para makatakas sa hanging malakas.",
     "kanlungan, proteksyon", "tagiliran, mukha"),
    ("Iwasan o itaboy ang suntok, tanong, o argumento.",
     "Dahan-dahang itaboy — suntok ng espada, tanong na mahirap sagutin, o paratang — nang hindi nawawala ang ritmo.",
     "Iniwas niya ang mahirap na tanong ng tagapagbalita sa madaling biro.",
     "itaboy", "maghanda, ipagtanggol"),
    ("Mabahong amoy, nakalalason.",
     "Bumaho nang parang lason — amoy na napakasama at mukhang delikado langlangin.",
     "Isang mabahong amoy ang tumaas mula sa latian nang lumubog ang araw.",
     "nakalalasong singaw", "may katangian ng"),
    ("Taong tapat sa luho at kasiyahan.",
     "Taong nabubuhay para sa ginhawa at pagpapasasa — masarap na pagkain, malambot na kama, madaling buhay — mula sa sinaunang lungsod ng Sybaris na tanyag sa sobra.",
     "Tunay na maluho, tinanggihan niya ang silid ng hotel na walang banyera.",
     "sinaunang lungsod ng Gresya na tanyag sa luho", "naninirahan ng"),
    ("Sadyang isantabi o balewalain ang isang bahagi.",
     "Sadyang ilagay sa isip ang isang piraso ng palaisipan sa tabi, para malinis na magtuon sa natitira.",
     "Isantabi muna natin ang gastos at tanungin lang kung gumagana ba talaga ang plano.",
     "bago, palayo", "gupitin"),
    ("Kritisahin nang malupit; gayundin balatan.",
     "Punitin ang isang tao sa malupit na puna — sa salita, parang talagang binabalatan.",
     "Binatikos ng mga tagapuna ang sequel dahil nagtaksil sa lahat ng minahal ng mga tagahanga sa orihinal.",
     "tanggal", "balat"),
    ("Sipiin bilang ebidensya o patunay.",
     "Ilabas ang katotohanan o halimbawa para suportahan ang punto — ang tinuturo mo kapag nagtanong ang isang tao ng \"what's your evidence?\".",
     "Naglahad ang abugado ng tatlong saksi para suportahan ang alibi ng kanyang kliyente.",
     "tungo, papunta", "akayin"),
    ("Mga paglalakbay o pagala-gala, lalo na ang mahaba at malawak.",
     "Mahahabang, gumagala na paglalakbay — malawak na pagala-galang naglalayo sa iyo sa tahanan nang mahabang panahon.",
     "Ang kanyang mga paglalakbay sa tatlong kontinente ay pumuno ng buong istante ng mga talaarawan sa paglalakbay.",
     "sa pamamagitan", "bukid, lupa (peregrinus: dayuhan)"),
    ("Pulubi, o namumuhay sa limos.",
     "Taong namumuhay sa paghingi ng awa — sa kasaysayan, tumutukoy din sa mga monghe na nanumpa ng kahirapan at nabuhay sa donasyon.",
     "Ang mga prayleng palimos ay walang pag-aari at umaasa nang lubos sa kabutihan ng mga taganayon.",
     "magpalimos", "pulubi"),
    ("Lubhang mapagbigay.",
     "Mapagbigay sa malaking, halos palabas na sukat — uri ng regalong nakakapagpatigil ng hininga.",
     "Pinondohan ng mapagbigay na donasyon ang buong bagong pakpak ng aklatan.",
     "regalo, paglilingkod", "paggawa, pagbibigay"),
    ("Pagkapagod mula sa kakulangan ng pagkain; gayundin kakulangan ng sigla.",
     "Mahina, nauubos na kalagayan mula sa hindi napakain o napagasolina — literal mula sa gutom, o sa talinghaga mula sa walang natitira para tumakbo.",
     "Sa katapusan ng pagkubkob, malapit na sa pagkahapo ang mga sundalo.",
     "walang laman, hungkag", "gawa o resulta"),
    ("Mapait, mapang-abusong puna.",
     "Kritikang lampas na sa patas at naging galit, mapait na tirada.",
     "Natunaw ang mga komento online sa purong panlalait sa loob ng ilang minuto.",
     "sala", "ihanda, bigyan"),
    ("Galit, nakapipinsala sa epekto.",
     "Gumagana laban sa iyo, kahit tahimik — kundisyon o ugaling hindi magiliw sa iyong interes.",
     "Ang bagong patakaran ay nakapipinsala sa maliliit na negosyo, kahit hindi iyon ang layunin.",
     "hindi", "kaibigan"),
    ("Malamang magdulot ng sama ng loob o hindi kasiyahan, madalas sa hindi patas na paghahambing.",
     "Tiyak na magpaparamdam ng paghamak — karaniwan dahil nagsasalansan ng tao o bagay nang hindi patas.",
     "Ang pagraranggo ng magkakapatid ayon sa \"sino ang pinakamamahal ni Nanay\" ay larong tiyak na magdulot ng sama ng loob at hindi dapat laruin ninuman.",
     "inggit", "tingnan (nang may masamang loob)"),
    ("Taong mas mababang ranggo o katayuan; nasasakupan.",
     "Taong mas mababa sa tanikala ng utos o hagdanang panlipunan — junior, nagtatrabaho sa ilalim ng mas makapangyarihan.",
     "Bilang batang mababang opisyal, tumanggap siya ng utos matagal bago siya nagbigay nito.",
     "sa ilalim", "kahalili, iba"),
    ("Damhin o ipahayag ang matinding pagkamuhi.",
     "Suklam hanggang isumpa nang malakas — purong, may tinig na pagkamuhi.",
     "Isinumpa ng mga taganayon ang maniningil ng buwis tuwing dumaraan ang kanyang kariton sa bayan.",
     "mula sa", "sagrado (sumpain palabas sa sagrado)"),
    ("Likas na panlabas na pabalat, tulad ng balat o talukab.",
     "Sariling proteksiyon ng kalikasan — balat, talukab, balat ng binhi, o balat ng prutas, anumang tumatakip at nagtatanggol sa buhay.",
     "Ang talukab ng pagong ay napakatibay na panlabas na balat.",
     "sa ibabaw, sa ibabaw", "takpan"),
    ("Inosente, walang malay, nagpapakita ng pagiging-bata; kabaligtaran ng \"disingenuous\".",
     "Hayagang nagtitiwala at medyo musmos, walang nakatagong balak — madaling ipagkamali sa \"ingenious\" na ang ibig sabihin ay matalino.",
     "Ang kanyang walang-malay na tanong — \"bakit magsisinungaling ang isang tao tungkol diyan?\" — ay nagpakita kung gaano siya kaunti ang daya.",
     "sa loob, katutubo", "magkaanak (malayang isinilang, tapat)"),
    ("Sobrang pagmamalasakit sa maliliit na detalye o alituntunin.",
     "Naliligaw sa maliliit na alituntunin habang napapalampas ang mas malaking larawan — nasisiraan sa pinong letra na wala namang inaalala ang iba.",
     "Ang kanyang labis na pagmamaselan sa Oxford comma ang nagtanggal sa buong pulong sa riles.",
     "guro ng mga bata", "gawi o katangian"),
    ("Masusing, maingat na pagsusuri.",
     "Malalim, walang-batong-naiwan na pagtingin — sinusuri ang bawat detalye nang may tunay na ingat.",
     "Pagkatapos lang ng masusing pagsusuri ng mga aklat-tungkos lumitaw ang pagkakaiba.",
     "sa pamamagitan, lubusan", "hanapin, suriin"),
    ("Magtaas ng tutol; magpakita ng pag-aatubili.",
     "Magalang na itulak pabalik o mag-atubili sa halip na sumunod agad — malambot na \"I'd rather not\".",
     "Nang hilinging pumirma nang hindi binabasa, siya ay nag-atubili.",
     "mula, palayo", "antalahin"),
    ("Sa ibabaw ay mukhang makatwiran pero mali pala.",
     "Mukhang nakakumbinsi sa unang tingin pero gumuho sa sandaling suriin mo talaga.",
     "Ang \"Everyone's doing it\" ay argumentong mukhang matino ngunit hindi kailanman tumatagal sa pagsisiyasat.",
     "hitsura, anyo", "puno ng (mukhang maganda)"),
    ("Hindi tapat, mapagkunwaring usapan, madalas nagtuturo ng moral.",
     "Makinis na usapang mukhang mabuti pero walang tunay na damdamin — pose ng moral na tumatakbo mag-isa.",
     "Napagod siya sa pakitang-taong usapan tungkol sa \"pamilya\" mula sa kumpanyang hindi kailanman nagbibigay ng bakasyon kaninuman.",
     "umawit (kinalaunan: singsong na jargon)", "daing ng pulubi, pagkatapos pagkukunwari"),
    ("Walang tapang, duwag.",
     "Mahiyain hanggang walang gulugod — masyadong natatakot tumayo kahit malinaw na mahalaga.",
     "Ang duwag na katahimikan ng lupon ang nagpalawak ng iskandalo palabas sa kontrol.",
     "napakaliit", "espiritu, tapang"),
    ("Parang soro; tuso, mapanlinlang.",
     "Tuso at matalino tulad ng soro — mabilis mag-isip, medyo lihim, palaging isang hakbang sa unahan.",
     "Nagbigay siya ng ngiting parang soro sa sandaling makita ang butas.",
     "soro", "ng o tulad ng"),
    ("Isa-isa, sunud-sunod.",
     "Tinatanggap nang mahigpit nang isa-isa, ayon sa ayos — walang laktaw, walang dalawa nang sabay.",
     "Tinugunan ng hukom ang bawat isa sa labindalawang usapin nang isa-isa.",
     "hanay, pagkakasunod", "isa-isa"),
    ("Sobrang pagtitipid; pagiging kuripot.",
     "Mahigpit sa pera (o salita, o yaman) lampas sa makatwirang tipid.",
     "Ang kanyang kakuriputan ay alamat — ginamit niyang muli ang supot ng tsaa nang tatlong beses.",
     "magtipid, maging matipid", "kalagayan o gawi"),
    ("Pagwawasto, lalo na sa teksto.",
     "Ayos sa isang sulatin — akademikong pag-aayos na itinatama ang mali sa lumang o mahalagang teksto.",
     "Kasama sa bagong edisyon ang dose-dosenang pagwawasto sa orihinal na manuskrito.",
     "mula sa", "sala, mali"),
    ("Katamtaman sa pagkain at inumin.",
     "Sadyang nagtitimpi sa paligid ng pagkain at inumin — hindi kailanman sobra, palaging may natitira sa plato.",
     "Ang kanyang mapagtimping gawi ang nagpanatili sa kanya nang matalas matagal pagkatapos bumagal ang kanyang mga kapantay.",
     "palayo sa", "nakalalasing na inumin"),
    ("Mali sa gramatika o paglabag sa etiketa.",
     "Maliit na pagkakamali sa gramatika o asal — uri ng maliit na pagkakamaling ikinakabig ng mapili.",
     "Ang \"Between you and I\" ay karaniwang maling gramatika na ikinakabig pa rin ng mga gramarista.",
     "lungsod sa Cilicia na kilala sa 'masamang' Griyego", "gawi, paraan"),
    ("May kinalaman sa hidwaan sa loob ng grupo; magkasamang mapanira.",
     "Awayan sa loob na pumipiraso sa grupo mula sa loob — laban kung saan natalo ang lahat, dahil pamilya laban sa pamilya.",
     "Ang pag-aaway sa loob mismo ng partido ay mas nakasira kaysa anumang kalaban sa labas.",
     "sa pagitan, sa gitna", "pumatay"),
    ("Walang-pakialam, pabaya na ugali.",
     "Isang balikat na naging buong personalidad — napakakaunting malasakit sa dating mahalaga hanggang walang tila sulit pagsikapan.",
     "Ang kanyang walang-pakialam na ugali sa seremonya ng parangal ay ikinagulat ng lahat na alam kung gaano siya nagsikap.",
     "kaunti", "malasakit"),
    ("Magulo, kumplikadong sitwasyon o hidwaan.",
     "Nakatali, magulong sitwasyong mahirap unawain — bahaging hindi pagkakaintindihan, bahaging drama, lahat kalituhan.",
     "Ang buong gusot ng upuan ay nagsimula sa isang maling lagay na kard ng pangalan.",
     "sa loob", "itulak, gulo"),
    ("Nanganganib, banta.",
     "May malinaw na hangin ng banta — ang nagbabantang tingin o liham ay malinaw na may masamang maaaring sumunod.",
     "Ang nagbabantang tono ng liham ay kinabahan ang nangungupahan bago pa niya buksan ang sobre.",
     "banta", "nagsisilbing"),
    ("Malakas na pampublikong puna o pag-alipusta.",
     "Malakas, pampublikong paghatol — uri ng nakapapasong punang nagaganap sa harap ng lahat.",
     "Hinarap ng magsisiwalat ang mga taon ng pampublikong paninirang-puri bago napatunayan ng kasaysayan na tama siya.",
     "laban", "magsalita"),
    ("Biglang marahas na pagsabog, ng damdamin o kilos.",
     "Bigla, matinding pagsabog na lumalamon sa iyo nang sabay — tawa, galit, o ubong dumadating parang alon.",
     "Hinawakan siya ng silakbo ng tawa na hindi niya maipaliwanag sa iba pang nasa silid.",
     "lampas", "matulis, matindi"),
    ("Idinagdag mula sa panlabas na pinagmulan, hindi likas.",
     "Ikinabit mula sa labas sa halip na itinayo mula sa simula — dagdag, hindi ubod.",
     "Parang idinugtong mula sa labas ang komentaryo, na parang idinikit sa natapos nang teksto.",
     "tungo, dagdag", "sang-ayunan, tanggapin"),
    ("Kakulangan ng kaalaman, kamangmangan.",
     "Payak na hindi-alam — puwang sa kaalaman, walang hatol na nakakabit.",
     "Inamin niya ang kanyang kamangmangan sa alak na Pranses at hinayaang pumili ang sommelier.",
     "hindi", "malaman"),
    ("Sobrang interes sa mga usaping sekswal.",
     "Sobrang sabik, tumitingin nang may pagnanasa sa anumang malaswa — interes na lampas sa malusog tungo sa pakikialam.",
     "Ang malaswang interes ng tabloid sa pribadong buhay ng mag-asawa ay halos naging pagkahumaling.",
     "mangati, maghangad", "kalagayan"),
    ("Mauling, madilim, malabo.",
     "Madilim at mausok ang hitsura, parang manipis na uling ang nakapatong sa lahat.",
     "Isang maulingang ulap ang nakasabit sa bayan ng pabrika sa takipsilim.",
     "uling", "puno ng"),
    ("Tanggihan o salungatin.",
     "Tuwirang magsalita laban sa sinabi ng iba — sabihin ang \"that's not so\".",
     "Walang nangahas na salungatin ang kuwento ng matandang kapitan tungkol sa bagyo.",
     "laban", "magsalita"),
    ("Katamaran, katamaran (mula sa Latin).",
     "Lumang salitang Latin para sa purong katamaran — ang hila ng ayaw gumawa ng anuman.",
     "Nangaral ang mga monghe laban sa katamaran bilang isa sa tahimik na panganib ng kaluluwa.",
     "hindi", "abala, masipag"),
    ("Kalasag na nagpapakita ng eskudo.",
     "Emblemang hugis-kalasag na nagpapakita ng eskudo ng pamilya — ang \"plaka ng pangalan\" ng sagisag.",
     "Nakabitin pa rin ang kalasag-eskudo ng pamilya sa itaas ng pintuan ng lumang manor.",
     "kalasag", "maliit / bagay"),
    ("Luma na, lipas, o retirado dahil sa edad.",
     "Lampas na sa kapaki-pakinabang na rurok at inilabas sa pastulan — masyadong luma o gastado para magpatuloy sa trabaho.",
     "Ang lipas nang printer ay pinalitan sa wakas pagkatapos ng labinlimang taon ng pagkakabara.",
     "lampas", "taon"),
    ("Mga kapalit, lalo na sa medisina.",
     "Pampalit na lunas kapag wala ang tunay na gamot — sa esensya, panghalili sa paggagamot.",
     "Madalas umasa ang mga doktor noong giyera sa mga kapalit na gamot kapag naubos ang wastong gamot.",
     "sa halip ng", "pumunta, magbigay-daan"),
    ("Mayabang, palalong usapan.",
     "Malaking, palalong pagmamayabang — malakas na usapan tungkol sa sariling kadakilaan na karamihan ay mainit na hangin.",
     "Ang kanyang kayabangan tungkol sa \"nag-iisa\" na pagsagip sa proyekto ay walang nalinlang na talagang nandoon.",
     "mayabang na kabalyero sa Orlando Furioso", "kilos, palabas"),
    ("Gumamit ng daya o panlilinlang para makamit ang isang bagay.",
     "Gumapang patungo sa layunin sa pamamagitan ng tuso sa halip na patas na laro.",
     "Nakapasok siya sa deal sa pamamagitan ng daya, sa kontratang puno ng pinong letra.",
     "maghamak, dayain", "daya; kalaunan matinding liko"),
    ("Dalisay o abstraktong agham ng pag-aaral o kaalaman, madalas matematika.",
     "Pag-aaral sa pinakadalisay, pinakaabstraktong anyo — ang malalim na kayarian ng kaalaman mismo, lalo na ang matematikal.",
     "Nangarap ang pilosopo ng isang pangkalahatang agham ng kaalaman na makapagkakaisa sa bawat larangan.",
     "matuto", "gawa ng pagkatuto"),
    ("Sobrang nagmamalasakit sa pormal na alituntunin o walang-kabuluhang detalye.",
     "Sobrang mahigpit sa maliliit na bagay — itinatama ang maliliit na teknikalidad na hindi naman nagbabago ng anuman.",
     "Medyo pedante ang makipagtalo tungkol sa \"who\" kontra \"whom\" sa text message.",
     "gabay ng bata, guro", "may paraan ng"),
    ("Kumikislap, kumikinang na liwanag.",
     "Mabilis, kumikinang na kidlat ng liwanag — isipin ang sikat ng araw na tumatalbog sa tubig, o diamanteng nakakakuha ng liwanag.",
     "Ang kislap ng ilawang kristal ay nagkalat ng liwanag sa bawat sulok ng bulwagan ng sayaw.",
     "kumislap, kumidlat", "ang gawa"),
    ("Baguhan, nobato.",
     "Taong ganap na bago sa kasanayan o larangan — natututo pa ng lubid, hindi pa dalubhasa.",
     "Kahit baguhang manlalaro ng ahedres ay makikita ang maling hakbang na iyon.",
     "rekrut, baguhan", "hilaw na batang sundalo"),
    ("Lubhang masama, kasuklam-suklam.",
     "Masama sa paraang karapat-dapat sa tunay na suklam — hindi lang \"katamtaman,\" kundi tunay na kasuklam-suklam.",
     "Tinawag ng tagarebyu ang sequel na kasuklam-suklam, at sumang-ayon ang mga numero sa takilya.",
     "sumpain", "karapat-dapat, kayang maging"),
    ("Kulay pulang-dugo.",
     "Malalim, matingkad na pula — kulay ng sariwang dugo, tanyag mula sa Macbeth ni Shakespeare.",
     "Ginawang ningning na pulang-dugo ng paglubog ng araw ang buong langit.",
     "papasok", "laman (pulang-laman)"),
    ("Maliit na puwang o agwat sa pagitan ng mga bagay.",
     "Ang maliit na puwang sa pagitan na madaling palampasin — bitak sa sahig, puwang sa iskedyul.",
     "Tumubo ang mga damo sa bawat puwang ng lumang landas na ladrilyo.",
     "sa pagitan", "tumayo"),
    ("Mga mapanuri o mapanghusgang puna.",
     "Matulis, hindi sang-ayong komento — uri ng kritikang may kaunting tono ng pagsaway.",
     "Pinuno ng mga masakit na puna ng propesor sa sanaysay ang mga gilid ng pulang tinta.",
     "isip", "humarap tungo"),
    ("Imposibleng pabulaanan, hindi maitatanggi.",
     "Napatunayang napakatibay na walang argumentong maihaharap — sarado na ang kaso.",
     "Ang ebidensyang DNA ay hindi maitatanggi, at natapos ang paglilitis sa loob ng oras.",
     "hindi", "salungatin, labanan"),
    ("Pagkakumplikado, pagkakasalimuot; gayundin pagkulot paloob.",
     "Uri ng komplikasyong nakatiklop sa sarili — mga bagay na binalot nang mahigpit na mahirap paghiwalayin.",
     "Ang pagkakasalimuot ng plot ay iniwan ang kalahati ng madla na sinusubukang tanggalin ito pagkatapos ng mga pangalan sa dulo.",
     "sa loob, paloob", "magulong, mag-ikot"),
    ("Lakas o pagsisikap, tulad ng \"by dint of\".",
     "Tahasang pagsisikap o lakas — ngayon ay nabubuhay na lang sa pariralang \"by dint of\".",
     "Nakapasa siya sa pagsusulit sa lakas ng tahasan, matigas na pagsasanay.",
     "suntok, hampas", "sa lakas ng"),
    ("Pinagsama gamit ang uka at dila; mahigpit na nakaangkop.",
     "Naka-lock sa lumang paraan ng karpintero — isang piraso ang pumapasok nang mahigpit sa butas na ginupit para dito.",
     "Ang mga biga ng lumang kamalig ay pinagdugtong sa uka at dila nang walang isang pako.",
     "saksakan, butas", "kagat, hawak"),
    ("Lubhang nauugnay, angkop.",
     "Eksaktong tamang tugma para sa sandali — komento, sipi, o halimbawang tumatama nang perpekto sa punto.",
     "Ang kanyang angkop na puna ay binalot ang buong debate sa isang pangungusap.",
     "tungo", "ilagay"),
    ("Malumanay na nagniningning o kumikislap (liwanag); gayundin magaan na talas.",
     "Nagniningning nang malumanay sa halip na magningas — malambot, kumikislap na liwanag, o talas na mapaglaro sa halip na matulis.",
     "Naghagis ang liwanag ng kandila ng malumanay na ningning sa lumang silid-kainan.",
     "dilaan", "gumagawa (liwanag na 'dumidila')"),
    ("Relihiyosong ermitanyong nabubuhay sa pag-iisa.",
     "Taong umuurong nang ganap mula sa daigdig para mamuhay mag-isa sa dasal at pagninilay.",
     "Nakatira ang ermitanyo sa maliit na selda na nakakabit sa simbahan nang mahigit tatlumpung taon.",
     "pabalik, palayo", "umuwi"),
    ("Bigyang-kasiyahan ang uhaw; patayin.",
     "Lubos na bigyang-kasiyahan ang pagnanasa — kadalasan uhaw, pero sa talinghaga anumang malalim na gusto o pangangailangan.",
     "Isang malamig na basong tubig ang pumawi sa kanyang uhaw pagkatapos ng mahabang lakad.",
     "maluwag, maluwag", "paluwagin, paliitin"),
    ("Hugis-karayom.",
     "Mahaba, manipis, at matulis parang karayom — hugis ng dahon ng pino o matulis na maliit na kristal.",
     "Madaling kilalanin ang mga puno ng pino sa kanilang mga dahong hugis-karayom.",
     "karayom", "maliit"),
    ("Naubos ang sigla, mahina, sobrang pinong.",
     "Luma at malambot — nawala ang orihinal na lakas o sigla dahil sa sobrang ginhawa o pagiging-pinong.",
     "Tinawag ng mga tagapuna ang dating matapang na magasin na naubos na ang sigla, anino ng magagiting na unang taon nito.",
     "palabas", "mabungang, nanganak na"),
    ("Karagdagan o maliit na nakakabit na bagay o karapatan.",
     "Maliit na dagdag na kasama ng mas malaki — mga accessory at dagdag na nabibilang sa pangunahing bagay.",
     "Kasama sa upa ang garahe at lahat ng kalakip nito.",
     "tungo", "mag-ari"),
    ("Takpan o paliitin ang sala.",
     "Pahid ang mali sa malalambot na salita, para mas magmukhang maliit kaysa sa totoo.",
     "Sinubukan niyang pagtakpan ang napalampas na takdang panahon sa malabong usapan tungkol sa \"hindi inaasahang hamon\".",
     "glosa, paliwanag", "magkomento — pagkatapos ay pahirin"),
    ("Nasa maagang yugto, kakasimula pa lang.",
     "Kakasimula pa lang magpakita — ang pinakaunang, halos hindi nakikitang yugto ng mas malaking darating.",
     "Nahuli ng mga doktor ang maagang palatandaan ng sakit bago ito kumalat.",
     "sa ibabaw, papasok", "kunin (pulutin, simulan)"),
    ("Malikhaing inspirasyon, lalo na ang banal.",
     "Biglang bugso ng inspirasyong mas malaki kaysa sa iyo — parang hiningahan ka ng ideya mula sa ibang lugar.",
     "Inilarawan ng makata ang buong piyesa na dumating sa isang bugso ng inspirasyon nang ikatlo ng umaga.",
     "tungo, sa ibabaw", "hipan (paghipa sa ibabaw)"),
]
