# Afrikaans rows
ROWS = [
    ("Om te versoet of te suiwer; om stroefheid uit iets te haal.",
     "Om die steek of bitterheid uit iets te haal — letterlik deur dit soeter te maak, of figuurlik deur 'n harde idee sagter te maak sodat dit makliker afgaan.",
     "Die redakteur het die harde resensie edulcorated voordat dit gedruk is.",
     "uit, deeglik", "soet"),
    ("Oordrewe of gemaak-godsdienstig of vroom.",
     "Beskryf iemand wie se godsdienstige toewyding voorgegee voel vir die vertoon — meer opvoering as egte geloof.",
     "Sy pietistic sug tydens die preek het die res van die bank gepla.",
     "vroomheid, pligsgetrouheid", "wat die karakter het van"),
    ("Dubbelsinnigheid wat uit die grammatikale struktuur kom — 'n sin wat op twee maniere gelees kan word.",
     "A sin wat grammatikaal reg is maar op twee heeltemal verskillende maniere gelees kan word, soos \"I saw the man with the telescope.\"",
     "\"Visiting relatives can be tiring\" is 'n klassieke amphiboly — is die familie moegmakend, of is dit om hulle te besoek?",
     "albei, aan albei kante", "om te gooi"),
    ("Skerp, trefseker, sny reguit tot by die punt.",
     "Sny dwarsdeur die opvulling — 'n trenchant opmerking of verstand kom vinnig by die hart van die saak, sonder vermorste woorde.",
     "Haar trenchant kritiek het geen plek gelaat vir die rolprent se plotgate om weg te kruip nie.",
     "om te sny", "doen, wat die gehalte het van"),
    ("Net aan die begin; in 'n vroeë of rudimentêre stadium.",
     "Nog in sy openingsoomblikke — 'n plan, gevoel of proses wat skaars begin vorm aanneem het.",
     "Die inchoative stadiums van die verdrag was belowend, maar baie besonderhede was nog onbeslis.",
     "om te begin, om te start", "wat neig na"),
    ("'n Formele toespraak of stuk skryfwerk wat iemand hoog prys.",
     "'n Volledige, formele huldeblyk — dink aan 'n gloeiende lykrede of 'n toespraak wat iemand se prestasies van die dakke af sing.",
     "Die aftredende professor is weggestuur met 'n panegyric van haar naaste studente.",
     "almal", "vergadering, byeenkoms"),
    ("Wat betrekking het op werklike bestaan of feitelike wees, teenoor abstrakte teorie.",
     "Oor dinge soos hulle werklik in die werklikheid bestaan, nie net as idees of teorieë daaroor nie.",
     "Filosowe debatteer of getalle enige ontic status het, of net in ons denke bestaan.",
     "wees, dit wat bestaan", "wat betrekking het op"),
    ("Om vrugte te dra, of produktief te word.",
     "Om eindelik vrug af te werp — 'n poging, idee of belegging wat fructify, het van saad tot iets nuttigs gegroei.",
     "Jare se stil navorsing het eindelik fructified tot 'n werkende entstof.",
     "vrug", "om te maak, om te veroorsaak"),
    ("Wat iets vooruitloop of as klaar voorstel voordat dit werklik gebeur het.",
     "Om letterkundig die geweer voor die skoot af te vuur — 'n toekomstige gebeurtenis beskryf asof dit al klaar is, sodat die punt harder tref.",
     "Die generaal se proleptical heildronk op \"victory\" is 'n volle week voor die geveg uitgereik.",
     "voor", "om te vat, om te gryp"),
    ("Aangedryf deur lugdruk; ook verwant aan gees of asem.",
     "Beteken gewoonlik \"aangedryf deur saamgeperste lug\" — hoewel dit ook op gees of asem kan slaan.",
     "Die pneumatic remme het gegesis toe die bus by die sypaadjie stilhou.",
     "wind, asem, gees", "wat betrekking het op"),
    ("Om God of die goddelike deur positiewe stellings te beskryf — die teenoorgestelde van apofaties.",
     "'n Manier om oor God te praat deur te sê wat God is — \"God is love\" — eerder as net wat God nie is nie.",
     "Cataphatic teologie praat vol vertroue van God as liefdevol, regverdig en barmhartig.",
     "af, volgens", "om te praat, om te sê"),
    ("Gebaseer op vertroue of geloof; ook gebruik as 'n vaste verwysingspunt.",
     "Iets wat jy op vertroue aanvaar en dan as anker gebruik — 'n fiducial merk is die vaste punt waarteen alles anders gemeet word.",
     "Landmeters het 'n fiducial merker in die rotspunt geplaas voordat hulle die terrein gekarteer het.",
     "om te vertrou", "vertroue, sekerheid"),
    ("'n Verdediging van God se goedheid gegewe die bestaan van die kwaad.",
     "Die eeue-oue poging om te antwoord \"If God is good, why does evil exist?\"",
     "Haar tesis het theodicy deur die lens van die Boek van Job ondersoek.",
     "god", "geregtigheid"),
    ("Wederkerige inwoning — 'n teologiese term vir hoe die persone van die Drie-eenheid in mekaar bestaan.",
     "'n Teologie-woord vir drie-in-een-saamwees so volledig dat elke deel die ander ten volle bevat en deur hulle bevat word.",
     "Die leerstuk van circumincession probeer verduidelik hoe Vader, Seun en Gees onderskeie dog onafskeidbaar is.",
     "rondom", "om te gaan, om te loop"),
    ("Om 'n gevolg te hê wat iemand tot voordeel strek of op hulle terugslaan.",
     "Wanneer eer (of blaam) terugbons op die verantwoordelike persoon — goeie dade wat redound tot jou reputasie kom weer terug om jou te beloon.",
     "Die span se sukses sal redound tot die eer van sy stil, hardwerkende afrigter.",
     "terug, weer", "golf"),
    ("Onvermydelik; nie te ontsnap nie.",
     "Gedoem om te gebeur wat jy ook al doen — daar is geen uitkruip nie by 'n ineluctable uitkoms.",
     "Ouderdom kom vir almal; dit is eenvoudig ineluctable.",
     "nie", "om uit te worstel"),
    ("Wat omslagtige, woordryke formulering gebruik in plaas van 'n direkte vorm.",
     "Die lang pad met woorde — om \"make a decision\" te sê in plaas van \"decide.\"",
     "Sy periphrastic e-posse kon in een reël gesê het wat hom drie paragrawe gevat het.",
     "rondom", "om te verklaar, om te vertel"),
    ("Geestelike stompheid of lusteloosheid.",
     "Daardie mistige, trege gemoedstoestand waarin dink soos deur stroop waaier voel.",
     "'n Golf van hebetude het die klas net ná middagete getref.",
     "stomp, dof", "toestand of gehalte"),
    ("Nie gunstig nie; wat onheil voorspel.",
     "'n Slegte teken — omstandighede of tydsberekening wat teen jou lyk te werk nog voor jy begin het.",
     "Grys luchte en 'n dooie motorbattery het 'n unpropitious begin aan die padreis gegee.",
     "nie", "gunstig, genadig"),
    ("Vleis in sous gestoof of gebraseer — reg gespel \"fricasseed.\"",
     "'n Gesellige ou kookterm vir vleis wat opgesny en stadig in sy eie sous gesimmer is tot sag.",
     "Ouma se fricasseed hoender was die hoogtepunt van elke Sondagmaaltyd.",
     "om te braai", "om te breek (in stukke)"),
    ("'n Kunsmatige of minderwaardige plaasvervanger.",
     "'n Namaaksel wat vir die egte ding instaan — dit doen tegnies die werk, maar almal sien dis nie die ware artikel nie.",
     "Oorlogstydse kopers het hul gered met ersatz-koffie van geroosterde sigorei.",
     "uit, vervangingsvoorvoegsel", "om te sit, om te plaas"),
    ("Om 'n abstrakte idee te behandel asof dit 'n konkrete ding is.",
     "Om 'n idee werklik en solied te laat voel — iets dowes, soos \"the economy,\" in 'n ding te verander waarna jy kan wys.",
     "Om 'n nasie se \"spirit\" sy eie wese te noem, reifies iets wat eintlik net miljoene individuele keuses is.",
     "ding", "om te maak"),
    ("Het vaardig ontsnap of vermy.",
     "Skoon weggegly — iets ontwyk, dikwels slim of nou, of dit nou 'n vangs, 'n vraag of 'n antwoord is.",
     "Die antwoord het haar ure lank eluded tot dit skielik in die stort geklik het.",
     "uit, weg", "om te speel"),
    ("Wat twyfel, verbystering of 'n onopgeloste teenstrydigheid uitdruk.",
     "Vassit by 'n egte denkdoodloopstraat — nie verward uit luiheid nie, maar omdat die vraag self 'n netjiese antwoord weerstaan.",
     "Sokrates het sy dialoë dikwels op 'n aporetic noot geëindig, met meer vrae as antwoorde.",
     "sonder", "deurgang, weg"),
    ("'n Stylfiguur wat iets by 'n verwante term noem, bv. \"the crown\" vir die vorst.",
     "Om 'n verwante woord in die plek van die ware ding te gebruik — om te sê \"the White House announced\" as jy die administrasie bedoel.",
     "\"Wall Street had a rough day\" is metonymy — dit beteken eintlik die aandelemark het.",
     "verandering, ná", "naam"),
    ("Om met wortels en al uit te trek; om uit 'n natuurlike omgewing te skeur.",
     "Om iets (of iemand) met wortels en al uit te trek, weg van die plek of kultuur waar hulle hoort.",
     "Oorlog het 'n hele geslag deracinated en gesinne oor grense versprei.",
     "weg, af", "wortel"),
    ("Aangenaam klinkend.",
     "Net lekker om te hoor — 'n euphonious woord, naam of sin rol sag oor die oor, amper musikaal.",
     "\"Murmuring brook\" is 'n euphonious klein frase, sag en maklik om te sê.",
     "goed, wel", "klank, stem"),
    ("Algemeen aanvaar of veronderstel om te wees.",
     "Wyd geglo as waar, selfs al is dit nie werklik bewys nie — die \"supposed\" weergawe van iets.",
     "Die putative skrywer van die brief het later 'n volkome vreemdeling geblyk.",
     "om te dink, om te ag", "wat die aard het van"),
    ("'n Nuutgeskepte woord of frase.",
     "'n Splinternuwe woord — pas uitgevind, nog nie (of skaars) in die woordeboek nie.",
     "\"Doomscrolling\" het as 'n neologism begin en gou alledaagse slang geword.",
     "nuut", "woord, spraak"),
    ("Kwaad of sleggehumeurig.",
     "In 'n nare, prikkelbare bui — vinnig om te knap, soos mense eens geglo het die milt jou humeur beheer.",
     "Hy het 'n splenetic antwoord op die e-pos afgevuur binne sekondes nadat hy dit gelees het.",
     "milt (setel van woede)", "aangetas deur"),
    ("Geneig om op 'n pompeuse of gemaakte wyse te moraliseer.",
     "Is mal daaroor om klein lewenslesse op 'n selfbelangrike wyse te lewer, asof elke sin 'n gelukkiewielkoekie is.",
     "Sy sententious heildronk oor \"the true meaning of friendship\" het almal laat horlosies nagaan.",
     "mening, spreuk", "vol van"),
    ("Oordrewe praatsiek, veral oor triviale dinge.",
     "Hou net nie op praat nie — babbel oor kleinighede lank nadat almal anders se gesprekstof op is.",
     "Die garrulous taxibestuurder het ons sy hele lewensverhaal vertel voordat ons die lughawe verlaat het.",
     "om te babbel, om te klets", "geneig tot"),
    ("Dwaasheid, onnoselheid.",
     "Gewone dwaasheid — 'n opmerking of plan so onnosel dat dit skaars 'n ernstige antwoord verdien.",
     "Die blote fatuity van die plan het duidelik geword die oomblik toe hulle dit probeer het.",
     "dwaas, onnosel", "staat van wees"),
    ("Die afsluitende deel van 'n toespraak, dikwels samevattend.",
     "Die groot slot van 'n toespraak — die slotgedeelte waar die spreker alles saamtrek en die punt tuisbring.",
     "By die peroration was die helfte van die gehoor op hul voete.",
     "deur, tot die einde", "om te praat, om te bepleit"),
    ("Onnodige herhaling van dieselfde idee in ander woorde.",
     "Om dieselfde ding twee keer te sê sonder om iets nuuts by te voeg, soos \"free gift\" of \"end result.\"",
     "\"It is what it is\" is 'n gunsteling-tautology van mense wat 'n ware verklaring vermy.",
     "dieselfde", "woord, spraak"),
    ("Die gebruik van baie min woorde; bondige spraak.",
     "Om baie met min te sê — die kuns van die kort, stomp antwoord, genoem na die berugte kortaf Spartane van Lakonië.",
     "\"Molon labe\" — \"come and take them\" — is die geskiedenis se beroemdste stuk laconism.",
     "'n Spartaan van Lakonië", "gebruik, wyse"),
    ("Flaou, oorvereenvoudigde idees; oorspronklik, flaou kos of pap.",
     "Dun, waterige denke — inhoud so vereenvoudig en veilig dat dit geen voedingswaarde vir die gees het nie.",
     "Die politikus se toespraak was meestal pabulum: vae beloftes met niks waaraan jy kan vasklou nie.",
     "om te voed", "middel of instrument"),
    ("Wat slaap of slaperigheid veroorsaak.",
     "So dof — of so letterlik slaapverwekkend — dat dit jou slaperig maak. Dink aan warm melk, of 'n drie-uur-begrotingsvergadering.",
     "Die lesing se soporific gedreun het die helfte van die kamer laat veg om hul oë oop te hou.",
     "diep slaap", "makend, veroorsakend"),
    ("Oordrewe vleiend of olierig van maniere.",
     "Só glad charmant dat dit glibberig voel — vleiery so dik aangewend dat jy amper die vet kan voel.",
     "Die unctuous verkoper het my \"excellent taste\" bly prys voor elke opverkoop.",
     "om te salf, om te olie", "vol van"),
    ("Vinnig om fout te vind, oordrewe krities oor triviale dinge.",
     "Vitterig tot 'n fout — die tipe wat 'n probleem met alles vind, selfs as dit nie werklik saak maak nie.",
     "Sy captious notas op die verslag het geheel en al op kommaplek gefokus.",
     "om te gryp, om te vat", "'n strik, 'n sofisme"),
    ("Traag, geestelik of liggaamlik onaktief.",
     "Stadig en half aan die slaap, soos 'n beer in winterslaap — skaars aan die beweeg, skaars aan die dink.",
     "Die kantoor het torpid geraak in die swaar Augustus-hitte.",
     "om gevoelloos te wees, om traag te wees", "in 'n toestand van"),
    ("'n Rentmeester of beampte wat 'n middeleeuse huishouding bestuur het.",
     "Die middeleeuse weergawe van 'n hoof van personeel — die vertroude beampte wat 'n heer se huis en landgoed van dag tot dag bestuur het.",
     "Die kasteel se seneschal het alles van die oesrekeninge tot die gastelys bestuur.",
     "oud, senior", "dienaar"),
    ("Om uitvoerig oor 'n onderwerp te praat of te skryf.",
     "Om werklik op dreef te kom oor 'n onderwerp — aanhou praat of skryf en dit van elke hoek dek.",
     "Vra hom oor vintage motors en hy sal 'n volle uur expatiate.",
     "uit", "ruimte"),
    ("Van geen waarde, gering; ook ongeldig of ondoeltreffend.",
     "Wêreldlik niks werd nie — 'n nugatory klousule in 'n kontrak is een wat eintlik niks doen nie.",
     "Die hof het die ou verordening nugatory verklaar, aangesien dit nooit afgedwing is nie.",
     "kleinighede, onsin", "behorende tot"),
    ("Wysheid, skerp oordeel.",
     "Skerp, praktiese wysheid — die soort goeie oordeel wat uit ervaring kom, nie net boekkennis nie.",
     "Die ou kaptein se sagacity het die bemanning meer as een keer uit die moeilikheid gehou.",
     "skerp-ruikend, skerp", "gehalte van"),
    ("Die gewone gespuis of massas, minagtend gebruik.",
     "'n Snobistiese, afwysende woord vir \"the rabble\" of gewone mense, met minagting gebruik.",
     "Die graaf het gesny vir die canaille wat buite die paleishekke saamgetrek het.",
     "hond", "versameling, trop"),
    ("Brutalige, vernederende behandeling of taal.",
     "Wrede, spottende behandeling bedoel om te verneder — die soort belediging wat ontwerp is om te steek.",
     "Hy het jare se contumely van kritici verdra voordat sy werk eindelik erken is.",
     "met, deeglik", "om te swel (van trots)"),
    ("Met agterdog of afkeur; 'n sywaartse blik.",
     "Die sywaartse blik wat jy iets gee wat jy nie heeltemal vertrou nie — 'n kyk vol twyfel.",
     "Die onderwyser het askance na die verdag netjiese huiswerk gekyk.",
     "by, na", "skeef, vooroordeel"),
    ("'n Dom persoon; 'n houtkop.",
     "'n Ouderwetse, amper liefderike belediging vir iemand wat dof of dig is — 'n houtkop.",
     "\"You clodpate,\" het sy gelag, \"you've had the map upside down the whole time.\"",
     "klont aarde", "kop"),
    ("Om in beweging of aksie te bring; om te motiveer.",
     "Om die vonk te wees wat iets laat beweeg — of dit nou 'n masjien is wat aanskakel of 'n persoon wat eindelik op 'n idee optree.",
     "Vrees om die kontrak te verloor het die hele span actuated tot 'n naweek se oortyd.",
     "'n doen, 'n dryf", "om te dryf, om te doen"),
    ("Verduistering van fondse wat aan jou sorg toevertrou is.",
     "Stilweg geld steel wat jy vertrou is om na te sien — verduistering in 'n ouderwetse jas.",
     "Die tesourier se peculation het byna 'n dekade ongemerk verbygegaan.",
     "private eiendom", "vee, rykdom"),
    ("'n Groep wat op die rand van fatsoenlike samelewing gereken word.",
     "Die glansryke-maar-skaduryke sosiale onderwêreld — mense wat net buite die reëls van \"respectable\" samelewing leef.",
     "Die roman volg 'n sangeres wat die demi-monde van 1920's-kaberette navigeer.",
     "half", "wêreld, samelewing"),
    ("Nog bestaande; nie uitgesterf of vernietig nie.",
     "Nog vandag hier — gebruik vir ou dinge (manuskripte, spesies, geboue) wat dit reggekry het om te oorleef.",
     "Slegs drie extant kopieë van die eerste druk is bekend.",
     "uit", "om te staan"),
    ("Bedrieglikheid; verraad van vertroue.",
     "Diep, opsetlike verraad — 'n vertroue verbreek wat iemand tereg verwag het jy sou hou.",
     "Die generaal het nooit sy ou vriend se perfidy by die onderhandelingstafel vergewe nie.",
     "deur, teen", "geloof, vertroue"),
    ("'n Streekdialek, veral 'n nie-standaard een.",
     "Die kenmerkende, plaaslike manier waarop mense in 'n bepaalde streek praat — vol woorde en ritmes wat 'n buitestander dalk mis.",
     "Haar ouma het nog die eiland se patois by familiediners gepraat.",
     "ruwe spraak, dialek", "poot — lomp praat"),
    ("'n Spesiale reg wat aan 'n persoon of groep behoort.",
     "'n Voorreg wat joune en net joune is — 'n reg wat saam met jou rol, posisie of status kom.",
     "Om die familie se vakansiebestemming te kies is Oupa se prerogative, en almal weet dit.",
     "voor", "om te vra, om te stem"),
    ("Dapperheid, vermetelheid; ook taaiheid of uithouvermoë.",
     "Rukkerige, dapper weerstand — die durf om vorentoe te druk en die taaiheid om aan te hou sodra jy begin.",
     "Dit het ware hardihood gevat om die pas in 'n sneeustorm sonder kaart oor te steek.",
     "dapper, taai", "toestand, stand"),
    ("Om in blom uit te bars; ook om te ontwikkel of geleidelik te verskyn.",
     "Om tot volle uitdrukking oop te gaan — soos 'n blom wat oopgaan, of 'n idee wat eindelik tot sy reg kom.",
     "Haar stil skildertalent het effloresced toe sy eers haar eie ateljee gehad het.",
     "uit", "om te begin blom"),
    ("'n Gewig aan 'n tou om loodregtheid te bepaal; figuurlik, 'n maatstaf van oordeel.",
     "'n Gewig aan 'n tou wat perfek reguit afhang, gebruik om te kyk of iets werklik loodreg is — en, by uitbreiding, enige vaste maatstaf waarteen jy alles anders meet.",
     "Hy het sy eie oupa se eerlikheid as 'n soort plumb-line vir elke besluit gebruik.",
     "lood", "koord, maat"),
    ("Gaarne, gewillig (ouderwets).",
     "'n Ouderwetse manier om \"gladly\" of \"with pleasure\" te sê.",
     "\"I would fain rest here a while,\" het die reisiger gesug.",
     "bly, vrolik", "gaarne, gewillig"),
    ("Harde openbare kritiek of skande.",
     "Openbare skaamte wat op iemand in 'n groot, sigbare manier gestort word — die skande wat van wydverspreide afkeur kom.",
     "Die skandaal het openbare opprobrium oor die hele firma laat neerdaal.",
     "teen", "skande, verwyt"),
    ("Skerp sarkasties, bytende in gevatheid of kritiek.",
     "Gevatheid met regte tande — 'n mordant opmerking steek 'n bietjie juis omdat dit so trefseker gemik is.",
     "Haar mordant rolprentresensies is deur regisseurs gevrees en deur lesers gelief.",
     "om te byt", "bytende, doende"),
    ("'n Formele proklamasie, dikwels polities of militêr.",
     "'n Groot, amptelike aankondiging — gewoonlik een wat 'n nuwe regering, opstand of groot dekreet verklaar.",
     "Die generaal se pronunciamento het die nuwe regering teen dagbreek aangekondig.",
     "vorentoe", "om aan te kondig"),
    ("Iemand met oppervlakkige kennis wat voorgee om 'n kenner te wees.",
     "Iemand wat die oppervlak van 'n onderwerp afgekyk het en dan praat asof hulle die handboek daaroor geskryf het.",
     "Die dinee se sciolist het selfversekerd die werklike astrofisikus by die tafel reggehelp.",
     "om te weet", "verkleinwoord — 'n klein weter"),
    ("'n Afneming van geestelike vermoëns in die ouderdom.",
     "Die mistige, vergeetagtige strek van hoë ouderdom wanneer die skerpte van die gees begin vervaag.",
     "In sy dotage het hy dieselfde drie stories elke besoek vertel, elke keer asof dit nuut was.",
     "om te dote, om dwaas te wees", "toestand of gevolg"),
    ("Die kant wat teen die wind beskut is.",
     "Die kalm, beskutte kant van iets — 'n heuwel, 'n skip, 'n muur — waar die wind jou nie heeltemal bereik nie.",
     "Die stappers het hul tent aan die lee-side van die rif opgeslaan om die winde te ontsnap.",
     "skuiling, beskerming", "flank, gesig"),
    ("Om 'n hou, vraag of argument af te weer of weg te slaan.",
     "Om iets gladweg weg te slaan — 'n swaardhou, 'n ongemaklike vraag of 'n beskuldiging — sonder om 'n tree te mis.",
     "Sy het die joernalis se lastige vraag met 'n maklike grap parried.",
     "om af te weer", "om voor te berei, om te verdedig"),
    ("Slegtruikend, skadelik.",
     "Stinkend op 'n manier wat byna giftig voel — 'n stank so sleg dat dit gevaarlik lyk om asem te haal.",
     "'n Mephitic reuk het uit die moeras opgedryf toe die son sak.",
     "skadelike damp", "wat die aard het van"),
    ("Iemand wat aan weelde en plesier toegewy is.",
     "Iemand wat vir gemak en genot leef — fyn kos, sagte beddens, maklike lewe — genoem na die antieke Griekse stad Sybaris, bekend vir sy oormaat.",
     "'n Ware sybarite, hy het enige hotelkamer sonder 'n bad geweier.",
     "antieke Griekse stad bekend vir weelde", "inwoner van"),
    ("Om doelbewus 'n deel van iets opsy te sit of te ignoreer.",
     "Om 'n stuk van die legkaart doelbewus ter syde te sit, sodat jy skoon op die res kan fokus.",
     "Kom ons prescind 'n oomblik van die koste en vra net of die plan werklik werk.",
     "voor, weg", "om te sny"),
    ("Om streng te kritiseer; ook om vel af te stroop.",
     "Om iemand met harde kritiek stukkend te skeur — verbaal, asof jy letterlik die vel afstroop.",
     "Die kritici het die opvolger excoriated omdat dit alles verraai het wat aanhangers van die oorspronklike liefgehad het.",
     "af", "vel, huid"),
    ("Om as bewys of staaf aan te voer.",
     "Om 'n feit of voorbeeld vorentoe te bring om jou punt te staaf — die ding waarna jy wys as iemand vra \"what's your evidence?\"",
     "Die prokureur het drie getuies adduced om haar kliënt se alibi te staaf.",
     "na, toe", "om te lei"),
    ("Reise of swerftogte, veral lang of uitgebreide.",
     "Lang, swerwende reise — die soort uitgebreide swerf wat jou lank van die huis af wegneem.",
     "Sy peregrinations oor drie kontinente het 'n hele rak reisjoernale gevul.",
     "deur", "veld, land (peregrinus: vreemdeling)"),
    ("'n Bedelaar, of een wat van aalmoese leef.",
     "Iemand wat van liefdadigheid leef — histories het dit ook monnike beskryf wat armoede-geloftes afgelê en van skenkings geleef het.",
     "Die mendicant broeders het niks besit nie en heeltemal op die dorpenaars se goedheid staatgemaak.",
     "om te bedel", "bedelaar"),
    ("Uiters vrygewig.",
     "Vrygewig op 'n groot, amper vertoonagtige skaal — die soort geskenk wat mense 'n bietjie laat gis.",
     "Die munificent skenking het die hele nuwe vleuel van die biblioteek befonds.",
     "geskenk, diens", "makend, gewend"),
    ("Uitputting weens gebrek aan voeding; ook 'n gebrek aan lewenskrag.",
     "'n Swak, uitgeputte toestand van nie gevoed of aangevuur te wees nie — letterlik van honger, of figuurlik van niks oor te hê om op te ry nie.",
     "Teen die einde van die beleg was die soldate naby inanition.",
     "leeg, leemte", "die daad of gevolg van"),
    ("Bitter, beledigende kritiek.",
     "Kritiek wat lank verby billik gegaan het en in 'n kwaai, bitter uitbarsting verander het.",
     "Die aanlynkommentaar het binne minute in suiwer vituperation opgelos.",
     "fout", "om voor te berei, om te voorsien"),
    ("Vyandig, skadelik van uitwerking.",
     "Werk teen jou, selfs stilweg — omstandighede of houdings wat onvriendelik teenoor jou belange is.",
     "Die nuwe beleid was inimical vir klein besighede, selfs al was dit nie die bedoeling nie.",
     "nie", "vriend"),
    ("Geneig om wrok of ontevredenheid te wek, dikwels deur onbillike vergelykings.",
     "Gedoem om iemand te laat voel misken — gewoonlik omdat dit mense of dinge onbillik teen mekaar opstel.",
     "Om die sibbe te rangskik volgens \"who Mom loves best\" is 'n invidious spel wat niemand moet speel nie.",
     "jaloesie", "om te bekyk (met kwaadwilligheid)"),
    ("Iemand van laer rang of status; 'n ondergeskikte.",
     "Iemand laer op die bevelsketting of sosiale leer — 'n junior, wat onder iemand met meer mag werk.",
     "As jong subaltern het hy lank bevele geneem voordat hy ooit welke gegee het.",
     "onder", "wisselend, ander"),
    ("Om sterk haat teenoor iets te voel of uit te druk.",
     "Om iets só te verafsku dat jy dit hardop vervloek — suiwer, luidrugtige afsku.",
     "Die dorpenaars het die belastinggaarder execrated elke keer as sy wa deur die dorp gerol het.",
     "uit", "heilig (om uit die heilige te vloek)"),
    ("'n Natuurlike buitenste bedekking, soos vel of 'n dop.",
     "Die natuur se eie beskermende omhulsel — vel, dop, peul of skil, wat ook al iets lewendigs toemaak en beskerm.",
     "'n Skilpad se dop is 'n merkwaardig taai integument.",
     "op, oor", "om te bedek"),
    ("Onskuldig, naïef, met kinderlike eenvoud; die teenoorgestelde van \"disingenuous.\"",
     "Openlik vertrouend en 'n bietjie naïef, sonder enige verborge agenda — maklik om met \"ingenious\" te verwar, wat slim beteken.",
     "Haar ingenuous vraag — \"why would anyone lie about that?\" — het gewys hoe min slinksheid sy gehad het.",
     "in, inheems", "om te verwek (vrygebore, opreg)"),
    ("Oormatige bekommernis oor klein besonderhede of reëls.",
     "Verlore raak in die klein reëltjies en die groter prentjie mis — obsessie met die fynskrif waaroor niemand anders omgee nie.",
     "Sy pedantry oor Oxford-kommas het die hele vergadering ontspoor.",
     "kinders se onderwyser", "praktyk of gehalte"),
    ("'n Deeglike, sorgvuldige ondersoek.",
     "'n Diep, geen-klip-omgedraaide kyk na iets — elke besonderheid met ware sorg deurgaan.",
     "Eers na 'n noukeurige perscrutation van die grootboeke het die afwyking opgeduik.",
     "deur, deeglik", "om te soek, om te ondersoek"),
    ("Om besware te opper; om onwillig te toon.",
     "Om beleefd terug te druk of te huiwer eerder as dadelik saam te gaan — 'n sagte \"I'd rather not.\"",
     "Toe sy gevra is om te teken sonder om te lees, het sy demurred.",
     "van, weg", "om te talm"),
    ("Oppervlakkig aannemlik maar eintlik verkeerd.",
     "Klink oortuigend by die eerste oogopslag, maar val uitmekaar die oomblik as jy dit werklik nagaan.",
     "\"Everyone's doing it\" is 'n specious argument wat nooit heeltemal onder ondersoek hou nie.",
     "voorkoms, aansien", "vol van (skynbaar mooi)"),
    ("Oneerlike, skynheilige praat, dikwels moraliserend.",
     "Preekagtige praat wat deugsaam klink maar deur geen ware gevoel gesteun word nie — morele posering op outopilot.",
     "Hy was moeg vir die korporatiewe cant oor \"family\" van 'n maatskappy wat nooit iemand afgee nie.",
     "om te sing (later: singsang-jargon)", "bedelaars se kermende praat, daarna skynheiligheid"),
    ("Sonder moed, lafhartig.",
     "Bang tot ruggraatloosheid — té bang om standpunt in te neem selfs wanneer dit duidelik saak maak.",
     "Die raad se pusillanimous stilte het die skandaal uit beheer laat spiral.",
     "baie klein", "gees, moed"),
    ("Jakkalsagtig; slinks, listig.",
     "Slinks en slim soos 'n jakkals — vinnig van verstand, 'n bietjie gluiperig, altyd 'n tree vooruit.",
     "Hy het 'n vulpine glimlag gegee die oomblik toe hy die slaggat raakgesien het.",
     "jakkals", "van of soos"),
    ("Een ná die ander, in volgorde.",
     "Streng een op 'n slag, in volgorde — geen voorspring nie, geen twee gelyktydig nie.",
     "Die regter het elk van die twaalf eise seriatim aangespreek.",
     "ry, volgorde", "een op 'n slag"),
    ("Uiterste spaarsaamheid; vrekkerigheid.",
     "Suinig wees met geld (of woorde, of hulpbronne) ver verby redelike spaarsaamheid.",
     "Sy parsimony was legendaries — hy het teesakkies drie keer hergebruik.",
     "om te spaar, om spaarsaam te wees", "toestand of praktyk"),
    ("'n Regstelling, veral in 'n teks.",
     "'n Herstel aan 'n stuk skryfwerk — 'n geleerde aanpassing wat 'n fout in 'n ou of belangrike teks regstel.",
     "Die nuwe uitgawe bevat dosyne emendations aan die oorspronklike manuskrip.",
     "uit", "fout, dwaling"),
    ("Matig in eet en drink.",
     "Doelbewus ingetoë rondom kos en drank — nooit oordadig nie, altyd 'n bietjie op die bord gelos.",
     "Sy abstemious gewoontes het hom skerp gehou lank nadat sy leeftydgenote vertraag het.",
     "weg van", "bedwelmende drank"),
    ("'n Grammatikale fout of 'n skending van etiket.",
     "'n Misstap in grammatika of maniere — die soort klein fout wat 'n vitter laat wince.",
     "\"Between you and I\" is 'n algemene solecism wat grammatikuste steeds laat ruggraat kry.",
     "Silisiese stad bekend vir 'slegte' Grieks", "gebruik, wyse"),
    ("Wat betrekking het op konflik binne 'n groep; wedersyds vernietigend.",
     "Binnegeveg wat 'n groep van binne verskeur — 'n stryd waarin almal verloor, want dit is familie teen familie.",
     "Die party se internecine gekibbel het meer skade gedoen as enige buitestaander ooit kon.",
     "tussen, onder", "om te dood"),
    ("Onverskillige, nalatige houding.",
     "'n Skouerophaling tot 'n hele persoonlikheid gemaak — so min omgee vir dinge wat vroeër saakgemaak het dat niks meer die moeite werd lyk nie.",
     "Sy pococurante houding teenoor die prysseremonie het almal verras wat geweet het hoe hard hy gewerk het.",
     "bietjie", "om om te gee"),
    ("'n Verwarde, ingewikkelde situasie of dispuut.",
     "'n Verwronge, gemorsige situasie wat moeilik is om sin van te maak — deels misverstand, deels drama, alles verwarring.",
     "Die hele sitplekkaart-imbroglio het met een verkeerd geplaasde naamkaartjie begin.",
     "in", "om te verstrengel, om te verwar"),
    ("Dreigend, dreigend.",
     "Dra 'n onmiskenbare lug van dreigement — 'n minatory blik of brief maak dit baie duidelik dat iets sleg kan volg.",
     "Die minatory toon van die brief het die huurder senuweeagtig gemaak nog voordat sy die koevert oopgemaak het.",
     "om te dreig", "dienende tot"),
    ("Sterk openbare kritiek of verbale skeldery.",
     "Luidrugtige, openbare veroordeling — die soort blitsende kritiek wat voor almal afspeel.",
     "Die fluitblaser het jare se openbare obloquy in die gesig gestaar voordat die geskiedenis haar gelyk gegee het.",
     "teen", "om te praat"),
    ("'n Skielike geweldadige uitbarsting, van emosie of aksie.",
     "'n Skielike, intense stoot wat jou ineens oorweldig — 'n vlaag van lag, woede of hoes wat soos 'n golf tref.",
     "Sy is deur 'n paroxysm van lag aangegryp wat sy vir niemand anders in die kamer kon verduidelik nie.",
     "bo", "skerp, akuut"),
    ("Bygevoeg uit 'n eksterne bron, nie inherent nie.",
     "Van buite vasgeskroef eerder as van die begin af ingebou — 'n ekstra, nie 'n kerndeel nie.",
     "Die kommentaar voel adscititious, asof dit op 'n reeds voltooide teks geplak is.",
     "by, bykomend", "om goed te keur, om aan te neem"),
    ("Gebrek aan kennis, onkunde.",
     "Eenvoudige nie-weet — 'n gaping in kennis, sonder enige oordeel daaraan geheg.",
     "Hy het sy nescience van Franse wyn erken en die sommelier laat kies.",
     "nie", "om te weet"),
    ("Oormatige belangstelling in seksuele sake.",
     "'n Oorywerige, loerende nuuskierigheid oor enigiets pittig — belangstelling wat verby gesond naatjie gegaan het.",
     "Die tabloid se prurience oor die paartjie se privaatlewe het aan obsessief gegrens.",
     "om te jeuk, om te smag na", "toestand van"),
    ("Roetig, donker, donkerig.",
     "Donker en rokerig van voorkoms, asof alles met 'n dun laag roet bedek is.",
     "'n Fuliginous waas het teen skemer oor die fabrieksdorp gehang.",
     "roet", "vol van"),
    ("Om te ontken of te weerspreek.",
     "Om platweg teen iets te praat wat iemand anders gesê het — om te sê \"that's not so.\"",
     "Niemand het durf gainsay die ou kaptein se relaas van die storm nie.",
     "teen", "om te praat"),
    ("Luiheid, traagheid (uit Latyn).",
     "'n Ou Latynse woord vir suiwer luiheid — die sleep van glad niks te wil doen nie.",
     "Die monnike het teen ignavia gepreek as een van die siel se stille gevare.",
     "nie", "besig, ywerig"),
    ("'n Skild wat 'n wapen toon.",
     "Die skildvormige embleem wat 'n familie se wapen toon — sy heraldiese \"nameplate.\"",
     "Die familie se escutcheon hang nog bo die ou herehuis se voordeur.",
     "skild", "verkleinwoord / voorwerp"),
    ("Verouderd, obsoleet, of weens ouderdom afgetree.",
     "Verby sy nuttige toppunt en op die weiveld gesit — té ouderwets of verslete om die werk aan te hou doen.",
     "Die superannuated drukker is eindelik ná vyftien jaar se vasmaak vervang.",
     "bo", "jaar"),
    ("Plaasvervangers, veral in die geneeskunde.",
     "Instaanmiddels wat gebruik word wanneer die ware behandeling nie beskikbaar is nie — mediese onderstudies, in wese.",
     "Oorlogstydse dokters het dikwels op succedanea staatgemaak wanneer die regte medisyne opgeraak het.",
     "in die plek van", "om te gaan, om te wyk"),
    ("Spoggerige, blaserige praat.",
     "Groot, blaserige spog — luide praat oor jou eie grootheid wat meestal warm lug is.",
     "Sy rodomontade oor hoe hy die projek \"single-handedly\" gered het, het niemand gefop wat werklik daar was nie.",
     "spoggerige ridder in Orlando Furioso", "handeling, vertoon"),
    ("Om slenter of bedrog te gebruik om iets te bereik.",
     "Om jou met gluiperige truuks na 'n doel te wurm eerder as deur billike spel.",
     "Hy het hom met 'n kontrak vol fynskrif in die ooreenkoms chicaned.",
     "om te kibbel, om te bedrieg", "slenter; later 'n skerp draai"),
    ("Die suiwer of abstrakte wetenskap van leer of kennis, dikwels wiskunde.",
     "Leer in sy suiwerste, mees abstrakte vorm — die diep struktuur van kennis self, veral die wiskundige soort.",
     "Die filosoof het van 'n universele mathesis gedroom wat elke kennisveld kon verenig.",
     "om te leer", "die daad van leer"),
    ("Oordrewe begaan oor formele reëls of triviale besonderhede.",
     "Oordrewe streng oor die kleinighede — klein tegniese puntjies korrigeer wat eintlik niks verander nie.",
     "Dit het 'n bietjie pedantic gevoel om in 'n teksboodskap oor \"who\" versus \"whom\" te stry.",
     "kindergids, tutor", "wat die wyse het van"),
    ("'n Flitsende, sprankelende lig.",
     "'n Vinnige, glinsterende ligflits — dink aan sonlig wat van water afbons, of 'n diamant wat die lig vang.",
     "Die coruscation van die kandelaar het lig oor elke hoek van die balsaal gestrooi.",
     "om te glinster, om te flits", "die daad van"),
    ("'n Beginner, nuweling.",
     "Iemand splinternuut in 'n vaardigheid of veld — nog besig om die toue te leer, nog nie 'n kenner nie.",
     "Selfs 'n tyro skaakspeler kan daardie flater raaksien.",
     "rekruut, nuweling", "'n rou jong soldaat"),
    ("Uiters sleg, veragtelik.",
     "Sleg op 'n manier wat ware afsku verdien — nie net \"mediocre\" nie, maar werklik veragtelik.",
     "Die resensent het die opvolger execrable genoem, en die kassytellings het saamgestem.",
     "om te vervloek", "waardig, in staat om"),
    ("Bloedrooi van kleur.",
     "'n Diep, lewendige rooi — die kleur van vars bloed, beroemd deur Shakespeare se Macbeth gebruik.",
     "Die sonsondergang het die hele hemel 'n incarnadine gloed gegee.",
     "in", "vlees (vlees-rooi)"),
    ("'n Klein gaping of spasie tussen dinge.",
     "Die piepklein tussenruimte wat maklik misgekyk word — die skeur tussen die vloerplanke, die gaping in 'n rooster.",
     "Onkruid het deur elke interstice in die ou baksteenpaadjie opgestoot.",
     "tussen", "om te staan"),
    ("Kritiese of afkeurende opmerkings.",
     "Puntige, afkeurende kommentaar — die soort kritiek wat 'n bietjie skeltoon dra.",
     "Die professor se animadversions op die opstel het die kantlyne met rooi ink gevul.",
     "verstand", "om na te draai"),
    ("Onmoontlik om te weerlê, onontkenbaar.",
     "Só solied bewys dat daar nie mee te stry is nie — die saak is eenvoudig toe.",
     "Die DNA-bewys was irrefragable, en die verhoor was binne die uur verby.",
     "nie", "om te weerstaan, om teë te staan"),
    ("Kompleksiteit, ingewikkeldheid; ook 'n inwaartse krul.",
     "'n Verwronge, in-homself-gevoude soort kompleksiteit — dinge só styf inmekaar gewikkel dat hulle moeilik uitmekaar te trek is.",
     "Die plot se involution het die helfte van die gehoor ná die nateks probeer ontrafel.",
     "in, inwaarts", "om te rol, om te draai"),
    ("Krag of poging, soos in \"by dint of.\"",
     "Blote poging of krag — oorleef vandag meestal in die frase \"by dint of.\"",
     "Hy het die eksamen by dint of blote, koppige oefening geslaag.",
     "'n hou, 'n slag", "deur krag van"),
    ("Met 'n tap-en-gat-las verbind; stewig inmekaar gepas.",
     "Op die ouderwetse skrynwerker se manier inmekaar gesluit — een stuk wat netjies in 'n gaatjie gly wat net daarvoor gesny is.",
     "Die ou skuur se balke was sonder 'n enkele spyker mortised.",
     "'n holte, 'n gat", "'n byt, 'n greep"),
    ("Hoogs relevant, trefseker.",
     "Presies die regte pas vir die oomblik — 'n opmerking, aanhaling of voorbeeld wat perfek op die punt land.",
     "Haar apposite opmerking het die hele debat in een sin opgesom.",
     "na", "om te plaas"),
    ("Sag gloeiend of flikkerend (lig); ook ligte gevatheid.",
     "Sag gloeiend eerder as blakend — 'n sagte, flikkerende lig, of 'n gevatheid wat speels eerder as skerp is.",
     "Kerlig het 'n lambent gloed oor die ou eetkamer gegooi.",
     "om te lek", "doende (lig wat 'lek')"),
    ("'n Godsdienstige kluisenaar wat in eensaamheid leef.",
     "Iemand wat hom heeltemal van die wêreld onttrek om alleen in gebed en nadenke te leef.",
     "Die anchorite het meer as dertig jaar in 'n klein sel teen die kerk gewoon.",
     "terug, weg", "om hom te onttrek"),
    ("Om dors te les; om te blus.",
     "Om 'n hunkering ten volle te bevredig — meestal dors, maar figuurlik enige diep behoefte.",
     "Een koue glas water het sy dors ná die lang staptog slaked.",
     "slap, los", "om te verslap, om te les"),
    ("Naaldvormig.",
     "Lank, dun en gepunt soos 'n naald — die vorm van 'n denne-naald of 'n skerp klein kristal.",
     "Dennebome is maklik aan hul acicular blare te herken.",
     "naald", "klein"),
    ("Van lewenskrag uitgeput, swak, oorverfyn.",
     "Verslete en sag — sy oorspronklike krag of pit deur te veel gemak of verfyning verloor.",
     "Kritici het die eens-dapper tydskrif effete genoem, 'n skaduwee van sy vroeë dapper jare.",
     "uit", "vrugbaar, wat gedra het"),
    ("'n Bykomstigheid of kleiner aangehegte item of reg.",
     "'n Klein ekstra wat aan iets groters kleef — die bykomstighede en aanhangsels wat by die hoofsaak hoort.",
     "Die huurkontrak het die motorhuis en al sy appurtenances ingesluit.",
     "na", "om te behoort"),
    ("Om 'n fout te verbloem of te verklein.",
     "Om 'n fout met sagte woorde glad te stryk, sodat dit kleiner klink as wat dit werklik is.",
     "Hy het probeer gloze oor die gemiste sperdatum met vage praat van \"unforeseen challenges.\"",
     "'n glos, 'n verklaring", "om te kommentaar — daarna om glad te stryk"),
    ("In 'n vroeë stadium, net aan die begin.",
     "Net begin om homself te toon — die heel eerste, skaars-sigbare stadium van iets groters wat kom.",
     "Dokters het die incipient tekens van die siekte gevang voordat dit kon versprei.",
     "op, in", "om te vat (om op te vat, om te begin)"),
    ("Skeppende inspirasie, veral goddelike.",
     "'n Skielike golf van inspirasie wat groter as jy voel — asof die idee van iewers anders in jou ingeasem is.",
     "Die digter het beskryf hoe die hele stuk in een stoot van afflatus om 3 vm. gekom het.",
     "na, op", "om te blaas ('n aanblaas)"),
]
