# Icelandic rows
ROWS = [
    ("Að sæta eða hreinsa; að fjarlægja stríðleika úr einhverju.",
     "Að taka broddinn eða beiskjuna úr einhverju — bókstaflega með því að sæta það, eða myndrænt með því að mýkja harða hugmynd svo hún fari auðveldar niður.",
     "Ritstjórinn edulcorated hörðu umsögnina áður en hún fór í prentun.",
     "út, rækilega", "sætt"),
    ("Of eða tilgerðarlega trúarlegur eða guðhræddur.",
     "Lýsir einhverjum sem trúarleg hollusta virðist sviðsett til sýnis — meira sýning en raunveruleg trú.",
     "Pietistic andvörp hans í predikuninni pirruðu restina af bekknum.",
     "guðhræðsla, skyldurækni", "sem hefur eðli"),
    ("Tvíræðni sem sprettur af málfræðilegri byggingu — setning sem má lesa á tvo vegu.",
     "Setning sem er málfræðilega í lagi en má lesa á tvo algjörlega ólíka vegu, eins og \"I saw the man with the telescope.\"",
     "\"Visiting relatives can be tiring\" er klassísk amphiboly — eru ættingjarnir þreytandi, eða er það að heimsækja þá?",
     "báðir, á báðar hliðar", "að kasta"),
    ("Beitt, nákvæmt, skera beint að kjarna málsins.",
     "Sker beint í gegnum fyllinguna — trenchant athugasemd eða hugur kemst fljótt að hjarta málsins, án ónýtra orða.",
     "Trenchant gagnrýni hennar skildi engum stað eftir fyrir söguholur kvikmyndarinnar að fela sig.",
     "að skera", "gerandi, sem hefur eiginleika"),
    ("Nýbyrjað; á snemmbúnu eða frumstigi.",
     "Enn í opnunarandartaki — áætlun, tilfinning eða ferli sem er nýbyrjað að taka á sig mynd.",
     "Inchoative stig samningsins voru efnileg, en mörg smáatriði voru enn óleyst.",
     "að byrja, að hefja", "sem stefnir að"),
    ("Formleg ræða eða rit sem lofar einhvern hátt.",
     "Fullgert, formlegt lof — hugsaðu glóandi minningarræðu eða ræðu sem syngur afrek einhvers af þökunum.",
     "Prófessorinn sem lét af störfum var kvaddur með panegyric frá nánustu nemendum sínum.",
     "allt", "samkoma, safn"),
    ("Varðar raunverulega tilvist eða staðreynda veru, andstætt abstrakt kenningu.",
     "Um hluti eins og þeir raunverulega eru til, ekki bara sem hugmyndir eða kenningar um þá.",
     "Heimspekingar deila um hvort tölur hafi einhverja ontic stöðu eða séu bara til í hugum okkar.",
     "vera, það sem er", "sem varðar"),
    ("Að bera ávöxt, eða verða afkastamikið.",
     "Að greiða sig loksins — átak, hugmynd eða fjárfesting sem fructify, hefur vaxið úr fræi í eitthvað gagnlegt.",
     "Ára kyrr rannsókn fructified loksins í virkt bóluefni.",
     "ávöxtur", "að gera, að valda"),
    ("Sem á undan eða sýnir eitthvað sem þegar gert áður en það hefur raunverulega gerst.",
     "Að hlaupa á undan á bókmenntalegan hátt — lýsa framtíðaratburði sem hann væri þegar búinn, svo punkturinn lendi harðar.",
     "Proleptical skál hershöfðingjans fyrir \"victory\" var borin fram heilli viku fyrir orrustuna.",
     "á undan", "að taka, að grípa"),
    ("Knúið loftþrýstingi; einnig tengt anda eða andardrætti.",
     "Merkir yfirleitt \"knúið þrýstilofti\" — þó það geti líka átt við anda eða andardrátt.",
     "Pneumatic bremsurnar hvæstu þegar strætóinn stöðvaðist við kantsteininn.",
     "vindur, andardráttur, andi", "sem tilheyrir"),
    ("Að lýsa Guði eða hinu guðlega með jákvæðum fullyrðingum — andstæða apófatísks.",
     "Leið til að tala um Guð með því að segja hvað Guð er — \"God is love\" — fremur en bara hvað Guð er ekki.",
     "Cataphatic guðfræði talar örugg um Guð sem elskandi, réttlátan og miskunnsaman.",
     "niður, samkvæmt", "að tala, að segja"),
    ("Byggt á trausti eða trú; einnig notað sem fast viðmiðunarpunkt.",
     "Eitthvað sem þú tekur á trausti og notar svo sem akkeri — fiducial merki er fasta punkturinn sem allt annað er mælt við.",
     "Landmælingamenn settu fiducial merki í berggrunninn áður en þeir kortlögðu svæðið.",
     "að treysta", "traust, öruggt"),
    ("Vörn fyrir gæsku Guðs í ljósi tilvistar hins illa.",
     "Hina aldagömlu tilraun til að svara \"If God is good, why does evil exist?\"",
     "Ritgerð hennar skoðaði theodicy í gegnum Jobsbók.",
     "guð", "réttlæti"),
    ("Gagnkvæm innistun — guðfræðilegt hugtak um hvernig persónur þrenningarinnar eru hver í annarri.",
     "Guðfræðiorð fyrir þrjá-í-einum samveru svo fullkomna að hver hluti inniheldur hina og er innihaldinn af þeim.",
     "Kenningin um circumincession reynir að útskýra hvernig Faðir, Sonur og Andi eru aðskildir en óaðskiljanlegir.",
     "umhverfis", "að fara, að ganga"),
    ("Að hafa afleiðingu sem gagnast einhverjum eða speglast til baka á hann.",
     "Þegar heiður (eða sök) skoppar til baka á ábyrgðaraðilann — góð verk sem redound til orðstírs þíns koma til baka og verðlauna þig.",
     "Árangur liðsins mun redound til heiðurs hins hljóða, vinnusama þjálfara.",
     "til baka, aftur", "bylgja"),
    ("Óhjákvæmilegt; ekki hægt að forðast eða slíta sig lausan.",
     "Dæmt til að gerast sama hvað þú gerir — engin leið að slíta sig lausan úr ineluctable niðurstöðu.",
     "Ellin kemur til allra; hún er einfaldlega ineluctable.",
     "ekki", "að berjast út"),
    ("Sem notar umsvifamiklar, orðmargar setningar í stað beinnar myndar.",
     "Að taka langa leiðina með orðunum — að segja \"make a decision\" í stað \"decide.\"",
     "Periphrastic tölvupóstar hans hefðu getað sagt í einni línu það sem tók hann þrjár málsgreinar.",
     "umhverfis", "að lýsa, að segja"),
    ("Andleg sljóleiki eða sljóleiki.",
     "Sú þokukennda, seinfæra hugarástand þar sem hugsun finnst eins og að vaða í sýrópi.",
     "Bylgja hebetude skall á bekkinn strax eftir hádegismat.",
     "sljór, bitlaus", "ástand eða eiginleiki"),
    ("Óhagstætt; sem boðar illt.",
     "Slæmt merki — aðstæður eða tímasetning sem virðast vinna gegn þér áður en þú ert einu sinni byrjaður.",
     "Grár himinn og dauð bílastaðla gerðu unpropitious byrjun á bíltúrnum.",
     "ekki", "hagstætt, náðugt"),
    ("Kjöt soðið eða brasað í sósu — rétt stafsett \"fricasseed.\"",
     "Huggulegt gamalt eldunarorð yfir kjöt sem hefur verið skorið upp og soðið hægt í eigin sósu þar til það er meyrt.",
     "Fricasseed kjúklingur ömmu var hápunktur hvers sunnudagsmatars.",
     "að steikja", "að brjóta (í bita)"),
    ("Gervi eða lakari staðgengill.",
     "Eftirlíking sem stendur í stað hins sanna — hún vinnur verkið tæknilega, en allir sjá að þetta er ekki alvöru vara.",
     "Stríðstíðar viðskiptavinir björguðu sér með ersatz-kaffi soðnu úr ristuðu sikóríu.",
     "út, staðgengilsforskeyti", "að setja, að koma fyrir"),
    ("Að meðhöndla abstrakta hugmynd eins og hún væri áþreifanlegur hlutur.",
     "Að láta hugmynd finnast raunveruleg og föst — að snúa einhverju óljósu, eins og \"the economy,\" í hlut sem hægt er að benda á.",
     "Að kalla \"spirit\" þjóðar sinn eigin veru reifies eitthvað sem er í raun bara milljónir einstakra vala.",
     "hlutur", "að gera"),
    ("Slapp undan eða forðaðist af list.",
     "Renndi hreint í burtu — sneiddi hjá einhverju, oft kænlega eða naumlega, hvort sem það var grip, spurning eða svar.",
     "Svarið eluded hana í klukkustundir þar til það smellti skyndilega í sturtunni.",
     "út, í burtu", "að leika"),
    ("Sem tjáir efa, rugl eða óleysta mótsögn.",
     "Föst í raunverulegum hugsunarendapunkti — ekki rugluð af leti, heldur vegna þess að spurningin sjálf stendur gegn snyrtilegu svari.",
     "Sókrates lauk oft samræðum sínum á aporetic nótu, með fleiri spurningum en svörum.",
     "án", "gangur, leið"),
    ("Stílbragð sem nefnir eitthvað með tengdu hugtaki, t.d. \"the crown\" fyrir konunginn.",
     "Að nota tengt orð í stað hlutarins sjálfs — að segja \"the White House announced\" þegar þú átt við stjórnina.",
     "\"Wall Street had a rough day\" er metonymy — það þýðir í raun hlutabréfamarkaðinn.",
     "breyting, eftir", "nafn"),
    ("Að rífa upp með rótum; að rífa úr náttúrulegu umhverfi.",
     "Að draga eitthvað (eða einhvern) upp með rótum, í burtu frá staðnum eða menningunni sem þau tilheyra.",
     "Stríð deracinated heila kynslóð og dreifði fjölskyldum yfir landamæri.",
     "í burtu, af", "rót"),
    ("Ánægjulegt á heyrn.",
     "Einfaldlega gott að heyra — euphonious orð, nafn eða setning rúllar mjúkt um eyrað, nánast tónlistarlega.",
     "\"Murmuring brook\" er euphonious lítil setning, mjúk og auðvelt að segja.",
     "gott, vel", "hljóð, rödd"),
    ("Almennt talið eða ætlað að vera.",
     "Víða trúað sönnu, jafnvel þótt það hafi ekki raunverulega verið sannað — \"supposed\" útgáfan af einhverju.",
     "Putative höfundur bréfsins reyndist síðar algjör ókunnugur.",
     "að hugsa, að telja", "sem hefur eðli"),
    ("Nýmyndað orð eða orðasamband.",
     "Alveg nýtt orð — nýuppfunnið, enn ekki (eða varla) í orðabókinni.",
     "\"Doomscrolling\" byrjaði sem neologism og varð fljótt hversdagslegt slangur.",
     "nýtt", "orð, tal"),
    ("Reiður eða illa skapi.",
     "Í vondu, pirruðu skapi — fljótur að smella, eins og fólk trúði einu sinni að miltað stýrði skapinu.",
     "Hann sendi splenetic svar við tölvupóstinum á sekúndum eftir að hafa lesið hann.",
     "milta (sæti reiði)", "sem hefur áhrif"),
    ("Hneigður til að siðpræða á pompósa eða tilgerðarlegan hátt.",
     "Elskar að deila litlum lífslexíum á sjálfumfullan hátt, eins og hver setning sé heppnikaka.",
     "Sententious skál hans um \"the true meaning of friendship\" fékk alla til að horfa á klukkuna.",
     "skoðun, málsháttur", "fullt af"),
    ("Of málgefinn, sérstaklega um smávægilega hluti.",
     "Hættir bara ekki að spjalla — þvælist um smámuni löngu eftir að allir aðrir eru búnir að umræðuefni.",
     "Garrulous leigubílstjórinn sagði okkur alla ævisögu sína áður en við vorum farnir frá flugvellinum.",
     "að þvælast, að babbla", "hneigður til"),
    ("Heimska, fíflska.",
     "Hrein heimska — athugasemd eða áætlun svo fíflaleg að hún á varla skilið alvarlegt svar.",
     "Hrein fatuity áætlunarinnar varð ljós um leið og þeir reyndu hana.",
     "heimskur, fíflalegur", "ástand þess að vera"),
    ("Lokahluti ræðu, oft samantekt.",
     "Stóra endirinn á ræðu — lokakaflinn þar sem ræðumaðurinn dregur allt saman og rekur punktinn heim.",
     "Við peroration stóð helmingur áhorfenda á fótunum.",
     "í gegnum, til enda", "að tala, að flytja"),
    ("Óþörf endurtekning sömu hugmyndar með öðrum orðum.",
     "Að segja það sama tvisvar án þess að bæta neinu nýju við, eins og \"free gift\" eða \"end result.\"",
     "\"It is what it is\" er uppáhalds-tautology fólks sem forðast raunverulega skýringu.",
     "hið sama", "orð, tal"),
    ("Notkun mjög fárra orða; stuttmælt tal.",
     "Að segja mikið með litlu — listin að stuttu, beinu svari, nefnd eftir hinum alræmdu fáorðu Spartverjum Lakóníu.",
     "\"Molon labe\" — \"come and take them\" — er frægasta laconism sögunnar.",
     "Spartverji frá Lakóníu", "siður, háttur"),
    ("Daufar, ofureinfaldar hugmyndir; upphaflega, dauf matur eða grautur.",
     "Þunn, vatnsblandað hugsun — efni svo einfaldað og öruggt að það hefur ekkert næringargildi fyrir hugann.",
     "Ræða stjórnmálamannsins var að mestu pabulum: óljósar loforð án neins sem hægt var að festa á.",
     "að fæða", "tæki eða áhald"),
    ("Sem veldur svefni eða sljóleika.",
     "Svo leiðinlegt — eða svo bókstaflega svæfandi — að það gerir mann syfjaðan. Hugsaðu um heitt mjólk, eða þriggja klukkustunda fjárhagsfundn.",
     "Soporific suð fyrirlestursins fékk helming herbergisins til að berjast við að halda augunum opnum.",
     "djúpur svefn", "gerandi, valda"),
    ("Of smjaðrandi eða olíukenndur í háttum.",
     "Svo slétt heillandi að það finnst hált — smjör klárt svo þykkt að þú finnur nánast fitu.",
     "Unctuous sölumaðurinn hélt áfram að hrósa \"excellent taste\" mínu fyrir hverja uppsala.",
     "að smyrja, að olía", "fullt af"),
    ("Fljótur að finna sök, of gagnrýninn á smávægilega hluti.",
     "Nákvæmur að sök — gerðin sem finnur vandamál við allt, jafnvel þegar það skiptir ekki máli.",
     "Captious athugasemdir hans við skýrsluna snérust eingöngu um kommastöður.",
     "að grípa, að taka", "gildra, sófisma"),
    ("Seinn, andlega eða líkamlega óvirkur.",
     "Hægur og hálfsófandi, eins og björn í vetrardvala — varla á hreyfingu, varla í hugsun.",
     "Skrifstofan féll torpid í þunga ágústhitann.",
     "að vera dofinn, að vera seinn", "í ástandi"),
    ("Ráðsmaður eða embættismaður sem stjórnaði miðaldahúsi.",
     "Miðaldaútgáfa af starfsfólksstjóra — trausti embættismaðurinn sem rak hús og eignir drottins frá degi til dags.",
     "Seneschal kastalans sá um allt frá uppskerureikningum til gestalista.",
     "gamall, eldri", "þjónn"),
    ("Að tala eða skrifa ítarlega um efni.",
     "Að komast virkilega á flug um efni — tala eða skrifa og þekja það frá hverju horni.",
     "Spurðu hann um vintagebíla og hann mun expatiate í heila klukkustund.",
     "út", "rými"),
    ("Án gildis, léttvægt; einnig ógilt eða árangurslaust.",
     "Í raun einskis virði — nugatory ákvæði í samningi er eitt sem gerir í raun ekkert.",
     "Dómstóllinn dæmdi gamla samþykktina nugatory, þar sem hún hafði aldrei verið framfylgt.",
     "smámuni, bull", "sem tilheyrir"),
    ("Viska, skarpskyggn dómgreind.",
     "Skörp, hagnýt viska — sú góða dómgreind sem kemur af reynslu, ekki bara bókavit.",
     "Sagacity gamla skipstjórans hélt áhöfninni frá vandræðum oftar en einu sinni.",
     "skarpur á lykt, skarpskyggn", "eiginleiki"),
    ("Pöbbel eða massar, notað fyrirlitlega.",
     "Snobbótt, afneitandi orð yfir \"the rabble\" eða alþýðu, notað með fyrirlitningu.",
     "Greifinn hæðst að canaille sem safnast fyrir utan hallarhliðin.",
     "hundur", "safn, hjörð"),
    ("Ósvífin, niðurlægjandi meðferð eða mál.",
     "Grimm, háðsleg meðferð ætluð til að niðurlægja — sú tegund móðgunar sem er hönnuð til að sviða.",
     "Hann þoldi ár af contumely frá gagnrýnendum áður en verk hans voru loks viðurkennd.",
     "með, rækilega", "að þenjast (af hroka)"),
    ("Með tortryggni eða vanþóknun; hliðarsýn.",
     "Sú hliðarsýn sem þú gefur einhverju sem þú treystir ekki alveg — svipur hlaðinn efa.",
     "Kennarinn horfði askance á grunsamlega snyrtilega heimalærdóminn.",
     "að, til", "skakkt, hlutdrægni"),
    ("Heimskur maður; trékollur.",
     "Gamaldags, nánast kærleg móðgun við einhvern sem er seinn eða þykkhyrndur — trékollur.",
     "\"You clodpate,\" hló hún, \"you've had the map upside down the whole time.\"",
     "jarðklumpur", "höfuð"),
    ("Að setja á hreyfingu eða í verk; að hvetja.",
     "Að vera neistinn sem setur eitthvað á hreyfingu — hvort sem það er vél sem kviknar eða maður sem loksins bregst við hugmynd.",
     "Ótti við að missa samninginn actuated allt liðið í helgar yfirvinnu.",
     "gerð, akstur", "að reka, að gera"),
    ("Fjárdráttur fjármuna sem þér er treyst fyrir.",
     "Að stela hljóðlega peningum sem þér var treyst til að gæta — fjárdráttur í gamaldags kápu.",
     "Peculation gjaldkerans fór óséð í næstum áratug.",
     "einkaeign", "búfé, auður"),
    ("Hópur sem talinn er á jaðri virðulegs samfélags.",
     "Glæsilegur en skuggalegur félagslegur undirheimur — fólk sem lifir rétt utan reglna \"respectable\" samfélags.",
     "Skáldsagan fylgir söngkonu sem rataði um demi-monde kabarettanna á 2. áratugnum.",
     "hálfur", "heimur, samfélag"),
    ("Enn til; ekki útdauð eða eyðilagt.",
     "Enn hér í dag — notað um gamla hluti (handrit, tegundir, byggingar) sem hafa tekist að lifa af.",
     "Aðeins þrjú extant eintök af fyrstu prentuninni eru þekkt.",
     "út", "að standa"),
    ("Sviksemi; svik á trausti.",
     "Djúp, vísvitandi svik — að brjóta traust sem einhver átti rétt á að búast við að þú héldir.",
     "Hershöfðinginn fyrirgaf aldrei perfidy gamla vinar síns við samningaborðið.",
     "í gegnum, gegn", "trú, traust"),
    ("Svæðisbundið mállýska, sérstaklega ósamræmd.",
     "Sérstæða, staðbundna leiðin sem fólk talar á tilteknu svæði — full af orðum og takti sem utanaðkomandi gæti misst.",
     "Amma hennar talaði enn patois eyjarinnar við fjölskyldukvöldverði.",
     "gróft tal, mállýska", "lófi — klunnalegt tal"),
    ("Sérstakur réttur sem tilheyrir einstaklingi eða hópi.",
     "Forréttindi sem eru þín og aðeins þín — réttur sem fylgir hlutverki þínu, stöðu eða stöðu.",
     "Að velja fjölskyldufríið er prerogative afa, og allir vita það.",
     "á undan", "að spyrja, að kjósa"),
    ("Djarfleiki, áræðni; einnig harðfylgi eða þol.",
     "Hrjúf, hugdjörf mótstaða — taugarnar til að ýta áfram og harðfylgið til að halda áfram þegar þú byrjar.",
     "Það tók raunverulega hardihood að fara yfir skarðið í snjóstormi án korts.",
     "djarfur, harðnaður", "ástand, staða"),
    ("Að springa út í blóma; einnig að þróast eða birtast smám saman.",
     "Að opnast í fulla tjáningu — eins og blóm sem opnast, eða hugmynd sem loksins kemur til sín.",
     "Hljóðlát málunargáfa hennar effloresced þegar hún fékk eigið vinnustofu.",
     "út", "að byrja að blómstra"),
    ("Lóðstrengur til að ákvarða lóðrétt; myndrænt, mælikvarði á dómgreind.",
     "Þyngd á streng sem hangir alveg beint niður, notuð til að athuga hvort eitthvað sé sannarlega lóðrétt — og í víðari merkingu hvaða fasti mælikvarði sem þú mælir allt annað við.",
     "Hann notaði heiðarleika eigin afa sem eins konar plumb-line fyrir hverja ákvörðun.",
     "blý", "snæri, mál"),
    ("Gjarnan, viljugur (fornlegt).",
     "Gamaldags leið til að segja \"gladly\" eða \"with pleasure.\"",
     "\"I would fain rest here a while,\" andvarpaði ferðalangurinn.",
     "glaður, feginn", "gjarnan, viljugur"),
    ("Hörð opinber gagnrýni eða smán.",
     "Opinber skömm sem er hellt yfir einhvern á stóran, sýnilegan hátt — smánin sem kemur af víðtækri vanþóknun.",
     "Hneykslið bar opinbert opprobrium niður á allt fyrirtækið.",
     "gegn", "smán, ámæli"),
    ("Beitt sarkastískt, bitandi í viti eða gagnrýni.",
     "Vit með alvöru tennur — mordant athugasemd sviður aðeins einmitt vegna þess að hún er svo vel beint.",
     "Mordant kvikmyndagagnrýni hennar var óttast af leikstjórum og elskuð af lesendum.",
     "að bíta", "bitandi, gerandi"),
    ("Formleg yfirlýsing, oft pólitísk eða hernaðarleg.",
     "Stór, opinber tilkynning — venjulega ein sem lýsir yfir nýrri ríkisstjórn, uppreisn eða stóru tilskipun.",
     "Pronunciamento hershöfðingjans tilkynnti nýju ríkisstjórnina í dögun.",
     "fram", "að tilkynna"),
    ("Maður með yfirborðslega þekkingu sem þykist vera sérfræðingur.",
     "Einhver sem hefur skimað yfirborð efnis og talar svo eins og hann hafi skrifað kennslubókina um það.",
     "Sciolist kvöldverðarins leiðrétti sjálfsöruggt raunverulega stjarneðlisfræðinginn við borðið.",
     "að vita", "smækkun — lítill vitandi"),
    ("Hnignun andlegra hæfileika á elliárum.",
     "Þokaða, gleymska kafli hárra ævi þegar skerpa hugarins byrjar að dofna.",
     "Í dotage sagði hann sömu þrjár sögurnar í hverri heimsókn, í hvert sinn eins og þær væru nýjar.",
     "að dotta, að vera heimskur", "ástand eða niðurstaða"),
    ("Hliðin sem er varin fyrir vindi.",
     "Kyrrlát, varin hlið einhvers — hæðar, skips, veggjar — þar sem vindurinn nær þér ekki alveg.",
     "Göngumennirnir reistu tjaldið á lee-side hryggsins til að sleppa undan hviðunum.",
     "skjól, vernd", "hlið, flötur"),
    ("Að verjast eða slá frá höggi, spurningu eða rökum.",
     "Að slá einhverju mjúklega frá — sverðshögg, vandræðalegri spurningu eða ásökun — án þess að missa taktinn.",
     "Hún parried snjöllu spurningu blaðamannsins með léttum brandara.",
     "að verjast", "að undirbúa, að verja"),
    ("Illa lyktandi, skaðlegt.",
     "Fýlur á hátt sem finnst nánast eitrað — fýla svo slæm að það virðist hættulegt að anda.",
     "Mephitic lykt rak upp úr mýrinni þegar sólin settist.",
     "skaðleg gufa", "sem hefur eðli"),
    ("Maður sem er helgaður lúxus og nautn.",
     "Einhver sem lifir fyrir þægindi og nautn — fínan mat, mjúk rúm, auðvelt líf — nefndur eftir forngrísku borginni Sybaris, frægri fyrir ofgnótt.",
     "Sannur sybarite, hann neitaði öllum hótelherbergjum án baðkars.",
     "forngríska borgin fræg fyrir lúxus", "íbúi"),
    ("Að leggja vísvitandi hluta af einhverju til hliðar.",
     "Að setja púslhluta vísvitandi til hliðar svo þú getir einbeitt þér hreint að restinni.",
     "Prescind frá kostnaðinum augnablik og spyrjum bara hvort áætlunin virki raunverulega.",
     "á undan, í burtu", "að skera"),
    ("Að gagnrýna harðlega; einnig að rífa húð af.",
     "Að rífa einhvern í tætlur með harðri gagnrýni — í orðum, eins og þú værir bókstaflega að rífa húðina af.",
     "Gagnrýnendur excoriated framhaldið fyrir að svíkja allt sem aðdáendur elskuðu við frumverkið.",
     "af", "húð, skinn"),
    ("Að vitna sem sönnun eða rök.",
     "Að koma fram með staðreynd eða dæmi til að styðja punktinn þinn — það sem þú bendir á þegar einhver spyr \"what's your evidence?\"",
     "Lögmaðurinn adduced þrjá vitni til að styðja alibi skjólstæðingsins.",
     "að, til", "að leiða"),
    ("Ferðir eða flakkar, sérstaklega langar eða víðtækar.",
     "Langar, flakkandi ferðir — sú tegund víðtækrar flakks sem tekur þig langt að heiman um langan tíma.",
     "Peregrinations hans yfir þrjár heimsálfur fylltu heila hillu ferðadagbóka.",
     "í gegnum", "akur, land (peregrinus: útlendingur)"),
    ("Betlari, eða sá sem lifir á ölmusu.",
     "Einhver sem lifir á því að biðja um góðverk — sögulega lýsti þetta einnig munkum sem tóku fátæktarheit og lifðu á gjöfum.",
     "Mendicant bræðurnir áttu ekkert og treystu alveg á góðvild þorpsbúa.",
     "að betla", "betlari"),
    ("Afar örlátur.",
     "Örlátur á stórum, nánast sýnilegum skala — sú tegund gjafar sem lætur fólk anda aðeins að sér.",
     "Munificent gjöfin fjármagnaði alla nýju álmuna á bókasafninu.",
     "gjöf, þjónusta", "gerandi, gefandi"),
    ("Örmögnun vegna skorts á næringu; einnig skortur á lífsþrótti.",
     "Veikt, tómt ástand af því að hafa ekki verið fóðrað eða eldsneyti — bókstaflega af hungri, eða myndrænt af því að eiga ekkert eftir að keyra á.",
     "Í lok umsátrinu voru hermennirnir nálægt inanition.",
     "tómt, tómarúm", "athöfn eða niðurstaða"),
    ("Beisk, móðgandi gagnrýni.",
     "Gagnrýni sem er löngu komin framhjá sanngjörnu og orðin reið, beisk úthelling.",
     "Netathugasemdirnar leystust upp í hreina vituperation á mínútum.",
     "sök", "að undirbúa, að útvega"),
    ("Fjandsamlegt, skaðlegt í áhrifum.",
     "Vinnur gegn þér, jafnvel hljóðlega — aðstæður eða viðhorf sem eru óvingjarnleg hagsmunum þínum.",
     "Nýja stefnan var inimical fyrir lítil fyrirtæki, jafnvel þótt það hafi ekki verið ætlunin.",
     "ekki", "vinur"),
    ("Líklegt til að vekja gremju eða óánægju, oft með ósanngjörnum samanburði.",
     "Dæmt til að láta einhvern finnast hunsaður — venjulega vegna þess að það setur fólk eða hluti ósanngjarnt gegn hvert öðru.",
     "Að raða systkinum eftir \"who Mom loves best\" er invidious leikur sem enginn ætti að spila.",
     "öfund", "að horfa á (með illvilja)"),
    ("Maður af lægri stöðu; undirmaður.",
     "Einhver neðar í skipanakæðju eða félagsstiga — yngri, sem vinnur undir einhverjum með meira vald.",
     "Sem ungur subaltern tók hann skipanir lengi áður en hann gaf þær nokkurn tímann.",
     "undir", "til skiptis, annar"),
    ("Að finna eða tjá sterkt hatur á.",
     "Að fyrirlíta eitthvað svo mikið að þú bölvar því upphátt — hreint, hávært hatur.",
     "Þorpsbúarnir execrated skattheimtumanninn í hvert sinn sem vagn hans rúllaði í gegnum bæinn.",
     "út úr", "heilagt (að bölva út úr hinu helga)"),
    ("Náttúrulegt ytra hulstur, eins og húð eða skel.",
     "Eigið verndarhylki náttúrunnar — húð, skel, belgur eða hýði, hvað sem þekur og verndar lifandi.",
     "Skel skjaldböku er merkilega hörð integument.",
     "á, yfir", "að hylja"),
    ("Saklaus, naív, sem sýnir barnlega einfaldleika; andstæða \"disingenuous.\"",
     "Opið traustur og svolítið naívur, án falinnar dagskrár — auðvelt að rugla saman við \"ingenious,\" sem þýðir snjall.",
     "Ingenuous spurning hennar — \"why would anyone lie about that?\" — sýndi hversu litla slægð hún hafði.",
     "í, innfæddur", "að geta (frjálsborinn, einlægur)"),
    ("Ofuráhyggja um smáatriði eða reglur.",
     "Að villast í smáreglunum og missa stærri myndina — að festast í smáprentinu sem enginn annar nennir.",
     "Pedantry hans um Oxford-kommur fór með allan fundinn af sporinu.",
     "kennari barna", "venja eða eiginleiki"),
    ("Ítarleg, vandleik rannsókn.",
     "Djúp, enginn-steinn-ósnertur skoðun á einhverju — að fara yfir hvert smáatriði með raunverulegri umhyggju.",
     "Aðeins eftir vandlega perscrutation bókhaldsins kom misræmið í ljós.",
     "í gegnum, rækilega", "að leita, að rannsaka"),
    ("Að bera fram andmæli; að sýna tregðu.",
     "Að bakka kurteislega eða hika frekar en að hoppa strax með — mjúkt \"I'd rather not.\"",
     "Þegar hún var beðin um að skrifa undir án þess að lesa, demurred hún.",
     "frá, í burtu", "að tefja"),
    ("Yfirborðslega trúverðugt en í raun rangt.",
     "Hljómar sannfærandi í fyrstu en fellur í sundur um leið og þú athugar það raunverulega.",
     "\"Everyone's doing it\" er specious rök sem standast aldrei skoðun.",
     "útlit, svipur", "fullt af (að því er virðist fagurt)"),
    ("Óeinlægt, hræsnið tal, oft siðpræðandi.",
     "Predikandi tal sem hljómar dyggðugt en er ekki stutt af neinni raunverulegri tilfinningu — siðferðileg uppstilling á sjálfstýringu.",
     "Hann var þreyttur á fyrirtækis-cant um \"family\" frá fyrirtæki sem gaf aldrei frí.",
     "að syngja (síðar: söngkennd slangur)", "kveinandi tal betlara, síðan hræsni"),
    ("Án hugrekkis, huglaus.",
     "Hræddur til hrygglleysis — of hræddur til að standa jafnvel þegar það skiptir augljóslega máli.",
     "Pusillanimous þögn stjórnarinnar lét hneykslið snúast úr böndunum.",
     "mjög lítill", "andi, hugrekki"),
    ("Reflegt; slóttugt, kænt.",
     "Slóttugt og snjallt eins og refur — skjóthugsað, svolítið laumulegt, alltaf skrefi á undan.",
     "Hann gaf vulpine bros um leið og hann sá gatið.",
     "refur", "af eða eins og"),
    ("Einn á fætur öðrum, í röð.",
     "Tekin strangt einn í einu, í röð — ekkert hopp áfram, ekkert tvennt í einu.",
     "Dómarinn fjallaði um hvert af tólf kröfunum seriatim.",
     "röð, röð", "einn í einu"),
    ("Öfgafull sparsemi; nískur.",
     "Að vera nískur með peninga (eða orð, eða auðlindir) langt framhjá sanngjarnri sparsemi.",
     "Parsimony hans var goðsagnakennd — hann endurnýtti tepoka þrisvar.",
     "að spara, að vera sparsamur", "ástand eða venja"),
    ("Leiðrétting, sérstaklega í texta.",
     "Viðgerð á ritverki — fræðileg aðlögun sem leiðréttir villu í gömlum eða mikilvægum texta.",
     "Nýja útgáfan inniheldur tugi emendations á upprunalega handritinu.",
     "út úr", "villa, mistök"),
    ("Hófsamur í mat og drykk.",
     "Vísvitandi hófsamur um mat og drykk — aldrei of mikið, alltaf skilið eftir smá á disknum.",
     "Abstemious venjur hans héldu honum skörpum löngu eftir að jafnaldrar hans höfðu hægðist.",
     "í burtu frá", "vímuvaldandi drykkur"),
    ("Málfræðileg villa eða brot á siðareglum.",
     "Hras í málfræði eða siðum — sú tegund lítillar villu sem lætur nákvæman hrökkva.",
     "\"Between you and I\" er algeng solecism sem lætur málfræðinga enn hrökkva.",
     "Kilíkísk borg þekkt fyrir 'slæma' grísku", "siður, háttur"),
    ("Varðar átök innan hóps; gagnkvæmt eyðileggjandi.",
     "Innri deilur sem rífa hóp í sundur innan frá — barátta þar sem allir tapa, því það er fjölskylda gegn fjölskyldu.",
     "Internecine þras flokksins olli meiri skaða en nokkur ytri andstæðingur hefði getað.",
     "milli, meðal", "að drepa"),
    ("Áhugalaus, kærulaus afstaða.",
     "Öxlalyfting gerð að heilli persónu — að vera svo sama um hluti sem áður skiptu máli að ekkert virðist þess virði lengur.",
     "Pococurante afstaða hans til verðlaunahátíðarinnar kom öllum á óvart sem vissu hversu hart hann hafði unnið.",
     "lítið", "að vera sama"),
    ("Ruglingsleg, flókin staða eða deila.",
     "Flækt, sóðaleg staða sem er erfið að ná utan um — að hluta misskilningur, að hluta drama, allt rugl.",
     "Allt sætaskipulags-imbroglio byrjaði á einu rangt staðsettu nafnspjaldi.",
     "í", "að flækja, að rugla"),
    ("Ógnandi, hótandi.",
     "Ber ótvíræðan ógnaranda — minatory svipur eða bréf gerir það mjög ljóst að eitthvað slæmt getur fylgt.",
     "Minatory tónn bréfsins gerði leigjandann taugaveiklaðan áður en hún opnaði umslagið.",
     "að hóta", "sem þjónar"),
    ("Sterk opinber gagnrýni eða munnleg misnotkun.",
     "Hávær, opinber fordæming — sú tegund sviðandi gagnrýni sem fer fram fyrir framan alla.",
     "Uppljóstrarinn stóð frammi fyrir árum opinbers obloquy áður en sagan gaf henni rétt.",
     "gegn", "að tala"),
    ("Skyndileg ofbeldisfull úthelling, tilfinningar eða athafnar.",
     "Skyndilegt, ákaflegt högg sem yfirgnæfir þig í einu — hláturskast, reiði eða hósti sem slær eins og bylgja.",
     "Hana greip paroxysm hlátrs sem hún gat ekki útskýrt fyrir neinum öðrum í herberginu.",
     "handan", "beitt, brátt"),
    ("Bætt við frá ytri uppsprettu, ekki innbyggt.",
     "Skrúfað á utan frá í stað þess að vera innbyggt frá upphafi — auka, ekki kjarnahluti.",
     "Athugasemdin finnst adscititious, eins og hún hafi verið límd á þegar fulluninn texta.",
     "að, auk þess", "að samþykkja, að taka"),
    ("Skortur á þekkingu, vanþekking.",
     "Einfalt ekki-vita — gat í þekkingu, án nokkurs dóms fest við það.",
     "Hann játaði nescience sína um franskt vín og lét sommelierinn velja.",
     "ekki", "að vita"),
    ("Of mikill áhugi á kynferðislegum málum.",
     "Ofágjarn, starandi forvitni um allt kryddað — áhugi sem er kominn framhjá heilbrigðu í nálægt.",
     "Prurience tabloidsins um einkalíf parsins nálgaðist þráhyggju.",
     "að klæja, að þrá", "ástand"),
    ("Sótað, dimmt, myrkt.",
     "Dökkt og reykennd útlit, eins og allt sé þakið þunnu lagi af sóti.",
     "Fuliginous þoka hékk yfir verksmiðjubænum í rökkri.",
     "sót", "fullt af"),
    ("Að neita eða mótmæla.",
     "Að tala beint gegn því sem annar sagði — að segja \"that's not so.\"",
     "Enginn þorði að gainsay frásögn gamla skipstjórans af storminum.",
     "gegn", "að tala"),
    ("Leti, sljóleiki (úr latínu).",
     "Gamalt latneskt orð yfir hreina leti — slóðin við að vilja ekkert gera.",
     "Munkarnir prédikuðu gegn ignavia sem einni af hljóðlátu hættum sálarinnar.",
     "ekki", "upptekinn, iðinn"),
    ("Skjöldur sem sýnir skjaldarmerki.",
     "Skjaldarlaga merki sem sýnir skjaldarmerki fjölskyldu — heraldiska \"nameplate\" hennar.",
     "Escutcheon fjölskyldunnar hangir enn yfir fordyri gamla höfuðbólsins.",
     "skjöldur", "smækkun / hlutur"),
    ("Úrelt, úrelt, eða hætt vegna aldurs.",
     "Framhjá nytsamlegu hámarki og sett á beit — of gamaldags eða slitið til að halda starfinu áfram.",
     "Superannuated prentarinn var loks skipt út eftir fimmtán ár af pappírsstoppum.",
     "handan", "ár"),
    ("Staðgenglar, sérstaklega í læknisfræði.",
     "Staðgengilslyf notuð þegar raunveruleg meðferð er ekki tiltæk — læknisfræðilegir staðgenglar í raun.",
     "Stríðstíðar læknar treystu oft á succedanea þegar réttu lyfin kláruðust.",
     "í staðinn fyrir", "að fara, að víkja"),
    ("Hróðuglegt, blásandi tal.",
     "Stórt, blásandi hróðugleiki — hátt tal um eigin stærð sem er að mestu heitt loft.",
     "Rodomontade hans um að hafa \"single-handedly\" bjargað verkefninu plataði engan sem raunverulega var þar.",
     "hróðuglegur riddari í Orlando Furioso", "athöfn, sýning"),
    ("Að nota kænsku eða svik til að ná einhverju.",
     "Að slíta sig að marki með laumulegum brögðum fremur en sanngjörnum leik.",
     "Hann chicaned sig inn í samninginn með samningi fullum af smáprentun.",
     "að þrasa, að plata", "bragð; síðar beygja"),
    ("Hrein eða abstrakt vísindi náms eða þekkingar, oft stærðfræði.",
     "Nám í hreinustu, abstraktustu mynd — djúp bygging þekkingarinnar sjálfrar, sérstaklega stærðfræðilega tegundin.",
     "Heimspekingurinn dreymdi um alhliða mathesis sem gæti sameinað hvert þekkingarsvið.",
     "að læra", "athöfn þess að læra"),
    ("Of upptekinn af formlegum reglum eða smávægilegum smáatriðum.",
     "Of strangur um smámuni — leiðréttir smá tæknileg atriði sem breyta í raun engu.",
     "Það fannst svolítið pedantic að deila um \"who\" versus \"whom\" í textaskilaboðum.",
     "barnalleiðbeinandi, leiðbeinandi", "sem hefur hátt"),
    ("Blikkandi, glitrandi ljós.",
     "Fljótt, glitrandi ljósglampi — hugsaðu sólarljós sem skoppar af vatni, eða demant sem grípur ljósið.",
     "Coruscation ljósakrónunnar dreifði ljósi um hvert horn danssalarins.",
     "að glitra, að blikka", "athöfn"),
    ("Byrjandi, nýliði.",
     "Einhver alveg nýr í færni eða sviði — enn að læra grunninn, ekki enn sérfræðingur.",
     "Jafnvel tyro skákmaður getur séð þessa klaufaskap.",
     "nýliði, nýliði", "hrár ungur hermenn"),
    ("Afar slæmt, viðbjóðslegt.",
     "Slæmt á hátt sem á skilið raunverulegan viðbjóð — ekki bara \"mediocre,\" heldur virkilega viðbjóðslegt.",
     "Gagnrýnandinn kallaði framhaldið execrable, og miðasölutölurnar voru sammála.",
     "að bölva", "verðugt, fært um að vera"),
    ("Blóðrautt að lit.",
     "Djúpt, lifandi rautt — litur fersks blóðs, frægt notað af Macbeth Shakespeare.",
     "Sólsetrið sneri öllum himninum í incarnadine ljóma.",
     "inn í", "hold (hold-rautt)"),
    ("Lítið bil eða rými milli hluta.",
     "Litla bilið sem er auðvelt að líta framhjá — sprungan milli gólfborða, gatið í stundatöflu.",
     "Illgresi ýtti sér upp um hvert interstice í gamla múrsteinsstígnum.",
     "milli", "að standa"),
    ("Gagnrýnar eða ámælandi athugasemdir.",
     "Beittar, vanþóknandi athugasemdir — sú tegund gagnrýni sem ber svolítið skammartón.",
     "Animadversions prófessorsins á ritgerðinni fylltu spássíurnar með rauðu bleki.",
     "hugur", "að snúa að"),
    ("Ómögulegt að hrekja, óumdeilanlegt.",
     "Svo traustlega sannað að það er ekki hægt að deila um það — málið er einfaldlega lokað.",
     "DNA-sönnunin var irrefragable og réttarhöldin voru búin innan klukkustundar.",
     "ekki", "að standa gegn, að mótast"),
    ("Flækja, flækjustig; einnig innvafning.",
     "Flækt, innvafin flækja — hlutir vafðir svo þétt að erfitt er að draga þá í sundur.",
     "Involution söguþráðarins skildi helming áhorfenda eftir að reyna að ráða hann eftir lokaúttekt.",
     "inn, innávið", "að rúlla, að snúa"),
    ("Kraftur eða átak, eins og \"by dint of.\"",
     "Hreint átak eða kraftur — lifir í dag að mestu í orðasambandinu \"by dint of.\"",
     "Hann stóðst prófið by dint of hreinu, þrjósku æfingunni.",
     "högg, sláttur", "með krafti"),
    ("Tengt með tappi; þétt saman sett.",
     "Læst saman á gamaldags smíðahátt — stykki sem rennur þétt inn í gat skorið einmitt fyrir það.",
     "Bitarnir í gamla hlöðunni voru mortised saman án einnar nagla.",
     "hol, gat", "bit, grip"),
    ("Mjög viðeigandi, hæfilegt.",
     "Nákvæmlega rétt fyrir augnablikið — athugasemd, tilvitnun eða dæmi sem lendir fullkomlega á punktinum.",
     "Apposite athugasemd hennar tók alla umræðuna saman í einni setningu.",
     "að", "að koma fyrir"),
    ("Mjúkt glóandi eða flöktandi (ljós); einnig létt vit.",
     "Glóandi mjúkt fremur en logandi — mjúkt, flöktandi ljós, eða vit sem er leikandi fremur en beitt.",
     "Kertaljós kastaði lambent ljóma yfir gamla matsalinn.",
     "að sleikja", "gerandi (ljós sem 'sleikir')"),
    ("Trúarlegur einsetumaður sem lifir í einveru.",
     "Einhver sem dregur sig algjörlega frá heiminum til að lifa einn í bæn og íhugun.",
     "Anchorite bjó í lítilli klefu við kirkjuna í yfir þrjátíu ár.",
     "til baka, í burtu", "að draga sig í hlé"),
    ("Að slökkva þorsta; að slökkva.",
     "Að fullnægja löngun algjörlega — oftast þorsta, en myndrænt hvaða djúpa þörf sem er.",
     "Eitt kalt glas af vatni slaked þorsta hans eftir löngu göngunni.",
     "slakur, laus", "að slaka, að slökkva"),
    ("Nálalaga.",
     "Langt, mjótt og oddhvasst eins og nál — lögun furunálar eða hvassrar lítillar kristals.",
     "Furutré er auðvelt að þekkja á acicular laufum sínum.",
     "nál", "lítið"),
    ("Útþrota af lífsþrótti, veikt, ofurhreinsað.",
     "Slitið og mjúkt — hefur tapað upprunalegum styrk eða þrótti vegna of mikilla þæginda eða hreinsunar.",
     "Gagnrýnendur kölluðu hið eina djarfa tímarit effete, skugga af djarfa fyrstu árum sínum.",
     "út", "ávöxtursælt, sem hefur borið"),
    ("Aukahlutur eða minni tengdur hlutur eða réttur.",
     "Lítið auka sem fylgir einhverju stærra — aukahlutir og viðhengi sem tilheyra aðalatriðinu.",
     "Leigusamningurinn náði yfir bílskúrinn og öll appurtenances hans.",
     "að", "að tilheyra"),
    ("Að slétta yfir eða minnka sök.",
     "Að slétta yfir mistök með mjúkum orðum, svo þau hljómi minni en þau raunverulega eru.",
     "Hann reyndi að gloze yfir misstu frestinn með óljósu tali um \"unforeseen challenges.\"",
     "glosa, skýring", "að athugasemda — síðan að slétta yfir"),
    ("Á snemmbúnu stigi, nýbyrjað.",
     "Nýbyrjað að sýna sig — allra fyrsta, varla sýnilega stig einhvers stærra sem kemur.",
     "Læknar náðu incipient einkennum sjúkdómsins áður en hann gat dreifst.",
     "á, inn í", "að taka (að taka upp, að byrja)"),
    ("Skapandi innblástur, sérstaklega guðlegur.",
     "Skyndileg innblástursbylgja sem finnst stærri en þú — eins og hugmyndin hafi verið andað inn í þig annars staðar frá.",
     "Skáldið lýsti því hvernig allt verkið kom í einu afflatus höggi klukkan þrjú að nóttu.",
     "að, á", "að blása (áblástur)"),
]
