# Albanian rows
ROWS = [
    ("Të ëmbëlosh ose të pastrosh; të heqësh ashpërsinë nga diçka.",
     "Të heqësh thumbin ose hidhësinë — fjalë për fjalë duke e ëmbëlsuar, ose figurativisht duke zbutur një ide të ashpër që të shkojë më lehtë.",
     "Redaktori zbuti recensionin e ashpër para se të shkonte në shtyp.",
     "jashtë, tërësisht", "i ëmbël"),
    ("Tejet ose me prekje fetar ose i devotshëm.",
     "Përshkruan dikë, përkushtimi fetar i të cilit duket i vënë për shfaqje — më shumë spektakël se besim i vërtetë.",
     "Psherëtimat e tij pietiste gjatë predikimit bezdisën pjesën tjetër të stolës.",
     "devotshmëri, ndjenjë detyre", "që ka karakterin e"),
    ("Paqartësi që lind nga struktura gramatikore — fjali që lexohet në dy mënyra.",
     "Fjali që është gramatikisht në rregull, por mund të lexohet në dy mënyra krejt të ndryshme, si \"I saw the man with the telescope.\"",
     "\"Visiting relatives can be tiring\" është një amfiboli klasike — a janë të lodhshëm të afërmit, apo është lodhëse t'i vizitosh?",
     "të dyja, nga të dyja anët", "të hedhësh"),
    ("I mprehtë, i prerë, që pret drejt në thelb.",
     "Pret drejt përmes fjalëve të kota — një vërejtje ose mendje therëse arrin shpejt te zemra e çështjes, pa fjalë të tepërta.",
     "Kritika e saj therëse nuk la vend që boshllëqet e filmit të fshiheshin.",
     "të presësh", "që bën, që ka cilësinë"),
    ("Sapo ka filluar; në fazë të hershme ose fillestare.",
     "Ende në çastet e hapjes — një plan, ndjenjë ose proces që sapo ka filluar të marrë formë.",
     "Fazat fillestare të traktatit ishin premtuese, por shumë hollësi mbetën të pazgjidhura.",
     "të fillosh, të nisesh", "që priret drejt"),
    ("Fjalim ose shkrim formal që lëvdon dikë lart.",
     "Një lavdërim i plotë, formal — mendo një fjalim funerali të ndritshëm ose një fjalim që këndon arritjet e dikujt nga çatitë.",
     "Profesoresha që po dilte në pension u përcoll me një panegjirik nga studentët e saj më të afërt.",
     "të gjitha", "kuvend, mbledhje"),
    ("Që lidhet me ekzistencën e vërtetë ose qenien faktike, në kundërshtim me teorinë abstrakte.",
     "Për gjërat ashtu siç ekzistojnë vërtet, jo vetëm si ide apo teori rreth tyre.",
     "Filozofët debatojnë nëse numrat kanë ndonjë status ontik apo ekzistojnë vetëm në mendjet tona.",
     "qenie, ajo që është", "që lidhet me"),
    ("Të japësh fryt, ose të bëhesh produktiv.",
     "Të japë fryt më në fund — një përpjekje, ide ose investim që jep fryt është rritur nga fara në diçka të dobishme.",
     "Vitet e kërkimit të qetë më në fund dhanë fryt: një vaksinë që funksiononte.",
     "frut", "të bësh, të shkaktoosh"),
    ("Që parashikon ose paraqet diçka si të kryer para se të ketë ndodhur vërtet.",
     "Të nxitosh në mënyrë letrare — të përshkruash një ngjarje të ardhshme sikur tashmë ka mbaruar, që pika të bjerë më fort.",
     "Tosti paraprak i gjeneralit për \"fitoren\" u mbajt një javë të tërë para betejës.",
     "para", "të marrësh, të kapësh"),
    ("I vepruar nga presioni i ajrit; gjithashtu i lidhur me shpirtin ose frymën.",
     "Zakonisht do të thotë \"i fuqizuar nga ajri i kompresuar\" — megjithëse mund të nënkuptojë edhe lidhjen me shpirtin ose frymën.",
     "Frenat pneumatike fëshfëritën kur autobusi u ndal te trotuari.",
     "erë, frymë, shpirt", "që i përket"),
    ("Që përshkruan Zotin ose hyjnoren me pohime pozitive — e kundërta e apofatikes.",
     "Një mënyrë për të folur për Zotin duke thënë se çfarë është Zoti — \"God is love\" — e jo vetëm se çfarë nuk është.",
     "Teologjia katafatike flet me besim për Zotin si dashamirës, i drejtë dhe i mëshirshëm.",
     "poshtë, sipas", "të flasësh, të thuash"),
    ("I bazuar në besim ose besnikëri; gjithashtu pikë e fiksuar referimi.",
     "Diçka që e merr me besim dhe pastaj e përdor si spirancë — një shenjë referimi është pika e fiksuar kundrejt së cilës matet gjithçka tjetër.",
     "Matësit vendosën një shënues referimi në shkëmb para se të hartonin vendin.",
     "të besosh", "besim, siguri"),
    ("Mbrojtje e mirësisë së Zotit duke pasur parasysh ekzistencën e së keqes.",
     "Përpjekja e lashtë për t'iu përgjigjur: \"If God is good, why does evil exist?\"",
     "Teza e saj eksploroi teodicenë përmes lenteve të Librit të Jobit.",
     "zot", "drejtësi"),
    ("Banim i ndërsjellë — term teologjik për mënyrën se si personat e Trinisë ekzistojnë brenda njëri-tjetrit.",
     "Fjalë teologjie për një bashkësi tre-në-një kaq të plotë sa çdo pjesë përmban dhe përmbahet plotësisht nga të tjerat.",
     "Doktrina e perikorezës përpiqet të shpjegojë se si Ati, Biri dhe Shpirti janë të dallueshëm, por të pandashëm.",
     "përqark", "të shkosh, të ecësh"),
    ("Të kesh pasojë që i sjell dobi ose i kthehet dikujt.",
     "Kur lavdërimi (ose faji) kthehet te personi përgjegjës — veprat e mira që i shkojnë në nder reputacionit tënd kthehen për të të shpërblyer.",
     "Suksesi i ekipit do të shkojë në nder të trajnerit të tij të qetë e punëtor.",
     "mbrapa, përsëri", "valë"),
    ("I pashmangshëm; që nuk mund t'i shpëtosh.",
     "Do të ndodhë, çfarëdo që të bësh — nuk ka ku të shkëputesh nga një përfundim i pashmangshëm.",
     "Pleqëria vjen për të gjithë; është thjesht e pashmangshme.",
     "jo", "të luftosh për t'u shkëputur"),
    ("Që përdor shprehje të tërthorta, me shumë fjalë, në vend të formës së drejtpërdrejtë.",
     "Të shkosh rrugën e gjatë me fjalë — të thuash \"make a decision\" në vend të \"decide.\"",
     "Email-et e tij të stërzgjatura mund të kishin thënë në një rresht atë që i mori tre paragrafë.",
     "përqark", "të shpallësh, të tregosh"),
    ("Mpirje mendore ose letargji.",
     "Ajo gjendje e mjegullt, e ngadaltë e mendjes ku të menduarit ndihet si ecje nëpër shurup.",
     "Një valë topitjeje e goditi klasën menjëherë pas drekës.",
     "i shurdhër, i mpirë", "gjendje ose cilësi"),
    ("I pafavorshëm; shenjë e keqe.",
     "Shenjë e keqe — kushte ose kohë që duket se punojnë kundër teje para se të kesh filluar fare.",
     "Qielli gri dhe bateria e shkarkuar e makinës bënë një fillim të pafat për udhëtimin.",
     "jo", "i favorshëm, i hirshëm"),
    ("Mish i zier ngadalë në salcë — shkruhet saktë \"fricasseed.\"",
     "Term i vjetër, i ngrohtë gatimi për mishin e prerë dhe të zier ngadalë në salcën e vet derisa të bëhet i butë.",
     "Pula frikase e gjyshes ishte ylli i çdo darke të dielë.",
     "të skuqësh", "të thërmosh (në copa)"),
    ("Zëvendësues artificial ose i dobët.",
     "Një kopje që zë vendin e së vërtetës — teknikisht e bën punën, por të gjithë e shohin se nuk është origjinali.",
     "Blerësit e kohës së luftës u kënaqën me kafe zëvendësuese nga çikore e pjekur.",
     "jashtë, parashtesë zëvendësimi", "të vësh, të vendosësh"),
    ("Të trajtosh një ide abstrakte sikur të ishte gjë konkrete.",
     "Të bësh që një ide të ndihet e vërtetë dhe e ngurtë — ta kthesh diçka të mjegullt, si \"the economy,\" në një gjë që mund ta tregosh me gisht.",
     "Ta quash \"shpirtin\" e një kombi qenie më vete do të thotë ta sendërtosh diçka që në të vërtetë është miliona zgjedhje individuale.",
     "gjë", "të bësh"),
    ("I shpëtoi ose iu shmang me mjeshtëri.",
     "Iu shkëput pastër — iu shmang diçkaje, shpesh me zgjuarsi ose ngushtë, qoftë kapja, një pyetje, apo një përgjigje.",
     "Përgjigja i shpëtoi për orë të tëra derisa papritmas i klikoi në dush.",
     "jashtë, larg", "të luash"),
    ("Që shpreh dyshim, hutim ose një kundërthënie të pazgjidhur.",
     "I bllokuar në një rrugë të vërtetë pa krye të mendimit — jo nga përtacia, por sepse vetë pyetja i reziston një përgjigjeje të pastër.",
     "Sokrati shpesh i mbyllte dialogët me një notë aporetike, me më shumë pyetje se përgjigje.",
     "pa", "kalim, rrugë"),
    ("Figurë e të folurit që emërton diçka me një term të lidhur, p.sh. \"the crown\" për monarkun.",
     "Të përdorësh një fjalë të lidhur në vend të së vërtetës — të thuash \"the White House announced\" kur ke parasysh administratën.",
     "\"Wall Street had a rough day\" është metonimi — në të vërtetë do të thotë se tregu i aksioneve pati një ditë të vështirë.",
     "ndryshim, pas", "emër"),
    ("Të shkulësh nga rrënjët; të shqitësh nga mjedisi natyror.",
     "Të nxjerrësh diçka (ose dikë) me rrënjë, larg vendit ose kulturës ku i përket.",
     "Lufta shkuli me rrënjë një brez të tërë, duke shpërndarë familjet përtej kufijve.",
     "larg, poshtë", "rrënjë"),
    ("Me tingull të këndshëm.",
     "Thjesht e këndshme për t'u dëgjuar — një fjalë, emër ose fjali eufonike rrëshqet në vesh pa pengesë, pothuajse muzikalisht.",
     "\"Murmuring brook\" është një frazë e vogël eufonike — e butë dhe e lehtë për t'u thënë.",
     "i mirë, mirë", "tingull, zë"),
    ("I supozuar ose i marrë përgjithësisht si i tillë.",
     "I besuar gjerësisht si i vërtetë, edhe nëse nuk është vërtetuar — versione \"e supozuar\" e diçkaje.",
     "Autori i supozuar i letrës më vonë doli të ishte një i huaj i plotë.",
     "të mendosh, të gjykosh", "që ka natyrën e"),
    ("Fjalë ose frazë e sapo krijuar.",
     "Një fjalë krejt e re — sapo e shpikur, ende (ose gati) jo në fjalor.",
     "\"Doomscrolling\" nisi si neologjizëm dhe shpejt u bë slang i përditshëm.",
     "i ri", "fjalë, ligjëratë"),
    ("I zemëruar ose me temperament të keq.",
     "Në humor të keq, të acaruar — i shpejtë për t'u ndezur, siç besohej dikur se shpretka kontrollonte temperamentin.",
     "Ai dërgoi një përgjigje vrerosëse të email-it brenda sekondave pasi e lexoi.",
     "shpretkë (vendi i zemërimit)", "i prekur nga"),
    ("I prirur të moralizojë në mënyrë pompoze ose të prekur.",
     "I pëlqen të japë mësime të vogla jete me rëndësi të tepruar, sikur çdo fjali të ishte biskotë fati.",
     "Tosti i tij moralizues për \"kuptimin e vërtetë të miqësisë\" i bëri të gjithë të shikonin orët.",
     "mendim, maksimë", "i mbushur me"),
    ("Tejet bisedues, veçanërisht për gjëra të vogla.",
     "Thjesht nuk ndalet së foluri — llafazan për gjëra të vogla shumë pasi të tjerëve u kanë mbaruar fjalët.",
     "Shoferi llafazan i taksisë na tregoi gjithë historinë e jetës së tij para se të dilnim nga aeroporti.",
     "të llafazanësh, të pëshpëritësh", "i prirur drejt"),
    ("Marrëzi, budallallëk.",
     "Marrëzi e thjeshtë — një vërejtje ose plan kaq budalla sa mezi meriton përgjigje serioze.",
     "Marrëzia e pastër e planit u bë e qartë në çastin që e provuan.",
     "i marrë, budalla", "gjendja e të qenit"),
    ("Pjesa përmbyllëse e një fjalimi, shpesh përmbledhëse.",
     "Mbarimi i madh i një fjalimi — seksioni mbyllës ku folësi i lidh të gjitha dhe e çon pikën në shtëpi.",
     "Deri te fjala e mbylljes, gjysma e publikut ishte në këmbë.",
     "përmes, deri në fund", "të flasësh, të mbrosh"),
    ("Përsëritje e panevojshme e së njëjtës ide me fjalë të ndryshme.",
     "Të thuash të njëjtën gjë dy herë pa shtuar asgjë të re, si \"free gift\" ose \"end result.\"",
     "\"It is what it is\" është tautologjia e preferuar e njerëzve që i shmangen një shpjegimi të vërtetë.",
     "i njëjti", "fjalë, ligjëratë"),
    ("Përdorimi i shumë pak fjalëve; fjalim i shkurtër.",
     "Të thuash shumë me shumë pak — arti i përgjigjes së shkurtër e të prerë, emërtuar nga spartanët famëkeq të shkurtër të Lakonisë.",
     "\"Molon labe\" — \"ejani e merrini\" — është copa më e famshme e lakonizmit në histori.",
     "një spartan i Lakonisë", "praktikë, mënyrë"),
    ("Ide të zbehta, të thjeshtuara tepër; fillimisht, ushqim i zbehtë ose qull.",
     "Mendim i hollë, i holluar — përmbajtje kaq e thjeshtuar e e sigurt sa nuk ka asnjë vlerë ushqyese për mendjen.",
     "Fjalimi i politikanit ishte kryesisht llafe boshe: premtime të mjegullta që nuk mund t'i kapje.",
     "të ushqesh", "mjet ose instrument"),
    ("Që shkakton gjumë ose përgjumje.",
     "Ka aq e mërzitshme — ose fjalë për fjalë qetësuese — sa të bën të flesh. Mendo qumështin e ngrohtë, ose një mbledhje buxheti treorëshe.",
     "Zhurma gjumëndjellëse e leksionit e kishte gjysmën e sallës duke luftuar për t'i mbajtur sytë hapur.",
     "gjumë i thellë", "që bën, që shkakton"),
    ("Tejet lajkatar ose i yndyrshëm në sjellje.",
     "Ka aq i butë e tërheqës sa ndihet i rrëshqitshëm — lajka e vënë kaq trashë sa pothuajse e ndjen yndyrën.",
     "Shitësi lajkatar vazhdonte të lavdëronte \"shijen time të shkëlqyer\" para çdo shitjeje shtesë.",
     "të vajosësh, të vajisësh", "i mbushur me"),
    ("I shpejtë për të gjetur faj, tepër kritik ndaj gjërave të vogla.",
     "I imët deri në gabim — lloji i personit që gjen problem në gjithçka, edhe kur nuk ka rëndësi vërtet.",
     "Shënimet e tij cikërrimtare mbi raportin u përqendruan tërësisht te vendosja e presjeve.",
     "të kapësh, të marrësh", "grackë, sofizëm"),
    ("I ngadalshëm, mendërisht ose fizikisht joaktiv.",
     "I ngadalshëm e gjysmë i fjetur, si ari në dimërim — mezi lëviz, mezi mendon.",
     "Zyra ra në plogështi në nxehtësinë e rëndë të gushtit.",
     "të jesh i mpirë, i ngadalshëm", "në gjendje të"),
    ("Kujdestar ose nëpunës që menaxhonte një shtëpi mesjetare.",
     "Versioni mesjetar i shefit të stafit — nëpunësi i besuar që drejtonte shtëpinë dhe pasurinë e zotërisë nga dita në ditë.",
     "Kujdestari i kështjellës menaxhonte gjithçka, nga llogaritë e korrjes deri te lista e të ftuarve.",
     "i vjetër, i moshuar", "shërbëtor"),
    ("Të flasësh ose të shkruash gjatë për një temë.",
     "Të nisesh vërtet në një temë — të flasësh ose të shkruash e të shkruash, duke e mbuluar nga çdo kënd.",
     "Pyete për makinat e vjetra dhe ai do të zgjatet për një orë të tërë.",
     "jashtë", "hapësirë"),
    ("Pa vlerë, i parëndësishëm; gjithashtu i pavlefshëm ose i paefektshëm.",
     "I vlefshëm praktikisht për asgjë — një klauzolë e pavlefshme në një kontratë është ajo që në të vërtetë nuk bën asgjë.",
     "Gjykata e shpalli rregulloren e vjetër të pavlefshme, sepse kurrë nuk ishte zbatuar vërtet.",
     "gjëra të vogla, marrëzi", "që i përket"),
    ("Urtësi, gjykim i mprehtë.",
     "Urtësi e mprehtë, praktike — lloji i gjykimit të mirë që vjen nga përvoja, jo vetëm nga librat.",
     "Mençuria e kapitenit të vjetër e mbajti ekuipazhin jashtë telasheve më shumë se një herë.",
     "me nuhatje të mprehtë, i zgjuar", "cilësi e"),
    ("Turma e zakonshme ose masat, e përdorur me përbuzje.",
     "Fjalë snobiste, përbuzëse për \"turmën\" ose njerëzit e thjeshtë, e përdorur me përbuzje.",
     "Konti qeshi me përçmim ndaj turmës së rëndomtë që mblidhej para portave të pallatit.",
     "qen", "kolektiv, tufë"),
    ("Trajtim ose gjuhë e pasjellshme, poshtëruese.",
     "Trajtim i egër, përbuzës i destinuar të poshtërojë — lloji i fyerjes i krijuar për të djegur.",
     "Ai duroi vite poshtërimi nga kritikët para se vepra e tij të njihej më në fund.",
     "me, tërësisht", "të fryhesh (nga krenaria)"),
    ("Me dyshim ose mosmiratim; vështrim anash.",
     "Vështrimi anash që i jep diçkaje që nuk e beson plotësisht — një vështrim i ngarkuar me dyshim.",
     "Mësuesja shikoi shtrembër detyrën e shtëpisë dyshimisht të rregullt.",
     "te, drejt", "pjerrësi, anësi"),
    ("Një person budalla; kokëdruri.",
     "Fyerje e vjetër, pothuajse e dashur për dikë që është i shurdhër ose i dendur — kokëdruri.",
     "\"O kokëtrashë,\" qeshi ajo, \"e ke pasur hartën përmbys gjithë kohës.\"",
     "copë dheu", "kokë"),
    ("Të vësh në lëvizje ose në veprim; të motivosh.",
     "Të jesh shkëndija që vë diçka në lëvizje — qoftë një makinë që ndizet, qoftë një person që më në fund vepron sipas një ideje.",
     "Frika e humbjes së kontratës e vuri gjithë ekipin në një fundjavë me orë shtesë.",
     "një bërje, një shtytje", "të shtysh, të bësh"),
    ("Përvetësim i fondeve të besuara në kujdesin tënd.",
     "Vjedhje e qetë e parave që të janë besuar t'i ruash — përvetësim i veshur me pallto të vjetër.",
     "Përvetësimi i thesararit mbeti i papërfillur gati një dekadë.",
     "pronë private", "bagëti, pasuri"),
    ("Grup i konsideruar në skajet e shoqërisë së respektueshme.",
     "Nënbota sociale e shkëlqyer por e hijshme — njerëz që jetojnë sapo jashtë rregullave të shoqërisë \"të respektueshme.\"",
     "Romani ndjek një këngëtare që lundron në gjysmëbotën e kabareve të viteve 1920.",
     "gjysmë", "botë, shoqëri"),
    ("Që ekziston ende; jo i zhdukur ose i shkatërruar.",
     "Ende këtu sot — përdoret për gjëra të vjetra (dorëshkrime, specie, ndërtesa) që kanë arritur të mbijetojnë.",
     "Njihen vetëm tre kopje të mbijetuara të shtypjes së parë.",
     "jashtë", "të qëndrosh"),
    ("Mashtrim; tradhti e besimit.",
     "Tradhti e thellë, e qëllimshme — të thye sh një besim që dikush kishte të drejtë të priste se do ta ruje.",
     "Gjenerali kurrë nuk ia fali mikut të vjetër pabesinë në tryezën e bisedimeve.",
     "përmes, kundër", "besim, besnikëri"),
    ("Dialekt krahinor, veçanërisht jo-standard.",
     "Mënyra e veçantë, vendase se si flasin njerëzit në një krahinë — plot fjalë e ritme që një i huaj mund të mos i kapë.",
     "Gjyshja e saj ende fliste të folmen e ishullit në darkat familjare.",
     "ligjëratë e ashpër, dialekt", "puthër — fjalë e ngathët"),
    ("E drejtë e veçantë që i takon një personi ose grupi.",
     "Privilegji që është i yti dhe vetëm i yti — e drejtë që vjen me rolin, pozitën ose statusin tënd.",
     "Zgjedhja e destinacionit të pushimeve të familjes është privilegj i gjyshit, dhe të gjithë e dinë.",
     "para", "të pyesësh, të votosh"),
    ("Guxim, guxim i trashë; gjithashtu qëndrueshmëri.",
     "Qëndrueshmëri e ashpër, e guximshme — nervi për të ecur përpara dhe fortësia për të vazhduar sapo të kesh filluar.",
     "Duhej guxim i vërtetë për të kaluar qafën në furtunë bore pa hartë.",
     "i guximshëm, i fortë", "gjendje, kusht"),
    ("Të lulëzosh; gjithashtu të zhvillohesh ose të shfaqesh gradualisht.",
     "Të lulëzosh në shprehje të plotë — si një lule që hapet, ose një ide që më në fund vjen te vetja.",
     "Talenti i saj i qetë për pikturë lulëzoi sapo pati një studio të vetën.",
     "jashtë", "të fillosh të lulëzosh"),
    ("Fije e peshuar për të përcaktuar vertikalisht; figurativisht, standard gjykimi.",
     "Një peshë në fije që varret krejt drejt poshtë, për të kontrolluar nëse diçka është vërtet vertikale — dhe, më gjerë, çdo standard i fiksuar kundrejt të cilit mat gjithçka tjetër.",
     "Ai përdorte ndershmërinë e gjyshit të tij si një lloj filli vertikal për çdo vendim.",
     "plumb", "litar, masë"),
    ("Me kënaqësi, me dëshirë (i vjetëruar).",
     "Mënyrë e vjetër për të thënë \"me kënaqësi\" ose \"me dëshirë.\"",
     "\"Do të pushoja me kënaqësi këtu pak,\" psherëtiu udhëtari.",
     "i gëzuar, i lumtur", "me kënaqësi, me dëshirë"),
    ("Kritikë e ashpër publike ose turp.",
     "Turp publik i grumbulluar mbi dikë në mënyrë të madhe, të dukshme — turpi që vjen nga mosmiratimi i gjerë.",
     "Skandali solli turp publik mbi gjithë firmën.",
     "kundër", "turp, qortim"),
    ("Thellësisht sarkastik, i prerë në zgjuarsi ose kritikë.",
     "Zgjuarsi me dhëmbë të vërtetë — një vërejtje kafshuese djeg pikërisht sepse është kaq zgjuar e synuar.",
     "Recensionet e saj kafshuese të filmave i trembnin regjisorët dhe i donin lexuesit.",
     "të kafshosh", "që kafshon, që bën"),
    ("Shpallje formale, shpesh politike ose ushtarake.",
     "Njoftim i madh, zyrtar — zakonisht ai që shpall një qeveri të re, një kryengritje ose një dekret të rëndësishëm.",
     "Kumtesa e gjeneralit në agim shpalli qeverinë e re.",
     "përpara", "të shpallësh"),
    ("Person me njohuri sipërfaqësore që bën sikur është ekspert.",
     "Dikush që ka përshkuar sipërfaqen e një teme dhe pastaj flet sikur ka shkruar tekstin shkollor për të.",
     "Gjysmëdijetari i darkës korrigjoi me siguri astrofizikanin e vërtetë në tryezë.",
     "të dish", "zvogëlues — një njohës i vogël"),
    ("Rënie e aftësive mendore në pleqëri.",
     "Ajo shtrirje e mjegullt, harrese e pleqërisë së thellë kur mprehtësia e mendjes fillon të zbehet.",
     "Në pleqërinë e tij, tregonte të njëjtat tre histori çdo vizitë, çdo herë sikur të ishin të reja.",
     "të bëhesh budalla, të jesh i marrë", "gjendje ose rezultat"),
    ("Ana e mbrojtur nga era.",
     "Ana e qetë, e mbrojtur e diçkaje — një kodër, një anije, një mur — ku era nuk të arrin fare.",
     "Udhëtarët ngritën çadrën në anën e strehuar të kreshtës për t'i shpëtuar erërave.",
     "strehë, mbrojtje", "anë, fytyrë"),
    ("Të zmbrapsësh ose të mbrohesh nga një goditje, pyetje ose argument.",
     "Të zmbrapsësh butësisht diçka — një goditje shpate, një pyetje të vështirë, ose një akuzë — pa humbur ritmin.",
     "Ajo e zmbrapsi pyetjen e vështirë të gazetarit me një shaka të lehtë.",
     "të zmbrapsësh", "të përgatitesh, të mbrohesh"),
    ("Me erë të keqe, i dëmshëm.",
     "Që qelbon në mënyrë që ndihet pothuajse toksike — një erë kaq e keqe sa duket e rrezikshme të frymëmarrësh.",
     "Një erë e qelbur ngrihej nga këneta ndërsa dielli perëndonte.",
     "avull i dëmshëm", "që ka natyrën e"),
    ("Person i përkushtuar ndaj luksit dhe kënaqësisë.",
     "Dikush që jeton për rehati dhe kënaqësi — ushqim i mirë, shtretër të butë, jetë e lehtë — emërtuar nga qyteti i lashtë grek Sybaris, i famshëm për tepricat.",
     "Një sibarit i vërtetë, ai refuzonte çdo dhomë hoteli pa vaskë.",
     "qytet i lashtë grek i famshëm për luks", "banor i"),
    ("Të lësh qëllimisht mënjanë ose të injorosh një pjesë.",
     "Të lësh qëllimisht një copë të enigmës mënjanë, që të përqendrohesh pastër te pjesa tjetër.",
     "Le të shkëputemi nga kostoja për një çast dhe të pyesim vetëm nëse plani funksionon vërtet.",
     "para, larg", "të presësh"),
    ("Të kritikosh rëndë; gjithashtu, të heqësh lëkurën.",
     "Të grisësh dikë me kritikë të ashpër — me fjalë, sikur fjalë për fjalë t'i hiqje lëkurën.",
     "Kritikët e shqyen vazhdimin për tradhtinë e gjithçkaje që fansat donin te origjinali.",
     "poshtë", "lëkurë, lëkurë kafshe"),
    ("Të sjellësh si dëshmi ose provë.",
     "Të nxjerrësh një fakt ose shembull për të mbështetur pikën tënde — ajo që tregon kur dikush pyet \"what's your evidence?\"",
     "Avokatja paraqiti tre dëshmitarë për të mbështetur alibinë e klientit.",
     "te, drejt", "të udhëheqësh"),
    ("Udhëtime ose endje, veçanërisht të gjata ose të gjera.",
     "Udhëtime të gjata, endacake — lloji i endjes së gjerë që të çon larg shtëpisë për një kohë të gjatë.",
     "Bredhjet e tij nëpër tre kontinente mbushën një raft të tërë ditarësh udhëtimi.",
     "përmes", "fushë, tokë (peregrinus: i huaj)"),
    ("Lypës, ose dikush që jeton nga lëmosha.",
     "Dikush që jeton duke kërkuar bamirësi — historikisht kjo përshkruante edhe murgjit që bënin betime varfërie dhe jetonin nga dhurimet.",
     "Murgjit lypës nuk zotëronin asgjë dhe mbështeteshin tërësisht te mirësia e fshatarëve.",
     "të lypësh", "lypës"),
    ("Tejet bujar.",
     "Bujar në shkallë të madhe, pothuajse shfaqëse — lloji i dhuratës që i bën njerëzit të nxjerrin pak frymë.",
     "Dhurimi bujar financoi gjithë krahun e ri të bibliotekës.",
     "dhuratë, shërbim", "që bën, që jep"),
    ("Rraskapitje nga mungesa e ushqimit; gjithashtu mungesë vitaliteti.",
     "Gjendje e dobët, e shteruar nga të mos u ushqyer ose mbushur — fjalë për fjalë nga uria, ose figurativisht nga të mos të ketë mbetur asgjë për të punuar.",
     "Në fund të rrethimit, ushtarët ishin afër rraskapitjes.",
     "i zbrazët, boshllëk", "veprimi ose rezultati i"),
    ("Kritikë e hidhur, fyese.",
     "Kritikë që ka kaluar shumë tej të drejtës dhe është kthyer në një tiradë të zemëruar, të hidhur.",
     "Komentet në internet u shpërbënë në sharje të pastra brenda minutash.",
     "faj", "të përgatitësh, të pajisësh"),
    ("Armiqësor, i dëmshëm në efekt.",
     "Punon kundër teje, edhe nëse në heshtje — kushte ose qëndrime që nuk janë miqësore ndaj interesave të tua.",
     "Politika e re ishte armiqësore për bizneset e vogla, edhe nëse ky nuk ishte qëllimi.",
     "jo", "mik"),
    ("I prirur të shkaktojë zemërim ose pakënaqësi, shpesh përmes krahasimeve të padrejta.",
     "I destinuar të bëjë dikë të ndihet i lënë mënjanë — zakonisht sepse vë njerëz ose gjëra kundër njëri-tjetrit padrejtësisht.",
     "Të renditësh vëllezërit e motrat sipas asaj se \"kë e do mamaja më shumë\" është një lojë përçarëse që askush nuk duhet ta luajë.",
     "invidi", "të shikosh (me vullnet të keq)"),
    ("Person me rang ose status më të ulët; vartës.",
     "Dikush më poshtë në zinxhirin e komandës ose shkallën sociale — një i ri, që punon nën dikë me më shumë pushtet.",
     "Si oficer i vogël i ri, ai merrte urdhra shumë para se t'i jepte ndonjëherë.",
     "nën", "alternativ, tjetër"),
    ("Të ndjesh ose të shprehësh urrejtje të fortë për.",
     "Të urresh diçka aq shumë sa ta mallkosh me zë — neveri e pastër, me zë.",
     "Fshatarët e mallkonin mbledhësin e taksave sa herë që karroca e tij rrotullohej nëpër qytet.",
     "jashtë nga", "i shenjtë (të mallkosh jashtë të shenjtës)"),
    ("Mbulesë e jashtme natyrore, si lëkura ose predha.",
     "Mbështjellja mbrojtëse e vetë natyrës — lëkurë, predhë, lëvozhgë ose lëvore, çfarëdo që mbulon dhe mbron diçka të gjallë.",
     "Predha e breshkës është një mbulesë jashtëzakonisht e fortë.",
     "mbi, mbi", "të mbulosh"),
    ("I pafajshëm, naiv, me thjeshtësi fëmijërore; e kundërta e \"disingenuous.\"",
     "I hapur, besues dhe pak naiv, pa asnjë axhendë të fshehtë — e lehtë për t'u ngatërruar me \"ingenious,\" që do të thotë i zgjuar.",
     "Pyetja e saj e çiltër — \"pse do të gënjente kush për këtë?\" — tregoi sa pak dinakëri kishte.",
     "brenda, i lindur", "të lindësh (i lindur i lirë, i hapur)"),
    ("Shqetësim i tepruar me hollësi të vogla ose rregulla.",
     "Të humbasësh në rregullat e vogla duke humbur pamjen e madhe — të obsesionohësh me shkronjat e imta që askush tjetër nuk i vë re.",
     "Pedanteria e tij për presjet e Oksfordit i prishi gjithë mbledhjen.",
     "mësues fëmijësh", "praktikë ose cilësi"),
    ("Ekzaminim i thellë, i kujdesshëm.",
     "Një vështrim i thellë, pa-gur-të-palëvizur — të shkosh mbi çdo hollësi me kujdes të vërtetë.",
     "Vetëm pas një shqyrtimi të kujdesshëm të librave të llogarive doli mospërputhja.",
     "përmes, tërësisht", "të kërkosh, të shqyrtoosh"),
    ("Të ngrësh kundërshtime; të tregosh hezitim.",
     "Të tërhiqesh me mirësjellje ose të hezitosh në vend që të pranosh menjëherë — një \"I'd rather not\" i butë.",
     "Kur iu kërkua të nënshkruante pa e lexuar, ajo ngurroi.",
     "nga, larg", "të vonosh"),
    ("Sipërfaqësisht i besueshëm, por në të vërtetë i gabuar.",
     "Tingëllon bindëse në shikim të parë, por shkërmoqet në çastin që e kontrollon vërtet.",
     "\"Everyone's doing it\" është një argument mashtrues që kurrë nuk qëndron nën shqyrtim.",
     "pamje, dukje", "i mbushur me (që duket i bukur)"),
    ("Fjalë e pasinqertë, hipokrite, shpesh moralizuese.",
     "Fjalë predikuese që tingëllon e virtytshme por nuk mbështetet nga asnjë ndjenjë e vërtetë — pozë morale në autopilot.",
     "Ai ishte lodhur nga llafet boshe korporative për \"familjen\" nga një kompani që kurrë nuk i jepte askujt pushime.",
     "të këndosh (më vonë: zhargon monoton)", "ligjëratë vajtuese e lypësve, pastaj hipokrizi"),
    ("Pa guxim, i frikësuar.",
     "I timor deri në mungesë kurrizi — shumë i frikësuar për t'u ngritur edhe kur ka rëndësi të qartë.",
     "Heshtja frikacake e bordit e la skandalin të shpërthente jashtë kontrollit.",
     "shumë i vogël", "shpirt, guxim"),
    ("Si dhelpër; dinak, i zgjuar.",
     "Dinak e i zgjuar si dhelpra — i shpejtë në mendje, pak i rrëshqitshëm, gjithmonë një hap përpara.",
     "Ai dha një buzëqeshje dhelparake në çastin që vuri re të çarën.",
     "dhelpër", "i ose si"),
    ("Njëri pas tjetrit, me radhë.",
     "I marrë rreptësisht një nga një, me radhë — pa kërcyer përpara, pa bërë dy njëherësh.",
     "Gjykuesi i trajtoi secilën nga dymbëdhjetë pretendimet një nga një.",
     "rresht, sekuencë", "një nga një"),
    ("Kursim i skajshëm; koprraci.",
     "Të jesh i ngushtë me paratë (ose fjalët, ose burimet) shumë përtej kursimit të arsyeshëm.",
     "Koprracia e tij ishte legjendare — qeset e çajit i ripërdorte tri herë.",
     "të kursesh, të jesh kursimtar", "gjendje ose praktikë"),
    ("Korrigjim, veçanërisht në një tekst.",
     "Një ndreqje e bërë në një shkrim — një ndreqje shkencore që korrigjon një gabim në një tekst të vjetër ose të rëndësishëm.",
     "Botimi i ri përfshin dhjetëra ndreqje të dorëshkrimit origjinal.",
     "jashtë nga", "faj, gabim"),
    ("I moderuar në ngrënie dhe pirje.",
     "I përmbajtur qëllimisht rreth ushqimit dhe pijes — kurrë nuk tepron, gjithmonë lë pak në pjatë.",
     "Zakonet e tij të përkorë e mbajtën të mprehtë shumë pasi moshatarët e tij ishin ngadalësuar.",
     "larg nga", "pije dehëse"),
    ("Gabim gramatikor ose shkelje e etikës.",
     "Një rrëshqitje në gramatikë ose sjellje — lloji i gabimit të vogël që e bën pedantin të dridhet.",
     "\"Between you and I\" është një gabim i zakonshëm gjuhësor që ende i bën gramatikanët të tunden.",
     "qytet cilician i njohur për greqishten 'të keqe'", "praktikë, mënyrë"),
    ("Që lidhet me konfliktin brenda një grupi; shkatërrues i ndërsjellë.",
     "Grindje e brendshme që gris grupin nga brenda — një luftë ku të gjithë humbin, sepse është familje kundër familjes.",
     "Grindjet e brendshme të partisë bënë më shumë dëm se çdo kundërshtar i jashtëm.",
     "ndërmjet, mes", "të vrasësh"),
    ("Qëndrim indiferent, i pakujdesshëm.",
     "Një ngritje supe e kthyer në personalitet të tërë — të të interesojë kaq pak gjërat që dikur kishin rëndësi sa asgjë nuk duket e vlefshme më.",
     "Qëndrimi i tij indiferent ndaj ceremonisë së çmimeve i befasoi të gjithë që dinin sa fort kishte punuar.",
     "pak", "të të interesojë"),
    ("Situatë ose mosmarrëveshje e ngatërruar, e ndërlikuar.",
     "Situatë e ngatërruar, e çrregullt, e vështirë për t'u kuptuar — pjesë keqkuptimi, pjesë dramë, gjithë konfuzion.",
     "I gjithë ngatërrimi i planit të ulëseve nisi me një kartë emri të vendosur gabim.",
     "brenda", "të ngatërrosh, të hutosh"),
    ("Kërcënues, i frikshëm.",
     "Që mbart një atmosferë të qartë kërcënimi — një vështrim ose letër kërcënuese e bën shumë të qartë se mund të ndjekë diçka e keqe.",
     "Toni kërcënues i letrës e bëri qiramarrësen nervoze para se të kishte hapur zarfin.",
     "të kërcënosh", "që shërben për"),
    ("Kritikë e fortë publike ose fyerje me fjalë.",
     "Dënim i zëshëm, publik — lloji i kritikës djegëse që ndodh para të gjithëve.",
     "Sinjalizuesja u përball me vite përbaltjeje publike para se historia ta vërtetonte.",
     "kundër", "të flasësh"),
    ("Shpërthim i papritur i dhunshëm, i emocionit ose veprimit.",
     "Shpërthim i papritur, intensiv që të merr përsipër menjëherë — një krizë e të qeshurit, zemërimit ose kollës që bie si valë.",
     "Ajo u kap nga një krizë të qeshuri që nuk mund t'ia shpjegonte askujt tjetër në dhomë.",
     "përtej", "i mprehtë, akut"),
    ("I shtuar nga një burim i jashtëm, jo i brendshëm.",
     "I vidhosur nga jashtë në vend që të jetë ndërtuar që në fillim — një shtesë, jo pjesë thelbësore.",
     "Komenti duket i shtuar nga jashtë, sikur të ishte ngjitur mbi një tekst tashmë të përfunduar.",
     "te, përveç", "të miratosh, të marrësh"),
    ("Mungesë njohurish, injorancë.",
     "Thjesht mosdije — një boshllëk në njohuri, pa asnjë gjykim të lidhur.",
     "Ai pranoi mosnjohjen e tij për verën franceze dhe e la somelierin të zgjidhte.",
     "jo", "të dish"),
    ("Interes i tepruar për çështje seksuale.",
     "Kuriozitet tepër i etur, i vështruar për gjithçka pikante — interes që ka kaluar të shëndetshmen te ngacmuesja.",
     "Epshi i tabloidit mbi jetën private të çiftit kufizohej me obsesionin.",
     "të kruhesh, të dëshirosh", "gjendje e"),
    ("I tymosur, i errët, i turbullt.",
     "I errët e i tymosur në pamje, sikur gjithçka të ishte e mbuluar me një shtresë të hollë tymi.",
     "Një mjegull blozë varej mbi qytetin e fabrikës në muzg.",
     "tym", "i mbushur me"),
    ("Të mohosh ose të kundërshtosh.",
     "Të flasësh rrafshët kundër asaj që tha dikush tjetër — të thuash \"that's not so.\"",
     "Askush nuk guxoi të kundërshtonte tregimin e kapitenit të vjetër për stuhinë.",
     "kundër", "të flasësh"),
    ("Përtaci, dembelizëm (nga latinishtja).",
     "Fjalë e vjetër latine për përtacinë e pastër — tërheqja e të mos dashur të bësh asgjë fare.",
     "Murgjit predikonin kundër përtacisë si një nga rreziqet e qeta të shpirtit.",
     "jo", "i zënë, i zellshëm"),
    ("Mburojë që shfaq një stemë.",
     "Emblema në formë mburoje që tregon stemën e familjes — \"pllakën e emrit\" heraldike.",
     "Stema e familjes ende varet mbi derën e përparme të manorit të vjetër.",
     "mburojë", "zvogëlues / objekt"),
    ("I vjetëruar, i dalë mode, ose i pensionuar për shkak të moshës.",
     "Përtej kulmit të dobishëm dhe i lënë në kullotë — shumë i vjetëruar ose i konsumuar për të vazhduar punën.",
     "Printeri i vjetruar më në fund u zëvendësua pas pesëmbëdhjetë vjetësh bllokimesh.",
     "përtej", "vit"),
    ("Zëvendësues, veçanërisht në mjekësi.",
     "Mjekime zëvendësuese që përdoren kur trajtimi i vërtetë nuk është i disponueshëm — në thelb dublantë mjekësorë.",
     "Mjekët e luftës shpesh mbështeteshin te zëvendësuesit kur mbaronin barnat e vërteta.",
     "në vend të", "të shkosh, të lësh vend"),
    ("Fjalë mburrëse, e zhurmshme.",
     "Mburrje e madhe, e zhurmshme — fjalë e zëshme për madhështinë tënde që është kryesisht ajër i nxehtë.",
     "Mburrja e tij se e kishte shpëtuar projektin \"krejt vetëm\" nuk mashtroi askënd që kishte qenë vërtet aty.",
     "kalorës mburrës në Orlando Furioso", "veprim, shfaqje"),
    ("Të përdorësh mashtrim ose dinakëri për të arritur diçka.",
     "Të rrëshqasësh drejt një qëllimi me trukë të dinakë, jo me lojë të drejtë.",
     "Ai u fut me dredhi në marrëveshje me një kontratë plot shkronja të imta.",
     "të ngatërrosh, të mashtrash", "dinakëri; më vonë kthesë e mprehtë"),
    ("Shkenca e pastër ose abstrakte e të nxënit ose e dijes, shpesh matematika.",
     "Të nxënit në formën e tij më të pastër, më abstrakte — struktura e thellë e vetë dijes, veçanërisht ajo matematike.",
     "Filozofi ëndërronte një mathesis universale që mund të bashkonte çdo fushë të dijes.",
     "të mësosh", "akti i të nxënit"),
    ("Tejet i shqetësuar me rregulla formale ose hollësi të parëndësishme.",
     "Tepër i rreptë për gjërat e vogla — korrigjon nuanca të vogla teknike që në të vërtetë nuk ndryshojnë asgjë.",
     "Dukej pak pedante të diskutoje për \"who\" kundër \"whom\" në një mesazh.",
     "udhëheqës fëmijësh, mësues", "që ka mënyrën e"),
    ("Dritë që shkëlqen, që xixa.",
     "Një shkëndijë e shpejtë, e shkëlqyer drite — mendo dritën e diellit mbi ujë, ose një diamant që kap dritën.",
     "Vezullimi i llambadarit shpërndau dritën në çdo cep të sallës së ballos.",
     "të shkëlqesh, të xixëlosh", "akti i"),
    ("Fillestar, novic.",
     "Dikush krejt i ri në një aftësi ose fushë — ende po i mëson litarët, ende jo ekspert.",
     "Edhe një lojtar shahu fillestar mund ta vërë re atë gabim.",
     "rekrut, novic", "ushtar i ri i papërpunuar"),
    ("Tejet i keq, i neveritshëm.",
     "I keq në një mënyrë që meriton neveri të vërtetë — jo vetëm \"mesatar,\" por vërtet i neveritshëm.",
     "Recensuesi e quajti vazhdimin të neveritshëm, dhe numrat e arkës u pajtuan.",
     "të mallkosh", "i denjë, i aftë të jetë"),
    ("I kuq si gjaku.",
     "Një e kuqe e thellë, e gjallë — ngjyra e gjakut të freskët, e përdorur famshëm nga Makbethi i Shekspirit.",
     "Perëndimi e ktheu gjithë qiellin në një shkëlqim gjakosur.",
     "brenda", "mish (i kuq mishi)"),
    ("Hapësirë e vogël ose boshllëk ndërmjet gjërave.",
     "Ajo hapësirë e vogël ndërmjet që është e lehtë të anashkalohet — çarja ndërmjet dërrasave të dyshemesë, boshllëku në orar.",
     "Barërat e këqija shtynin lart nëpër çdo të çarë të shtegut të vjetër të tullave.",
     "ndërmjet", "të qëndrosh"),
    ("Vërejtje kritike ose qortuese.",
     "Komente të mprehta, mosmiratuese — lloji i kritikës që mbart pak ton qortimi.",
     "Vërejtjet e profesorit mbi esenë i mbushën anët me bojë të kuqe.",
     "mendje", "të kthehesh drejt"),
    ("I pamundur për t'u hedhur poshtë, i pamohueshëm.",
     "Ka aq i fortë i vërtetuar sa nuk ka se çfarë të diskutosh — çështja është thjesht e mbyllur.",
     "Prova e ADN-së ishte e pakundërshtueshme, dhe gjyqi mbaroi brenda orës.",
     "jo", "të kundërshtosh, t'i rezistosh"),
    ("Ndërlikim, ngatërresë; gjithashtu një përthyerje e brendshme.",
     "Një ndërlikim i ngatërruar, i palosur mbi vete — gjëra të mbështjella kaq ngushtë sa janë të vështira për t'u shkëputur.",
     "Ndërlikimi i intrigës e la gjysmën e publikut duke u përpjekur ta zgjidhte pas titujve.",
     "brenda, drejt brendësisë", "të rrotullosh, të kthesh"),
    ("Forcë ose përpjekje, si në \"by dint of.\"",
     "Forcë ose përpjekje e pastër — sot mbijeton kryesisht në frazën \"by dint of.\"",
     "Ai e kaloi provimin falë praktikës së pastër, kokëfortë.",
     "një goditje, një rrahje", "me forcën e"),
    ("I bashkuar me nyjë dhëmb e fole; i përshtatur fort bashkë.",
     "I kyçur bashkë në mënyrën e vjetër të zdrukthëtarit — një copë që futet ngushtë në një vrimë të prerë pikërisht për të.",
     "Trarët e hambarit të vjetër ishin bashkuar me dhëmb e fole pa asnjë gozhdë.",
     "fole, vrimë", "kafshim, kapje"),
    ("Shumë i përshtatshëm, i saktë.",
     "Pikërisht i duhuri për çastin — një vërejtje, citim ose shembull që bie përsosmërisht në pikë.",
     "Vërejtja e saj e goditur e përmblodhi gjithë debatin në një fjali.",
     "te", "të vendosësh"),
    ("Që shkëlqen butësisht ose xixëllon (dritë); gjithashtu zgjuarsi e lehtë.",
     "Që shkëlqen butësisht në vend që të flakërojë — dritë e butë, xixëlluese, ose zgjuarsi lozonjare në vend të ashpër.",
     "Drita e qirinjve hodhi një shkëlqim vezullues mbi dhomën e ngrënies së vjetër.",
     "të lëpish", "që bën (dritë që 'lëpin')"),
    ("Ermit fetar që jeton në vetmi.",
     "Dikush që tërhiqet tërësisht nga bota për të jetuar vetëm në lutje e reflektim.",
     "Vetmitari jetoi në një qeli të vogël të lidhur me kishën për mbi tridhjetë vjet.",
     "mbrapa, larg", "të tërhiqesh"),
    ("Të shuash etjen; të shuash.",
     "Të kënaqësh plotësisht një dëshirë — më shpesh etjen, por figurativisht çdo nevojë të thellë.",
     "Një gotë e ftohtë uji ia shoi etjen pas ecjes së gjatë.",
     "i lëshuar, i lirë", "të lëshosh, të qetësosh"),
    ("Në formë gjilpëre.",
     "I gjatë, i hollë e i mprehtë si gjilpërë — forma e një gjilpëre pishë ose e një kristali të vogël të mprehtë.",
     "Pishat njihen lehtë nga gjethet e tyre gjilpërore.",
     "gjilpërë", "i vogël"),
    ("I shteruar nga vitaliteti, i dobët, i stërholluar.",
     "I konsumuar e i butë — që ka humbur forcën ose gjallërinë origjinale nga shumë rehati ose stërhollim.",
     "Kritikët e quajtën revistën dikur të guximshme të sfilitur, hijen e viteve të saj të hershme të guximshme.",
     "jashtë", "i frytshëm, që ka lindur"),
    ("Aksesor ose send ose e drejtë e vogël e bashkangjitur.",
     "Një shtesë e vogël që vjen e bashkangjitur me diçka më të madhe — aksesorët dhe shtesat që i përkasin gjësë kryesore.",
     "Qiraja përfshinte garazhin dhe të gjitha pajisjet e tij.",
     "te", "të i përkasësh"),
    ("Të mbulosh ose të zvogëlosh një faj.",
     "Të zbutësh një gabim me fjalë të buta, duke e bërë të tingëllojë më i vogël se sa është.",
     "Ai u përpoq ta zbukuronte afatin e humbur me fjalë të mjegullta për \"sfida të paparashikuara\".",
     "glosë, shpjegim", "të komentosh — pastaj të zbutësh"),
    ("Në fazë të hershme, sapo ka filluar.",
     "Sapo po tregon veten — faza e parë, mezi e dukshme e diçkaje më të madhe që do të vijë.",
     "Mjekët kapën shenjat e para të sëmundjes para se ajo të përhapej.",
     "mbi, brenda", "të marrësh (të ndërmarrësh, të fillosh)"),
    ("Frymëzim krijues, veçanërisht hyjnor.",
     "Një valë e papritur frymëzimi që ndihet më e madhe se ti — sikur ideja të të jetë fryrë nga diku tjetër.",
     "Poeti e përshkroi gjithë pjesën duke ardhur në një shpërthim frymëzimi në orën tre të mëngjesit.",
     "te, mbi", "të frysh (një fryrje mbi)"),
]
