# Finnish rows
ROWS = [
    ("Makeuttaa tai puhdistaa; poistaa karheus jostakin.",
     "Ottaa pisto tai karvaus jostakin — kirjaimellisesti makeuttamalla, tai kuvainnollisesti pehmentämällä kova ajatus, jotta se menee paremmin alas.",
     "Toimittaja edulcorated kovan arvostelun ennen kuin se meni painoon.",
     "ulos, perin pohjin", "makea"),
    ("Liiallisen tai teennäisen uskonnollinen tai hurskas.",
     "Kuvaa ihmistä, jonka uskonnollinen hartaus tuntuu näytökseltä — enemmän esitystä kuin aitoa uskoa.",
     "Hänen pietistic huokailunsa saarnan aikana ärsytti muuta penkkiriviä.",
     "hurskaus, velvollisuudentunto", "jonka luonne on"),
    ("Kieliopillisesta rakenteesta syntyvä kaksiselitteisyys — lause, joka voidaan lukea kahdella tavalla.",
     "Lause, joka on kieliopillisesti kunnossa mutta voidaan lukea kahdella täysin eri tavalla, kuten \"I saw the man with the telescope.\"",
     "\"Visiting relatives can be tiring\" on klassinen amphiboly — ovatko sukulaiset uuvuttavia, vai onko heidän luona käyminen?",
     "molemmat, molemmin puolin", "heittää"),
    ("Terävä, osuva, leikkaa suoraan asiaan.",
     "Leikkaa suoraan täytteen läpi — trenchant huomautus tai mieli pääsee asian ytimeen nopeasti, ilman turhia sanoja.",
     "Hänen trenchant arvostelunsa ei jättänyt elokuvan juoniaukoille piilopaikkaa.",
     "leikata", "tekevä, jonka laatu on"),
    ("Vasta alussa; varhaisessa tai alkeellisessa vaiheessa.",
     "Yhä avaushetkissään — suunnitelma, tunne tai prosessi, joka on vasta alkanut saada muotoa.",
     "Sopimuksen inchoative vaiheet olivat lupaavia, mutta monet yksityiskohdat olivat vielä auki.",
     "aloittaa, käynnistää", "joka pyrkii kohti"),
    ("Muodollinen puhe tai kirjoitus, joka ylistää ketään suuresti.",
     "Täysimittainen, muodollinen ylistys — ajattele hehkuvaa muistopuhetta tai puhetta, joka laulaa jonkun saavutuksia katoilta.",
     "Eläkkeelle jäävä professori saateltiin matkaan panegyric-puheella lähimmiltä opiskelijoiltaan.",
     "kaikki", "kokous, kokoontuminen"),
    ("Koskee todellista olemassaoloa tai tosiasiallista olemista, vastakohtana abstraktille teorialle.",
     "Asioista sellaisina kuin ne todella ovat olemassa, ei vain ideoina tai teorioina niistä.",
     "Filosofit kiistelevät, onko luvuilla mitään ontic asemaa vai ovatko ne olemassa vain mielissämme.",
     "oleminen, se mikä on", "joka liittyy"),
    ("Kantaa hedelmää tai tulla tuottavaksi.",
     "Tuottaa vihdoin tulosta — ponnistus, idea tai sijoitus, joka fructify, on kasvanut siemenestä joksikin hyödylliseksi.",
     "Vuosien hiljainen tutkimus fructified vihdoin toimivaksi rokotteeksi.",
     "hedelmä", "tehdä, aiheuttaa"),
    ("Ennakoi tai esittää jotakin jo tehtynä ennen kuin se on todella tapahtunut.",
     "Juoksee edelle kirjallisesti — kuvaa tulevaa tapahtumaa kuin se olisi jo ohi, jotta pointti iskee kovemmin.",
     "Kenraalin proleptical malja \"victory\":lle nostettiin kokonainen viikko ennen taistelua.",
     "ennen", "ottaa, temmata"),
    ("Ilmanpaineella toimiva; myös henkeen tai hengitykseen liittyvä.",
     "Tarkoittaa yleensä \"paineilmalla toimivaa\" — vaikka se voi merkitä myös henkeä tai hengitystä.",
     "Pneumatic jarrut sihisivät, kun bussi pysähtyi reunakivelle.",
     "tuuli, hengitys, henki", "joka kuuluu"),
    ("Kuvaa Jumalaa tai jumalallista myönteisillä väitteillä — apofaattisen vastakohta.",
     "Tapa puhua Jumalasta sanomalla, mitä Jumala on — \"God is love\" — eikä vain, mitä Jumala ei ole.",
     "Cataphatic teologia puhuu luottavaisesti Jumalasta rakastavana, oikeudenmukaisena ja laupiaana.",
     "alas, mukaan", "puhua, sanoa"),
    ("Luottamukseen tai uskoon perustuva; myös kiinteä viitepiste.",
     "Jokin, jonka otat luottamuksella ja jota käytät sitten ankkurina — fiducial merkki on kiinteä piste, johon kaikki muu mitataan.",
     "Maanmittarit asettivat fiducial merkin kallioperään ennen alueen kartoitusta.",
     "luottaa", "luottamus, varmuus"),
    ("Jumalan hyvyyden puolustus pahan olemassaolon valossa.",
     "Iänikuinen yritys vastata kysymykseen \"If God is good, why does evil exist?\"",
     "Hänen tutkielmansa tarkasteli theodicya Jobin kirjan kautta.",
     "jumala", "oikeudenmukaisuus"),
    ("Keskinäinen asuminen toisissaan — teologinen termi sille, miten Kolminaisuuden persoonat ovat toisissaan.",
     "Teologian sana kolmessa-yhdessä-yhteydelle, joka on niin täydellinen, että kukin osa sisältää toiset ja sisältyy niihin.",
     "Circumincession-oppi yrittää selittää, miten Isä, Poika ja Henki ovat erillisiä mutta erottamattomia.",
     "ympäri", "mennä, kävellä"),
    ("Saada seuraus, joka hyödyttää ketään tai heijastuu takaisin häneen.",
     "Kun kunnia (tai syy) kimpoaa takaisin vastuulliselle — hyvät teot, jotka redound maineellesi, palaavat palkitsemaan sinua.",
     "Joukkueen menestys tulee redound hiljaisen, ahkeran valmentajansa kunniaksi.",
     "takaisin, jälleen", "aalto"),
    ("Mahdoton välttää tai paeta.",
     "Tapahtuu väistämättä, teitpä mitä tahansa — ineluctable lopputuloksesta ei luikahdeta pois.",
     "Vanhuus tulee kaikille; se on yksinkertaisesti ineluctable.",
     "ei", "kamppailla ulos"),
    ("Käyttää kiertelevää, sanarikasta ilmaisua suoran muodon sijaan.",
     "Pitkä kiertotie sanoilla — sanoa \"make a decision\" sen sijaan että sanoisi \"decide.\"",
     "Hänen periphrastic sähköpostinsa olisivat voineet sanoa yhdellä rivillä sen, mihin häneltä meni kolme kappaletta.",
     "ympäri", "julistaa, kertoa"),
    ("Henkinen tylsyys tai letargia.",
     "Se utuinen, visva mielentila, jossa ajattelu tuntuu siirapissa kahlailulta.",
     "Hebetude-aalto iski luokkaan heti lounaan jälkeen.",
     "tylppä, tumpelo", "tila tai ominaisuus"),
    ("Epäsuotuisa; enteilee pahaa.",
     "Huono merkki — olosuhteet tai ajoitus, jotka tuntuvat toimivan sinua vastaan jo ennen kuin olet edes alkanut.",
     "Harmaa taivas ja kuollut autonakku tekivät road tripille unpropitious alun.",
     "ei", "suotuisa, armollinen"),
    ("Kastikkeessa haudutettua tai braseroitua lihaa — oikein kirjoitettuna \"fricasseed.\"",
     "Kotoisa vanha keittotermi lihalle, joka on leikattu paloiksi ja haudutettu hitaasti omassa kastikkeessaan mureaksi.",
     "Isoäidin fricasseed kana oli jokaisen sunnuntailounaan kohokohta.",
     "paistaa", "rikkoa (paloiksi)"),
    ("Keinotekoinen tai heikompi korvike.",
     "Jäljitelmä aidon tilalla — hoitaa homman teknisesti, mutta kaikki näkevät, ettei se ole aitoa tavaraa.",
     "Sodanaikaiset ostajat tyytyivät paahdetusta sikurista keitettyyn ersatz-kahviin.",
     "ulos, korvausetuliite", "asettaa, sijoittaa"),
    ("Kohdella abstraktia ideaa kuin se olisi konkreettinen asia.",
     "Saada idea tuntumaan todelliselta ja kiinteältä — muuttaa sumea asia, kuten \"the economy,\" joksikin, johon voi osoittaa.",
     "Kansakunnan \"spirit\":n kutsuminen omaksi olennokseen reifies jotakin, joka on oikeasti vain miljoonia yksittäisiä valintoja.",
     "asia", "tehdä"),
    ("Pakeni tai vältti taitavasti.",
     "Luiskahti puhtaasti karkuun — väisti jotakin, usein ovelasti tai täpärästi, oli se sitten kiinniotto, kysymys tai vastaus.",
     "Vastaus eluded häntä tunteja, kunnes se yhtäkkiä naksahti suihkussa.",
     "ulos, pois", "leikkiä"),
    ("Ilmaisee epäilyä, hämmennystä tai ratkaisematonta ristiriitaa.",
     "Jumissa aidossa ajattelun umpikujassa — ei laiskuudesta hämmentynyt, vaan koska kysymys itse vastustaa siistiä vastausta.",
     "Sokrates päätti usein dialoginsa aporetic sävyyn, enemmän kysymyksiä kuin vastauksia.",
     "ilman", "käytävä, tie"),
    ("Kielikuva, joka nimeää asian liittyvällä termillä, esim. \"the crown\" hallitsijasta.",
     "Käyttää liittyvää sanaa itse asian sijaan — sanoa \"the White House announced,\" kun tarkoittaa hallintoa.",
     "\"Wall Street had a rough day\" on metonymy — se tarkoittaa oikeasti pörssiä.",
     "muutos, jälkeen", "nimi"),
    ("Revittää juurineen; temmata luonnollisesta ympäristöstä.",
     "Kiskoa jotakin (tai jotakuta) juurineen irti paikkaasta tai kulttuurista, johon he kuuluvat.",
     "Sota deracinated kokonaisen sukupolven ja hajotti perheet rajojen yli.",
     "pois, irti", "juuri"),
    ("Miellyttävästi soiva.",
     "Yksinkertaisesti kiva kuulla — euphonious sana, nimi tai lause vierii korvassa pehmeästi, miltei musikaalisesti.",
     "\"Murmuring brook\" on euphonious pieni fraasi, pehmeä ja helppo sanoa.",
     "hyvä, hyvin", "ääni, ääni"),
    ("Yleisesti oletettu tai luultu olevan.",
     "Laajalti uskottu todeksi, vaikka sitä ei ole oikeasti todistettu — jonkin \"supposed\" versio.",
     "Kirjeen putative kirjoittaja paljastui myöhemmin täydeksi vieraaksi.",
     "ajatella, pitää", "jonka luonne on"),
    ("Vastakeksitty sana tai ilmaus.",
     "Upouusi sana — juuri keksitty, ei vielä (tai tuskin) sanakirjassa.",
     "\"Doomscrolling\" alkoi neologism-sanana ja muuttui nopeasti arkikieleksi.",
     "uusi", "sana, puhe"),
    ("Vihainen tai äkäinen.",
     "Pahalla, ärtyisällä tuulella — nopea räjähtämään, niin kuin ennen uskottiin pernan hallitsevan luonnetta.",
     "Hän ampui splenetic vastauksen sähköpostiin sekunneissa sen luettuaan.",
     "perna (vihan paikka)", "jonka vallassa"),
    ("Taipuvainen moralisoimaan mahtailevasti tai teennäisesti.",
     "Rakastaa jakaa pieniä elämänoppeja itseään täynnä, aivan kuin jokainen lause olisi onnenkeksi.",
     "Hänen sententious maljapuheensa \"the true meaning of friendship\":stä sai kaikki vilkuilemaan kelloaan.",
     "mielipide, mietelause", "täynnä"),
    ("Liian puhelias, etenkin mitättömistä asioista.",
     "Ei vain lakkaa juttelemasta — jaarittelee pikkujutuista kauan sen jälkeen, kun muilla on aiheet loppu.",
     "Garrulous taksikuski kertoi koko elämäntarinansa ennen kuin olimme lähteneet lentoasemalta.",
     "jaarittelu, jaaritus", "taipuvainen"),
    ("Tyhmyys, hölmöys.",
     "Puhdasta tyhmyyttä — kommentti tai suunnitelma niin hölmö, ettei se juuri ansaitse vakavaa vastausta.",
     "Suunnitelman silkka fatuity kävi ilmi heti, kun he kokeilivat sitä.",
     "tyhmä, hölmö", "olemisen tila"),
    ("Puheen päättävä osa, usein tiivistävä.",
     "Puheen suuri lopetus — päätösjakso, jossa puhuja kokoaa kaiken ja iskee pointin kotiin.",
     "Peroration-kohdassa puolet yleisöstä oli jo jaloillaan.",
     "läpi, loppuun asti", "puhua, vedota"),
    ("Saman idean tarpeeton toisto eri sanoin.",
     "Sanoa sama kahdesti lisäämättä mitään uutta, kuten \"free gift\" tai \"end result.\"",
     "\"It is what it is\" on suosittu tautology niillä, jotka välttävät oikeaa selitystä.",
     "sama", "sana, puhe"),
    ("Hyvin harvojen sanojen käyttö; napakka puhe.",
     "Sanoa paljon vähällä — lyhyen, suoran vastauksen taito, nimetty Lakonian kuuluisan niukkasanaisista spartalaisista.",
     "\"Molon labe\" — \"come and take them\" — on historian kuuluisin laconism.",
     "Lakonian spartalainen", "tapa, käytäntö"),
    ("Miedot, yliselvennetyt ideat; alun perin mieto ruoka tai velli.",
     "Ohutta, vesitettyä ajattelua — sisältöä niin yksinkertaistettua ja turvallista, ettei siinä ole ravintoa mielelle.",
     "Poliitikon puhe oli enimmäkseen pabulumia: epämääräisiä lupauksia, joihin ei saanut otetta.",
     "ruokkia", "väline tai keino"),
    ("Unettava tai torkkua aiheuttava.",
     "Niin tylsä — tai niin kirjaimellisesti nukuttava — että se tekee uniseksi. Ajattele lämmintä maitoa tai kolmen tunnin budjettikokousta.",
     "Luentojen soporific humina sai puolet huoneesta taistelemaan silmiensä auki pitämiseksi.",
     "syvä uni", "tekevä, aiheuttava"),
    ("Liian imarteleva tai öljyinen käytökseltään.",
     "Niin sileän hurmaava, että se tuntuu liukkaalta — imartelua niin paksulti, että rasvan miltei tuntee.",
     "Unctuous myyjä kehui \"excellent taste\":äni ennen jokaista lisämyyntiä.",
     "voidella, öljytä", "täynnä"),
    ("Nopea löytämään vikoja, liian kriittinen mitättömissä asioissa.",
     "Nitpickaava vikaan asti — tyyppi, joka löytää ongelman kaikesta, vaikka sillä ei ole väliä.",
     "Hänen captious huomautuksensa raportista keskittyivät kokonaan pilkkuihin.",
     "tarttua, ottaa", "ansa, sofismi"),
    ("Velttona, henkisesti tai ruumiillisesti toimeton.",
     "Hidas ja puoliunessa, kuin karhu talviunilla — tuskin liikkuu, tuskin ajattelee.",
     "Toimisto vajosi torpid-tilaan elokuun raskaassa helteessä.",
     "olla tunnoton, olla veltto", "jonkin tilassa"),
    ("Hovimestari tai virkamies, joka hoiti keskiaikaista taloutta.",
     "Keskiajan versio henkilöstöpäälliköstä — luotettu virkamies, joka pyöritti herran taloutta ja tiluksia päivästä toiseen.",
     "Linnan seneschal hoiti kaiken satojen kirjanpidosta vieraslistaan.",
     "vanha, vanhempi", "palvelija"),
    ("Puhua tai kirjoittaa aiheesta pitkälti.",
     "Päästä kunnolla vauhtiin aiheesta — puhua tai kirjoittaa ja peittää se joka kulmasta.",
     "Kysy häneltä vintage-autoista, niin hän expatiate täyden tunnin.",
     "ulos", "tila"),
    ("Arvoton, mitätön; myös mitätön tai tehoton.",
     "Käytännössä ei minkään arvoinen — nugatory sopimuskohta on sellainen, joka ei oikeasti tee mitään.",
     "Oikeus julisti vanhan säännön nugatory, koska sitä ei ollut koskaan pantu täytäntöön.",
     "pikkuseikat, hölynpöly", "kuuluva"),
    ("Viisaus, terävä harkinta.",
     "Terävää, käytännöllistä viisautta — sellaista hyvää harkintaa, joka syntyy kokemuksesta, ei vain kirjoista.",
     "Vanhan kapteenin sagacity piti miehistön pois pulasta useammin kuin kerran.",
     "terävähajuinen, terävä", "ominaisuus"),
    ("Rähjä tai massat, halveksuen käytettynä.",
     "Ylpeilevä, sivuuttava sana \"the rabble\":lle tai tavalliselle väelle, käytetty halveksuen.",
     "Kreivi irvisti canaillelle, joka kerääntyi palatsin porteille.",
     "koira", "joukko, lauma"),
    ("Röyhkeä, nöyryyttävä kohtelu tai kieli.",
     "Julmaa, pilkallista kohtelua, jonka tarkoitus on nöyryyttää — sellainen herja, joka on tehty kirvelemään.",
     "Hän kesti vuosien contumelya kriitikoilta, ennen kuin hänen työnsä vihdoin tunnustettiin.",
     "kanssa, perin pohjin", "paisua (ylpeydestä)"),
    ("Epäillen tai paheksuen; sivusilmäys.",
     "Se sivusilmäys, jonka annat jollekin, johon et aivan luota — katse täynnä epäilyä.",
     "Opettaja katsoi askance epäilyttävän siistiä läksyä.",
     "kohti, luo", "vino, vinouma"),
    ("Tyhmä ihminen; pölkkypää.",
     "Vanhahtava, miltei hellä herja jollekulle, joka on hidas tai paksukalloinen — pölkkypää.",
     "\"You clodpate,\" hän nauroi, \"you've had the map upside down the whole time.\"",
     "maakokkare", "pää"),
    ("Laittaa liikkeelle tai toimintaan; motivoida.",
     "Olla kipinä, joka saa jotakin liikkumaan — olipa kyseessä kone, joka käynnistyy, tai ihminen, joka vihdoin toimii idean pohjalta.",
     "Pelko sopimuksen menettämisestä actuated koko joukkueen viikonlopun ylityöhön.",
     "tekeminen, ajaminen", "ajaa, tehdä"),
    ("Haltuun uskottujen varojen kavallus.",
     "Varastaa hiljaa rahaa, jonka hoitoon sinut on luotettu — kavallus vanhanaikaisessa takissa.",
     "Rahastonhoitajan peculation jäi huomaamatta lähes vuosikymmeneksi.",
     "yksityisomaisuus", "karja, rikkaus"),
    ("Ryhmä, jota pidetään kunniallisen seurapiirin laidalla.",
     "Loistokas mutta hämärä sosiaalinen alamaailma — ihmisiä, jotka elävät juuri \"respectable\" seurapiirin sääntöjen ulkopuolella.",
     "Romaani seuraa laulajatarta, joka luovii 1920-luvun kabareiden demi-mondeessa.",
     "puoli", "maailma, seura"),
    ("Yhä olemassa; ei sukupuuttoon kuollut tai tuhottu.",
     "Yhä täällä tänään — käytetään vanhoista asioista (käsikirjoituksista, lajeista, rakennuksista), jotka ovat onnistuneet säilymään.",
     "Vain kolme extant kappaletta ensipainoksesta tiedetään olevan olemassa.",
     "ulos", "seisoa"),
    ("Petollisuus; luottamuksen pettäminen.",
     "Syvä, tahallinen petos — luottamuksen rikkominen, jota toinen sai odottaa sinun pitävän.",
     "Kenraali ei koskaan antanut anteeksi vanhan ystävänsä perfidya neuvottelupöydässä.",
     "läpi, vastaan", "usko, luottamus"),
    ("Alueellinen murre, etenkin epästandardi.",
     "Erityinen, paikallinen tapa, jolla ihmiset puhuvat tietyllä seudulla — täynnä sanoja ja rytmejä, joita ulkopuolinen ei ehkä tavoita.",
     "Hänen isoäitinsä puhui yhä saaren patoisia perheillallisilla.",
     "karkea puhe, murre", "tassu — kömpelö puhe"),
    ("Erityinen oikeus, joka kuuluu henkilölle tai ryhmälle.",
     "Erioikeus, joka on sinun ja vain sinun — oikeus, joka tulee roolisi, asemasi tai statuksesi mukana.",
     "Perheen lomakohteen valinta on isoisän prerogative, ja kaikki tietävät sen.",
     "ennen", "kysyä, äänestää"),
    ("Rohkeus, uskaliaisuus; myös sitkeys tai kestävyys.",
     "Karkeaa, sisukasta kestävyyttä — hermoja mennä eteenpäin ja sitkeyttä jatkaa, kun kerran aloitat.",
     "Oikeaa hardihoodia vaadittiin solan ylittämiseen lumimyrskyssä ilman karttaa.",
     "rohkea, karaistunut", "tila, olotila"),
    ("Puhjeta kukkaan; myös kehittyä tai ilmestyä vähitellen.",
     "Avautua täyteen ilmaisuun — kuin kukka, joka aukeaa, tai idea, joka vihdoin tulee omakseen.",
     "Hänen hiljainen maalaustalenttinsa effloresced, kun hän sai oman ateljeen.",
     "ulos", "alkaa kukkia"),
    ("Painotettu naru pystysuoruuden määräämiseen; kuvainnollisesti, harkinnan mittapuu.",
     "Paino narussa, joka riippuu täysin suoraan alas — sillä tarkistetaan, onko jokin aidosti pystysuora — ja laajemmin mikä tahansa kiinteä mittapuu, johon kaikkea muuta verrataan.",
     "Hän käytti oman isoisänsä rehellisyyttä eräänlaisena plumb-linena jokaiseen päätökseen.",
     "lyijy", "naru, mitta"),
    ("Mielellään, vapaaehtoisesti (vanhahtava).",
     "Vanhahtava tapa sanoa \"gladly\" tai \"with pleasure.\"",
     "\"I would fain rest here a while,\" matkalainen huokaisi.",
     "iloinen, riemukas", "mielellään, vapaaehtoisesti"),
    ("Kova julkinen arvostelu tai häpeä.",
     "Julkista häpeää, jota kasataan näkyvästi jonkun päälle — häpeä, joka syntyy laajasta paheksunnasta.",
     "Skandaali toi julkisen opprobriumin koko firman ylle.",
     "vastaan", "häpeä, moite"),
    ("Terävän sarkastinen, pureva nokkeluudessa tai arvostelussa.",
     "Nokkeluutta, jolla on oikeat hampaat — mordant huomautus kirvelee juuri siksi, että se on niin osuvasti tähdätty.",
     "Hänen mordant elokuva-arvostelujaan ohjaajat pelkäsivät ja lukijat rakastivat.",
     "purra", "pureva, tekevä"),
    ("Muodollinen julistus, usein poliittinen tai sotilaallinen.",
     "Suuri, virallinen ilmoitus — yleensä sellainen, joka julistaa uuden hallituksen, kapinan tai merkittävän asetuksen.",
     "Kenraalin pronunciamento julisti uuden hallituksen aamunkoitteessa.",
     "eteen", "ilmoittaa"),
    ("Henkilö, jolla on pinnallista tietoa ja joka teeskentelee asiantuntijaa.",
     "Joku, joka on silmäillyt aiheen pinnan ja puhuu sitten kuin olisi kirjoittanut oppikirjan siitä.",
     "Päivällisten sciolist korjasi itsevarmasti pöydän oikeaa astrofyysikkoa.",
     "tietää", "diminutiivi — pieni tietäjä"),
    ("Henkinen taantuma vanhuudessa.",
     "Utuinen, unohteleva jakso korkeassa iässä, kun mielen terävyys alkaa himmetä.",
     "Dotageessaan hän kertoi samat kolme tarinaa joka käynnillä, joka kerta kuin uutena.",
     "höperehtiä, olla typerä", "tila tai tulos"),
    ("Tuulelta suojassa oleva puoli.",
     "Jonkin rauhallinen, suojaisa puoli — mäen, laivan, muurin — jossa tuuli ei aivan yllä luoksesi.",
     "Vaeltajat pystyttivät teltan harjanteen lee-sidelle päästäkseen puuskilta.",
     "suoja, turva", "kylki, sivu"),
    ("Torjua isku, kysymys tai argumentti.",
     "Lyödä jotakin sulavasti sivuun — miekanisku, kiusallinen kysymys tai syytös — tahdista putoamatta.",
     "Hän parried toimittajan kiperän kysymyksen helpolla vitsillä.",
     "torjua", "valmistautua, puolustaa"),
    ("Pahanhajuinen, myrkyllinen.",
     "Haiskahtaa miltei myrkylliseltä — haju niin paha, että hengittäminen tuntuu vaaralliselta.",
     "Mephitic haju nousi suosta auringon laskiessa.",
     "myrkyllinen höyry", "jonka luonne on"),
    ("Henkilö, joka on omistautunut ylellisyydelle ja nautinnolle.",
     "Joku, joka elää mukavuuden ja nautinnon vuoksi — hieno ruoka, pehmeät sängyt, helppo elämä — nimetty antiikin kreikkalaisen Sybariksen mukaan, joka oli kuuluisa yltäkylläisyydestään.",
     "Tosi sybarite, hän kieltäytyi kaikista hotellihuoneista ilman kylpyammetta.",
     "antiikin kreikkalainen ylellisyydestään kuuluisa kaupunki", "asukas"),
    ("Sivuuttaa tahallaan osa jostakin.",
     "Laittaa palapelin pala tahallaan sivuun, jotta voit keskittyä puhtaasti muuhun.",
     "Prescind kustannuksesta hetkeksi ja kysytään vain, toimiiko suunnitelma oikeasti.",
     "ennen, pois", "leikata"),
    ("Arvostella ankarasti; myös nylkeä iho.",
     "Revittää joku rikki kovalla arvostelulla — sanoin, aivan kuin nylkisit ihon kirjaimellisesti.",
     "Kriitikot excoriated jatko-osan, koska se petti kaiken, mitä fanit rakastivat alkuperäisessä.",
     "irti", "nahka, iho"),
    ("Vedota todisteena tai näyttönä.",
     "Tuoda esiin tosiasia tai esimerkki pointtisi tueksi — se, johon osoitat, kun joku kysyy \"what's your evidence?\"",
     "Asianajaja adduced kolme todistajaa asiakkaansa alibin tueksi.",
     "luo, kohti", "johtaa"),
    ("Matkat tai vaellukset, etenkin pitkät tai laajat.",
     "Pitkiä, harhailevia matkoja — sellaista laajaa vaellusta, joka vie kauas kotoa pitkäksi aikaa.",
     "Hänen peregrinations kolmen mantereen halki täyttivät kokonaisen hyllyn matkapäiväkirjoja.",
     "läpi", "pelto, maa (peregrinus: muukalainen)"),
    ("Kerjäläinen tai almuilla elävä.",
     "Joku, joka elää pyytämällä hyväntekeväisyyttä — historiallisesti tämä kuvasi myös munkkeja, jotka vannoivat köyhyyslupauksen ja elivät lahjoituksilla.",
     "Mendicant veljet eivät omistaneet mitään ja luottivat täysin kyläläisten hyvyyteen.",
     "kerjätä", "kerjäläinen"),
    ("Äärimmäisen antelias.",
     "Antelias suurella, miltei pröystäilevällä mittakaavalla — sellainen lahja, joka saa ihmiset hieman haukkomaan henkeään.",
     "Munificent lahjoitus rahoitti koko kirjaston uuden siiven.",
     "lahja, palvelus", "tekevä, antava"),
    ("Uupumus ravinnon puutteesta; myös elinvoiman puute.",
     "Heikko, tyhjä tila siitä, ettei ole saanut ruokaa tai polttoainetta — kirjaimellisesti nälästä, tai kuvainnollisesti siitä, ettei ole enää mitään millä kulkea.",
     "Piirityksen lopussa sotilaat olivat lähellä inanitionia.",
     "tyhjä, tyhjiö", "teko tai tulos"),
    ("Katkera, herjaava arvostelu.",
     "Arvostelua, joka on mennyt kauan reilun ohi ja muuttunut vihaiseksi, katkeraksi purkaukseksi.",
     "Verkkokommentit hajosivat puhtaaksi vituperationiksi minuuteissa.",
     "vika", "valmistaa, varustaa"),
    ("Vihamielinen, vahingollinen vaikutukseltaan.",
     "Toimii sinua vastaan, vaikkakin hiljaa — olosuhteet tai asenteet, jotka ovat epäystävällisiä etujesi kannalta.",
     "Uusi politiikka oli inimical pienyrityksille, vaikka se ei ollut tarkoitus.",
     "ei", "ystävä"),
    ("Omiaan herättämään kaunaa tai tyytymättömyyttä, usein epäreilujen vertailujen kautta.",
     "Tuomittu saamaan joku tuntemaan itsensä sivuutetuksi — yleensä siksi, että se asettaa ihmisiä tai asioita epäreilusti toisiaan vastaan.",
     "Sisarusten ranking \"who Mom loves best\":n mukaan on invidious peli, jota kenenkään ei pitäisi pelata.",
     "kateus", "katsoa (pahantahtoisesti)"),
    ("Alempiarvoinen tai -asemainen henkilö; alainen.",
     "Alempana komentoketjussa tai sosiaalisella tikapuilla — junioreita, jotka työskentelevät vaikutusvaltaisemman alaisuudessa.",
     "Nuorena subalternina hän otti käskyjä kauan ennen kuin koskaan antoi niitä.",
     "alla", "vuorotteleva, toinen"),
    ("Tuntea tai ilmaista voimakasta vihaa kohtaan.",
     "Inhota jotakin niin, että kiroat sen ääneen — puhdasta, äänekästä inhoa.",
     "Kyläläiset execrated veronkantajaa joka kerta, kun hänen kärrynsä vierivät kylän läpi.",
     "ulos", "pyhä (kirota pyhästä pois)"),
    ("Luonnollinen ulkokuori, kuten iho tai kuori.",
     "Luonnon oma suojaava kääre — iho, kuori, palko tai kuori, mikä tahansa, joka peittää ja suojaa elävää.",
     "Kilpikonnan kuori on huomattavan sitkeä integument.",
     "päällä, yli", "peittää"),
    ("Viaton, naiivi, lapsenomaista yksinkertaisuutta osoittava; \"disingenuous\":n vastakohta.",
     "Avoimen luottavainen ja hieman naiivi, ilman piilotettua agendaa — helppo sekoittaa \"ingenious\":een, joka tarkoittaa nokkelaa.",
     "Hänen ingenuous kysymyksensä — \"why would anyone lie about that?\" — paljasti, miten vähän kavaluutta hänessä oli.",
     "sisässä, syntyperäinen", "siittää (vapaana syntynyt, vilpitön)"),
    ("Liiallinen huoli pikkuyksityiskohdista tai säännöistä.",
     "Eksyminen pieniin sääntöihin ja isomman kuvan menettäminen — takertuminen pieneen pränttiin, josta kukaan muu ei välitä.",
     "Hänen pedantry Oxford-pilkuista suisti koko kokouksen raiteiltaan.",
     "lasten opettaja", "käytäntö tai ominaisuus"),
    ("Perusteellinen, huolellinen tarkastelu.",
     "Syvä, yhtään kiveä kääntämätön katsaus johonkin — jokaisen yksityiskohdan läpikäynti aidolla huolella.",
     "Vasta huolellisen perscrutationin jälkeen kirjanpidosta löytyi poikkeama.",
     "läpi, perin pohjin", "etsiä, tutkia"),
    ("Esittää vastalauseita; osoittaa haluttomuutta.",
     "Perääntyä kohteliaasti tai epäröidä sen sijaan, että lähtisi heti mukaan — pehmeä \"I'd rather not.\"",
     "Kun häntä pyydettiin allekirjoittamaan lukematta, hän demurred.",
     "pois, erilleen", "viivytellä"),
    ("Pinnallisesti uskottava mutta itse asiassa väärä.",
     "Kuulostaa vakuuttavalta ensi vilkaisulla, mutta hajoaa heti, kun sen oikeasti tarkistaa.",
     "\"Everyone's doing it\" on specious argumentti, joka ei kestä tarkastelua.",
     "ulkonäkö, ilme", "täynnä (näennäisen kaunis)"),
    ("Vilpitön, tekopyhä puhe, usein moralisoiva.",
     "Saarnaavaa puhetta, joka kuulostaa hyveelliseltä mutta jota ei tue mikään aito tunne — moraalista poseerausta autopilotilla.",
     "Hän oli kyllästynyt yrityksen cant-puheeseen \"family\":stä firmalta, joka ei koskaan antanut vapaata.",
     "laulaa (myöhemmin: laulava slangi)", "kerjäläisten kitinä, sitten tekopyhyys"),
    ("Rohkeutta vailla, pelkuri.",
     "Arka selkärangattomuuteen asti — liian peloissaan seistä edes silloin, kun se selvästi merkitsee.",
     "Hallituksen pusillanimous hiljaisuus antoi skandaalin kieriä käsistä.",
     "hyvin pieni", "henki, rohkeus"),
    ("Kettumainen; ovela, viekas.",
     "Ovela ja nokkela kuin kettu — nopeaälyinen, hieman salakavala, aina askeleen edellä.",
     "Hän virnisti vulpine hymyn heti bongattuaan porsaanreiän.",
     "kettu", "jonkin tai kaltaisen"),
    ("Yksi kerrallaan, järjestyksessä.",
     "Otettu tiukasti yksi kerrallaan, järjestyksessä — ei hypätä eteen, ei kahta kerralla.",
     "Tuomari käsitteli kunkin kahdestatoista vaateesta seriatim.",
     "rivi, jakso", "yksi kerrallaan"),
    ("Äärimmäinen säästäväisyys; kitsaus.",
     "Kitukuus rahan (tai sanojen tai voimavarojen) kanssa kauan järkevän säästäväisyyden ohi.",
     "Hänen parsimony oli legendaarista — hän käytti teepussit kolmeen kertaan.",
     "säästää, olla säästäväinen", "tila tai käytäntö"),
    ("Korjaus, etenkin tekstissä.",
     "Korjaus kirjoitukseen — oppinut säätö, joka korjaa virheen vanhassa tai tärkeässä tekstissä.",
     "Uusi laitos sisältää kymmeniä emendations alkuperäiseen käsikirjoitukseen.",
     "ulos", "virhe, erehdys"),
    ("Kohtuullinen syömisessä ja juomisessa.",
     "Tarkoituksellisen pidättyväinen ruoan ja juoman suhteen — ei koskaan liikaa, aina vähän lautaselle jätettynä.",
     "Hänen abstemious tapansa pitivät hänet terävänä kauan sen jälkeen, kun ikätoverit olivat hidastuneet.",
     "pois jostakin", "päihdyttävä juoma"),
    ("Kieliopillinen virhe tai etiketin rikkomus.",
     "Kömmähdys kieliopissa tai tavoissa — sellainen pieni virhe, joka saa saivartelijan irvistämään.",
     "\"Between you and I\" on yleinen solecism, joka saa kieliopin vartijat yhä säpsähtämään.",
     "Kilikian kaupunki, joka tunnettiin 'huonosta' kreikasta", "tapa, käytäntö"),
    ("Koskee ryhmän sisäistä konfliktia; molemminpuolisesti tuhoisa.",
     "Sisäinen riita, joka repii ryhmän sisältä — taistelu, jossa kaikki häviävät, koska se on perhe perhettä vastaan.",
     "Puolueen internecine kinastelu teki enemmän vahinkoa kuin mikään ulkopuolinen vastustaja olisi voinut.",
     "välillä, keskuudessa", "tappaa"),
    ("Välinpitämätön, huolimaton asenne.",
     "Olankohautus, josta on tehty koko persoonallisuus — välittää niin vähän asioista, jotka ennen merkitsivät, ettei mikään enää tunnu vaivan arvoiselta.",
     "Hänen pococurante asenteensa palkintogaalaan yllätti kaikki, jotka tiesivät, miten kovasti hän oli tehnyt töitä.",
     "vähän", "välittää"),
    ("Hämmentynyt, monimutkainen tilanne tai riita.",
     "Sotkuinen, sekava tilanne, josta on vaikea saada tolkkua — osin väärinkäsitystä, osin draamaa, kokonaan hämmennystä.",
     "Koko istumajärjestys-imbroglio alkoi yhdestä väärään paikkaan joutuneesta nimikortista.",
     "sisässä", "sotkea, hämmentää"),
    ("Uhkaava, uhkaileva.",
     "Kantaa erehtymätöntä uhan ilmaa — minatory katse tai kirje tekee hyvin selväksi, että jotakin pahaa voi seurata.",
     "Kirjeen minatory sävy teki vuokralaisen hermostuneeksi jo ennen kuin hän oli avannut kirjekuoren.",
     "uhata", "palveleva"),
    ("Voimakas julkinen arvostelu tai sanallinen herja.",
     "Äänekästä, julkista tuomitsemista — sellaista kirvelevää arvostelua, joka tapahtuu kaikkien nähden.",
     "Ilmiantaja kohtasi vuosien julkisen obloquyn, ennen kuin historia antoi hänelle oikeuden.",
     "vastaan", "puhua"),
    ("Äkillinen väkivaltainen purkaus, tunteen tai teon.",
     "Äkillinen, intensiivinen isku, joka valtaa kerralla — naurun, raivon tai yskän puuska, joka iskee kuin aalto.",
     "Hänet valtasi paroxysm naurua, jota hän ei osannut selittää kenellekään muulle huoneessa.",
     "tuolla puolen", "terävä, akuutti"),
    ("Lisätty ulkoisesta lähteestä, ei luontainen.",
     "Ruuvattu kiinni ulkopuolelta sen sijaan, että olisi rakennettu sisään alusta asti — lisä, ei ydinosa.",
     "Kommentti tuntuu adscititious, aivan kuin se olisi liimattu jo valmiiseen tekstiin.",
     "lisäksi, lisäksi", "hyväksyä, ottaa"),
    ("Tiedon puute, tietämättömyys.",
     "Yksinkertaista ei-tietämistä — aukko tiedossa, ilman siihen liitettyä arvostelua.",
     "Hän myönsi nesciencensa ranskalaisesta viinistä ja antoi sommelieerin valita.",
     "ei", "tietää"),
    ("Liiallinen kiinnostus seksuaalisia asioita kohtaan.",
     "Yli-innokasta, tuijottavaa uteliaisuutta kaikkea pikanttia kohtaan — kiinnostusta, joka on mennyt terveen ohi uteliaaksi.",
     "Tabloidin prurience parin yksityiselämästä rajasi pakkomielteiseen.",
     "kutittaa, kaivata", "tila"),
    ("Nokeinen, pimeä, samea.",
     "Tumma ja savuinen näköinen, aivan kuin kaikki olisi ohuen noen peitossa.",
     "Fuliginous utu riippui tehdaskaupungin yllä hämärässä.",
     "noki", "täynnä"),
    ("Kieltää tai väittää vastaan.",
     "Puhua suoraan vastaan sitä, mitä toinen on sanonut — sanoa \"that's not so.\"",
     "Kukaan ei uskaltanut gainsay vanhan kapteenin kertomusta myrskystä.",
     "vastaan", "puhua"),
    ("Laiskuus, joutilaisuus (latinasta).",
     "Vanha latinalainen sana puhtaalle laiskuudelle — laahaaminen siinä, ettei halua tehdä mitään.",
     "Munkit saarnasivat ignaviaa vastaan yhtenä sielun hiljaisista vaaroista.",
     "ei", "kiireinen, ahkera"),
    ("Kilpi, jossa on vaakuna.",
     "Kilvenmuotoinen tunnus, joka näyttää suvun vaakunan — sen heraldisen \"nameplate\":n.",
     "Suvun escutcheon riippuu yhä vanhan kartanon etuoven yläpuolella.",
     "kilpi", "diminutiivi / esine"),
    ("Vanhentunut, vanhentunut tai iän vuoksi eläkkeelle siirretty.",
     "Hyödyllisen huippunsa ohi ja laitumelle laitettu — liian vanhanaikainen tai kulunut jatkamaan hommaa.",
     "Superannuated tulostin vaihdettiin vihdoin viidentoista vuoden paperitukosten jälkeen.",
     "tuolla puolen", "vuosi"),
    ("Korvikkeet, etenkin lääketieteessä.",
     "Korvaavia lääkkeitä, kun oikeaa hoitoa ei ole saatavilla — lääketieteellisiä sijaisia pohjimmiltaan.",
     "Sodanaikaiset lääkärit turvautuivat usein succedaneaan, kun oikeat lääkkeet loppuivat.",
     "sijasta", "mennä, väistyä"),
    ("Kerskailevaa, pöyhkeilevää puhetta.",
     "Suurta, puhkuvaa kerskailua — äänekästä puhetta omasta suuruudesta, joka on enimmäkseen tyhjää ilmaa.",
     "Hänen rodomontadensa siitä, että hän \"single-handedly\" pelasti projektin, ei huijannut ketään, joka oli oikeasti paikalla.",
     "kerskaileva ritari teoksessa Orlando Furioso", "teko, näytös"),
    ("Käyttää kikkaa tai petosta jonkin saavuttamiseksi.",
     "Kiemurrella tavoitteeseen salakavalilla tempuilla reilun pelin sijaan.",
     "Hän chicaned itsensä diiliin pienellä präntillä täytetyllä sopimuksella.",
     "saivarrella, huijata", "kikka; myöhemmin jyrkkä mutka"),
    ("Oppimisen tai tiedon puhdas tai abstrakti tiede, usein matematiikka.",
     "Oppiminen puhtaimmassa, abstrakteimmassa muodossaan — tiedon syvä rakenne itse, etenkin matemaattinen laji.",
     "Filosofi unelmoi universaalista mathesiksesta, joka voisi yhdistää jokaisen tieteenalan.",
     "oppia", "oppimisen teko"),
    ("Liian kiinnostunut muodollisista säännöistä tai mitättömistä yksityiskohdista.",
     "Liian tiukka pikkujutuista — korjaa pieniä teknisiä seikkoja, jotka eivät oikeasti muuta mitään.",
     "Tuntui hieman pedantic väitellä \"who\":sta versus \"whom\":sta tekstiviestissä.",
     "lapsenopas, ohjaaja", "jonka tapa on"),
    ("Välähtävä, kimalteleva valo.",
     "Nopea, kimalteleva valonvälähdys — ajattele auringonvaloa veden pinnalla tai timanttia, joka nappaa valon.",
     "Kattokruunun coruscation sirotteli valoa jokaiseen tanssisalin nurkkaan.",
     "kimaltaa, välähtää", "teko"),
    ("Aloittelija, noviisi.",
     "Joku upouusi taidossa tai alalla — yhä opettelemassa alkeita, ei vielä asiantuntija.",
     "Jopa tyro-shakinpelaaja huomaa sen kömmähdyksen.",
     "rekryytti, noviisi", "raaka nuori sotilas"),
    ("Äärimmäisen huono, inhottava.",
     "Huono tavalla, joka ansaitsee aitoa inhoa — ei vain \"mediocre,\" vaan todella inhottava.",
     "Arvostelija kutsui jatko-osaa execrableksi, ja lipputulot olivat samaa mieltä.",
     "kirota", "arvoinen, kykenevä tulemaan"),
    ("Verenpunainen väriltään.",
     "Syvä, eloisa punainen — tuoreen veren väri, Shakespearen Macbethin kuuluisasti käyttämä.",
     "Auringonlasku käänsi koko taivaan incarnadine hehkuun.",
     "sisään", "liha (lihanpunainen)"),
    ("Pieni rako tai tila asioiden välissä.",
     "Pieni väli, joka on helppo sivuuttaa — lattialautojen rako, aikataulun aukko.",
     "Rikkakasvit puskeutuivat jokaisesta intersticestä vanhalla tiilipolulla.",
     "välillä", "seisoa"),
    ("Kriittisiä tai moittivia huomautuksia.",
     "Teräviä, paheksuvia kommentteja — sellaista arvostelua, jossa on hieman nuhteleva sävy.",
     "Professorin animadversions esseestä täyttivät marginaalit punaisella musteella.",
     "mieli", "kääntyä kohti"),
    ("Mahdoton kumota, kiistämätön.",
     "Niin vankasti todistettu, ettei siitä voi kiistellä — asia on yksinkertaisesti suljettu.",
     "DNA-todiste oli irrefragable, ja oikeudenkäynti oli ohi tunnissa.",
     "ei", "vastustaa, panna vastaan"),
    ("Monimutkaisuus, mutkikkuus; myös sisäänpäin kiertyminen.",
     "Sotkuista, itseensä kiertynyttä monimutkaisuutta — asioita kiedottu niin tiukkaan, että niitä on vaikea irrottaa.",
     "Juonen involution jätti puolet yleisöstä yrittämään sen selvittämistä loppumusiikin jälkeen.",
     "sisään, sisäänpäin", "kieriä, kääntyä"),
    ("Voima tai ponnistus, kuten \"by dint of.\"",
     "Silkkaa ponnistusta tai voimaa — elää nykyään enimmäkseen fraasissa \"by dint of.\"",
     "Hän pääsi kokeesta by dint of silkalla, itsepäisellä harjoittelulla.",
     "isku, täräys", "voimalla"),
    ("Liitetty tapilla; tiukasti yhteen sovitettu.",
     "Lukittu yhteen vanhanaikaisen puusepän tapaan — pala, joka liukuu tiukasti juuri sille leikattuun koloon.",
     "Vanhan ladon palkit oli mortised yhteen ilman yhtään naulaa.",
     "kolo, reikä", "puraisu, ote"),
    ("Erittäin osuva, sopiva.",
     "Juuri oikea hetkeen — huomautus, lainaus tai esimerkki, joka osuu täydellisesti nappiin.",
     "Hänen apposite huomautuksensa tiivisti koko keskustelun yhteen lauseeseen.",
     "luo", "sijoittaa"),
    ("Pehmeästi hehkuva tai välkkyvä (valo); myös kevyt nokkeluus.",
     "Hehkuu lempeästi mieluummin kuin leimuaa — pehmeä, välkkyvä valo, tai nokkeluus, joka on leikkisää pikemmin kuin terävää.",
     "Kynttilänvalo heitti lambent hehkun vanhan ruokasalin ylle.",
     "nuolla", "tekevä (valo joka 'nuolee')"),
    ("Uskonnollinen erakko, joka elää yksinäisyydessä.",
     "Joku, joka vetäytyy maailmasta kokonaan elämään yksin rukouksessa ja pohdinnassa.",
     "Anchorite asui pienessä kirkkoon liitetyssä sellissä yli kolmekymmentä vuotta.",
     "takaisin, pois", "vetäytyä"),
    ("Sammuttaa jano; sammuttaa.",
     "Tyydyttää kaipuu täysin — useimmiten jano, mutta kuvainnollisesti mikä tahansa syvä tarve.",
     "Yksi kylmä lasillinen vettä slaked hänen janonsa pitkän vaelluksen jälkeen.",
     "veltto, löysä", "löysätä, tyynnyttää"),
    ("Neulanmuotoinen.",
     "Pitkä, ohut ja terävä kuin neula — männynneulasen tai terävän pienen kristallin muoto.",
     "Männyt on helppo tunnistaa acicular lehdistään.",
     "neula", "pieni"),
    ("Elinvoimasta uupunut, heikko, ylisivistynyt.",
     "Kulunut ja pehmeä — menettänyt alkuperäisen voimansa tai ponnen liiallisen mukavuuden tai hienostuneisuuden kautta.",
     "Kriitikot kutsuivat kerran rohkeaa lehteä effete, sen varhaisten rohkeiden vuosien varjoksi.",
     "ulos", "hedelmällinen, joka on kantanut"),
    ("Lisäke tai pienempi liitännäinen esine tai oikeus.",
     "Pieni lisä, joka tulee isomman mukana — lisävarusteet ja liitteet, jotka kuuluvat pääasiaan.",
     "Vuokrasopimus sisälsi autotallin ja kaikki sen appurtenances.",
     "luo", "kuulua"),
    ("Peitellä tai vähätellä virhettä.",
     "Silottaa virhe pehmeillä sanoilla, jotta se kuulostaa pienemmältä kuin se on.",
     "Hän yritti gloze myöhästyneen määräajan yli epämääräisellä puheella \"unforeseen challenges\":sta.",
     "glossa, selitys", "kommentoida — sitten silottaa"),
    ("Varhaisessa vaiheessa, vasta alkamassa.",
     "Vasta alkamassa näkyä — aivan ensimmäinen, tuskin näkyvä vaihe jostakin suuremmasta, joka on tulossa.",
     "Lääkärit nappasivat taudin incipient merkit, ennen kuin se ehti levitä.",
     "päälle, sisään", "ottaa (ottaa vastaan, aloittaa)"),
    ("Luova inspiraatio, etenkin jumalallinen.",
     "Äkillinen inspiraation puuska, joka tuntuu itseäsi suuremmalta — aivan kuin idea olisi puhallettu sinuun jostakin muualta.",
     "Runoilija kuvasi koko teoksen saapuneen yhdessä afflatus-puuskassa kello kolme yöllä.",
     "luo, päälle", "puhaltaa (päällepuhallus)"),
]
