# Azerbaijani rows: (definition, friendly, exampleGloss, root1, root2)
ROWS = [
    ("Şirinləşdirmək və ya təmizləmək; bir şeydən sərtliyi götürmək.",
     "Acını, zəhəri çıxarmaq — hərfən şirinləşdirmək, ya da məcazi olaraq sərt bir fikri yumşaldıb udulası etmək.",
     "Redaktor, sərt rəyi çapdan əvvəl yumşaltdı.",
     "çölə, köklü", "şirin"),
    ("Həddindən artıq və ya süni dindar.",
     "Dini bağlılığı göstəriş kimi duran, səmimi imandan çox tamaşa olan şəxsi təsvir edir.",
     "Xütbə zamanı dindarlıq satan ah çəkmələri sıranın qalanını bezdirdi.",
     "təqva, borc", "xarakterinə malik"),
    ("Qrammatik quruluşdan doğan qeyri-müəyyənlik — iki cür oxunan cümlə.",
     "Qrammatikası düzgün, amma tamamilə fərqli iki yolla oxuna bilən cümlə, məsələn \"Visiting relatives can be tiring\".",
     "\"Visiting relatives can be tiring\" klassik bir məna ikiliyidir — yorucu olan qohumlar, yoxsa onları ziyarət etmək?",
     "hər ikisi, iki tərəfdə", "atmaq"),
    ("İti, kəsici, düz nöqtəyə kəsən.",
     "Söz yığınını kəsir — kəskin bir irad və ya zəka, boş söz olmadan işin canına tez çatır.",
     "Onun kəskin tənqidi filmin süjet boşluqlarına gizlənməyə yer qoymadı.",
     "kəsmək", "etmək, keyfiyyətinə malik"),
    ("Yenicə başlayan; erkən və ya ibtidai mərhələdə.",
     "Hələ açılış anlarında — yenicə forma almağa başlamış plan, hiss və ya proses.",
     "Müqavilənin başlanğıc mərhələləri ümidverici idi, amma çox detallar açıq qalmışdı.",
     "başlamaq, girişmək", "yönəlmə meyli"),
    ("Birini yüksək tərifləyən rəsmi nitq və ya yazı.",
     "Tam, rəsmi bir tərif — parlaq bir mədhiyyə, ya da nailiyyətləri damdan oxuyan nitq düşünün.",
     "Təqaüdə çıxan professoru ən yaxın tələbələri bir mədhiyyə ilə yola saldılar.",
     "hamısı", "yığıncaq, toplanış"),
    ("Mücərrəd nəzəriyyənin əksi olaraq real varlıq və ya faktiki olmaqla bağlı.",
     "Şeylərin həqiqətən necə mövcud olduğu haqqında, təkcə onlar haqqındakı fikir və ya nəzəriyyələr deyil.",
     "Filosoflar rəqəmlərin varlıqsal statusu olub-olmadığını, yoxsa yalnız zehnimizdə durduğunu müzakirə edir.",
     "varlıq, mövcud olan", "ilə bağlı"),
    ("Meyvə vermək, ya da məhsuldar olmaq.",
     "Nəhayət bəhrəsini vermək — səy, fikir və ya yatırımı toxumdan faydalı bir şeyə böyütmək.",
     "İllərlə sakit tədqiqat nəhayət bar verib işlək bir peyvəndə çevrildi.",
     "meyvə", "etmək, səbəb olmaq"),
    ("Bir şeyi həqiqətən baş verməmişdən əvvəl bitmiş kimi qabaqlamaq və ya göstərmək.",
     "Ədəbi tələsmək — gələcək hadisəni sanki bitmiş kimi təsvir edərək nöqtəni daha bərk vurmaq.",
     "Generalın \"qələbə\" üçün vaxtından əvvəl qaldırdığı badə döyüşdən tam bir həftə əvvələ düşdü.",
     "əvvəl", "almaq, tutmaq"),
    ("Hava təzyiqi ilə işləyən; həm də ruh və ya nəfəslə bağlı.",
     "Adətən \"sıxılmış hava ilə işləyən\" deməkdir — ruh və ya nəfəslə də bağlı ola bilər.",
     "Avtobus səkiyə yaxınlaşanda hava əyləcləri fısıldadı.",
     "külək, nəfəs, ruh", "aid"),
    ("Allahı və ya ilahini müsbət ifadələrlə təsvir etmək — apofatikin əksi.",
     "Allahın nə olmadığını yox, nə olduğunu deyərək danışmaq — \"God is love\" kimi.",
     "Təsdiqi ilahiyyat Allahdan sevən, ədalətli və mərhəmətli deyə inamla danışır.",
     "aşağı, görə", "danışmaq, demək"),
    ("Etibar və ya imana əsaslanan; həm də sabit istinad nöqtəsi kimi işlənir.",
     "Etibar edib sonra lövbər etdiyiniz şey — dayaq nişanı, hər şeyin ölçüldüyü sabit nöqtədir.",
     "Ölçüçülər sahəni xəritələməzdən əvvəl ana qayaya dayaq nişanı qoydular.",
     "etibar etmək", "etibar, inam"),
    ("Şərin varlığı qarşısında Allahın yaxşılığının müdafiəsi.",
     "Qədim sualı cavablamağa cəhd: \"Allah yaxşıdırsa, niyə şər var?\"",
     "Dissertasiyası teodiseya mövzusunu Əyyub Kitabı prizmasından araşdırdı.",
     "tanrı", "ədalət"),
    ("Qarşılıqlı içəridə durma — Üçlük şəxslərinin bir-birinin içində var olmasına dair ilahiyyat termini.",
     "Hər hissənin digərlərini tam ehtiva etdiyi və ehtiva olunduğu üç-birdə duruş üçün ilahiyyat sözü.",
     "Qarşılıqlı içkinlik təlimi Ata, Oğul və Ruhun necə ayrı, amma ayrılmaz olduğunu izah etməyə çalışır.",
     "ətrafında", "getmək, gəzmək"),
    ("Birinə fayda verən və ya əks olunan nəticə doğurmaq.",
     "Tərif (və ya qınaq) məsula geri sıçrayanda — adınıza yazılan yaxşılıqlar dönüb sizi mükafatlandırır.",
     "Komandanın uğuru sakit və zəhmətkeş məşqçisinin hesabına yazılacaq.",
     "geri, yenə", "dalğa"),
    ("Qaçınılmaz və ya qaçıla bilinməyən.",
     "Nə etsəniz də olacaq — qaçılmaz bir nəticədən burulub çıxılmaz.",
     "Qocalıq hər kəsə gəlir; bu sadəcə qaçılmazdır.",
     "deyil", "çıxmaq üçün çabalamaq"),
    ("Dolayı, sözü uzadan ifadə işlətmək, birbaşa forma əvəzinə.",
     "Sözlə uzun yol — \"decide\" demək əvəzinə \"make a decision\" demək kimi.",
     "Onun dolayı e-məktubları üç abzasda dediyini bir sətirdə deyə bilərdi.",
     "ətrafında", "bildirmək, danışmaq"),
    ("Zehin kütlüyü və ya süstlük.",
     "Düşünməyin şirədə yerimək kimi gəldiyi dumanlı, ağır zehin halı.",
     "Nahardan dərhal sonra sinfə bir süstlük dalğası dəydi.",
     "küt, kəsərsiz", "hal və ya keyfiyyət"),
    ("Əlverişsiz; uğursuz əlamət.",
     "Pis nişanə — hələ başlamamış şəraitin və ya vaxtın əleyhinizə işləməsi.",
     "Boz səma və ölü akkumulyator səfərə uğursuz bir başlanğıc verdi.",
     "deyil", "əlverişli, lütfkar"),
    ("Sousda qaynadılmış və ya bişmiş ət — düzgün yazılışı \"fricasseed\".",
     "Öz sousunda yavaş-yavaş bişib yumşalana qədər kəsilmiş ət üçün isti, köhnə mətbəx sözü.",
     "Nənənin souslu bişmiş toyuğu hər bazar axşam yeməyinin ulduzu idi.",
     "qızartmaq", "sındırmaq (parçalara)"),
    ("Süni və ya daha aşağı keyfiyyətli əvəz.",
     "Həqiqətin yerini tutan saxta — işi görür, amma hər kəs əsl olmadığını bilir.",
     "Müharibə dövrü alıcılar qovrulmuş hindibadan saxta qəhvə ilə kifayətləndi.",
     "çölə, əvəzetmə prefiksi", "qoymaq, yerləşdirmək"),
    ("Mücərrəd bir ideyanı konkret bir şeymiş kimi qəbul etmək.",
     "İdeyanı real və bərk hiss etdirmək — \"the economy\" kimi bulanıq şeyi göstərilə bilən cisimə çevirmək.",
     "Bir millətin \"ruhunu\" öz varlığı kimi adlandırmaq, əslində milyonlarla fərdi seçim olan şeyi şeyləşdirir.",
     "şey", "etmək"),
    ("Ustalıqla qaçdı və ya yayındı.",
     "Təmizcə sıyrılmaq — tutulmağı, sualı və ya cavabı hiyləgərcəsinə və ya tük qədər yayındırmaq.",
     "Cavab saatlarla ondan yayındı, ta duşda birdən yerinə oturana qədər.",
     "çölə, uzağa", "oynamaq"),
    ("Şübhə, çaşqınlıq və ya həll olunmamış ziddiyyət ifadə edən.",
     "Düşüncənin həqiqi çıxılmazında — tənbəllikdən yox, sualın özü səliqəli cavabı rədd etdiyi üçün.",
     "Sokrat dialoqlarını tez-tez çıxılmaz bir tonda bitirər, cavabdan çox sual buraxardı.",
     "olmadan", "keçid, yol"),
    ("Bir şeyi bağlı terminlə adlandıran söz sənəti, məs. hökmdar üçün \"the crown\".",
     "Əsl şeyin yerinə bağlı söz işlətmək — idarəni nəzərdə tutaraq \"the White House announced\" demək.",
     "\"Wall Street had a rough day\" bir ad dəyişməsidir — əslində birja pis gün keçirdi deməkdir.",
     "dəyişiklik, sonra", "ad"),
    ("Kökündən qoparmaq; təbii mühitindən ayırmaq.",
     "Bir şeyi (və ya birini) kökündən çəkib mənsub olduğu yerdən və ya mədəniyyətdən ayırmaq.",
     "Müharibə bütöv bir nəsli kökündən qopardı, ailələri sərhədlərin o üzünə səpələdi.",
     "uzağa, qopuq", "kök"),
    ("Qulağa xoş gələn.",
     "Sadəcə dinləməsi gözəl — qulağa xoş gələn bir söz, ad və ya cümlə az qala musiqi kimi sürüşür.",
     "\"Murmuring brook\" qulağa xoş gələn kiçik bir ifadədir, yumşaq və deməsi asan.",
     "yaxşı, gözəl", "səs, ün"),
    ("Adətən fərz edilən və ya belə sanılan.",
     "Sübut olunmasa da genişcə doğru qəbul edilən — \"supposed\" versiyası.",
     "Məktubun ehtimal olunan müəllifi sonradan tamamilə yad çıxdı.",
     "düşünmək, saymaq", "təbiətinə malik"),
    ("Yenicə uydurulmuş söz və ya ifadə.",
     "Təzə-təzə söz — yenicə icad, hələ (və ya az qala) lüğətdə yox.",
     "\"Doomscrolling\" yeni bir söz kimi başladı və tez gündəlik jarqon oldu.",
     "yeni", "söz, nitq"),
    ("Qəzəbli və ya əsəbi.",
     "Pis, əsəbi əhval — bir vaxtlar qəzəbi dalağın idarə etdiyinə inanıldığı kimi tez partlayır.",
     "E-məktubu oxuduqdan saniyələr içində hirsli bir cavab göndərdi.",
     "dalaq (qəzəb yeri)", "təsirə məruz"),
    ("Təkəbbürlü və ya süni şəkildə əxlaq dərsi verməyə meyilli.",
     "Hər cümlə fal peçenyesiymiş kimi özündən razı həyat dərsləri paylamağı sevir.",
     "\"Dostluğun həqiqi mənası\" üzərinə moizəçi badəsi hər kəsin saatına baxmasına səbəb oldu.",
     "rəy, hikmətli söz", "dolu"),
    ("Xüsusən xırda şeylər haqqında həddindən artıq danışqan.",
     "Söhbəti kəsmir — başqaları sözü tükətdikdən çox sonra da xırda şeyləri boşboğazlıq edir.",
     "Danışqan taksi sürücüsü aeroportdan çıxmamış bütün həyatını danışdı.",
     "boşboğazlıq etmək", "meylli"),
    ("Axmaqlıq, cəfəngiyat.",
     "Sadə axmaqlıq — ciddi cavabı haqq etməyəcək qədər gülünc irad və ya plan.",
     "Planın düpədüz axmaqlığı sınadıqları anda üzə çıxdı.",
     "axmaq, gülünc", "olma halı"),
    ("Nitqin bağlanış hissəsi, çox vaxt xülasə edir.",
     "Nitqin böyük finalı — natiqin hər şeyi toplayıb nöqtəni vurduğu bağlanış.",
     "Yekun sözə gələndə dinləyicinin yarısı ayağa qalxmışdı.",
     "boyunca, sonadək", "danışmaq, müdafiə etmək"),
    ("Eyni fikrin fərqli sözlərlə lazımsız təkrarı.",
     "Yeni heç nə qatmadan eyni şeyi iki dəfə demək — \"free gift\" və ya \"end result\" kimi.",
     "\"It is what it is\" həqiqi izahdan qaçanların sevdiyi tavtologiya nümunəsidir.",
     "eyni", "söz, nitq"),
    ("Çox az söz işlətmə; qısa nitq.",
     "Çox azla çox demək — Lakoniya spartalılarının məşhur qısalığından adını alan qısa, sərt cavab sənəti.",
     "\"Molon labe\" — \"gəlin və götürün\" — tarixin ən məşhur lakonik sözüdür.",
     "Lakoniya spartalısı", "adət, tərz"),
    ("Dadsız, həddindən artıq sadələşdirilmiş ideyalar; əslində dadsız yemək və ya sıyıq.",
     "Seyrəldilmiş düşüncə — zehin üçün qida dəyəri qalmayacaq qədər sadələşdirilmiş, təhlükəsiz məzmun.",
     "Siyasətçinin nitqi əsasən boş söz idi: tutula bilməyən qeyri-müəyyən vədlər.",
     "yemləmək", "vasitə və ya alət"),
    ("Yuxu və ya süstlük gətirən.",
     "Darıxdırıcı — və ya hərfən sakitləşdirici — olacaq qədər yuxuya çəkir. İlıq süd, ya da üç saatlıq büdcə iclası düşünün.",
     "Mühazirənin yuxugətirici uğultusu otağın yarısını gözünü açıq saxlamağa məcbur etdi.",
     "dərin yuxu", "etmək, səbəb olmaq"),
    ("Həddindən artıq yaltaq və ya yağlı tərzli.",
     "Sürüşkən gələcək qədər hamar cazibədar — yağlılığı az qala hiss ediləcək qədər qalın yaltaqlıq.",
     "Yaltaq satıcı hər əlavə satışdan əvvəl \"mükəmməl zövqümü\" tərifləməyə davam etdi.",
     "yağ sürmək, məsh etmək", "dolu"),
    ("Qüsur axtarmağa tez, xırda şeylərə həddindən artıq tənqidi.",
     "Tükü tükdən ayırmağa varan — həqiqətən əhəmiyyəti yoxkən hər şeydə problem tapan şəxs.",
     "Hesabatdakı qüsur axtaran qeydləri tamamilə vergül yerinə fokuslanmışdı.",
     "tutmaq, almaq", "tələ, safsəta"),
    ("Ağır, zehni və ya bədənən hərəkətsiz.",
     "Qış yuxusundakı ayı kimi yavaş və yarıyuxulu — az qala tərpənmir, az qala düşünmür.",
     "Avqustun ağır istisində ofis süstləşdi.",
     "keyimək, ağırlaşmaq", "halında"),
    ("Orta əsr evini idarə edən kətxuda və ya məmur.",
     "Orta əsr versiyası bir heyət rəisi — lordun evini və mülkünü gündəlik idarə edən etibarlı məmur.",
     "Qalanın mülk müdiri məhsul dəftərindən qonaq siyahısına hər şeyi idarə edirdi.",
     "yaşlı, böyük", "xidmətçi"),
    ("Bir mövzuda uzun-uzadı danışmaq və ya yazmaq.",
     "Mövzuya həqiqətən dalmaq — hər bucaqdan dayanmadan danışmaq və ya yazmaq.",
     "Ona klassik maşınları soruşun, düz bir saat ətraflı danışar.",
     "çölə", "fəza"),
    ("Dəyərsiz, xırda; həm də etibarsız və ya təsirsiz.",
     "Əsasən heç bir dəyəri yox — müqavilədəki hökmsüz maddə əslində heç nə etmir.",
     "Məhkəmə köhnə nizamnaməni hökmsüz saydı, çünki heç tətbiq olunmamışdı.",
     "xırda-xuruş, cəfəng", "aid"),
    ("Müdriklik, iti mühakimə.",
     "İti, praktik müdriklik — yalnız kitabdan yox, təcrübədən gələn yaxşı mühakimə.",
     "Qoca kapitanın uzaqgörənliyi ekipajı bir dəfədən çox beladan qorudu.",
     "iti qoxulu, zirək", "keyfiyyəti"),
    ("Aşağılayaraq işlədilən avam və ya kütlə.",
     "\"Ayaq takımı\" və ya adi insanlar üçün təkəbbürlü, xor baxan söz.",
     "Qraf, saray qapısının xaricində toplanan ayaqtakımına xor baxdı.",
     "it", "kollektiv, sürü"),
    ("Təkəbbürlü, alçaldıcı rəftar və ya dil.",
     "Utandırmaq üçün qurulmuş zalım, xor rəftar — ağrıtsın deyə qurulmuş təhqir.",
     "Əsəri tanınmazdan əvvəl tənqidçilərdən illərlə təhqir çəkdi.",
     "ilə, köklü", "şişmək (qürurla)"),
    ("Şübhə və ya bəyənməmə ilə; yan baxış.",
     "Pek etibar etmədiyiniz şeyə atdığınız yan baxış — şübhə dolu bir baxış.",
     "Müəllim şübhəli dərəcədə təmiz tapşırığa çəp baxdı.",
     "ə, doğru", "əyri, yanlı"),
    ("Axmaq şəxs; küt kəllə.",
     "Bir az qalın kəlləli biri üçün köhnə üsul, az qala mehriban təhqir — küt kəllə.",
     "\"Səni kütbeyin,\" güldü, \"xəritə bunca vaxt tərs dururdu.\"",
     "torpaq parçası", "baş"),
    ("Hərəkətə və ya əmələ keçirmək; həvəsləndirmək.",
     "Bir şeyi hərəkətə gətirən qığılcım olmaq — maşının açılması, ya da şəxsin nəhayət fikir üzərinə əmələ keçməsi.",
     "Müqaviləni itirmək qorxusu bütün komandanı hərəkətə gətirib həftəsonu işinə saldı.",
     "etmə, sürmə", "sürmək, etmək"),
    ("Əmanət edilən vəsaitin mənimsənilməsi.",
     "Sizə əmanət edilən pulu sakitcə oğurlamaq — köhnə palto geymiş mənimsəmə.",
     "Xəzinədarın mənimsəməsi az qala on il fərq edilmədi.",
     "şəxsi mülk", "mal-qara, sərvət"),
    ("Nüfuzlu cəmiyyətin kənarında görülən qrup.",
     "Parlaq, amma qaranlıq sosial yeraltı — \"nüfuzlu\" cəmiyyət qaydalarının elə kənarında yaşayanlar.",
     "Roman 1920-lər kabarelərinin yarım aləmində yolunu tapan bir müğənnini izləyir.",
     "yarı", "dünya, cəmiyyət"),
    ("Hələ mövcud olan; nəsli kəsilməmiş və ya məhv edilməmiş.",
     "Bu gün hələ duran — sağ qalmağı bacarmış köhnə şeylər (əlyazma, növ, bina) üçün.",
     "İlk çapın günümüzə çatan yalnız üç nüsxəsi bilinir.",
     "çölə", "durmaq"),
    ("Aldatma; etibar xəyanəti.",
     "Dərin, qəsdən xəyanət — birinin haqlı olaraq gözlədiyi etibarı qırmaq.",
     "General danışıq masasında köhnə dostunun xəyanətini heç bağışlamadı.",
     "içindən, qarşı", "iman, etibar"),
    ("Regional ləhcə, xüsusən standart olmayan.",
     "Müəyyən bir yurdda insanların özünəməxsus danışıq tərzi — yadın tuta bilməyəcəyi söz və ritmlərlə dolu.",
     "Nənəsi ailə yeməklərində hələ adanın yerli şivəsində danışırdı.",
     "qaba nitq, ləhcə", "pəncə — yöndəmsiz danışıq"),
    ("Bir şəxsə və ya qrupa məxsus xüsusi hüquq.",
     "Yalnız sizin olan imtiyaz — rol, vəzifə və ya statusla gələn hüquq.",
     "Ailənin tətil yerini seçmək babanın imtiyazıdır, hər kəs bunu bilir.",
     "əvvəl", "soruşmaq, səs vermək"),
    ("Cəsarət, cürət; həm də dözüm və ya dözümlülük.",
     "Kobud, ürəkli müqavimət — irəli getmə cəsarəti və getdikdən sonra davam etmə sərtliyi.",
     "Xəritəsiz qar fırtınasında aşırımı keçmək həqiqi cəsarət tələb edirdi.",
     "cəsur, dözümlü", "hal, vəziyyət"),
    ("Çiçək açmaq; həm də inkişaf etmək və ya tədricən görünmək.",
     "Tam ifadəyə açılmaq — çiçək kimi, ya da bir fikrin nəhayət özü olması kimi.",
     "Rəsmdəki sakit istedadı öz emalatxanası olanda çiçəkləndi.",
     "çölə", "çiçək açmağa başlamaq"),
    ("Şaquliliyi müəyyən etmək üçün ağırlıqlı ip; məcazi olaraq mühakimə ölçüsü.",
     "Dosdoğru aşağı sallanmış ağırlıqlı ip, həqiqətən şaquli olub-olmadığına baxmaq üçün — və uzantısı ilə hər şeyi ölçdüyünüz sabit ölçü.",
     "Öz babasının dürüstlüyünü hər qərar üçün bir növ şaqul etdi.",
     "qurğuşun", "ip, ölçü"),
    ("Sevə-sevə, istəyə-istəyə (köhnə).",
     "\"Sevə-sevə\" və ya \"məmnuniyyətlə\" deməyin köhnə yolu.",
     "\"Burada bir az dincəlməyi çox istərdim,\" deyə ah çəkdi yolçu.",
     "şən, sevincli", "sevə-sevə, istəyə-istəyə"),
    ("Sərt ictimai tənqid və ya rüsvayçılıq.",
     "Birinin üzərinə böyük, görünən şəkildə yığılan ictimai utanc — geniş bəyənməmədən gələn rüsvayçılıq.",
     "Qalmaqal bütün firmanın üstünə ictimai rüsvayçılıq endirdi.",
     "qarşı", "rüsvayçılıq, qınaq"),
    ("İti kinayəli, zəka və ya tənqiddə dişləyici.",
     "Dişi olan zəka — sancıcı bir irad məhz nişanı yaxşı olduğu üçün bir az ağrıdır.",
     "Onun sancıcı film rəyləri rejissorlarca qorxulur, oxucularca sevilirdi.",
     "dişləmək", "dişləyən, edən"),
    ("Rəsmi bəyannamə, çox vaxt siyasi və ya hərbi.",
     "Böyük, rəsmi elan — adətən yeni hökumət, üsyan və ya böyük fərman elan edir.",
     "Generalın hərbi bəyannaməsi şəfəqdə yeni hökuməti elan etdi.",
     "irəli", "elan etmək"),
    ("Səthi biliyi olub mütəxəssis kimi davranan şəxs.",
     "Mövzunun səthini sürtüb sonra dərslik yazmış kimi danışan şəxs.",
     "Axşam yeməyindəki çoxbilmiş, masadakı həqiqi astrofiziki özündən əmin düzəltdi.",
     "bilmək", "kiçiltmə — kiçik bilən"),
    ("Qocalıqda zehni qabiliyyətlərin geriləməsi.",
     "Zehin itiliyinin solmağa başladığı çox qocalığın dumanlı, unutqan dövrü.",
     "Qocalıq zəifliyi dövründə hər ziyarətdə eyni üç hekayəni danışardı, hər dəfə yeniymiş kimi.",
     "kəmağıllıq, axmaqlaşmaq", "hal və ya nəticə"),
    ("Küləkdən qorunan yan.",
     "Təpənin, gəminin, divarın küləyin pek çata bilmədiyi sakit, sığınacaqlı yanı.",
     "Gəzintiçilər küləkdən qaçmaq üçün belin küləkaltı yanına çadır qurdular.",
     "sığınacaq, qoruma", "yan, üz"),
    ("Bir zərbəni, sualı və ya dəlili yayındırmaq.",
     "Ritmi qaçırmadan hamar yayındırmaq — qılınc zərbəsi, çətin sual və ya ittiham.",
     "Müxbirin çətin sualını asan bir zarafatla dəf etdi.",
     "yayındırmaq", "hazırlamaq, müdafiə etmək"),
    ("Pis qoxulu, zərərli.",
     "Az qala zəhərli gələn qoxu — nəfəs almaq təhlükəli gələcək qədər pis qoxu.",
     "Günəş batanda bataqlıqdan üfunətli bir qoxu qalxdı.",
     "zərərli buxar", "təbiətinə malik"),
    ("Lüks və ləzzətə həsr olunmuş şəxs.",
     "Rahatlıq və şıltaqlıq üçün yaşayan — gözəl yemək, yumşaq yataq, asan həyat — ifratı ilə məşhur qədim Yunan şəhəri Sybarisdən.",
     "Həqiqi bir eyş-işrət düşkünü olaraq vannasız otel otağını rədd etdi.",
     "lüksü ilə məşhur qədim Yunan şəhəri", "sakini"),
    ("Bir hissəni qəsdən kənara qoymaq və ya saymamaq.",
     "Tapmacanın bir parçasını qəsdən zehində kənara qoyub qalanına təmiz fokuslanmaq.",
     "Xərci bir an kənara qoyaq və planın həqiqətən işləyib-işləmədiyini soruşaq.",
     "əvvəl, uzağa", "kəsmək"),
    ("Şiddətlə tənqid etmək; həm də dərini soymək.",
     "Sərt tənqidlə birini parçalamaq — sözlə, sanki həqiqətən dərini soyurmuş kimi.",
     "Tənqidçilər davam filmini, əslin pərəstişkarlarının sevdiyi hər şeyə xəyanət etdiyi üçün yerlə bir etdi.",
     "qopuq", "dəri, post"),
    ("Sübut və ya dəlil kimi göstərmək.",
     "Nöqtənizi dəstəkləyəcək fakt və ya nümunə irəli sürmək — kimsə \"what's your evidence?\" deyə soruşanda işarə etdiyiniz şey.",
     "Vəkil müvəkkilinin bəhanəsini dəstəkləmək üçün üç şahid gətirdi.",
     "ə, doğru", "yönəltmək"),
    ("Səyahətlər və ya dolaşmalar, xüsusən uzun və geniş olanlar.",
     "Uzun, dolaşan səyahətlər — sizi evdən uzun müddət uzağa aparan geniş gəzinti.",
     "Üç qitədəki gəzişmələri bir rəf dolusu səyahət gündəliyini doldurdu.",
     "içindən", "tarla, torpaq (peregrinus: yad)"),
    ("Dilənçi, və ya sədəqə ilə yaşayan.",
     "Xeyir dilənərək yaşayan — tarixdə yoxsulluq andı içib ianə ilə yaşayan rahibləri də təsvir edərdi.",
     "Dilənçi rahiblər heç nəyə sahib deyildi və tamamilə kəndlilərin yaxşılığına bel bağlayırdı.",
     "dilənmək", "dilənçi"),
    ("Son dərəcə səxavətli.",
     "Az qala göstərişli miqyasda səxavətli — insanları bir az nəfəsini saxladan hədiyyə.",
     "Səxavətli ianə kitabxananın bütün yeni qanadını maliyyələşdirdi.",
     "hədiyyə, xidmət", "etmək, vermək"),
    ("Qida yoxluğundan tükənmə; həm də canlılıq yoxluğu.",
     "Qidalanmamış və ya yanacaqsız qalmaqdan zəif, tükənmiş hal — hərfən aclıqdan, məcazi olaraq qaçacaq bir şey qalmamasından.",
     "Mühasirənin sonunda əsgərlər taqətsizlik astanasında idi.",
     "boş, yox", "hərəkət və ya nəticə"),
    ("Acı, söyüşlü tənqid.",
     "Ədalinin çox o üzünə keçib qəzəbli, acı bir nutqa dönmüş tənqid.",
     "Onlayn şərhlər dəqiqələr içində saf söyüşə çevrildi.",
     "qüsur", "hazırlamaq, təmin etmək"),
    ("Düşməncəsinə, təsiri zərərli.",
     "Sakitcə belə sizə qarşı işləyən — maraqlarınıza dost olmayan şərait və ya münasibətlər.",
     "Yeni siyasət, niyyət o olmasa da kiçik müəssisələrə zərərli idi.",
     "deyil", "dost"),
    ("Çox vaxt ədalətsiz müqayisələrlə kin və ya narazılıq oyatmağa meyilli.",
     "Birini xor görünmüş hiss etdirməyə məhkum — adətən insanları və ya şeyləri ədalətsiz yığdığı üçün.",
     "Qardaş-bacıları \"Ana kimi ən çox sevir\" deyə sıralamaq heç kimin oynamaması gərəkən incidici bir oyundur.",
     "qısqanclıq", "(pis niyyətlə) baxmaq"),
    ("Daha aşağı rütbə və ya statusdakı şəxs; tabeli.",
     "Komanda zəncirində və ya ictimai nərdivanda daha aşağıda olan — daha güclü birinin altında çalışan gənc.",
     "Gənc bir kiçik zabit olaraq əmr verməzdən çox əvvəl əmr aldı.",
     "altında", "ehtiyat, digər"),
    ("Güclü nifrət duymaq və ya dilə gətirmək.",
     "Ucadan lənətləyəcək qədər iyrənmək — saf, səsli nifrət.",
     "Kəndlilər vergi yığanın arabası hər keçəndə onu lənətlədi.",
     "xaricə", "müqəddəs (müqəddəsdən çıxarıb lənətləmək)"),
    ("Dəri və ya qabıq kimi təbii xarici örtük.",
     "Təbiətin öz qoruyucu paketi — dəri, qabıq, qın və ya qabıq, canlıyı örtən və qoruyan nə varsa.",
     "Tısbağa qabığı son dərəcə möhkəm bir örtükdür.",
     "üzərində, örtən", "örtmək"),
    ("Məsum, sadəlövh, uşaqcasına sadəlik göstərən; \"disingenuous\"in əksi.",
     "Açıqca inanan və bir az sadəlövh, gizli gündəmsiz — \"clever\" mənasına gələn \"ingenious\" ilə qarışdırılması asan.",
     "Onun sadədil sualı — \"niyə kimsə bunun haqqında yalan desin?\" — nə qədər az hiyləli olduğunu göstərdi.",
     "içində, yerli", "törətmək (azad doğulmuş, açıq)"),
    ("Kiçik detallara və ya qaydalara həddindən artıq düşkünlük.",
     "Böyük mənzərəni qaçırıb kiçik qaydalarda itmək — heç kimin umursamadığı incə yazıya ilişmək.",
     "Oksford vergülü üzərinə bilikfüruşluğu bütün iclası relsdən çıxardı.",
     "uşaqların müəllimi", "adət və ya keyfiyyət"),
    ("İncə, diqqətli yoxlama.",
     "Daş qoymayan dərin baxış — hər detalı həqiqi qayğıyla tarama.",
     "Dəftərlərin diqqətli və ətraflı araşdırılmasından sonra uyğunsuzluq üzə çıxdı.",
     "içindən, köklü", "axtarmaq, yoxlamaq"),
    ("Etiraz qaldırmaq; istəksizlik göstərmək.",
     "Dərhal razı olmaq əvəzinə nəzakətlə geri itələmək və ya tərəddüd — yumşaq \"I'd rather not\".",
     "Oxumadan imzalamağı istənəndə tərəddüd etdi.",
     "dən, uzağa", "gecikdirmək"),
    ("Səthdə inandırıcı görünən, amma əslində yanlış.",
     "İlk baxışda inandırıcı durur, həqiqətən yoxlayanda çökür.",
     "\"Everyone's doing it\" yoxlama altında heç durmayan aldadıcı bir dəlildir.",
     "görünüş, baxış", "dolu (gözəl görünən)"),
    ("Səmimi olmayan, riyakar nitq, çox vaxt əxlaqçı.",
     "Fəzilətli duran, amma həqiqi hisslə dəstəklənməyən vaaz — avtomatik əxlaq pozu.",
     "Heç kəsə məzuniyyət verməyən bir şirkətin \"ailə\" üzərinə korporativ riyakar sözlərindən bezmişdi.",
     "oxumaq (sonra: monoton jarqon)", "dilənçilərin iniltisi, sonra riyakarlıq"),
    ("Cəsarətdən məhrum, qorxaq.",
     "Onurğasızlığa varan ürkək — açıqca vacibkən belə ayağa qalxa bilməyəcək qədər qorxaq.",
     "İdarə heyətinin qorxaq sükutu qalmaqalın nəzarətdən çıxmasına yol açdı.",
     "çox kiçik", "ruh, cəsarət"),
    ("Tülkü kimi; hiyləgər, zirək.",
     "Tülkü kimi hiyləgər və ağıllı — tez zəkalı, bir az gizli, həmişə bir addım öndə.",
     "Boşluğu görən kimi tülkü kimi bir sırıtma verdi.",
     "tülkü", "aid və ya kimi"),
    ("Bir-birinin ardınca, sırayla.",
     "Sıx-sıx bir-bir, sırayla ələ almaq — atlama yox, iki birlikdə yox.",
     "Hakim on iki tələbin hər birini ardıcıllıqla ələ aldı.",
     "sıra, silsilə", "bir-bir"),
    ("Həddindən artıq qənaətçilik; xəsislik.",
     "Pulu (və ya sözü, mənbəni) ağlabatan qənaətin o üzündə sıxmaq.",
     "Onun xəsisliyi əfsanə idi — çay kisəciyini üç dəfə işlətdi.",
     "əsirgəmək, qənaətcil olmaq", "hal və ya adət"),
    ("Düzəliş, xüsusən mətndə.",
     "Bir yazıya edilən təmir — köhnə və ya vacib bir mətndəki səhvi düzəldən akademik toxunuş.",
     "Yeni nəşr orijinal əlyazmaya onlarla düzəliş ehtiva edir.",
     "xaricə", "qüsur, səhv"),
    ("Yemək-içməkdə mülayim.",
     "Yemək və içki ətrafında qəsdən çəkinən — heç vaxt həddi aşmır, boşqabda bir az buraxır.",
     "Ölçülü vərdişləri, yaşıdları yavaşladıqdan sonra da onu uzun müddət iti saxladı.",
     "uzağında", "sərxoşedici içki"),
    ("Qrammatik səhv və ya ədəb qaydası pozuntusu.",
     "Qrammatika və ya ədəbdə kiçik sürüşmə — tükü tükdən ayıranı ürpədən növ səhv.",
     "\"Between you and I\" qrammatikçiləri hələ ürpədən yayğın bir dil səhvidir.",
     "pis yunancası ilə tanınan Kilikiya şəhəri", "adət, tərz"),
    ("Qrup daxili münaqişə ilə bağlı; qarşılıqlı dağıdıcı.",
     "Qrupu içəridən parçalayan daxili dava — hər kəsin uduzduğu, çünki ailə ailəyə qarşı.",
     "Partiyanın öz içindəki çəkişməsi xaricdəki hər hansı rəqibin verəcəyindən çox zərər verdi.",
     "arasında, içində", "öldürmək"),
    ("Biganə, umursamaz münasibət.",
     "Çiyin silkələmənin bütün bir şəxsiyyətə çevrilməsi — vaxtilə vacib olanlara o qədər az əhəmiyyət verir ki, heç nə səyə dəyməz.",
     "Mükafat mərasiminə laqeyd münasibəti, nə qədər çox çalışdığını bilən hər kəsi təəccübləndirdi.",
     "az", "əhəmiyyət vermək"),
    ("Qarışıq, mürəkkəb vəziyyət və ya mübahisə.",
     "Anlaması çətin dolaşıq, dağınıq vəziyyət — bir hissəsi yanlış anlama, bir hissəsi drama, hamısı qarışıqlıq.",
     "Bütün oturma planı dolaşıqlığı səhv qoyulmuş bir ad kartı ilə başladı.",
     "içində", "dolaşdırmaq, qarışdırmaq"),
    ("Təhdidedici, qorxuducu.",
     "Yanıltmaz bir təhdid havası daşıyan — hədələyici baxış və ya məktub ardınca pis bir şey gələ biləcəyini çox açıq edir.",
     "Məktubun hədələyici tonu kirəçini zərfi açmadan tədirgin etdi.",
     "hədə etmək", "işinə yarayan"),
    ("Güclü ictimai tənqid və ya şifahi söyüş.",
     "Ucadan ictimai qınaq — hər kəsin önündə oynanan yandırıcı tənqid.",
     "İfşaedən, tarix onu haqlı çıxarmazdan əvvəl illərlə ictimai qara yaxma ilə üzləşdi.",
     "qarşı", "danışmaq"),
    ("Hiss və ya hərəkətdə ani şiddətli partlayış.",
     "Bir anda sizi udan ani, sıx partlayış — gülmə, qəzəb və ya öskürək tutması dalğa kimi gəlir.",
     "Otaqdakı heç kəsə izah edə bilməyəcəyi bir gülmə tutmasına yaxalandı.",
     "o tərəf", "iti, kəskin"),
    ("Xarici mənbədən əlavə edilən, daxili olmayan.",
     "Başdan tikilmək əvəzinə kənardan vintlənmiş — əlavə, nüvə deyil.",
     "Şərh sonradan əlavə edilmiş gəlir, sanki bitmiş bir mətnə yapışdırılmış.",
     "ə, əlavə", "təsdiqləmək, üzərinə götürmək"),
    ("Bilik yoxluğu, cəhalət.",
     "Sadə bilməmə — hökm əlavə edilməmiş bilik boşluğu.",
     "Fransız şərabı barədə bilgisizliyini qəbul etdi və seçimi sommelierə buraxdı.",
     "deyil", "bilmək"),
    ("Cinsi mövzulara həddindən artıq maraq.",
     "Müəyyən hər şeyə həddindən artıq həvəsli, süzən bir maraq — sağlamı keçib burnunu soxmağa dönmüş maraq.",
     "Tabloidin cütlüyün şəxsi həyatına şəhvətli marağı saplantıya yaxın idi.",
     "qaşınmaq, həsrət çəkmək", "hal"),
    ("Hissli, qaranlıq, bulanıq.",
     "Qaranlıq və tüstülü görünüşlü, hər şeyin nazik his təbəqəsi ilə örtülü kimi.",
     "Alatoranlıqda fabrika qəsəbəsinin üstündə hisli bir duman asılı idi.",
     "his", "dolu"),
    ("İnkar etmək və ya zidd çıxmaq.",
     "Başqasının dediyinə qəti qarşı danışmaq — \"that's not so\" demək.",
     "Heç kəs qoca kapitanın fırtına hekayəsini təkzib etməyə cürət etmədi.",
     "qarşı", "danışmaq"),
    ("Tənbəllik, süstlük (latıncadan).",
     "Saf tənbəllik üçün köhnə latınca söz — heç nə etmək istəməmənin çəkisi.",
     "Rahiblər tənbəlliyi ruhun sakit təhlükələrindən biri deyə vəz etdi.",
     "deyil", "məşğul, zəhmətkeş"),
    ("Gerb göstərən qalxan.",
     "Ailənin gerbini göstərən qalxan şəkilli emblem — heraldik \"ad lövhəsi\".",
     "Ailənin gerb qalxanı hələ köhnə malikanənin ön qapısının üstündə asılıdır.",
     "qalxan", "kiçiltmə / obyekt"),
    ("Köhnəlmiş, etibarsız və ya yaşdan təqaüdə çıxmış.",
     "Faydalı zirvəsini keçmiş və otlağa çıxarılmış — işi davam etdirmək üçün çox köhnəmoda və ya yıpranmış.",
     "Köhnəlmiş printer on beş illik kağız ilişməsindən sonra nəhayət dəyişdirildi.",
     "o tərəf", "il"),
    ("Əvəzedicilər, xüsusən tibbdə.",
     "Əsl müalicə yoxkən işlədilən əvəzedici dərmanlar — əslində tibbi ehtiyat oyunçu.",
     "Müharibə həkimləri uyğun dərmanlar bitəndə tez-tez əvəzedici dərmanlara bel bağlayırdı.",
     "yerinə", "getmək, boyun əymək"),
    ("Öyünən, lovğa danışıq.",
     "Böyük, lovğa öyünmə — öz böyüklüyü haqqında çoxu hava olan uca səs.",
     "Layihəni \"tək başına\" xilas etdiyinə dair lovğalığı orada həqiqətən olan heç kəsi aldatmadı.",
     "Orlando Furioso-dakı öyünən cəngavər", "hərəkət, göstəriş"),
    ("Bir şeyə hiylə və ya aldatma ilə çatmaq.",
     "Ədalətli oyun əvəzinə gizli triklərlə hədəfə burulub çatmaq.",
     "İncə yazıyla dolu bir müqavilə ilə razılaşmaya hiylə ilə girdi.",
     "kılı qırx yarmaq, aldatmaq", "hiylə; sonra kəskin döngə"),
    ("Öyrənmə və ya biliyin təmiz və ya mücərrəd elmi, çox vaxt riyaziyyat.",
     "Ən təmiz, ən mücərrəd halında öyrənmə — biliyin özünün dərin quruluşu, xüsusən riyazi növü.",
     "Filosof hər bilik sahəsini birləşdirəcək universal bir mathesis xəyal etdi.",
     "öyrənmək", "öyrənmə aktı"),
    ("Formal qaydalara və ya xırda detalə həddindən artıq düşkün.",
     "Kiçik şeylərdə həddindən artıq sərt — əslində heç nəyi dəyişdirməyən texniki detalları düzəltmək.",
     "Bir mesajda \"who\" ilə \"whom\" mübahisə etmək bir az bilikfüruşluq gəldi.",
     "uşaq bələdçisi, müəllim", "tərzinə malik"),
    ("Parıldayan, qığılcımlanan işıq.",
     "Tez, parıldayan bir işıq çaxması — suda sıçrayan günəş, ya da işığı tutan almaz düşünün.",
     "Avizenin parıltısı balo salonunun hər küncünə işıq saçdı.",
     "parıldamaq, çaxmaq", "o akt"),
    ("Təcrübəsiz, acəmi.",
     "Bir bacarıq və ya sahəyə təzə-təzə biri — hələ ipin ucunu öyrənir, hələ mütəxəssis deyil.",
     "Yenibaşlayan bir şahmatçı belə o səhvi görər.",
     "təcrübəsiz əsgər, acəmi", "xam gənc əsgər"),
    ("Son dərəcə pis, iyrənc.",
     "Həqiqi iyrənmə haqq edəcək qədər pis — yalnız \"orta\" deyil, həqiqətən iyrənc.",
     "Tənqidçi davamı iyrənc deyə adlandırdı, kassa rəqəmləri də qoşuldu.",
     "lənətləmək", "layiq, ola bilən"),
    ("Qan qırmızısı rəngdə.",
     "Dərin, canlı qırmızı — təzə qan rəngi, Şekspirin Macbeth-i ilə məşhur.",
     "Qürub bütün səmanı al qırmızı bir parıltıya çevirdi.",
     "içinə", "ət (ət qırmızısı)"),
    ("Şeylər arasındakı kiçik boşluq.",
     "Gözdən qaçması asan ara boşluq — döşəmə taxtası çatlağı, proqramdakı ara.",
     "Köhnə kərpic yoldakı hər aralıqdan otlar fışqırdı.",
     "arasında", "durmaq"),
    ("Tənqidi və ya qınayıcı sözlər.",
     "İti, bəyənməyən iradlar — azar tonu daşıyan növ tənqid.",
     "Professorun esse üzərinə iradları kənarları qırmızı mürəkkəblə doldurdu.",
     "zehin", "doğru dönmək"),
    ("Təkzibedilməz, inkar edilə bilinməyən.",
     "O qədər möhkəm sübut olunmuş ki, mübahisə ediləcək bir şey yox — iş bağlanmışdır.",
     "DNT sübutu danılmaz idi və məhkəmə bir saat içində bitdi.",
     "deyil", "qarşı çıxmaq, müqavimət göstərmək"),
    ("Mürəkkəblik, dolayılıq; həm də içinə burulma.",
     "Öz içinə qatlanmış, açılması çətin mürəkkəblik — o qədər sıx sarılmış ki, ayırmaq çətindir.",
     "Süjetin mürəkkəbliyi tamaşaçının yarısını titrlərdən sonra açmağa buraxmışdı.",
     "içə, içeriyə", "sarmaq, döndərmək"),
    ("Güc və ya səy, \"by dint of\" deyimində olduğu kimi.",
     "Sadəcə səy və ya güc — bu gün əsasən \"by dint of\" deyimində yaşayır.",
     "İmtahanı sadəcə inadkar məşqin gücü ilə keçdi.",
     "zərbə, vuruş", "gücü ilə"),
    ("Yuva-diş birləşməsi ilə birləşdirilmiş; sıx oturdulmuş.",
     "Köhnə üsul dülgər yolunda kilidlənmiş — bir parça tam özü üçün kəsilmiş deşiyə sıx oturur.",
     "Köhnə anbarın tirləri tək mismar olmadan yuvaya keçirilərək birləşmişdi.",
     "yuva, deşik", "dişləmə, tutuş"),
    ("Son dərəcə uyğun, yerində.",
     "O ana tam oturan — nöqtəyə kusursuz düşən irad, sitat və ya nümunə.",
     "Onun yerində sözü bütün mübahisəni bir cümlədə yığdı.",
     "ə", "qoymaq"),
    ("Yumşaqca parlayan və ya titrəyən (işıq); həm də yüngül zəka.",
     "Yanmaq əvəzinə nəzakətlə parlamaq — yumşaq titrəyən işıq, ya da iti deyil, oynaq zəka.",
     "Şam işığı köhnə yemək otağına titrək bir parıltı saldı.",
     "yalamaq", "etmək ('yalayan' işıq)"),
    ("Tənhalıqda yaşayan dini münzəvi.",
     "Dua və təfəkkürlə tək yaşamaq üçün dünyadan tamamilə çəkilən şəxs.",
     "Zahid otuz ildən çox kilsəyə bitişik kiçik bir hücrədə yaşadı.",
     "geri, uzağa", "çəkilmək"),
    ("Susuzluğu yatırtmaq; söndürmək.",
     "Bir həsrəti tamamilə doyurmaq — çox vaxt susuzluq, məcazi olaraq hər dərin istək və ya ehtiyac.",
     "Uzun gəzintidən sonra bir stəkan soyuq su susuzluğunu yatırtdı.",
     "boş, boşaldılmış", "boşaltmaq, yatırmaq"),
    ("İynə şəkilli.",
     "Uzun, nazik və iynə kimi sivri — şam iynəsi və ya iti kiçik kristal forması.",
     "Şamlar iynəvari yarpaqları ilə asan tanınır.",
     "iynə", "kiçik"),
    ("Canlılığı tükənmiş, zəif, həddindən artıq incəlmiş.",
     "Köhnəlmiş və yumşaq — həddindən artıq rahatlıq və ya incəlikdən əsl gücünü və həvəsini itirmiş.",
     "Tənqidçilər bir vaxtlar cəsur jurnalı gücünü itirmiş, erkən illərinin kölgəsi deyə adlandırdı.",
     "çölə", "məhsuldar, doğurmuş"),
    ("Əlavə və ya kiçik bağlı hüquq.",
     "Daha böyüyünə yapışıq gələn kiçik əlavə — əsas şeyə aid aksesuar və əlavələr.",
     "İcarə qarajı və bütün əlavələrini əhatə edirdi.",
     "ə", "aid olmaq"),
    ("Bir qüsuru örtmək və ya kiçiltmək.",
     "Yumşaq sözlərlə səhvi hamarlamaq, həqiqətən kiçikmiş kimi göstərmək.",
     "Buraxılmış təslim tarixini \"gözlənilməz çətinliklər\" üzərinə qeyri-müəyyən sözlərlə ötüşdürməyə çalışdı.",
     "şərh, izah", "şərh etmək — sonra örtmək"),
    ("Erkən mərhələdə, yenicə başlayan.",
     "Yenicə görünməyə başlayan — daha böyük bir şeyin ilk, az qala görünməz mərhələsi.",
     "Həkimlər xəstəlik yayılmadan başlanğıc əlamətlərini tutdu.",
     "üzərində, içinə", "almaq (qaldırmaq, başlamaq)"),
    ("Yaradıcı ilham, xüsusən ilahi.",
     "Sizdən böyük gələn ani ilham — fikir başqa yerdən sizə üfürülmüş kimi.",
     "Şair bütün parçanın gecə 3-də bir ilham partlayışı ilə gəldiyini danışdı.",
     "ə, üzərinə", "üfürmək (üzərinə üfürmə)"),
]
