# Swahili rows: (definition, friendly, exampleGloss, root1, root2)
ROWS = [
    ("Kutia tamu au kusafisha; kuondoa ukali kutoka katika kitu.",
     "Kutoa mwiba au uchungu — kwa hakika kutia tamu, au kwa sitiari kulainisha wazo kali ili liingie vizuri.",
     "Mhariri alilainisha tathmini kali kabla haijachapishwa.",
     "nje, kabisa", "tamu"),
    ("Kupita kiasi au kwa uwongo kuwa wa dini au mcha Mungu.",
     "Inaelezea mtu ambaye ibada yake inaonekana ni maonyesho, si imani ya kweli.",
     "Kuugua kwake kwa kujifanya mcha Mungu wakati wa mahubiri kuliwachukiza wengine wote benchi.",
     "uchamungu, wajibu", "kuwa na tabia ya"),
    ("Utata unaotokana na muundo wa sarufi — sentensi inayosomeka namna mbili.",
     "Sentensi iliyo sawa kisarufi lakini inasomeka maana mbili tofauti kabisa, kama \"I saw the man with the telescope.\"",
     "\"Visiting relatives can be tiring\" ni utata wa kisarufi wa kawaida — je, ndugu wanachosha, au kuwatembelea?",
     "pande zote mbili", "kutupa"),
    ("Mkali, unaokatiza, unaokata moja kwa moja kwenye suala.",
     "Inakata porojo — maoni au akili ya mkato inafika moyoni mwa jambo haraka, bila maneno ya bure.",
     "Ukosoaji wake wa mkato haukuacha pengo la hadithi ya filamu mahali pa kujificha.",
     "kata", "kufanya, kuwa na sifa"),
    ("Inaanza tu; katika hatua ya mapema au ya msingi.",
     "Bado katika dakika za kwanza — mpango, hisia, au mchakato ulioanza tu kuumbika.",
     "Hatua changa za mkataba zilikuwa za matumaini, lakini maelezo mengi yalibaki wazi.",
     "kuanza, kuanzisha", "kuelemea kuelekea"),
    ("Hotuba rasmi au andiko linalomsifu mtu sana.",
     "Heshima rasmi kamili — fikiria sifa inayong'aa au hotuba inayoimba mafanikio kutoka paa.",
     "Profesa aliyestaafu aliondolewa kwa hotuba ya sifa kutoka kwa wanafunzi wake wa karibu.",
     "yote", "mkusanyiko, kusanyiko"),
    ("Kuhusu uwepo halisi au kuwako kwa ukweli, si nadharia tupu.",
     "Kuhusu vitu kama vilivyo kweli, si kama mawazo au nadharia tu juu yake.",
     "Wanafalsafa wanajadili kama namba zina hadhi ya kuwako au zipo tu akilini mwetu.",
     "kuwako, kilichopo", "kinachohusiana na"),
    ("Kuzaa matunda, au kuwa na tija.",
     "Hatimaye kutoa matunda — juhudi, wazo, au uwekezaji uliokua kutoka mbegu kuwa kitu chenye faida.",
     "Miaka ya utafiti wa kimya hatimaye ilizaa chanjo inayofanya kazi.",
     "tunda", "kufanya, kusababisha"),
    ("Kutarajia au kuonyesha kitu kama kimekwisha kabla hakijatokea.",
     "Kuruka mbele kwa mtindo wa fasihi — kueleza tukio la baadaye kama limekwisha, ili hoja iume zaidi.",
     "Toast ya kutangulia ya jenerali kwa \"ushindi\" ilitolewa wiki kamili kabla ya vita.",
     "kabla", "kuchukua, kunyakua"),
    ("Inayoendeshwa na shinikizo la hewa; pia kuhusu roho au pumzi.",
     "Kwa kawaida humaanisha \"inaendeshwa na hewa iliyoshinikizwa\" — ingawa inaweza pia kumaanisha roho au pumzi.",
     "Breki za hewa zilifoka basi liliposimama kando ya barabara.",
     "upepo, pumzi, roho", "kinachohusu"),
    ("Kueleza Mungu au yaliyo matakatifu kwa kauli chanya — kinyume cha apofatiki.",
     "Njia ya kuzungumza juu ya Mungu kwa kusema yeye ni nini — \"God is love\" — si tu yeye si nini.",
     "Theolojia katafatiki inazungumza kwa uhakika juu ya Mungu kama mwenye upendo, haki, na huruma.",
     "chini, kulingana na", "kusema, kutamka"),
    ("Kulingana na imani au uaminifu; pia hutumika kama alama thabiti ya kurejelea.",
     "Kitu unachokichukua kwa imani kisha kukitumia kama nanga — alama ya kurejelea ndiyo sehemu thabiti ambayo vinginevyo hupimwa.",
     "Wapima ardhi waliweka alama ya kurejelea kwenye mwamba kabla ya kuchora ramani ya eneo.",
     "kuamini", "imani, uaminifu"),
    ("Ulinzi wa wema wa Mungu licha ya kuwepo kwa uovu.",
     "Jaribio la kale la kujibu \"Ikiwa Mungu ni mwema, kwa nini uovu upo?\"",
     "Tasnifu yake ilichunguza utetezi wa wema wa Mungu kupitia kioo cha Kitabu cha Ayubu.",
     "mungu", "haki"),
    ("Kukaa ndani kwa pamoja — neno la theolojia kuhusu jinsi nafsi za Utatu zinavyokaa ndani ya kila moja.",
     "Neno la theolojia kwa umoja wa tatu-ndani-ya-moja ulio kamili kiasi kwamba kila sehemu inajumuisha na inajumuishwa na nyingine.",
     "Fundisho la kukaa ndani kwa pamoja linajaribu kueleza jinsi Baba, Mwana, na Roho walivyo tofauti lakini hawatenganishwi.",
     "kuzunguka", "kwenda, kutembea"),
    ("Kuleta matokeo yanayonufaisha au yanayorudi kwa mtu.",
     "Sifa (au lawama) inaporudi kwa anayewajibika — mema yanayorudi kwa sifa yako yanarudi kukulipa.",
     "Mafanikio ya timu yatarudi kama sifa kwa kocha wake mtulivu na mchapakazi.",
     "nyuma, tena", "wimbi"),
    ("Isiyoweza kuepukwa wala kutoroka.",
     "Lazima litokee hata ukifanya nini — hakuna kujikunja nje ya matokeo yasiyoepukika.",
     "Uzee huwafikia wote; ni jambo lisiloepukika tu.",
     "si", "kujitahidi kutoka"),
    ("Kutumia maneno ya kuzunguka, marefu, badala ya umbo la moja kwa moja.",
     "Kuchukua njia ndefu kwa maneno — kusema \"make a decision\" badala ya \"decide\".",
     "Barua pepe zake za mzunguko zingeweza kusema kwa mstari mmoja kile kilichochukua aya tatu.",
     "kuzunguka", "kutangaza, kusimulia"),
    ("Uzembe wa akili au ulegevu.",
     "Hali ya akili yenye ukungu, ya polepole, ambapo kufikiri kunahisi kama kuvuka shira.",
     "Wimbi la ulegevu wa akili liliwapiga darasa mara baada ya chakula cha mchana.",
     "butu, si kali", "hali au sifa"),
    ("Isiyofaa; ishara mbaya.",
     "Ishara mbaya — hali au wakati unaoonekana kukupinga kabla hujataanza.",
     "Mawingu ya kijivu na betri iliyokufa yalifanya mwanzo usiofaa wa safari.",
     "si", "unaofaa, mwenye neema"),
    ("Nyama iliyochemshwa au kupikwa katika mchuzi — tahajia sahihi ni \"fricasseed\".",
     "Neno la kale la kupikia lenye joto kwa nyama iliyokatwa na kuchemshwa taratibu katika mchuzi wake hadi laini.",
     "Kuku wa nyanya aliyepikwa katika mchuzi alikuwa kilele cha kila chakula cha jioni cha Jumapili.",
     "kukaanga", "kuvunja (vipande)"),
    ("Mbadala bandia au duni.",
     "Bandia inayosimama mahali pa ya kweli — kitaalamu inafanya kazi, lakini kila mtu anajua si ya asili.",
     "Wanunuzi wa wakati wa vita walitumia kahawa bandia iliyotokana na chicory iliyochomwa.",
     "nje, kiambishi cha mbadala", "kuweka, kuweka mahali"),
    ("Kuchukulia wazo dhahania kama kitu halisi.",
     "Kufanya wazo lihisike kuwa thabiti — kugeuza kilicho wazi, kama \"the economy\", kuwa kitu unachoweza kuelekeza kidole.",
     "Kuita \"roho\" ya taifa kama kiumbe chake mwenyewe ni kukifanya halisi kitu ambacho kweli ni maamuzi ya mamilioni ya watu.",
     "kitu", "kufanya"),
    ("Kutoroka au kuepuka kwa ustadi.",
     "Kuteleza safi — kuepuka kukamatwa, swali, au jibu, mara nyingi kwa ujanja au karibu karibu.",
     "Jibu lilimkwepa kwa masaa hadi ghafla likafunguka alipokuwa ananawa.",
     "nje, mbali", "kucheza"),
    ("Kueleza shaka, mshangao, au mkanganyiko ambao haujatatuliwa.",
     "Kukwama kwenye mwisho wa mawazo wa kweli — si kuchanganyikiwa kwa uvivu, bali kwa sababu swali lenyewe linakataa jibu safi.",
     "Socrates mara nyingi alimaliza mazungumzo kwa sauti ya mkanganyiko, maswali zaidi kuliko majibu.",
     "bila", "njia, njia ya kupita"),
    ("Tamathali inayotaja kitu kwa neno linalohusiana, k.m. \"the crown\" kwa mfalme.",
     "Kutumia neno linalohusiana badala ya kitu chenyewe — kusema \"the White House announced\" ukimaanisha serikali.",
     "\"Wall Street had a rough day\" ni tamathali ya uwakilishi — kweli inamaanisha soko la hisa lilikumbwa na shida.",
     "badiliko, baada", "jina"),
    ("Kung'oa mizizi; kurarua kutoka mazingira asilia.",
     "Kuvuta kitu (au mtu) kutoka mizizi, mbali na mahali au utamaduni wake.",
     "Vita viling'oa kizazi kizima kwenye mizizi yake, vikitawanya familia kuvuka mipaka.",
     "mbali, kutoka", "mzizi"),
    ("Yenye sauti nzuri.",
     "Tu inayofaa kusikiliza — neno, jina, au sentensi yenye sauti nzuri inatiririka sikioni kama muziki.",
     "\"Murmuring brook\" ni kishazi kidogo chenye sauti nzuri, laini na rahisi kutamka.",
     "nzuri, vizuri", "sauti, sauti ya mtu"),
    ("Inayodhaniwa au kufikiriwa kwa ujumla.",
     "Inaaminika sana kuwa kweli ingawa haijathibitishwa — toleo la \"supposed\".",
     "Mwandishi anayedhaniwa wa barua baadaye alionekana kuwa mgeni kabisa.",
     "kufikiri, kuzingatia", "kuwa na asili ya"),
    ("Neno au kishazi kipya kilichobuniwa.",
     "Neno jipya kabisa — limebuniwa sasa hivi, bado halijaingia (au karibu) kamusi.",
     "\"Doomscrolling\" lilianza kama neno jipya na haraka likawa lugha ya kila siku.",
     "mpya", "neno, usemi"),
    ("Mwenye hasira au hasira mbaya.",
     "Katika hali mbaya, tayari kulipuka — kama watu wa kale walivyoamini wengu unadhibiti hasira.",
     "Alirusha jibu la hasira sekunde chache baada ya kusoma barua pepe.",
     "wengu (kiti cha hasira)", "aliyeathiriwa na"),
    ("Anayependa kuhubiri maadili kwa kiburi au kwa uwongo.",
     "Anapenda kutoa mafunzo madogo ya maisha kwa kujiona, kama kila sentensi ni biskuti ya bahati.",
     "Toast yake ya kuhubiri kwa kiburi kuhusu \"maana ya kweli ya urafiki\" ilifanya kila mtu aangalie saa.",
     "maoni, methali", "imejaa"),
    ("Anayezungumza kupita kiasi, hasa kuhusu mambo madogo.",
     "Haisi kuzungumza — anaendelea kuhadithia mambo madogo muda mrefu baada ya wengine kuishiwa maneno.",
     "Dereva wa teksi mwenye maneno mengi alitueleza maisha yake yote kabla hatujaondoka uwanja wa ndege.",
     "kupiga porojo", "mwenye mwelekeo"),
    ("Upumbavu, ujinga.",
     "Upumbavu mtupu — maoni au mpango mjinga kiasi kwamba hauhitaji jibu zito.",
     "Upumbavu wazi wa mpango huo ulionekana mara walipojaribu.",
     "mjinga, mjinga", "hali ya kuwa"),
    ("Sehemu ya mwisho ya hotuba, mara nyingi inayofupisha.",
     "Mwisho mkubwa wa hotuba — sehemu ya kufunga ambapo msemaji anakusanya yote na kupigilia hoja.",
     "Kufikia hitimisho, nusu ya hadhira walikuwa wamesimama.",
     "kupitia, hadi mwisho", "kusema, kutetea"),
    ("Kurudia wazo lile lile kwa maneno tofauti bila haja.",
     "Kusema kitu kile kile mara mbili bila kuongeza chochote, kama \"free gift\" au \"end result\".",
     "\"It is what it is\" ni urudiaji usio na haja unaopendwa na wanaoepuka maelezo ya kweli.",
     "lile lile", "neno, usemi"),
    ("Kutumia maneno machache sana; usemi mfupi.",
     "Kusema mengi kwa machache — sanaa ya jibu fupi, kali, kutoka kwa Wasparta wa Laconia waliojulikana kwa ufupi.",
     "\"Molon labe\" — \"njoo uzichukue\" — ndio usemi mfupi maarufu zaidi katika historia.",
     "Msparta wa Laconia", "tabia, namna"),
    ("Mawazo yasiyo na ladha, yaliyorahisishwa kupita kiasi; asili, chakula kisicho na ladha au uji.",
     "Mawazo yaliyopunguzwa maji — maudhui yaliyorahisishwa na salama kiasi kwamba hayana lishe kwa akili.",
     "Hotuba ya mwanasiasa ilikuwa hasa maneno matupu: ahadi zisizo wazi zisizoshikika.",
     "kulisha", "chombo au njia"),
    ("Inayosababisha usingizi au usingizi mzito.",
     "Ya kuchosha — au kwa hakika yenye dawa ya usingizi — kiasi cha kukulaza. Fikiria maziwa ya joto, au mkutano wa bajeti wa masaa matatu.",
     "Mlio wa kusinzisha wa somo ulifanya nusu ya chumba wapiganie kufungua macho.",
     "usingizi mzito", "kufanya, kusababisha"),
    ("Anayebembeleza kupita kiasi au mwenye tabia ya mafuta.",
     "Lainifu kiasi cha kuteleza — sifa iliyopakwa nene unahisi mafuta.",
     "Muuzaji mwenye kubembeleza aliendelea kupongeza \"ladha bora\" yangu kabla ya kila uuzaji wa ziada.",
     "kupaka mafuta", "imejaa"),
    ("Haraka kupata kosa, mkali kupita kiasi kwa mambo madogo.",
     "Mwenye ubishi wa kila kitu — aina ya mtu anayepata tatizo kila mahali, hata lisilojali.",
     "Maelezo yake ya kutafuta makosa kwenye ripoti yalilenga tu mahali pa koma.",
     "kukamata, kuchukua", "mtego, uwongo wa hoja"),
    ("Mzembe, asiyefanya kazi kiakili au kimwili.",
     "Polepole na nusu usingizi, kama dubu katika usingizi wa majira ya baridi — karibu hana mwendo, karibu hana mawazo.",
     "Ofisi ilikuwa legevu katika joto zito la Agosti.",
     "ganzi, mzembe", "katika hali ya"),
    ("Msimamizi au afisa anayesimamia nyumba ya enzi za kati.",
     "Toleo la enzi za kati la mkuu wa wafanyakazi — afisa anayeaminika aliyesimamia nyumba na shamba la bwana kila siku.",
     "Mwangalizi wa ngome alisimamia kila kitu kutoka akaunti za mavuno hadi orodha ya wageni.",
     "mzee, mkubwa", "mtumishi"),
    ("Kuzungumza au kuandika kwa urefu juu ya mada.",
     "Kweli kuanza juu ya somo — kuzungumza au kuandika bila kukoma, kufunika kila pembe.",
     "Muulize kuhusu magari ya kale naye atazungumza kwa urefu kwa saa kamili.",
     "nje", "nafasi"),
    ("Isiyo na thamani, ndogo; pia batili au isiyofanya kazi.",
     "Karibu haina thamani — kifungu batili katika mkataba ni kile kisichofanya chochote kweli.",
     "Mahakama iliamua sheria ndogo ya kale ilikuwa batili, kwa kuwa haikuwahi kutekelezwa.",
     "mambo madogo, upuuzi", "ya"),
    ("Hekima, hukumu makini.",
     "Hekima makini ya kivitendo — hukumu nzuri inayotoka katika uzoefu, si vitabu tu.",
     "Hekima ya nahodha mzee iliwaokoa wafanyakazi wa meli zaidi ya mara moja.",
     "wenye harufu kali, werevu", "sifa ya"),
    ("Umati wa kawaida au watu wa chini, hutumika kwa dharau.",
     "Neno la kiburi, la kudharau kwa \"umati\" au watu wa kawaida.",
     "Count aliudhihaki umati wa chini uliokusanyika nje ya milango ya ikulu.",
     "mbwa", "kundi, kundi la"),
    ("Matibabu au lugha ya kiburi, ya kufedhehesha.",
     "Matibabu makali, ya dharau yaliyokusudiwa kufedhehesha — tusi lililoundwa kuuma.",
     "Alivumilia miaka ya fedheha kutoka kwa wakosoaji kabla kazi yake hatimaye kutambuliwa.",
     "pamoja, kabisa", "kuvimba (kwa kiburi)"),
    ("Kwa shaka au kutokubali; mtazamo wa pembeni.",
     "Mtazamo wa pembeni unaotoa kwa kitu usichoamini kabisa — macho yaliyojaa shaka.",
     "Mwalimu alitazama kwa shaka kazi ya nyumbani iliyokuwa safi kwa kutiliwa shaka.",
     "kwa, kuelekea", "upande, upendeleo"),
    ("Mjinga; kichwa kigumu.",
     "Tusi la kale, karibu la upendo, kwa mtu anayekuwa mzito kichwa — kichwa kigumu.",
     "\"Wewe mjinga,\" alicheka, \"ramani imekuwa juu chini muda wote.\"",
     "donge la udongo", "kichwa"),
    ("Kuweka katika mwendo au hatua; kuhamasisha.",
     "Kuwa cheche inayosukuma kitu kusonga — iwe mashine inawaka au mtu hatimaye kutenda juu ya wazo.",
     "Hofu ya kupoteza mkataba iliisukuma timu yote kwenye kazi ya ziada ya wikendi.",
     "kitendo, kusukuma", "kusukuma, kufanya"),
    ("Kuiba pesa zilizoaminiwa.",
     "Kuiba kimya pesa ulizoaminiwa kushika — wizi wa pesa katika vazi la kale.",
     "Wizi wa fedha za amana uliofanywa na mweka hazina haukugunduliwa karibu muongo mmoja.",
     "mali binafsi", "ng'ombe, utajiri"),
    ("Kundi linalochukuliwa kuwa pembeni mwa jamii yenye heshima.",
     "Dunia ya chini ya kijamii yenye kung'aa lakini yenye shaka — watu wanaoishi nje kabisa ya sheria za jamii \"yenye heshima\".",
     "Riwaya inafuata mwimbaji anayetembea ulimwengu wa pembezoni wa mabaa ya miaka ya 1920.",
     "nusu", "dunia, jamii"),
    ("Bado lipo; halijapotea wala kuharibiwa.",
     "Bado lipo leo — hutumika kwa vitu vya kale (hati, spishi, majengo) vilivyofanikiwa kuishi.",
     "Nakala tatu tu zilizosalia za chapisho la kwanza zinajulikana kuwepo.",
     "nje", "kusimama"),
    ("Udanganyifu; usaliti wa imani.",
     "Usaliti wa kina, wa makusudi — kuvunja imani ambayo mtu alikuwa na haki kutarajia utunze.",
     "Jenerali hakuwahi kusamehe usaliti wa rafiki yake wa zamani mezani mwa mazungumzo.",
     "kupitia, dhidi", "imani, uaminifu"),
    ("Lahaja ya eneo, hasa isiyo ya kawaida.",
     "Njia ya kipekee ya watu kuzungumza katika eneo fulani — imejaa maneno na midundo ambayo mgeni anaweza asije akashikwa.",
     "Bibi yake bado alizungumza lahaja ya kisiwa kwenye milo ya familia.",
     "usemi mkali, lahaja", "kiganja — usemi wa kigugumizi"),
    ("Haki maalum inayomilikiwa na mtu au kundi.",
     "Upendeleo ulio wako wewe peke yako — haki inayokuja na jukumu, cheo, au hadhi.",
     "Kuchagua mahali pa likizo ya familia ni haki maalum ya babu, na kila mtu anajua.",
     "kabla", "kuuliza, kupiga kura"),
    ("Ujasiri, ujasiri mkubwa; pia ugumu au uvumilivu.",
     "Uvumilivu mkali, wenye moyo — ujasiri wa kusonga mbele na ugumu wa kuendelea ukishaanza.",
     "Ilihitaji ujasiri wa kweli kuvuka njia katika dhoruba ya theluji bila ramani.",
     "jasiri, mgumu", "hali, hali ya"),
    ("Kuchanua; pia kukua au kuonekana taratibu.",
     "Kuchanua katika usemi kamili — kama ua linalofunguka, au wazo linalokuwa lenyewe hatimaye.",
     "Kipaji chake cha kimya cha uchoraji kilichanua alipopata studio yake mwenyewe.",
     "nje", "kuanza kuchanua"),
    ("Kamba yenye uzito kuthibitisha wima; kwa sitiari, kipimo cha hukumu.",
     "Uzito kwenye kamba unaoning'inia moja kwa moja chini, kuthibitisha kama kitu ni wima kweli — na, kwa upana, kipimo thabiti unachopimia vinginevyo.",
     "Alitumia uaminifu wa babu yake mwenyewe kama aina ya timazi kwa kila uamuzi.",
     "risasi", "kamba, kipimo"),
    ("Kwa furaha, kwa hiari (ya kale).",
     "Njia ya kale ya kusema \"kwa furaha\" au \"kwa raha\".",
     "\"Ningependa kupumzika hapa kwa muda,\" msafiri aliugua.",
     "furaha, shangwe", "kwa furaha, kwa hiari"),
    ("Ukosoaji mkali wa umma au aibu.",
     "Aibu ya umma inayomiminwa juu ya mtu kwa njia kubwa, inayoonekana — aibu inayotoka katika kutokubaliwa kwa wingi.",
     "Kashfa ilileta aibu ya umma juu ya kampuni nzima.",
     "dhidi", "aibu, lawama"),
    ("Mwenye kejeli kali, inayouma katika akili au ukosoaji.",
     "Akili yenye meno — maoni yenye kuuma yanauma kidogo hasa kwa sababu yameelekezwa kwa ustadi.",
     "Tathmini zake za filamu zenye kuuma ziliogopwa na waongozaji na kupendwa na wasomaji.",
     "kuuma", "kuuma, kufanya"),
    ("Tangazo rasmi, mara nyingi la kisiasa au kijeshi.",
     "Tangazo kubwa, rasmi — kwa kawaida linatangaza serikali mpya, uasi, au amri kubwa.",
     "Tangazo rasmi la jenerali lilitangaza serikali mpya alfajiri.",
     "mbele", "kutangaza"),
    ("Mtu mwenye maarifa ya juujuu anayejifanya mtaalamu.",
     "Mtu aliyepangusa uso wa mada kisha anazungumza kama aliandika kitabu cha somo hilo.",
     "Mjuaji wa juujuu kwenye karamu ya jioni alimrekebisha kwa ujasiri mwanaastrofizikia wa kweli mezani.",
     "kujua", "kidogo — mjuzi mdogo"),
    ("Kupungua kwa uwezo wa akili katika uzee.",
     "Kipindi cha uzee wa kuchelewa, cha kusahau, wakati ukali wa akili unaanza kufifia.",
     "Katika uzee wake, alisimulia hadithi tatu zile zile kila ziara, kila mara kama mpya.",
     "kuwa mjinga, kuwa mzito", "hali au matokeo"),
    ("Upande uliolindwa na upepo.",
     "Upande tulivu, uliolindwa — kilima, meli, ukuta — ambapo upepo hauwezi kukufikia.",
     "Watembezi waliweka hema yao kwenye upande wa kivuli cha upepo wa ukingo ili kuepuka pepo.",
     "kivuli, ulinzi", "upande, uso"),
    ("Kuzuia au kuzuia pigo, swali, au hoja.",
     "Kupiga mbali kwa ustadi — pigo la upanga, swali gumu, au shtaka — bila kupoteza mdundo.",
     "Yeye aliliepusha swali gumu la mwandishi kwa mzaha mwepesi.",
     "kuzuia", "kutayarisha, kutetea"),
    ("Yenye harufu mbaya, yenye sumu.",
     "Inanuka kiasi cha karibu kuwa sumu — harufu mbaya kiasi inaonekana hatari kuvuta.",
     "Harufu ya kunuka ilipanda kutoka kwenye bwawa jua lilipozama.",
     "mvuke wenye sumu", "kuwa na asili ya"),
    ("Mtu aliyejitolea kwa anasa na starehe.",
     "Mtu anayeishi kwa starehe na kujifurahisha — chakula kizuri, vitanda laini, maisha mepesi — kutoka mji wa kale wa Kigiriki Sybaris maarufu kwa kuzidi.",
     "Mpenda anasa wa kweli, alikataa chumba chochote cha hoteli bila bafu.",
     "mji wa kale wa Kigiriki maarufu kwa anasa", "mkaaji wa"),
    ("Kukusudia kuweka kando au kupuuza sehemu.",
     "Kuweka kipande cha fumbo kando kwa makusudi akilini, ili uzingatie kwa usafi kilichobaki.",
     "Hebu tuweke gharama kando kwa muda na tuulize kama mpango unafanya kazi kweli.",
     "kabla, mbali", "kata"),
    ("Kukosoa vikali; pia kuvua ngozi.",
     "Kurarua mtu kwa ukosoaji mkali — kwa maneno, kama unavua ngozi kweli.",
     "Wakosoaji walikosoa vikali mwendelezo kwa kusaliti kila kitu mashabiki walipenda katika asili.",
     "kutoka", "ngozi, ngozi ya mnyama"),
    ("Kutaja kama ushahidi au uthibitisho.",
     "Kuleta ukweli au mfano kuunga mkono hoja yako — kitu unachoelekeza mtu anapouliza \"what's your evidence?\".",
     "Wakili aliwataja mashahidi watatu kuunga mkono alibi ya mteja wake.",
     "kwa, kuelekea", "kuongoza"),
    ("Safari au kutangatanga, hasa ndefu na pana.",
     "Safari ndefu, za kutangatanga — kutangatanga kwa upana kunakokupeleka mbali na nyumbani kwa muda mrefu.",
     "Safari zake katika mabara matatu zilijaza rafu nzima ya shajara za safari.",
     "kupitia", "shamba, nchi (peregrinus: mgeni)"),
    ("Mwombaji, au anayeishi kwa sadaka.",
     "Mtu anayeishi kwa kuomba huruma — kihistoria pia watawa walioapa umaskini na kuishi kwa michango.",
     "Watawa waombaji hawakuwa na chochote na walitegemea kabisa wema wa wanakijiji.",
     "kuomba", "mwombaji"),
    ("Mkarimu sana.",
     "Mkarimu kwa kiwango kikubwa, karibu cha kuonyesha — zawadi inayofanya watu washike pumzi kidogo.",
     "Mchango mkarimu ulifadhili bawa zima jipya la maktaba.",
     "zawadi, huduma", "kufanya, kutoa"),
    ("Uchovu kutokana na ukosefu wa lishe; pia ukosefu wa nguvu.",
     "Hali dhaifu, iliyokauka kutokana na kutolishwa au kutochajiwa — kwa hakika kutoka njaa, au kwa sitiari kutoka kutokuwa na kitu cha kuendesha.",
     "Mwisho wa kuzingirwa, askari walikuwa karibu na uchovu wa njaa.",
     "tupu, bure", "tendo au matokeo"),
    ("Ukosoaji mchungu, wa matusi.",
     "Ukosoaji uliopita haki na kuwa hasira, mchungu wa maneno.",
     "Maoni mtandaoni yaligeuka matusi matupu ndani ya dakika chache.",
     "kosa", "kutayarisha, kutoa"),
    ("Adui, yenye madhara katika athari.",
     "Inakufanyia kazi dhidi yako, hata kimya — hali au mitazamo isiyo rafiki kwa masilahi yako.",
     "Sera mpya ilikuwa na madhara kwa biashara ndogo, hata kama hiyo haikuwa nia.",
     "si", "rafiki"),
    ("Inayoweza kusababisha chuki au kutoridhika, mara nyingi kupitia kulinganisha visivyo vya haki.",
     "Lazima ifanye mtu ahisi kudharauliwa — kwa kawaida kwa kuwapanga watu au vitu visivyo vya haki.",
     "Kupanga ndugu kwa \"nani Mama anampenda zaidi\" ni mchezo wa kuchochea chuki ambao hakuna anayepaswa kucheza.",
     "wivu", "kutazama (kwa nia mbaya)"),
    ("Mtu wa cheo au hadhi ya chini; msaidizi.",
     "Mtu chini katika mnyororo wa amri au ngazi ya kijamii — mdogo, anayefanya kazi chini ya mwenye nguvu zaidi.",
     "Kama afisa mdogo mchanga, alipokea maagizo muda mrefu kabla hajawahi kuyatoa.",
     "chini", "badala, mwingine"),
    ("Kuhisi au kueleza chuki kali.",
     "Kuchukia kitu kiasi cha kukilaani kwa sauti — chuki mtupu, yenye sauti.",
     "Wanakijiji walimlaani mtoza kodi kila gari lake lilipopita mjini.",
     "nje ya", "takatifu (kulaani nje ya kitakatifu)"),
    ("Kifuniko cha nje asilia, kama ngozi au ganda.",
     "Kifuniko cha kinga cha asili chenyewe — ngozi, ganda, kaka, au ganda la tunda, chochote kinachofunika na kulinda kilicho hai.",
     "Ganda la kobe ni kifuniko cha nje imara ajabu.",
     "juu, juu ya", "kufunika"),
    ("Msafi, mjinga, anayeonyesha unyenyekevu wa mtoto; kinyume cha \"disingenuous\".",
     "Anayeamini waziwazi na kidogo mjinga, bila ajenda iliyofichwa — rahisi kuchanganywa na \"ingenious\" inayomaanisha mwerevu.",
     "Swali lake la unyofu — \"kwa nini mtu angesema uwongo kuhusu hilo?\" — lilionyesha jinsi alivyokuwa na hila kidogo.",
     "ndani, asilia", "kuzaa (aliyezaliwa huru, mwaminifu)"),
    ("Kujali kupita kiasi maelezo madogo au sheria.",
     "Kupotea katika sheria ndogo ukikosa picha kubwa — kuzama katika maandishi madogo ambayo hakuna mwingine anayejali.",
     "Kujali kwake kupita kiasi koma za Oxford kulipotosha mkutano mzima.",
     "mwalimu wa watoto", "tabia au sifa"),
    ("Ukaguzi wa kina, wa makini.",
     "Mtazamo wa kina, usioacha jiwe — kupitia kila undani kwa uangalifu wa kweli.",
     "Baada tu ya ukaguzi wa kina wa vitabu vya hesabu ndipo tofauti ilipotokea.",
     "kupitia, kabisa", "kutafuta, kuchunguza"),
    ("Kutoa pingamizi; kuonyesha kusita.",
     "Kurudisha kwa adabu au kusita badala ya kukubali mara moja — \"I'd rather not\" laini.",
     "Alipoulizwa kusaini bila kusoma, yeye alisita.",
     "kutoka, mbali", "kuchelewesha"),
    ("Inayoonekana kuwa na mantiki kwa uso lakini si kweli.",
     "Inasikika kushawishi kwa mtazamo wa kwanza lakini inaporomoka unapoikagua kweli.",
     "\"Everyone's doing it\" ni hoja yenye mvuto wa uwongo isiyoshika chini ya ukaguzi.",
     "muonekano, sura", "imejaa (inayoonekana nzuri)"),
    ("Mazungumzo yasiyo ya kweli, ya unafiki, mara nyingi ya kuhubiri maadili.",
     "Mazungumzo yanayosikika ya wema lakini hayana hisia za kweli — mkao wa maadili wa kiotomatiki.",
     "Alichoka na unafiki wa kampuni kuhusu \"familia\" kutoka kampuni isiyowahi kutoa likizo kwa yeyote.",
     "kuimba (baadaye: jargon ya sauti)", "mlio wa waombaji, kisha unafiki"),
    ("Mwenye ukosefu wa ujasiri, mwoga.",
     "Mwenye woga kiasi cha kutokuwa na uti wa mgongo — anaogopa sana kusimama hata linapojali wazi.",
     "Ukimya wa woga wa bodi uliruhusu kashfa izunguke nje ya udhibiti.",
     "ndogo sana", "roho, ujasiri"),
    ("Kama mbweha; mjanja, werevu.",
     "Mjanja na mwerevu kama mbweha — mwenye akili haraka, kidogo wa siri, daima hatua moja mbele.",
     "Alitoa tabasamu kama la mbweha mara tu alipoona pengo la sheria.",
     "mbweha", "ya au kama"),
    ("Moja baada ya nyingine, kwa mfululizo.",
     "Inachukuliwa kwa ukali moja kwa moja, kwa utaratibu — bila kuruka, bila kufanya mbili kwa pamoja.",
     "Hakimu alishughulikia kila moja ya madai kumi na mawili moja baada ya nyingine.",
     "safu, mfululizo", "moja kwa moja"),
    ("Uchumi mkali; ubahili.",
     "Kuwa mkali kwa pesa (au maneno, au rasilimali) kupita kiwango cha kuokoa kinachofaa.",
     "Ubahili wake ulikuwa hadithi — alitumia mifuko ya chai tena mara tatu.",
     "kuokoa, kuwa mwangalifu", "hali au tabia"),
    ("Marekebisho, hasa katika maandishi.",
     "Marekebisho ya andiko — kugusa kwa kitaaluma kurekebisha kosa katika maandishi ya kale au muhimu.",
     "Toleo jipya linajumuisha marekebisho kadhaa kwa hati asili.",
     "nje ya", "kosa, kosa"),
    ("Mwenye kiasi katika kula na kunywa.",
     "Anayejizuia kwa makusudi kuhusu chakula na kinywaji — hashindi kamwe, daima anaacha kidogo sahani.",
     "Tabia zake za kiasi zilimweka mkali muda mrefu baada ya wenzake kupungua kasi.",
     "mbali na", "kinywaji chenye kilevi"),
    ("Kosa la sarufi au uvunjaji wa adabu.",
     "Kuteleza katika sarufi au adabu — aina ya kosa dogo linalomfanya mtu mkali akune.",
     "\"Between you and I\" ni kosa la sarufi la kawaida bado linalowafanya wataalamu wa sarufi washtuke.",
     "mji wa Cilicia maarufu kwa Kigiriki 'kibaya'", "tabia, namna"),
    ("Kuhusu mgogoro ndani ya kundi; unaoharibu pande zote.",
     "Vita vya ndani vinavyorarua kundi kutoka ndani — pambano ambapo kila mtu anapoteza, kwa sababu familia inapigana na familia.",
     "Mabishano ya ndani kwa ndani ya chama yalidhuru zaidi kuliko mpinzani yeyote wa nje.",
     "kati, kati ya", "kuua"),
    ("Tabia ya kutojali, ya uzembe.",
     "Kuinua mabega kunakuwa nafsi yote — kujali kidogo kiasi kwamba hakuna kinachoonekana kinafaa juhudi tena.",
     "Tabia yake ya kutojali kuelekea sherehe ya tuzo ilishangaza kila aliyejua jinsi alivyofanya kazi kwa bidii.",
     "kidogo", "kujali"),
    ("Hali au mzozo uliochanganyikiwa na mgumu.",
     "Hali iliyochanganyikiwa, chafu, ngumu kuelewa — sehemu kutoelewana, sehemu drama, yote mkanganyiko.",
     "Mvurugano wote wa ramani ya viti ulianza kwa kadi moja ya jina iliyowekwa vibaya.",
     "ndani", "kuchanganya, kufanya mkanganyiko"),
    ("Inayotishia, inayotisha.",
     "Inayohema tisho lisilokoseka — mtazamo au barua ya kutishia inafanya wazi kabisa kitu kibaya kinaweza kufuata.",
     "Sauti ya kutishia ya barua ilimfanya mpangaji aogope kabla hata hajafungua bahasha.",
     "kutisha", "kutumika kwa"),
    ("Ukosoaji mkali wa umma au matusi.",
     "Hukumu ya umma yenye sauti — aina ya ukosoaji unaowaka unaofanyika mbele ya kila mtu.",
     "Mtoaji taarifa alikabili miaka ya lawama za umma kabla historia kumthibitisha kuwa sahihi.",
     "dhidi", "kusema"),
    ("Mlipuko wa ghafla mkali, wa hisia au hatua.",
     "Mlipuko wa ghafla, mkali unaokumeza mara moja — kicheko, hasira, au kikohozi kinachokuja kama wimbi.",
     "Alishikwa na mlipuko wa kicheko ambao hakuweza kueleza kwa mwingine yeyote chumbani.",
     "zaidi ya", "kali, mkali"),
    ("Imeongezwa kutoka chanzo cha nje, si asilia.",
     "Imeunganishwa kutoka nje badala ya kujengwa tangu mwanzo — nyongeza, si kiini.",
     "Maelezo yanaonekana kuwa yameongezwa kutoka nje, kama yalibandikwa kwenye maandishi yaliyokwisha.",
     "kwa, nyongeza", "kuidhinisha, kuchukua"),
    ("Ukosefu wa maarifa, ujinga.",
     "Kutojua tu — pengo la maarifa, bila hukumu iliyounganishwa.",
     "Alikiri ujinga wake wa divai ya Kifaransa na kumwacha sommelier achague.",
     "si", "kujua"),
    ("Kuvutiwa kupita kiasi na mambo ya ngono.",
     "Udaku wenye hamu, wa kutazama, kuhusu chochote chenye rangi — hamu iliyopita afya kuwa ya kujichungulia.",
     "Udadisi wa ngono wa gazeti la uvumi juu ya maisha ya faragha ya wanandoa ulikaribia kuwa wa kuzama.",
     "kuwasha, kutamani", "hali"),
    ("Yenye masizi, nyeusi, yenye ukungu.",
     "Nyeusi na inayoonekana ya moshi, kama kila kitu kimefunikwa na masizi nyembamba.",
     "Ukungu wa masizi ulining'inia juu ya mji wa kiwanda jioni.",
     "masizi", "imejaa"),
    ("Kukanusha au kupinga.",
     "Kuzungumza moja kwa moja dhidi ya kile mtu mwingine alisema — kusema \"that's not so\".",
     "Hakuna aliyethubutu kupinga hadithi ya nahodha mzee kuhusu dhoruba.",
     "dhidi", "kusema"),
    ("Uvivu, ulegevu (kutoka Kilatini).",
     "Neno la kale la Kilatini kwa uvivu mtupu — mvuto wa kutotaka kufanya chochote.",
     "Watawa walihubiri dhidi ya uvivu kama moja ya hatari za kimya za roho.",
     "si", "mwenye shughuli, mchapakazi"),
    ("Ngao inayoonyesha nembo.",
     "Nembo yenye umbo la ngao inayoonyesha nembo ya familia — \"bamba la jina\" la silaha.",
     "Ngao ya nembo ya familia bado inaning'inia juu ya mlango wa mbele wa nyumba kubwa ya kale.",
     "ngao", "kidogo / kitu"),
    ("Iliyopitwa na wakati, iliyochakaa, au iliyostaafu kwa sababu ya umri.",
     "Iliyopita kilele chake cha manufaa na kuachwa shambani — ya kale sana au iliyochakaa kuendelea kufanya kazi.",
     "Printa iliyochakaa hatimaye ilibadilishwa baada ya miaka kumi na tano ya kuziba.",
     "zaidi ya", "mwaka"),
    ("Mbadala, hasa katika dawa.",
     "Tiba za mbadala zinapotumiwa tiba ya kweli haipo — kimsingi wachezaji wa akiba wa tiba.",
     "Madaktari wa wakati wa vita mara nyingi walitegemea dawa mbadala pale dawa sahihi zilipoisha.",
     "mahali pa", "kwenda, kutoa njia"),
    ("Mazungumzo ya kujisifu, ya kiburi.",
     "Kujisifu kubwa, kwa sauti — kuzungumza kwa sauti juu ya ukuu wako mwenyewe ambayo ni hewa zaidi.",
     "Majivuno yake kuhusu \"peke yake\" kuokoa mradi hayakumdanganya yeyote aliyekuwa pale kweli.",
     "shujaa mwenye kujisifu katika Orlando Furioso", "tendo, kuonyesha"),
    ("Kutumia hila au udanganyifu kufikia kitu.",
     "Kujikunja kuelekea lengo kupitia hila badala ya mchezo wa haki.",
     "Aliingia katika mpango kwa hila, kwa mkataba uliojaa maandishi madogo.",
     "kubishana, kudanganya", "hila; baadaye zamu kali"),
    ("Sayansi safi au dhahania ya kujifunza au maarifa, mara nyingi hisabati.",
     "Kujifunza katika umbo lake safi kabisa, dhahania kabisa — muundo wa kina wa maarifa yenyewe, hasa ya hisabati.",
     "Mwanafalsafa aliota sayansi ya jumla ya maarifa inayoweza kuunganisha kila uwanja wa maarifa.",
     "kujifunza", "tendo la kujifunza"),
    ("Anayejali kupita kiasi sheria rasmi au maelezo madogo.",
     "Mkali kupita kiasi kwa mambo madogo — kurekebisha maelezo madogo ya kiufundi ambayo hayabadilishi chochote.",
     "Ilihisi kuwa ukaidi wa kanuni kidogo kubishana \"who\" dhidi ya \"whom\" katika ujumbe.",
     "mwongoza mtoto, mwalimu", "kuwa na namna ya"),
    ("Mwanga unaomulika, unaong'aa.",
     "Mwanga wa haraka unaong'aa — fikiria jua likiruka juu ya maji, au almasi ikishika mwanga.",
     "Mng'ao wa taa ya dari ulitawanya mwanga kila pembe ya ukumbi wa densi.",
     "kung'aa, kuwaka", "tendo hilo"),
    ("Mwanzo, mgeni.",
     "Mtu mpya kabisa kwa ujuzi au uwanja — bado anajifunza kamba, si mtaalamu bado.",
     "Hata mchezaji mgeni wa sataranji anaweza kuona kosa hilo.",
     "mwandani, mwanzo", "askari mchanga mbichi"),
    ("Mbaya sana, ya kuchukiza.",
     "Mbaya kwa njia inayostahili chuki ya kweli — si tu \"wastani,\" bali ya kuchukiza kweli.",
     "Mkaguzi aliuita mwendelezo wa kuchukiza, na nambari za tiketi zilikubali.",
     "kulaani", "inayostahili, inayoweza"),
    ("Rangi nyekundu ya damu.",
     "Nyekundu ya kina, hai — rangi ya damu mbichi, maarufu kutoka Macbeth wa Shakespeare.",
     "Machweo yaligeuza mbingu yote mwanga mwekundu wa damu.",
     "ndani", "nyama (nyekundu ya nyama)"),
    ("Pengo dogo au nafasi kati ya vitu.",
     "Nafasi ndogo kati inayopita kwa urahisi — ufa kati ya mbao za sakafu, pengo katika ratiba.",
     "Magugu yalisukuma juu kila pengo katika njia ya matofali ya kale.",
     "kati", "kusimama"),
    ("Maoni makali au ya kukemea.",
     "Maoni makali, yasiyokubali — aina ya ukosoaji wenye sauti ya kukemea.",
     "Lawama za profesa kwenye insha zilijaza kingo kwa wino mwekundu.",
     "akili", "kugeukia"),
    ("Isiyoweza kukanushwa, isiyopingika.",
     "Imethibitishwa imara kiasi kwamba hakuna kubishana — kesi imefungwa.",
     "Ushahidi wa DNA haukuweza kukanushwa, na kesi iliisha ndani ya saa.",
     "si", "kupinga, kupinga"),
    ("Ugumu, uchanganyiko; pia kujikunja ndani.",
     "Ugumu uliojikunja ndani yake — vitu vilivyofungwa kwa nguvu kiasi ni vigumu kuvitenganisha.",
     "Uchanganyiko wa hadithi uliacha nusu ya hadhira wakijaribu kufungua baada ya sifa.",
     "ndani, kuelekea ndani", "kukunja, kugeuza"),
    ("Nguvu au juhudi, kama katika \"by dint of\".",
     "Juhudi au nguvu tu — leo inaishi karibu tu katika kishazi \"by dint of\".",
     "Alipita mtihani kwa nguvu ya mazoezi magumu ya kudumu.",
     "pigo, mpigo", "kwa nguvu ya"),
    ("Imeunganishwa kwa kiungo cha tundu na ulimi; imewekwa imara.",
     "Imefungwa kwa njia ya seredani ya kale — kipande kimoja kinaingia vizuri kwenye tundu lililokatwa kwa ajili yake.",
     "Mihimili ya ghalani ya kale iliunganishwa kwa tundu na ulimi bila msumari mmoja.",
     "tundu, shimo", "kuuma, kushika"),
    ("Inayofaa sana, inayolingana.",
     "Inayotoshea kabisa wakati — maoni, nukuu, au mfano unaotua kamili kwenye hoja.",
     "Maoni yake yanayofaa yalifupisha mjadala wote katika sentensi moja.",
     "kwa", "kuweka"),
    ("Inayong'aa taratibu au kutetemeka (mwanga); pia akili nyepesi.",
     "Inayong'aa taratibu badala ya kuwaka — mwanga laini unaotetemeka, au akili inayocheza badala ya kuwa kali.",
     "Mwanga wa mshumaa ulitupa mwanga unaotetemeka katika chumba cha kulia cha kale.",
     "kulamba", "kufanya (mwanga unao'lamba')"),
    ("Mkaapweke wa dini anayeishi peke yake.",
     "Mtu anayejiondoa kabisa kutoka ulimwengu kuishi peke yake katika sala na tafakari.",
     "Mkaapweke aliishi katika seli ndogo iliyounganishwa na kanisa kwa zaidi ya miaka thelathini.",
     "nyuma, mbali", "kujiondoa"),
    ("Kutosheleza kiu; kuzima.",
     "Kutosheleza kabisa hamu — mara nyingi kiu, lakini kwa sitiari hamu au hitaji lolote la kina.",
     "Kioo kimoja cha maji baridi kilizima kiu yake baada ya matembezi marefu.",
     "legevu, huru", "kulegeza, kutuliza"),
    ("Yenye umbo la sindano.",
     "Ndefu, nyembamba, na ncha kama sindano — umbo la sindano ya paini au kioo kidogo chenye ncha.",
     "Miti ya paini ni rahisi kutambua kwa majani yake yenye umbo la sindano.",
     "sindano", "kidogo"),
    ("Iliyokauka nguvu, dhaifu, iliyosafishwa kupita kiasi.",
     "Iliyochakaa na laini — imepoteza nguvu au uchangamfu wake asilia kwa starehe au usafi kupita kiasi.",
     "Wakosoaji waliita gazeti lililokuwa jasiri kuwa limekauka nguvu, kivuli cha miaka yake ya kwanza ya ujasiri.",
     "nje", "yenye matunda, iliyozaliwa"),
    ("Kifuasi au haki ndogo iliyounganishwa.",
     "Nyongeza ndogo inayokuja ikiwa imefungwa kwenye kitu kikubwa zaidi — vifaa na nyongeza zinazomilikiwa na kitu kikuu.",
     "Kukodisha kulijumuisha gereji na vifuasi vyake vyote.",
     "kwa", "kumiliki"),
    ("Kufunika au kupunguza kosa.",
     "Kulainisha kosa kwa maneno laini, kulifanya lisikike dogo kuliko lilivyo.",
     "Alijaribu kufunika tarehe ya mwisho iliyokosa kwa mazungumzo yasiyo wazi kuhusu \"changamoto zisizotarajiwa\".",
     "ufafanuzi, maelezo", "kutoa maoni — kisha kulainisha"),
    ("Katika hatua ya mapema, inaanza tu.",
     "Inaanza tu kujionyesha — hatua ya kwanza kabisa, karibu isiyoonekana, ya kitu kikubwa kinachokuja.",
     "Madaktari walishika ishara za mwanzo za ugonjwa kabla haujaenea.",
     "juu, ndani", "kuchukua (kununua, kuanza)"),
    ("Msukumo wa ubunifu, hasa wa kimungu.",
     "Msukumo wa ghafla wa msukumo unaohisi mkubwa kuliko wewe — kama wazo lilipulizwa ndani yako kutoka mahali pengine.",
     "Mshairi alieleza kazi yote ilifika katika mlipuko mmoja wa msukumo saa tisa usiku.",
     "kwa, juu", "kuvuma (kupuliza juu)"),
]
