# Lithuanian rows
ROWS = [
    ("Saldinti arba valyti; pašalinti ko nors aštrumą.",
     "Išimti geluonį ar kartumą — tiesiogine prasme saldinant arba perkeltine švelninant aštrią mintį, kad ji lengviau nuslystų.",
     "Redaktorius sušvelnino aštrią recenziją, prieš jai išeinant į spaudą.",
     "lauk, kruopščiai", "saldus"),
    ("Per daug arba apsimestinai religingas ar pamaldus.",
     "Apibūdina ką nors, kieno religinis atsidavimas atrodo vaidinamas publikai — daugiau spektaklis nei tikras tikėjimas.",
     "Jo pietistiniai atodūsiai per pamokslą erzino visą suolą.",
     "pamaldumas, pareigingumas", "turintis pobūdį"),
    ("Dviprasmybė, kylanti iš gramatinės sandaros — sakinys, kurį galima skaityti dvejopai.",
     "Sakinys, kuris gramatiškai taisyklingas, bet jį galima suprasti dviem visai skirtingais būdais, kaip \"I saw the man with the telescope.\"",
     "\"Visiting relatives can be tiring\" yra klasikinė amfibolija — ar vargina giminės, ar pats jų lankymas?",
     "abu, iš abiejų pusių", "mesti"),
    ("Aštrus, taiklus, kertantis tiesiai į esmę.",
     "Kerta kiaurai tuščius žodžius — aštri pastaba ar protas greitai pasiekia dalyko širdį, be pertekliaus.",
     "Jos aštri kritika nepaliko filmo siužeto spragoms kur slėptis.",
     "pjauti", "veikiantis, turintis savybę"),
    ("Tik prasidedantis; ankstyvoje ar užuomazginėje stadijoje.",
     "Dar atidarymo akimirkose — planas, jausmas ar procesas, kuris tik pradėjo įgauti pavidalą.",
     "Pradiniai sutarties etapai buvo daug žadantys, bet daug kas dar liko neišspręsta.",
     "pradėti, imtis", "linkstantis į"),
    ("Formali kalba ar rašinys, aukštai giriantis ką nors.",
     "Visapusiškas, formalus pagyrimas — pagalvok apie spindintį nekrologą ar kalbą, kuri gieda kieno nors nuopelnus nuo stogų.",
     "Išeinančią profesorę palydėjo panegirika iš artimiausių studentų.",
     "viskas", "susirinkimas, sueiga"),
    ("Susijęs su tikra būtimi ar faktiniu buvimu, priešingai abstrakčiai teorijai.",
     "Apie daiktus taip, kaip jie iš tikrųjų egzistuoja, ne tik kaip idėjos ar teorijos apie juos.",
     "Filosofai ginčijasi, ar skaičiai turi kokį ontinį statusą, ar egzistuoja tik mūsų galvose.",
     "būtis, tai kas yra", "susijęs su"),
    ("Duoti vaisių arba tapti produktyviam.",
     "Pagaliau atsipirkti — pastanga, idėja ar investicija, kuri duoda vaisių, išaugo iš sėklos į ką nors naudingo.",
     "Metų metus trukę ramūs tyrimai pagaliau davė vaisių — veikiančią vakciną.",
     "vaisius", "daryti, sukelti"),
    ("Numatantis ar vaizduojantis ką nors kaip jau įvykusį, kol tai dar nėra įvykę.",
     "Literatūriškai užbėgti už akių — aprašyti būsimą įvykį tarsi jis jau būtų pasibaigęs, kad mintis smogtų stipriau.",
     "Generolo išankstinis tostas už \"pergalę\" buvo pasakytas visą savaitę prieš mūšį.",
     "prieš", "imti, nutverti"),
    ("Varomas oro slėgiu; taip pat susijęs su dvasia ar kvėpavimu.",
     "Paprastai reiškia \"varomas suslėgtu oru\" — nors gali reikšti ir susijusį su dvasia ar kvėpavimu.",
     "Pneumatiniai stabdžiai šnypštė, kai autobusas privažiavo prie šaligatvio.",
     "vėjas, kvėpavimas, dvasia", "susijęs su"),
    ("Dievą ar dieviškumą apibūdinantis teigiamais teiginiais — apofatinio priešingybė.",
     "Būdas kalbėti apie Dievą sakant, kas Dievas yra — \"God is love\" —, o ne tik kas Dievas nėra.",
     "Katafatinė teologija drąsiai kalba apie Dievą kaip mylintį, teisingą ir gailestingą.",
     "žemyn, pagal", "kalbėti, sakyti"),
    ("Paremta pasitikėjimu ar tikėjimu; taip pat kaip fiksuotas atskaitos taškas.",
     "Kažkas, ką priimi pasitikėdamas ir tada naudoji kaip inkarą — atskaitos žymė yra fiksuotas taškas, pagal kurį matuojama visa kita.",
     "Matininkai padėjo atskaitos žymeklį uolienoje prieš kartografuodami vietą.",
     "pasitikėti", "pasitikėjimas, tikrumas"),
    ("Dievo gerumo gynimas, atsižvelgiant į blogio egzistavimą.",
     "Senovinis bandymas atsakyti: \"If God is good, why does evil exist?\"",
     "Jos disertacija nagrinėjo teodicėją per Jobo knygos prizmę.",
     "dievas", "teisingumas"),
    ("Abipusis gyvenimas vienas kitame — teologinis terminas, kaip Trejybės asmenys egzistuoja vienas kitame.",
     "Teologijos žodis tokiai visapusiškai trijų-viename bendrystei, kad kiekviena dalis visiškai talpina ir yra talpinama kitose.",
     "Perichorezės doktrina bando paaiškinti, kaip Tėvas, Sūnus ir Dvasia yra skirtingi, bet neatskiriami.",
     "aplink", "eiti, vaikščioti"),
    ("Turėti pasekmes, kurios naudingos ar atsispindi kam nors.",
     "Kai pagyrimas (ar kaltė) atšoka atgal ant atsakingojo — geri darbai, kurie atitenka tavo reputacijai, sugrįžta su atlygiu.",
     "Komandos sėkmė atiteks ramaus, darbštaus trenerio garbei.",
     "atgal, vėl", "banga"),
    ("Tokio, kurio negalima išvengti ar pabėgti.",
     "Įvyks, kad ir ką darytum — iš neišvengiamos baigties nėra kur išsisukti.",
     "Senatvė ateina visiems; ji tiesiog neišvengiama.",
     "ne", "išsikovoti lauk"),
    ("Vartojantis aplinkinius, žodingus posakius vietoj tiesioginės formos.",
     "Eiti žodžiais ilguoju keliu — sakyti \"make a decision\" vietoj \"decide.\"",
     "Jo perifrastiniai laiškai galėjo viena eilute pasakyti tai, kam jis skyrė tris pastraipas.",
     "aplink", "skelti, pasakoti"),
    ("Protinis bukumas ar letargija.",
     "Tas miglotas, vangus proto būvis, kuriame mąstymas jaučiasi kaip bridimą per sirupą.",
     "Bukumo banga užplūdo klasę tuoj po pietų.",
     "bukas, atšipęs", "būsena ar savybė"),
    ("Nepatankus; blogos žinios.",
     "Blogas ženklas — sąlygos ar laikas, kurie atrodo veikiantys prieš tave, dar nespėjus pradėti.",
     "Pilki dangūs ir išsikrovęs automobilio akumuliatorius sudarė nepalankią kelionės pradžią.",
     "ne", "palankus, maloningas"),
    ("Mėsa, troškinta padaže — taisyklingai rašoma \"fricasseed.\"",
     "Jaukus senas maisto žodis mėsai, kuri supjaustyta ir lėtai troškinta savo padaže, kol suminkštėja.",
     "Močiutės frikasė vištiena buvo kiekvienos sekmadienio vakarienės žvaigždė.",
     "kepti", "laužyti (gabalais)"),
    ("Dirbtinis ar prastesnis pakaitalas.",
     "Padirbinys tikrojo vietoje — techniškai atlieka darbą, bet visiems matyti, kad tai ne originalas.",
     "Karinio meto pirkėjai tenkinosi pakaitine kava iš skrudintų cikorijų.",
     "lauk, pakeitimo priešdėlis", "dėti, statyti"),
    ("Traktuoti abstrakčią idėją tarsi ji būtų konkretus daiktas.",
     "Padaryti, kad idėja jaustųsi tikra ir kieta — paversti ką nors migloto, kaip \"the economy,\" daiktu, į kurį galima parodyti.",
     "Vadinti tautos \"dvasią\" savarankiška būtybe reiškia sudaiktinti tai, kas iš tikrųjų yra milijonai atskirų pasirinkimų.",
     "daiktas", "daryti"),
    ("Sumaniai pabėgo ar išvengė.",
     "Švariai paspruko — išsisuko nuo ko nors, dažnai gudriai ar vos vos, ar tai būtų suėmimas, klausimas, ar atsakymas.",
     "Atsakymas slydo jai iš rankų valandomis, kol staiga spragtelėjo duše.",
     "lauk, šalin", "žaisti"),
    ("Išreiškiantis abejonę, sumišimą ar neišspręstą prieštaravimą.",
     "Įstrigęs tikrame minties aklavietėje — ne iš tingumo, o todėl, kad pats klausimas priešinasi tvarkingam atsakymui.",
     "Sokratas dažnai baigdavo dialogus aporetine nata, su daugiau klausimų nei atsakymų.",
     "be", "kelias, perėja"),
    ("Kalbos figūra, įvardijanti ką nors susijusiu žodžiu, pvz., \"the crown\" monarchui.",
     "Naudoti susijusį žodį tikrojo vietoje — sakyti \"the White House announced,\" kai turi omenyje administraciją.",
     "\"Wall Street had a rough day\" yra metonimija — iš tikrųjų tai reiškia, kad sunkią dieną turėjo akcijų rinka.",
     "kaita, po", "vardas"),
    ("Išrauti su šaknimis; atplėšti nuo natūralios aplinkos.",
     "Ištraukti ką nors (ar ką nors) su šaknimis, šalin nuo vietos ar kultūros, kuriai priklauso.",
     "Karas išrovė su šaknimis visą kartą, išblaškydamas šeimas per sienas.",
     "šalin, nuo", "šaknis"),
    ("Maloniai skambantis.",
     "Tiesiog malonu girdėti — skambus žodis, vardas ar sakinys rieda ausiai sklandžiai, beveik muzikaliai.",
     "\"Murmuring brook\" yra skambus mažas posakis — švelnus ir lengvai ištariamas.",
     "geras, gerai", "garsas, balsas"),
    ("Visuotinai laikomas ar manomas esąs.",
     "Plačiai tikima esant tiesa, net jei dar neįrodyta — \"tariama\" versija apie ką nors.",
     "Tariamas laiško autorius vėliau pasirodė esąs visiškai svetimas žmogus.",
     "galvoti, laikyti", "turintis prigimtį"),
    ("Naujai sugalvotas žodis ar frazė.",
     "Visai naujas žodis — ką tik išrastas, dar (ar vos) ne žodyne.",
     "\"Doomscrolling\" prasidėjo kaip naujadaras ir greitai tapo kasdieniu slengu.",
     "naujas", "žodis, kalba"),
    ("Piktas ar blogo būdo.",
     "Blogoje, irzlioje nuotaikoje — greitai pyksta, kaip kadaise tikėta, kad blužnis valdo temperamentą.",
     "Jis išsiuntė tulžingą atsakymą laiškui per kelias sekundes po perskaitymo.",
     "blužnis (pykčio buveinė)", "veikiamas"),
    ("Linkęs moralizuoti išdidžiai ar apsimestinai.",
     "Mėgsta teikti mažas gyvenimo pamokas savimylos būdu, tarsi kiekvienas sakinys būtų laimės sausainis.",
     "Jo pamokslaujantis tostas apie \"tikrąją draugystės prasmę\" privertė visus žvilgtelėti į laikrodžius.",
     "nuomonė, maksima", "pilnas"),
    ("Per daug šnekus, ypač apie smulkmenas.",
     "Tiesiog nesiliauja plepėti — plepa apie smulkmenas gerokai po to, kai visiems kitiems baigėsi žodžiai.",
     "Plepus taksistas papasakojo visą savo gyvenimo istoriją, dar nespėjus palikti oro uosto.",
     "plepėti, taukšti", "linkęs į"),
    ("Kvailystė, paikyba.",
     "Paprasta kvailystė — pastaba ar planas toks kvailas, kad vos nusipelno rimto atsakymo.",
     "Gryna plano kvailybė tapo akivaizdi tą akimirką, kai jie jį išbandė.",
     "kvailas, paikas", "buvimo būsena"),
    ("Kalbos baigiamoji dalis, dažnai santrauka.",
     "Kalbos didysis finalas — baigiamoji dalis, kurioje kalbėtojas viską surenka ir įkala mintį namo.",
     "Iki baigiamosios kalbos pusė publikos jau stovėjo ant kojų.",
     "kiaurai, iki galo", "kalbėti, ginti"),
    ("Bereikalingas tos pačios minties kartojimas kitais žodžiais.",
     "Sakyti tą patį du kartus nieko naujo nepridedant, kaip \"free gift\" ar \"end result.\"",
     "\"It is what it is\" yra mėgstama tautologija tų, kurie vengia tikro paaiškinimo.",
     "tas pats", "žodis, kalba"),
    ("Labai nedaug žodžių vartojimas; lakoniška kalba.",
     "Daug pasakyti su labai mažai — trumpo, stačiokiško atsakymo menas, pavadintas pagal garsiai trumpareikius Lakonijos spartiečius.",
     "\"Molon labe\" — \"ateikite ir pasiimkite\" — yra garsiausias istorijos lakonizmo pavyzdys.",
     "Lakonijos spartietis", "praktika, būdas"),
    ("Blankios, pernelyg supaprastintos idėjos; iš pradžių — blankus maistas ar košė.",
     "Plonas, atskiestas mąstymas — turinys toks supaprastintas ir saugus, kad protui nėra jokios maistinės vertės.",
     "Politiko kalba buvo daugiausia tuščiažodžiavimas: migloti pažadai, prie kurių nieko neprikabinsi.",
     "maitinti", "priemonė ar įrankis"),
    ("Sukeliantis miegą ar mieguistumą.",
     "Toks nuobodus — ar tiesiogine prasme raminantis —, kad užmigdo. Pagalvok apie šiltą pieną ar trijų valandų biudžeto posėdį.",
     "Paskaitos migdantis dūzgesys privertė pusę salės kovoti, kad palaikytų akis atmerktas.",
     "gilus miegas", "darantis, keliantis"),
    ("Per daug meilikaujantis ar riebus maniera.",
     "Toks glotniai žavus, kad atrodo slidus — meilikavimas užteptas taip storai, kad beveik jauti riebalus.",
     "Meilikaujantis pardavėjas vis gyrė mano \"puikų skonį\" prieš kiekvieną papildomą pardavimą.",
     "tepti, aliejuoti", "pilnas"),
    ("Greitai randa klaidų, pernelyg kritiškas smulkmenoms.",
     "Kabus iki klaidos — toks, kuris randa problemą visame, net kai tai iš tikrųjų nesvarbu.",
     "Jo priekabios pastabos prie ataskaitos telkėsi tik į kablelių išdėstymą.",
     "nutverti, imti", "spąstai, sofizmas"),
    ("Vangus, protiškai ar fiziškai neaktyvus.",
     "Lėtas ir pusiau miega, kaip lokys žiemos miege — vos juda, vos galvoja.",
     "Biuras apsnūdo rugpjūčio sunkioje kaitroje.",
     "būti nutirpusiam, būti vangiam", "būsenoje"),
    ("Seniūnas ar pareigūnas, tvarkęs viduramžių ūkį.",
     "Viduramžių personalo vadovo versija — patikimas pareigūnas, kasdien vadovavęs lordo namams ir dvarui.",
     "Pilies seneskalas tvarkė viską nuo derliaus apskaitos iki svečių sąrašo.",
     "senas, vyresnysis", "tarnas"),
    ("Kalbėti ar rašyti ilgai apie temą.",
     "Iš tikrųjų įsibėgėti tema — kalbėti ar rašyti ir rašyti, apžvelgiant ją iš visų pusių.",
     "Paklausk jo apie senovinius automobilius, ir jis plėtos temą visą valandą.",
     "lauk", "erdvė"),
    ("Bevertis, menkas; taip pat negaliojantis ar neveiksmingas.",
     "Vertas praktiškai nieko — negaliojanti sąlyga sutartyje yra tokia, kuri iš tikrųjų nieko nedaro.",
     "Teismas pripažino seną taisyklę negaliojančia, nes ji niekada nebuvo iš tikrųjų taikoma.",
     "smulkmenos, nesąmonės", "priklausantis"),
    ("Išmintis, įžvalgus sprendimas.",
     "Aštri, praktinė išmintis — toks geras sprendimas, kuris ateina iš patirties, ne tik iš knygų.",
     "Seno kapitono įžvalgumas ne kartą išgelbėjo įgulą nuo bėdų.",
     "aštrios uoslės, įžvalgus", "savybė"),
    ("Paprasta minia ar masės, vartojama paniekinamai.",
     "Išdidus, paniekinantis žodis \"miniai\" ar paprastiems žmonėms, vartojamas su panieka.",
     "Grafas šaipėsi iš prasčiokų, susirinkusių prie rūmų vartų.",
     "šuo", "visuma, gauja"),
    ("Įžūlus, žeminantis elgesys ar kalba.",
     "Žiaurus, paniekinantis elgesys, skirtas pažeminti — toks įžeidimas, kuris sukurtas gelti.",
     "Jis kentė metų paniekinimą iš kritikų, kol jo darbas pagaliau buvo pripažintas.",
     "su, kruopščiai", "pūstis (iš puikybės)"),
    ("Su įtarimu ar nepritarimu; žvilgsnis į šoną.",
     "Tas žvilgsnis į šoną, kurį duodi kam nors, kuo visai nepasitiki — žvilgsnis, pilnas abejonių.",
     "Mokytoja kreivai pažvelgė į įtartinai tvarkingą namų darbą.",
     "į, prie", "nuolydis, šališkumas"),
    ("Kvailas žmogus; mulkis.",
     "Senas, beveik meilus įžeidimas kam nors, kas bukas ar tankus — kelmo galva.",
     "\"Tu mulki,\" ji juokėsi, \"tu visą laiką laikei žemėlapį aukštyn kojomis.\"",
     "žemės gniužulas", "galva"),
    ("Paleisti į judesį ar veiksmą; motyvuoti.",
     "Būti kibirkštimi, kuri ką nors paleidžia — ar tai mašina, kuri įsijungia, ar žmogus, kuris pagaliau ima veikti pagal idėją.",
     "Baimė prarasti sutartį paskatino visą komandą savaitgalio viršvalandžiams.",
     "darymas, varymas", "varyti, daryti"),
    ("Patikėtų lėšų pasisavinimas.",
     "Tylus pinigų, kuriais tau patikėta rūpintis, vagystė — pasisavinimas senu paltu.",
     "Iždininko grobstymas liko nepastebėtas beveik dešimtmetį.",
     "privati nuosavybė", "galvijai, turtas"),
    ("Grupė, laikoma gerbiamos visuomenės paraštėse.",
     "Tas glaistytas, bet šešėlinis socialinis požemis — žmonės, gyvenantys vos už \"gerbiamos\" visuomenės taisyklių.",
     "Romanas seka dainininkę, naršančią 1920-ųjų kabaretų pusiasvietį.",
     "pusė", "pasaulis, visuomenė"),
    ("Vis dar egzistuojantis; neišnykęs ar nesunaikintas.",
     "Vis dar čia šiandien — vartojama seniems daiktams (rankraščiams, rūšims, pastatams), kuriems pavyko išlikti.",
     "Žinomos tik trys išlikusios pirmojo spaudinio kopijos.",
     "lauk", "stovėti"),
    ("Klasta; pasitikėjimo išdavystė.",
     "Gili, sąmoninga išdavystė — sulaužyti pasitikėjimą, kurio kas nors turėjo teisę tikėtis, kad išlaikysi.",
     "Generolas niekada neatleido senojo draugo klastos prie derybų stalo.",
     "kiaurai, prieš", "tikėjimas, pasitikėjimas"),
    ("Regioninė tarmė, ypač nestandartinė.",
     "Savitas, vietinis būdas, kaip žmonės kalba tam tikrame krašte — pilnas žodžių ir ritmų, kurių svetimšalis gali nesuprasti.",
     "Jos močiutė vis dar kalbėjo salos tarme per šeimos vakarienes.",
     "šiurkšti kalba, tarmė", "letena — gremėzdiška kalba"),
    ("Ypatinga teisė, priklausanti asmeniui ar grupei.",
     "Privilegija, kuri yra tavo ir tik tavo — teisė, ateinanti su tavo vaidmeniu, pareigomis ar statusu.",
     "Šeimos atostogų vietos pasirinkimas yra senelio prerogatyva, ir visiems tai žinoma.",
     "prieš", "klausti, balsuoti"),
    ("Drąsa, įžūlumas; taip pat ištvermė.",
     "Šiurkšti, drąsi ištvermė — nervai eiti pirmyn ir tvirtumas tęsti, kai jau pradėjai.",
     "Reikėjo tikros drąsos kirsti perėją pūgoje be žemėlapio.",
     "drąsus, ištvermingas", "būsena, būklė"),
    ("Pražysti; taip pat vystytis ar pamažu pasirodyti.",
     "Pražysti pilna išraiška — kaip gėlė atsiverianti, ar idėja, kuri pagaliau ateina į save.",
     "Jos ramus tapybos talentas pražydo, kai ji turėjo savą studiją.",
     "lauk", "pradėti žydėti"),
    ("Svoris ant virvės vertikalumui nustatyti; perkeltine prasme — sprendimo matas.",
     "Svoris ant virvės, kabantis visiškai stačiai žemyn, kad patikrintum, ar kas nors iš tikrųjų vertikalu — ir, plačiau, bet koks fiksuotas standartas, pagal kurį matuoji visa kita.",
     "Jis naudojo savo senelio sąžiningumą kaip savotišką svambalą kiekvienam sprendimui.",
     "švinas", "virvė, matas"),
    ("Mielai, noriai (archaizmas).",
     "Senas būdas pasakyti \"mielai\" ar \"su malonumu.\"",
     "\"Mielai čia truputį pailsėčiau,\" atsiduso keliautojas.",
     "linksmas, džiaugsmingas", "mielai, noriai"),
    ("Aštri vieša kritika ar gėda.",
     "Vieša gėda, užkrauta kam nors dideliu, matomu būdu — negarbė, ateinanti iš plataus nepritarimo.",
     "Skandalas užtraukė viešą nešlovę visai įmonei.",
     "prieš", "gėda, priekaištas"),
    ("Aštriai sarkastiškas, kandus sąmojyje ar kritikoje.",
     "Sąmojis su tikrais dantimis — kandi pastaba gelia būtent todėl, kad taip gudriai taikyta.",
     "Jos kandžių filmų recenzijų bijojo režisieriai ir mylėjo skaitytojai.",
     "kąsti", "kandantis, veikiantis"),
    ("Formalus paskelbimas, dažnai politinis ar karinis.",
     "Didelis, oficialus pranešimas — paprastai toks, kuris skelbia naują vyriausybę, sukilimą ar svarbų dekretą.",
     "Generolo manifestas aušroje paskelbė naująją vyriausybę.",
     "pirmyn", "skelti"),
    ("Žmogus su paviršinėmis žiniomis, apsimetantis ekspertu.",
     "Kažkas, kas vos palietė temos paviršių ir tada kalba tarsi būtų parašęs vadovėlį.",
     "Vakarienės pusmokslis užtikrintai taisė tikrąjį astrofiziką prie stalo.",
     "žinoti", "mažybinis — mažas žinovas"),
    ("Protinių gebėjimų silpnėjimas senatvėje.",
     "Miglotas, užmaršus labai senos senatvės tarpsnis, kai proto aštrumas ima blėsti.",
     "Senatvinėje silpnystėje jis kiekvieno apsilankymo metu pasakodavo tuos pačius tris pasakojimus, kaskart tarsi naujus.",
     "kvailioti, būti kvailam", "būsena ar rezultatas"),
    ("Pusė, apsaugota nuo vėjo.",
     "Rami, užuovėja pusė ko nors — kalvos, laivo, sienos —, kur vėjas tavęs visai nepasiekia.",
     "Žygeiviai pastatė palapinę keteros pavėjinėje pusėje, kad pabėgtų nuo gūsių.",
     "prieglauda, apsauga", "šonas, veidas"),
    ("Atmušti ar atmesti smūgį, klausimą ar argumentą.",
     "Sklandžiai atmušti ką nors — kardo kirtį, nepatogų klausimą ar kaltinimą — neprarandant ritmo.",
     "Ji atrėmė žurnalisto klastingą klausimą lengvu pokštu.",
     "atremti", "rengtis, gintis"),
    ("Dvokiantis, kenksmingas.",
     "Dvokia taip, kad atrodo beveik nuodinga — smarvė tokia bloga, kad kvėpuoti atrodo pavojinga.",
     "Dvokiantis kvapas kilo iš pelkės saulei leidžiantis.",
     "kenksmingi garai", "turintis prigimtį"),
    ("Žmogus, atsidavęs prabangai ir malonumui.",
     "Kažkas, kas gyvena komfortui ir pasileidimui — geras maistas, minkštos lovos, lengvas gyvenimas — pavadintas pagal senovės graikų miestą Sybaris, garsėjusį pertekliais.",
     "Tikras sibaritas, jis atsisakė bet kokio viešbučio kambario be vonios.",
     "senovės graikų miestas, garsėjęs prabanga", "gyventojas"),
    ("Sąmoningai atidėti į šalį ar ignoruoti dalį ko nors.",
     "Sąmoningai atidėti dėlionės gabalą į šalį, kad švariai susitelktum į likusį.",
     "Atsiribokime nuo kainos akimirkai ir tik paklauskime, ar planas iš viso veikia.",
     "prieš, šalin", "pjauti"),
    ("Griežtai kritikuoti; taip pat nuplėšti odą.",
     "Įplėšti ką nors aštria kritika — žodžiais, tarsi tiesiogine prasme nuplėštum odą.",
     "Kritikai sudirbo tęsinį už tai, kad išdavė viską, ką gerbėjai mylėjo originale.",
     "nuo", "oda, kailis"),
    ("Cituoti kaip įrodymą ar argumentą.",
     "Iškelti faktą ar pavyzdį savo teiginiui paremti — tai, į ką parodai, kai kas nors klausia \"what's your evidence?\"",
     "Advokatė pateikė tris liudytojus kliento alibi paremti.",
     "į, link", "vesti"),
    ("Kelionės ar klaidžiojimai, ypač ilgi ar platūs.",
     "Ilgos, klaidžiojančios kelionės — toks platus klaidžiojimas, kuris nuveda toli nuo namų ilgam.",
     "Jo klajonės per tris žemynus pripildė visą lentyną kelionių dienoraščių.",
     "kiaurai", "laukas, žemė (peregrinus: svetimšalis)"),
    ("Elgeta arba tas, kuris gyvena iš išmaldos.",
     "Kažkas, kas gyvena prašydamas labdaros — istoriškai tai apibūdino ir vienuolius, davusius skurdo įžadus ir gyvenusius iš aukų.",
     "Elgetaujantys vienuoliai nieko neturėjo ir visiškai rėmėsi kaimiečių gerumu.",
     "elgetauti", "elgeta"),
    ("Ypatingai dosnus.",
     "Dosnus grandioziniu, beveik parodomuoju mastu — tokia dovana, kuri priverčia žmones šiek tiek aiktelėti.",
     "Dosni auka finansavo visą naująjį bibliotekos sparną.",
     "dovana, paslauga", "darymas, davimas"),
    ("Išsekimas dėl maisto stokos; taip pat gyvybingumo stoka.",
     "Silpnas, išsekęs būvis nuo to, kad nesi maitinamas ar papildomas — tiesiogine prasme iš bado arba perkeltine nuo to, kad nebeliko kuo veikti.",
     "Apsiausties pabaigoje kariai buvo arti išsekimo.",
     "tuščias, tuštuma", "veiksmas ar rezultatas"),
    ("Kartus, įžeidžianti kritika.",
     "Kritika, seniai peržengusi teisingumo ribą ir tapusi pikta, kartia tirada.",
     "Internetiniai komentarai per kelias minutes subyrėjo į gryną plūdimąsi.",
     "kaltė", "rengti, aprūpinti"),
    ("Priešiškas, žalingas poveikiu.",
     "Veikia prieš tave, net jei tyliai — sąlygos ar požiūris, nedraugiški tavo interesams.",
     "Naujoji politika buvo priešiška mažoms įmonėms, net jei toks nebuvo ketinimas.",
     "ne", "draugas"),
    ("Galintis sukelti apmaudą ar nepasitenkinimą, dažnai per neteisingus palyginimus.",
     "Būtinai privers ką nors jaustis nuskriaustu — paprastai todėl, kad nesąžiningai gretina žmones ar daiktus.",
     "Rikiuoti brolius ir seseris pagal tai, \"ką mama myli labiausiai\", yra įžeidus žaidimas, kurio niekas neturėtų žaisti.",
     "pavydas", "žiūrėti (su pikta valia)"),
    ("Žemesnio rango ar statuso asmuo; pavaldinys.",
     "Kažkas žemiau komandos grandinėje ar socialinėse kopėčiose — jaunesnysis, dirbantis po kuo nors galingesniu.",
     "Kaip jaunas jaunesnysis karininkas jis ilgai gavo įsakymus, kol pats ėmė juos duoti.",
     "po", "kitas, pakaitinis"),
    ("Jausti ar reikšti stiprią neapykantą.",
     "Nekęsti ko nors tiek, kad keiktum balsu — grynas, balsingas pasibjaurėjimas.",
     "Kaimiečiai keikė mokesčių rinkėją kaskart, kai jo vežimas riedėjo per miestelį.",
     "lauk iš", "šventas (keikti lauk iš švento)"),
    ("Natūralus išorinis dangalas, kaip oda ar kiautas.",
     "Gamtos pačios apsauginė pakuotė — oda, kiautas, lukštas ar žievė, kas dengia ir saugo gyvą.",
     "Vėžlio kiautas yra nepaprastai tvirtas dangalas.",
     "ant, virš", "dengti"),
    ("Nekaltas, naivus, su vaikišku paprastumu; priešingybė \"disingenuous.\"",
     "Atvirai pasitikintis ir šiek tiek naivus, be slaptos darbotvarkės — lengva sumaišyti su \"ingenious,\" reiškiančiu gudrus.",
     "Jos naivus klausimas — \"kodėl kas nors dėl to meluotų?\" — parodė, kiek mažai klastos ji turėjo.",
     "viduje, gimtasis", "gimdyti (laisvai gimęs, atviras)"),
    ("Pernelyg didelis rūpestis smulkiomis detalėmis ar taisyklėmis.",
     "Paskęsti smulkiose taisyklėse, paleidžiant didesnį vaizdą — apsėsti smulkiuoju šriftu, kuriuo niekas kitas nesirūpina.",
     "Jo pedantiškumas dėl Oksfordo kablelio sužlugdė visą posėdį.",
     "vaikų mokytojas", "praktika ar savybė"),
    ("Kruopštus, rūpestingas nagrinėjimas.",
     "Gilus, nė-akmens-neapverstas žvilgsnis į ką nors — eiti per kiekvieną detalę su tikru rūpesčiu.",
     "Tik po kruopštaus apskaitos knygų patikrinimo išlindo neatitikimas.",
     "kiaurai, kruopščiai", "ieškoti, nagrinėti"),
    ("Kelti prieštaravimus; rodyti nenorą.",
     "Mandagiai atsispirti ar dvejojoti, o ne iškart sutikti — švelnus \"I'd rather not.\"",
     "Paprašyta pasirašyti neskaičius, ji paprieštaravo.",
     "nuo, šalin", "atidėti"),
    ("Paviršiumi įtikinamas, bet iš tikrųjų klaidingas.",
     "Iš pirmo žvilgsnio skamba įtikinamai, bet subyra tą akimirką, kai iš tikrųjų patikrini.",
     "\"Everyone's doing it\" yra apgaulingai įtikinamas argumentas, kuris niekada visai neišlaiko patikros.",
     "išvaizda, vaizdas", "pilnas (atrodo geras)"),
    ("Nenuoširdi, veidmainiška kalba, dažnai moralizuojanti.",
     "Pamokslaujanti kalba, kuri skamba dorybingai, bet nėra paremta tikru jausmu — moralinė poza autopilotu.",
     "Jis buvo pavargęs nuo įmonės tuščiažodžiavimo apie \"šeimą\" iš kompanijos, kuri niekada neduoda niekam atostogų.",
     "dainuoti (vėliau: monotoniškas žargonas)", "elgetų aimanuojanti kalba, tada veidmainystė"),
    ("Neturintis drąsos, bailus.",
     "Bailus iki stuburo stokos — pernelyg išsigandęs atsistoti, net kai tai akivaizdžiai svarbu.",
     "Valdybos bailus tylėjimas leido skandalui išplisti nekontroliuojamai.",
     "labai mažas", "dvasia, drąsa"),
    ("Lapės pavidalo; klastingas, gudrus.",
     "Klastingas ir gudrus kaip lapė — sąmojingas, šiek tiek slidus, visada žingsniu priekyje.",
     "Jis šyptelėjo lapiška šypsena tą akimirką, kai pastebėjo spragą.",
     "lapė", "iš ar kaip"),
    ("Vienas po kito, seka.",
     "Imama griežtai po vieną, tvarka — be šuolių į priekį, be dviejų vienu metu.",
     "Teisėjas išnagrinėjo kiekvieną iš dvylikos pretenzijų iš eilės.",
     "eilė, seka", "po vieną"),
    ("Ypatingas taupumas; šykštumas.",
     "Būti kietam su pinigais (ar žodžiais, ar ištekliais) gerokai anapus protingo taupumo.",
     "Jo šykštumas buvo legendinis — arbatos maišelius jis naudojo tris kartus.",
     "taupyti, būti taupiam", "būsena ar praktika"),
    ("Pataisa, ypač tekste.",
     "Pataisa rašinyje — mokslinė pataisa, ištaisanti klaidą sename ar svarbiame tekste.",
     "Naujajame leidime yra dešimtys originalaus rankraščio pataisymų.",
     "lauk iš", "kaltė, klaida"),
    ("Saikingas valgant ir geriant.",
     "Sąmoningai santūrus maisto ir gėrimo atžvilgiu — niekada nepersivalgo, visada palieka šiek tiek lėkštėje.",
     "Jo santūrūs įpročiai palaikė jį aštrų gerokai po to, kai bendraamžiai sulėtėjo.",
     "šalin nuo", "svaiginantis gėrimas"),
    ("Gramatinė klaida ar etiketo pažeidimas.",
     "Klaida gramatikoje ar manierose — tokia maža klaida, kuri priverčia pedantą krūptelėti.",
     "\"Between you and I\" yra dažna kalbos klaida, vis dar verčianti gramatikus krūpčioti.",
     "Kilikijos miestas, žinomas dėl 'blogos' graikų kalbos", "praktika, būdas"),
    ("Susijęs su konfliktu grupės viduje; abipusiai naikinantis.",
     "Vidinės rietenos, draskančios grupę iš vidaus — kova, kurioje visi pralaimi, nes tai šeima prieš šeimą.",
     "Partijos tarpusavio rietenos padarė daugiau žalos nei bet koks išorinis priešininkas.",
     "tarp, tarpe", "žudyti"),
    ("Abejingas, nerūpestingas požiūris.",
     "Gūžtelėjimas pečiais, tapęs visa asmenybe — rūpintis taip mažai dalykais, kurie kadaise rūpėjo, kad niekas nebeatrodo to verta.",
     "Jo abejingas požiūris į apdovanojimų ceremoniją nustebino visus, kurie žinojo, kaip sunkiai jis dirbo.",
     "mažai", "rūpintis"),
    ("Sumišusi, sudėtinga situacija ar ginčas.",
     "Susipainiojusi, netvarkinga situacija, kurią sunku suprasti — dalis nesusipratimo, dalis dramos, visoks sumaištis.",
     "Visa sėdimų vietų painiava prasidėjo nuo vienos neteisingai padėtos vardo kortelės.",
     "viduje", "painioti, painioti"),
    ("Grėsmingas, grasinantis.",
     "Neša aiškią grėsmės atmosferą — grasinantis žvilgsnis ar laiškas padaro labai aišku, kad gali sekti kas nors bloga.",
     "Grasinantis laiško tonas padarė nuomininkę nervingą, dar nespėjus atplėšti voko.",
     "grasinti", "tarnaujantis"),
    ("Stipri vieša kritika ar žodinis įžeidinėjimas.",
     "Garsus, viešas pasmerkimas — tokia plėšianti kritika, kuri vyksta visiems matant.",
     "Pranešėja susidūrė su metų viešu paniekinimu, kol istorija ją išteisino.",
     "prieš", "kalbėti"),
    ("Staigus smarkus emocijų ar veiksmo protrūkis.",
     "Staigus, intensyvus protrūkis, užplūstantis tave iš karto — juoko, pykčio ar kosulio priepuolis, smogiantis kaip banga.",
     "Ją užplūdo juoko priepuolis, kurio ji negalėjo paaiškinti niekam kitam kambaryje.",
     "anapus", "aštrus, ūminis"),
    ("Pridėtas iš išorinio šaltinio, neįgimtas.",
     "Prikaltas iš išorės, o ne įmontuotas nuo pradžių — priedas, ne branduolys.",
     "Komentaras atrodo pridurtas iš šalies, tarsi būtų priklijuotas prie jau baigto teksto.",
     "į, papildomai", "pritarti, priimti"),
    ("Žinių trūkumas, nežinojimas.",
     "Paprastas nežinojimas — žinių spraga, be jokio teismo.",
     "Jis pripažino savo nežinojimą apie prancūzišką vyną ir leido someljė rinktis.",
     "ne", "žinoti"),
    ("Pernelyg didelis susidomėjimas lytiniais dalykais.",
     "Peruoli, žvilgčiojantis smalsumas viskam pikantiškam — susidomėjimas, perėjęs sveiką ribą į įkyrų.",
     "Tabloido geidulingumas dėl poros privataus gyvenimo ribojosi su apsėdimu.",
     "niežėti, ilgėtis", "būsena"),
    ("Suodinas, tamsus, drumstas.",
     "Tamsus ir dūminis išvaizda, tarsi viskas būtų padengta plonu suodžių sluoksniu.",
     "Suodina migla kabėjo virš gamyklos miestelio sutemose.",
     "suodžiai", "pilnas"),
    ("Neigti ar prieštarauti.",
     "Plokščiai kalbėti prieš tai, ką kas nors kitas pasakė — sakyti \"that's not so.\"",
     "Niekas nedrįso paneigti seno kapitono pasakojimo apie audrą.",
     "prieš", "kalbėti"),
    ("Tingumas, tinginystė (iš lotynų).",
     "Senas lotyniškas žodis grynam tingumui — vilkinimas, kai visai nesinori nieko daryti.",
     "Vienuoliai pamokslavo prieš tingumą kaip vieną ramų sielos pavojų.",
     "ne", "užsiėmęs, darbštus"),
    ("Skydas, rodantis herbą.",
     "Skydo formos emblemą, rodanti šeimos herbą — jos heraldinė \"vardinė lentelė.\"",
     "Šeimos herbas vis dar kabo virš senojo dvaro priekinių durų.",
     "skydas", "mažybinis / daiktas"),
    ("Pasenęs, atgyvenęs ar pensijoje dėl amžiaus.",
     "Per savo naudingą žydėjimą ir paleistas į ganyklą — pernelyg senamadiškas ar nudėvėtas, kad tęstų darbą.",
     "Pasenęs spausdintuvas pagaliau buvo pakeistas po penkiolikos metų strigimų.",
     "anapus", "metai"),
    ("Pakaitalai, ypač medicinoje.",
     "Pakaitiniai vaistai, naudojami, kai tikrasis gydymas neprieinamas — iš esmės medicininiai dubleriai.",
     "Kariniai gydytojai dažnai rėmėsi pakaitalais, kai tikrieji vaistai baigdavosi.",
     "vietoje", "eiti, užleisti"),
    ("Girtis, garsiai puikuotis.",
     "Didelis, triukšmingas gyrimasis — garsi kalba apie savo didybę, kuri daugiausia karštas oras.",
     "Jo pagyros apie tai, kad \"vienas pats\" išgelbėjo projektą, neapgavo nė vieno, kuris ten iš tikrųjų buvo.",
     "besigiriantis riteris Orlando Furioso", "veiksmas, rodymas"),
    ("Naudoti klastą ar apgaulę tikslui pasiekti.",
     "Išsisukti prie tikslo klastingais triukais, o ne sąžiningu žaidimu.",
     "Jis gudravimu prasibrovė į sandorį sutartimi, pilna smulkaus šrifto.",
     "kabučioti, apgauti", "klasta; vėliau aštrus posūkis"),
    ("Grynoji ar abstrakti mokymosi ar žinojimo mokslas, dažnai matematika.",
     "Mokymasis tyriausia, abstrakčiausia forma — pati gilioji žinių struktūra, ypač matematinė.",
     "Filosofas svajojo apie visuotinę mathesis, galinčią suvienyti visas žinių sritis.",
     "mokytis", "mokymosi aktas"),
    ("Pernelyg rūpestingas dėl formalių taisyklių ar smulkių detalių.",
     "Per griežtas dėl smulkmenų — taiso mažas technines niuanas, kurios iš tikrųjų nieko nekeičia.",
     "Atrodė šiek tiek pedantiška ginčytis dėl \"who\" prieš \"whom\" žinutėje.",
     "vaikų vedlys, mokytojas", "turintis manierą"),
    ("Mirganti, žėrinti šviesa.",
     "Greitas, žėrintis šviesos blyksnis — pagalvok apie saulės šviesą ant vandens ar deimantą, gaudantį šviesą.",
     "Sietyno žėrėjimas išbarstė šviesą po visus balių salės kampus.",
     "žėrėti, blykčioti", "veiksmas"),
    ("Pradedantysis, novicijus.",
     "Kažkas visai naujas įgūdžiui ar sričiai — dar mokosi virvių, dar ne ekspertas.",
     "Net pradedantysis šachmatininkas gali pastebėti tą klaidą.",
     "naujas kareivis, novicijus", "žalias jaunas kareivis"),
    ("Ypatingai blogas, bjaurus.",
     "Blogas būdu, kuris nusipelno tikro pasibjaurėjimo — ne tik \"vidutiniškas,\" bet tikrai bjaurus.",
     "Recenzentas pavadino tęsinį pasibjaurėtinu, ir kasa sutiko.",
     "keikti", "vertas, galintis būti"),
    ("Kraujo raudonumo.",
     "Gilus, ryškus raudonas — šviežio kraujo spalva, garsiai vartota Šekspyro Makbete.",
     "Saulėlydis pavertė visą dangų kruvinai raudonu švytėjimu.",
     "į", "kūnas (kūno raudonas)"),
    ("Mažas tarpas ar erdvė tarp daiktų.",
     "Ta maža tarpinė vieta, kurią lengva nepastebėti — plyšys tarp grindų lentų, spraga tvarkaraštyje.",
     "Piktžolės stūmėsi pro kiekvieną plyšį sename plytų take.",
     "tarp", "stovėti"),
    ("Kritinės ar smerkiamos pastabos.",
     "Aštrios, nepritariančios pastabos — tokia kritika, kurioje yra šiek tiek barmo tono.",
     "Profesoriaus priekaištai dėl esė pripildė paraštes raudonu rašalu.",
     "protas", "gręžtis link"),
    ("Neįmanoma paneigti, nenuginčijamas.",
     "Taip tvirtai įrodyta, kad nėra apie ką ginčytis — byla tiesiog uždaryta.",
     "DNR įrodymai buvo nepaneigiami, ir teismas baigėsi per valandą.",
     "ne", "priešintis, priešintis"),
    ("Sudėtingumas, painumas; taip pat įsisukimas vidun.",
     "Susipainiojęs, į save įsisukęs sudėtingumas — daiktai, suvynioti taip glaudžiai, kad sunku juos atskirti.",
     "Siužeto susivėlimas paliko pusę publikos bandančią jį išpainioti po titrų.",
     "vidun, į vidų", "ritinti, sukti"),
    ("Jėga ar pastanga, kaip \"by dint of.\"",
     "Gryna jėga ar pastanga — šiandien daugiausia išlikusi frazėje \"by dint of.\"",
     "Jis išlaikė egzaminą grynos, užsispyrusios praktikos dėka.",
     "smūgis, kirtis", "jėga"),
    ("Sujungtas įlaidine jungtimi; tvirtai suleistas.",
     "Sukabintas senu staliaus būdu — vienas gabalas snūduriuoja į skylę, išpjautą būtent jam.",
     "Seno tvarto sijos buvo sujungtos įlaidais be nė vienos vinies.",
     "lizdas, skylė", "kandimas, sukibimas"),
    ("Labai tinkamas, taiklus.",
     "Tiksliai tinkamas akimirkai — pastaba, citata ar pavyzdys, kuris nusileidžia tobulai į tašką.",
     "Jos taikli pastaba sutraukė visą diskusiją į vieną sakinį.",
     "į", "dėti"),
    ("Švelniai švytintis ar mirgantis (šviesa); taip pat lengvas sąmojis.",
     "Švyti švelniai, o ne liepsnoja — minkšta, mirganti šviesa ar sąmojis, kuris žaismingas, o ne aštrus.",
     "Žvakių šviesa metė mirguliuojantį švytėjimą per seną valgomąjį.",
     "laižyti", "veikiantis (šviesa, kuri 'laižo')"),
    ("Religinis atsiskyrėlis, gyvenantis vienumoje.",
     "Kažkas, kas visiškai pasitraukia iš pasaulio gyventi vienas maldoje ir apmąstyme.",
     "Atsiskyrėlis gyveno mažoje celėje, prijungtoje prie bažnyčios, daugiau nei trisdešimt metų.",
     "atgal, šalin", "atsitraukti"),
    ("Numalšinti troškulį; užgesinti.",
     "Visiškai patenkinti alkį — dažniausiai troškulį, bet perkeltine bet kokį gilų norą ar poreikį.",
     "Viena šalto vandens stiklinė numalšino jo troškulį po ilgo žygio.",
     "palaidas, palaidas", "atlaisvinti, nuraminti"),
    ("Adatos formos.",
     "Ilgas, plonas ir smailus kaip adata — pušies adatos ar aštraus mažo kristalo forma.",
     "Pušis lengva atpažinti pagal adatiškus lapus.",
     "adata", "mažas"),
    ("Išsekęs gyvybingumo, silpnas, pernelyg ištobulintas.",
     "Sudėvėtas ir minkštas — praradęs pirmykštę jėgą ar žvalumą per pernelyg daug komforto ar rafinuotumo.",
     "Kritikai pavadino kadaise drąsų žurnalą nusigyvenusiu, jo drąsių ankstyvųjų metų šešėliu.",
     "lauk", "vaisingas, kuris nešė"),
    ("Priedas ar mažesnis pridėtas daiktas ar teisė.",
     "Mažas priedas, ateinantis su kuo nors didesniu — priedai ir papildymai, priklausantys pagrindiniam daiktui.",
     "Nuomos sutartis apėmė garažą ir visus jo priklausinius.",
     "į", "priklausyti"),
    ("Nutylėti ar sumažinti kaltę.",
     "Išlyginti klaidą švelniais žodžiais, kad ji skambėtų mažesnė, nei yra.",
     "Jis bandė nutylėti praleistą terminą miglota kalba apie \"nenumatytus iššūkius\".",
     "glosa, paaiškinimas", "komentuoti — tada išlyginti"),
    ("Ankstyvoje stadijoje, tik prasidedantis.",
     "Tik pradeda rodytis — pati pirmoji, vos matoma stadija ko nors didesnio, kas ateis.",
     "Gydytojai pagavo pradinius ligos ženklus, kol ji nespėjo išplisti.",
     "ant, į", "imti (imtis, pradėti)"),
    ("Kūrybinis įkvėpimas, ypač dieviškasis.",
     "Staigus įkvėpimo pliūpsnis, jaučiantis didesnis už tave — tarsi idėja būtų įpūsta į tave iš kitur.",
     "Poetas aprašė, kaip visas kūrinys atėjo vienu įkvėpimo pliūpsniu trečią nakties.",
     "į, ant", "pūsti (užpūtimas)"),
]
