# Latvian rows
ROWS = [
    ("Saldināt vai attīrīt; novērst kaut kā skarbumu.",
     "Izņemt dzēlīgumu vai rūgtumu — burtiski saldinot vai pārnestā nozīmē mīkstinot skarbu ideju, lai to vieglāk pieņemtu.",
     "Redaktors mīkstināja skarbo recenziju, pirms tā aizgāja uz druku.",
     "ārā, rūpīgi", "salds"),
    ("Pārmērīgi vai izlikti reliģiozs vai dievbijīgs.",
     "Apraksta kādu, kura reliģiskā uzticība šķiet izlikšanās publikai — vairāk izrāde nekā īsta ticība.",
     "Viņa piētiskās nopūtas sludināšanas laikā kaitināja pārējo soliņu.",
     "dievbijība, pienākuma apziņa", "kam piemīt raksturs"),
    ("Divdomība, kas rodas no gramatiskās uzbūves — teikums, ko var lasīt divējādi.",
     "Teikums, kas gramatiski ir kārtībā, bet ko var saprast divos pilnīgi atšķirīgos veidos, piemēram, \"I saw the man with the telescope.\"",
     "\"Visiting relatives can be tiring\" ir klasiska amfibolija — vai nogurdina radinieki, vai tas, ka viņus apmeklē?",
     "abi, no abām pusēm", "mest"),
    ("Ass, trāpīgs, griež taisni pie lietas būtības.",
     "Griež cauri tukšajiem vārdiem — asa piezīme vai prāts ātri nonāk pie lietas sirds, bez lieka.",
     "Viņas asā kritika neatstāja filmas sižeta caurumiem, kur paslēpties.",
     "griezt", "darītājs, kam piemīt īpašība"),
    ("Tikko sācies; agrīnā vai pirmatnējā stadijā.",
     "Vēl atklāšanas brīžos — plāns, sajūta vai process, kas tikko sācis iegūt formu.",
     "Līguma sākotnējie posmi bija daudzsološi, bet daudz kas vēl palika neatrisināts.",
     "sākt, uzsākt", "kas tiecas uz"),
    ("Formāla runa vai raksts, kas kādu augsti slavē.",
     "Pilnīgs, formāls slavinājums — iedomājies spožu piemiņas runu vai uzrunu, kas dzied kāda sasniegumus no jumtiem.",
     "Aizejošo profesori pavadīja slavinājums no viņas tuvākajiem studentiem.",
     "viss", "sapulce, pulcēšanās"),
    ("Attiecas uz īstu esamību vai faktisku būtību, pretēji abstraktai teorijai.",
     "Par lietām tā, kā tās patiešām pastāv, ne tikai kā idejas vai teorijas par tām.",
     "Filozofi strīdas, vai skaitļiem ir kāds ontiskais statuss, vai tie pastāv tikai mūsu prātos.",
     "būtība, tas, kas ir", "kas attiecas uz"),
    ("Nest augļus vai kļūt produktīvam.",
     "Beidzot atmaksāties — pūles, ideja vai ieguldījums, kas nes augļus, ir izaudzis no sēklas par kaut ko noderīgu.",
     "Gadiem ilgie klusie pētījumi beidzot nesa augļus — strādājošu vakcīnu.",
     "auglis", "darīt, izraisīt"),
    ("Kas paredz vai attēlo kaut ko kā jau notikušu, pirms tas patiešām ir noticis.",
     "Pārsteigt notikumus literārā veidā — aprakstīt nākotnes notikumu, it kā tas jau būtu beidzies, lai punkts iesistu stiprāk.",
     "Ģenerāļa priekšlaicīgais tosts par \"uzvaru\" tika teikts veselu nedēļu pirms kaujas.",
     "pirms", "ņemt, sagrābt"),
    ("Darbināts ar gaisa spiedienu; arī saistīts ar garu vai elpu.",
     "Parasti nozīmē \"darbināts ar saspiestu gaisu\" — lai gan var arī nozīmēt saistītu ar garu vai elpu.",
     "Pneimatiskās bremzes šņāca, kad autobuss piebrauca pie apmales.",
     "vējš, elpa, gars", "kas attiecas uz"),
    ("Dievu vai dievišķo apraksta ar pozitīviem apgalvojumiem — pretstats apofātiskajam.",
     "Veids, kā runāt par Dievu, sakot, kas Dievs ir — \"God is love\" —, nevis tikai, kas Dievs nav.",
     "Katafātiskā teoloģija pārliecināti runā par Dievu kā mīlošu, taisnīgu un žēlsirdīgu.",
     "lejā, saskaņā ar", "runāt, teikt"),
    ("Balstīts uz uzticību vai ticību; arī kā fiksēts atskaites punkts.",
     "Kaut kas, ko pieņem uzticībā un tad izmanto kā enkuru — atskaites zīme ir fiksētais punkts, pret ko mēra visu pārējo.",
     "Mērnieki novietoja atskaites marķieri pamatiezī, pirms kartēja vietu.",
     "uzticēties", "uzticība, pārliecība"),
    ("Dieva labestības aizstāvība, ņemot vērā ļaunuma esamību.",
     "Senais mēģinājums atbildēt: \"If God is good, why does evil exist?\"",
     "Viņas disertācija pētīja teodiceju caur Ījaba grāmatas prizmu.",
     "dievs", "taisnīgums"),
    ("Savstarpēja mājvieta — teoloģisks termins tam, kā Trīsvienības personas pastāv viena otrā.",
     "Teoloģijas vārds tik pilnīgai trīs-vienā kopībai, ka katra daļa pilnībā satur un ir saturēta pārējās.",
     "Perihorēzes doktrīna mēģina izskaidrot, kā Tēvs, Dēls un Gars ir atšķirīgi, tomēr neatdalāmi.",
     "apkārt", "iet, staigāt"),
    ("Radīt sekas, kas nāk par labu vai atspoguļojas uz kādu.",
     "Kad uzslava (vai vaina) atlec atpakaļ pie atbildīgā — labi darbi, kas nāk par godu tavai reputācijai, atgriežas ar atlīdzību.",
     "Komandas panākumi nāks par godu tās klusajam, čaklajam trenerim.",
     "atpakaļ, atkal", "vilnis"),
    ("Tāds, no kā nevar izvairīties vai izbēgt.",
     "Notiks, lai ko tu darītu — no neizbēgama iznākuma nav, kur izslīdēt.",
     "Vecums nāk pie visiem; tas ir vienkārši neizbēgams.",
     "ne", "izcīnīties ārā"),
    ("Kas lieto apkārtēju, vārdiem bagātu izteiksmi, nevis tiešu formu.",
     "Iet ar vārdiem garo ceļu — saka \"make a decision\" tā vietā, lai teiktu \"decide.\"",
     "Viņa izplūdušie e-pasti varēja vienā rindā pateikt to, kam viņš tērēja trīs rindkopas.",
     "apkārt", "paziņot, stāstīt"),
    ("Garīgs trulums vai letarģija.",
     "Tā miglainā, gausā prāta stāvoklī, kurā domāšana jūtas kā brīdīšana cauri sīrupam.",
     "Truluma vilnis pārņēma klasi tūlīt pēc pusdienām.",
     "truls, strups", "stāvoklis vai īpašība"),
    ("Nelabvēlīgs; sliktas zīmes.",
     "Slikta zīme — apstākļi vai laiks, kas šķiet strādā pret tevi, pirms esi pat sācis.",
     "Pelēkas debesis un izlādējies automašīnas akumulators veidoja nelabvēlīgu sākumu ceļojumam.",
     "ne", "labvēlīgs, žēlīgs"),
    ("Gaļa, kas sautēta mērcē — pareizi rakstīts \"fricasseed.\"",
     "Mājīgs, vecs ēdiena vārds gaļai, kas sagriezta un lēni sautēta savā mērcē, līdz kļūst maiga.",
     "Vecmāmiņas frikasē vista bija katras svētdienas vakariņu zvaigzne.",
     "cept", "lauzt (gabalos)"),
    ("Mākslīgs vai sliktāks aizstājējs.",
     "Viltojums īstā vietā — tehniski dara darbu, bet visiem redzams, ka tas nav īstais.",
     "Kara laika pircēji iztika ar aizvietotājkafiju no grauzdētas cigoriņu saknes.",
     "ārā, aizvietošanas priedēklis", "likt, novietot"),
    ("Izturēties pret abstraktu ideju tā, it kā tā būtu konkrēta lieta.",
     "Padarīt ideju jūtamies īstu un cietu — pārvērst kaut ko neskaidru, piemēram, \"the economy,\" par lietu, uz ko var norādīt.",
     "Saukt nācijas \"garu\" par patstāvīgu būtni nozīmē pārvērst lietā kaut ko, kas patiesībā ir miljoniem atsevišķu izvēļu.",
     "lieta", "darīt"),
    ("Prasmīgi izbēga vai izvairījās.",
     "Tīri izslīdēja — izvairījās no kaut kā, bieži gudri vai šauri, vai tā būtu sagūstīšana, jautājums vai atbilde.",
     "Atbilde izvairījās no viņas stundām, līdz pēkšņi noklikšķināja dušā.",
     "ārā, projām", "spēlēt"),
    ("Kas izsaka šaubas, apjukumu vai neatrisinātu pretrunu.",
     "Iestrēdzis īstā domu strupceļā — ne jau slinkuma dēļ, bet tāpēc, ka pats jautājums pretojas kārtīgai atbildei.",
     "Sokrats bieži beidza dialogus aporētiskā notī, ar vairāk jautājumiem nekā atbildēm.",
     "bez", "ceļš, eja"),
    ("Stila figūra, kas nosauc kaut ko ar saistītu vārdu, piemēram, \"the crown\" par monarhu.",
     "Izmantot saistītu vārdu īstā vietā — teikt \"the White House announced,\" kad domā administrāciju.",
     "\"Wall Street had a rough day\" ir metonīmija — patiesībā tas nozīmē, ka smagu dienu piedzīvoja birža.",
     "maiņa, pēc", "vārds"),
    ("Izraut ar saknēm; atraut no dabiskās vides.",
     "Izraut kaut ko (vai kādu) ar saknēm, prom no vietas vai kultūras, kurai viņš pieder.",
     "Karš izrāva ar saknēm veselu paaudzi, izkaisot ģimenes pāri robežām.",
     "prom, nost", "sakne"),
    ("Patīkami skanošs.",
     "Vienkārši jauki dzirdēt — skanīgs vārds, nosaukums vai teikums slīd ausij gludi, gandrīz muzikāli.",
     "\"Murmuring brook\" ir skanīgs mazs izteiciens — mīksts un viegli izrunājams.",
     "labs, labi", "skaņa, balss"),
    ("Vispārīgi pieņemts vai uzskatīts par tādu.",
     "Plaši ticēts par patiesu, pat ja tas nav pierādīts — \"pieņemamā\" versija par kaut ko.",
     "Vēstules iedomātais autors vēlāk izrādījās pilnīgs svešinieks.",
     "domāt, uzskatīt", "kam piemīt daba"),
    ("Jaunradīts vārds vai frāze.",
     "Pavisam jauns vārds — tikko izgudrots, vēl (vai tikko) nav vārdnīcā.",
     "\"Doomscrolling\" sākās kā jaunvārds un ātri kļuva par ikdienas slengu.",
     "jauns", "vārds, runa"),
    ("Dusmīgs vai ļauns raksturā.",
     "Sliktā, aizkaitināmā noskaņā — ātri uzliesmo, kā kādreiz ticēja, ka liesa kontrolē temperamentu.",
     "Viņš aizsūtīja žultainu atbildi e-pastam dažu sekunžu laikā pēc izlasīšanas.",
     "liesa (dusmu mājvieta)", "ietekmēts no"),
    ("Tāds, kas morālizē uzpūtīgi vai izlikti.",
     "Mīl pasniegt mazas dzīves mācības pašsvarīgā veidā, it kā katrs teikums būtu laimes cepums.",
     "Viņa pamācošais tosts par \"draudzības patieso nozīmi\" lika visiem skatīties pulksteņos.",
     "viedoklis, maksima", "pilns ar"),
    ("Pārmērīgi runīgs, it īpaši par sīkumiem.",
     "Vienkārši nepārtrauc čalot — mētājas par sīkumiem ilgi pēc tam, kad visiem pārējiem beigušies vārdi.",
     "Pļāpīgais taksists pastāstīja visu savu dzīvesstāstu, pirms bijām atstājuši lidostu.",
     "čalot, pļāpāt", "tiecas uz"),
    ("Muļķība, neprāts.",
     "Parasta muļķība — piezīme vai plāns tik stulbs, ka tikko pelna nopietnu atbildi.",
     "Plāna tīrā muļķība kļuva acīmredzama brīdī, kad viņi to izmēģināja.",
     "muļķīgs, stulbs", "būšanas stāvoklis"),
    ("Runas noslēdzošā daļa, bieži kopsavilkums.",
     "Runas lielais fināls — noslēguma daļa, kur runātājs savilks visu kopā un iesit punktu mājās.",
     "Līdz noslēguma runai puse publikas jau stāvēja kājās.",
     "cauri, līdz galam", "runāt, aizstāvēt"),
    ("Nevajadzīga tās pašas idejas atkārtošana citiem vārdiem.",
     "Teikt to pašu divreiz, neko jaunu nepievienojot, piemēram, \"free gift\" vai \"end result.\"",
     "\"It is what it is\" ir iecienīta tautoloģija tiem, kas izvairās no īsta skaidrojuma.",
     "tas pats", "vārds, runa"),
    ("Ļoti maz vārdu lietošana; lakoniska runa.",
     "Daudz pateikt ar ļoti maz — īsās, strupās atbildes māksla, nosaukta pēc Lakonijas leģendāri īsiem spartiešiem.",
     "\"Molon labe\" — \"nāciet un ņemiet\" — ir vēstures slavenākais lakonisma paraugs.",
     "Lakonas spartietis", "prakse, veids"),
    ("Plieknas, pārmērīgi vienkāršotas idejas; sākotnēji — plieknas ēdiens vai biezputra.",
     "Plāns, atšķaidīts domāšana — saturs tik vienkāršots un drošs, ka prātam nav nekādas barības vērtības.",
     "Politiķa runa bija galvenokārt tukša pļāpāšana: neskaidri solījumi, pie kuriem neko nevarēja piesiet.",
     "barot", "līdzeklis vai instruments"),
    ("Kas izraisa miegu vai miegainību.",
     "Tik garlaicīgs — vai burtiski nomierinošs —, ka tas liek aizmigt. Iedomājies siltu pienu vai trīs stundu budžeta sēdi.",
     "Lekcijas miegainā dūkoņa lika pusei telpas cīnīties, lai turētu acis vaļā.",
     "dziļš miegs", "kas rada, izraisa"),
    ("Pārmērīgi glaimojošs vai eļļains manierē.",
     "Tik gludi šarmants, ka šķiet slidenš — glaimi uzklāti tik biezi, ka praktiski jūt taukus.",
     "Glaimojošais pārdevējs turpināja slavēt manu \"izcilo gaumi\" pirms katras papildu pārdošanas.",
     "svaidīt, eļļot", "pilns ar"),
    ("Ātri atrod kļūdas, pārmērīgi kritisks pret sīkumiem.",
     "Nīgrs līdz kļūdai — tāds, kas atrod problēmu visā, pat kad tas īsti nav svarīgi.",
     "Viņa ķildīgās piezīmes pie atskaites koncentrējās tikai uz komatu izvietojumu.",
     "sagrābt, ņemt", "slazds, sofisms"),
    ("Gausš, garīgi vai fiziski neaktīvs.",
     "Lēns un pusmiegā, kā lācis ziemas miegā — tikko kustas, tikko domā.",
     "Birojs kļuva gurds augusta smagajā karstumā.",
     "būt nejūtīgam, būt gausam", "stāvoklī"),
    ("Pārvaldnieks vai amatpersona, kas vadīja viduslaiku saimniecību.",
     "Viduslaiku personāla vadītāja versija — uzticamais ierēdnis, kas vadīja kunga māju un muižu no dienas uz dienu.",
     "Pils seneskals pārvaldīja visu no ražas grāmatvedības līdz viesu sarakstam.",
     "vecs, vecākais", "kalps"),
    ("Runāt vai rakstīt gari par tēmu.",
     "Patiešām iešūpoties tēmā — runāt vai rakstīt un rakstīt, apskatot to no visām pusēm.",
     "Pajautā viņam par senlaicīgajām automašīnām, un viņš izplūdīs veselu stundu.",
     "ārā", "telpa"),
    ("Bez vērtības, niecīgs; arī spēkā neesošs vai neefektīvs.",
     "Vērts praktiski neko — spēkā neesoša klauzula līgumā ir tāda, kas īsti neko nedara.",
     "Tiesa atzina veco noteikumu par spēkā neesošu, jo tas nekad nebija īsti piemērots.",
     "sīkumi, muļķības", "kas pieder pie"),
    ("Gudrība, vērīgs spriedums.",
     "Ass, praktiska gudrība — tāds labs spriedums, kas nāk no pieredzes, ne tikai no grāmatām.",
     "Vecā kapteiņa gudrība ne reizi vien izglāba komandu no nepatikšanām.",
     "ass ožas, vērīgs", "īpašība"),
    ("Vienkāršā pūlis vai masas, lietots nicinoši.",
     "Uzpūtīgs, nicinošs vārds \"pūlim\" vai vienkāršajiem ļaudīm, lietots ar nicinājumu.",
     "Grāfs ņirgājās par zemo pūli, kas pulcējās pie pils vārtiem.",
     "suns", "kopums, bars"),
    ("Neķītrs, pazemojošs izturēšanās vai valoda.",
     "Cietsirdīga, nicinoša izturēšanās, kas paredzēta pazemot — tāds apvainojums, kas ir iecerēts sāpēt.",
     "Viņš izturēja gadiem ilgu apkaunojumu no kritiķiem, pirms viņa darbs beidzot tika atzīts.",
     "ar, rūpīgi", "uzpūsties (ar lepnumu)"),
    ("Ar aizdomām vai noraidījumu; skatīties sānis.",
     "Tas sānis skatiens, ko dod kaut kam, kam īsti neuzticies — skatiens, pilns šaubu.",
     "Skolotāja šķībi paskatījās uz aizdomīgi kārtīgo mājasdarbu.",
     "uz, pie", "slīpums, novirze"),
    ("Stulbs cilvēks; muļķis.",
     "Vecmodīgs, gandrīz mīļš apvainojums kādam, kas ir blāvs vai blīvs — kluča galva.",
     "\"Tu muļķi,\" viņa smējās, \"tev karte visu laiku ir bijusi otrādi.\"",
     "zemes pika", "galva"),
    ("Iedarbināt vai likt darboties; motivēt.",
     "Būt dzirkstelei, kas kaut ko iedarbina — vai tā būtu mašīna, kas ieslēdzas, vai cilvēks, kas beidzot rīkojas pēc idejas.",
     "Bailes zaudēt līgumu pamudināja visu komandu uz nedēļas nogales virsstundām.",
     "darīšana, dzīšana", "dzīt, darīt"),
    ("Uzticētu līdzekļu piesavināšanās.",
     "Klusi zagšana naudas, kas tev uzticēta glabāt — piesavināšanās vecmodīgā mētelī.",
     "Kasiera piesavināšanās palika nepamanīta gandrīz desmit gadus.",
     "privātīpašums", "lopi, bagātība"),
    ("Grupa, kas uzskatīta par cienījamas sabiedrības malā.",
     "Tas glamorīgais, bet ēnainais sociālais apakšpasaule — cilvēki, kas dzīvo tieši ārpus \"cienījamās\" sabiedrības noteikumiem.",
     "Romāns seko dziedātājai, kas navigē 1920. gadu kabarē puspasaulē.",
     "puse", "pasaule, sabiedrība"),
    ("Joprojām pastāvošs; nav izmiris vai iznīcināts.",
     "Joprojām ir šeit šodien — lieto vecām lietām (manuskriptiem, sugām, ēkām), kas ir spējušas izdzīvot.",
     "Ir zināmas tikai trīs saglabājušās pirmā iespieduma kopijas.",
     "ārā", "stāvēt"),
    ("Viltība; uzticības nodevība.",
     "Dziļa, tīša nodevība — lauzt uzticību, ko kāds bija tiesīgs sagaidīt, ka tu saglabāsi.",
     "Ģenerālis nekad nepiedeva sava vecā drauga nodevību pie sarunu galda.",
     "cauri, pret", "ticība, uzticība"),
    ("Reģionāls dialekts, īpaši nestandarta.",
     "Īpatnējais, vietējais veids, kā cilvēki runā kādā reģionā — pilns vārdu un ritmu, ko svešinieks varētu nesaprast.",
     "Viņas vecmāmiņa joprojām runāja salas izloksnē ģimenes vakariņās.",
     "rupja runa, dialekts", "ķepa — neveikla runa"),
    ("Īpašas tiesības, kas pieder personai vai grupai.",
     "Privilēģija, kas ir tava un tikai tava — tiesības, kas nāk ar tavu lomu, amatu vai statusu.",
     "Ģimenes brīvdienu vietas izvēle ir vectēva prerogatīva, un to visi zina.",
     "pirms", "jautāt, balsot"),
    ("Drosme, drosmība; arī izturība.",
     "Raupja, drosmīga izturība — nervi iet uz priekšu un cietība turpināt, kad esi sācis.",
     "Bija vajadzīga īsta drosme, lai šķērsotu pāreju sniegputenī bez kartes.",
     "drosmīgs, izturīgs", "stāvoklis, nosacījums"),
    ("Uzziedēt; arī attīstīties vai pakāpeniski parādīties.",
     "Uzziedēt pilnā izteiksmē — kā zieds, kas atveras, vai ideja, kas beidzot nāk pie sevis.",
     "Viņas klusais gleznošanas talants uzplauka, kad viņai bija sava studija.",
     "ārā", "sākt ziedēt"),
    ("Atsvars uz auklas, lai noteiktu vertikāli; pārnestā nozīmē — sprieduma mēraukla.",
     "Svars uz auklas, kas karājas pilnīgi taisni lejup, lai pārbaudītu, vai kaut kas ir īsti vertikāls — un, plašāk, jebkurš fiksēts standarts, pret ko mēra visu pārējo.",
     "Viņš izmantoja sava vectēva godīgumu kā sava veida svērteni katram lēmumam.",
     "svins", "aukla, mērs"),
    ("Labprāt, ar prieku (arhaisms).",
     "Vecmodīgs veids, kā teikt \"labprāt\" vai \"ar prieku.\"",
     "\"Es labprāt te kādu brīdi atpūstos,\" ceļotājs nopūtās.",
     "priecīgs, priecīgs", "labprāt, ar prieku"),
    ("Skarba publiska kritika vai negods.",
     "Publisks kauns, kas uzkrāts kādam lielā, redzamā veidā — negods, kas nāk no plaša noraidījuma.",
     "Skandāls nesa publisku negodu visai firmai.",
     "pret", "negods, pārmetums"),
    ("Asi sarkastisks, kodīgs asprātībā vai kritikā.",
     "Asprātība ar īstiem zobiem — kodīga piezīme kniebj tieši tāpēc, ka tā ir tik gudri mērķēta.",
     "Viņas kodīgās filmu recenzijas baidīja režisorus un mīlēja lasītāji.",
     "kost", "kožošs, darītājs"),
    ("Formāls paziņojums, bieži politisks vai militārs.",
     "Liels, oficiāls paziņojums — parasti tāds, kas pasludina jaunu valdību, sacelšanos vai svarīgu dekrētu.",
     "Ģenerāļa pasludinājums rītausmā paziņoja jauno valdību.",
     "uz priekšu", "paziņot"),
    ("Cilvēks ar virspusējām zināšanām, kas izliekas par ekspertu.",
     "Kāds, kas ir pārlidojis tēmas virsmu un tad runā, it kā būtu rakstījis par to mācību grāmatu.",
     "Vakariņu pusgudrais pārliecināti laboja īsto astrofiziķi pie galda.",
     "zināt", "mazināmais — mazs zinātājs"),
    ("Garīgo spēju vājināšanās vecumā.",
     "Miglainais, aizmāršīgais ļoti veca vecuma posms, kad prāta asums sāk zūd.",
     "Savā sirmajā vecumā viņš katru apmeklējumu stāstīja tos pašus trīs stāstus, katru reizi it kā jaunus.",
     "muļķoties, būt muļķīgam", "stāvoklis vai rezultāts"),
    ("Puse, kas paslēpta no vēja.",
     "Kaut kā mierīgā, pasargātā puse — kalna, kuģa, sienas —, kur vējš tevi īsti nesasniedz.",
     "Pārgājēji uzcēla telti grēdas aizvēja pusē, lai izbēgtu brāzmām.",
     "patvērums, aizsardzība", "sāns, seja"),
    ("Atsist vai novērst sitienu, jautājumu vai argumentu.",
     "Gludi atsist kaut ko — zobena sitienu, neveiklu jautājumu vai apsūdzību — nezaudējot ritmu.",
     "Viņa atvairīja žurnālista viltīgo jautājumu ar vieglu joku.",
     "novērst", "sagatavoties, aizstāvēties"),
    ("Smirdīgs, kaitīgs.",
     "Smaržo tik slikti, ka šķiet gandrīz toksisks — smaka tik ļauna, ka elpot šķiet bīstami.",
     "Smirdīga smaka cēlās no purva, kad saule norietēja.",
     "kaitīgi tvaiki", "kam piemīt daba"),
    ("Cilvēks, kas nodevies greznībai un bauda.",
     "Kāds, kas dzīvo komfortam un izdabāšanai — smalks ēdiens, mīkstas gultas, viegla dzīve — nosaukts pēc sengrieķu pilsētas Sybaris, slavenas ar pārmērībām.",
     "Īsts sibarīts, viņš atteicās no jebkuras viesnīcas istabas bez vannas.",
     "sengrieķu pilsēta, slavenā ar greznību", "iedzīvotājs"),
    ("Tīši atlikt malā vai ignorēt kādu daļu.",
     "Apzināti atlikt puzles gabalu malā, lai tīri koncentrētos uz pārējo.",
     "Uz brīdi atkāpsimies no izmaksām un vienkārši pajautāsim, vai plāns vispār strādā.",
     "pirms, projām", "griezt"),
    ("Smagi kritizēt; arī novilkt ādu.",
     "Ieplēst kādu ar skarbu kritiku — vārdiski, it kā burtiski novilktu ādu.",
     "Kritiķi noplēsa turpinājumu par to, ka tas nodeva visu, ko fani mīlēja oriģinālā.",
     "nost", "āda, kažoks"),
    ("Minēt kā pierādījumu vai argumentu.",
     "Izvirzīt faktu vai piemēru, lai pamatotu savu punktu — tas, uz ko norādi, kad kāds jautā \"what's your evidence?\"",
     "Advokāte uzrādīja trīs lieciniekus, lai atbalstītu klienta alibi.",
     "uz, pretī", "vest"),
    ("Ceļojumi vai klejojumi, īpaši gari vai plaši.",
     "Gari, klejojoši ceļojumi — tāda plaša klejošana, kas ved tālu no mājām uz labu laiku.",
     "Viņa klejojumi pāri trim kontinentiem piepildīja veselu plauktu ceļojumu dienasgrāmatu.",
     "cauri", "lauks, zeme (peregrinus: svešinieks)"),
    ("Ubagotājs vai tāds, kas dzīvo no žēlastības dāvanām.",
     "Kāds, kas dzīvo, lūdzot žēlastību — vēsturiski tas aprakstīja arī mūkus, kas zvērēja nabadzību un dzīvoja no ziedojumiem.",
     "Ubagotājiem mūkiem nepiederēja nekas, un viņi paļāvās pilnībā uz ciema ļaužu laipnību.",
     "ubagot", "ubagotājs"),
    ("Ārkārtīgi dāsns.",
     "Dāsns grandiozā, gandrīz izrādes mērogā — tāda dāvana, kas liek cilvēkiem mazliet ievilkt elpu.",
     "Devīgais ziedojums finansēja visu jauno bibliotēkas spārnu.",
     "dāvana, pakalpojums", "darīšana, došana"),
    ("Izsīkums no barības trūkuma; arī vitalitātes trūkums.",
     "Vājš, iztukšots stāvoklis no tā, ka nav barots vai uzpildīts — burtiski no bada vai pārnestā nozīmē no tā, ka vairs nav, ar ko darboties.",
     "Līdz aplenkuma beigām karavīri bija tuvu izsīkumam.",
     "tukšs, tukšums", "darbība vai rezultāts"),
    ("Rūgta, apvainojoša kritika.",
     "Kritika, kas sen pārgājusi taisnīguma robežu un kļuvusi par dusmīgu, rūgtu tirādi.",
     "Tiešsaistes komentāri dažu minūšu laikā izjuka tīros lamu vārdos.",
     "vainība", "sagatavot, apgādāt"),
    ("Naidīgs, kaitīgs iedarbībā.",
     "Strādā pret tevi, pat ja klusi — apstākļi vai attieksme, kas nav draudzīgi tavām interesēm.",
     "Jaunā politika bija naidīga mazajiem uzņēmumiem, pat ja tas nebija nolūks.",
     "ne", "draugs"),
    ("Tāds, kas var izraisīt īgnumu vai neapmierinātību, bieži caur netaisnīgiem salīdzinājumiem.",
     "Noteikti liks kādam justies aizvainotam — parasti tāpēc, ka tas nesamērīgi salīdzina cilvēkus vai lietas.",
     "Sarindot brāļus un māsas pēc tā, \"ko mamma mīl visvairāk\", ir aizvainojoša spēle, ko nevienam nevajadzētu spēlēt.",
     "skaudība", "skatīties (ar ļaunu gribu)"),
    ("Zemāka ranga vai statusa persona; padotais.",
     "Kāds zemāk komandķēdē vai sociālajā kāpnēs — jaunākais, kas strādā zem kāda ar lielāku varu.",
     "Kā jauns jaunākais virsnieks viņš ilgi saņēma pavēles, pirms pats tās deva.",
     "zem", "alternatīvs, cits"),
    ("Just vai izteikt stipru naidu pret.",
     "Nīst kaut ko tik ļoti, ka to lādē skaļi — tīrs, balsīgs pretīgums.",
     "Ciema ļaudis nolādēja nodokļu iekasētāju katru reizi, kad viņa rati iebrauca pilsētā.",
     "ārā no", "svēts (lādēt ārā no svētā)"),
    ("Dabisks ārējais apvalks, piemēram, āda vai čaula.",
     "Dabas pašu aizsargājošais ietīums — āda, čaula, miza vai miza, kas vien sedz un sargā dzīvo.",
     "Bruņurupuča čaula ir ievērojami izturīgs apvalks.",
     "uz, pāri", "segt"),
    ("Nevainīgs, naivs, ar bērnišķīgu vienkāršību; pretstats \"disingenuous.\"",
     "Atklāti uzticīgs un mazliet naivs, bez slēptas programmas — viegli sajaukt ar \"ingenious,\" kas nozīmē gudrs.",
     "Viņas naivais jautājums — \"kāpēc gan kāds par to melotu?\" — parādīja, cik maz viltības viņai bija.",
     "iekšā, dzimts", "dzemdēt (brīvi dzimis, atklāts)"),
    ("Pārmērīgas rūpes par sīkām detaļām vai noteikumiem.",
     "Pazust sīkajos noteikumos, palaidot garām lielāko bildi — apsēsties ar sīkajiem burtiem, par kuriem neviens cits nerūpējas.",
     "Viņa pedantisms par Oksfordas komatu izjauca visu sapulci.",
     "bērnu skolotājs", "prakse vai īpašība"),
    ("Rūpīga, uzmanīga pārbaude.",
     "Dziļš, neviens-akmens-neapgriezts skatījums uz kaut ko — iet cauri katrai detaļai ar īstu rūpību.",
     "Tikai pēc rūpīgas grāmatvedības pārbaudes parādījās neatbilstība.",
     "cauri, rūpīgi", "meklēt, pārbaudīt"),
    ("Izteikt iebildumus; parādīt nevēlēšanos.",
     "Pieklājīgi atspiesties vai vilcināties, nevis uzreiz piekrist — maigs \"I'd rather not.\"",
     "Kad lūdza parakstīt, neizlasot, viņa iebilda.",
     "no, projām", "aizkavēt"),
    ("Virspusēji ticams, bet patiesībā nepareizs.",
     "Pirmajā acu uzmetienā izklausās pārliecinoši, bet sabrūk brīdī, kad to īsti pārbaudi.",
     "\"Everyone's doing it\" ir šķietami pārliecinošs arguments, kas nekad īsti neiztur pārbaudi.",
     "izskats, izskats", "pilns ar (šķietami labs)"),
    ("Neīsta, liekulīga runa, bieži morālizējoša.",
     "Sprediķojoša runa, kas izklausās tikumīga, bet nav atbalstīta ar īstu sajūtu — morāla poza autopilotā.",
     "Viņš bija noguris no korporatīvās tukšās runāšanas par \"ģimeni\" no uzņēmuma, kas nekad nedod nevienam brīvdienas.",
     "dziedāt (vēlāk: vienmuļa žargons)", "ubagu vaidoša runa, tad liekulība"),
    ("Bez drosmes, gļēvs.",
     "Bailīgs līdz mugurkaula trūkumam — pārāk nobijies piecelties, pat kad tas acīmredzami ir svarīgi.",
     "Valdes gļēvais klusums ļāva skandālam izplesties ārpus kontroles.",
     "ļoti mazs", "gars, drosme"),
    ("Lapsveidīgs; viltīgs, gudrs.",
     "Viltīgs un gudrs kā lapsa — asprātīgs, mazliet slīdīgs, vienmēr soli priekšā.",
     "Viņš uzsmaidīja lapsisku smaidu brīdī, kad ieraudzīja robu likumā.",
     "lapsa", "no vai kā"),
    ("Viens pēc otra, secībā.",
     "Ņemts strikti pa vienam, kārtībā — bez izlaišanas uz priekšu, bez diviem vienlaikus.",
     "Tiesnesis izskatīja katru no divpadsmit prasībām pēc kārtas.",
     "rinda, secība", "pa vienam"),
    ("Ārkārtīga taupība; skopums.",
     "Būt ciešam ar naudu (vai vārdiem, vai resursiem) tālu pāri saprātīgai taupībai.",
     "Viņa skopums bija leģendārs — viņš tējas maisiņus izmantoja trīs reizes.",
     "taupīt, būt taupīgam", "stāvoklis vai prakse"),
    ("Labojums, īpaši tekstā.",
     "Labojums rakstā — zinātnisks labojums, kas izlabo kļūdu vecā vai svarīgā tekstā.",
     "Jaunajā izdevumā ir desmitiem oriģinālā manuskripta labojumu.",
     "ārā no", "vainība, kļūda"),
    ("Mērens ēšanā un dzeršanā.",
     "Apzināti atturīgs ēdiena un dzēriena ziņā — nekad nepārēdas, vienmēr atstāj mazliet uz šķīvja.",
     "Viņa atturīgie ieradumi uzturēja viņu asu ilgi pēc tam, kad vienaudži bija palēninājušies.",
     "prom no", "apreibinošs dzēriens"),
    ("Gramatiska kļūda vai etiķetes pārkāpums.",
     "Kļūme gramatikā vai manierēs — tāda maza kļūda, kas liek pedantam saraustīties.",
     "\"Between you and I\" ir izplatīta valodas kļūda, kas joprojām liek gramatiķiem raustīties.",
     "Kilikijas pilsēta, pazīstama ar 'slikto' grieķu valodu", "prakse, veids"),
    ("Saistīts ar konfliktu grupas iekšienē; savstarpēji postošs.",
     "Iekšējās ķildas, kas saplēš grupu no iekšpuses — cīņa, kurā visi zaudē, jo tā ir ģimene pret ģimeni.",
     "Partijas savstarpējās ķildas nodarīja vairāk ļaunuma nekā jebkurš ārējs pretinieks.",
     "starp, starpā", "nogalināt"),
    ("Vienaldzīga, nevērīga attieksme.",
     "Plecu paraustīšana, kas kļuvusi par veselu personību — rūpēties tik maz par lietām, kas kādreiz bija svarīgas, ka nekas vairs neliekas tā vērts.",
     "Viņa vienaldzīgā attieksme pret balvu ceremoniju pārsteidza visus, kas zināja, cik smagi viņš bija strādājis.",
     "maz", "rūpēties"),
    ("Sajaukta, sarežģīta situācija vai strīds.",
     "Sajaukta, nekārtīga situācija, ko grūti saprast — daļa pārpratuma, daļa drāmas, visa juceklis.",
     "Viss sēdvietu juceklis sākās ar vienu nepareizi novietotu vārda kartīti.",
     "iekšā", "sapīt, sajaukt"),
    ("Draudīgs, draudošs.",
     "Nes nepārprotamu draudu gaisotni — draudīgs skatiens vai vēstule padara ļoti skaidru, ka kaut kas slikts var sekot.",
     "Vēstules draudīgais tonis padarīja īrnieci nervozu, pirms viņa bija pat atvērusi aploksni.",
     "draudēt", "kas kalpo"),
    ("Stipra publiska kritika vai mutisks apvainojums.",
     "Skaļa, publiska nosodīšana — tāda plosoša kritika, kas notiek visiem redzot.",
     "Trauksmes cēlēja saskārās ar gadiem ilgu publisku nomelnošanu, pirms vēsture viņu attaisnoja.",
     "pret", "runāt"),
    ("Pēkšņs vardarbīgs emociju vai darbības uzliesmojums.",
     "Pēkšņs, intensīvs uzliesmojums, kas pārņem tevi uzreiz — smieklu, dusmu vai klepus lēkme, kas sit kā vilnis.",
     "Viņu pārņēma smieklu lēkme, ko viņa nespēja izskaidrot nevienam citam telpā.",
     "aiz, pāri", "ass, akūts"),
    ("Pievienots no ārēja avota, nav piemītošs.",
     "Pieskrūvēts no ārpuses, nevis iebūvēts no sākuma — papildinājums, nevis kodols.",
     "Komentārs šķiet no malas pievienots, it kā tas būtu pielīmēts jau pabeigtam tekstam.",
     "uz, papildus", "apstiprināt, pieņemt"),
    ("Zināšanu trūkums, nezināšana.",
     "Vienkārša nezināšana — zināšanu robs, bez jebkāda sprieduma.",
     "Viņš atzina savu nezināšanu par franču vīnu un ļāva someljē izvēlēties.",
     "ne", "zināt"),
    ("Pārmērīga interese par seksuālām lietām.",
     "Pārāk dedzīga, lūrējoša ziņkāre par visu pikanto — interese, kas pārgājusi veselīgo robežu uz uzbāzīgo.",
     "Tabloīda kārība par pāra privāto dzīvi robežojās ar apsēstību.",
     "niezēt, ilgoties", "stāvoklis"),
    ("Kvēpains, tumšs, dūmakains.",
     "Tumšs un dūmakains izskatā, it kā viss būtu pārklāts ar plānu kvēpu slāni.",
     "Kvēpaina dūmaka karājās pār rūpnīcas pilsētu krēslā.",
     "kvēpi", "pilns ar"),
    ("Noliegt vai pretoties.",
     "Plakani runāt pretī tam, ko kāds cits teica — teikt \"that's not so.\"",
     "Neviens neuzdrošinājās apstrīdēt vecā kapteiņa stāstu par vētru.",
     "pret", "runāt"),
    ("Slinkums, kūtrums (no latīņu).",
     "Vecs latīņu vārds tīram slinkumam — vilkšanās, kad negribas darīt neko vispār.",
     "Mūki sludināja pret slinkumu kā vienu no dvēseles klusajām briesmām.",
     "ne", "aizņemts, čakls"),
    ("Vairogs, uz kura attēlots ģerbonis.",
     "Vairoga formas emblēma, kas rāda ģimenes ģerboni — tās heraldiskā \"vārda plāksnīte.\"",
     "Ģimenes ģerbonis joprojām karājas virs vecās muižas priekšējām durvīm.",
     "vairogs", "mazināmais / priekšmets"),
    ("Novecojis, novecojis vai pensionēts vecuma dēļ.",
     "Pār savu noderīgo ziedu un palaists ganībās — pārāk vecmodīgs vai nodilis, lai turpinātu darbu.",
     "Novecojušais printeris beidzot tika nomainīts pēc piecpadsmit gadu ilgas ķīlēšanās.",
     "aiz, pāri", "gads"),
    ("Aizstājēji, īpaši medicīnā.",
     "Aizstājējzāles, ko lieto, kad īstā ārstēšana nav pieejama — būtībā medicīniskie dublieri.",
     "Kara ārsti bieži paļāvās uz aizstājējiem, kad īstās zāles beidzās.",
     "vietā", "iet, piekāpties"),
    ("Lielīga, trokšņaina runa.",
     "Liela, trokšņaina lielīšanās — skaļa runa par savu diženumu, kas galvenokārt ir karsts gaiss.",
     "Viņa lielīšanās par to, ka \"viens pats\" izglābis projektu, neapmānīja nevienu, kas tur tiešām bija bijis.",
     "lielīgs bruņinieks Orlando Furioso", "darbība, izrāde"),
    ("Izmantot viltību vai maldināšanu, lai kaut ko panāktu.",
     "Izslīdēt pie mērķa ar viltīgiem trikiem, nevis godīgu spēli.",
     "Viņš ar viltu ielavījās darījumā, izmantojot līgumu, pilnu sīkā teksta.",
     "gudrot, maldināt", "viltība; vēlāk ass pagrieziens"),
    ("Tīrā vai abstraktā mācīšanās vai zināšanu zinātne, bieži matemātika.",
     "Mācīšanās visšķīstākajā, visabstraktākajā formā — zināšanu dziļā struktūra pati, it īpaši matemātiskā.",
     "Filozofs sapņoja par universālu mathesis, kas varētu vienot visus zināšanu laukus.",
     "mācīties", "mācīšanās akts"),
    ("Pārmērīgi rūpīgs par formāliem noteikumiem vai sīkām detaļām.",
     "Pārāk strikts par sīkumiem — labo mazas tehniskas nianses, kas īsti neko nemaina.",
     "Šķita mazliet pedantiski strīdēties par \"who\" pret \"whom\" īsziņā.",
     "bērnu vadītājs, skolotājs", "kam piemīt veids"),
    ("Mirgojoša, dzirkstoša gaisma.",
     "Ātra, mirdzoša gaismas zibsnīšana — iedomājies saules gaismu uz ūdens vai dimantu, kas tver gaismu.",
     "Lustras mirdzums izkaisīja gaismu visos balles zāles stūros.",
     "mirdzēt, zibsnīt", "darbība"),
    ("Iesācējs, novicis.",
     "Kāds pavisam jauns prasmē vai jomā — vēl mācās virves, vēl nav eksperts.",
     "Pat iesācējs šahists var pamanīt to kļūdu.",
     "iesaucējs, novicis", "jauns, neapstrādāts kareivis"),
    ("Ārkārtīgi slikts, pretīgs.",
     "Slikts veidā, kas pelna īstu riebumu — ne tikai \"viduvējs,\" bet patiešām pretīgs.",
     "Recenzents nosauca turpinājumu par pretīgu, un kases cipari piekrita.",
     "lādēt", "cienīgs, spējīgs būt"),
    ("Asins sarkanā krāsā.",
     "Dziļš, spilgts sarkans — svaigu asiņu krāsa, slaveni lietota Šekspīra Makbetā.",
     "Saulriets pārvērta visas debesis asinssarkanā mirdzumā.",
     "iekšā", "miesa (miesas sarkans)"),
    ("Neliela sprauga vai telpa starp lietām.",
     "Tā mazā starpvieta, ko viegli nepamanīt — plaisa starp grīdas dēļiem, robs grafikā.",
     "Nezāles spiedās cauri katrai spraugai vecajā ķieģeļu celiņā.",
     "starp", "stāvēt"),
    ("Kritiskas vai nosodošas piezīmes.",
     "Asas, noraidošas piezīmes — tāda kritika, kurā ir mazliet rājiena tonis.",
     "Profesora aizrādījumi par eseju piepildīja malas ar sarkanu tinti.",
     "prāts", "griezties pretī"),
    ("Neiespējami atspēkot, nenoliedzams.",
     "Tik cieti pierādīts, ka nav, par ko strīdēties — lieta ir vienkārši slēgta.",
     "DNS pierādījumi bija neatspēkojami, un tiesa beidzās stundas laikā.",
     "ne", "pretoties, pretoties"),
    ("Sarežģītība, sarežģītība; arī ievirzīšanās iekšā.",
     "Sapīta, sevī ievirzīta sarežģītība — lietas, kas ietītas tik cieši kopā, ka tās grūti atraisīt.",
     "Sižeta samudžinājums lika pusei publikas mēģināt to atraisīt pēc titriem.",
     "iekšā, uz iekšu", "ritināt, griezt"),
    ("Spēks vai pūles, kā \"by dint of.\"",
     "Tīrs spēks vai pūles — mūsdienās galvenokārt paliek frāzē \"by dint of.\"",
     "Viņš nokārtoja eksāmenu, pateicoties tīrai, stūrgalvīgai praksei.",
     "sitiens, trieciens", "ar spēku"),
    ("Savienots ar iedobuma un ieliktņa savienojumu; cieši iekļauts kopā.",
     "Saslēgts kopā vecmodīgā galdnieka veidā — viens gabals ieiet cieši caurumā, kas izgriezts tieši tam.",
     "Vecās šķūņa sijas bija savienotas ar tapām bez nevienas naglas.",
     "ligzda, caurums", "kodums, saķere"),
    ("Ļoti atbilstošs, trāpīgs.",
     "Tieši pareizais brīdim — piezīme, citāts vai piemērs, kas nosēžas pilnīgi punktā.",
     "Viņas trāpīgā piezīme savilka visas debates vienā teikumā.",
     "uz", "novietot"),
    ("Maigi mirdzošs vai mirgojošs (gaisma); arī viegla asprātība.",
     "Mirdz maigi, nevis liesmo — mīksta, mirgojoša gaisma vai asprātība, kas ir rotaļīga, nevis asa.",
     "Sveču gaisma meta mirgojošu mirdzumu pāri vecajai ēdamistabai.",
     "laizīt", "darītājs (gaisma, kas 'laiž')"),
    ("Reliģisks vientuļnieks, kas dzīvo vientulībā.",
     "Kāds, kas pilnībā atkāpjas no pasaules, lai dzīvotu viens lūgšanā un pārdomās.",
     "Vientuļnieks dzīvoja mazā cellē, kas pievienota baznīcai, vairāk nekā trīsdesmit gadus.",
     "atpakaļ, projām", "atkāpties"),
    ("Dzēst slāpes; apmierināt.",
     "Pilnībā apmierināt alkas — visbiežāk slāpes, bet pārnestā nozīmē jebkuru dziļu vēlmi vai vajadzību.",
     "Viena auksta glāze ūdens remdēja viņa slāpes pēc gara pārgājiena.",
     "vaļīgs, vaļīgs", "atslābināt, nomierināt"),
    ("Adatas formas.",
     "Garš, tievs un smails kā adata — priežu adatas vai asa maza kristāla forma.",
     "Priedes ir viegli atpazīt pēc adatveida lapām.",
     "adata", "mazs"),
    ("Izsmelts no vitalitātes, vājš, pārmērīgi noslīpēts.",
     "Nodilis un mīksts — zaudējis sākotnējo spēku vai sparu caur pārāk daudz komforta vai izsmalcinātības.",
     "Kritiķi nosauca kādreiz drosmīgo žurnālu par izdzisušu, tā drosmīgo agrīno gadu ēnu.",
     "ārā", "auglīgs, kas ir nesis"),
    ("Piederums vai mazāks pievienots priekšmets vai tiesības.",
     "Mazs papildinājums, kas nāk kopā ar kaut ko lielāku — piederumi un papildinājumi, kas pieder pie galvenās lietas.",
     "Nomas līgums ietvēra garāžu un visus tās piederumus.",
     "uz", "piederēt"),
    ("Nogludināt vai mazināt vainu.",
     "Nogludināt kļūdu ar mīkstiem vārdiem, lai tā izklausītos mazāka, nekā ir.",
     "Viņš mēģināja aizrunāt palaisto termiņu ar neskaidru runu par \"neparedzētiem izaicinājumiem\".",
     "glosa, skaidrojums", "komentēt — tad nogludināt"),
    ("Agrīnā stadijā, tikko sācies.",
     "Tikko sāk rādīties — pats pirmais, tikko redzamais posms kaut kam lielākam, kas nāks.",
     "Ārsti noķēra slimības sākotnējās pazīmes, pirms tā varēja izplatīties.",
     "uz, iekšā", "ņemt (uzņemties, sākt)"),
    ("Radoša iedvesma, īpaši dievišķā.",
     "Pēkšņs iedvesmas vilnis, kas jūtas lielāks par tevi — it kā ideja būtu iepūsta tevī no kaut kur citur.",
     "Dzejnieks aprakstīja, kā viss darbs ieradās vienā iedvesmas uzliesmojumā pulksten trīs naktī.",
     "uz, virsū", "pūst (uzpūšana)"),
]
