# Indonesian rows: (definition, friendly, exampleGloss, root1, root2)
ROWS = [
    ("Memaniskan atau memurnikan; menghilangkan kekerasan dari sesuatu.",
     "Mengambil sengat atau kepahitan — secara harfiah memaniskan, atau secara kiasan melembutkan gagasan kasar agar lebih mudah ditelan.",
     "Penyunting melunakkan ulasan keras itu sebelum dicetak.",
     "keluar, secara tuntas", "manis"),
    ("Terlalu atau dibuat-buat religius atau saleh.",
     "Menggambarkan seseorang yang bakti agamanya terasa sandiwara, lebih pertunjukan daripada iman sejati.",
     "Desahan kesalehannya selama khotbah mengesalkan sisa bangku.",
     "kesalehan, kewajiban", "memiliki watak"),
    ("Ambiguitas dari struktur tata bahasa — kalimat yang bisa dibaca dua cara.",
     "Kalimat yang tata bahasanya benar tetapi bisa dibaca dua makna sama sekali berbeda, seperti \"Visiting relatives can be tiring\".",
     "\"Visiting relatives can be tiring\" adalah ketaksaan klasik — apakah kerabatnya yang melelahkan, atau mengunjungi mereka?",
     "keduanya, di kedua sisi", "melempar"),
    ("Tajam, menusuk, memotong lurus ke inti.",
     "Memotong omong kosong — komentar atau pikiran yang tajam sampai ke jantung perkara dengan cepat, tanpa kata sia-sia.",
     "Kritik tajamnya tidak menyisakan lubang plot film tempat bersembunyi.",
     "memotong", "melakukan, memiliki mutu"),
    ("Baru mulai; pada tahap awal atau sederhana.",
     "Masih di menit pembuka — rencana, perasaan, atau proses yang baru mulai berbentuk.",
     "Tahap awal perjanjian itu menjanjikan, tetapi banyak rincian masih terbuka.",
     "memulai, mengawali", "cenderung ke arah"),
    ("Pidato atau tulisan resmi yang memuji seseorang dengan tinggi.",
     "Penghormatan formal yang penuh — bayangkan eulogi bersinar atau pidato yang menyanyikan prestasi dari atap.",
     "Profesor yang pensiun diantar dengan pidato pujian dari mahasiswanya yang terdekat.",
     "semua", "majelis, kumpulan"),
    ("Berkaitan dengan keberadaan nyata atau ada faktual, bukan teori abstrak.",
     "Tentang hal-hal sebagaimana benar-benar ada, bukan hanya sebagai gagasan atau teori tentangnya.",
     "Para filsuf berdebat apakah bilangan punya status keberadaan atau hanya ada di pikiran kita.",
     "ada, yang wujud", "berkaitan dengan"),
    ("Berbuah, atau menjadi produktif.",
     "Akhirnya membuahkan hasil — usaha, gagasan, atau investasi yang tumbuh dari benih menjadi sesuatu yang berguna.",
     "Tahun-tahun riset sunyi akhirnya berbuah menjadi vaksin yang bekerja.",
     "buah", "membuat, menyebabkan"),
    ("Mengantisipasi atau menampilkan sesuatu seolah sudah selesai sebelum benar-benar terjadi.",
     "Mendahului secara sastra — menggambarkan peristiwa masa depan seolah sudah selesai, agar poin lebih keras.",
     "Toast jenderal untuk \"kemenangan\" yang mendahului waktu disampaikan seminggu penuh sebelum pertempuran.",
     "sebelum", "mengambil, merebut"),
    ("Digerakkan tekanan udara; juga berkaitan dengan roh atau napas.",
     "Biasanya berarti \"ditenagai udara bertekanan\" — meski juga bisa berarti roh atau napas.",
     "Rem angin mendesis saat bus merapat ke trotoar.",
     "angin, napas, roh", "berkenaan dengan"),
    ("Menggambarkan Tuhan atau yang ilahi lewat pernyataan positif — kebalikan apofatik.",
     "Cara berbicara tentang Tuhan dengan mengatakan apa adanya Tuhan — \"God is love\" — bukan hanya apa yang bukan Tuhan.",
     "Teologi afirmatif berbicara yakin tentang Tuhan sebagai pengasih, adil, dan murah hati.",
     "ke bawah, menurut", "berbicara, berkata"),
    ("Berdasarkan kepercayaan atau iman; juga dipakai sebagai titik acuan tetap.",
     "Sesuatu yang Anda terima dengan percaya lalu jadikan jangkar — tanda acuan adalah titik tetap tempat segala diukur.",
     "Para juru ukur menempatkan penanda acuan di batuan dasar sebelum memetakan lokasi.",
     "percaya", "kepercayaan, keyakinan"),
    ("Pembelaan kebaikan Tuhan mengingat adanya kejahatan.",
     "Upaya kuno menjawab \"Jika Tuhan baik, mengapa kejahatan ada?\"",
     "Tesisnya menelusuri teodisi lewat lensa Kitab Ayub.",
     "tuhan", "keadilan"),
    ("Saling tinggal di dalam — istilah teologi tentang pribadi Tritunggal yang ada di dalam satu sama lain.",
     "Kata teologi untuk kebersamaan tiga-dalam-satu begitu lengkap hingga tiap bagian berisi dan diisi yang lain.",
     "Doktrin saling-meresap mencoba menjelaskan bagaimana Bapa, Anak, dan Roh berbeda namun tak terpisahkan.",
     "sekitar", "pergi, berjalan"),
    ("Menghasilkan akibat yang menguntungkan atau memantul pada seseorang.",
     "Ketika pujian (atau celaan) memantul ke orang yang bertanggung jawab — perbuatan baik yang berpulang pada nama baik berputar membalas Anda.",
     "Keberhasilan tim akan berpulang pada jasa pelatihnya yang sunyi dan pekerja keras.",
     "kembali, lagi", "gelombang"),
    ("Tidak dapat dihindari atau diloloskan.",
     "Pasti terjadi apa pun yang Anda lakukan — tidak ada celah keluar dari hasil yang tak terelakkan.",
     "Usia tua datang pada semua orang; itu semata tak terelakkan.",
     "tidak", "berjuang keluar"),
    ("Memakai ungkapan berputar, bertele-tele, bukan bentuk langsung.",
     "Menempuh jalan panjang dengan kata — berkata \"make a decision\" alih-alih \"decide\".",
     "Surel berbelitnya bisa mengatakan dalam satu baris apa yang memakan tiga paragraf.",
     "sekitar", "menyatakan, menceritakan"),
    ("Ketumpulan atau kelesuan mental.",
     "Keadaan pikiran berkabut, lamban, di mana berpikir terasa seperti mengarungi sirup.",
     "Gelombang ketumpulan pikiran menghantam kelas tepat setelah makan siang.",
     "tumpul, tidak tajam", "keadaan atau mutu"),
    ("Tidak menguntungkan; pertanda buruk.",
     "Tanda buruk — kondisi atau waktu yang seolah bekerja melawan Anda sebelum mulai.",
     "Langit kelabu dan aki mati membuat awal perjalanan darat yang tak menjanjikan.",
     "tidak", "menguntungkan, murah hati"),
    ("Daging direbus atau dimasak dalam saus — ejaan yang benar \"fricasseed\".",
     "Istilah masak lama yang nyaman untuk daging yang dipotong dan direbus pelan dalam sausnya sendiri hingga empuk.",
     "Ayam rebus bersaus nenek adalah bintang setiap makan malam Minggu.",
     "menggoreng", "memecah (jadi potongan)"),
    ("Pengganti buatan atau yang lebih rendah.",
     "Tiruan yang berdiri menggantikan yang asli — secara teknis berfungsi, tetapi semua tahu bukan barang asli.",
     "Pembeli masa perang bertahan dengan kopi tiruan dari chicory sangrai.",
     "keluar, awalan pengganti", "meletakkan, menempatkan"),
    ("Memperlakukan gagasan abstrak seolah benda konkret.",
     "Membuat gagasan terasa nyata dan padat — mengubah yang kabur, seperti \"the economy\", menjadi benda yang bisa ditunjuk.",
     "Menyebut \"jiwa\" suatu bangsa sebagai wujud sendiri membendakan sesuatu yang sebenarnya hanya jutaan pilihan individu.",
     "benda", "membuat"),
    ("Lolos atau menghindar dengan cakap.",
     "Menyelinap bersih — mengelak tangkapan, pertanyaan, atau jawaban, sering dengan licin atau nyaris.",
     "Jawaban itu luput darinya berjam-jam sampai tiba-tiba nyambung di kamar mandi.",
     "keluar, pergi", "bermain"),
    ("Mengungkapkan keraguan, kebingungan, atau kontradiksi yang belum selesai.",
     "Terjebak di jalan buntu pikiran yang sungguh — bukan bingung karena malas, melainkan karena pertanyaan itu sendiri menolak jawaban rapi.",
     "Sokrates sering mengakhiri dialog dengan nada buntu, lebih banyak pertanyaan daripada jawaban.",
     "tanpa", "lorong, jalan"),
    ("Majas yang menamai sesuatu dengan istilah terkait, misalnya \"the crown\" untuk raja.",
     "Memakai kata terkait menggantikan yang sebenarnya — berkata \"the White House announced\" padahal maksudnya pemerintahan.",
     "\"Wall Street had a rough day\" adalah metonimia — artinya pasar saham yang kacau.",
     "perubahan, setelah", "nama"),
    ("Mencabut akar; merenggut dari lingkungan alaminya.",
     "Menarik sesuatu (atau seseorang) sampai ke akar, jauh dari tempat atau budaya tempatnya milik.",
     "Perang mencabut seluruh generasi dari akarnya, menyebarkan keluarga melewati perbatasan.",
     "jauh, lepas", "akar"),
    ("Sedap didengar.",
     "Sekadar enak didengar — kata, nama, atau kalimat yang merdu mengalir di telinga hampir musikal.",
     "\"Murmuring brook\" adalah frasa merdu yang kecil, lembut dan mudah diucapkan.",
     "baik, bagus", "bunyi, suara"),
    ("Umumnya dianggap atau disangka.",
     "Dipercaya luas benar meski belum terbukti — versi \"supposed\".",
     "Orang yang dianggap penulis surat itu kemudian ternyata orang asing total.",
     "berpikir, menganggap", "memiliki sifat"),
    ("Kata atau frasa yang baru diciptakan.",
     "Kata baru sama sekali — baru saja diciptakan, belum (atau hampir belum) masuk kamus.",
     "\"Doomscrolling\" bermula sebagai kata baru dan cepat menjadi slang sehari-hari.",
     "baru", "kata, ucapan"),
    ("Marah atau berperangai buruk.",
     "Dalam suasana jelek, mudah meledak — seperti orang dulu percaya limpa mengatur amarah.",
     "Dia menembakkan balasan berang beberapa detik setelah membaca surel.",
     "limpa (tempat amarah)", "dipengaruhi"),
    ("Suka bermoral dengan gaya sombong atau dibuat-buat.",
     "Suka menyampaikan pelajaran hidup dengan penting diri, seolah setiap kalimat kue keberuntungan.",
     "Toast yang menggurui tentang \"makna sejati persahabatan\" membuat semua memeriksa jam.",
     "pendapat, pepatah", "penuh"),
    ("Terlalu banyak bicara, terutama soal sepele.",
     "Tidak berhenti ngobrol — mengoceh hal kecil lama setelah orang lain kehabisan kata.",
     "Sopir taksi cerewet itu menceritakan seluruh hidupnya sebelum kami meninggalkan bandara.",
     "cerewet, mengoceh", "cenderung"),
    ("Kebodohan, kekonyolan.",
     "Bodoh belaka — komentar atau rencana begitu konyol hampir tak pantas dijawab serius.",
     "Kedunguan murni rencana itu menjadi jelas saat mereka mencobanya.",
     "bodoh, konyol", "keadaan"),
    ("Bagian penutup pidato, sering merangkum.",
     "Penutup besar pidato — bagian penutup di mana pembicara merangkum segala dan menancapkan poin.",
     "Menjelang penutup pidato, separuh hadirin sudah berdiri.",
     "melalui, sampai akhir", "berbicara, membela"),
    ("Pengulangan sia-sia gagasan yang sama dengan kata berbeda.",
     "Mengatakan hal yang sama dua kali tanpa menambah apa pun, seperti \"free gift\" atau \"end result\".",
     "\"It is what it is\" adalah tautologi kesukaan orang yang menghindari penjelasan sungguhan.",
     "yang sama", "kata, ucapan"),
    ("Pemakaian sangat sedikit kata; ucapan ringkas.",
     "Mengatakan banyak dengan sangat sedikit — seni jawaban pendek, blak-blakan, dari Sparta Laconia yang terkenal singkat.",
     "\"Molon labe\" — \"datang dan ambillah\" — adalah ucapan singkat paling terkenal dalam sejarah.",
     "seorang Sparta Laconia", "kebiasaan, cara"),
    ("Gagasan hambar, terlalu disederhanakan; aslinya makanan hambar atau bubur.",
     "Pikiran yang diencerkan — isi begitu disederhanakan dan aman hingga tak bernutrisi bagi pikiran.",
     "Pidato politisi itu sebagian besar omong hambar: janji kabur yang tak bisa dipaku.",
     "memberi makan", "sarana atau alat"),
    ("Menyebabkan tidur atau kantuk.",
     "Begitu membosankan — atau secara harfiah menenangkan — hingga membuat ngantuk. Pikirkan susu hangat, atau rapat anggaran tiga jam.",
     "Dengung kuliah yang mengantukkan itu membuat separuh ruangan berjuang membuka mata.",
     "tidur nyenyak", "membuat, menyebabkan"),
    ("Terlalu menyanjung atau berminyak dalam sikap.",
     "Licin memikat sampai terasa licin — pujian dilumur begitu tebal hampir terasa lemaknya.",
     "Penjual yang menjilat itu terus memuji \"selera unggul\" saya sebelum setiap penjualan tambahan.",
     "mengurapi, mengoles minyak", "penuh"),
    ("Cepat mencari salah, terlalu kritis pada hal sepele.",
     "Cerewet sampai berlebihan — tipe yang menemukan masalah di segala hal, meski tak penting.",
     "Catatan yang suka mencela pada laporan hanya fokus pada letak koma.",
     "menangkap, mengambil", "perangkap, sofisma"),
    ("Lamban, tidak aktif secara mental atau fisik.",
     "Lambat dan setengah tidur, seperti beruang hibernasi — hampir tak bergerak, hampir tak berpikir.",
     "Kantor menjadi lesu dalam panas berat Agustus.",
     "kebas, lamban", "dalam keadaan"),
    ("Pengurus atau pejabat yang mengelola rumah tangga abad pertengahan.",
     "Versi abad pertengahan kepala staf — pejabat tepercaya yang menjalankan rumah dan tanah tuan sehari-hari.",
     "Kepala rumah tangga kastil mengelola segala dari pembukuan panen sampai daftar tamu.",
     "tua, senior", "pelayan"),
    ("Berbicara atau menulis panjang lebar tentang suatu topik.",
     "Benar-benar masuk mode — berbicara atau menulis terus, mencakup setiap sudut.",
     "Tanyakan mobil klasik dan dia akan berpanjang lebar selama satu jam penuh.",
     "keluar", "ruang"),
    ("Tak bernilai, sepele; juga tidak sah atau tak efektif.",
     "Pada dasarnya tak berharga — klausul yang tak berlaku dalam kontrak adalah yang sebenarnya tak melakukan apa pun.",
     "Pengadilan menyatakan peraturan lama itu tak berlaku, karena tak pernah ditegakkan.",
     "hal sepele, omong kosong", "milik"),
    ("Kebijaksanaan, pertimbangan tajam.",
     "Kebijaksanaan praktis yang tajam — pertimbangan baik dari pengalaman, bukan hanya buku.",
     "Kearifan kapten tua itu lebih dari sekali menjaga awak dari kesusahan.",
     "penciuman tajam, cerdik", "mutu dari"),
    ("Rakyat jelata atau massa, dipakai dengan penghinaan.",
     "Kata sombong, merendahkan untuk \"rakyat rendah\" atau orang biasa.",
     "Sang comte menyeringai pada gerombolan hina yang berkumpul di luar gerbang istana.",
     "anjing", "kumpulan, kawanan"),
    ("Perlakuan atau bahasa yang lancang, mempermalukan.",
     "Perlakuan kejam, menghina yang dimaksudkan mempermalukan — hinaan yang dirancang menyakitkan.",
     "Dia menahan bertahun-tahun hinaan dari kritikus sebelum karyanya diakui.",
     "bersama, secara tuntas", "menggembung (karena sombong)"),
    ("Dengan curiga atau tidak setuju; pandangan menyamping.",
     "Pandangan menyamping yang Anda berikan pada sesuatu yang belum dipercaya — tatapan penuh ragu.",
     "Guru memandang dengan sebelah mata pekerjaan rumah yang mencurigakan rapinya.",
     "pada, ke", "miring, bias"),
    ("Orang bodoh; kepala batu.",
     "Hinaan kuno, hampir sayang, untuk orang yang sedang bebal — kepala batu.",
     "\"Kau tolol,\" dia tertawa, \"peta itu terbalik sepanjang waktu.\"",
     "gumpalan tanah", "kepala"),
    ("Menggerakkan ke dalam gerak atau tindakan; memotivasi.",
     "Menjadi percikan yang menggerakkan — mesin menyala atau orang akhirnya bertindak atas gagasan.",
     "Takut kehilangan kontrak menggerakkan seluruh tim ke lembur akhir pekan.",
     "perbuatan, dorongan", "mendorong, melakukan"),
    ("Penggelapan dana yang dipercayakan.",
     "Diam-diam mencuri uang yang dipercayakan pada Anda — penggelapan berjas kuno.",
     "Penggelapan bendahara itu tak terdeteksi hampir satu dekade.",
     "harta pribadi", "ternak, kekayaan"),
    ("Kelompok yang dianggap di pinggiran masyarakat terhormat.",
     "Dunia bawah sosial yang glamor tapi gelap — orang yang hidup tepat di luar aturan masyarakat \"terhormat\".",
     "Novel itu mengikuti seorang penyanyi menavigasi dunia remang kabaret 1920-an.",
     "setengah", "dunia, masyarakat"),
    ("Masih ada; tidak punah atau dihancurkan.",
     "Masih ada hari ini — dipakai untuk benda lama (naskah, spesies, bangunan) yang berhasil bertahan.",
     "Hanya tiga salinan yang tersisa dari cetakan pertama yang diketahui ada.",
     "keluar", "berdiri"),
    ("Kecurangan; pengkhianatan kepercayaan.",
     "Pengkhianatan dalam, disengaja — merusak kepercayaan yang wajar diharapkan Anda jaga.",
     "Jenderal tak pernah memaafkan pengkhianatan teman lamanya di meja perundingan.",
     "melalui, melawan", "iman, kepercayaan"),
    ("Dialek daerah, terutama yang nonstandar.",
     "Cara bicara lokal yang khas di suatu daerah — penuh kata dan irama yang orang luar mungkin tak tangkap.",
     "Neneknya masih berbicara logat daerah pulau itu saat makan malam keluarga.",
     "ucapan kasar, dialek", "cakar — bicara canggung"),
    ("Hak istimewa milik seseorang atau kelompok.",
     "Hak istimewa yang hanya milik Anda — hak yang datang dengan peran, jabatan, atau status.",
     "Memilih tujuan liburan keluarga adalah hak istimewa kakek, dan semua mengetahuinya.",
     "sebelum", "bertanya, memberi suara"),
    ("Keberanian, kelancangan; juga ketangguhan atau daya tahan.",
     "Ketahanan kasar yang berani — nyali maju dan ketangguhan terus setelah itu.",
     "Butuh keberanian sungguhan untuk menyeberangi celah dalam badai salju tanpa peta.",
     "berani, tangguh", "keadaan, kondisi"),
    ("Mekar penuh; juga berkembang atau muncul berangsur.",
     "Mekar menjadi ungkapan penuh — seperti bunga membuka, atau gagasan akhirnya menjadi dirinya.",
     "Bakat lukisnya yang sunyi mekar begitu dia punya studio sendiri.",
     "keluar", "mulai mekar"),
    ("Tali berbobot untuk menentukan tegak lurus; kiasan, standar penilaian.",
     "Bobot pada tali yang tergantung lurus ke bawah, untuk memeriksa apakah sesuatu benar-benar vertikal — dan, lebih luas, standar tetap yang Anda ukur segala terhadapnya.",
     "Dia memakai kejujuran kakeknya sendiri sebagai semacam unting-unting bagi setiap keputusan.",
     "timah", "tali, ukuran"),
    ("Dengan senang, dengan rela (arkais).",
     "Cara kuno mengatakan \"dengan senang\" atau \"dengan senang hati\".",
     "\"Aku ingin sekali beristirahat di sini sejenak,\" keluh sang musafir.",
     "gembira, riang", "dengan senang, dengan rela"),
    ("Kritik publik yang keras atau aib.",
     "Malu publik yang ditumpuk pada seseorang secara besar, terlihat — aib dari ketidaksetujuan luas.",
     "Skandal itu membawa aib publik ke seluruh firma.",
     "melawan", "aib, celaan"),
    ("Sarkastis tajam, pedas dalam kecerdasan atau kritik.",
     "Kecerdasan yang punya gigi — komentar pedas sedikit menusuk justru karena sasarannya begitu cermat.",
     "Ulasan film pedasnya ditakuti sutradara dan dicintai pembaca.",
     "menggigit", "menggigit, melakukan"),
    ("Maklumat resmi, sering politis atau militer.",
     "Pengumuman besar, resmi — biasanya menyatakan pemerintahan baru, pemberontakan, atau dekret besar.",
     "Maklumat militer jenderal mengumumkan pemerintahan baru saat fajar.",
     "ke depan", "mengumumkan"),
    ("Orang berpengetahuan dangkal yang berpura-pura ahli.",
     "Seseorang yang hanya menyapu permukaan topik lalu bicara seolah menulis buku teksnya.",
     "Si sok tahu di pesta makan malam itu dengan percaya diri mengoreksi astrofisikawan sungguhan di meja.",
     "mengetahui", "diminutif — penahu kecil"),
    ("Kemunduran daya mental di usia tua.",
     "Masa tua sangat lanjut yang berkabut, pelupa, ketika ketajaman pikiran mulai pudar.",
     "Dalam masa pikunnya, dia menceritakan tiga kisah yang sama setiap kunjungan, setiap kali seolah baru.",
     "pikun, menjadi bodoh", "keadaan atau hasil"),
    ("Sisi terlindung dari angin.",
     "Sisi tenang, terlindung — bukit, kapal, tembok — tempat angin tak cukup menjangkau Anda.",
     "Para pendaki memasang tenda di sisi bawah angin punggungan untuk lolos dari hembusan.",
     "perlindungan, naungan", "sisi, muka"),
    ("Menangkis atau menepis pukulan, pertanyaan, atau argumen.",
     "Menepis dengan licin — tebasan pedang, pertanyaan canggung, atau tuduhan — tanpa kehilangan irama.",
     "Dia menangkis pertanyaan rumit reporter dengan lelucon ringan.",
     "menangkis", "menyiapkan, membela"),
    ("Berbau busuk, beracun.",
     "Berbau sampai terasa hampir beracun — bau begitu buruk hingga berbahaya dihirup.",
     "Bau busuk naik dari rawa saat matahari terbenam.",
     "uap beracun", "memiliki sifat"),
    ("Orang yang berbakti pada kemewahan dan kesenangan.",
     "Seseorang yang hidup untuk kenyamanan dan pemanjaan — makanan enak, ranjang lembut, hidup mudah — dari kota Yunani kuno Sybaris yang terkenal berlebih.",
     "Pemuja kemewahan sejati, dia menolak kamar hotel tanpa bak mandi.",
     "kota Yunani kuno terkenal mewah", "penduduk"),
    ("Sengaja mengesampingkan atau mengabaikan sebagian.",
     "Sengaja menaruh sepotong teka-teki ke samping di pikiran, agar fokus bersih pada sisanya.",
     "Mari kesampingkan biaya sejenak dan hanya bertanya apakah rencana itu benar-benar jalan.",
     "sebelum, jauh", "memotong"),
    ("Mengkritik keras; juga menguliti.",
     "Mencerabuti seseorang dengan kritik keras — secara lisan, seolah benar-benar menguliti.",
     "Para kritikus mengecam keras sekuel itu karena mengkhianati segala yang disukai penggemar dari yang asli.",
     "lepas", "kulit, kulit binatang"),
    ("Mengutip sebagai bukti atau dalil.",
     "Mengajukan fakta atau contoh untuk menopang poin — hal yang Anda tunjuk ketika seseorang bertanya \"what's your evidence?\".",
     "Pengacara mengajukan tiga saksi mendukung alibi kliennya.",
     "ke, menuju", "memimpin"),
    ("Perjalanan atau pengembaraan, terutama yang panjang dan luas.",
     "Perjalanan panjang, mengembara — pengembaraan luas yang membawa Anda jauh dari rumah cukup lama.",
     "Pengembaraannya di tiga benua memenuhi satu rak jurnal perjalanan.",
     "melalui", "ladang, tanah (peregrinus: orang asing)"),
    ("Pengemis, atau orang yang hidup dari sedekah.",
     "Seseorang yang hidup dengan meminta belas kasihan — secara historis juga biarawan yang bersumpah miskin dan hidup dari sumbangan.",
     "Para biarawan pengemis tidak memiliki apa pun dan sepenuhnya mengandalkan kebaikan penduduk desa.",
     "mengemis", "pengemis"),
    ("Sangat dermawan.",
     "Dermawan dalam skala besar, hampir pamer — pemberian yang membuat orang sedikit terengah.",
     "Sumbangan dermawan itu membiayai seluruh sayap baru perpustakaan.",
     "hadiah, jasa", "membuat, memberi"),
    ("Kelelahan karena kurang gizi; juga kurang daya hidup.",
     "Keadaan lemah, terkuras karena tidak diberi makan atau bahan bakar — harfiah dari lapar, atau kiasan dari tak tersisa apa pun untuk berjalan.",
     "Menjelang akhir pengepungan, para prajurit hampir kehabisan daya.",
     "kosong, hampa", "tindakan atau hasil"),
    ("Kritik pahit, kasar.",
     "Kritik yang jauh melewati adil dan menjadi omelan marah, pahit.",
     "Komentar daring larut menjadi cacian murni dalam hitungan menit.",
     "kesalahan", "menyiapkan, menyediakan"),
    ("Bermusuhan, merugikan dalam efek.",
     "Bekerja melawan Anda, meski diam-diam — kondisi atau sikap yang tidak ramah pada kepentingan Anda.",
     "Kebijakan baru itu merugikan usaha kecil, meski bukan itu niatnya.",
     "tidak", "teman"),
    ("Cenderung menimbulkan dendam atau ketidakpuasan, sering lewat perbandingan tidak adil.",
     "Pasti membuat seseorang merasa diremehkan — biasanya karena menyusun orang atau hal secara tidak adil.",
     "Memeringkat saudara berdasarkan \"siapa yang paling disayang Ibu\" adalah permainan yang menimbulkan iri dan tak boleh dimainkan siapa pun.",
     "iri", "memandang (dengan niat buruk)"),
    ("Orang berpangkat atau status lebih rendah; bawahan.",
     "Seseorang lebih rendah di rantai komando atau tangga sosial — yunior, bekerja di bawah yang lebih berkuasa.",
     "Sebagai perwira rendahan muda, dia menerima perintah lama sebelum pernah memberikannya.",
     "di bawah", "pengganti, lain"),
    ("Merasa atau menyatakan kebencian kuat.",
     "Membenci sesuatu sampai mengutuknya keras-keras — kebencian murni, bersuara.",
     "Penduduk desa mengutuk penagih pajak setiap gerobaknya melintas kota.",
     "keluar dari", "suci (mengutuk keluar dari yang suci)"),
    ("Penutup luar alami, seperti kulit atau cangkang.",
     "Bungkus pelindung milik alam — kulit, cangkang, sekam, atau kulit buah, apa pun yang menutupi dan melindungi yang hidup.",
     "Cangkang kura-kura adalah selubung yang luar biasa tangguh.",
     "pada, di atas", "menutupi"),
    ("Polos, naif, menunjukkan kesederhanaan kekanak-kanakan; kebalikan \"disingenuous\".",
     "Terbuka percaya dan sedikit naif, tanpa agenda tersembunyi — mudah tertukar dengan \"ingenious\" yang berarti cerdik.",
     "Pertanyaan polosnya — \"mengapa ada orang berbohong tentang itu?\" — menunjukkan betapa sedikit muslihatnya.",
     "di dalam, asli", "memperanakkan (lahir merdeka, jujur)"),
    ("Kepedulian berlebihan pada rincian kecil atau aturan.",
     "Tersesat di aturan kecil sambil melewatkan gambar besar — terobsesi pada cetakan halus yang tak peduli orang lain.",
     "Kerewelannya soal koma Oxford menggagalkan seluruh rapat.",
     "guru anak-anak", "kebiasaan atau mutu"),
    ("Pemeriksaan teliti dan hati-hati.",
     "Tinjauan dalam, tak ada batu terlewat — menelusuri setiap rincian dengan sungguh.",
     "Hanya setelah penelitian saksama atas buku besar, selisih itu muncul.",
     "melalui, secara tuntas", "mencari, memeriksa"),
    ("Mengajukan keberatan; menunjukkan keengganan.",
     "Menolak secara sopan atau ragu alih-alih langsung menurut — \"I'd rather not\" yang lembut.",
     "Ketika diminta menandatangani tanpa membaca, dia berkeberatan.",
     "dari, jauh", "menunda"),
    ("Secara lahiriah masuk akal tetapi sebenarnya salah.",
     "Terdengar meyakinkan sekilas tetapi runtuh begitu Anda benar-benar memeriksa.",
     "\"Everyone's doing it\" adalah argumen menyesatkan yang tak pernah bertahan di bawah pemeriksaan.",
     "penampilan, rupa", "penuh (tampak indah)"),
    ("Omongan tidak tulus, munafik, sering bermoral.",
     "Ceramah yang terdengar bajik tetapi tidak ditopang perasaan nyata — pose moral otomatis.",
     "Dia lelah dengan omong kosong munafik tentang \"keluarga\" dari perusahaan yang tak pernah memberi cuti siapa pun.",
     "menyanyi (kemudian: jargon bernada)", "celoteh pengemis, lalu kemunafikan"),
    ("Kurang keberanian, pengecut.",
     "Penakut sampai tak bertulang punggung — terlalu takut berdiri meski jelas penting.",
     "Keheningan pengecut dewan membiarkan skandal berputar di luar kendali.",
     "sangat kecil", "semangat, keberanian"),
    ("Seperti rubah; licik, cerdik.",
     "Licin dan cerdas seperti rubah — cepat berpikir, sedikit licik, selalu selangkah di depan.",
     "Dia memberi senyum licik begitu melihat celah hukum.",
     "rubah", "dari atau seperti"),
    ("Satu demi satu, berurutan.",
     "Diambil ketat satu per satu, berurutan — tanpa loncat, tanpa dua sekaligus.",
     "Hakim menangani masing-masing dari dua belas tuntutan satu per satu.",
     "baris, urutan", "satu per satu"),
    ("Kehematan ekstrem; kekikiran.",
     "Ketat dengan uang (atau kata, atau sumber daya) jauh melewati hemat yang wajar.",
     "Kekikirannya legendaris — kantong teh dipakai ulang tiga kali.",
     "menghemat, berhemat", "keadaan atau kebiasaan"),
    ("Koreksi, terutama dalam teks.",
     "Perbaikan pada tulisan — sentuhan ilmiah yang memperbaiki kesalahan dalam teks lama atau penting.",
     "Edisi baru mencakup puluhan perbaikan pada naskah asli.",
     "keluar dari", "kesalahan, galat"),
    ("Sedang dalam makan dan minum.",
     "Sengaja menahan diri seputar makanan dan minuman — tak pernah berlebih, selalu menyisakan sedikit di piring.",
     "Kebiasaan berpantangnya menjaganya tajam lama setelah rekan-rekannya melambat.",
     "jauh dari", "minuman memabukkan"),
    ("Kesalahan tata bahasa atau pelanggaran etiket.",
     "Khilaf tata bahasa atau sopan santun — jenis kesalahan kecil yang membuat orang teliti meringis.",
     "\"Between you and I\" adalah kesalahan gramatikal umum yang masih membuat ahli tata bahasa tersentak.",
     "kota Kilikia terkenal karena Yunani yang 'buruk'", "kebiasaan, cara"),
    ("Berkaitan dengan konflik dalam kelompok; saling merusak.",
     "Pertikaian internal yang merobek kelompok dari dalam — pertarungan di mana semua kalah, karena keluarga lawan keluarga.",
     "Pertengkaran internal yang saling membinasakan di partai itu lebih merusak daripada lawan luar mana pun.",
     "antara, di antara", "membunuh"),
    ("Sikap acuh, ceroboh.",
     "Anggukan bahu yang menjadi seluruh kepribadian — peduli begitu sedikit pada hal yang dulu penting hingga tak ada yang tampak layak diupayakan.",
     "Sikap acuh tak acuhnya terhadap upacara penghargaan mengejutkan semua yang tahu betapa kerasnya dia bekerja.",
     "sedikit", "peduli"),
    ("Situasi atau sengketa yang kacau dan rumit.",
     "Keadaan kusut, berantakan yang sulit dipahami — sebagian salah paham, sebagian drama, seluruhnya kacau.",
     "Seluruh kekusutan bagan tempat duduk dimulai dari satu kartu nama yang salah letak.",
     "di dalam", "mengusut, mengacaukan"),
    ("Mengancam, menakutkan.",
     "Membawa aura ancaman yang tak salah — tatapan atau surat yang mengancam membuat sangat jelas sesuatu yang buruk mungkin menyusul.",
     "Nada mengancam surat itu membuat penyewa gelisah bahkan sebelum membuka amplop.",
     "mengancam", "berfungsi untuk"),
    ("Kritik publik kuat atau caci maki.",
     "Kecaman publik yang keras — kritik membakar yang berlangsung di depan semua orang.",
     "Penyingkap itu menghadapi bertahun-tahun cercaan publik sebelum sejarah membuktikan dia benar.",
     "melawan", "berbicara"),
    ("Ledakan tiba-tiba yang keras, emosi atau tindakan.",
     "Semburan tiba-tiba, intens yang menelan Anda sekaligus — tawa, amarah, atau batuk yang datang seperti gelombang.",
     "Dia dilanda serangan tawa yang tak bisa dijelaskannya pada siapa pun di ruangan.",
     "melampaui", "tajam, akut"),
    ("Ditambahkan dari sumber luar, bukan melekat.",
     "Dibaut dari luar alih-alih dibangun dari awal — tambahan, bukan inti.",
     "Komentar itu terasa sebagai tambahan dari luar, seolah ditempel pada teks yang sudah selesai.",
     "ke, tambahan", "menyetujui, menerima"),
    ("Kurang pengetahuan, ketidaktahuan.",
     "Sekadar tidak-tahu — celah pengetahuan, tanpa penilaian melekat.",
     "Dia mengakui ketidaktahuannya tentang anggur Prancis dan membiarkan sommelier memilih.",
     "tidak", "mengetahui"),
    ("Minat berlebihan pada hal seksual.",
     "Rasa ingin tahu yang terlalu bersemangat, melirik, tentang apa pun yang cabul — minat yang melewati sehat menjadi mengintip.",
     "Nafsu cabul tabloid atas kehidupan pribadi pasangan itu mendekati obsesif.",
     "gatal, merindukan", "keadaan"),
    ("Berjelaga, gelap, keruh.",
     "Gelap dan berasap, seolah segala dilapisi jelaga tipis.",
     "Kabut berjelaga menggantung di kota pabrik saat senja.",
     "jelaga", "penuh"),
    ("Menyangkal atau menyanggah.",
     "Berkata menentang secara tegas apa yang dikatakan orang lain — berkata \"that's not so\".",
     "Tak seorang pun berani membantah kisah kapten tua tentang badai itu.",
     "melawan", "berbicara"),
    ("Kemalasan, kelambanan (dari Latin).",
     "Kata Latin kuno untuk kemalasan murni — tarikan tidak ingin melakukan apa pun.",
     "Para biarawan berkhotbah menentang kemalasan sebagai salah satu bahaya sunyi jiwa.",
     "tidak", "sibuk, rajin"),
    ("Perisai yang menampilkan lambang.",
     "Emblem berbentuk perisai yang menunjukkan lambang keluarga — \"papan nama\" heraldiknya.",
     "Perisai lambang keluarga itu masih tergantung di atas pintu depan manor tua.",
     "perisai", "diminutif / benda"),
    ("Ketinggalan zaman, usang, atau pensiun karena usia.",
     "Lewat masa puncak gunanya dan dilepas ke padang — terlalu kuno atau aus untuk terus bekerja.",
     "Printer uzur itu akhirnya diganti setelah lima belas tahun macet.",
     "melampaui", "tahun"),
    ("Pengganti, terutama dalam kedokteran.",
     "Obat pengganti dipakai ketika pengobatan sungguhan tak tersedia — pada dasarnya pemain cadangan medis.",
     "Dokter masa perang sering mengandalkan obat pengganti ketika obat yang pantas habis.",
     "sebagai ganti", "pergi, menyerahkan"),
    ("Omongan sombong, menggertak.",
     "Pamer besar, berangin — bicara keras tentang kehebatan sendiri yang sebagian besar angin.",
     "Sesumbarnya tentang \"sendirian\" menyelamatkan proyek tak menipu siapa pun yang benar-benar ada di sana.",
     "ksatria sombong dalam Orlando Furioso", "tindakan, pamer"),
    ("Memakai tipu daya atau kecurangan untuk meraih sesuatu.",
     "Menggeliat menuju tujuan lewat trik licik alih-alih permainan adil.",
     "Dia mengakali jalannya masuk ke kesepakatan dengan kontrak penuh cetakan halus.",
     "mengutik, menipu", "tipu daya; kemudian belokan tajam"),
    ("Ilmu murni atau abstrak tentang belajar atau pengetahuan, sering matematika.",
     "Belajar dalam bentuk paling murni, paling abstrak — struktur dalam pengetahuan itu sendiri, terutama yang matematis.",
     "Filsuf itu bermimpi mathesis universal yang bisa menyatukan setiap bidang pengetahuan.",
     "belajar", "tindakan belajar"),
    ("Terlalu peduli pada aturan formal atau rincian sepele.",
     "Terlalu ketat soal hal kecil — mengoreksi teknis minor yang sebenarnya tak mengubah apa pun.",
     "Terasa agak rewel berdebat \"who\" versus \"whom\" dalam pesan teks.",
     "pemandu anak, guru", "memiliki cara"),
    ("Cahaya yang berkilat, berkilau.",
     "Kilatan cahaya cepat yang berkilat — pikirkan matahari memantul di air, atau berlian menangkap cahaya.",
     "Kilauan lampu gantung menyebarkan cahaya ke setiap sudut ruang dansa.",
     "berkilat, berkilau", "tindakan itu"),
    ("Pemula, novis.",
     "Seseorang yang sama sekali baru pada keterampilan atau bidang — masih belajar seluk-beluk, belum ahli.",
     "Bahkan pemain catur pemula bisa melihat blunder itu.",
     "rekrut, pemula", "prajurit muda mentah"),
    ("Sangat buruk, keji.",
     "Buruk dengan cara yang pantas dibenci sungguhan — bukan sekadar \"sedang\", melainkan benar-benar keji.",
     "Pengulas menyebut sekuel itu buruk sekali, dan angka box office setuju.",
     "mengutuk", "pantas, mampu"),
    ("Berwarna merah darah.",
     "Merah dalam dan cerah — warna darah segar, terkenal lewat Macbeth Shakespeare.",
     "Matahari terbenam mengubah seluruh langit menjadi cahaya merah darah.",
     "ke dalam", "daging (merah daging)"),
    ("Celah atau ruang kecil di antara benda.",
     "Ruang kecil di antara yang mudah terlewat — retakan papan lantai, jeda dalam jadwal.",
     "Gulma mendorong naik lewat setiap celah di jalur bata tua.",
     "di antara", "berdiri"),
    ("Ucapan kritis atau mencela.",
     "Komentar tajam, tidak setuju — jenis kritik yang membawa nada memarahi.",
     "Teguran profesor pada esai itu memenuhi pinggir dengan tinta merah.",
     "pikiran", "berpaling ke"),
    ("Mustahil disangkal, tak terbantahkan.",
     "Terbukti begitu kokoh hingga tak ada yang bisa dibantah — kasusnya sudah tertutup.",
     "Bukti DNA itu tak terbantahkan, dan sidang berakhir dalam sejam.",
     "tidak", "menentang, menahan"),
    ("Kerumitan, kekusutan; juga pelipatan ke dalam.",
     "Kerumitan yang terlipat ke dalam dirinya — hal-hal terbungkus begitu rapat hingga sulit ditarik terpisah.",
     "Kerumitan berlipat plot itu membuat separuh penonton masih mengurai setelah kredit.",
     "ke dalam", "menggulung, memutar"),
    ("Kekuatan atau usaha, seperti dalam \"by dint of\".",
     "Usaha atau kekuatan belaka — hari ini hampir hanya hidup dalam frasa \"by dint of\".",
     "Dia lulus ujian berkat latihan keras yang keras kepala.",
     "pukulan, hantaman", "dengan kekuatan"),
    ("Disambung dengan sambungan pen-dan-lubang; dipasang rapat.",
     "Terkunci cara tukang kayu lama — satu bagian masuk pas ke lubang yang dipotong tepat untuknya.",
     "Balok lumbung tua itu disambung dengan pen tanpa satu paku pun.",
     "soket, lubang", "gigitan, cengkeraman"),
    ("Sangat relevan, tepat.",
     "Tepat pas untuk momen itu — komentar, kutipan, atau contoh yang mendarat sempurna pada poin.",
     "Ucapan tepatnya merangkum seluruh debat dalam satu kalimat.",
     "ke", "menempatkan"),
    ("Bersinar lembut atau berkedip (cahaya); juga kecerdasan ringan.",
     "Bersinar lembut alih-alih menyala — cahaya lembut berkedip, atau kecerdasan yang bermain-main alih-alih tajam.",
     "Cahaya lilin melemparkan sinar berkilau lembut di ruang makan tua.",
     "menjilat", "melakukan (cahaya yang 'menjilat')"),
    ("Pertapa religius yang hidup dalam kesendirian.",
     "Seseorang yang menarik diri sepenuhnya dari dunia untuk hidup sendiri dalam doa dan perenungan.",
     "Pertapa itu tinggal di sel kecil yang menempel pada gereja lebih dari tiga puluh tahun.",
     "ke belakang, jauh", "menarik diri"),
    ("Memuaskan dahaga; memadamkan.",
     "Memenuhi sepenuhnya suatu hasrat — paling sering dahaga, tetapi secara kiasan segala keinginan atau kebutuhan dalam.",
     "Satu gelas air dingin melepas dahaganya setelah pendakian panjang.",
     "kendur, longgar", "melonggarkan, meredakan"),
    ("Berbentuk jarum.",
     "Panjang, tipis, dan runcing seperti jarum — bentuk daun pinus atau kristal kecil yang tajam.",
     "Pohon pinus mudah dikenali dari daunnya yang seperti jarum.",
     "jarum", "kecil"),
    ("Kehabisan daya hidup, lemah, terlalu halus.",
     "Aus dan lembut — kehilangan kekuatan atau semangat aslinya karena terlalu nyaman atau halus.",
     "Para kritikus menyebut majalah yang dulu berani itu sudah kehilangan daya, bayangan tahun-tahun awalnya yang berani.",
     "keluar", "berbuah, telah beranak"),
    ("Aksesori atau hak kecil yang melekat.",
     "Tambahan kecil yang datang menempel pada yang lebih besar — aksesori dan tambahan yang milik benda utama.",
     "Sewa itu mencakup garasi dan semua kelengkapannya.",
     "ke", "milik"),
    ("Menyelubungi atau meremehkan kesalahan.",
     "Menghaluskan kesalahan dengan kata lembut, membuatnya terdengar lebih kecil daripada kenyataannya.",
     "Dia mencoba menutupi tenggat yang terlewat dengan omongan kabur tentang \"tantangan tak terduga\".",
     "glos, penjelasan", "berkomentar — lalu menghaluskan"),
    ("Pada tahap awal, baru mulai.",
     "Baru mulai menampakkan diri — tahap pertama, hampir tak terlihat, dari sesuatu yang lebih besar yang akan datang.",
     "Para dokter menangkap tanda awal penyakit sebelum sempat menyebar.",
     "pada, ke dalam", "mengambil (mengangkat, memulai)"),
    ("Ilham kreatif, terutama yang ilahi.",
     "Hembusan ilham tiba-tiba yang terasa lebih besar dari Anda — seolah gagasan ditiupkan ke dalam Anda dari tempat lain.",
     "Penyair itu menggambarkan seluruh karya datang dalam satu semburan ilham pukul 3 pagi.",
     "ke, atas", "meniup (hembusan ke atas)"),
]
