# Danish rows: (definition, friendly, exampleGloss, root1, root2)
ROWS = [
    (
        "At søde eller rense; at fjerne stridhed fra noget.",
        "At tage brodden eller bitterheden ud af noget — bogstaveligt ved at søde det, eller billedligt ved at blødgøre en hård idé, så den går ned lettere.",
        "Redaktøren edulcorated den hårde anmeldelse, inden den gik i trykken.",
        "ud, grundigt",
        "sød",
    ),
    (
        "Overdrevent eller påtaget religiøs eller from.",
        "Beskriver nogen, hvis religiøse hengivenhed føles iscenesat for syns skyld, mere opvisning end ægte tro.",
        "Hans pietistic sukken under prædikenen irriterede resten af bænken.",
        "fromhed, pligttroskab",
        "som har karakteren af",
    ),
    (
        "Tvetydighed, der opstår af den grammatiske struktur — en sætning, der kan læses på to måder.",
        "En sætning, der er grammatisk i orden, men kan læses på to helt forskellige måder, som \"I saw the man with the telescope.\"",
        "\"Visiting relatives can be tiring\" er en klassisk amphiboly — er slægtningene trættende, eller er det at besøge dem?",
        "begge, på begge sider",
        "at kaste",
    ),
    (
        "Skarp, præcis, skærende lige til sagen.",
        "Skærer lige igennem fyldet — en trenchant kommentar eller et trenchant intellekt rammer sagens kerne hurtigt, uden spildte ord.",
        "Hendes trenchant kritik lod ingen plads til filmens huller i handlingen at gemme sig.",
        "at skære",
        "gørende, som har kvaliteten af",
    ),
    (
        "Lige i begyndelsen; i et tidligt eller rudimentært stadium.",
        "Stadig i sine åbningsøjeblikke — en plan, en følelse eller en proces, der kun lige er begyndt at tage form.",
        "De inchoative stadier af traktaten var lovende, men mange detaljer stod stadig åbne.",
        "at begynde, at starte",
        "som stræber imod",
    ),
    (
        "En formel tale eller tekst, der priser nogen højt.",
        "En fuldtonende, formel hyldest — tænk en strålende mindetale eller en tale, der synger nogens bedrifter fra tagene.",
        "Den afgående professor blev sendt afsted med en panegyric fra sine nærmeste studerende.",
        "alt",
        "forsamling, sammenkomst",
    ),
    (
        "Som vedrører virkelig eksistens eller faktisk væren, i modsætning til abstrakt teori.",
        "Om ting, som de faktisk findes i virkeligheden, ikke bare som idéer eller teorier om dem.",
        "Filosoffer debatterer, om tal har nogen ontic status, eller kun findes i vores sind.",
        "væren, det som findes",
        "som vedrører",
    ),
    (
        "At bære frugt, eller at blive produktiv.",
        "Endelig at betale sig — en indsats, idé eller investering, der fructify, er vokset fra frø til noget nyttigt.",
        "Års stille forskning fructified endelig til en fungerende vaccine.",
        "frugt",
        "at gøre, at fremkalde",
    ),
    (
        "Som foregriber eller fremstiller noget som allerede gjort, før det faktisk er sket.",
        "At løbe i forvejen på en litterær måde — at beskrive en fremtidig begivenhed, som om den allerede var afsluttet, så pointen rammer hårdere.",
        "Generalens proleptical skål for \"victory\" blev udbragt en hel uge før slaget.",
        "før",
        "at tage, at gribe",
    ),
    (
        "Drevet af lufttryk; også relateret til ånd eller åndedræt.",
        "Betyder oftest \"drevet af trykluft\" — men kan også betyde noget, der vedrører ånd eller åndedræt.",
        "De pneumatic bremser peb, da bussen stoppede ved fortovskanten.",
        "vind, åndedræt, ånd",
        "som hører til",
    ),
    (
        "At beskrive Gud eller det guddommelige gennem positive udsagn — modsætningen til apofatisk.",
        "En måde at tale om Gud ved at sige, hvad Gud er — \"God is love\" — snarere end kun, hvad Gud ikke er.",
        "Cataphatic teologi taler trygt om Gud som kærlig, retfærdig og barmhjertig.",
        "ned, i henhold til",
        "at tale, at sige",
    ),
    (
        "Baseret på tillid eller tro; også brugt som et fast referencepunkt.",
        "Noget du tager på tillid og derefter bruger som anker — et fiducial mærke er det faste punkt, alt andet måles imod.",
        "Landmålere satte en fiducial markør i grundfjeldet, inden de kortlagde stedet.",
        "at stole",
        "tillid, fortrøstning",
    ),
    (
        "Et forsvar for Guds godhed i lyset af ondskabens eksistens.",
        "Det ældgamle forsøg på at svare på \"If God is good, why does evil exist?\"",
        "Hendes speciale undersøgte theodicy gennem Jobs Bog.",
        "gud",
        "retfærdighed",
    ),
    (
        "Gensidig indboen — et teologisk udtryk for, hvordan Treenighedens personer findes i hinanden.",
        "Et teologisk ord for tre-i-én-samhørighed så fuldstændig, at hver del helt rummer og rummes af de andre.",
        "Læren om circumincession forsøger at forklare, hvordan Fader, Søn og Ånd er adskilte, men uadskillelige.",
        "rundt om",
        "at gå, at vandre",
    ),
    (
        "At få en følge, der gavner eller slår tilbage på nogen.",
        "Når æren (eller skylden) hopper tilbage på den ansvarlige — gode gerninger, der redound til dit omdømme, kommer tilbage og belønner dig.",
        "Holdets succes vil redound til den stille, hårdtarbejdende træners ære.",
        "tilbage, igen",
        "bølge",
    ),
    (
        "Ude af stand til at undgås eller undslippes.",
        "Dømt til at ske, uanset hvad du gør — der er ingen vej uden om et ineluctable udfald.",
        "Alderdommen kommer til alle; den er simpelthen ineluctable.",
        "ikke",
        "at kæmpe sig ud af",
    ),
    (
        "Som bruger omstændelige, ordige formuleringer i stedet for en direkte form.",
        "At tage den lange vej med ordene — at sige \"make a decision\" i stedet for \"decide.\"",
        "Hans periphrastic e-mails kunne have sagt på én linje, hvad der tog ham tre afsnit.",
        "rundt om",
        "at forkynde, at fortælle",
    ),
    (
        "Åndelig sløvhed eller letargi.",
        "Den dér tågede, trege sindstilstand, hvor tænkning føles som at vade gennem sirup.",
        "En bølge af hebetude ramte klassen lige efter frokost.",
        "sløv, stump",
        "tilstand eller egenskab",
    ),
    (
        "Ikke gunstig; som varsler ondt.",
        "Et dårligt tegn — forhold eller timing, der synes at arbejde imod dig, før du overhovedet er begyndt.",
        "Grå himmel og et dødt bilbatteri gav en unpropitious start på roadtripen.",
        "ikke",
        "gunstig, nådig",
    ),
    (
        "Kød stuvet eller braseret i sovs — rigtigt stavet \"fricasseed.\"",
        "Et hyggeligt gammelt madlavningsudtryk for kød, der er skåret op og simret langsomt i sin egen sovs, indtil det er mørt.",
        "Bedstemors fricasseed kylling var højdepunktet ved hver søndagsmiddag.",
        "at stege",
        "at bryde (i stykker)",
    ),
    (
        "En kunstig eller ringere erstatning.",
        "En kopi, der står i for det ægte — den klarer jobbet teknisk, men alle kan se, at det ikke er den ægte vare.",
        "Krigstidens kunder nøjedes med ersatz-kaffe brygget på ristet cikorie.",
        "ud, erstatningspræfiks",
        "at sætte, at placere",
    ),
    (
        "At behandle en abstrakt idé, som om den var en konkret ting.",
        "At få en idé til at føles virkelig og solid — at vende noget uklart, som \"the economy,\" til en ting, man kan pege på.",
        "At kalde en nations \"spirit\" for et eget væsen reifies noget, der i virkeligheden bare er millioner af individuelle valg.",
        "ting",
        "at gøre",
    ),
    (
        "Undslap eller undgik dygtigt.",
        "Gled rent væk — smuttede fra noget, ofte listigt eller knebent, hvad enten det var et greb, et spørgsmål eller et svar.",
        "Svaret eluded hende i timevis, indtil det pludselig klikkede i badet.",
        "ud, væk",
        "at lege",
    ),
    (
        "Som udtrykker tvivl, forvirring eller en uløst modsigelse.",
        "Fast i en ægte tankemæssig blindgyde — ikke forvirret af dovenskab, men fordi spørgsmålet selv modsætter sig et pænt svar.",
        "Sokrates afsluttede ofte sine dialoger på en aporetic tone, med flere spørgsmål end svar.",
        "uden",
        "passage, vej",
    ),
    (
        "En stilfigur, der benævner noget med et forbundet udtryk, f.eks. \"the crown\" for monarken.",
        "At bruge et beslægtet ord i stedet for sagen selv — at sige \"the White House announced,\" når man mener administrationen.",
        "\"Wall Street had a rough day\" er metonymy — det betyder egentlig, at aktiemarkedet havde det.",
        "ændring, efter",
        "navn",
    ),
    (
        "At rykke op med rode; at rive ud af et naturligt miljø.",
        "At trække noget (eller nogen) op med rod, væk fra det sted eller den kultur, de hører til.",
        "Krig deracinated en hel generation og spredte familier over grænserne.",
        "væk, af",
        "rod",
    ),
    (
        "Velllydende.",
        "Simpelthen rart at høre — et euphonious ord, navn eller en sætning ruller blødt hen over øret, næsten musikalsk.",
        "\"Murmuring brook\" er en euphonious lille frase, blød og nem at sige.",
        "god, vel",
        "lyd, stemme",
    ),
    (
        "Almindeligt antaget eller formodet at være.",
        "Udbredt troet at være sand, selv om det ikke egentlig er bevist — den \"supposed\" udgave af noget.",
        "Den putative forfatter til brevet viste sig senere at være en total fremmed.",
        "at tænke, at anse",
        "som har naturen af",
    ),
    (
        "Et nydannet ord eller udtryk.",
        "Et spritnyt ord — netop opfundet, endnu ikke (eller knap) i ordbogen.",
        "\"Doomscrolling\" begyndte som en neologism og blev hurtigt hverdagsslang.",
        "ny",
        "ord, tale",
    ),
    (
        "Vred eller gnaven.",
        "I et surt, irritabelt humør — hurtig til at brække af, som man engang troede milten styrede temperamentet.",
        "Han affyrede et splenetic svar på e-mailen inden for sekunder efter at have læst den.",
        "milt (vredens sæde)",
        "påvirket af",
    ),
    (
        "Tilbøjelig til at moralisere på en pompøs eller påtaget måde.",
        "Elsker at uddele små livslektioner på en selvoptaget måde, som om hver sætning var en lykkekage.",
        "Hans sententious skål om \"the true meaning of friendship\" fik alle til at tjekke uret.",
        "mening, sentens",
        "fuld af",
    ),
    (
        "Overdrevent snakkesalig, især om trivielle ting.",
        "Holder bare ikke op med at sludre — vrøvler om småting længe efter, at alle andre er løbet tør for emner.",
        "Den garrulous taxachauffør fortalte os hele sin livshistorie, før vi havde forladt lufthavnen.",
        "at sludre, at plapre",
        "tilbøjelig til",
    ),
    (
        "Dårskab, fjolleri.",
        "Ren dårskab — en kommentar eller plan så fjollet, at den knap fortjener et seriøst svar.",
        "Planens rene fatuity blev indlysende i det øjeblik, de prøvede den.",
        "dårlig, fjollet",
        "tilstand at være",
    ),
    (
        "Den afsluttende del af en tale, ofte sammenfattende.",
        "Talens store finale — det sidste afsnit, hvor taleren samler det hele og slår pointen fast.",
        "Ved peroration stod halve publikum på benene.",
        "igennem, til enden",
        "at tale, at plædere",
    ),
    (
        "Unødig gentagelse af den samme idé med andre ord.",
        "At sige det samme to gange uden at tilføje noget nyt, som \"free gift\" eller \"end result.\"",
        "\"It is what it is\" er en yndlings-tautology blandt folk, der undgår en rigtig forklaring.",
        "den samme",
        "ord, tale",
    ),
    (
        "Brugen af meget få ord; knap tale.",
        "At sige meget med meget lidt — kunsten af det korte, ligefremme svar, opkaldt efter de berygtet fåmælte spartanere fra Lakonien.",
        "\"Molon labe\" — \"come and take them\" — er historiens mest berømte stykke laconism.",
        "en spartaner fra Lakonien",
        "skik, måde",
    ),
    (
        "Tamme, overforenklede idéer; oprindeligt tam mad eller velling.",
        "Tynd, udvandet tænkning — indhold så forenklet og sikkert, at det ikke har nogen næring for sindet.",
        "Politikerens tale var mest pabulum: vage løfter uden noget at hænge fast i.",
        "at føde",
        "middel eller redskab",
    ),
    (
        "Som fremkalder søvn eller døsighed.",
        "Så kedeligt — eller så bogstaveligt sovende — at det gør én søvnig. Tænk varm mælk, eller et tre timer langt budgetmøde.",
        "Forelæsningens soporific brum fik halve rummet til at kæmpe for at holde øjnene åbne.",
        "dyb søvn",
        "gørende, fremkaldende",
    ),
    (
        "Overdrevent smigrende eller olieret i sin facon.",
        "Så glat charmerende, at det føles glat — smiger lagt så tykt på, at man næsten kan mærke fedtet.",
        "Den unctuous sælger blev ved med at rose min \"excellent taste\" før hvert mersalg.",
        "at salve, at olier",
        "fuld af",
    ),
    (
        "Hurtig til at finde fejl, overdrevent kritisk over for trivielle ting.",
        "Pirket til et fejl — typen, der finder et problem ved alting, også når det ikke rigtig betyder noget.",
        "Hans captious noter til rapporten handlede udelukkende om kommaer.",
        "at gribe, at tage",
        "en fælde, et sofisme",
    ),
    (
        "Træg, mentalt eller fysisk inaktiv.",
        "Langsom og halvsovende, som en bjørn i hi — knap i bevægelse, knap i tanke.",
        "Kontoret faldt torpid i augustvarmen.",
        "at være følelsesløs, at være træg",
        "i en tilstand af",
    ),
    (
        "En forvalter eller embedsmand, der styrede en middelalderlig husholdning.",
        "Middelalderens udgave af en stabschef — den betroede embedsmand, der drev en herres hus og gods fra dag til dag.",
        "Borgens seneschal styrede alt fra høstregnskaber til gæstelisten.",
        "gammel, senior",
        "tjener",
    ),
    (
        "At tale eller skrive udførligt om et emne.",
        "Virkelig at komme i gang om et emne — tale eller skrive løs og dække det fra alle vinkler.",
        "Spørg ham om veteranbiler, og han vil expatiate i en time i træk.",
        "ud",
        "rum",
    ),
    (
        "Uden værdi, ubetydelig; også ugyldig eller virkningsløs.",
        "Værd stort set ingenting — en nugatory klausul i en kontrakt er en, der ikke egentlig gør noget.",
        "Retten dømte den gamle vedtægt nugatory, da den aldrig faktisk var blevet håndhævet.",
        "bagateller, sludder",
        "tilhørende",
    ),
    (
        "Visdom, skarpsindig dømmekraft.",
        "Skarp, praktisk visdom — den slags gode dømmekraft, der kommer af erfaring, ikke bare boglige kundskaber.",
        "Den gamle kaptajns sagacity holdt mandskabet ude af problemer mere end én gang.",
        "skarptlugtende, skarpsindig",
        "egenskab af",
    ),
    (
        "Pøbelen eller masserne, brugt foragteligt.",
        "Et snobbet, afvisende ord for \"the rabble\" eller jævne folk, brugt med foragt.",
        "Greven hånede canaille, der samlede sig uden for paladsets porte.",
        "hund",
        "kollektiv, flok",
    ),
    (
        "Fræk, ydmygende behandling eller sprog.",
        "Grusom, hånlig behandling ment til at ydmyge — den slags fornærmelse, der er designet til at svi.",
        "Han udholdt år af contumely fra kritikere, før hans værk endelig blev anerkendt.",
        "med, grundigt",
        "at svulme (af stolthed)",
    ),
    (
        "Med mistanke eller misbilligelse; et sideblik.",
        "Det dér sideblik, du giver noget, du ikke helt stoler på — et blik ladet med tvivl.",
        "Læreren så askance på den mistænkeligt pæne lektie.",
        "ad, til",
        "skæv, bias",
    ),
    (
        "En dum person; et træhoved.",
        "En gammeldags, næsten kærlig fornærmelse for nogen, der er sløv eller tykhovedet — et træhoved.",
        "\"You clodpate,\" lo hun, \"you've had the map upside down the whole time.\"",
        "jordklump",
        "hoved",
    ),
    (
        "At sætte i bevægelse eller handling; at motivere.",
        "At være gnisten, der sætter noget i gang — hvad enten det er en maskine, der tændes, eller et menneske, der endelig handler på en idé.",
        "Frygten for at miste kontrakten actuated hele holdet til en weekend med overarbejde.",
        "et gøren, et drive",
        "at drive, at gøre",
    ),
    (
        "Underslæb af midler betroet ens varetægt.",
        "Stille at stjæle penge, man var betroet at passe — underslæb i en gammeldags frakke.",
        "Kassererens peculation gik ubemærket hen i næsten et årti.",
        "privat ejendom",
        "kvæg, rigdom",
    ),
    (
        "En gruppe, der anses for at stå i udkanten af det respektable selskab.",
        "Den glamourøse, men skumle sociale underverden — folk, der lever lige uden for reglerne for \"respectable\" selskab.",
        "Romanen følger en sangerinde, der navigerer 1920'ernes kabareters demi-monde.",
        "halv",
        "verden, selskab",
    ),
    (
        "Stadig eksisterende; ikke uddød eller ødelagt.",
        "Stadig her i dag — bruges om gamle ting (manuskripter, arter, bygninger), der har formået at overleve.",
        "Kun tre extant eksemplarer af det første tryk vides at findes.",
        "ud",
        "at stå",
    ),
    (
        "Svigagtighed; svigt af tillid.",
        "Dybt, bevidst svigt — at bryde en tillid, som nogen havde ret til at forvente, at du ville holde.",
        "Generalen tilgav aldrig sin gamle vens perfidy ved forhandlingsbordet.",
        "igennem, imod",
        "tro, tillid",
    ),
    (
        "En regional dialekt, især en ikke-standardsproglig.",
        "Den særlige, lokale måde, folk taler på i en bestemt egn — fuld af ord og rytmer, en udenforstående måske ikke fanger.",
        "Hendes bedstemor talte stadig øens patois ved familiemiddage.",
        "grov tale, dialekt",
        "pote — klodset tale",
    ),
    (
        "En særlig ret, der tilhører en person eller gruppe.",
        "Et privilegium, der er dit og kun dit — en ret, der følger med din rolle, stilling eller status.",
        "At vælge familiens feriemål er farfars prerogative, og det ved alle.",
        "før",
        "at spørge, at stemme",
    ),
    (
        "Dristighed, uforskammethed; også hårdhed eller udholdenhed.",
        "Rå, modig modstandskraft — nerverne til at gå videre og sejheden til at blive ved, når du først gør det.",
        "Det krævede virkelig hardihood at krydse passet i snestorm uden kort.",
        "dristig, hærdet",
        "tilstand, stand",
    ),
    (
        "At springe ud i blomst; også at udvikle sig eller gradvist vise sig.",
        "At folde sig ud i fuldt udtryk — som en blomst, der åbner sig, eller en idé, der endelig kommer til sin ret.",
        "Hendes stille malertalent effloresced, da hun fik sit eget atelier.",
        "ud",
        "at begynde at blomstre",
    ),
    (
        "En vægt på en snor brugt til at afgøre lodrethed; billedligt, en målestok for dømmekraft.",
        "En vægt på en snor, der hænger helt lodret, brugt til at tjekke, om noget er sandt lodret — og i videre forstand enhver fast målestok, du måler alt andet imod.",
        "Han brugte sin egen farfars ærlighed som en slags plumb-line for hver beslutning.",
        "bly",
        "snor, mål",
    ),
    (
        "Gerne, villigt (gammeldags).",
        "En gammeldags måde at sige \"gladly\" eller \"with pleasure.\"",
        "\"I would fain rest here a while,\" sukkede rejsende.",
        "glad, lykkelig",
        "gerne, villigt",
    ),
    (
        "Hård offentlig kritik eller vanære.",
        "Offentlig skam, der hældes ud over nogen på en stor, synlig måde — vanæren, der kommer af udbredt misbilligelse.",
        "Skandalen bragte offentlig opprobrium ned over hele firmaet.",
        "imod",
        "vanære, bebrejdelse",
    ),
    (
        "Skarpt sarkastisk, bidende i vid eller kritik.",
        "Vid med rigtige tænder — en mordant kommentar svider lidt, netop fordi den er så træfsikkert rettet.",
        "Hendes mordant filmanmeldelser blev frygtet af instruktører og elsket af læsere.",
        "at bide",
        "bidende, gørende",
    ),
    (
        "En formel proklamation, ofte politisk eller militær.",
        "En stor, officiel meddelelse — oftest en, der udråber en ny regering, et oprør eller et stort dekret.",
        "Generalens pronunciamento bekendtgjorde den nye regering ved daggry.",
        "frem",
        "at bekendtgøre",
    ),
    (
        "En person med overfladisk viden, der lader som om at være ekspert.",
        "Nogen, der har skummet overfladen af et emne og derefter taler, som om de skrev lærebogen om det.",
        "Middagselskabets sciolist rettede selvsikkert den faktiske astrofysiker ved bordet.",
        "at vide",
        "diminutiv — en lille vider",
    ),
    (
        "Aftagen af de mentale evner i alderdommen.",
        "Den tågede, glemsomme strækning af høj alder, hvor sindets skarphed begynder at falme.",
        "I sin dotage fortalte han de samme tre historier ved hvert besøg, hver gang som om de var nye.",
        "at dote, at være tåbelig",
        "tilstand eller resultat",
    ),
    (
        "Siden, der er læ for vinden.",
        "Den rolige, læ side af noget — en bakke, et skib, en mur — hvor vinden ikke rigtig kan nå dig.",
        "Vandrerne slog teltet op på rygens lee-side for at undslippe kastevindene.",
        "læ, beskyttelse",
        "flanke, side",
    ),
    (
        "At afværge eller slå et slag, et spørgsmål eller et argument til side.",
        "Glat at slå noget væk — et sværdhug, et akavet spørgsmål eller en anklage — uden at tabe rytmen.",
        "Hun parried reporterens lumsk spørgsmål med en let vittighed.",
        "at afværge",
        "at berede, at forsvare",
    ),
    (
        "Ildelugtende, skadelig.",
        "Stinkende på en måde, der føles næsten giftig — en stank så slem, at det synes farligt at ånde.",
        "En mephitic lugt drev op fra sumpen, da solen gik ned.",
        "skadelig damp",
        "som har naturen af",
    ),
    (
        "En person hengiven til luksus og nydelse.",
        "Nogen, der lever for komfort og nydelse — fin mad, bløde senge, et let liv — opkaldt efter den antikke græske by Sybaris, berømt for sit overskud.",
        "En sand sybarite, han nægtede ethvert hotelværelse uden badekar.",
        "antikt græsk by berømt for luksus",
        "indbygger i",
    ),
    (
        "Bevidst at lægge en del af noget til side eller ignorere den.",
        "Mentalt at lægge en brik af puslespillet til side med vilje, så du kan fokusere rent på resten.",
        "Lad os prescind fra prisen et øjeblik og bare spørge, om planen faktisk virker.",
        "før, væk",
        "at skære",
    ),
    (
        "At kritisere hårdt; også at flå huden af.",
        "At rive nogen i stykker med hård kritik — verbalt, som om du bogstaveligt flåede huden af.",
        "Kritikerne excoriated opfølgeren for at forråde alt, hvad fans elskede ved originalen.",
        "af",
        "skind, hud",
    ),
    (
        "At anføre som bevis eller belæg.",
        "At føre et faktum eller eksempel frem til støtte for din pointe — det, du peger på, når nogen spørger \"what's your evidence?\"",
        "Advokaten adduced tre vidner til støtte for klientens alibi.",
        "til, imod",
        "at føre",
    ),
    (
        "Rejser eller vandringer, især lange eller omfattende.",
        "Lange, omflakkende færder — den slags omfattende vandring, der tager dig langt hjemmefra i lang tid.",
        "Hans peregrinations over tre kontinenter fyldte en hel hylde med rejsedagbøger.",
        "igennem",
        "mark, land (peregrinus: fremmed)",
    ),
    (
        "En tigger, eller en der lever af almisser.",
        "Nogen, der lever af at bede om velgørenhed — historisk beskrev dette også munke, der aflagde fattigdomsløfter og levede af gaver.",
        "De mendicant brødre ejede intet og stolede helt på landsbyboernes godhed.",
        "at tigge",
        "tigger",
    ),
    (
        "Yderst gavmild.",
        "Gavmild i en stor, næsten prangende skala — den slags gave, der får folk til at gispe lidt.",
        "Den munificent donation finansierede hele bibliotekets nye fløj.",
        "gave, tjeneste",
        "gørende, givende",
    ),
    (
        "Udmattelse af mangel på næring; også mangel på livskraft.",
        "En svag, tømt tilstand af ikke at være blevet mættet eller drevet — bogstaveligt af sult, eller billedligt af ikke at have noget tilbage at køre på.",
        "Ved belejringens slutning var soldaterne nær inanition.",
        "tom, vakuum",
        "handlingen eller resultatet af",
    ),
    (
        "Bitter, skældende kritik.",
        "Kritik, der er gået langt forbi det rimelige og blevet til et vredt, bittert udbrud.",
        "Netkommentarerne opløstes i ren vituperation inden for minutter.",
        "fejl",
        "at berede, at forsyne",
    ),
    (
        "Fjendtlig, skadelig i virkning.",
        "Arbejder imod dig, også stille — forhold eller holdninger, der er uvenlige over for dine interesser.",
        "Den nye politik var inimical over for små virksomheder, selv om det ikke var hensigten.",
        "ikke",
        "ven",
    ),
    (
        "Tilbøjelig til at vække nag eller misfornøjelse, ofte gennem uretfærdige sammenligninger.",
        "Dømt til at få nogen til at føle sig tilsidesat — oftest fordi det stiller folk eller ting op imod hinanden på en uretfærdig måde.",
        "At rangere søskende efter \"who Mom loves best\" er et invidious spil, ingen burde lege.",
        "misundelse",
        "at se på (med ond vilje)",
    ),
    (
        "En person af lavere rang eller status; en underordnet.",
        "Nogen længere nede i kommandokæden eller den sociale stige — en junior, der arbejder under nogen med mere magt.",
        "Som ung subaltern tog han ordrer længe, før han nogensinde gav dem.",
        "under",
        "skiftevis, anden",
    ),
    (
        "At føle eller udtrykke stærkt had til.",
        "At afsky noget så meget, at du forbander det højt — ren, højlydt afsky.",
        "Landsbyboerne execrated skatteopkræveren, hver gang hans vogn rullede gennem byen.",
        "ud af",
        "hellig (at forbande ud af det hellige)",
    ),
    (
        "Et naturligt ydre dække, som hud eller et skjold.",
        "Naturens eget beskyttende omslag — hud, skjold, bælg eller skal, hvad der nu dækker og værner noget levende.",
        "En skildpaddes skjold er et bemærkelsesværdigt sejt integument.",
        "på, over",
        "at dække",
    ),
    (
        "Uskyldig, naiv, med barnlig enkelhed; modsætningen til \"disingenuous.\"",
        "Åbent tillidsfuld og lidt naiv, uden skjult dagsorden — nem at forveksle med \"ingenious,\" som betyder klog.",
        "Hendes ingenuous spørgsmål — \"why would anyone lie about that?\" — viste, hvor lidt list hun havde.",
        "i, indfødt",
        "at avle (frifødt, oprigtig)",
    ),
    (
        "Overdreven omhu med små detaljer eller regler.",
        "At fare vild i de små regler og misser det større billede — at hænge i det med småt, som ingen andre gider.",
        "Hans pedantry om Oxford-kommaer afsporede hele mødet.",
        "børns lærer",
        "praksis eller egenskab",
    ),
    (
        "En grundig, omhyggelig undersøgelse.",
        "Et dybt, ingen-sten-urørt blik på noget — at gå hver detalje igennem med ægte omhu.",
        "Først efter en omhyggelig perscrutation af bøgerne dukkede afvigelsen op.",
        "igennem, grundigt",
        "at søge, at undersøge",
    ),
    (
        "At rejse indvendinger; at vise modvilje.",
        "Høfligt at bakke eller tøve i stedet for at hoppe med det samme — et blødt \"I'd rather not.\"",
        "Da hun blev bedt om at underskrive uden at læse, demurred hun.",
        "fra, væk",
        "at tøve",
    ),
    (
        "Overfladisk plausibel, men i virkeligheden forkert.",
        "Lyder overbevisende ved første øjekast, men falder fra hinanden, så snart du faktisk tjekker det.",
        "\"Everyone's doing it\" er et specious argument, der aldrig rigtig holder ved nærmere eftersyn.",
        "udseende, opsyn",
        "fuld af (tilsyneladende skøn)",
    ),
    (
        "Uærlig, hyklerisk tale, ofte moraliserende.",
        "Prædikende tale, der lyder dydig, men ikke bakkes af nogen ægte følelse — moralsk poseren på autopilot.",
        "Han var træt af det korporative cant om \"family\" fra et firma, der aldrig gav nogen fri.",
        "at synge (senere: syngende jargon)",
        "tiggeres klynkende tale, derefter hykleri",
    ),
    (
        "Som mangler mod, fej.",
        "Frygtsom til ryggradsløshed — for bange til at stå fast, selv når det klart betyder noget.",
        "Bestyrelsens pusillanimous tavshed lod skandalen spire ud af kontrol.",
        "meget lille",
        "ånd, mod",
    ),
    (
        "Ræveagtig; snu, listig.",
        "Snu og klog som en ræv — kviktænkende, lidt lumsk, altid et skridt foran.",
        "Han smilede et vulpine smil i det øjeblik, han opdagede smuthullet.",
        "ræv",
        "af eller lig",
    ),
    (
        "En efter en, i rækkefølge.",
        "Taget strengt én ad gangen, i orden — intet spring frem, ingen to på én gang.",
        "Dommeren behandlede hvert af de tolv krav seriatim.",
        "række, følge",
        "én ad gangen",
    ),
    (
        "Ekstrem sparsommelighed; nærighed.",
        "At være karrig med penge (eller ord, eller ressourcer) langt forbi rimelig sparsommelighed.",
        "Hans parsimony var legendarisk — han genbrugte tebreve tre gange.",
        "at spare, at være sparsommelig",
        "tilstand eller praksis",
    ),
    (
        "En rettelse, især i en tekst.",
        "En rettelse i et stykke skrift — en lærd justering, der retter en fejl i en gammel eller vigtig tekst.",
        "Den nye udgave rummer dusinvis af emendations af originalmanuskriptet.",
        "ud af",
        "fejl, misforståelse",
    ),
    (
        "Mådeholden i spisning og drikning.",
        "Bevidst tilbageholdende omkring mad og drikke — aldrig overdrevet, altid efterladt lidt på tallerkenen.",
        "Hans abstemious vaner holdt ham skarp længe efter, at hans jævnaldrende var sløvet.",
        "væk fra",
        "berusende drik",
    ),
    (
        "En grammatisk fejl eller et brud på etikette.",
        "Et glip i grammatik eller manerer — den slags lille fejl, der får en pedant til at ryste på hovedet.",
        "\"Between you and I\" er en almindelig solecism, der stadig får grammatikere til at rykke.",
        "kilikisk by kendt for 'dårlig' græsk",
        "skik, måde",
    ),
    (
        "Som vedrører konflikt inden for en gruppe; gensidigt ødelæggende.",
        "Indre strid, der river en gruppe fra hinanden indefra — en kamp, hvor alle taber, fordi det er familie mod familie.",
        "Partiets internecine kævl gjorde mere skade, end nogen ydre modstander kunne.",
        "mellem, blandt",
        "at dræbe",
    ),
    (
        "Ligegyldig, skødesløs holdning.",
        "Et skuldertræk gjort til en hel personlighed — at bekymre sig så lidt om ting, der plejede at betyde noget, at intet længere synes umagen værd.",
        "Hans pococurante holdning til prisceremonien overraskede alle, der vidste, hvor hårdt han havde arbejdet.",
        "lidt",
        "at bekymre sig",
    ),
    (
        "En forvirret, kompliceret situation eller tvist.",
        "En indviklet, rodet situation, der er svær at få styr på — delvist misforståelse, delvist drama, helt forvirring.",
        "Hele siddeplads-imbroglio startede med ét forkert placeret navnekort.",
        "i",
        "at filtre, at forvirre",
    ),
    (
        "Truende, truende.",
        "Bærende en umiskendelig luft af trussel — et minatory blik eller brev gør det meget klart, at noget ondt kan følge.",
        "Brevets minatory tone gjorde lejeren nervøs, før hun overhovedet havde åbnet kuverten.",
        "at true",
        "tjenende til",
    ),
    (
        "Stærk offentlig kritik eller verbal skældsord.",
        "Højlydt, offentlig fordømmelse — den slags svidende kritik, der udspiller sig for øjnene af alle.",
        "Whistlebloweren mødte år af offentlig obloquy, før historien gav hende ret.",
        "imod",
        "at tale",
    ),
    (
        "Et pludseligt voldsomt udbrud, af følelse eller handling.",
        "Et pludseligt, intenst stød, der overvælder dig på én gang — et latteranfald, raseri eller hoste, der rammer som en bølge.",
        "Hun blev grebet af et paroxysm af latter, hun ikke kunne forklare for nogen anden i rummet.",
        "hinsides",
        "skarp, akut",
    ),
    (
        "Tilføjet fra en ydre kilde, ikke iboende.",
        "Skruet på udefra i stedet for indbygget fra starten — et ekstra, ikke en kernedel.",
        "Kommentaren føles adscititious, som om den var klistret på en allerede færdig tekst.",
        "til, desuden",
        "at godkende, at antage",
    ),
    (
        "Mangel på viden, uvidenhed.",
        "Simpelt ikke-vide — et hul i viden, uden nogen vurdering knyttet til det.",
        "Han indrømmede sin nescience om fransk vin og lod sommelieren vælge.",
        "ikke",
        "at vide",
    ),
    (
        "Overdreven interesse for seksuelle anliggender.",
        "En overivrig, gloende nysgerrighed efter alt pikant — interesse, der er gået forbi det sunde og blevet nærgående.",
        "Tabloidens prurience omkring parrets privatliv grænsede til det tvangsprægede.",
        "at klø, at længes efter",
        "tilstand af",
    ),
    (
        "Sodet, mørk, diset.",
        "Mørk og røget at se til, som om alting er belagt med et tyndt lag sod.",
        "En fuliginous dis hang over fabriksbyen i skumringen.",
        "sod",
        "fuld af",
    ),
    (
        "At nægte eller modsige.",
        "Fladt at tale imod noget, en anden har sagt — at sige \"that's not so.\"",
        "Ingen vovede at gainsay den gamle kaptajns beretning om stormen.",
        "imod",
        "at tale",
    ),
    (
        "Dovenskab, sløvhed (fra latin).",
        "Et gammelt latinsk ord for ren dovenskab — slæbet i slet ikke at ville gøre noget.",
        "Munkene prædikede imod ignavia som en af sjælens stille farer.",
        "ikke",
        "optaget, flittig",
    ),
    (
        "Et skjold, der viser et våben.",
        "Det skjoldformede emblem, der viser en families våben — dens heraldiske \"nameplate.\"",
        "Familiens escutcheon hænger stadig over den gamle herregårds hoveddør.",
        "skjold",
        "diminutiv / genstand",
    ),
    (
        "Forældet, obsolet, eller pensioneret på grund af alder.",
        "Forbi sin nyttige top og sat på græs — for gammeldags eller slidt til at blive ved med jobbet.",
        "Den superannuated printer blev endelig skiftet ud efter femten års papirstop.",
        "hinsides",
        "år",
    ),
    (
        "Erstatninger, især inden for medicin.",
        "Erstatningsmidler brugt, når den rigtige behandling ikke er tilgængelig — medicinske understudies, i bund og grund.",
        "Krigstidens læger stolede ofte på succedanea, når de rigtige mediciner slap op.",
        "i stedet for",
        "at gå, at vige",
    ),
    (
        "Pralende, blærende tale.",
        "Stort, blæsende pral — højlydt tale om din egen storhed, der mest er tom luft.",
        "Hans rodomontade om at have \"single-handedly\" reddet projektet narrede ingen, der faktisk havde været der.",
        "pralende ridder i Orlando Furioso",
        "handling, opvisning",
    ),
    (
        "At bruge kneb eller svig for at opnå noget.",
        "At sno sig til et mål gennem lumsk kneb snarere end fair play.",
        "Han chicaned sig ind i handlen med en kontrakt fuld af med småt.",
        "at kævle, at snyde",
        "kneb; senere et skarpt sving",
    ),
    (
        "Den rene eller abstrakte videnskab om læring eller viden, ofte matematik.",
        "Læring i sin reneste, mest abstrakte form — selve videns dybe struktur, især den matematiske slags.",
        "Filosoffen drømte om en universel mathesis, der kunne forene hvert vidensfelt.",
        "at lære",
        "handlingen at lære",
    ),
    (
        "Overdrevent optaget af formelle regler eller trivielle detaljer.",
        "Overdrevent streng med småtingene — retter små teknikaliteter, der ikke rigtig ændrer noget.",
        "Det føltes lidt pedantic at skændes om \"who\" versus \"whom\" i en sms.",
        "børneleder, vejleder",
        "som har måden af",
    ),
    (
        "Et blinkende, gnistrende lys.",
        "Et hurtigt, glitrende lysglimt — tænk sollys, der hopper på vand, eller en diamant, der fanger lyset.",
        "Kronelysets coruscation strøede lys over hvert hjørne af balsalen.",
        "at glitre, at blinke",
        "handlingen af",
    ),
    (
        "En begynder, novice.",
        "Nogen spritny i en færdighed eller et felt — stadig i gang med at lære grundene, endnu ikke ekspert.",
        "Selv en tyro skakspiller kan se den bommert.",
        "rekrut, novice",
        "en rå ung soldat",
    ),
    (
        "Yderst dårlig, afskyelig.",
        "Dårlig på en måde, der fortjener ægte afsky — ikke bare \"mediocre,\" men virkelig afskyelig.",
        "Anmelderen kaldte opfølgeren execrable, og biograftallene var enige.",
        "at forbande",
        "værdig, i stand til at blive",
    ),
    (
        "Blodrød i farven.",
        "En dyb, levende rød — farven af frisk blod, berømt brugt af Shakespeares Macbeth.",
        "Solnedgangen vendte hele himlen til en incarnadine glød.",
        "ind i",
        "kød (kød-rød)",
    ),
    (
        "Et lille mellemrum eller en spalte mellem ting.",
        "Det lille mellemrum, der er nemt at overse — revnen mellem gulvbrædderne, hullet i en kalender.",
        "Ukrudt skød op gennem hver interstice i den gamle teglsti.",
        "mellem",
        "at stå",
    ),
    (
        "Kritiske eller dadlende bemærkninger.",
        "Spidse, misbilligende kommentarer — den slags kritik, der bærer en smule skældende tone.",
        "Professorens animadversions på essayet fyldte margenerne med rød blæk.",
        "sind",
        "at vende imod",
    ),
    (
        "Umulig at gendrive, uomtvistelig.",
        "Så solidt bevist, at der ikke er noget at argumentere imod — sagen er simpelthen lukket.",
        "DNA-beviset var irrefragable, og retssagen var ovre inden for timen.",
        "ikke",
        "at modsætte sig, at stå imod",
    ),
    (
        "Kompleksitet, indviklethed; også en indrulning.",
        "En indviklet, foldet-ind-i-sig-selv slags kompleksitet — ting viklet så tæt, at de er svære at trække fra hinanden.",
        "Handlingens involution lod halve publikum prøve at rede den ud efter rulleteksterne.",
        "ind, indad",
        "at rulle, at vende",
    ),
    (
        "Kraft eller møje, som i \"by dint of.\"",
        "Ren møje eller kraft — overlever mest i dag i frasen \"by dint of.\"",
        "Han bestod eksamen by dint of ren, stædig øvelse.",
        "et slag, et stød",
        "ved kraft af",
    ),
    (
        "Sammenføjet med tap; sikkert indpasset.",
        "Låst sammen på den gammeldags tømrermåde — et stykke, der glider tæt ind i et hul skåret lige til det.",
        "Den gamle lades bjælker var mortised sammen uden en eneste søm.",
        "et udsnit, et hul",
        "et bid, et greb",
    ),
    (
        "Højt relevant, rammende.",
        "Præcis det rigtige til øjeblikket — en kommentar, et citat eller et eksempel, der lander helt på kornet.",
        "Hendes apposite bemærkning samlede hele debatten i én sætning.",
        "til",
        "at placere",
    ),
    (
        "Blødt glødende eller flakkende (lys); også let vid.",
        "Glødende mildt snarere end flammende — et blødt, flakkende lys, eller et vid, der er legende snarere end skarpt.",
        "Stearinlys kastede en lambent glød over det gamle spiseværelse.",
        "at slikke",
        "gørende (lys der 'slikker')",
    ),
    (
        "En religiøs eneboer, der lever i ensomhed.",
        "Nogen, der trækker sig helt fra verden for at leve alene i bøn og eftertanke.",
        "Anchorite boede i en lille celle knyttet til kirken i over tredive år.",
        "tilbage, væk",
        "at trække sig tilbage",
    ),
    (
        "At stille tørst; at slukke.",
        "Helt at stille et begær — oftest tørst, men billedligt ethvert dybt behov.",
        "Et koldt glas vand slaked hans tørst efter den lange vandretur.",
        "slak, løs",
        "at slappe, at stille",
    ),
    (
        "Nålformet.",
        "Lang, tynd og spids som en nål — formen af en fyrnål eller en skarp lille krystal.",
        "Fyrretræer er nemme at kende på deres acicular blade.",
        "nål",
        "lille",
    ),
    (
        "Udtømt for livskraft, svag, overforfinet.",
        "Slidt og blød — har mistet sin oprindelige styrke eller spændstighed gennem for megen komfort eller forfinelse.",
        "Kritikere kaldte det engang så dristige magasin effete, en skygge af sine tidlige dristige år.",
        "ud",
        "frugtbar, som har båret",
    ),
    (
        "Et tilbehør eller et mindre vedhængende emne eller ret.",
        "Et lille ekstra, der følger med noget større — tilbehøret og vedhængene, der hører til hovedsagen.",
        "Lejemålet omfattede garagen og alle dens appurtenances.",
        "til",
        "at tilhøre",
    ),
    (
        "At dække over eller formindske en fejl.",
        "At sløre en fejl med bløde ord, så den lyder mindre, end den virkelig er.",
        "Han prøvede at gloze over den missede deadline med vagt snak om \"unforeseen challenges.\"",
        "en glose, en forklaring",
        "at kommentere — derefter at sløre",
    ),
    (
        "I et tidligt stadium, lige i begyndelsen.",
        "Lige ved at vise sig — det allerførste, knap synlige stadium af noget større, der kommer.",
        "Lægerne fangede de incipient tegn på sygdommen, før den kunne sprede sig.",
        "på, ind i",
        "at tage (at tage op, at begynde)",
    ),
    (
        "Kreativ inspiration, især guddommelig.",
        "Et pludseligt sus af inspiration, der føles større end dig — som om idéen blev åndet ind i dig et andet sted fra.",
        "Digteren beskrev, at hele stykket kom i ét stød af afflatus klokken tre om natten.",
        "til, på",
        "at blæse (et åndedræt-på)",
    ),
]
