#!/usr/bin/env python3
"""Emit assets/l10n/words_<locale>.json for East/SE Asian, Turkic, and Caucasian locales."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EN = json.loads((ROOT / "tool" / "_en_words_src.json").read_text(encoding="utf-8"))
OUT = ROOT / "assets" / "l10n"

POS = {
    "ja": {
        "verb": "動詞",
        "adjective": "形容詞",
        "noun": "名詞",
        "adverb": "副詞",
        "adjective / verb": "形容詞 / 動詞",
        "verb (past tense)": "動詞（過去形）",
        "adjective / noun": "形容詞 / 名詞",
    },
    "ko": {
        "verb": "동사",
        "adjective": "형용사",
        "noun": "명사",
        "adverb": "부사",
        "adjective / verb": "형용사 / 동사",
        "verb (past tense)": "동사(과거형)",
        "adjective / noun": "형용사 / 명사",
    },
    "zh_TW": {
        "verb": "動詞",
        "adjective": "形容詞",
        "noun": "名詞",
        "adverb": "副詞",
        "adjective / verb": "形容詞／動詞",
        "verb (past tense)": "動詞（過去式）",
        "adjective / noun": "形容詞／名詞",
    },
    "zh_HK": {
        "verb": "動詞",
        "adjective": "形容詞",
        "noun": "名詞",
        "adverb": "副詞",
        "adjective / verb": "形容詞／動詞",
        "verb (past tense)": "動詞（過去式）",
        "adjective / noun": "形容詞／名詞",
    },
    "vi": {
        "verb": "động từ",
        "adjective": "tính từ",
        "noun": "danh từ",
        "adverb": "phó từ",
        "adjective / verb": "tính từ / động từ",
        "verb (past tense)": "động từ (quá khứ)",
        "adjective / noun": "tính từ / danh từ",
    },
    "id": {
        "verb": "verba",
        "adjective": "adjektiva",
        "noun": "nomina",
        "adverb": "adverbia",
        "adjective / verb": "adjektiva / verba",
        "verb (past tense)": "verba (kala lampau)",
        "adjective / noun": "adjektiva / nomina",
    },
    "ms": {
        "verb": "kata kerja",
        "adjective": "kata adjektif",
        "noun": "kata nama",
        "adverb": "kata keterangan",
        "adjective / verb": "kata adjektif / kata kerja",
        "verb (past tense)": "kata kerja (kala lampau)",
        "adjective / noun": "kata adjektif / kata nama",
    },
    "fil": {
        "verb": "pandiwa",
        "adjective": "pang-uri",
        "noun": "pangngalan",
        "adverb": "pang-abay",
        "adjective / verb": "pang-uri / pandiwa",
        "verb (past tense)": "pandiwa (pangnagdaan)",
        "adjective / noun": "pang-uri / pangngalan",
    },
    "tr": {
        "verb": "fiil",
        "adjective": "sıfat",
        "noun": "isim",
        "adverb": "zarf",
        "adjective / verb": "sıfat / fiil",
        "verb (past tense)": "fiil (geçmiş zaman)",
        "adjective / noun": "sıfat / isim",
    },
    "az": {
        "verb": "fel",
        "adjective": "sifət",
        "noun": "isim",
        "adverb": "zərf",
        "adjective / verb": "sifət / fel",
        "verb (past tense)": "fel (keçmiş zaman)",
        "adjective / noun": "sifət / isim",
    },
    "kk": {
        "verb": "етістік",
        "adjective": "сын есім",
        "noun": "зат есім",
        "adverb": "үстеу",
        "adjective / verb": "сын есім / етістік",
        "verb (past tense)": "етістік (өткен шақ)",
        "adjective / noun": "сын есім / зат есім",
    },
    "ky": {
        "verb": "этиш",
        "adjective": "сын атооч",
        "noun": "зат атооч",
        "adverb": "тактооч",
        "adjective / verb": "сын атооч / этиш",
        "verb (past tense)": "этиш (өткөн чак)",
        "adjective / noun": "сын атооч / зат атооч",
    },
    "sw": {
        "verb": "kitenzi",
        "adjective": "kivumishi",
        "noun": "nomino",
        "adverb": "kielezi",
        "adjective / verb": "kivumishi / kitenzi",
        "verb (past tense)": "kitenzi (wakati uliopita)",
        "adjective / noun": "kivumishi / nomino",
    },
    "hy": {
        "verb": "բայ",
        "adjective": "ածական",
        "noun": "գոյական",
        "adverb": "մակբայ",
        "adjective / verb": "ածական / բայ",
        "verb (past tense)": "բայ (անցյալ ժամանակ)",
        "adjective / noun": "ածական / գոյական",
    },
    "ka": {
        "verb": "ზმნა",
        "adjective": "ზედსართავი",
        "noun": "არსებითი სახელი",
        "adverb": "ზმნიზედა",
        "adjective / verb": "ზედსართავი / ზმნა",
        "verb (past tense)": "ზმნა (წარსული)",
        "adjective / noun": "ზედსართავი / არსებითი სახელი",
    },
}

ORIGIN = {
    "ja": {
        "Latin": "ラテン語",
        "Greek": "ギリシャ語",
        "Old French": "古フランス語",
        "French": "フランス語",
        "German": "ドイツ語",
        "French / Latin": "フランス語 / ラテン語",
        "Greek / Latin": "ギリシャ語 / ラテン語",
        "Frankish / Old French": "フランク語 / 古フランス語",
        "Italian / French": "イタリア語 / フランス語",
        "Uncertain / Italian": "不詳 / イタリア語",
        "English": "英語",
        "Old French / English": "古フランス語 / 英語",
        "Spanish": "スペイン語",
        "Middle English": "中英語",
        "Old English": "古英語",
        "Latin / English": "ラテン語 / 英語",
        "Latin / French": "ラテン語 / フランス語",
        "Italian": "イタリア語",
        "Italian / Latin": "イタリア語 / ラテン語",
        "Italian / Greek": "イタリア語 / ギリシャ語",
        "Old French / Latin": "古フランス語 / ラテン語",
        "Latin / Old French": "ラテン語 / 古フランス語",
    },
    "ko": {
        "Latin": "라틴어",
        "Greek": "그리스어",
        "Old French": "고프랑스어",
        "French": "프랑스어",
        "German": "독일어",
        "French / Latin": "프랑스어 / 라틴어",
        "Greek / Latin": "그리스어 / 라틴어",
        "Frankish / Old French": "프랑크어 / 고프랑스어",
        "Italian / French": "이탈리아어 / 프랑스어",
        "Uncertain / Italian": "불확실 / 이탈리아어",
        "English": "영어",
        "Old French / English": "고프랑스어 / 영어",
        "Spanish": "스페인어",
        "Middle English": "중세 영어",
        "Old English": "고대 영어",
        "Latin / English": "라틴어 / 영어",
        "Latin / French": "라틴어 / 프랑스어",
        "Italian": "이탈리아어",
        "Italian / Latin": "이탈리아어 / 라틴어",
        "Italian / Greek": "이탈리아어 / 그리스어",
        "Old French / Latin": "고프랑스어 / 라틴어",
        "Latin / Old French": "라틴어 / 고프랑스어",
    },
    "zh_TW": {
        "Latin": "拉丁語",
        "Greek": "希臘語",
        "Old French": "古法語",
        "French": "法語",
        "German": "德語",
        "French / Latin": "法語／拉丁語",
        "Greek / Latin": "希臘語／拉丁語",
        "Frankish / Old French": "法蘭克語／古法語",
        "Italian / French": "義大利語／法語",
        "Uncertain / Italian": "不確定／義大利語",
        "English": "英語",
        "Old French / English": "古法語／英語",
        "Spanish": "西班牙語",
        "Middle English": "中古英語",
        "Old English": "古英語",
        "Latin / English": "拉丁語／英語",
        "Latin / French": "拉丁語／法語",
        "Italian": "義大利語",
        "Italian / Latin": "義大利語／拉丁語",
        "Italian / Greek": "義大利語／希臘語",
        "Old French / Latin": "古法語／拉丁語",
        "Latin / Old French": "拉丁語／古法語",
    },
    "zh_HK": {
        "Latin": "拉丁語",
        "Greek": "希臘語",
        "Old French": "古法語",
        "French": "法語",
        "German": "德語",
        "French / Latin": "法語／拉丁語",
        "Greek / Latin": "希臘語／拉丁語",
        "Frankish / Old French": "法蘭克語／古法語",
        "Italian / French": "意大利語／法語",
        "Uncertain / Italian": "不確定／意大利語",
        "English": "英語",
        "Old French / English": "古法語／英語",
        "Spanish": "西班牙語",
        "Middle English": "中古英語",
        "Old English": "古英語",
        "Latin / English": "拉丁語／英語",
        "Latin / French": "拉丁語／法語",
        "Italian": "意大利語",
        "Italian / Latin": "意大利語／拉丁語",
        "Italian / Greek": "意大利語／希臘語",
        "Old French / Latin": "古法語／拉丁語",
        "Latin / Old French": "拉丁語／古法語",
    },
    "vi": {
        "Latin": "tiếng Latinh",
        "Greek": "tiếng Hy Lạp",
        "Old French": "tiếng Pháp cổ",
        "French": "tiếng Pháp",
        "German": "tiếng Đức",
        "French / Latin": "tiếng Pháp / tiếng Latinh",
        "Greek / Latin": "tiếng Hy Lạp / tiếng Latinh",
        "Frankish / Old French": "tiếng Frank / tiếng Pháp cổ",
        "Italian / French": "tiếng Ý / tiếng Pháp",
        "Uncertain / Italian": "không chắc / tiếng Ý",
        "English": "tiếng Anh",
        "Old French / English": "tiếng Pháp cổ / tiếng Anh",
        "Spanish": "tiếng Tây Ban Nha",
        "Middle English": "tiếng Anh trung đại",
        "Old English": "tiếng Anh cổ",
        "Latin / English": "tiếng Latinh / tiếng Anh",
        "Latin / French": "tiếng Latinh / tiếng Pháp",
        "Italian": "tiếng Ý",
        "Italian / Latin": "tiếng Ý / tiếng Latinh",
        "Italian / Greek": "tiếng Ý / tiếng Hy Lạp",
        "Old French / Latin": "tiếng Pháp cổ / tiếng Latinh",
        "Latin / Old French": "tiếng Latinh / tiếng Pháp cổ",
    },
    "id": {
        "Latin": "Latin",
        "Greek": "Yunani",
        "Old French": "Prancis Kuno",
        "French": "Prancis",
        "German": "Jerman",
        "French / Latin": "Prancis / Latin",
        "Greek / Latin": "Yunani / Latin",
        "Frankish / Old French": "Frankish / Prancis Kuno",
        "Italian / French": "Italia / Prancis",
        "Uncertain / Italian": "tidak pasti / Italia",
        "English": "Inggris",
        "Old French / English": "Prancis Kuno / Inggris",
        "Spanish": "Spanyol",
        "Middle English": "Inggris Pertengahan",
        "Old English": "Inggris Kuno",
        "Latin / English": "Latin / Inggris",
        "Latin / French": "Latin / Prancis",
        "Italian": "Italia",
        "Italian / Latin": "Italia / Latin",
        "Italian / Greek": "Italia / Yunani",
        "Old French / Latin": "Prancis Kuno / Latin",
        "Latin / Old French": "Latin / Prancis Kuno",
    },
    "ms": {
        "Latin": "Latin",
        "Greek": "Yunani",
        "Old French": "Perancis Lama",
        "French": "Perancis",
        "German": "Jerman",
        "French / Latin": "Perancis / Latin",
        "Greek / Latin": "Yunani / Latin",
        "Frankish / Old French": "Frankish / Perancis Lama",
        "Italian / French": "Itali / Perancis",
        "Uncertain / Italian": "tidak pasti / Itali",
        "English": "Inggeris",
        "Old French / English": "Perancis Lama / Inggeris",
        "Spanish": "Sepanyol",
        "Middle English": "Inggeris Pertengahan",
        "Old English": "Inggeris Lama",
        "Latin / English": "Latin / Inggeris",
        "Latin / French": "Latin / Perancis",
        "Italian": "Itali",
        "Italian / Latin": "Itali / Latin",
        "Italian / Greek": "Itali / Yunani",
        "Old French / Latin": "Perancis Lama / Latin",
        "Latin / Old French": "Latin / Perancis Lama",
    },
    "fil": {
        "Latin": "Latin",
        "Greek": "Griyego",
        "Old French": "Lumang Pranses",
        "French": "Pranses",
        "German": "Aleman",
        "French / Latin": "Pranses / Latin",
        "Greek / Latin": "Griyego / Latin",
        "Frankish / Old French": "Frankish / Lumang Pranses",
        "Italian / French": "Italyano / Pranses",
        "Uncertain / Italian": "hindi tiyak / Italyano",
        "English": "Ingles",
        "Old French / English": "Lumang Pranses / Ingles",
        "Spanish": "Espanyol",
        "Middle English": "Gitnang Ingles",
        "Old English": "Lumang Ingles",
        "Latin / English": "Latin / Ingles",
        "Latin / French": "Latin / Pranses",
        "Italian": "Italyano",
        "Italian / Latin": "Italyano / Latin",
        "Italian / Greek": "Italyano / Griyego",
        "Old French / Latin": "Lumang Pranses / Latin",
        "Latin / Old French": "Latin / Lumang Pranses",
    },
    "tr": {
        "Latin": "Latince",
        "Greek": "Yunanca",
        "Old French": "Eski Fransızca",
        "French": "Fransızca",
        "German": "Almanca",
        "French / Latin": "Fransızca / Latince",
        "Greek / Latin": "Yunanca / Latince",
        "Frankish / Old French": "Frankça / Eski Fransızca",
        "Italian / French": "İtalyanca / Fransızca",
        "Uncertain / Italian": "belirsiz / İtalyanca",
        "English": "İngilizce",
        "Old French / English": "Eski Fransızca / İngilizce",
        "Spanish": "İspanyolca",
        "Middle English": "Orta İngilizce",
        "Old English": "Eski İngilizce",
        "Latin / English": "Latince / İngilizce",
        "Latin / French": "Latince / Fransızca",
        "Italian": "İtalyanca",
        "Italian / Latin": "İtalyanca / Latince",
        "Italian / Greek": "İtalyanca / Yunanca",
        "Old French / Latin": "Eski Fransızca / Latince",
        "Latin / Old French": "Latince / Eski Fransızca",
    },
    "az": {
        "Latin": "latın",
        "Greek": "yunanca",
        "Old French": "qədim fransız",
        "French": "fransız",
        "German": "alman",
        "French / Latin": "fransız / latın",
        "Greek / Latin": "yunanca / latın",
        "Frankish / Old French": "frank / qədim fransız",
        "Italian / French": "italyan / fransız",
        "Uncertain / Italian": "qeyri-müəyyən / italyan",
        "English": "ingilis",
        "Old French / English": "qədim fransız / ingilis",
        "Spanish": "ispan",
        "Middle English": "orta ingilis",
        "Old English": "qədim ingilis",
        "Latin / English": "latın / ingilis",
        "Latin / French": "latın / fransız",
        "Italian": "italyan",
        "Italian / Latin": "italyan / latın",
        "Italian / Greek": "italyan / yunanca",
        "Old French / Latin": "qədim fransız / latın",
        "Latin / Old French": "latın / qədim fransız",
    },
    "kk": {
        "Latin": "латын",
        "Greek": "грек",
        "Old French": "ескі француз",
        "French": "француз",
        "German": "неміс",
        "French / Latin": "француз / латын",
        "Greek / Latin": "грек / латын",
        "Frankish / Old French": "франк / ескі француз",
        "Italian / French": "итальян / француз",
        "Uncertain / Italian": "белгісіз / итальян",
        "English": "ағылшын",
        "Old French / English": "ескі француз / ағылшын",
        "Spanish": "испан",
        "Middle English": "орта ағылшын",
        "Old English": "ескі ағылшын",
        "Latin / English": "латын / ағылшын",
        "Latin / French": "латын / француз",
        "Italian": "итальян",
        "Italian / Latin": "итальян / латын",
        "Italian / Greek": "итальян / грек",
        "Old French / Latin": "ескі француз / латын",
        "Latin / Old French": "латын / ескі француз",
    },
    "ky": {
        "Latin": "латын",
        "Greek": "грек",
        "Old French": "эски француз",
        "French": "француз",
        "German": "немис",
        "French / Latin": "француз / латын",
        "Greek / Latin": "грек / латын",
        "Frankish / Old French": "франк / эски француз",
        "Italian / French": "итальян / француз",
        "Uncertain / Italian": "белгисиз / итальян",
        "English": "англис",
        "Old French / English": "эски француз / англис",
        "Spanish": "испан",
        "Middle English": "орто англис",
        "Old English": "эски англис",
        "Latin / English": "латын / англис",
        "Latin / French": "латын / француз",
        "Italian": "итальян",
        "Italian / Latin": "итальян / латын",
        "Italian / Greek": "итальян / грек",
        "Old French / Latin": "эски француз / латын",
        "Latin / Old French": "латын / эски француз",
    },
    "sw": {
        "Latin": "Kilatini",
        "Greek": "Kigiriki",
        "Old French": "Kifaransa cha Kale",
        "French": "Kifaransa",
        "German": "Kijerumani",
        "French / Latin": "Kifaransa / Kilatini",
        "Greek / Latin": "Kigiriki / Kilatini",
        "Frankish / Old French": "Kifranki / Kifaransa cha Kale",
        "Italian / French": "Kiitalia / Kifaransa",
        "Uncertain / Italian": "si hakika / Kiitalia",
        "English": "Kiingereza",
        "Old French / English": "Kifaransa cha Kale / Kiingereza",
        "Spanish": "Kihispania",
        "Middle English": "Kiingereza cha Kati",
        "Old English": "Kiingereza cha Kale",
        "Latin / English": "Kilatini / Kiingereza",
        "Latin / French": "Kilatini / Kifaransa",
        "Italian": "Kiitalia",
        "Italian / Latin": "Kiitalia / Kilatini",
        "Italian / Greek": "Kiitalia / Kigiriki",
        "Old French / Latin": "Kifaransa cha Kale / Kilatini",
        "Latin / Old French": "Kilatini / Kifaransa cha Kale",
    },
    "hy": {
        "Latin": "լատիներեն",
        "Greek": "հունարեն",
        "Old French": "հին ֆրանսերեն",
        "French": "ֆրանսերեն",
        "German": "գերմաներեն",
        "French / Latin": "ֆրանսերեն / լատիներեն",
        "Greek / Latin": "հունարեն / լատիներեն",
        "Frankish / Old French": "ֆրանկերեն / հին ֆրանսերեն",
        "Italian / French": "իտալերեն / ֆրանսերեն",
        "Uncertain / Italian": "անորոշ / իտալերեն",
        "English": "անգլերեն",
        "Old French / English": "հին ֆրանսերեն / անգլերեն",
        "Spanish": "իսպաներեն",
        "Middle English": "միջին անգլերեն",
        "Old English": "հին անգլերեն",
        "Latin / English": "լատիներեն / անգլերեն",
        "Latin / French": "լատիներեն / ֆրանսերեն",
        "Italian": "իտալերեն",
        "Italian / Latin": "իտալերեն / լատիներեն",
        "Italian / Greek": "իտալերեն / հունարեն",
        "Old French / Latin": "հին ֆրանսերեն / լատիներեն",
        "Latin / Old French": "լատիներեն / հին ֆրանսերեն",
    },
    "ka": {
        "Latin": "ლათინური",
        "Greek": "ბერძნული",
        "Old French": "ძველი ფრანგული",
        "French": "ფრანგული",
        "German": "გერმანული",
        "French / Latin": "ფრანგული / ლათინური",
        "Greek / Latin": "ბერძნული / ლათინური",
        "Frankish / Old French": "ფრანკული / ძველი ფრანგული",
        "Italian / French": "იტალიური / ფრანგული",
        "Uncertain / Italian": "გაურკვეველი / იტალიური",
        "English": "ინგლისური",
        "Old French / English": "ძველი ფრანგული / ინგლისური",
        "Spanish": "ესპანური",
        "Middle English": "შუა ინგლისური",
        "Old English": "ძველი ინგლისური",
        "Latin / English": "ლათინური / ინგლისური",
        "Latin / French": "ლათინური / ფრანგული",
        "Italian": "იტალიური",
        "Italian / Latin": "იტალიური / ლათინური",
        "Italian / Greek": "იტალიური / ბერძნული",
        "Old French / Latin": "ძველი ფრანგული / ლათინური",
        "Latin / Old French": "ლათინური / ძველი ფრანგული",
    },
}


def emit(locale: str, rows: list[tuple[str, str, str, str, str]]) -> None:
    """rows: (definition, friendly, exampleGloss, root1, root2) in EN order."""
    if len(rows) != len(EN):
        raise SystemExit(f"{locale}: expected {len(EN)} rows, got {len(rows)}")
    pos_map = POS[locale]
    origin_map = ORIGIN[locale]
    words = {}
    for src, row in zip(EN, rows):
        definition, friendly, gloss, r1, r2 = row
        if src["pos"] not in pos_map:
            raise SystemExit(f"{locale}: missing POS {src['pos']!r}")
        if src["origin"] not in origin_map:
            raise SystemExit(f"{locale}: missing origin {src['origin']!r}")
        if not all(isinstance(x, str) and x.strip() for x in row):
            raise SystemExit(f"{locale}: empty field in {src['id']}")
        words[src["id"]] = {
            "partOfSpeech": pos_map[src["pos"]],
            "definition": definition,
            "friendly": friendly,
            "exampleGloss": gloss,
            "origin": origin_map[src["origin"]],
            "rootMeanings": [r1, r2],
        }
    path = OUT / f"words_{locale}.json"
    path.write_text(
        json.dumps({"words": words}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {path} ({len(words)} words)")
