# Portuguese (European) overlays: (definition, friendly, exampleGloss, root1, root2)
WORDS = {
    "edulcorate": (
        "Doçar ou purificar; tirar a aspereza de alguma coisa.",
        "Tirar o ferrão ou o amargor — adoçar a sério, ou suavizar em sentido figurado uma ideia dura para que desça melhor.",
        "O redator edulcorated a crítica dura antes de a mandar para impressão.",
        "fora, a fundo",
        "doce",
    ),
    "pietistic": (
        "Excessiva ou fingidamente religioso ou piedoso.",
        "Descreve alguém cuja devoção cheira a espetáculo: mais pose do que fé verdadeira.",
        "Os seus suspiros pietistic durante o sermão irritaram o resto do banco.",
        "piedade, sentido do dever",
        "que tem o carácter de",
    ),
    "amphiboly": (
        "Ambiguidade nascida da estrutura gramatical — uma frase que se lê de duas maneiras.",
        "Uma frase gramaticalmente correta, mas que se pode ler de dois modos completamente diferentes, como «Visiting relatives can be tiring».",
        "«Visiting relatives can be tiring» é uma amphiboly clássica — cansam os parentes, ou o facto de os visitar?",
        "ambos, de ambos os lados",
        "lançar",
    ),
    "trenchant": (
        "Agudo, incisivo, que vai direto ao ponto.",
        "Corta o recheio de um só golpe — um comentário ou uma mente trenchant chega ao cerne depressa, sem palavras a mais.",
        "A sua crítica trenchant não deixou recanto onde se escondessem os buracos do argumento.",
        "cortar",
        "fazendo, que tem a qualidade de",
    ),
    "inchoative": (
        "Que mal começou; numa fase precoce ou rudimentar.",
        "Ainda nos primeiros instantes — um plano, um sentimento ou um processo que só agora começa a tomar forma.",
        "As fases inchoative do tratado eram promissoras, mas muitos pormenores ficaram por assentar.",
        "começar, dar início",
        "que tende para",
    ),
    "panegyric": (
        "Um discurso ou escrito formal que louva alguém com brilho.",
        "Uma homenagem em toda a regra — pense num elogio fúnebre luminoso, ou num discurso que canta os feitos de alguém aos quatro ventos.",
        "A professora que se reformava foi despedida com um panegyric dos seus alunos mais próximos.",
        "todo, inteiro",
        "assembleia, reunião",
    ),
    "ontic": (
        "Relativo à existência real, em oposição à teoria abstrata.",
        "Das coisas tais como existem de verdade, e não só como ideias ou teorias a seu respeito.",
        "Os filósofos debatem se os números têm algum estatuto ontic ou existem apenas nas nossas cabeças.",
        "ser, o que existe",
        "relativo a",
    ),
    "fructify": (
        "Dar fruto, ou tornar-se produtivo.",
        "Por fim dar fruto — um esforço, uma ideia ou um investimento que fructifies passou da semente a algo útil.",
        "Anos de investigação calada fructified enfim numa vacina que funciona.",
        "fruto",
        "fazer, causar",
    ),
    "proleptical": (
        "Antecipar ou apresentar algo como já feito antes de acontecer.",
        "Adiantar-se de modo literário — descrever um facto futuro como se já estivesse fechado, para o golpe cair mais fundo.",
        "O brinde proleptical do general a «victory» foi pronunciado uma semana inteira antes da batalha.",
        "antes",
        "tomar, agarrar",
    ),
    "pneumatic": (
        "Accionado por pressão de ar; também relativo ao espírito ou ao sopro.",
        "O mais habitual: movido a ar comprimido — uma broca, um travão de autocarro — mas a mesma raiz grega fala também de sopro e de espírito.",
        "Os travões pneumatic sibilavam quando o autocarro parou no lancil.",
        "vento, sopro, espírito",
        "pertencente a",
    ),
    "cataphatic": (
        "Descrever Deus ou o divino com afirmações positivas — o contrário de apofático.",
        "Falar de Deus dizendo o que Ele é — «Deus é amor», «Deus é justo» — em vez de apenas o que Ele não é.",
        "A teologia cataphatic fala com confiança de Deus como amoroso, justo e misericordioso.",
        "abaixo, segundo",
        "falar, dizer",
    ),
    "fiducial": (
        "Fundado na confiança ou na fé; também: um ponto de referência fixo.",
        "Algo que se toma a crédito e depois serve de âncora — uma marca fiducial é o ponto fixo contra o qual se mede todo o resto.",
        "Os topógrafos colocaram um marcador fiducial na rocha antes de cartografar o sítio.",
        "confiar",
        "confiança, segurança",
    ),
    "theodicy": (
        "Uma defesa da bondade de Deus face à existência do mal.",
        "A tentativa de sempre: responder «se Deus é bom, porque há mal?» sem largar nenhuma das duas afirmações.",
        "A tese dela explorava theodicy através da lente do Livro de Job.",
        "deus",
        "justiça",
    ),
    "circumincession": (
        "Inhabitação mútua — termo teológico para o modo como as pessoas da Trindade existem umas nas outras.",
        "Uma palavra de teologia para um conjunto três-em-um tão completo que cada parte contém as outras e é por elas contida.",
        "A doutrina de circumincession tenta explicar como Pai, Filho e Espírito são distintos e ainda assim inseparáveis.",
        "à volta",
        "ir, andar",
    ),
    "redound": (
        "Ter uma consequência que beneficia alguém ou recai sobre ele.",
        "Quando o crédito (ou a culpa) ressalta para quem é responsável — as boas ações que redound ao seu nome voltam depois como prémio.",
        "O êxito da equipa redound ao crédito do treinador calado e trabalhador.",
        "para trás, de novo",
        "onda",
    ),
    "ineluctable": (
        "Que não se pode evitar nem de que se possa escapar.",
        "Vai acontecer faça o que fizer — de um desfecho ineluctable não se safará.",
        "A velhice chega para todos; é simplesmente ineluctable.",
        "não",
        "forcejar para sair",
    ),
    "periphrastic": (
        "Que usa um rodeio verboso em vez de uma forma direta.",
        "Tomar o caminho longo com as palavras — dizer numa frase inteira o que uma só palavra cobriria.",
        "Os seus e-mails periphrastic poderiam ter dito numa linha o que lhe levou três parágrafos.",
        "à volta",
        "declarar, contar",
    ),
    "hebetude": (
        "Embaciamento mental ou letargia.",
        "Aquele estado de espírito brumoso e lento em que pensar é como vadear xarope.",
        "Uma vaga de hebetude caiu sobre a turma logo a seguir ao almoço.",
        "romo, embotado",
        "estado ou qualidade",
    ),
    "unpropitious": (
        "Pouco favorável; de mau agouro.",
        "Mau sinal — condições ou um momento que já parecem ir contra si antes de ter começado.",
        "Céu cinzento e bateria do carro morta fizeram um arranque unpropitious para a viagem.",
        "não",
        "favorável, gracioso",
    ),
    "fricaseed": (
        "Carne estufada ou braseada em molho — corretamente escrito «fricasseed».",
        "Um termo de cozinha antigo e caseiro para carne cortada e cozida lentamente no próprio molho até ficar tenra.",
        "O frango fricasseed da avó era o ponto alto de cada jantar de domingo.",
        "fritar",
        "partir (em pedaços)",
    ),
    "ersatz": (
        "Um substituto artificial ou de menor qualidade.",
        "Uma imitação que faz as vezes do verdadeiro — cumpre, mas toda a gente vê que não é o original.",
        "Em tempo de guerra, os fregueses contentavam-se com café ersatz de chicória torrada.",
        "fora, prefixo de substituição",
        "pôr, colocar",
    ),
    "reify": (
        "Tratar uma ideia abstrata como se fosse uma coisa concreta.",
        "Fazer uma ideia sentir-se real e sólida — transformar algo vago, como «o mercado», num objeto a que se pode apontar.",
        "Chamar «espírito» de uma nação a um ser próprio reifies algo que na verdade não passa de milhões de escolhas soltas.",
        "coisa",
        "fazer",
    ),
    "eluded": (
        "Escapado ou evitado com jeito.",
        "Escorregar limpo — esquivar-se a algo, muitas vezes com astúcia ou por um triz, seja uma captura, uma pergunta ou uma resposta.",
        "A resposta eluded durante horas até que, de repente, encaixou no duche.",
        "fora, longe",
        "jogar",
    ),
    "aporetic": (
        "Que expressa dúvida, perplexidade ou uma contradição por resolver.",
        "Encalhado num beco de verdade do pensamento — não por preguiça, mas porque a própria pergunta se recusa a uma resposta limpa.",
        "Sócrates costumava terminar os diálogos numa nota aporetic, com mais perguntas do que respostas.",
        "sem",
        "passagem, caminho",
    ),
    "metonymy": (
        "Figura que nomeia algo por um termo associado, p. ex. «a coroa» pelo monarca.",
        "Usar uma palavra aparentada em vez da coisa mesma — dizer «Wall Street» quando se quer dizer a bolsa.",
        "«Wall Street had a rough day» é metonymy — na verdade significa que a bolsa teve um mau dia.",
        "mudança, depois",
        "nome",
    ),
    "deracinate": (
        "Desenraizar; arrancar de um meio natural.",
        "Arrancar algo (ou alguém) pela raiz, longe do sítio ou da cultura a que pertence.",
        "A guerra deracinated toda uma geração, espalhando famílias para além das fronteiras.",
        "longe, fora",
        "raiz",
    ),
    "euphonious": (
        "De som agradável.",
        "Simplesmente bom de ouvir — uma palavra ou uma frase euphonious escorrega, quase com música, no ouvido.",
        "«Murmuring brook» é uma frasinha euphonious, macia e fácil de dizer.",
        "bom, bem",
        "som, voz",
    ),
    "putative": (
        "Geralmente suposto ou tido como tal.",
        "Tido por verdadeiro à larga, mesmo sem prova — a versão presumida ou suposta de alguma coisa.",
        "O autor putative da carta veio a revelar-se um desconhecido total.",
        "pensar, considerar",
        "que tem a natureza de",
    ),
    "neologism": (
        "Uma palavra ou locução recém-cunhada.",
        "Uma palavra novinha em folha — recém-inventada, ainda (quase) fora do dicionário.",
        "«Doomscrolling» começou como neologism e depressa se tornou calão do dia a dia.",
        "novo",
        "palavra, fala",
    ),
    "splenetic": (
        "Zangado ou de mau génio.",
        "De humor azedo e irritável, pronto a saltar — como se acreditava outrora que o baço governava o temperamento.",
        "Disparou uma resposta splenetic ao e-mail segundos depois de o ler.",
        "baço (sede da ira)",
        "afetado por",
    ),
    "sententious": (
        "Dado a moralizar de modo pomposo ou afetado.",
        "Adora debitar liçõezinhas de vida, como se cada frase fosse um biscoito da sorte.",
        "O seu brinde sententious sobre «the true meaning of friendship» fez toda a gente olhar para o relógio.",
        "opinião, máxima",
        "cheio de",
    ),
    "garrulous": (
        "Excessivamente falador, sobretudo de nadas.",
        "Não pára de conversar — divaga sobre miudezas muito depois de os outros se terem calado.",
        "O taxista garrulous contou-nos a vida toda antes de sairmos do aeroporto.",
        "tagarelar, palrar",
        "inclinado a",
    ),
    "fatuity": (
        "Parvoíce, asneira.",
        "A parvoíce lisa — um comentário ou um plano tão parvo que mal merece uma resposta a sério.",
        "A fatuity pura do plano ficou óbvia no momento em que o experimentaram.",
        "parvo, tolo",
        "estado de ser",
    ),
    "peroration": (
        "A parte conclusiva de um discurso, muitas vezes recapitulativa.",
        "O grande final de um discurso — o troço em que o orador junta tudo e crava o ponto.",
        "Na peroration, metade da plateia estava de pé.",
        "através, até ao fim",
        "falar, alegar",
    ),
    "tautology": (
        "Repetição desnecessária da mesma ideia com outras palavras.",
        "Dizer o mesmo duas vezes sem acrescentar nada, como «oferta grátis» ou «it is what it is».",
        "«It is what it is» é uma tautology favorita de quem evita uma explicação a sério.",
        "o mesmo",
        "palavra, fala",
    ),
    "laconism": (
        "O uso de muito poucas palavras; um falar lacónico.",
        "Dizer muito com muito pouco — a arte da réplica curta e seca, assim chamada pelos espartanos da Lacónia, famosos pela brevidade.",
        "«Molon labe» — «come and take them» — é o pedaço de laconism mais famoso da história.",
        "um espartano da Lacónia",
        "prática, maneira",
    ),
    "pabulum": (
        "Ideias insípidas e demasiado simplificadas; na origem, comida sosa ou papa.",
        "Pensamento aguado — conteúdo tão simplificado e tão seguro que não nutre a mente.",
        "O discurso do político era sobretudo pabulum: promessas vagas a que não se podia agarrar nada.",
        "alimentar",
        "meio ou instrumento",
    ),
    "soporific": (
        "Que provoca sono ou sonolência.",
        "Tão aborrecido — ou tão literalmente sedativo — que dá sono. Pense em leite quente, ou numa reunião de orçamento de três horas.",
        "O zumbido soporific da aula tinha metade da sala a lutar para não fechar os olhos.",
        "sono profundo",
        "que faz, que causa",
    ),
    "unctuous": (
        "Excessivamente lisonjeiro ou oleoso no trato.",
        "Tão liso de encanto que escorrega — uma lisonja tão espessa que quase se sente a gordura.",
        "O vendedor unctuous não parava de elogiar o meu «excellent taste» antes de cada venda extra.",
        "ungir, olear",
        "cheio de",
    ),
    "captious": (
        "Pronto a achar defeito, demasiado crítico com nadas.",
        "Picuinhas até ao excesso — o tipo que encontra problema em tudo, mesmo quando não importa.",
        "As suas notas captious ao relatório centravam-se por completo nas vírgulas.",
        "agarrar, tomar",
        "uma armadilha, um sofisma",
    ),
    "torpid": (
        "Lento, inativo de mente ou de corpo.",
        "Lento e a meio adormecido, como um urso em hibernação — quase não se mexe, quase não pensa.",
        "O escritório caiu torpid no calor pesado de agosto.",
        "estar entorpecido, estar preguiçoso",
        "num estado de",
    ),
    "seneschal": (
        "Um mordomo ou oficial que geria uma casa medieval.",
        "A versão medieval de um chefe de pessoal — o oficial de confiança que levava no dia a dia a casa e a herdade de um senhor.",
        "O seneschal do castelo geria tudo, das contas da colheita à lista de convidados.",
        "velho, sénior",
        "servo",
    ),
    "expatiate": (
        "Falar ou escrever longamente sobre um tema.",
        "Pôr-se a sério a caminho — falar ou escrever sem parar, percorrendo o assunto de todos os lados.",
        "Pergunte-lhe de carros de época e ele vai expatiate durante uma hora inteira.",
        "fora",
        "espaço",
    ),
    "nugatory": (
        "Sem valor, fútil; também inválido ou ineficaz.",
        "Que quase não vale nada — uma cláusula nugatory num contrato, na prática, não faz nada.",
        "O tribunal declarou nugatory o velho regulamento, pois nunca tinha sido aplicado.",
        "futilidades, disparates",
        "pertencente a",
    ),
    "sagacity": (
        "Sabedoria, juízo perspicaz.",
        "Uma sabedoria viva e prática — o bom juízo que vem da experiência, não só dos livros.",
        "A sagacity do velho capitão tirou a tripulação de sarilhos mais do que uma vez.",
        "de olfato fino, perspicaz",
        "qualidade de",
    ),
    "canaille": (
        "A ralé ou a massa, usado com desprezo.",
        "Uma palavra esnobe e desdenhosa para a gente comum, como se fossem uma alcateia de cães.",
        "O conde escarneceu da canaille reunida fora dos portões do palácio.",
        "cão",
        "coletivo, matilha",
    ),
    "contumely": (
        "Trato ou linguagem insolente e humilhante.",
        "Um trato cruel e desdenhoso feito para humilhar — o insulto pensado para arder.",
        "Aguentou anos de contumely dos críticos antes de a obra ser enfim reconhecida.",
        "com, a fundo",
        "inchar (de orgulho)",
    ),
    "askance": (
        "Com suspeita ou desaprovação; um olhar de viés.",
        "O olhar de lado que se lança a algo em que não se confia de todo — um olhar carregado de dúvida.",
        "A professora olhou askance para o trabalho de casa suspeitosamente arrumado.",
        "para, a",
        "viés, inclinação",
    ),
    "clodpate": (
        "Um parvo; um cabeça-dura.",
        "Um insulto antigo, quase afetuoso, para alguém torpe ou denso — um cabeça-dura.",
        "«You clodpate», riu ela, «you've had the map upside down the whole time.»",
        "torrão de terra",
        "cabeça",
    ),
    "actuate": (
        "Pôr em movimento ou em ação; motivar.",
        "Ser a faísca que põe algo a andar — uma máquina que liga ou uma pessoa que por fim age sobre uma ideia.",
        "O medo de perder o contrato actuated toda a equipa para um fim de semana de horas extra.",
        "um fazer, um impelir",
        "impelir, fazer",
    ),
    "peculation": (
        "Peculato de fundos confiados à sua guarda.",
        "Roubar em silêncio o dinheiro que se devia guardar — o peculato, vestido à antiga.",
        "A peculation do tesoureiro passou despercebida durante quase uma década.",
        "propriedade privada",
        "gado, riqueza",
    ),
    "demi-monde": (
        "Um grupo tido nas margens da sociedade respeitável.",
        "O meio-mundo glamouroso e sombrio — gente que vive mesmo fora das regras do decoro.",
        "O romance segue uma cantora na demi-monde dos cabarés dos anos vinte.",
        "meio",
        "mundo, sociedade",
    ),
    "extant": (
        "Que ainda existe; não extinto nem destruído.",
        "Continua cá hoje — diz-se de coisas velhas (manuscritos, espécies, edifícios) que conseguiram sobreviver.",
        "Só se conhecem três exemplares extant da primeira impressão.",
        "fora",
        "estar de pé",
    ),
    "perfidy": (
        "Engano; traição da confiança.",
        "Uma traição funda e deliberada — quebrar uma confiança que alguém tinha o direito de esperar de si.",
        "O general nunca perdoou a perfidy do velho amigo à mesa das negociações.",
        "através, contra",
        "fé, confiança",
    ),
    "patois": (
        "Um dialeto regional, sobretudo não padrão.",
        "O modo próprio, local, de falar numa região — cheio de palavras e ritmos que um forasteiro não apanha.",
        "A avó ainda falava o patois da ilha nos jantares de família.",
        "fala tosca, dialeto",
        "pata — fala desajeitada",
    ),
    "prerogative": (
        "Um direito especial de uma pessoa ou de um grupo.",
        "Um privilégio que é só seu — um direito que vem com o papel, o posto ou o estatuto.",
        "Escolher o destino das férias da família é a prerogative do Grandpa, e toda a gente o sabe.",
        "antes",
        "perguntar, votar",
    ),
    "hardihood": (
        "Ousadia, audácia; também resistência ou fôlego.",
        "Uma resiliência rude e corajosa — o nervo de avançar e a teimosia de aguentar uma vez a caminho.",
        "Foi precisa uma hardihood a sério para cruzar o porto num nevão, sem mapa.",
        "ousado, rijo",
        "estado, condição",
    ),
    "effloresce": (
        "Estalar em flor; também desenvolver-se ou aparecer aos poucos.",
        "Abrir-se até se exprimir de todo — como uma flor que se abre, ou uma ideia que por fim encontra a forma.",
        "O talento calado dela para a pintura effloresced assim que teve um ateliê seu.",
        "fora",
        "começar a florescer",
    ),
    "plumb-line": (
        "Um fio de prumo para julgar a vertical; em sentido figurado, um critério.",
        "Um peso num fio que cai a prumo, para ver se algo está mesmo a prumo — e, por extensão, qualquer medida fixa contra a qual se compara o resto.",
        "Usava a honestidade do avô como uma espécie de plumb line para cada decisão.",
        "chumbo",
        "corda, medida",
    ),
    "fain": (
        "De bom grado, de vontade (arcaico).",
        "Um modo antigo de dizer «de bom grado» ou «com gosto» — you would fain fazer algo se isso lhe apetecer.",
        "«I would fain rest here a while», suspirou o viajante.",
        "alegre, gozoso",
        "de bom grado, de vontade",
    ),
    "opprobrium": (
        "Crítica pública dura, ou desonra.",
        "A vergonha pública deitada em cima de alguém em grande — a desonra de uma desaprovação geral.",
        "O escândalo trouxe opprobrium público sobre toda a firma.",
        "contra",
        "desonra, censura",
    ),
    "mordant": (
        "Vivamente sarcástico, mordaz no engenho ou na crítica.",
        "Engenho com dentes a sério — um comentário mordant pica precisamente porque aponta tão bem.",
        "As críticas de cinema mordant dela eram temidas pelos realizadores e amadas pelos leitores.",
        "morder",
        "mordaz, fazendo",
    ),
    "pronunciamento": (
        "Uma proclamação formal, muitas vezes política ou militar.",
        "Um anúncio grande e oficial — costuma ser o que declara um governo novo, um levantamento ou um decreto maior.",
        "O pronunciamento do general anunciou o novo governo ao amanhecer.",
        "avante",
        "anunciar",
    ),
    "sciolist": (
        "Pessoa de saber superficial que se faz passar por perito.",
        "Alguém que roçou a superfície de um tema e depois fala como se tivesse escrito o manual.",
        "O sciolist do jantar corrigiu com à-vontade o verdadeiro astrofísico à mesa.",
        "saber",
        "diminutivo — um pequeno sabedor",
    ),
    "dotage": (
        "O declínio das faculdades mentais na velhice.",
        "O troço brumoso e esquecido da velhice avançada, quando a agudeza da mente começa a apagar-se.",
        "Na sua dotage, contava as mesmas três histórias em cada visita, cada vez como se fossem novas.",
        "chochear, ser tolo",
        "estado ou resultado",
    ),
    "lee-side": (
        "O lado abrigado do vento.",
        "O lado calmo e abrigado de alguma coisa — uma colina, um navio, um muro — onde o vento já não chega de todo.",
        "Os caminhantes armaram a tenda no lee side da crista para fugir às rajadas.",
        "abrigo, proteção",
        "flanco, face",
    ),
    "parry": (
        "Desviar ou rejeitar um golpe, uma pergunta ou um argumento.",
        "Afastar com jeito — um golpe de espada, uma pergunta incómoda, uma acusação — sem perder o compasso.",
        "Ela parried a pergunta manhosa do jornalista com uma piada fácil.",
        "rejeitar",
        "preparar, defender",
    ),
    "mephitic": (
        "De cheiro nauseabundo, nocivo.",
        "Fétido de um modo quase tóxico — um cheiro tão mau que parece perigoso respirar.",
        "Um cheiro mephitic subiu do pântano ao pôr do sol.",
        "vapor nocivo",
        "que tem a natureza de",
    ),
    "sybarite": (
        "Pessoa votada ao luxo e ao prazer.",
        "Alguém que vive para o conforto e o deleite — boa mesa, camas macias, vida fácil — assim chamado pela cidade grega de Síbaris, famosa pelo excesso.",
        "Um verdadeiro sybarite, recusava qualquer quarto de hotel sem banheira.",
        "antiga cidade grega famosa pelo luxo",
        "habitante de",
    ),
    "prescind": (
        "Pôr de lado ou ignorar de propósito uma parte de alguma coisa.",
        "Afastar de propósito, na mente, uma peça do puzzle para olhar limpo o resto.",
        "Prescind um momento do custo e perguntemos só se o plano funciona de verdade.",
        "antes, longe",
        "cortar",
    ),
    "excoriate": (
        "Criticar com dureza; também, esfolar.",
        "Esfolar alguém a golpes de crítica — como se se lhe arrancasse a pele a sério.",
        "Os críticos excoriated a sequela por trair tudo o que os fãs amavam no original.",
        "fora",
        "pele, couro",
    ),
    "adduce": (
        "Citar como prova ou como evidência.",
        "Trazer um facto ou um exemplo para suster o ponto — aquilo a que se aponta quando alguém pede provas.",
        "A advogada adduced três testemunhas em apoio do álibi da cliente.",
        "para, em direção a",
        "conduzir",
    ),
    "peregrinations": (
        "Viagens ou andanças, sobretudo longas ou extensas.",
        "Longos periplos errantes — essa espécie de vaguear que o tem longe de casa uma boa temporada.",
        "As suas peregrinations por três continentes encheram uma prateleira inteira de diários de viagem.",
        "através",
        "campo, terra (peregrinus: estrangeiro)",
    ),
    "mendicant": (
        "Um mendigo, ou quem vive de esmolas.",
        "Alguém que vive a pedir caridade — historicamente, também frades que fizeram voto de pobreza e viviam de donativos.",
        "Os frades mendicant não possuíam nada e dependiam por inteiro da bondade dos aldeões.",
        "mendigar",
        "mendigo",
    ),
    "munificent": (
        "Extremamente generoso.",
        "Generoso a uma escala quase teatral — o donativo que arranca um pequeno «ah».",
        "A doação munificent financiou toda a nova ala da biblioteca.",
        "dom, serviço",
        "fazendo, dando",
    ),
    "inanition": (
        "Esgotamento por falta de alimento; também falta de vitalidade.",
        "Um estado fraco, esvaziado, por não estar alimentado — no literal pela fome, ou no figurado por não restar combustível.",
        "No fim do cerco, os soldados estavam perto da inanition.",
        "vazio, vão",
        "o ato ou o resultado de",
    ),
    "vituperation": (
        "Crítica amarga e injuriosa.",
        "Uma crítica que já deixou para trás o justo e se tornou uma diatribe zangada e amarga.",
        "Os comentários em linha dissolveram-se em pura vituperation em minutos.",
        "falha, defeito",
        "preparar, fornecer",
    ),
    "inimical": (
        "Hostil, prejudicial nos efeitos.",
        "Que trabalha contra si, ainda que em silêncio — condições ou atitudes pouco amigas dos seus interesses.",
        "A nova política era inimical para os pequenos negócios, mesmo que essa não fosse a intenção.",
        "não",
        "amigo",
    ),
    "invidious": (
        "Propenso a causar rancor, muitas vezes por comparações injustas.",
        "De certeza que alguém se sente menosprezado — quase sempre porque se põe gente ou coisas em concorrência desigual.",
        "Classificar os irmãos por «who Mom loves best» é um jogo invidious que ninguém deveria jogar.",
        "inveja",
        "olhar (com má vontade)",
    ),
    "subaltern": (
        "Pessoa de grau ou estatuto inferior; um subordinado.",
        "Alguém mais abaixo na cadeia de comando ou na escala social — um júnior, sob alguém com mais poder.",
        "Como jovem subaltern, recebeu ordens muito tempo antes de as dar.",
        "sob",
        "alternativo, outro",
    ),
    "execrate": (
        "Sentir ou exprimir um ódio intenso.",
        "Aborrecer algo tanto que se amaldiçoa em voz alta — uma detestação pura e sonora.",
        "Os aldeões execrated o cobrador de impostos cada vez que o carro dele atravessava a vila.",
        "fora de",
        "sagrado (amaldiçoar para fora do sagrado)",
    ),
    "integument": (
        "Uma cobertura natural exterior, como a pele ou uma carapaça.",
        "O invólucro protetor da natureza — pele, concha, casca ou cortiça, o que cobre e resguarda um ser vivo.",
        "A carapaça de uma tartaruga é um integument notavelmente rijo.",
        "sobre, por cima",
        "cobrir",
    ),
    "ingenuous": (
        "Inocente, ingénuo, de simplicidade infantil; o contrário de manhoso.",
        "Abertamente confiante e um pouco ingénuo, sem agenda oculta — fácil de confundir com «ingenious», que significa engenhoso.",
        "A pergunta ingenuous dela — «why would anyone lie about that?» — mostrava quão pouca astúcia tinha.",
        "em, nativo",
        "gerar (de nascimento livre, cândido)",
    ),
    "pedantry": (
        "Preocupação excessiva com pormenores menores ou regras.",
        "Perder-se nas regras miúdas e falhar o quadro grande — obcecar-se com a letra pequena de que mais ninguém se importa.",
        "A pedantry dele com as vírgulas de Oxford descarrilou toda a reunião.",
        "preceptor de crianças",
        "prática ou qualidade",
    ),
    "perscrutation": (
        "Um exame minucioso e cuidadoso.",
        "Um olhar fundo, que não deixa pedra por mexer — percorrer cada pormenor com verdadeiro cuidado.",
        "Só após uma perscrutation atenta dos livros apareceu a discrepância.",
        "através, a fundo",
        "procurar, examinar",
    ),
    "demur": (
        "Levantar objeções; mostrar relutância.",
        "Recuar com cortesia ou hesitar em vez de seguir logo — um suave «um momento».",
        "Quando lhe pediram que assinasse sem ler, ela demurred.",
        "de, longe",
        "demorar",
    ),
    "specious": (
        "Plausível na aparência, mas na verdade falso.",
        "Soa convincente à primeira vista, mas desfaz-se assim que se verifica a sério.",
        "«Everyone's doing it» é um argumento specious que nunca aguenta de todo o escrutínio.",
        "aparência, aspeto",
        "cheio de (de belo parecer)",
    ),
    "cant": (
        "Conversa insincera e hipócrita, muitas vezes moralizante.",
        "Um falar de púlpito que soa virtuoso sem sentimento verdadeiro — pose moral em piloto automático.",
        "Estava farto do cant empresarial sobre a «family» de uma empresa que nunca dava um dia de folga.",
        "cantar (depois: jargão cantado)",
        "fala queixosa de mendigos, depois hipocrisia",
    ),
    "pusillanimous": (
        "Falto de coragem, cobarde.",
        "Tímido até não ter coluna — demasiado assustado para se erguer, mesmo quando claramente importa.",
        "O silêncio pusillanimous da direção deixou o escândalo descontrolar-se.",
        "muito pequeno",
        "espírito, coragem",
    ),
    "vulpine": (
        "De raposa; astuto, ladino.",
        "Manhoso e esperto como uma raposa — vivo de mente, um pouco taimado, sempre um passo à frente.",
        "Deu um sorriso vulpine no instante em que viu a falha.",
        "raposa",
        "de ou como",
    ),
    "seriatim": (
        "Um após o outro, em sequência.",
        "Tomado estritamente um a um, por ordem — sem saltar, sem fazer dois de uma vez.",
        "O juiz abordou cada um dos doze pedidos seriatim.",
        "fila, sequência",
        "um a um",
    ),
    "parsimony": (
        "Frugalidade extrema; sovinice.",
        "Andar curto de dinheiro (ou de palavras, ou de recursos) muito para além de uma poupança razoável.",
        "A sua parsimony era lendária — reutilizava os saquinhos de chá três vezes.",
        "escassear, ser frugal",
        "estado ou prática",
    ),
    "emendation": (
        "Uma correção, sobretudo num texto.",
        "Um conserto num escrito — um retoque erudito que corrige um erro num texto velho ou importante.",
        "A nova edição inclui dezenas de emendations ao manuscrito original.",
        "fora de",
        "falha, erro",
    ),
    "abstemious": (
        "Moderado no comer e no beber.",
        "De propósito contido à mesa — nunca em excesso, sempre a deixar um pouco no prato.",
        "Os hábitos abstemious dele mantiveram-no lúcido muito depois de os pares terem abrandado.",
        "longe de",
        "bebida inebriante",
    ),
    "solecism": (
        "Um erro gramatical ou uma falta de etiqueta.",
        "Um escorregão de gramática ou de maneiras — o pequeno erro que faz encolher um picuinhas.",
        "«Between you and I» é um solecism comum que ainda faz estremecer os gramáticos.",
        "cidade cilícia conhecida pelo grego «mau»",
        "prática, maneira",
    ),
    "internecine": (
        "Relativo a um conflito interno a um grupo; mutuamente destrutivo.",
        "Rixas internas que rasgam um grupo por dentro — uma luta em que todos perdem, porque é família contra família.",
        "As rixas internecine do partido fizeram mais dano do que qualquer rival de fora.",
        "entre, no meio",
        "matar",
    ),
    "pococurante": (
        "Atitude indiferente, descuidada.",
        "Um encolher de ombros tornado personalidade — importar tão pouco o que outrora importava que nada parece já valer o esforço.",
        "A atitude pococurante dele para com a gala dos prémios surpreendeu quantos sabiam o quanto ele tinha trabalhado.",
        "pouco",
        "cuidar de",
    ),
    "imbroglio": (
        "Uma situação ou disputa confusa e enredada.",
        "Um imbróglio emaranhado, difícil de deslindar — parte mal-entendido, parte drama, tudo confusão.",
        "Todo o imbroglio do plano de mesas começou com um cartão de nome mal posto.",
        "em",
        "enredar, confundir",
    ),
    "minatory": (
        "Ameaçador, de mau presságio.",
        "Com um ar inconfundível de ameaça — um olhar ou uma carta minatory deixa bem claro que pode vir algo feio.",
        "O tom minatory da carta deixou a inquilina nervosa ainda antes de abrir o envelope.",
        "ameaçar",
        "que serve para",
    ),
    "obloquy": (
        "Crítica pública forte ou abuso verbal.",
        "Uma condenação ruidosa e pública — a crítica abrasadora que se representa diante de todos.",
        "A denunciante aguentou anos de obloquy público antes de a história lhe dar razão.",
        "contra",
        "falar",
    ),
    "paroxysm": (
        "Um rebentamento súbito e violento de emoção ou de ação.",
        "Um empurrão intenso que o cobre de golpe — um ataque de riso, de ira ou de tosse como uma onda.",
        "Acometeu-a um paroxysm de riso que não conseguia explicar a mais ninguém na sala.",
        "para além",
        "agudo, acerado",
    ),
    "adscititious": (
        "Acrescentado de fora, não inerente.",
        "Aparafusado de fora em vez de vir de origem — um extra, não um núcleo.",
        "O comentário sente-se adscititious, como colado a um texto já acabado.",
        "para, além",
        "aprovar, assumir",
    ),
    "nescience": (
        "Falta de saber, ignorância.",
        "O simples não-saber — um buraco no conhecimento, sem juízo colado por cima.",
        "Admitiu a sua nescience do vinho francês e deixou o sommelier escolher.",
        "não",
        "saber",
    ),
    "prurience": (
        "Interesse excessivo por assuntos sexuais.",
        "Uma curiosidade demasiado ansiosa, um tanto lúbrica, por tudo o que é picante — um interesse que passou o são e se tornou bisbilhoteiro.",
        "A prurience do tablóide sobre a vida privada do casal beirava o obsessivo.",
        "comichar, anelar",
        "estado de",
    ),
    "fuliginous": (
        "Fuliginoso, escuro, turvo.",
        "Escuro e fumado, como se tudo levasse uma camada fina de fuligem.",
        "Uma bruma fuliginous pairava ao entardecer sobre a vila fabril.",
        "fuligem",
        "cheio de",
    ),
    "gainsay": (
        "Negar ou contradizer.",
        "Falar contra, de frente, o que outro disse — dizer que não é assim.",
        "Ninguém ousou gainsay o relato do velho capitão sobre a tempestade.",
        "contra",
        "falar",
    ),
    "ignavia": (
        "Preguiça, ociosidade (do latim).",
        "Uma palavra latina antiga para a preguiça pura — o lastro de não querer fazer nada.",
        "Os monges pregavam contra ignavia como um dos perigos calados da alma.",
        "não",
        "ocupado, diligente",
    ),
    "escutcheon": (
        "Um escudo que mostra um brasão.",
        "O emblema em forma de escudo com as armas de uma família — a sua insígnia heráldica.",
        "O escutcheon da família continua pendurado sobre a porta da velha casa senhorial.",
        "escudo",
        "diminutivo / objeto",
    ),
    "superannuated": (
        "Antiquado, obsoleto, ou reformado por idade.",
        "Passado o bom tempo e posto de lado — demasiado fora de moda ou gasto para continuar a fazer o trabalho.",
        "A impressora superannuated foi enfim substituída após quinze anos de enguiços.",
        "para além",
        "ano",
    ),
    "succedanea": (
        "Substitutos, sobretudo em medicina.",
        "Remédios de recurso quando falta o tratamento a sério — dublês médicos, no fundo.",
        "Os médicos de guerra apoiavam-se muitas vezes em succedanea quando acabavam os medicamentos a sério.",
        "em vez de",
        "ir, ceder",
    ),
    "rodomontade": (
        "Conversa jactanciosa e fanfarrona.",
        "Fanfarronice grande e ruidosa — um falar alto da própria grandeza que é, sobretudo, ar quente.",
        "A sua rodomontade de ter salvo o projeto «single-handedly» não enganou ninguém que tivesse estado lá a sério.",
        "cavaleiro fanfarrão em Orlando Furioso",
        "ação, ostentação",
    ),
    "chicane": (
        "Usar astúcia ou engano para conseguir algo.",
        "Chegar ao objetivo com truques em vez de jogo limpo.",
        "Chicaned a entrada no negócio com um contrato cheio de letra miúda.",
        "tergiversar, enganar",
        "artimanha; depois uma curva fechada",
    ),
    "mathesis": (
        "A ciência pura ou abstrata do aprender ou do saber, muitas vezes a matemática.",
        "O aprender na forma mais pura e abstrata — a estrutura funda do saber em si, sobretudo a matemática.",
        "O filósofo sonhava com uma mathesis universal que unisse todos os campos do saber.",
        "aprender",
        "o ato de aprender",
    ),
    "pedantic": (
        "Excessivamente ocupado com regras formais ou pormenores triviais.",
        "Demasiado estrito com o miúdo — corrigir minudências técnicas que não mudam nada de fundo.",
        "Soava um pouco pedantic discutir «who» contra «whom» numa mensagem de texto.",
        "guia de crianças, preceptor",
        "que tem o modo de",
    ),
    "coruscation": (
        "Um lampejo de luz faiscante.",
        "Um relâmpago rápido e brilhante — o sol na água, ou um diamante que apanha a luz.",
        "A coruscation do candelabro espalhava luz por cada canto da sala de baile.",
        "brilhar, faiscar",
        "o ato de",
    ),
    "tyro": (
        "Um principiante, um novato.",
        "Alguém novinho num ofício ou num campo — ainda a aprender os jeitos, ainda não um perito.",
        "Até um jogador de xadrez tyro consegue ver essa asneira.",
        "recruta, novato",
        "um soldado jovem e verde",
    ),
    "execrable": (
        "Extremamente mau, detestável.",
        "Mau de um modo que merece nojo a sério — não só medíocre, mas francamente atroz.",
        "O crítico chamou à sequela execrable, e a bilheteira deu-lhe razão.",
        "amaldiçoar",
        "digno de, capaz de ser",
    ),
    "incarnadine": (
        "De cor vermelho-sangue.",
        "Um vermelho fundo e vivo — a cor do sangue fresco, famoso pelo Macbeth de Shakespeare.",
        "O pôr do sol tingiu o céu todo de um resplendor incarnadine.",
        "dentro",
        "carne (vermelho de carne)",
    ),
    "interstice": (
        "Um pequeno vão ou espaço entre coisas.",
        "O entremedio mínimo que se passa por alto — a fenda entre as tábuas, o buraco numa agenda.",
        "As ervas daninhas empurravam por cada interstice do velho caminho de tijolo.",
        "entre",
        "estar de pé",
    ),
    "animadversion": (
        "Observações críticas ou censuradoras.",
        "Comentários pungentes, de desaprovação — a crítica que soa um pouco a repreensão.",
        "As animadversions do professor ao ensaio encheram as margens de tinta vermelha.",
        "mente",
        "voltar-se para",
    ),
    "irrefragable": (
        "Impossível de refutar, inegável.",
        "Tão solidamente provado que não há argumento em contrário — o caso está fechado.",
        "A prova de ADN era irrefragable, e o julgamento terminou na hora.",
        "não",
        "opor-se, resistir",
    ),
    "involution": (
        "Complexidade, enredo; também um recolher para dentro.",
        "Uma complexidade emaranhada, dobrada sobre si — coisas tão apertadas que custa despegá-las.",
        "A involution da trama deixou metade da plateia a deslindar depois dos créditos.",
        "dentro, para dentro",
        "enrolar, voltar",
    ),
    "dint": (
        "Força ou esforço, como em «by dint of».",
        "Pura força ou empenho — sobrevive sobretudo na locução «by dint of».",
        "Passou no exame by dint of uma prática teimosa, pura e simples.",
        "um golpe, um envite",
        "à força de",
    ),
    "mortised": (
        "Unido com encaixe de caixa e espiga; encaixado com firmeza.",
        "Travado à maneira antiga do carpinteiro — uma peça entra justa num vão cortado para ela.",
        "As vigas do velho celeiro estavam mortised entre si sem um único prego.",
        "uma caixa, um vão",
        "uma dentada, um aperto",
    ),
    "apposite": (
        "Altamente pertinente, adequado.",
        "Exatamente o que o momento pedia — um comentário, uma citação ou um exemplo que acerta em cheio.",
        "A observação apposite dela resumiu todo o debate numa frase.",
        "para",
        "colocar",
    ),
    "lambent": (
        "De um resplendor suave ou vacilante; também, um engenho leve.",
        "Um brilho manso em vez de um incêndio — uma chama que brinca, ou um engenho brincalhão mais do que cortante.",
        "A luz das velas lançava um resplendor lambent sobre a velha sala de jantar.",
        "lamber",
        "fazendo (luz que «lambe»)",
    ),
    "anchorite": (
        "Um recluso religioso que vive em solidão.",
        "Alguém que se retira do mundo por completo para viver sozinho em oração e reflexão.",
        "O anchorite viveu mais de trinta anos numa cela pequena adossada à igreja.",
        "para trás, longe",
        "retirar-se",
    ),
    "slake": (
        "Saciar a sede; apagar.",
        "Satisfazer de todo um anseio — quase sempre a sede, mas no figurado qualquer necessidade funda.",
        "Um copo de água fria slaked a sede dele após a longa caminhada.",
        "frouxo, solto",
        "afrouxar, aliviar",
    ),
    "acicular": (
        "Em forma de agulha.",
        "Comprido, fino e aguçado como uma agulha — a forma de uma agulha de pinheiro ou de um cristalito agudo.",
        "Os pinheiros reconhecem-se facilmente pelas folhas acicular.",
        "agulha",
        "pequeno",
    ),
    "effete": (
        "Esgotado de vitalidade, fraco, demasiado refinado.",
        "Gasto e mole — tendo perdido o vigor primeiro à força de conforto ou de requinte.",
        "Os críticos chamaram effete à revista outrora ousada, sombra dos seus anos bravos.",
        "fora",
        "fecundo, que deu fruto",
    ),
    "appurtenance": (
        "Um acessório ou um pequeno elemento ou direito anexo.",
        "Um extra pequeno unido a algo maior — os acessórios e anexos que vão com o principal.",
        "O arrendamento incluía a garagem e todas as suas appurtenances.",
        "para",
        "pertencer",
    ),
    "gloze": (
        "Passar por cima ou minimizar uma falta.",
        "Alisar um erro com palavras macias, para que soe mais pequeno do que é.",
        "Tentou gloze over o prazo perdido com um vago discurso de «unforeseen challenges».",
        "uma glosa, uma explicação",
        "comentar — depois alisar",
    ),
    "incipient": (
        "Numa fase precoce, que mal começa.",
        "Apenas a começar a mostrar-se — o primeiro estádio, quase invisível, de algo maior.",
        "Os médicos apanharam os sinais incipient da doença antes de se espalhar.",
        "sobre, para dentro",
        "tomar (empreender, começar)",
    ),
    "afflatus": (
        "Inspiração criativa, sobretudo divina.",
        "Um empurrão súbito de inspiração maior do que si — como se a ideia lhe tivesse sido soprada de outra parte.",
        "O poeta contou que toda a peça chegou num burst of afflatus às três da manhã.",
        "para, sobre",
        "soprar (um sopro sobre)",
    ),
}
