# German overlays: (definition, friendly, exampleGloss, root1, root2)
WORDS = {
    "edulcorate": (
        "Süßen oder reinigen; einem Ding die Schärfe nehmen.",
        "Den Stachel oder die Bitterkeit herausnehmen — wörtlich süßer machen, oder bildlich einen harten Gedanken so weichspülen, dass er leichter eingeht.",
        "Der Redakteur milderte die harte Rezension, bevor sie in den Druck ging.",
        "hinaus, gründlich",
        "süß",
    ),
    "pietistic": (
        "Übertrieben oder gekünstelt religiös oder fromm.",
        "Beschreibt jemanden, dessen Frömmigkeit nach Show riecht: mehr Aufführung als echter Glaube.",
        "Sein pietistisches Seufzen während der Predigt störte den Rest der Bank.",
        "Frömmigkeit, Pflichtgefühl",
        "den Charakter habend von",
    ),
    "amphiboly": (
        "Mehrdeutigkeit durch den Satzbau — ein Satz, der auf zwei Arten lesbar ist.",
        "Ein Satz, der grammatisch in Ordnung ist, sich aber auf zwei völlig verschiedene Weisen lesen lässt, wie „Visiting relatives can be tiring.“",
        "„Visiting relatives can be tiring“ ist eine klassische Amphibolie — sind die Verwandten anstrengend, oder ist es der Besuch?",
        "beide, auf beiden Seiten",
        "werfen",
    ),
    "trenchant": (
        "Scharf, treffend, geradewegs zum Punkt.",
        "Schneidet durch den Ballast — ein scharfer Kommentar oder Geist trifft rasch den Kern, ohne überflüssige Worte.",
        "Ihre schneidende Kritik ließ den Plotlöchern des Films keinen Unterschlupf.",
        "schneiden",
        "tuend, die Eigenschaft habend",
    ),
    "inchoative": (
        "Eben erst beginnend; in einem frühen oder rudimentären Stadium.",
        "Noch in den ersten Augenblicken — ein Plan, Gefühl oder Prozess, der gerade erst Gestalt annimmt.",
        "Die beginnenden Phasen des Vertrags waren vielversprechend, doch viele Einzelheiten blieben offen.",
        "beginnen, anfangen",
        "neigend zu",
    ),
    "panegyric": (
        "Eine förmliche Rede oder Schrift, die jemanden hoch preist.",
        "Ein voller, förmlicher Lobpreis — denk an eine leuchtende Grabrede oder eine Ansprache, die jemandes Taten von den Dächern singt.",
        "Die scheidende Professorin wurde mit einer Lobrede ihrer nächsten Studierenden verabschiedet.",
        "all, ganz",
        "Versammlung, Zusammenkunft",
    ),
    "ontic": (
        "Das wirkliche Dasein betreffend, im Gegensatz zur abstrakten Theorie.",
        "Über die Dinge, wie sie wirklich sind — nicht nur als Ideen oder Theorien über sie.",
        "Philosophen streiten, ob Zahlen irgendeinen ontischen Status haben oder nur in unserem Kopf existieren.",
        "Sein, das was existiert",
        "bezüglich",
    ),
    "fructify": (
        "Frucht tragen oder ertragreich werden.",
        "Endlich aufgehen — eine Mühe, Idee oder Anlage, die Frucht trägt, ist vom Samen zu etwas Nützlichem geworden.",
        "Jahre stiller Forschung trugen endlich Frucht in einem funktionierenden Impfstoff.",
        "Frucht",
        "machen, bewirken",
    ),
    "proleptical": (
        "Etwas vorwegnehmen oder so darstellen, als sei es schon geschehen.",
        "Auf literarische Weise voreilen — ein künftiges Ereignis beschreiben, als wäre es schon fertig, damit der Punkt härter trifft.",
        "Des Generals vorwegnehmender Toast auf „den Sieg“ wurde eine volle Woche vor der Schlacht ausgebracht.",
        "vorher",
        "nehmen, ergreifen",
    ),
    "pneumatic": (
        "Mit Luftdruck betrieben; auch Atem oder Geist betreffend.",
        "Meist: mit Druckluft betrieben — ein Bohrer, eine Busbremse — aber dieselbe griechische Wurzel spricht auch von Atem und Geist.",
        "Die pneumatischen Bremsen zischten, als der Bus am Bordstein hielt.",
        "Wind, Atem, Geist",
        "zugehörig",
    ),
    "cataphatic": (
        "Gott oder das Göttliche durch bejahende Aussagen beschreiben — das Gegenteil von apophatisch.",
        "Von Gott sprechen, indem man sagt, was Gott ist — „Gott ist Liebe“, „Gott ist gerecht“ — statt nur, was Gott nicht ist.",
        "Kataphatische Theologie spricht zuversichtlich von Gott als liebend, gerecht und barmherzig.",
        "hinab, gemäß",
        "sprechen, sagen",
    ),
    "fiducial": (
        "Auf Vertrauen oder Glauben gegründet; auch: ein fester Bezugspunkt.",
        "Etwas, das man auf Treu und Glauben nimmt und dann als Anker nutzt — eine Bezugsmarke ist der feste Punkt, an dem alles andere gemessen wird.",
        "Vermesser setzten eine feste Bezugsmarke ins Gestein, bevor sie den Ort kartierten.",
        "vertrauen",
        "Vertrauen, Zuversicht",
    ),
    "theodicy": (
        "Eine Verteidigung der Güte Gottes angesichts des Bösen.",
        "Der uralte Versuch, zu antworten: Wenn Gott gut ist, warum gibt es dann Böses? — ohne eine der beiden Behauptungen aufzugeben.",
        "Ihre Arbeit untersuchte die Theodizee durch die Linse des Buches Hiob.",
        "Gott",
        "Gerechtigkeit",
    ),
    "circumincession": (
        "Gegenseitiges Innewohnen — ein theologischer Begriff dafür, wie die Personen der Dreifaltigkeit ineinander existieren.",
        "Ein Theologie-Wort für ein Drei-in-einem-Beieinander, so vollständig, dass jeder Teil die anderen enthält und von ihnen enthalten wird.",
        "Die Lehre der Circumincessio versucht zu erklären, wie Vater, Sohn und Geist unterschieden und doch untrennbar sind.",
        "ringsum",
        "gehen, wandeln",
    ),
    "redound": (
        "Eine Folge haben, die jemandem zugutekommt oder auf ihn zurückfällt.",
        "Wenn Ruhm (oder Tadel) zum Verantwortlichen zurückprallt — gute Taten, die deinem Ruf zugutekommen, kehren als Lohn wieder.",
        "Der Erfolg der Mannschaft wird dem stillen, fleißigen Trainer zur Ehre gereichen.",
        "zurück, wiederum",
        "Welle",
    ),
    "ineluctable": (
        "Nicht zu vermeiden oder zu entkommen.",
        "Es kommt, was du auch tust — aus einem unausweichlichen Ausgang windest du dich nicht heraus.",
        "Das Alter kommt für alle; es ist schlicht unausweichlich.",
        "nicht",
        "sich herauswinden",
    ),
    "periphrastic": (
        "Weitschweifige, wortreiche Formulierung statt einer direkten Form.",
        "Der lange Weg mit Worten — in einem ganzen Satz sagen, was ein Wort decken würde.",
        "Seine umständlichen E-Mails hätten in einer Zeile sagen können, was drei Absätze brauchte.",
        "herum",
        "erklären, erzählen",
    ),
    "hebetude": (
        "Geistige Stumpfheit oder Trägheit.",
        "Dieser neblige, schleppende Geisteszustand, in dem Denken sich anfühlt wie Waten durch Sirup.",
        "Eine Welle von Stumpfsinn traf die Klasse direkt nach dem Mittagessen.",
        "stumpf, dumpf",
        "Zustand oder Beschaffenheit",
    ),
    "unpropitious": (
        "Ungünstig; von schlechter Vorbedeutung.",
        "Ein schlechtes Zeichen — Umstände oder Timing, die schon gegen dich arbeiten, bevor du angefangen hast.",
        "Grauer Himmel und eine tote Autobatterie waren ein ungünstiger Start in die Reise.",
        "nicht",
        "günstig, gnädig",
    ),
    "fricaseed": (
        "Fleisch, geschmort oder gedünstet in Sauce — eigentlich „fricasseed“ geschrieben.",
        "Ein gemütlicher, alter Kochbegriff für Fleisch, das klein geschnitten und langsam in der eigenen Sauce zart geschmort wird.",
        "Großmutters frikassiertes Huhn war der Höhepunkt jedes Sonntagsessens.",
        "braten, backen",
        "brechen (in Stücke)",
    ),
    "ersatz": (
        "Ein künstlicher oder minderwertiger Ersatz.",
        "Eine Imitation, die für das Echte einspringt — sie tut den Job, aber jeder merkt, dass es nicht das Original ist.",
        "In Kriegszeiten begnügten sich Käufer mit Ersatzkaffee aus gerösteter Zichorie.",
        "aus, Ersatzpräfix",
        "setzen, stellen",
    ),
    "reify": (
        "Eine abstrakte Idee behandeln, als wäre sie ein greifbares Ding.",
        "Eine Idee fest und wirklich erscheinen lassen — etwas Unscharfes wie „den Markt“ zu einem Ding machen, auf das man zeigen kann.",
        "Den „Geist“ einer Nation zu einem Wesen zu erklären verdinglicht etwas, das in Wahrheit Millionen einzelner Entscheidungen ist.",
        "Ding",
        "machen",
    ),
    "eluded": (
        "Geschickt entkommen oder ausgewichen.",
        "Sauber entwischt — etwas umgangen, oft klug oder knapp, ob Fang, Frage oder Antwort.",
        "Die Antwort entzog sich ihr stundenlang, bis sie unter der Dusche plötzlich klickte.",
        "hinaus, weg",
        "spielen",
    ),
    "aporetic": (
        "Zweifel, Ratlosigkeit oder einen ungelösten Widerspruch ausdrückend.",
        "An einem echten gedanklichen Sackgasse stehend — nicht aus Faulheit, sondern weil die Frage selbst keine nette Antwort zulässt.",
        "Sokrates endete seine Dialoge oft auf einem aporetischen Ton, mit mehr Fragen als Antworten.",
        "ohne",
        "Durchgang, Weg",
    ),
    "metonymy": (
        "Eine Stilfigur, die etwas mit einem zugehörigen Wort benennt, etwa „die Krone“ für den Herrscher.",
        "Ein verwandtes Wort für die Sache selbst einsetzen — „Wall Street“ sagen, wenn man die Börse meint.",
        "„Wall Street had a rough day“ ist Metonymie — gemeint ist eigentlich der Aktienmarkt.",
        "Wechsel, danach",
        "Name",
    ),
    "deracinate": (
        "Entwurzeln; aus einer natürlichen Umgebung reißen.",
        "Etwas (oder jemanden) mit der Wurzel herausziehen, weg von Ort oder Kultur, zu der es gehört.",
        "Krieg entwurzelte eine ganze Generation und zerstreute Familien über Grenzen hinweg.",
        "weg, ab",
        "Wurzel",
    ),
    "euphonious": (
        "Wohlklingend.",
        "Einfach schön zu hören — ein wohlklingendes Wort oder ein wohlklingender Satz gleitet weich, fast musikalisch, ins Ohr.",
        "„Murmuring brook“ ist eine wohlklingende kleine Wendung, weich und leicht zu sagen.",
        "gut, wohl",
        "Klang, Stimme",
    ),
    "putative": (
        "Allgemein angenommen oder vermutet.",
        "Weithin für wahr gehalten, auch wenn es nicht bewiesen ist — die vermeintliche oder mutmaßliche Fassung von etwas.",
        "Der mutmaßliche Verfasser des Briefes stellte sich später als völliger Fremder heraus.",
        "denken, erachten",
        "die Natur habend von",
    ),
    "neologism": (
        "Ein neu geprägtes Wort oder eine neue Wendung.",
        "Ein brandneues Wort — frisch erfunden, noch kaum im Wörterbuch.",
        "„Doomscrolling“ begann als Neologismus und wurde rasch Alltagsslang.",
        "neu",
        "Wort, Rede",
    ),
    "splenetic": (
        "Zornig oder schlechtgelaunt.",
        "In übler, reizbarer Stimmung — schnell scharf, wie man früher glaubte, die Milz steuere das Temperament.",
        "Er feuerte binnen Sekunden eine gallige Antwort auf die E-Mail ab.",
        "Milz (Sitz des Zorns)",
        "ergriffen von",
    ),
    "sententious": (
        "Geneigt, pompös oder gekünstelt zu moralisieren.",
        "Teilt gern kleine Lebenslehren aus, als wäre jeder Satz ein Glückskeks.",
        "Sein moralisierender Toast über „die wahre Bedeutung von Freundschaft“ ließ alle auf die Uhr schauen.",
        "Meinung, Sinnspruch",
        "voll von",
    ),
    "garrulous": (
        "Übermäßig redselig, besonders über Belangloses.",
        "Hört einfach nicht auf zu plaudern — redet über Kleinkram, lange nachdem alle anderen nichts mehr zu sagen haben.",
        "Der geschwätzige Taxifahrer erzählte uns seine ganze Lebensgeschichte, bevor wir den Flughafen verlassen hatten.",
        "plaudern, schwatzen",
        "neigend zu",
    ),
    "fatuity": (
        "Torheit, Albernheit.",
        "Schlichte Dummheit — eine Bemerkung oder ein Plan so albern, dass sie kaum eine ernste Antwort verdient.",
        "Die schiere Torheit des Plans wurde klar, sobald sie ihn ausprobierten.",
        "töricht, albern",
        "Zustand des Seins",
    ),
    "peroration": (
        "Der schließende Teil einer Rede, oft zusammenfassend.",
        "Der große Schluss einer Rede — der Abschnitt, in dem der Sprecher alles bündelt und den Punkt nach Hause bringt.",
        "Bei der Schlussrede war die Hälfte des Publikums auf den Beinen.",
        "durch, bis zum Ende",
        "sprechen, plädieren",
    ),
    "tautology": (
        "Überflüssige Wiederholung derselben Idee in anderen Worten.",
        "Dasselbe zweimal sagen, ohne etwas Neues hinzuzufügen, wie „kostenloses Geschenk“ oder „it is what it is.“",
        "„It is what it is“ ist eine beliebte Tautologie von Leuten, die eine echte Erklärung meiden.",
        "dasselbe",
        "Wort, Rede",
    ),
    "laconism": (
        "Der Gebrauch sehr weniger Worte; knappe Rede.",
        "Viel mit sehr wenig sagen — die Kunst der kurzen, barschen Antwort, benannt nach den notorisch knappen Spartanern Lakoniens.",
        "„Molon labe“ — „kommt und holt sie euch“ — ist das berühmteste Stück Lakonismus der Geschichte.",
        "ein Spartaner Lakoniens",
        "Übung, Art",
    ),
    "pabulum": (
        "Fade, übervereinfachte Ideen; ursprünglich: fade Speise oder Brei.",
        "Dünnes, verwässertes Denken — Inhalt so vereinfacht und sicher, dass er für den Geist keinen Nährwert hat.",
        "Die Rede des Politikers war vor allem Geschwafel: vage Versprechen, an denen nichts festzumachen war.",
        "nähren",
        "Mittel oder Werkzeug",
    ),
    "soporific": (
        "Schlaf oder Schläfrigkeit erzeugend.",
        "So langweilig — oder so wörtlich beruhigend — dass einen der Schlaf überkommt. Denk an warme Milch oder eine dreistündige Haushaltsdebatte.",
        "Der einschläfernde Singsang der Vorlesung ließ die Hälfte des Saals um offene Augen kämpfen.",
        "tiefer Schlaf",
        "machend, bewirkend",
    ),
    "unctuous": (
        "Übermäßig schmeichelnd oder ölig im Auftreten.",
        "So glatt charmant, dass es schlüpfrig wirkt — Schmeichelei so dick aufgetragen, dass man das Fett fast spürt.",
        "Der salbungsvolle Verkäufer lobte vor jedem Zusatzverkauf meinen „ausgezeichneten Geschmack“.",
        "salben, ölen",
        "voll von",
    ),
    "captious": (
        "Schnell im Tadeln, überkritisch bei Kleinigkeiten.",
        "Beckmesserisch bis zum Exzess — der Typ, der an allem etwas findet, auch wenn es nichts ausmacht.",
        "Seine kleinlichen Anmerkungen zum Bericht drehten sich nur um Kommasetzung.",
        "ergreifen, nehmen",
        "eine Falle, ein Sophisma",
    ),
    "torpid": (
        "Träge, geistig oder körperlich untätig.",
        "Langsam und halbbewusst, wie ein Bär im Winterschlaf — kaum Bewegung, kaum Gedanke.",
        "Das Büro versank in der schweren Augusthitze in Trägheit.",
        "taub sein, träge sein",
        "in einem Zustand von",
    ),
    "seneschal": (
        "Ein Verwalter oder Beamter, der einen mittelalterlichen Haushalt führte.",
        "Die mittelalterliche Fassung eines Haushofmeisters — der vertraute Beamte, der Haus und Gut eines Herrn im Alltag führte.",
        "Der Seneschall der Burg regelte alles, von den Erntebüchern bis zur Gästeliste.",
        "alt, senior",
        "Diener",
    ),
    "expatiate": (
        "Ausführlich über ein Thema sprechen oder schreiben.",
        "Richtig in Fahrt kommen — endlos reden oder schreiben und das Thema von allen Seiten beleuchten.",
        "Frag ihn nach Oldtimern, und er wird sich eine volle Stunde darüber auslassen.",
        "hinaus",
        "Raum",
    ),
    "nugatory": (
        "Ohne Wert, geringfügig; auch ungültig oder wirkungslos.",
        "So gut wie nichts wert — eine nichtige Klausel im Vertrag tut in der Praxis nichts.",
        "Das Gericht erklärte die alte Satzung für nichtig, weil sie nie durchgesetzt worden war.",
        "Nichtigkeiten, Unsinn",
        "zugehörig zu",
    ),
    "sagacity": (
        "Weisheit, kluges Urteil.",
        "Scharfe, praktische Klugheit — das gute Urteil, das aus Erfahrung kommt, nicht nur aus Büchern.",
        "Der Scharfsinn des alten Kapitäns bewahrte die Mannschaft mehr als einmal vor Unheil.",
        "feinnasig, scharfsinnig",
        "Beschaffenheit von",
    ),
    "canaille": (
        "Der gemeine Pöbel oder die Masse, verächtlich gebraucht.",
        "Ein snohaftes, abfälliges Wort für gewöhnliche Leute, als wären sie ein Rudel Hunde.",
        "Der Graf rümpfte die Nase über den Pöbel vor den Palasttoren.",
        "Hund",
        "Kollektiv, Rudel",
    ),
    "contumely": (
        "Freche, demütigende Behandlung oder Sprache.",
        "Grausame, höhnische Behandlung, die demütigen soll — die Beleidigung, die treffen will.",
        "Er ertrug Jahre von Schmähungen der Kritiker, bevor sein Werk endlich anerkannt wurde.",
        "mit, gründlich",
        "schwellen (vor Stolz)",
    ),
    "askance": (
        "Mit Argwohn oder Missbilligung; ein Seitenblick.",
        "Der schiefe Blick, den du etwas schenkst, dem du nicht ganz traust — ein Blick voll Zweifel.",
        "Die Lehrerin sah misstrauisch auf die verdächtig ordentliche Hausaufgabe.",
        "an, zu",
        "Schräge, Voreingenommenheit",
    ),
    "clodpate": (
        "Ein Dummkopf; ein Holzkopf.",
        "Ein altmodisches, fast zärtliches Schimpfwort für jemanden, der schwer von Begriff ist — ein Holzkopf.",
        "„Du Dummkopf,“ lachte sie, „du hältst die Karte die ganze Zeit verkehrt herum.“",
        "Erdklumpen",
        "Kopf",
    ),
    "actuate": (
        "In Bewegung oder Handlung versetzen; motivieren.",
        "Der Funke sein, der etwas in Gang setzt — ob eine Maschine anspringt oder ein Mensch endlich nach einer Idee handelt.",
        "Die Angst, den Vertrag zu verlieren, trieb das ganze Team in ein Wochenende Überstunden.",
        "ein Tun, ein Treiben",
        "treiben, tun",
    ),
    "peculation": (
        "Unterschlagung anvertrauter Gelder.",
        "Still Geld stehlen, das man hüten sollte — Unterschlagung im alten Gewand.",
        "Die Unterschlagung des Schatzmeisters blieb fast ein Jahrzehnt unbemerkt.",
        "Privateigentum",
        "Vieh, Reichtum",
    ),
    "demi-monde": (
        "Eine Gruppe am Rand der achtbaren Gesellschaft.",
        "Die glamouröse, aber zwielichtige Halbwelt — Leute, die knapp außerhalb der Regeln der Wohlanständigkeit leben.",
        "Der Roman folgt einer Sängerin in der Halbwelt der Cabarets der 1920er.",
        "halb",
        "Welt, Gesellschaft",
    ),
    "extant": (
        "Noch bestehend; nicht ausgestorben oder zerstört.",
        "Heute noch da — für alte Dinge (Handschriften, Arten, Bauten), die überlebt haben.",
        "Nur drei erhaltene Exemplare des Erstdrucks sind bekannt.",
        "hinaus",
        "stehen",
    ),
    "perfidy": (
        "Hinterlist; Vertrauensbruch.",
        "Tiefer, bewusster Verrat — ein Vertrauen brechen, das jemand zu Recht von dir erwartete.",
        "Der General verzieh die Treulosigkeit seines alten Freundes am Verhandlungstisch nie.",
        "durch, gegen",
        "Glaube, Vertrauen",
    ),
    "patois": (
        "Ein Regionaldialekt, besonders ein nicht standardsprachlicher.",
        "Die eigene, lokale Art, wie man in einer Gegend spricht — voller Wörter und Rhythmen, die ein Außenstehender nicht mitbekommt.",
        "Ihre Großmutter sprach bei Familientreffen noch immer die Mundart der Insel.",
        "derbe Rede, Dialekt",
        "Pfote — ungelenkes Sprechen",
    ),
    "prerogative": (
        "Ein besonderes Recht einer Person oder Gruppe.",
        "Ein Vorrecht, das dir allein zusteht — ein Recht, das mit Rolle, Stellung oder Rang kommt.",
        "Das Ferienziel der Familie zu wählen ist Opas Vorrecht, und jeder weiß das.",
        "vorher",
        "fragen, abstimmen",
    ),
    "hardihood": (
        "Kühnheit, Dreistigkeit; auch Zähigkeit oder Ausdauer.",
        "Raue, mutige Widerstandskraft — der Nerv voranzugehen und die Härte, durchzuhalten, sobald man unterwegs ist.",
        "Es brauchte echte Unerschrockenheit, den Pass im Schneesturm ohne Karte zu überqueren.",
        "kühn, zäh",
        "Zustand, Lage",
    ),
    "effloresce": (
        "Aufblühen; auch: sich entfalten oder allmählich erscheinen.",
        "Zur vollen Entfaltung aufblühen — wie eine Blüte, die sich öffnet, oder eine Idee, die endlich zu sich kommt.",
        "Ihr stilles Malertalent erblühte, sobald sie ein eigenes Atelier hatte.",
        "hinaus",
        "zu blühen beginnen",
    ),
    "plumb-line": (
        "Eine beschwerte Schnur zur Bestimmung der Senkrechten; bildlich: ein Maßstab.",
        "Ein Gewicht an einer Schnur, das senkrecht hängt, um zu prüfen, ob etwas wirklich lotrecht ist — und darüber hinaus jeder feste Maßstab, an dem du alles andere misst.",
        "Er nahm die Ehrlichkeit seines Großvaters als eine Art Senkblei für jede Entscheidung.",
        "Blei",
        "Schnur, Maß",
    ),
    "fain": (
        "Gerne, willig (archaisch).",
        "Eine altmodische Art, „gerne“ oder „mit Vergnügen“ zu sagen — wer etwas „fain“ tut, tut es herzlich gern.",
        "„Ich würde nur zu gern eine Weile hier rasten,“ seufzte der Reisende.",
        "froh, freudig",
        "gerne, willig",
    ),
    "opprobrium": (
        "Harsche öffentliche Kritik oder Schande.",
        "Öffentliche Schande, die jemandem groß und sichtbar angehängt wird — die Schmach weiter Ablehnung.",
        "Der Skandal brachte öffentliche Schmach über die ganze Firma.",
        "gegen",
        "Schande, Vorwurf",
    ),
    "mordant": (
        "Scharf sarkastisch, beißend in Witz oder Kritik.",
        "Witz mit echten Zähnen — ein beißender Kommentar sticht gerade, weil er so treffsicher zielt.",
        "Ihre bissigen Filmkritiken fürchteten Regisseure und liebten Leser.",
        "beißen",
        "beißend, tuend",
    ),
    "pronunciamento": (
        "Eine förmliche Proklamation, oft politisch oder militärisch.",
        "Eine große, offizielle Ansage — meist eine, die eine neue Regierung, einen Aufstand oder ein großes Dekret verkündet.",
        "Das Manifest des Generals verkündete bei Tagesanbruch die neue Regierung.",
        "hervor",
        "ankündigen",
    ),
    "sciolist": (
        "Jemand mit oberflächlichem Wissen, der den Experten spielt.",
        "Jemand, der über die Oberfläche eines Themas gestreift ist und dann redet, als hätte er das Lehrbuch geschrieben.",
        "Der Halbgebildete der Dinnerparty korrigierte selbstbewusst den echten Astrophysiker am Tisch.",
        "wissen",
        "Diminutiv — ein Kleinwisser",
    ),
    "dotage": (
        "Nachlassen der geistigen Kräfte im Alter.",
        "Die neblige, vergessliche späte Altersspanne, in der die Schärfe des Geistes nachlässt.",
        "In seinem Greisenalter erzählte er bei jedem Besuch dieselben drei Geschichten, jedes Mal als wären sie neu.",
        "faseln, töricht sein",
        "Zustand oder Ergebnis",
    ),
    "lee-side": (
        "Die windabgewandte, geschützte Seite.",
        "Die stille, geschützte Seite von etwas — Hügel, Schiff, Mauer — wo der Wind dich kaum erreicht.",
        "Die Wanderer schlugen ihr Zelt auf der Leeseite des Kamms auf, um den Böen zu entgehen.",
        "Schutz, Geborgenheit",
        "Flanke, Seite",
    ),
    "parry": (
        "Einen Schlag, eine Frage oder ein Argument abwehren.",
        "Etwas geschmeidig wegschlagen — einen Schwerthieb, eine heikle Frage, einen Vorwurf — ohne eine Sekunde zu stocken.",
        "Sie parierte die knifflige Frage des Reporters mit einem leichten Scherz.",
        "abwehren",
        "bereiten, verteidigen",
    ),
    "mephitic": (
        "Übelriechend, giftig.",
        "Stinkend auf eine fast giftige Weise — ein Gestank so schlimm, dass Atmen gefährlich scheint.",
        "Ein giftiger Gestank stieg bei Sonnenuntergang aus dem Sumpf.",
        "schädlicher Dunst",
        "die Natur habend von",
    ),
    "sybarite": (
        "Ein Mensch, der dem Luxus und dem Vergnügen ergeben ist.",
        "Jemand, der für Komfort und Genuss lebt — feines Essen, weiche Betten, leichtes Leben — benannt nach der griechischen Stadt Sybaris, berühmt für ihr Übermaß.",
        "Ein wahrer Sybarit, er lehnte jedes Hotelzimmer ohne Badewanne ab.",
        "antike griechische Stadt, berühmt für Luxus",
        "Bewohner von",
    ),
    "prescind": (
        "Absichtlich einen Teil von etwas beiseite setzen oder ignorieren.",
        "Im Kopf ein Stück des Puzzles bewusst zur Seite legen, damit du sauber auf den Rest schauen kannst.",
        "Lass uns für einen Moment von den Kosten absehen und nur fragen, ob der Plan überhaupt funktioniert.",
        "vorher, weg",
        "schneiden",
    ),
    "excoriate": (
        "Hart kritisieren; auch: die Haut abziehen.",
        "Jemanden mit scharfer Kritik zerlegen — verbal, als zöge man ihm die Haut ab.",
        "Die Kritiker verrissen die Fortsetzung, weil sie alles verriet, was Fans am Original liebten.",
        "ab",
        "Haut, Fell",
    ),
    "adduce": (
        "Als Beweis oder Beleg anführen.",
        "Eine Tatsache oder ein Beispiel vorbringen, um den Punkt zu stützen — das, worauf du zeigst, wenn jemand nach Beweis fragt.",
        "Die Anwältin führte drei Zeugen zur Stützung des Alibis ihrer Mandantin an.",
        "zu, hin",
        "führen",
    ),
    "peregrinations": (
        "Reisen oder Wanderungen, besonders lange oder ausgedehnte.",
        "Lange, schweifende Fahrten — das ausgedehnte Umherziehen, das einen lange fern der Heimat hält.",
        "Seine Irrfahrten über drei Kontinente füllten ein ganzes Regal mit Reisetagebüchern.",
        "durch",
        "Feld, Land (peregrinus: Fremder)",
    ),
    "mendicant": (
        "Ein Bettler oder jemand, der von Almosen lebt.",
        "Jemand, der von erbetener Wohltätigkeit lebt — historisch auch Mönche, die Armut gelobten und von Gaben lebten.",
        "Die Bettelbrüder besaßen nichts und lebten ganz von der Güte der Dorfbewohner.",
        "betteln",
        "Bettler",
    ),
    "munificent": (
        "Äußerst großzügig.",
        "Großzügig im großen, fast theatralischen Maßstab — das Geschenk, bei dem die Leute kurz die Luft anhalten.",
        "Die großzügige Spende finanzierte den ganzen neuen Flügel der Bibliothek.",
        "Gabe, Dienst",
        "machend, gebend",
    ),
    "inanition": (
        "Erschöpfung durch Mangel an Nahrung; auch ein Mangel an Lebenskraft.",
        "Ein schwacher, ausgelaugter Zustand, weil nichts nährt — wörtlich vor Hunger, oder bildlich, weil nichts mehr zum Laufen da ist.",
        "Am Ende der Belagerung waren die Soldaten nahe der Entkräftung.",
        "leer, nichtig",
        "die Tat oder das Ergebnis von",
    ),
    "vituperation": (
        "Bittere, schmähende Kritik.",
        "Kritik, die das Faire längst hinter sich gelassen hat und zur wütenden, bitteren Tirade geworden ist.",
        "Die Online-Kommentare lösten sich binnen Minuten in reine Beschimpfungen auf.",
        "Fehler, Makel",
        "bereiten, liefern",
    ),
    "inimical": (
        "Feindselig, schädlich in der Wirkung.",
        "Gegen dich wirkend, auch still — Umstände oder Haltungen, die deinen Interessen nicht freundlich gesinnt sind.",
        "Die neue Politik war kleinen Betrieben abträglich, auch wenn das nicht die Absicht war.",
        "nicht",
        "Freund",
    ),
    "invidious": (
        "Geeignet, Groll oder Unmut zu wecken, oft durch unfaire Vergleiche.",
        "Garantiert, dass sich jemand gekränkt fühlt — meist weil Menschen oder Dinge ungerecht gegeneinander gestellt werden.",
        "Geschwister nach „wen Mama am liebsten hat“ zu rangieren ist ein gehässiges Spiel, das niemand spielen sollte.",
        "Neid",
        "anblicken (mit bösem Willen)",
    ),
    "subaltern": (
        "Eine Person niederen Ranges oder Status; ein Untergebener.",
        "Jemand weiter unten in der Befehlskette oder auf der sozialen Leiter — ein Junior unter jemandem mit mehr Macht.",
        "Als junger Untergebener nahm er lange Befehle entgegen, bevor er je welche gab.",
        "unter",
        "alternativ, anderer",
    ),
    "execrate": (
        "Starken Hass empfinden oder äußern.",
        "Etwas so verabscheuen, dass man es laut verflucht — reine, stimmhafte Abscheu.",
        "Die Dorfbewohner verfluchten den Steuereintreiber jedes Mal, wenn sein Karren durch den Ort rollte.",
        "heraus",
        "heilig (aus dem Heiligen verfluchen)",
    ),
    "integument": (
        "Eine natürliche äußere Hülle, wie Haut oder Schale.",
        "Die schützende Verpackung der Natur — Haut, Schale, Hülse oder Rinde, was ein Lebewesen bedeckt und schützt.",
        "Der Panzer einer Schildkröte ist eine bemerkenswert zähe Hülle.",
        "auf, über",
        "bedecken",
    ),
    "ingenuous": (
        "Unschuldig, naiv, von kindlicher Schlichtheit; das Gegenteil von hinterhältig.",
        "Offen vertrauend und ein wenig naiv, ohne Hintergedanken — leicht zu verwechseln mit „ingenious“, das klug bedeutet.",
        "Ihre arglose Frage — „warum sollte jemand darüber lügen?“ — zeigte, wie wenig Hinterlist sie hatte.",
        "in, einheimisch",
        "zeugen (freigeboren, aufrichtig)",
    ),
    "pedantry": (
        "Übertriebene Sorge um Kleinigkeiten oder Regeln.",
        "In den kleinen Regeln verloren gehen und das große Bild verpassen — am Kleingedruckten kleben, das sonst niemanden kümmert.",
        "Seine Pedanterie um Oxford-Kommas entgleiste die ganze Sitzung.",
        "Kinderlehrer",
        "Übung oder Eigenschaft",
    ),
    "perscrutation": (
        "Eine gründliche, sorgfältige Prüfung.",
        "Ein tiefer Blick, der keinen Stein auf dem anderen lässt — jedes Detail mit echter Sorgfalt durchgehen.",
        "Erst nach einer sorgfältigen Durchleuchtung der Bücher tauchte die Unstimmigkeit auf.",
        "durch, gründlich",
        "suchen, prüfen",
    ),
    "demur": (
        "Einwände erheben; Zögern zeigen.",
        "Höflich widersprechen oder zögern, statt sofort mitzugehen — ein leises „warte mal“.",
        "Als man sie bat, ohne zu lesen zu unterschreiben, erhob sie Einspruch.",
        "von, weg",
        "zögern",
    ),
    "specious": (
        "Oberflächlich plausibel, aber tatsächlich falsch.",
        "Klingt auf den ersten Blick überzeugend, zerfällt aber, sobald man wirklich nachschaut.",
        "„Everyone's doing it“ ist ein trügerisch einleuchtendes Argument, das einer Prüfung nie ganz standhält.",
        "Erscheinung, Aussehen",
        "voll von (schön scheinend)",
    ),
    "cant": (
        "Unehrliches, heuchlerisches Gerede, oft moralisierend.",
        "Predigerton, der tugendhaft klingt, aber von keinem echten Gefühl getragen wird — moralisches Posieren im Autopilot.",
        "Er hatte das fromme Firmengerede über „Familie“ satt, von einer Firma, die niemandem frei gab.",
        "singen (später: Singsang-Jargon)",
        "winselnde Bettlersprache, dann Heuchelei",
    ),
    "pusillanimous": (
        "Ohne Mut, feige.",
        "Ängstlich bis zur Rückgratlosigkeit — zu ängstlich, aufzustehen, selbst wenn es klar darauf ankommt.",
        "Das kleinmütige Schweigen des Vorstands ließ den Skandal außer Kontrolle geraten.",
        "sehr klein",
        "Geist, Mut",
    ),
    "vulpine": (
        "Fuchsgleich; listig, verschlagen.",
        "Schlau und gewitzt wie ein Fuchs — schnell im Kopf, ein wenig hinterlistig, immer einen Schritt voraus.",
        "Er gab ein listiges Grinsen, sobald er die Lücke entdeckte.",
        "Fuchs",
        "von oder wie",
    ),
    "seriatim": (
        "Nacheinander, der Reihe nach.",
        "Strikt eins nach dem anderen, in der Reihenfolge — kein Überspringen, kein Zweierlei auf einmal.",
        "Die Richterin behandelte jede der zwölf Klagen der Reihe nach.",
        "Reihe, Folge",
        "eins nach dem anderen",
    ),
    "parsimony": (
        "Äußerste Sparsamkeit; Geiz.",
        "Eng mit Geld (oder Worten oder Mitteln) sein, weit über vernünftige Sparsamkeit hinaus.",
        "Sein Geiz war legendär — er verwendete Teebeutel dreimal.",
        "schonen, sparsam sein",
        "Zustand oder Praxis",
    ),
    "emendation": (
        "Eine Korrektur, besonders in einem Text.",
        "Eine Berichtigung in einem Schriftstück — ein gelehrter Eingriff, der einen Fehler in einem alten oder wichtigen Text behebt.",
        "Die neue Ausgabe enthält Dutzende Textverbesserungen am ursprünglichen Manuskript.",
        "heraus",
        "Fehler, Irrtum",
    ),
    "abstemious": (
        "Mäßig im Essen und Trinken.",
        "Bewusst zurückhaltend bei Speise und Trank — nie zu viel, immer ein wenig auf dem Teller lassen.",
        "Seine enthaltsamen Gewohnheiten hielten ihn scharf, lange nachdem seine Altersgenossen langsamer geworden waren.",
        "weg von",
        "berauschendes Getränk",
    ),
    "solecism": (
        "Ein grammatischer Fehler oder ein Verstoß gegen die Etikette.",
        "Ein Ausrutscher in Grammatik oder Manieren — der kleine Fehler, bei dem ein Pedant zusammenzuckt.",
        "„Between you and I“ ist ein häufiger Solözismus, der Grammatiker noch immer zusammenzucken lässt.",
        "kilikische Stadt, bekannt für ‚schlechtes‘ Griechisch",
        "Übung, Art",
    ),
    "internecine": (
        "Einen Konflikt innerhalb einer Gruppe betreffend; gegenseitig zerstörerisch.",
        "Interner Streit, der eine Gruppe von innen zerreißt — ein Kampf, in dem alle verlieren, weil es Familie gegen Familie ist.",
        "Das selbstzerstörerische Gezänk der Partei richtete mehr Schaden an als jeder äußere Gegner.",
        "zwischen, unter",
        "töten",
    ),
    "pococurante": (
        "Gleichgültige, nachlässige Haltung.",
        "Ein Schulterzucken zur ganzen Persönlichkeit gemacht — so wenig um das geben, was einmal zählte, dass nichts mehr die Mühe wert scheint.",
        "Seine gleichgültige Haltung zur Preisverleihung überraschte alle, die wussten, wie hart er gearbeitet hatte.",
        "wenig",
        "sich kümmern",
    ),
    "imbroglio": (
        "Eine verworrene, verwickelte Lage oder Streitigkeit.",
        "Eine verknotete, unordentliche Lage, die schwer zu entwirren ist — teils Missverständnis, teils Drama, alles Verwirrung.",
        "Das ganze Imbroglio um die Tischordnung begann mit einer falsch gelegten Namenskarte.",
        "in",
        "verwickeln, verwirren",
    ),
    "minatory": (
        "Drohend, bedrohlich.",
        "Mit unverkennbarem Hauch von Drohung — ein drohender Blick oder Brief macht sehr klar, dass etwas Unangenehmes folgen könnte.",
        "Der drohende Ton des Briefes machte die Mieterin nervös, noch bevor sie den Umschlag geöffnet hatte.",
        "drohen",
        "dienend zu",
    ),
    "obloquy": (
        "Starke öffentliche Kritik oder verbale Schmähung.",
        "Laute, öffentliche Verurteilung — die beißende Kritik, die sich vor aller Augen abspielt.",
        "Die Whistleblowerin ertrug Jahre öffentlicher Schmähung, bevor die Geschichte ihr Recht gab.",
        "gegen",
        "sprechen",
    ),
    "paroxysm": (
        "Ein plötzlicher heftiger Ausbruch von Gefühl oder Handlung.",
        "Ein plötzlicher, intensiver Schub, der einen auf einmal überwältigt — ein Lach-, Wut- oder Hustenanfall wie eine Welle.",
        "Sie wurde von einem Paroxysmus des Lachens ergriffen, den sie sonst niemandem im Raum erklären konnte.",
        "jenseits",
        "scharf, akut",
    ),
    "adscititious": (
        "Von außen hinzugefügt, nicht innewohnend.",
        "Von außen angeschraubt statt von Anfang an eingebaut — ein Extra, kein Kern.",
        "Der Kommentar wirkt angeflickt, als wäre er an einen schon fertigen Text angehängt.",
        "zu, zusätzlich",
        "gutheißen, annehmen",
    ),
    "nescience": (
        "Mangel an Wissen, Unwissenheit.",
        "Schlichtes Nichtwissen — eine Lücke im Wissen, ohne Urteil darüber.",
        "Er gab seine Unkenntnis französischen Weins zu und ließ den Sommelier wählen.",
        "nicht",
        "wissen",
    ),
    "prurience": (
        "Übermäßiges Interesse an sexuellen Dingen.",
        "Eine übereifrige, lüsterne Neugier auf alles Anzügliche — Interesse, das das Gesunde hinter sich gelassen hat und aufdringlich wird.",
        "Die Lüsternheit der Boulevardzeitung über das Privatleben des Paares grenzte an Besessenheit.",
        "jucken, verlangen",
        "Zustand von",
    ),
    "fuliginous": (
        "Rußig, dunkel, trübe.",
        "Dunkel und rauchig, als wäre alles mit einer dünnen Rußschicht überzogen.",
        "Ein rußiger Dunst hing in der Dämmerung über der Fabrikstadt.",
        "Ruß",
        "voll von",
    ),
    "gainsay": (
        "Leugnen oder widersprechen.",
        "Klar gegen etwas sprechen, das ein anderer gesagt hat — sagen, dass es nicht so ist.",
        "Niemand wagte, dem alten Kapitän über seinen Sturmbericht zu widersprechen.",
        "gegen",
        "sprechen",
    ),
    "ignavia": (
        "Faulheit, Trägheit (aus dem Lateinischen).",
        "Ein altes lateinisches Wort für schiere Faulheit — das Ziehen, nichts tun zu wollen.",
        "Die Mönche predigten gegen Trägheit als eine der stillen Gefahren der Seele.",
        "nicht",
        "beschäftigt, fleißig",
    ),
    "escutcheon": (
        "Ein Schild, das ein Wappen zeigt.",
        "Das schildförmige Emblem mit dem Familienwappen — das heraldische Zeichen.",
        "Das Wappenschild der Familie hängt noch über der Haustür des alten Herrenhauses.",
        "Schild",
        "Diminutiv / Gegenstand",
    ),
    "superannuated": (
        "Veraltet, überholt oder altersbedingt ausgeschieden.",
        "Über die nützliche Blüte hinaus und aufs Abstellgleis — zu altmodisch oder verschlissen, um den Job noch zu tun.",
        "Der ausgediente Drucker wurde nach fünfzehn Jahren Papierstau endlich ersetzt.",
        "jenseits",
        "Jahr",
    ),
    "succedanea": (
        "Ersatzmittel, besonders in der Medizin.",
        "Ersatzheilmittel, wenn die eigentliche Behandlung fehlt — medizinische Doubles, im Grunde.",
        "Kriegsärzte stützten sich oft auf Ersatzmittel, wenn die richtigen Mittel ausgingen.",
        "anstelle von",
        "gehen, weichen",
    ),
    "rodomontade": (
        "Prahlerisches, polterndes Gerede.",
        "Großes, polterndes Prahlen — lautes Reden über die eigene Größe, das vor allem heiße Luft ist.",
        "Seine Prahlerei, das Projekt „im Alleingang“ gerettet zu haben, täuschte niemanden, der wirklich dabei gewesen war.",
        "prahlerischer Ritter in Orlando Furioso",
        "Handlung, Schau",
    ),
    "chicane": (
        "Mit List oder Täuschung etwas erreichen.",
        "Sich mit hinterlistigen Tricks zum Ziel winden statt mit fairem Spiel.",
        "Er trickste sich mit einem Vertrag voller Kleingedrucktem in den Deal.",
        "klingeln, betrügen",
        "List; später eine scharfe Kurve",
    ),
    "mathesis": (
        "Die reine oder abstrakte Wissenschaft des Lernens oder Wissens, oft Mathematik.",
        "Lernen in seiner reinsten, abstraktesten Form — die tiefe Struktur des Wissens selbst, vor allem der mathematischen Art.",
        "Der Philosoph träumte von einer universalen Mathesis, die jedes Wissensgebiet einen könnte.",
        "lernen",
        "der Akt des Lernens",
    ),
    "pedantic": (
        "Übermäßig befasst mit formellen Regeln oder trivialen Details.",
        "Zu streng bei Kleinigkeiten — kleine technische Punkte korrigieren, die nichts Wesentliches ändern.",
        "Es fühlte sich ein wenig pedantisch an, in einer Kurznachricht über „who“ versus „whom“ zu streiten.",
        "Kinderführer, Tutor",
        "die Art habend von",
    ),
    "coruscation": (
        "Ein blitzendes, funkelndes Licht.",
        "Ein rascher, glitzernder Lichtblitz — Sonnenlicht auf Wasser, oder ein Diamant, der das Licht fängt.",
        "Das Funkeln des Kronleuchters streute Licht in jede Ecke des Ballsaals.",
        "glitzern, blitzen",
        "der Akt von",
    ),
    "tyro": (
        "Ein Anfänger, ein Neuling.",
        "Jemand brandneu in einer Fertigkeit oder einem Feld — noch dabei, die Kniffe zu lernen, noch kein Kenner.",
        "Selbst ein Anfänger im Schach sieht diesen Patzer.",
        "Rekrut, Neuling",
        "ein grüner junger Soldat",
    ),
    "execrable": (
        "Äußerst schlecht, verabscheuungswürdig.",
        "Schlecht auf eine Weise, die echten Ekel verdient — nicht nur mittelmäßig, sondern wirklich scheußlich.",
        "Der Rezensent nannte die Fortsetzung abscheulich, und die Kassen stimmten zu.",
        "verfluchen",
        "würdig, fähig zu",
    ),
    "incarnadine": (
        "Blutrot von Farbe.",
        "Ein tiefes, leuchtendes Rot — die Farbe frischen Blutes, berühmt durch Shakespeares Macbeth.",
        "Der Sonnenuntergang tauchte den ganzen Himmel in einen blutroten Schein.",
        "hinein",
        "Fleisch (fleischrot)",
    ),
    "interstice": (
        "Eine kleine Lücke oder Zwischenraum.",
        "Der winzige Zwischenraum, den man leicht übersieht — der Riss zwischen den Dielen, die Lücke im Terminkalender.",
        "Unkraut drängte durch jede Fuge im alten Ziegelweg.",
        "zwischen",
        "stehen",
    ),
    "animadversion": (
        "Kritische oder tadelnde Bemerkungen.",
        "Spitze, missbilligende Kommentare — die Art Kritik, die ein wenig nach Schelte klingt.",
        "Die Rügen des Professors zum Aufsatz füllten die Ränder mit roter Tinte.",
        "Geist",
        "sich zuwenden",
    ),
    "irrefragable": (
        "Nicht zu widerlegen, unleugbar.",
        "So solid bewiesen, dass es kein Argument dagegen gibt — der Fall ist einfach geschlossen.",
        "Der DNA-Beweis war unwiderleglich, und der Prozess endete innerhalb einer Stunde.",
        "nicht",
        "sich widersetzen, widerstehen",
    ),
    "involution": (
        "Komplexität, Verwickeltheit; auch ein Einwärtskrümmen.",
        "Eine verknotete, in sich gefaltete Komplexität — Dinge so eng ineinander gewickelt, dass sie schwer zu lösen sind.",
        "Die Verwicklung der Handlung ließ die Hälfte des Publikums nach dem Abspann noch entwirren.",
        "hinein, einwärts",
        "rollen, wenden",
    ),
    "dint": (
        "Kraft oder Mühe, wie in „by dint of“.",
        "Bloße Kraft oder Anstrengung — überlebt vor allem in der Wendung „by dint of“.",
        "Er bestand die Prüfung durch schiere, hartnäckige Übung.",
        "ein Schlag, ein Stoß",
        "kraft",
    ),
    "mortised": (
        "Mit einer Zapfenverbindung gefügt; fest ineinander gepasst.",
        "Auf die alte Zimmermannsart ineinander verriegelt — ein Stück gleitet genau in ein Loch, das eigens dafür geschnitten ist.",
        "Die Balken der alten Scheune waren mit Zapfenverbindungen ineinandergefügt, ohne einen einzigen Nagel.",
        "eine Vertiefung, ein Loch",
        "ein Biss, ein Griff",
    ),
    "apposite": (
        "Höchst treffend, passend.",
        "Genau der richtige Treffer für den Moment — eine Bemerkung, ein Zitat oder Beispiel, das punktgenau landet.",
        "Ihre treffende Bemerkung fasste die ganze Debatte in einem Satz zusammen.",
        "zu",
        "setzen",
    ),
    "lambent": (
        "Sanft glühend oder flackernd (Licht); auch: leichter Witz.",
        "Sanft glühend statt lodernd — ein weiches, flackerndes Licht, oder ein Witz, der spielerisch ist statt scharf.",
        "Kerzenlicht warf einen sanft flackernden Schein über das alte Esszimmer.",
        "lecken",
        "tuend (Licht, das ‚leckt‘)",
    ),
    "anchorite": (
        "Ein religiöser Einsiedler, der in Einsamkeit lebt.",
        "Jemand, der sich ganz aus der Welt zurückzieht, um allein in Gebet und Betrachtung zu leben.",
        "Der Einsiedler lebte über dreißig Jahre in einer kleinen Zelle an der Kirche.",
        "zurück, weg",
        "sich zurückziehen",
    ),
    "slake": (
        "Durst stillen; löschen.",
        "Ein Verlangen ganz stillen — meist Durst, bildlich aber jedes tiefe Bedürfnis.",
        "Ein kaltes Glas Wasser stillte seinen Durst nach der langen Wanderung.",
        "schlaff, lose",
        "lockern, lindern",
    ),
    "acicular": (
        "Nadelförmig.",
        "Lang, dünn und spitz wie eine Nadel — die Form einer Kiefernnadel oder eines scharfen Kriställchens.",
        "Kiefern sind an ihren nadelförmigen Blättern leicht zu erkennen.",
        "Nadel",
        "klein",
    ),
    "effete": (
        "Der Lebenskraft beraubt, schwach, überfeinert.",
        "Ausgelaugt und weich — die ursprüngliche Kraft durch zu viel Komfort oder Verfeinerung verloren.",
        "Kritiker nannten die einst kühne Zeitschrift kraftlos, ein Schatten ihrer dreisten Anfangsjahre.",
        "hinaus",
        "fruchtbar, getragen habend",
    ),
    "appurtenance": (
        "Ein Zubehör oder geringfügig anhängendes Stück oder Recht.",
        "Ein kleines Extra, das an etwas Größerem hängt — die Beigaben und Anhängsel zum Hauptstück.",
        "Der Mietvertrag umfasste die Garage und all ihr Zubehör.",
        "zu",
        "gehören",
    ),
    "gloze": (
        "Einen Fehler beschönigen oder verkleinern.",
        "Einen Schnitzer mit weichen Worten glätten, sodass er kleiner klingt, als er ist.",
        "Er versuchte, die verpasste Frist mit vagem Gerede von „unvorhergesehenen Schwierigkeiten“ zu beschönigen.",
        "eine Glosse, eine Erklärung",
        "kommentieren — dann glätten",
    ),
    "incipient": (
        "In einem frühen Stadium, eben beginnend.",
        "Gerade erst sichtbar werdend — das allererste, kaum merkbare Stadium von etwas Größerem.",
        "Ärzte erkannten die beginnenden Zeichen der Krankheit, bevor sie sich ausbreiten konnte.",
        "auf, hinein",
        "nehmen (aufnehmen, beginnen)",
    ),
    "afflatus": (
        "Schöpferische Eingebung, besonders göttliche.",
        "Ein plötzlicher Schub von Inspiration, der größer wirkt als du — als wäre die Idee dir von woanders eingehaucht.",
        "Der Dichter beschrieb, wie das ganze Stück in einem Anfall von Eingebung um drei Uhr morgens ankam.",
        "zu, auf",
        "blasen (ein Anhauchen)",
    ),
}
