# Polish overlays: (definition, friendly, exampleGloss, root1, root2)
WORDS = {
    "edulcorate": (
        "Słodzić lub oczyszczać; odbierać czemuś ostrość.",
        "Wyjąć żądło albo gorycz — dosłownie osłodzić, albo w przenośni zmiękczyć twardą myśl, żeby łatwiej weszła.",
        "Redaktor osłodził ostrą recenzję, zanim poszła do druku.",
        "na zewnątrz, gruntownie",
        "słodki",
    ),
    "pietistic": (
        "Nadmiernie albo afektowanie religijny lub pobożny.",
        "Opisuje kogoś, czyja pobożność pachnie pokazem: więcej występu niż prawdziwej wiary.",
        "Jego pietystyczne wzdychanie podczas kazania drażniło resztę ławki.",
        "pobożność, poczucie obowiązku",
        "mający charakter",
    ),
    "amphiboly": (
        "Dwuznaczność wynikająca ze składni — zdanie czytelne na dwa sposoby.",
        "Zdanie gramatycznie poprawne, ale dające się odczytać na dwa zupełnie różne sposoby, jak „Visiting relatives can be tiring”.",
        "„Visiting relatives can be tiring” to klasyczna amfibolia — męczą krewni, czy samo ich odwiedzanie?",
        "oba, z obu stron",
        "rzucać",
    ),
    "trenchant": (
        "Ostry, przenikliwy, idący prosto do rzeczy.",
        "Przecina zbędny szum — cięta uwaga albo umysł trafia w sedno szybko, bez zbędnych słów.",
        "Jej cięta krytyka nie zostawiła lukom w fabule filmu żadnej kryjówki.",
        "ciąć",
        "czyniący, mający jakość",
    ),
    "inchoative": (
        "Dopiero się zaczynający; we wczesnym lub szczątkowym stadium.",
        "Jeszcze w pierwszych chwilach — plan, uczucie albo proces, który dopiero zaczyna nabierać kształtu.",
        "Inchoatywne stadia traktatu były obiecujące, ale wiele szczegółów pozostało otwartych.",
        "zaczynać, rozpoczynać",
        "skłaniający się ku",
    ),
    "panegyric": (
        "Formalna mowa albo tekst wychwalający kogoś z przepychem.",
        "Pełny, uroczysty hołd — pomyśl o jaśniejącym panegiryku albo o mowie, która śpiewa czyjeś czyny z dachów.",
        "Odchodzącą profesor pożegnano panegirykiem jej najbliższych studentów.",
        "wszystko, cały",
        "zgromadzenie, zebranie",
    ),
    "ontic": (
        "Dotyczący rzeczywistego istnienia, w przeciwieństwie do teorii abstrakcyjnej.",
        "O rzeczach takimi, jakimi naprawdę są — nie tylko jako idee albo teorie na ich temat.",
        "Filozofowie spierają się, czy liczby mają jakikolwiek status ontyczny, czy istnieją tylko w naszych głowach.",
        "bycie, to co istnieje",
        "odnoszący się do",
    ),
    "fructify": (
        "Owocować albo stawać się wydajnym.",
        "Wreszcie wydać plon — wysiłek, pomysł albo inwestycja, która owocuje, wyrosła z ziarna w coś pożytecznego.",
        "Lata cichej pracy badawczej zaowocowały wreszcie działającą szczepionką.",
        "owoc",
        "czynić, powodować",
    ),
    "proleptical": (
        "Antycypować albo przedstawiać coś jako już dokonane, zanim się zdarzy.",
        "Wybiegać naprzód na literacki sposób — opisać przyszłe zdarzenie, jakby już było zamknięte, żeby punkt uderzył mocniej.",
        "Proleptyczny toast generała za „zwycięstwo” wzniesiono pełny tydzień przed bitwą.",
        "przed",
        "brać, chwytać",
    ),
    "pneumatic": (
        "Napędzany ciśnieniem powietrza; także dotyczący ducha albo oddechu.",
        "Zwykle: poruszany sprężonym powietrzem — wiertarka, hamulec autobusu — ale ten sam grecki rdzeń mówi też o oddechu i duchu.",
        "Pneumatyczne hamulce syknęły, gdy autobus stanął przy krawężniku.",
        "wiatr, oddech, duch",
        "dotyczący",
    ),
    "cataphatic": (
        "Opisywać Boga albo boskość twierdzeniami pozytywnymi — przeciwieństwo apofatycznego.",
        "Mówić o Bogu, mówiąc, kim jest — „Bóg jest miłością”, „Bóg jest sprawiedliwy” — zamiast tylko, kim nie jest.",
        "Teologia katafatyczna mówi z pewnością o Bogu jako kochającym, sprawiedliwym i miłosiernym.",
        "w dół, według",
        "mówić, rzec",
    ),
    "fiducial": (
        "Oparty na zaufaniu albo wierze; także: stały punkt odniesienia.",
        "Coś, co bierze się na wiarę, a potem służy za kotwicę — znacznik odniesienia to stały punkt, względem którego mierzy się resztę.",
        "Geodeci umieścili znacznik odniesienia w skale, zanim zmapowali teren.",
        "ufać",
        "zaufanie, pewność",
    ),
    "theodicy": (
        "Obrona dobroci Boga wobec istnienia zła.",
        "Stara próba odpowiedzi: jeśli Bóg jest dobry, dlaczego jest zło? — bez porzucania żadnego z tych twierdzeń.",
        "Jej praca badała teodyceę przez pryzmat Księgi Hioba.",
        "bóg",
        "sprawiedliwość",
    ),
    "circumincession": (
        "Wzajemne zamieszkiwanie — termin teologiczny na to, jak osoby Trójcy istnieją jedna w drugiej.",
        "Słowo teologii na trójjedyną wspólnotę tak pełną, że każda część zawiera pozostałe i jest przez nie zawierana.",
        "Doktryna perychorezy stara się wyjaśnić, jak Ojciec, Syn i Duch są odrębni, a jednak nierozłączni.",
        "dookoła",
        "iść, kroczyć",
    ),
    "redound": (
        "Mieć skutek, który komuś służy albo na kogoś spada.",
        "Gdy zasługa (albo wina) odbija się na odpowiedzialnym — dobre uczynki, które przysparzają ci imienia, wracają potem jako nagroda.",
        "Sukces drużyny przysporzy zasług cichemu, pracowitemu trenerowi.",
        "wstecz, znowu",
        "fala",
    ),
    "ineluctable": (
        "Niemożliwy do uniknięcia ani do ucieczki.",
        "Zdarzy się, cokolwiek zrobisz — z nieuniknionego wyniku się nie wywiniesz.",
        "Starość przychodzi do wszystkich; jest po prostu nieunikniona.",
        "nie",
        "wydzierać się na zewnątrz",
    ),
    "periphrastic": (
        "Używający okrężnego, słownego sformułowania zamiast formy bezpośredniej.",
        "Iść długą drogą ze słowami — powiedzieć całym zdaniem to, co pokryłoby jedno słowo.",
        "Jego peryfrastyczne e-maile mogły powiedzieć w jednej linijce to, co zajęło mu trzy akapity.",
        "dookoła",
        "oznajmiać, opowiadać",
    ),
    "hebetude": (
        "Otępienie umysłowe albo letarg.",
        "Ten mglisty, ociężały stan umysłu, w którym myślenie jest jak brnięcie przez syrop.",
        "Fala otępienia spadła na klasę zaraz po obiedzie.",
        "tępy, stępiony",
        "stan albo jakość",
    ),
    "unpropitious": (
        "Niekorzystny; złowróżbny.",
        "Zły znak — warunki albo czas, które już zdają się działać przeciwko tobie, zanim w ogóle zaczniesz.",
        "Szare niebo i martwa bateria w aucie dały niepomyślny początek podróży.",
        "nie",
        "przychylny, łaskawy",
    ),
    "fricaseed": (
        "Mięso duszone albo smażone w sosie — poprawnie pisane „fricasseed”.",
        "Przytulny, stary termin kuchenny na mięso pokrojone i wolno gotowane we własnym sosie, aż zmięknie.",
        "Kurczak babci w potrawce był gwiazdą każdego niedzielnego obiadu.",
        "smażyć",
        "łamać (na kawałki)",
    ),
    "ersatz": (
        "Sztuczny albo gorszy substytut.",
        "Podróbka stojąca za oryginał — spełnia zadanie, ale każdy widzi, że to nie to samo.",
        "W czasie wojny kupujący godzili się na namiastkę kawy z palonej cykorii.",
        "na zewnątrz, przedrostek zastępstwa",
        "stawiać, kłaść",
    ),
    "reify": (
        "Traktować abstrakcyjną ideę tak, jakby była konkretną rzeczą.",
        "Sprawić, by idea poczuła się realna i twarda — zamienić coś mglistego, jak „rynek”, w rzecz, na którą można wskazać.",
        "Nazywanie „ducha” narodu osobnym bytem reifikuje coś, co naprawdę jest milionami pojedynczych wyborów.",
        "rzecz",
        "czynić",
    ),
    "eluded": (
        "Zręcznie umknąć albo uniknąć.",
        "Wymknąć się czysto — wyminąć coś, często sprytnie albo o włos, czy to schwytanie, pytanie, czy odpowiedź.",
        "Odpowiedź wymykała się jej przez godziny, aż nagle kliknęła pod prysznicem.",
        "na zewnątrz, precz",
        "grać",
    ),
    "aporetic": (
        "Wyrażający wątpliwość, zakłopotanie albo nierozwiązaną sprzeczność.",
        "Zablokowany w prawdziwym ślepym zaułku myśli — nie z lenistwa, ale dlatego, że samo pytanie odmawia schludnej odpowiedzi.",
        "Sokrates często kończył dialogi na nucie aporetycznej, z większą liczbą pytań niż odpowiedzi.",
        "bez",
        "przejście, droga",
    ),
    "metonymy": (
        "Figura nazywająca coś terminem powiązanym, np. „korona” zamiast monarchy.",
        "Użyć pokrewnego słowa zamiast samej rzeczy — powiedzieć „Wall Street”, gdy ma się na myśli giełdę.",
        "„Wall Street had a rough day” to metonimia — naprawdę znaczy, że giełda miała zły dzień.",
        "zmiana, potem",
        "imię",
    ),
    "deracinate": (
        "Wykorzenić; wyrwać z naturalnego środowiska.",
        "Wyrwać coś (albo kogoś) z korzeniami, precz z miejsca albo kultury, do których należy.",
        "Wojna wykorzeniła całe pokolenie, rozrzucając rodziny poza granice.",
        "precz, z dala",
        "korzeń",
    ),
    "euphonious": (
        "Przyjemnie brzmiący.",
        "Po prostu miły dla ucha — eufoniczne słowo albo zdanie spływa, niemal muzycznie.",
        "„Murmuring brook” to eufoniczne małe wyrażenie, miękkie i łatwe do wypowiedzenia.",
        "dobry, dobrze",
        "dźwięk, głos",
    ),
    "putative": (
        "Powszechnie zakładany albo uważany za taki.",
        "Uznawany za prawdziwy na szeroką skalę, nawet bez dowodu — rzekoma albo domniemana wersja czegoś.",
        "Domniemany autor listu okazał się później zupełnym obcym.",
        "myśleć, uważać",
        "mający naturę",
    ),
    "neologism": (
        "Nowo ukute słowo albo zwrot.",
        "Zupełnie nowe słowo — świeżo wymyślone, jeszcze (ledwie) w słowniku.",
        "„Doomscrolling” zaczęło jako neologizm i szybko stało się codziennym slangiem.",
        "nowy",
        "słowo, mowa",
    ),
    "splenetic": (
        "Zły albo w złym humorze.",
        "W kwaśnym, drażliwym nastroju, skory do wybuchu — jak dawniej wierzono, że śledziona rządzi temperamentem.",
        "Odpalił zjadliwą odpowiedź na e-mail w kilka sekund po przeczytaniu.",
        "śledziona (siedziba gniewu)",
        "dotknięty przez",
    ),
    "sententious": (
        "Skłonny do moralizowania w sposób pompatyczny albo afektowany.",
        "Uwielbia sypać drobnymi życiowymi naukami, jakby każde zdanie było ciasteczkiem z wróżbą.",
        "Jego sentencjonalny toast o „prawdziwym znaczeniu przyjaźni” sprawił, że wszyscy spojrzeli na zegarki.",
        "opinia, maksyma",
        "pełen",
    ),
    "garrulous": (
        "Nadmiernie gadatliwy, zwłaszcza o drobiazgach.",
        "Po prostu nie przestaje gadać — plecie o drobiazgach długo po tym, jak reszta już nie ma nic do powiedzenia.",
        "Gadatliwy taksówkarz opowiedział nam całe swoje życie, zanim wyjechaliśmy z lotniska.",
        "paplać, gawędzić",
        "skłonny do",
    ),
    "fatuity": (
        "Głupota, niemądrość.",
        "Zwykła głupota — uwaga albo plan tak niemądre, że ledwie zasługują na poważną odpowiedź.",
        "Czysta niedorzeczność planu stała się oczywista, gdy tylko go spróbowali.",
        "głupi, niemądry",
        "stan bycia",
    ),
    "peroration": (
        "Zakończeniowa część mowy, często podsumowująca.",
        "Wielki finał przemowy — odcinek, w którym mówca zbiera wszystko i wbija punkt.",
        "Przy peroracji połowa publiczności była na nogach.",
        "przez, aż do końca",
        "mówić, wnosić",
    ),
    "tautology": (
        "Zbędne powtórzenie tej samej myśli innymi słowami.",
        "Powiedzieć to samo dwa razy, nic nie dodając, jak „darmowy prezent” albo „it is what it is”.",
        "„It is what it is” to ulubiona tautologia ludzi unikających prawdziwego wyjaśnienia.",
        "to samo",
        "słowo, mowa",
    ),
    "laconism": (
        "Używanie bardzo niewielu słów; zwięzła mowa.",
        "Powiedzieć wiele niewieloma — sztuka krótkiej, suchej odpowiedzi, nazwana od notorycznie zwięzłych Spartan z Lakonii.",
        "„Molon labe” — „przyjdźcie i weźcie” — to najsłynniejszy kawałek lakonizmu w historii.",
        "Spartanin z Lakonii",
        "praktyka, sposób",
    ),
    "pabulum": (
        "Nijakie, nazbyt uproszczone idee; pierwotnie: mdłe jedzenie albo papka.",
        "Rozcieńczone myślenie — treść tak uproszczona i bezpieczna, że nie karmi umysłu.",
        "Przemówienie polityka było głównie papką: mgliste obietnice, na których nic nie dało się zawiesić.",
        "karmić",
        "środek albo narzędzie",
    ),
    "soporific": (
        "Wywołujący sen albo senność.",
        "Tak nudny — albo tak dosłownie usypiający — że chce się spać. Pomyśl o ciepłym mleku albo o trzygodzinnej naradzie budżetowej.",
        "Usypiający szum wykładu sprawiał, że połowa sali walczyła, by nie zamknąć oczu.",
        "głęboki sen",
        "czyniący, powodujący",
    ),
    "unctuous": (
        "Nadmiernie pochlebny albo oleisty w sposobie bycia.",
        "Tak gładko czarujący, że śliski — pochlebstwo tak grube, że prawie czuć tłuszcz.",
        "Lizusowaty sprzedawca nie przestawał chwalić mojego „doskonałego gustu” przed każdą dodatkową sprzedażą.",
        "namaszczać, oliwić",
        "pełen",
    ),
    "captious": (
        "Skory do wyszukiwania wad, zbyt krytyczny wobec drobiazgów.",
        "Czepialski do przesady — typ, który znajdzie problem we wszystkim, nawet gdy to nic nie znaczy.",
        "Jego czepliwe uwagi do raportu skupiały się wyłącznie na przecinkach.",
        "chwytać, brać",
        "pułapka, sofizmat",
    ),
    "torpid": (
        "Ociężały, nieaktywny umysłowo albo fizycznie.",
        "Powolny i na wpół śpiący, jak niedźwiedź w hibernacji — ledwie się rusza, ledwie myśli.",
        "Biuro zapadło w odrętwienie w ciężkim sierpniowym upale.",
        "być zdrętwiałym, być ociężałym",
        "w stanie",
    ),
    "seneschal": (
        "Zarządca albo urzędnik prowadzący średniowieczny dwór.",
        "Średniowieczna wersja szefa personelu — zaufany urzędnik, który na co dzień prowadził dom i majątek pana.",
        "Seneszal zamku ogarniał wszystko, od rachunków żniw po listę gości.",
        "stary, starszy",
        "sługa",
    ),
    "expatiate": (
        "Mówić albo pisać obszernie o temacie.",
        "Naprawdę ruszyć z tematem — gadać albo pisać bez końca, oglądając go z każdej strony.",
        "Zapytaj go o oldtimery, a będzie się rozwodził przez dobrą godzinę.",
        "na zewnątrz",
        "przestrzeń",
    ),
    "nugatory": (
        "Bezwartościowy, błahy; także nieważny albo nieskuteczny.",
        "W zasadzie nic nie wart — bezskuteczna klauzula w umowie w praktyce nic nie robi.",
        "Sąd uznał stary przepis za bezskuteczny, bo nigdy nie był egzekwowany.",
        "drobiazgi, bzdury",
        "należący do",
    ),
    "sagacity": (
        "Mądrość, bystra ocena.",
        "Ostra, praktyczna mądrość — ten rodzaj dobrego osądu, który przychodzi z doświadczenia, nie tylko z książek.",
        "Roztropność starego kapitana nie raz wyciągnęła załogę z kłopotów.",
        "bystry węchem, przenikliwy",
        "jakość",
    ),
    "canaille": (
        "Pospólstwo albo masa, używane z pogardą.",
        "Snobistyczne, pogardliwe słowo na zwykłych ludzi, jakby byli sforą psów.",
        "Hrabia szydził z hołoty zbierającej się za bramami pałacu.",
        "pies",
        "zbiorowość, sfora",
    ),
    "contumely": (
        "Obraźliwe, upokarzające traktowanie albo język.",
        "Okrutne, pogardliwe traktowanie mające upokorzyć — obelga zaprojektowana, by zaboleć.",
        "Znosił lata zniewag od krytyków, zanim jego praca została wreszcie uznana.",
        "z, gruntownie",
        "puchnąć (z pychy)",
    ),
    "askance": (
        "Z podejrzeniem albo dezaprobatą; spojrzenie z ukosa.",
        "Skośne spojrzenie, które dajesz czemuś, czemu nie całkiem ufasz — spojrzenie pełne wątpliwości.",
        "Nauczycielka spojrzała krzywo na podejrzanie schludne zadanie.",
        "ku, do",
        "skos, uprzedzenie",
    ),
    "clodpate": (
        "Głupiec; tępak.",
        "Staromodna, niemal czuła obelga na kogoś, kto jest tępawy albo gęsty — tępak.",
        "„Ty ośle” — zaśmiała się — „przez cały czas trzymałeś mapę do góry nogami.”",
        "gruda ziemi",
        "głowa",
    ),
    "actuate": (
        "Wprawić w ruch albo w działanie; zmotywować.",
        "Być iskrą, która coś rusza — maszynę, która się włącza, albo człowieka, który wreszcie działa według pomysłu.",
        "Strach przed utratą kontraktu popchnął cały zespół do weekendu nadgodzin.",
        "czynienie, pędzenie",
        "pędzić, czynić",
    ),
    "peculation": (
        "Sprzeniewierzenie powierzonych środków.",
        "Cicho kraść pieniądze, które miało się strzec — sprzeniewierzenie w staromodnym płaszczu.",
        "Sprzeniewierzenie skarbnika umknęło uwadze przez niemal dekadę.",
        "własność prywatna",
        "bydło, bogactwo",
    ),
    "demi-monde": (
        "Grupa uważana za żyjącą na skraju przyzwoitego towarzystwa.",
        "Glamour i mroczny półświatek — ludzie żyjący tuż poza regułami przyzwoitości.",
        "Powieść śledzi piosenkarkę w półświatku kabaretów lat dwudziestych.",
        "pół",
        "świat, społeczeństwo",
    ),
    "extant": (
        "Wciąż istniejący; nie wymarły ani nie zniszczony.",
        "Wciąż tu dziś — o starych rzeczach (rękopisach, gatunkach, budynkach), które zdołały przetrwać.",
        "Znane są tylko trzy zachowane egzemplarze pierwszego druku.",
        "na zewnątrz",
        "stać",
    ),
    "perfidy": (
        "Podstęp; zdrada zaufania.",
        "Głęboka, zamierzona zdrada — złamać zaufanie, którego ktoś miał prawo od ciebie oczekiwać.",
        "Generał nigdy nie wybaczył perfidii starego przyjaciela przy stole negocjacji.",
        "przez, przeciw",
        "wiara, zaufanie",
    ),
    "patois": (
        "Dialekt regionalny, zwłaszcza niestandardowy.",
        "Własny, lokalny sposób mówienia w danym regionie — pełen słów i rytmów, których obcy nie złapie.",
        "Jej babcia wciąż mówiła wyspiarską gwarą przy rodzinnych obiadach.",
        "szorstka mowa, dialekt",
        "łapa — niezgrabna mowa",
    ),
    "prerogative": (
        "Szczególne prawo osoby albo grupy.",
        "Przywilej, który jest tylko twój — prawo, które przychodzi z rolą, stanowiskiem albo statusem.",
        "Wybór celu rodzinnych wakacji to prerogatywa dziadka, i wszyscy o tym wiedzą.",
        "przed",
        "pytać, głosować",
    ),
    "hardihood": (
        "Śmiałość, audacja; także twardość albo wytrzymałość.",
        "Szorstka, odważna odporność — nerw, by iść dalej, i twardość, by wytrwać, gdy już jesteś w drodze.",
        "Potrzeba było prawdziwego hartu, by przekroczyć przełęcz w śnieżycy, bez mapy.",
        "śmiały, twardy",
        "stan, warunek",
    ),
    "effloresce": (
        "Wystrzelić kwieciem; także rozwijać się albo stopniowo pojawiać.",
        "Rozwinąć się aż do pełnego wyrazu — jak kwiat, który się otwiera, albo pomysł, który wreszcie znajduje formę.",
        "Jej cichy talent malarski rozkwitł, gdy tylko miała własne studio.",
        "na zewnątrz",
        "zaczynać kwitnąć",
    ),
    "plumb-line": (
        "Obciążony sznur do oceny pionu; w przenośni: miara osądu.",
        "Ciężarek na sznurku, który spada pionowo, by sprawdzić, czy coś naprawdę stoi pionowo — i, szerzej, każda stała miara, względem której porównuje się resztę.",
        "Używał uczciwości dziadka jako swego rodzaju pionu przy każdej decyzji.",
        "ołów",
        "sznur, miara",
    ),
    "fain": (
        "Chętnie, z ochotą (arch.).",
        "Staromodny sposób powiedzenia „chętnie” albo „z ochotą” — kto robi coś „fain”, robi to z prawdziwą przyjemnością.",
        "„Chętnie odpocząłbym tu chwilę” — westchnął podróżny.",
        "rad, radosny",
        "chętnie, z ochotą",
    ),
    "opprobrium": (
        "Ostra publiczna krytyka albo hańba.",
        "Publiczny wstyd zrzucony na kogoś w wielkim stylu — hańba powszechnego potępienia.",
        "Skandal sprowadził publiczną hańbę na całą firmę.",
        "przeciw",
        "hańba, nagana",
    ),
    "mordant": (
        "Ostrosarkastyczny, kąśliwy w dowcipie albo krytyce.",
        "Dowcip z prawdziwymi zębami — zjadliwa uwaga szczypie właśnie dlatego, że tak celnie trafia.",
        "Jej zjadliwych recenzji filmowych bali się reżyserzy, a czytelnicy je kochali.",
        "gryźć",
        "kąśliwy, czyniący",
    ),
    "pronunciamento": (
        "Formalna proklamacja, często polityczna albo wojskowa.",
        "Wielkie, oficjalne ogłoszenie — zwykle to, które ogłasza nowy rząd, powstanie albo ważny dekret.",
        "Odezwa generała ogłosiła nowy rząd o świcie.",
        "naprzód",
        "ogłaszać",
    ),
    "sciolist": (
        "Osoba o powierzchownej wiedzy udająca eksperta.",
        "Ktoś, kto musnął powierzchnię tematu, a potem mówi, jakby napisał podręcznik.",
        "Mądrala na kolacji pewnie poprawił prawdziwego astrofizyka przy stole.",
        "wiedzieć",
        "zdrobnienie — mały znawca",
    ),
    "dotage": (
        "Upadek władz umysłowych w starości.",
        "Mglisty, zapominalski odcinek późnej starości, gdy ostrość umysłu zaczyna gasnąć.",
        "W swoim zdziecinnieniu opowiadał przy każdej wizycie te same trzy historie, za każdym razem jakby nowe.",
        "majaczyć, być niemądrym",
        "stan albo wynik",
    ),
    "lee-side": (
        "Strona osłonięta od wiatru.",
        "Spokojna, osłonięta strona czegoś — wzgórza, statku, muru — gdzie wiatr już cię nie sięga do końca.",
        "Wędrowcy rozbili namiot po zawietrznej stronie grzbietu, by uciec przed podmuchami.",
        "schronienie, ochrona",
        "flanka, ściana",
    ),
    "parry": (
        "Odeprzeć albo zbić cios, pytanie albo argument.",
        "Gładko odsunąć — cios miecza, niewygodne pytanie, oskarżenie — nie tracąc taktu.",
        "Odparowała podchwytliwe pytanie reportera łatwym żartem.",
        "odpierać",
        "przygotować, bronić",
    ),
    "mephitic": (
        "Cuchnący, trujący.",
        "Śmierdzący niemal toksycznie — smród tak zły, że oddychanie wydaje się niebezpieczne.",
        "Cuchnący zapach uniósł się z bagna o zachodzie słońca.",
        "szkodliwa para",
        "mający naturę",
    ),
    "sybarite": (
        "Osoba oddana luksusowi i przyjemności.",
        "Ktoś, kto żyje dla wygody i uciech — dobre jedzenie, miękkie łóżka, łatwe życie — nazwany od greckiego Sybaris, słynnego z nadmiaru.",
        "Prawdziwy sybaryta, odmawiał każdego pokoju hotelowego bez wanny.",
        "starożytne greckie miasto słynne z luksusu",
        "mieszkaniec",
    ),
    "prescind": (
        "Świadomie odłożyć albo zignorować część czegoś.",
        "W umyśle odsunąć kawałek układanki, by czysto spojrzeć na resztę.",
        "Abstrahujmy na chwilę od kosztu i zapytajmy tylko, czy plan w ogóle działa.",
        "przed, precz",
        "ciąć",
    ),
    "excoriate": (
        "Ostro skrytykować; także: zedrzeć skórę.",
        "Obrać kogoś ze skóry ostrą krytyką — jakby dosłownie zdzierać skórę.",
        "Krytycy zjechali sequel za zdradę wszystkiego, co fani kochali w oryginale.",
        "precz",
        "skóra, skóra zwierzęca",
    ),
    "adduce": (
        "Przytoczyć jako dowód albo świadectwo.",
        "Wysunąć fakt albo przykład na poparcie tezy — to, na co wskazujesz, gdy ktoś prosi o dowód.",
        "Adwokatka przytoczyła trzech świadków na poparcie alibi klientki.",
        "ku",
        "prowadzić",
    ),
    "peregrinations": (
        "Podróże albo wędrówki, zwłaszcza długie albo rozległe.",
        "Długie, błąkające się drogi — ten rodzaj tułaczki, który trzyma cię daleko od domu przez dobry czas.",
        "Jego peregrynacje przez trzy kontynenty wypełniły całą półkę dzienników podróży.",
        "przez",
        "pole, ziemia (peregrinus: obcy)",
    ),
    "mendicant": (
        "Żebrak, albo ktoś żyjący z jałmużny.",
        "Ktoś, kto żyje, prosząc o jałmużnę — historycznie także mnisi, którzy ślubowali ubóstwo i żyli z darów.",
        "Bracia żebrzący nic nie posiadali i całkowicie polegali na dobroci wieśniaków.",
        "żebrać",
        "żebrak",
    ),
    "munificent": (
        "Niezmiernie hojny.",
        "Hojny w niemal teatralnej skali — dar, przy którym ludzie na chwilę wstrzymują oddech.",
        "Hojny dar sfinansował całe nowe skrzydło biblioteki.",
        "dar, usługa",
        "czyniący, dający",
    ),
    "inanition": (
        "Wyczerpanie z braku pożywienia; także brak żywotności.",
        "Słaby, opróżniony stan z braku karmienia — dosłownie z głodu, albo w przenośni z braku paliwa.",
        "Pod koniec oblężenia żołnierze byli bliscy wycieńczenia.",
        "pusty, marny",
        "akt albo wynik",
    ),
    "vituperation": (
        "Gorzka, obelżywa krytyka.",
        "Krytyka, która dawno minęła to, co sprawiedliwe, i stała się złą, gorzką tyradą.",
        "Komentarze internetowe rozpłynęły się w czyste wyzwiska w kilka minut.",
        "wada, błąd",
        "przygotować, dostarczyć",
    ),
    "inimical": (
        "Wrogi, szkodliwy w skutkach.",
        "Działający przeciwko tobie, nawet po cichu — warunki albo postawy nieprzyjazne twoim interesom.",
        "Nowa polityka była wroga małym firmom, nawet jeśli to nie był zamiar.",
        "nie",
        "przyjaciel",
    ),
    "invidious": (
        "Skłonny budzić urazę, często przez niesprawiedliwe porównania.",
        "Pewne, że ktoś poczuje się urażony — zwykle dlatego, że stawia się ludzi albo rzeczy w nierównej konkurencji.",
        "Szeregować rodzeństwo według „kogo mama kocha najbardziej” to nikczemna gra, w którą nikt nie powinien grać.",
        "zazdrość",
        "spoglądać (niechętnie)",
    ),
    "subaltern": (
        "Osoba niższego stopnia albo statusu; podwładny.",
        "Ktoś niżej w łańcuchu dowodzenia albo na drabinie społecznej — junior pod kimś z większą władzą.",
        "Jako młody oficer niższej rangi długo przyjmował rozkazy, zanim sam je wydawał.",
        "pod",
        "alternatywny, inny",
    ),
    "execrate": (
        "Odczuwać albo wyrażać silną nienawiść.",
        "Tak bardzo czymś gardzić, że przeklina się to głośno — czysta, głośna odraza.",
        "Wieśniacy przeklinali poborcę podatków za każdym razem, gdy jego wóz toczył się przez miasteczko.",
        "z, poza",
        "święty (przekląć, wyrzucić ze świętego)",
    ),
    "integument": (
        "Naturalna zewnętrzna osłona, jak skóra albo skorupa.",
        "Ochronne opakowanie natury — skóra, skorupa, łuska albo kora, cokolwiek okrywa i chroni żywą istotę.",
        "Skorupa żółwia to niezwykle twarda powłoka.",
        "na, ponad",
        "okrywać",
    ),
    "ingenuous": (
        "Niewinny, naiwny, o dziecięcej prostocie; przeciwieństwo przebiegłego.",
        "Otwarcie ufny i trochę naiwny, bez ukrytego celu — łatwo pomylić z „ingenious”, które znaczy pomysłowy.",
        "Jej naiwne pytanie — „dlaczego ktokolwiek miałby o tym kłamać?” — pokazywało, jak mało miała przebiegłości.",
        "w, rodzimy",
        "płodzić (wolno urodzony, szczery)",
    ),
    "pedantry": (
        "Nadmierna troska o drobne szczegóły albo reguły.",
        "Zgubić się w drobnych regułach i przegapić szerszy obraz — obsesja na punkcie drobnego druku, który nikogo innego nie obchodzi.",
        "Jego pedanteria o przecinkach oksfordzkich wykoleiła całe spotkanie.",
        "nauczyciel dzieci",
        "praktyka albo jakość",
    ),
    "perscrutation": (
        "Dokładne, staranne zbadanie.",
        "Głębokie spojrzenie, które nie zostawia kamienia nieobróconego — przejść każdy szczegół z prawdziwą troską.",
        "Dopiero po starannym przeszukaniu ksiąg wyszła rozbieżność.",
        "przez, gruntownie",
        "szukać, badać",
    ),
    "demur": (
        "Wnosić zastrzeżenia; okazywać niechęć.",
        "Grzecznie się wycofać albo zawahać zamiast iść od razu — miękkie „chwileczkę”.",
        "Gdy poproszono ją, by podpisała bez czytania, zaoponowała.",
        "od, precz",
        "zwlekać",
    ),
    "specious": (
        "Powierzchownie wiarygodny, ale w rzeczywistości fałszywy.",
        "Brzmi przekonująco na pierwszy rzut oka, ale rozpada się, gdy naprawdę sprawdzisz.",
        "„Everyone's doing it” to pozorny argument, który nigdy do końca nie wytrzymuje badania.",
        "wygląd, pozór",
        "pełen (pięknie wyglądający)",
    ),
    "cant": (
        "Nieszczera, hipokrytyczna mowa, często moralizująca.",
        "Kaznodziejska mowa, która brzmi cnotliwie bez prawdziwego uczucia — moralna poza na autopilocie.",
        "Miał dość korporacyjnego frazesu o „rodzinie” z firmy, która nigdy nie dawała wolnego.",
        "śpiewać (później: śpiewny żargon)",
        "jękliwa mowa żebraków, potem hipokryzja",
    ),
    "pusillanimous": (
        "Pozbawiony odwagi, tchórzliwy.",
        "Bojaźliwy aż do braku kręgosłupa — zbyt przestraszony, by się podnieść, nawet gdy wyraźnie o to chodzi.",
        "Małoduszne milczenie zarządu pozwoliło skandalowi wymknąć się spod kontroli.",
        "bardzo mały",
        "duch, odwaga",
    ),
    "vulpine": (
        "Lisowaty; chytry, przebiegły.",
        "Chytry i sprytny jak lis — bystry, trochę krętacki, zawsze o krok do przodu.",
        "Puścił lisi uśmiech w chwili, gdy zauważył lukę.",
        "lis",
        "od albo jak",
    ),
    "seriatim": (
        "Jeden po drugim, po kolei.",
        "Brane ściśle po jednemu, w porządku — bez przeskakiwania, bez robienia dwóch naraz.",
        "Sędzia rozpatrzył każde z dwunastu roszczeń po kolei.",
        "rząd, sekwencja",
        "jeden po drugim",
    ),
    "parsimony": (
        "Skrajna oszczędność; skąpstwo.",
        "Być ciasnym z pieniędzmi (albo słowami, albo zasobami) daleko poza rozsądną oszczędność.",
        "Jego skąpstwo było legendarne — używał torebek herbaty trzy razy.",
        "oszczędzać, być oszczędnym",
        "stan albo praktyka",
    ),
    "emendation": (
        "Poprawka, zwłaszcza w tekście.",
        "Poprawka w piśmie — uczony retusz, który prostuje błąd w starym albo ważnym tekście.",
        "Nowe wydanie zawiera dziesiątki poprawek oryginalnego rękopisu.",
        "z, na zewnątrz",
        "wada, błąd",
    ),
    "abstemious": (
        "Umiarkowany w jedzeniu i piciu.",
        "Świadomie powściągliwy przy stole — nigdy za dużo, zawsze trochę zostawić na talerzu.",
        "Jego wstrzemięźliwe nawyki trzymały go bystrym długo po tym, jak rówieśnicy zwolnili.",
        "z dala od",
        "napój odurzający",
    ),
    "solecism": (
        "Błąd gramatyczny albo uchybienie etykiecie.",
        "Poślizg w gramatyce albo manierach — drobny błąd, od którego pedant się wzdryga.",
        "„Between you and I” to częsty solecyzm, od którego gramatycy wciąż się wzdrygają.",
        "cylicyjskie miasto znane z „złego” greckiego",
        "praktyka, sposób",
    ),
    "internecine": (
        "Dotyczący konfliktu wewnątrz grupy; wzajemnie niszczący.",
        "Wewnętrzne kłótnie, które rozdzierają grupę od środka — walka, w której wszyscy przegrywają, bo to rodzina przeciw rodzinie.",
        "Bratobójcze swary partii zrobiły więcej szkody niż jakikolwiek zewnętrzny przeciwnik.",
        "między, wśród",
        "zabijać",
    ),
    "pococurante": (
        "Obojętna, niedbała postawa.",
        "Wzruszenie ramionami zamienione w osobowość — tak mało dbać o to, co kiedyś miało znaczenie, że nic już nie wydaje się warte wysiłku.",
        "Jego obojętny stosunek do gali nagród zaskoczył wszystkich, którzy wiedzieli, jak ciężko pracował.",
        "mało",
        "dbać",
    ),
    "imbroglio": (
        "Splątana, skomplikowana sytuacja albo spór.",
        "Splątany, niechlujny bałagan trudny do rozwikłania — część nieporozumienia, część dramatu, cała dezorientacja.",
        "Cały zamęt wokół planu stołów zaczął się od jednej źle położonej wizytówki.",
        "w",
        "plątać, mieszać",
    ),
    "minatory": (
        "Groźny, złowieszczy.",
        "Z nieomylnym powiewem groźby — groźne spojrzenie albo list jasno mówi, że może nastąpić coś złego.",
        "Groźny ton listu spłoszył lokatorkę, zanim jeszcze otworzyła kopertę.",
        "grozić",
        "służący do",
    ),
    "obloquy": (
        "Silna publiczna krytyka albo obelgi.",
        "Głośne, publiczne potępienie — paląca krytyka, która rozgrywa się na oczach wszystkich.",
        "Sygnalistka znosiła lata publicznej niesławy, zanim historia przyznała jej rację.",
        "przeciw",
        "mówić",
    ),
    "paroxysm": (
        "Nagły gwałtowny wybuch emocji albo działania.",
        "Nagły, intensywny poryw, który zalewa cię od razu — atak śmiechu, gniewu albo kaszlu jak fala.",
        "Porwał ją paroksyzm śmiechu, którego nie potrafiła wyjaśnić nikomu innemu w pokoju.",
        "poza",
        "ostry, nagły",
    ),
    "adscititious": (
        "Dodany z zewnątrz, nie właściwy.",
        "Przykręcony z zewnątrz zamiast wbudowany od początku — dodatek, nie rdzeń.",
        "Komentarz wydaje się naddany, jakby był przyklejony do już skończonego tekstu.",
        "ku, dodatkowo",
        "zatwierdzać, przyjmować",
    ),
    "nescience": (
        "Brak wiedzy, niewiedza.",
        "Zwykłe nie-wiedzenie — luka w wiedzy, bez osądu przyklejonego z góry.",
        "Przyznał się do niewiedzy o francuskim winie i pozwolił wybrać sommelierowi.",
        "nie",
        "wiedzieć",
    ),
    "prurience": (
        "Nadmierne zainteresowanie sprawami seksualnymi.",
        "Zbyt chciwa, lubieżna ciekawość wszystkiego pikantnego — zainteresowanie, które minęło zdrowe i stało się wścibskie.",
        "Lubieżność brukowca wobec prywatnego życia pary ocierała się o obsesję.",
        "swędzieć, pragnąć",
        "stan",
    ),
    "fuliginous": (
        "Sadzowy, ciemny, mętny.",
        "Ciemny i dymny, jakby wszystko pokrywała cienka warstwa sadzy.",
        "Sadzowa mgła wisiała o zmierzchu nad miastem fabrycznym.",
        "sadza",
        "pełen",
    ),
    "gainsay": (
        "Zaprzeczyć albo sprzeciwić się.",
        "Otwarcie mówić przeciwko temu, co ktoś inny powiedział — powiedzieć, że tak nie jest.",
        "Nikt nie odważył się zaprzeczyć relacji starego kapitana o burzy.",
        "przeciw",
        "mówić",
    ),
    "ignavia": (
        "Lenistwo, gnuśność (z łaciny).",
        "Stare łacińskie słowo na czyste lenistwo — ciężar niechcenia czegokolwiek.",
        "Mnisi głosili przeciw gnuśności jako jednemu z cichych niebezpieczeństw duszy.",
        "nie",
        "zajęty, pilny",
    ),
    "escutcheon": (
        "Tarcza ukazująca herb.",
        "Tarczowaty emblemat z herbem rodziny — jej heraldyczny znak.",
        "Herb rodziny wciąż wisi nad drzwiami starego dworu.",
        "tarcza",
        "zdrobnienie / przedmiot",
    ),
    "superannuated": (
        "Przestarzały, nieużywany albo wycofany z racji wieku.",
        "Pożyteczny czas minął i odstawiony na boczny tor — zbyt staromodny albo zużyty, by dalej robić robotę.",
        "Przestarzała drukarka została wreszcie wymieniona po piętnastu latach zacięć.",
        "poza",
        "rok",
    ),
    "succedanea": (
        "Substytuty, zwłaszcza w medycynie.",
        "Zastępcze środki, gdy brakuje prawdziwego leczenia — medyczne dublerzy, w gruncie rzeczy.",
        "Lekarze wojenni często opierali się na surogatach, gdy kończyły się prawdziwe leki.",
        "zamiast",
        "iść, ustępować",
    ),
    "rodomontade": (
        "Chełpliwa, pyszałkowata mowa.",
        "Wielkie, hałaśliwe przechwałki — głośne mówienie o własnej wielkości, które jest głównie gorącym powietrzem.",
        "Jego przechwałki o ocaleniu projektu „w pojedynkę” nie oszukały nikogo, kto tam naprawdę był.",
        "chełpliwy rycerz w Orlando Szalonym",
        "działanie, pokaz",
    ),
    "chicane": (
        "Użyć podstępu albo oszustwa, by coś osiągnąć.",
        "Dojść do celu fortelami zamiast uczciwą grą.",
        "Wykrętami wszedł w interes umową pełną drobnego druku.",
        "kręcić, oszukiwać",
        "fortel; później ostry zakręt",
    ),
    "mathesis": (
        "Czysta albo abstrakcyjna nauka uczenia się albo wiedzy, często matematyka.",
        "Uczenie się w najczystszej, najbardziej abstrakcyjnej formie — głęboka struktura samej wiedzy, zwłaszcza matematycznej.",
        "Filozof marzył o uniwersalnej mathesis, która zjednoczyłaby każde pole wiedzy.",
        "uczyć się",
        "akt uczenia się",
    ),
    "pedantic": (
        "Nadmiernie zajęty formalnymi regułami albo trywialnymi szczegółami.",
        "Zbyt surowy wobec drobiazgów — poprawianie drobnych technicznych punktów, które nic istotnego nie zmieniają.",
        "Trochę pedantyczne było spierać się o „who” kontra „whom” w wiadomości tekstowej.",
        "przewodnik dzieci, nauczyciel",
        "mający sposób",
    ),
    "coruscation": (
        "Błysk iskrzącego światła.",
        "Szybki, błyszczący błysk — słońce na wodzie albo diament łapiący światło.",
        "Migotanie żyrandola rozsiewało światło w każdy kąt sali balowej.",
        "iskrzyć, błyskać",
        "akt",
    ),
    "tyro": (
        "Początkujący, nowicjusz.",
        "Ktoś zupełnie nowy w umiejętności albo dziedzinie — wciąż uczy się sztuczek, jeszcze nie znawca.",
        "Nawet początkujący szachista zauważy ten błąd.",
        "rekrut, nowicjusz",
        "surowy młody żołnierz",
    ),
    "execrable": (
        "Niezmiernie zły, wstrętny.",
        "Zły w sposób zasługujący na prawdziwy wstręt — nie tylko nijaki, ale naprawdę okropny.",
        "Recenzent nazwał sequel obrzydliwym, a kasa kinowa przyznała mu rację.",
        "przeklinać",
        "godny, zdolny być",
    ),
    "incarnadine": (
        "Krwistoczerwony.",
        "Głęboka, jaskrawa czerwień — kolor świeżej krwi, wsławiony przez Makbeta Szekspira.",
        "Zachód słońca zabarwił całe niebo na krwistoczerwoną poświatę.",
        "w, do",
        "ciało (cielistoczerwony)",
    ),
    "interstice": (
        "Mała szczelina albo przestrzeń między rzeczami.",
        "Drobna przestrzeń między, którą łatwo przeoczyć — szpara między deskami, luka w kalendarzu.",
        "Chwasty pchały się przez każdą szczelinę starej ceglanej ścieżki.",
        "między",
        "stać",
    ),
    "animadversion": (
        "Krytyczne albo cenzorskie uwagi.",
        "Ostre, dezaprobujące komentarze — krytyka z odrobiną karcenia.",
        "Uwagi krytyczne profesora do eseju wypełniły marginesy czerwonym atramentem.",
        "umysł",
        "zwracać się ku",
    ),
    "irrefragable": (
        "Niemożliwy do obalenia, niezaprzeczalny.",
        "Tak solidnie udowodniony, że nie ma argumentu przeciw — sprawa jest zamknięta.",
        "Dowód DNA był niezbity, a proces skończył się w ciągu godziny.",
        "nie",
        "sprzeciwiać się, opierać",
    ),
    "involution": (
        "Złożoność, zawiłość; także zwijanie do wewnątrz.",
        "Splątana, złożona w sobie złożoność — rzeczy tak ciasno owinięte, że trudno je rozdzielić.",
        "Zawiłość fabuły zostawiła połowę publiczności rozplątującą ją po napisach.",
        "w, do wewnątrz",
        "toczyć, obracać",
    ),
    "dint": (
        "Siła albo wysiłek, jak w „by dint of”.",
        "Czysta siła albo wysiłek — przetrwa głównie w zwrocie „by dint of”.",
        "Zdał egzamin dzięki czystej, upartej praktyce.",
        "cios, uderzenie",
        "siłą",
    ),
    "mortised": (
        "Połączony czopem i gniazdem; ciasno spasowany.",
        "Zaryglowany na starą stolarską modłę — jeden kawałek wchodzi równo w otwór wycięty właśnie dla niego.",
        "Belki starej stodoły były połączone na czopy bez jednego gwoździa.",
        "gniazdo, otwór",
        "ugryzienie, chwyt",
    ),
    "apposite": (
        "Niezwykle trafny, stosowny.",
        "Dokładnie to, czego chwila potrzebowała — uwaga, cytat albo przykład, który trafia w punkt.",
        "Jej trafna uwaga streściła całą debatę w jednym zdaniu.",
        "ku",
        "umieszczać",
    ),
    "lambent": (
        "Miękko jarzący albo migoczący (światło); także lekki dowcip.",
        "Łagodny blask zamiast pożaru — miękki, migoczący płomień albo dowcip igrający raczej niż ostry.",
        "Światło świec rzucało migotliwą poświatę na stary pokój jadalny.",
        "lizać",
        "czyniący (światło, które „liże”)",
    ),
    "anchorite": (
        "Religijny pustelnik żyjący w odosobnieniu.",
        "Ktoś, kto całkowicie wycofuje się ze świata, by żyć sam w modlitwie i refleksji.",
        "Anachoreta mieszkał ponad trzydzieści lat w małej celi przy kościele.",
        "wstecz, precz",
        "wycofywać się",
    ),
    "slake": (
        "Uśmierzyć pragnienie; ugasić.",
        "W pełni zaspokoić pragnienie — najczęściej pragnienie, ale w przenośni każdą głęboką potrzebę.",
        "Jedna zimna szklanka wody ugasiła jego pragnienie po długiej wędrówce.",
        "luźny, obwisły",
        "poluzować, uśmierzyć",
    ),
    "acicular": (
        "Igiełkowaty.",
        "Długi, cienki i zaostrzony jak igła — kształt igły sosny albo ostrego kryształka.",
        "Sosny łatwo rozpoznać po igiełkowatych liściach.",
        "igła",
        "mały",
    ),
    "effete": (
        "Wyczerpany z żywotności, słaby, zbyt wyrafinowany.",
        "Zużyty i miękki — straciwszy pierwotną siłę przez zbyt wiele wygody albo wyrafinowania.",
        "Krytycy nazwali niegdyś odważne pismo wyjałowionym, cieniem jego śmiałych wczesnych lat.",
        "na zewnątrz",
        "płodny, który wydał",
    ),
    "appurtenance": (
        "Dodatek albo drobny przyłączony przedmiot albo prawo.",
        "Mały extra przy czymś większym — akcesoria i przybudówki, które idą z rzeczą główną.",
        "Najem obejmował garaż i wszystkie jego przynależności.",
        "ku",
        "należeć",
    ),
    "gloze": (
        "Zatuszować albo pomniejszyć winę.",
        "Wygładzić pomyłkę miękkimi słowami, by brzmiała mniejsza, niż jest.",
        "Próbował zatuszować przegapiony termin mglistą gadaniną o „nieprzewidzianych trudnościach”.",
        "glosa, wyjaśnienie",
        "komentować — potem wygładzać",
    ),
    "incipient": (
        "We wczesnym stadium, dopiero się zaczynający.",
        "Dopiero zaczynający się pokazywać — najwcześniejsze, ledwie widoczne stadium czegoś większego.",
        "Lekarze złapali początkowe oznaki choroby, zanim zdążyła się rozprzestrzenić.",
        "na, do",
        "brać (podejmować, zaczynać)",
    ),
    "afflatus": (
        "Twórcze natchnienie, zwłaszcza boskie.",
        "Nagły poryw natchnienia większy od ciebie — jakby pomysł został ci tchnięty skądinąd.",
        "Poeta opisał, jak cały utwór przyszedł w jednym przypływie natchnienia o trzeciej nad ranem.",
        "ku, na",
        "dmuchać (tchnienie na)",
    ),
}
