# French (France) overlays: (definition, friendly, exampleGloss, root1, root2)
WORDS = {
    "edulcorate": (
        "Sucrer ou purifier ; ôter à quelque chose son âpreté.",
        "Enlever l’aiguillon ou l’amertume — sucrer au propre, ou adoucir au figuré une idée trop rude pour qu’elle passe mieux.",
        "Le rédacteur edulcorated la critique cinglante avant qu’elle parte à l’impression.",
        "hors, à fond",
        "doux, sucré",
    ),
    "pietistic": (
        "Excessivement ou faussement religieux ou pieux.",
        "Décrit quelqu’un dont la dévotion sent le spectacle : plus de pose que de foi vraie.",
        "Ses soupirs pietistic pendant le sermon agaçaient le reste du banc.",
        "piété, sentiment du devoir",
        "ayant le caractère de",
    ),
    "amphiboly": (
        "Ambiguïté née de la construction grammaticale — une phrase lisible de deux façons.",
        "Une phrase grammaticalement correcte, mais qu’on peut lire de deux manières tout à fait différentes, comme « Visiting relatives can be tiring ».",
        "« Visiting relatives can be tiring » est une amphiboly classique — ce sont les parents qui fatiguent, ou le fait de leur rendre visite ?",
        "les deux, des deux côtés",
        "jeter",
    ),
    "trenchant": (
        "Tranchant, incisif, allant droit au but.",
        "Coupe net dans le superflu — un propos ou un esprit trenchant va au cœur de l’affaire, sans un mot de trop.",
        "Sa critique trenchant ne laissait aucun trou du scénario où se cacher.",
        "couper",
        "faisant, ayant la qualité de",
    ),
    "inchoative": (
        "À peine commencé ; à un stade précoce ou rudimentaire.",
        "Encore dans les tout premiers instants — un plan, un sentiment ou un processus qui commence seulement à prendre forme.",
        "Les stades inchoative du traité étaient prometteurs, mais bien des détails restaient en suspens.",
        "commencer, débuter",
        "tendant vers",
    ),
    "panegyric": (
        "Un discours ou un écrit formel qui loue quelqu’un avec éclat.",
        "Un hommage en grande pompe — pensez à un éloge funèbre lumineux, ou à un discours qui chante les hauts faits de quelqu’un sur tous les toits.",
        "La professeure partant à la retraite fut saluée d’un panegyric de ses étudiants les plus proches.",
        "tout, entier",
        "assemblée, rassemblement",
    ),
    "ontic": (
        "Relatif à l’existence réelle, par opposition à la théorie abstraite.",
        "Des choses telles qu’elles existent vraiment, et non comme simples idées ou théories à leur sujet.",
        "Les philosophes débattent si les nombres ont un statut ontic quelconque, ou n’existent que dans nos têtes.",
        "être, ce qui existe",
        "relatif à",
    ),
    "fructify": (
        "Porter du fruit, ou devenir productif.",
        "Enfin porter ses fruits — un effort, une idée ou un placement qui fructifies est passé de la graine à quelque chose d’utile.",
        "Des années de recherche discrète fructified enfin en un vaccin qui fonctionne.",
        "fruit",
        "faire, causer",
    ),
    "proleptical": (
        "Anticiper ou représenter une chose comme déjà faite avant qu’elle n’arrive.",
        "Brûler les étapes de façon littéraire — décrire un événement futur comme s’il était déjà clos, pour que le propos frappe plus fort.",
        "Le toast proleptical du général à « victory » fut porté une semaine entière avant la bataille.",
        "avant",
        "prendre, saisir",
    ),
    "pneumatic": (
        "Actionné par la pression de l’air ; aussi relatif à l’esprit ou au souffle.",
        "Le plus souvent : mû par l’air comprimé — un marteau-piqueur, un frein de bus — mais la même racine grecque parle aussi du souffle et de l’esprit.",
        "Les freins pneumatic sifflèrent quand le bus s’arrêta au trottoir.",
        "vent, souffle, esprit",
        "relatif à",
    ),
    "cataphatic": (
        "Décrire Dieu ou le divin par des énoncés positifs — le contraire d’apophatique.",
        "Parler de Dieu en disant ce qu’il est — « Dieu est amour », « Dieu est juste » — plutôt que seulement ce qu’il n’est pas.",
        "La théologie cataphatic parle avec assurance de Dieu comme aimant, juste et miséricordieux.",
        "vers le bas, selon",
        "parler, dire",
    ),
    "fiducial": (
        "Fondé sur la confiance ou la foi ; aussi : un point de référence fixe.",
        "Quelque chose que l’on prend sur parole, puis dont on se sert d’ancre — une marque fiducial est le point fixe à partir duquel on mesure tout le reste.",
        "Les géomètres placèrent un repère fiducial dans le roc avant de cartographier le site.",
        "faire confiance",
        "confiance, assurance",
    ),
    "theodicy": (
        "Une défense de la bonté de Dieu face à l’existence du mal.",
        "La très vieille tentative de répondre : si Dieu est bon, pourquoi le mal ? — sans renoncer à l’une ou l’autre affirmation.",
        "Sa thèse explorait theodicy à travers le prisme du Livre de Job.",
        "dieu",
        "justice",
    ),
    "circumincession": (
        "Inhabitation mutuelle — terme théologique pour la façon dont les personnes de la Trinité existent l’une dans l’autre.",
        "Un mot de théologie pour un ensemble trois-en-un si complet que chaque part contient les autres et en est contenue.",
        "La doctrine de circumincession cherche à expliquer comment le Père, le Fils et l’Esprit sont distincts et pourtant inséparables.",
        "autour",
        "aller, marcher",
    ),
    "redound": (
        "Avoir une conséquence qui profite à quelqu’un ou se répercute sur lui.",
        "Quand le mérite (ou le blâme) rebondit vers le responsable — les bonnes actions qui redound à votre nom vous reviennent en récompense.",
        "Le succès de l’équipe redound à l’honneur de son entraîneur discret et laborieux.",
        "en arrière, de nouveau",
        "vague",
    ),
    "ineluctable": (
        "Qu’on ne peut éviter ni dont on ne peut s’échapper.",
        "Cela arrivera quoi que vous fassiez — d’une issue ineluctable, on ne se dégage pas.",
        "La vieillesse vient pour tout le monde ; c’est simplement ineluctable.",
        "ne pas",
        "s’extirper en luttant",
    ),
    "periphrastic": (
        "Qui emploie un détour verbeux plutôt qu’une forme directe.",
        "Prendre le chemin des écoliers avec les mots — dire en toute une phrase ce qu’un seul mot couvrirait.",
        "Ses e-mails periphrastic auraient pu dire en une ligne ce qui lui prenait trois paragraphes.",
        "autour",
        "déclarer, raconter",
    ),
    "hebetude": (
        "Émoussement mental ou léthargie.",
        "Cet état d’esprit brumeux et lent où penser revient à patauger dans du sirop.",
        "Une vague de hebetude s’abattit sur la classe juste après le déjeuner.",
        "émoussé, obtus",
        "état ou qualité",
    ),
    "unpropitious": (
        "Peu favorable ; de mauvais augure.",
        "Mauvais signe — des conditions ou un timing qui semblent déjà jouer contre vous avant même d’avoir commencé.",
        "Ciel gris et batterie à plat firent un départ unpropitious pour le voyage.",
        "ne pas",
        "favorable, bienveillant",
    ),
    "fricaseed": (
        "Viande étuvée ou braisée en sauce — correctement orthographié « fricasseed ».",
        "Un vieux terme de cuisine douillet pour de la viande coupée et mijotée lentement dans sa propre sauce jusqu’à tendreté.",
        "Le poulet fricasseed de grand-mère était le clou de chaque dîner du dimanche.",
        "frire",
        "casser (en morceaux)",
    ),
    "ersatz": (
        "Un substitut artificiel ou de moindre qualité.",
        "Une contrefaçon qui tient lieu de l’original — ça fait l’affaire, mais tout le monde voit que ce n’est pas le vrai.",
        "En temps de guerre, les clients se contentaient de café ersatz infusé de chicorée torréfiée.",
        "hors, préfixe de remplacement",
        "poser, placer",
    ),
    "reify": (
        "Traiter une idée abstraite comme si c’était une chose concrète.",
        "Rendre une idée solide et réelle — transformer quelque chose de flou, comme « le marché », en un objet qu’on peut montrer du doigt.",
        "Faire de l’« esprit » d’une nation un être à part reifies quelque chose qui n’est en réalité que des millions de choix individuels.",
        "chose",
        "faire",
    ),
    "eluded": (
        "S’être échappé ou avoir évité avec habileté.",
        "Glissé au large sans accroc — esquivé quelque chose, souvent avec ruse ou de justesse, que ce soit une capture, une question ou une réponse.",
        "La réponse eluded pendant des heures, jusqu’à ce qu’elle cliquette d’un coup sous la douche.",
        "hors, loin",
        "jouer",
    ),
    "aporetic": (
        "Qui exprime le doute, l’embarras, ou une contradiction non résolue.",
        "Bloqué à une vraie impasse de pensée — non par paresse, mais parce que la question elle-même refuse une réponse nette.",
        "Socrate terminait souvent ses dialogues sur une note aporetic, avec plus de questions que de réponses.",
        "sans",
        "passage, voie",
    ),
    "metonymy": (
        "Figure qui nomme une chose par un terme associé, par exemple « la couronne » pour le souverain.",
        "Laisser un mot voisin tenir lieu de la chose même — dire « Wall Street » quand on veut dire la Bourse.",
        "« Wall Street had a rough day » est une metonymy — cela veut dire en réalité que la Bourse a mal tourné.",
        "changement, après",
        "nom",
    ),
    "deracinate": (
        "Déraciner ; arracher à un milieu naturel.",
        "Arracher quelque chose (ou quelqu’un) avec ses racines, loin du lieu ou de la culture où il appartient.",
        "La guerre deracinated toute une génération, dispersant les familles par-delà les frontières.",
        "loin, hors",
        "racine",
    ),
    "euphonious": (
        "D’un son agréable.",
        "Tout simplement beau à l’oreille — un mot ou une phrase euphonious glisse, presque en musique.",
        "« Murmuring brook » est une petite phrase euphonious, douce et facile à dire.",
        "bon, bien",
        "son, voix",
    ),
    "putative": (
        "Généralement supposé ou tenu pour tel.",
        "Tenu pour vrai par beaucoup, même sans preuve — la version prétendue ou présumée d’une chose.",
        "L’auteur putative de la lettre se révéla plus tard un parfait inconnu.",
        "penser, considérer",
        "ayant la nature de",
    ),
    "neologism": (
        "Un mot ou une locution nouvellement forgés.",
        "Un mot tout neuf — fraîchement inventé, à peine (ou pas encore) dans le dictionnaire.",
        "« Doomscrolling » a commencé comme neologism et est vite devenu argot courant.",
        "nouveau",
        "mot, parole",
    ),
    "splenetic": (
        "Irrité ou de mauvaise humeur.",
        "D’une humeur maussade, prompte à claquer — comme on croyait jadis que la rate gouvernait le caractère.",
        "Il envoya une réponse splenetic au courriel dans les secondes qui suivirent sa lecture.",
        "rate (siège de la colère)",
        "affecté par",
    ),
    "sententious": (
        "Enclin à moraliser d’un air pompeux ou affecté.",
        "Aime débiter de petites leçons de vie, comme si chaque phrase était un biscuit de bonne aventure.",
        "Son toast sententious sur « the true meaning of friendship » fit regarder tout le monde sa montre.",
        "opinion, maxime",
        "plein de",
    ),
    "garrulous": (
        "Excessivement bavard, surtout sur des riens.",
        "N’en finit plus de parler — radote sur des broutilles longtemps après que les autres n’aient plus rien à dire.",
        "Le chauffeur de taxi garrulous nous raconta toute sa vie avant même que nous ayons quitté l’aéroport.",
        "bavarder, jacasser",
        "enclin à",
    ),
    "fatuity": (
        "Sottise, niaiserie.",
        "La sottise toute simple — une remarque ou un plan si niais qu’il mérite à peine une réponse sérieuse.",
        "La fatuity pure du plan apparut dès qu’ils l’essayèrent.",
        "sot, niais",
        "état d’être",
    ),
    "peroration": (
        "La partie conclusive d’un discours, souvent récapitulative.",
        "Le grand final d’une harangue — le passage où l’orateur rassemble tout et enfonce le clou.",
        "À la peroration, la moitié de la salle était debout.",
        "à travers, jusqu’au bout",
        "parler, plaider",
    ),
    "tautology": (
        "Répétition inutile de la même idée en d’autres mots.",
        "Dire deux fois la même chose sans rien ajouter, comme « cadeau gratuit » ou « it is what it is ».",
        "« It is what it is » est une tautology favorite de ceux qui évitent une vraie explication.",
        "le même",
        "mot, parole",
    ),
    "laconism": (
        "L’emploi de très peu de mots ; un parler laconique.",
        "Dire beaucoup avec très peu — l’art de la réplique courte et sèche, nommé d’après les Spartiates de Laconie, fameux pour leur brièveté.",
        "« Molon labe » — « come and take them » — est le plus célèbre morceau de laconism de l’histoire.",
        "un Spartiate de Laconie",
        "pratique, manière",
    ),
    "pabulum": (
        "Idées fades et trop simplifiées ; à l’origine, une nourriture insipide ou une bouillie.",
        "Une pensée trop diluée — un contenu si simplifié et si sage qu’il n’a plus de valeur nutritive pour l’esprit.",
        "Le discours du politicien n’était guère que du pabulum : des promesses vagues auxquelles on ne pouvait rien accrocher.",
        "nourrir",
        "moyen ou instrument",
    ),
    "soporific": (
        "Qui provoque le sommeil ou l’assoupissement.",
        "Si ennuyeux — ou si littéralement sédatif — que cela donne sommeil. Pensez au lait chaud, ou à une réunion budgétaire de trois heures.",
        "Le ronronnement soporific du cours faisait lutter la moitié de la salle pour garder les yeux ouverts.",
        "sommeil profond",
        "qui fait, qui cause",
    ),
    "unctuous": (
        "Excessivement flatteur ou onctueux dans les manières.",
        "Si lisse dans le charme que cela glisse — une flatterie si épaisse qu’on en sent presque la graisse.",
        "Le vendeur unctuous ne cessait de vanter mon « excellent taste » avant chaque vente additionnelle.",
        "oindre, huiler",
        "plein de",
    ),
    "captious": (
        "Prompt à trouver à redire, trop critique sur des riens.",
        "Pointilleux jusqu’à l’excès — le genre de personne qui trouve un problème à tout, même quand cela n’importe pas.",
        "Ses notes captious sur le rapport ne visaient que la place des virgules.",
        "saisir, prendre",
        "un piège, un sophisme",
    ),
    "torpid": (
        "Lent, inactif d’esprit ou de corps.",
        "Lent et à demi endormi, comme un ours en hibernation — à peine un geste, à peine une pensée.",
        "Le bureau tomba torpid sous la lourde chaleur d’août.",
        "être engourdi, être lent",
        "dans un état de",
    ),
    "seneschal": (
        "Un intendant ou officier gérant une maison médiévale.",
        "La version médiévale d’un chef de maison — l’officier de confiance qui tenait au quotidien le logis et le domaine d’un seigneur.",
        "Le seneschal du château gérait tout, des comptes de récolte à la liste des invités.",
        "vieux, aîné",
        "serviteur",
    ),
    "expatiate": (
        "S’étendre longuement, à l’oral ou à l’écrit, sur un sujet.",
        "Vraiment s’élancer sur un thème — en parler ou en écrire sans fin, sous tous les angles.",
        "Parlez-lui de voitures anciennes et il va expatiate pendant une bonne heure.",
        "hors",
        "espace",
    ),
    "nugatory": (
        "Sans valeur, futile ; aussi invalide ou inefficace.",
        "Ne valant à peu près rien — une clause nugatory dans un contrat ne fait, en pratique, rien du tout.",
        "Le tribunal déclara l’ancien règlement nugatory, puisqu’il n’avait jamais été appliqué.",
        "futilités, sornettes",
        "appartenant à",
    ),
    "sagacity": (
        "Sagesse, jugement perspicace.",
        "Une sagesse vive et pratique — le bon jugement qui vient de l’expérience, pas seulement des livres.",
        "La sagacity du vieux capitaine garda l’équipage hors d’affaire plus d’une fois.",
        "au flair vif, perspicace",
        "qualité de",
    ),
    "canaille": (
        "La populace ou la masse, employé avec mépris.",
        "Un mot snob et méprisant pour les gens ordinaires, comme s’ils étaient une meute de chiens.",
        "Le comte ricana devant la canaille rassemblée hors des grilles du palais.",
        "chien",
        "collectif, meute",
    ),
    "contumely": (
        "Un traitement ou un langage insolent et humiliant.",
        "Un traitement cruel, méprisant, fait pour humilier — l’insulte conçue pour brûler.",
        "Il endura des années de contumely des critiques avant que son œuvre fût enfin reconnue.",
        "avec, à fond",
        "enfler (d’orgueil)",
    ),
    "askance": (
        "Avec soupçon ou désapprobation ; un regard de biais.",
        "Le regard de côté que l’on jette à ce dont on ne se fie pas tout à fait — un regard chargé de doute.",
        "L’enseignante regarda askance le devoir suspectement soigné.",
        "vers, à",
        "biais, penchant",
    ),
    "clodpate": (
        "Un benêt ; une tête de bois.",
        "Une injure un peu ancienne, presque affectueuse, pour quelqu’un de lent d’esprit — une tête de bois.",
        "« You clodpate », rit-elle, « you've had the map upside down the whole time. »",
        "motte de terre",
        "tête",
    ),
    "actuate": (
        "Mettre en mouvement ou en action ; motiver.",
        "Être l’étincelle qui met quelque chose en marche — qu’il s’agisse d’une machine qui s’allume ou d’une personne qui agit enfin sur une idée.",
        "La peur de perdre le contrat actuated toute l’équipe dans un week-end d’heures supplémentaires.",
        "un faire, un pousser",
        "pousser, faire",
    ),
    "peculation": (
        "Détournement de fonds confiés à sa garde.",
        "Voler en silence l’argent qu’on vous avait confié — le détournement, habillé à l’ancienne.",
        "La peculation du trésorier passa inaperçue pendant près de dix ans.",
        "bien privé",
        "bétail, richesse",
    ),
    "demi-monde": (
        "Un groupe tenu pour vivre en marge de la société respectable.",
        "Le demi-monde glamour et louche — des gens qui vivent juste hors des règles du « bon ton ».",
        "Le roman suit une chanteuse dans la demi-monde des cabarets des années 1920.",
        "demi",
        "monde, société",
    ),
    "extant": (
        "Encore existant ; ni éteint ni détruit.",
        "Toujours là aujourd’hui — se dit des vieilles choses (manuscrits, espèces, bâtiments) qui ont survécu.",
        "On ne connaît que trois exemplaires extant de la première impression.",
        "hors",
        "se tenir",
    ),
    "perfidy": (
        "Tromperie ; trahison de la confiance.",
        "Une trahison profonde et délibérée — briser une confiance que quelqu’un était en droit d’attendre de vous.",
        "Le général ne pardonna jamais la perfidy de son vieil ami à la table des négociations.",
        "à travers, contre",
        "foi, confiance",
    ),
    "patois": (
        "Un dialecte régional, surtout non standard.",
        "La façon bien à soi, locale, de parler dans une région — pleine de mots et de rythmes qu’un étranger n’attrape pas.",
        "Sa grand-mère parlait encore le patois de l’île aux dîners de famille.",
        "parler rude, dialecte",
        "patte — parler maladroit",
    ),
    "prerogative": (
        "Un droit spécial appartenant à une personne ou à un groupe.",
        "Un privilège qui n’appartient qu’à vous — un droit qui vient avec le rôle, la place ou le rang.",
        "Choisir la destination des vacances familiales est la prerogative de Grandpa, et tout le monde le sait.",
        "avant",
        "demander, voter",
    ),
    "hardihood": (
        "Hardiesse, audace ; aussi robustesse ou endurance.",
        "Une résilience rude et courageuse — le cran d’avancer et la ténacité de tenir une fois en route.",
        "Il fallut une vraie hardihood pour franchir le col dans la tempête de neige, sans carte.",
        "hardi, robuste",
        "état, condition",
    ),
    "effloresce": (
        "Éclore ; aussi se développer ou apparaître peu à peu.",
        "S’épanouir jusqu’à s’exprimer pleinement — comme une fleur qui s’ouvre, ou une idée qui trouve enfin sa forme.",
        "Son talent discret pour la peinture effloresced dès qu’elle eut un atelier à elle.",
        "hors",
        "commencer à fleurir",
    ),
    "plumb-line": (
        "Un fil à plomb pour juger la verticalité ; au figuré, un étalon de jugement.",
        "Un poids au bout d’un fil qui tombe d’aplomb, pour vérifier si quelque chose est vraiment d’aplomb — et, par extension, toute mesure fixe à laquelle on compare le reste.",
        "Il prenait l’honnêteté de son grand-père comme une sorte de plumb line pour chaque décision.",
        "plomb",
        "corde, mesure",
    ),
    "fain": (
        "Volontiers, de bon gré (archaïque).",
        "Une façon un peu ancienne de dire « volontiers » ou « avec plaisir » — you would fain faire une chose si cela vous plaît.",
        "« I would fain rest here a while », soupira le voyageur.",
        "joyeux, aise",
        "volontiers, de bon gré",
    ),
    "opprobrium": (
        "Une critique publique cinglante, ou le déshonneur.",
        "La honte publique versée sur quelqu’un de façon voyante — le déshonneur d’une désapprobation générale.",
        "Le scandale abattit l’opprobrium public sur toute la firme.",
        "contre",
        "déshonneur, reproche",
    ),
    "mordant": (
        "Vivement sarcastique, mordant d’esprit ou de critique.",
        "De l’esprit qui a de vraies dents — une remarque mordant pique précisément parce qu’elle vise juste.",
        "Ses critiques de films mordant étaient redoutées des réalisateurs et chéries des lecteurs.",
        "mordre",
        "mordant, faisant",
    ),
    "pronunciamento": (
        "Une proclamation formelle, souvent politique ou militaire.",
        "Une grande annonce officielle — d’habitude celle qui déclare un nouveau gouvernement, un soulèvement ou un décret majeur.",
        "Le pronunciamento du général annonça le nouveau gouvernement à l’aube.",
        "en avant",
        "annoncer",
    ),
    "sciolist": (
        "Une personne au savoir superficiel qui se pose en expert.",
        "Quelqu’un qui a frôlé la surface d’un sujet et parle ensuite comme s’il en avait écrit le manuel.",
        "Le sciolist du dîner corrigea avec aplomb le véritable astrophysicien à table.",
        "savoir",
        "diminutif — un petit connaisseur",
    ),
    "dotage": (
        "Le déclin des facultés mentales dans la vieillesse.",
        "La période brumeuse et oublieuse du grand âge, quand la vivacité de l’esprit commence à s’effacer.",
        "Dans sa dotage, il racontait les mêmes trois histoires à chaque visite, chaque fois comme si c’était neuf.",
        "radoter, être sot",
        "état ou résultat",
    ),
    "lee-side": (
        "Le côté abrité du vent.",
        "Le côté calme et abrité de quelque chose — colline, navire, mur — où le vent ne vous atteint plus tout à fait.",
        "Les randonneurs plantèrent leur tente du lee side de la crête pour échapper aux rafales.",
        "abri, protection",
        "flanc, face",
    ),
    "parry": (
        "Détourner ou parer un coup, une question ou un argument.",
        "Écarter d’un geste souple — un coup d’épée, une question gênante, une accusation — sans perdre une seconde.",
        "Elle parried la question retorse du reporter d’une plaisanterie aisée.",
        "parer, écarter",
        "préparer, défendre",
    ),
    "mephitic": (
        "Nauséabond, nocif.",
        "D’une odeur presque toxique — une puanteur si forte qu’il semble dangereux de respirer.",
        "Une odeur mephitic monta du marais au coucher du soleil.",
        "vapeur nocive",
        "ayant la nature de",
    ),
    "sybarite": (
        "Une personne vouée au luxe et au plaisir.",
        "Quelqu’un qui vit pour le confort et l’indulgence — bonne chère, lits moelleux, vie facile — nommé d’après Sybaris, cité grecque fameuse pour ses excès.",
        "Vrai sybarite, il refusait toute chambre d’hôtel sans baignoire.",
        "cité grecque antique fameuse pour le luxe",
        "habitant de",
    ),
    "prescind": (
        "Écarter délibérément ou ignorer une part de quelque chose.",
        "Mettre de côté, dans l’esprit, un morceau du puzzle, pour regarder nettement le reste.",
        "Prescind un instant du coût et demandons seulement si le plan marche vraiment.",
        "avant, loin",
        "couper",
    ),
    "excoriate": (
        "Critiquer sévèrement ; aussi, arracher la peau.",
        "Écharper quelqu’un d’une critique féroce — comme si l’on arrachait littéralement la peau.",
        "Les critiques excoriated la suite pour avoir trahi tout ce que les fans aimaient de l’original.",
        "hors",
        "peau, cuir",
    ),
    "adduce": (
        "Citer comme preuve ou comme pièce à conviction.",
        "Avancer un fait ou un exemple pour étayer son propos — ce vers quoi l’on pointe quand on vous demande la preuve.",
        "L’avocate adduced trois témoins à l’appui de l’alibi de sa cliente.",
        "vers, envers",
        "mener",
    ),
    "peregrinations": (
        "Voyages ou errances, surtout longs ou étendus.",
        "De longs périples vagabonds — ce genre d’errance qui vous tient longtemps loin de chez vous.",
        "Ses peregrinations à travers trois continents remplirent toute une étagère de carnets de voyage.",
        "à travers",
        "champ, terre (peregrinus : étranger)",
    ),
    "mendicant": (
        "Un mendiant, ou quelqu’un qui vit d’aumônes.",
        "Quelqu’un qui vit en demandant la charité — historiquement, aussi des moines qui avaient voué la pauvreté et vivaient de dons.",
        "Les frères mendicant ne possédaient rien et ne vivaient que de la bonté des villageois.",
        "mendier",
        "mendiant",
    ),
    "munificent": (
        "Extrêmement généreux.",
        "Généreux à une échelle presque théâtrale — le don qui arrache un petit « ah ».",
        "Le don munificent finança toute la nouvelle aile de la bibliothèque.",
        "don, service",
        "faisant, donnant",
    ),
    "inanition": (
        "Épuisement par manque de nourriture ; aussi un manque de vitalité.",
        "Un état faible, vidé, faute d’être nourri — au propre par la faim, ou au figuré faute de carburant.",
        "À la fin du siège, les soldats étaient près de l’inanition.",
        "vide, vain",
        "l’acte ou le résultat de",
    ),
    "vituperation": (
        "Une critique amère et injurieuse.",
        "Une critique qui a largement dépassé le juste et s’est changée en tirade furieuse et amère.",
        "Les commentaires en ligne se dissolvaient en pure vituperation en quelques minutes.",
        "faute",
        "préparer, fournir",
    ),
    "inimical": (
        "Hostile, nuisible dans ses effets.",
        "Qui travaille contre vous, même en silence — des conditions ou des attitudes peu amies de vos intérêts.",
        "La nouvelle politique était inimical aux petites entreprises, même si ce n’était pas l’intention.",
        "ne pas",
        "ami",
    ),
    "invidious": (
        "Propre à causer du ressentiment, souvent par des comparaisons injustes.",
        "Sûr de froisser quelqu’un — d’habitude parce qu’on met des gens ou des choses en concurrence de façon inégale.",
        "Classer les frères et sœurs selon « who Mom loves best » est un jeu invidious que personne ne devrait jouer.",
        "envie",
        "regarder (de travers)",
    ),
    "subaltern": (
        "Une personne de rang ou de statut inférieur ; un subordonné.",
        "Quelqu’un plus bas dans la chaîne de commandement ou l’échelle sociale — un junior, sous quelqu’un de plus puissant.",
        "Jeune subaltern, il reçut longtemps des ordres avant d’en donner.",
        "sous",
        "alternatif, autre",
    ),
    "execrate": (
        "Éprouver ou exprimer une haine vive.",
        "Avoir une chose en telle horreur qu’on la maudit à voix haute — une détestation pure et vocale.",
        "Les villageois execrated le percepteur chaque fois que sa charrette traversait le bourg.",
        "hors de",
        "sacré (maudire hors du sacré)",
    ),
    "integument": (
        "Une enveloppe naturelle extérieure, comme la peau ou une coquille.",
        "L’emballage protecteur de la nature — peau, coquille, cosse ou écorce, ce qui couvre et abrite un vivant.",
        "La carapace d’une tortue est un integument remarquablement dur.",
        "sur, par-dessus",
        "couvrir",
    ),
    "ingenuous": (
        "Innocent, naïf, d’une simplicité d’enfant ; le contraire de retors.",
        "Ouvertement confiant et un peu naïf, sans arrière-pensée — facile à confondre avec « ingenious », qui veut dire ingénieux.",
        "Sa question ingenuous — « why would anyone lie about that ? » — montrait comme elle avait peu de ruse.",
        "dans, natal",
        "engendrer (de naissance libre, candide)",
    ),
    "pedantry": (
        "Un souci excessif des menus détails ou des règles.",
        "Se perdre dans les petites règles et rater le tableau d’ensemble — s’acharner sur les petites lignes dont personne d’autre ne se soucie.",
        "Sa pedantry sur les virgules d’Oxford fit dérailler toute la réunion.",
        "précepteur d’enfants",
        "pratique ou qualité",
    ),
    "perscrutation": (
        "Un examen minutieux et soigneux.",
        "Un regard profond, qui ne laisse aucune pierre non retournée — passer chaque détail avec un vrai soin.",
        "Ce n’est qu’après une perscrutation attentive des grands livres que l’écart apparut.",
        "à travers, à fond",
        "chercher, examiner",
    ),
    "demur": (
        "Élever des objections ; montrer de la réticence.",
        "Reculer poliment ou hésiter plutôt que d’acquiescer tout de suite — un doux « attendez un peu ».",
        "Quand on lui demanda de signer sans lire, elle demurred.",
        "de, loin",
        "différer",
    ),
    "specious": (
        "Plausible en apparence, mais en réalité faux.",
        "Semble convaincant au premier regard, mais s’effondre dès qu’on vérifie vraiment.",
        "« Everyone's doing it » est un argument specious qui ne tient jamais vraiment à l’examen.",
        "apparence, aspect",
        "plein de (d’apparence belle)",
    ),
    "cant": (
        "Un discours insincère, hypocrite, souvent moralisateur.",
        "Un parler prêchi-prêcha qui sonne vertueux sans aucun sentiment vrai — une pose morale en pilote automatique.",
        "Il en avait assez du cant d’entreprise sur la « family » d’une société qui ne donnait jamais de congé.",
        "chanter (plus tard : jargon chantant)",
        "parler plaintif des mendiants, puis hypocrisie",
    ),
    "pusillanimous": (
        "Manquant de courage, lâche.",
        "Timide jusqu’à n’avoir plus d’échine — trop peureux pour se lever, même quand cela compte clairement.",
        "Le silence pusillanimous du conseil laissa le scandale s’emballer.",
        "très petit",
        "esprit, courage",
    ),
    "vulpine": (
        "De renard ; rusé, malin.",
        "Sournois et vif comme un renard — l’esprit prompt, un peu retors, toujours un pas en avant.",
        "Il eut un sourire vulpine dès qu’il aperçut la faille.",
        "renard",
        "de ou comme",
    ),
    "seriatim": (
        "L’un après l’autre, en séquence.",
        "Pris strictement un à un, dans l’ordre — sans sauter, sans en faire deux à la fois.",
        "Le juge examina chacune des douze demandes seriatim.",
        "rang, suite",
        "un à un",
    ),
    "parsimony": (
        "Une frugalité extrême ; l’avarice.",
        "Être chiche d’argent (ou de mots, ou de moyens) bien au-delà d’une épargne raisonnable.",
        "Sa parsimony était légendaire — il réutilisait les sachets de thé trois fois.",
        "épargner, être frugal",
        "état ou pratique",
    ),
    "emendation": (
        "Une correction, surtout dans un texte.",
        "Une retouche savante qui répare une erreur dans un texte ancien ou important.",
        "La nouvelle édition comporte des dizaines d’emendations au manuscrit original.",
        "hors de",
        "faute, erreur",
    ),
    "abstemious": (
        "Modéré dans le manger et le boire.",
        "Délibérément retenu à table — jamais trop, toujours un peu laissé dans l’assiette.",
        "Ses habitudes abstemious le tinrent vif longtemps après que ses pairs eurent ralenti.",
        "loin de",
        "boisson enivrante",
    ),
    "solecism": (
        "Une faute de grammaire ou un écart d’étiquette.",
        "Un faux pas de grammaire ou de manières — la petite erreur qui fait grimacer un maniaque du détail.",
        "« Between you and I » est un solecism courant qui fait encore tiquer les grammairiens.",
        "cité cilicienne connue pour son « mauvais » grec",
        "pratique, manière",
    ),
    "internecine": (
        "Relatif à un conflit interne à un groupe ; mutuellement destructeur.",
        "Des querelles intestines qui déchirent un groupe de l’intérieur — un combat où tout le monde perd, parce que c’est famille contre famille.",
        "Les chamailleries internecine du parti firent plus de mal que n’importe quel adversaire extérieur.",
        "entre, parmi",
        "tuer",
    ),
    "pococurante": (
        "Attitude indifférente, insouciante.",
        "Un haussement d’épaules devenu toute une personnalité — se soucier si peu de ce qui comptait jadis que plus rien ne semble valoir l’effort.",
        "Son attitude pococurante envers la cérémonie des prix surprit tous ceux qui savaient comme il avait travaillé.",
        "peu",
        "se soucier",
    ),
    "imbroglio": (
        "Une situation ou un différend confus et compliqué.",
        "Une affaire emmêlée, brouillonne, difficile à démêler — un peu de malentendu, un peu de drame, tout de la confusion.",
        "Tout l’imbroglio du plan de table commença par un carton-nom mal placé.",
        "dans",
        "emmêler, confondre",
    ),
    "minatory": (
        "Mençant, de mauvais augure.",
        "Porteur d’une menace indéniable — un regard ou une lettre minatory fait clairement entendre que le pire peut suivre.",
        "Le ton minatory de la lettre rendit la locataire nerveuse avant même qu’elle eût ouvert l’enveloppe.",
        "menacer",
        "servant à",
    ),
    "obloquy": (
        "Une vive critique publique ou des injures.",
        "Une condamnation bruyante, publique — la critique cinglante qui se joue devant tout le monde.",
        "La lanceuse d’alerte subit des années d’obloquy public avant que l’histoire ne lui donnât raison.",
        "contre",
        "parler",
    ),
    "paroxysm": (
        "Un accès soudain et violent d’émotion ou d’action.",
        "Une poussée soudaine, intense, qui vous submerge d’un coup — un fou rire, une rage ou une quinte comme une vague.",
        "Elle fut saisie d’un paroxysm de rire qu’elle ne pouvait expliquer à personne d’autre dans la pièce.",
        "au-delà",
        "aigu, acéré",
    ),
    "adscititious": (
        "Ajouté de l’extérieur, non inhérent.",
        "Boulonné du dehors plutôt qu’intégré dès l’origine — un extra, pas un cœur.",
        "Le commentaire paraît adscititious, comme collé à un texte déjà fini.",
        "vers, en plus",
        "approuver, prendre",
    ),
    "nescience": (
        "Manque de savoir, ignorance.",
        "Le simple ne-pas-savoir — un trou dans la connaissance, sans jugement collé dessus.",
        "Il avoua sa nescience des vins français et laissa le sommelier choisir.",
        "ne pas",
        "savoir",
    ),
    "prurience": (
        "Un intérêt excessif pour les questions sexuelles.",
        "Une curiosité trop empressée, un peu lèche-vitrine, pour tout ce qui est osé — un intérêt passé le sain, devenu indiscret.",
        "La prurience du tabloïd sur la vie privée du couple frisait l’obsession.",
        "démanger, désirer",
        "état de",
    ),
    "fuliginous": (
        "Fuligineux, sombre, trouble.",
        "Sombre et enfumé, comme si tout était recouvert d’une mince couche de suie.",
        "Une brume fuliginous planait au crépuscule sur la ville d’usines.",
        "suie",
        "plein de",
    ),
    "gainsay": (
        "Nier ou contredire.",
        "S’opposer net à ce qu’un autre a dit — dire que ce n’est pas ainsi.",
        "Personne n’osa gainsay le récit du vieux capitaine sur la tempête.",
        "contre",
        "parler",
    ),
    "ignavia": (
        "Paresse, oisiveté (du latin).",
        "Un vieux mot latin pour la paresse pure — le poids de ne rien vouloir faire.",
        "Les moines prêchaient contre ignavia comme l’un des dangers silencieux de l’âme.",
        "ne pas",
        "occupé, diligent",
    ),
    "escutcheon": (
        "Un écu portant des armoiries.",
        "L’emblème en forme de bouclier qui montre les armes d’une famille — son insigne héraldique.",
        "L’escutcheon de la famille pend encore au-dessus de la porte du vieux manoir.",
        "bouclier",
        "diminutif / objet",
    ),
    "superannuated": (
        "Dépassé, obsolète, ou mis à la retraite pour cause d’âge.",
        "Passé son utile printemps et mis au rancart — trop démodé ou usé pour faire encore le travail.",
        "L’imprimante superannuated fut enfin remplacée après quinze ans d’enrayages.",
        "au-delà",
        "année",
    ),
    "succedanea": (
        "Des substituts, surtout en médecine.",
        "Des remèdes de remplacement quand le vrai traitement manque — des doublures médicales, en somme.",
        "Les médecins de guerre s’appuyaient souvent sur des succedanea quand les vrais médicaments manquaient.",
        "à la place de",
        "aller, céder",
    ),
    "rodomontade": (
        "Un discours vantard et fanfaron.",
        "De grandes fanfaronnades — un grand parler de sa propre grandeur qui n’est surtout que du vent.",
        "Sa rodomontade d’avoir sauvé le projet « single-handedly » ne trompa personne de ceux qui y étaient vraiment.",
        "chevalier vantard dans Roland furieux",
        "action, étalage",
    ),
    "chicane": (
        "User de ruse ou de tromperie pour parvenir à ses fins.",
        "Se faufiler jusqu’au but par des tours plutôt que par le jeu franc.",
        "Il chicaned son entrée dans l’affaire avec un contrat plein de petites lignes.",
        "ergoter, tromper",
        "ruse ; plus tard un virage serré",
    ),
    "mathesis": (
        "La science pure ou abstraite de l’apprendre ou du savoir, souvent les mathématiques.",
        "L’apprendre dans sa forme la plus pure et abstraite — la structure profonde du savoir lui-même, surtout mathématique.",
        "Le philosophe rêvait d’une mathesis universelle qui unirait tous les champs du savoir.",
        "apprendre",
        "l’acte d’apprendre",
    ),
    "pedantic": (
        "Excessivement attaché aux règles formelles ou aux détails triviaux.",
        "Trop strict sur les petites choses — corriger des minuties techniques qui ne changent rien d’essentiel.",
        "Cela paraissait un peu pedantic de discuter « who » contre « whom » dans un texto.",
        "guide d’enfants, précepteur",
        "ayant la manière de",
    ),
    "coruscation": (
        "Un éclat de lumière scintillante.",
        "Un éclair vif et pailleté — le soleil sur l’eau, ou un diamant qui attrape la lumière.",
        "La coruscation du lustre semait la lumière dans tous les coins de la salle de bal.",
        "étinceler, flasher",
        "l’acte de",
    ),
    "tyro": (
        "Un débutant, un novice.",
        "Quelqu’un tout neuf dans un art ou un domaine — encore à apprendre les ficelles, pas encore un expert.",
        "Même un joueur d’échecs tyro peut voir cette gaffe.",
        "recrue, novice",
        "un jeune soldat encore vert",
    ),
    "execrable": (
        "Extrêmement mauvais, détestable.",
        "Mauvais d’une façon qui mérite un vrai dégoût — pas seulement médiocre, mais vraiment affreux.",
        "Le critique appela la suite execrable, et le box-office lui donna raison.",
        "maudire",
        "digne de, capable d’être",
    ),
    "incarnadine": (
        "D’un rouge de sang.",
        "Un rouge profond et vif — la couleur du sang frais, rendu fameux par le Macbeth de Shakespeare.",
        "Le coucher du soleil teinta tout le ciel d’une lueur incarnadine.",
        "dans",
        "chair (rouge de chair)",
    ),
    "interstice": (
        "Un petit interstice ou espace entre des choses.",
        "Le tout petit entre-deux qu’on oublie facilement — la fente entre les lames du plancher, le trou dans un emploi du temps.",
        "Les mauvaises herbes poussaient par chaque interstice du vieux chemin de briques.",
        "entre",
        "se tenir",
    ),
    "animadversion": (
        "Des remarques critiques ou censoriales.",
        "Des commentaires pointus, désapprobateurs — la critique qui a un rien de semonce.",
        "Les animadversions du professeur sur la dissertation remplirent les marges d’encre rouge.",
        "esprit",
        "se tourner vers",
    ),
    "irrefragable": (
        "Impossible à réfuter, indéniable.",
        "Si solidement prouvé qu’on n’y peut rien objecter — l’affaire est close.",
        "La preuve ADN était irrefragable, et le procès s’acheva dans l’heure.",
        "ne pas",
        "s’opposer, résister",
    ),
    "involution": (
        "Complexité, enchevêtrement ; aussi un repli vers l’intérieur.",
        "Une complexité emmêlée, repliée sur elle-même — des choses si serrées qu’on a du mal à les démêler.",
        "L’involution de l’intrigue laissa la moitié de la salle démêler encore après le générique.",
        "dans, vers l’intérieur",
        "rouler, tourner",
    ),
    "dint": (
        "Force ou effort, comme dans « by dint of ».",
        "La force brute ou l’effort — survit surtout dans la locution « by dint of ».",
        "Il réussit l’examen by dint of une pratique obstinée, toute simple.",
        "un coup, une frappe",
        "à force de",
    ),
    "mortised": (
        "Assemblé par un assemblage à tenon et mortaise ; emboîté solidement.",
        "Verrouillé à l’ancienne façon du menuisier — une pièce glisse pile dans un trou taillé pour elle.",
        "Les poutres de la vieille grange étaient mortised ensemble sans un seul clou.",
        "une cavité, un trou",
        "une morsure, une prise",
    ),
    "apposite": (
        "Hautement pertinent, juste.",
        "Exactement ce qu’il fallait pour l’instant — une remarque, une citation ou un exemple qui tombe pile.",
        "Sa remarque apposite résuma tout le débat en une phrase.",
        "vers",
        "placer",
    ),
    "lambent": (
        "D’une lueur douce ou vacillante ; aussi, un esprit léger.",
        "Lueur douce plutôt qu’embrasement — une flamme qui joue, ou un esprit enjoué plutôt que coupant.",
        "La chandelle jetait une lueur lambent sur la vieille salle à manger.",
        "lécher",
        "faisant (lumière qui « lèche »)",
    ),
    "anchorite": (
        "Un reclus religieux vivant dans la solitude.",
        "Quelqu’un qui se retire entièrement du monde pour vivre seul dans la prière et la méditation.",
        "L’anchorite vécut plus de trente ans dans une petite cellule adossée à l’église.",
        "en arrière, loin",
        "se retirer",
    ),
    "slake": (
        "Étancher la soif ; apaiser.",
        "Satisfaire pleinement un désir — le plus souvent la soif, mais au figuré tout besoin profond.",
        "Un verre d’eau froide slaked sa soif après la longue randonnée.",
        "lâche, relâché",
        "détendre, calmer",
    ),
    "acicular": (
        "En forme d’aiguille.",
        "Long, mince et pointu comme une aiguille — la forme d’une aiguille de pin ou d’un petit cristal acéré.",
        "Les pins se reconnaissent facilement à leurs feuilles acicular.",
        "aiguille",
        "petit",
    ),
    "effete": (
        "Épuisé de vitalité, faible, trop raffiné.",
        "Usé et ramolli — ayant perdu sa vigueur première à force de confort ou de raffinement.",
        "Les critiques traitèrent le magazine jadis audacieux d’effete, ombre de ses années de bravoure.",
        "hors",
        "fécond, ayant porté",
    ),
    "appurtenance": (
        "Un accessoire ou un petit élément ou droit qui s’y rattache.",
        "Un petit extra rattaché à quelque chose de plus grand — les accessoires et dépendances qui vont avec le principal.",
        "Le bail comprenait le garage et toutes ses appurtenances.",
        "vers",
        "appartenir",
    ),
    "gloze": (
        "Glisser sur une faute ou la minimiser.",
        "Lisser une bévue de paroles douces, pour la faire paraître plus petite qu’elle n’est.",
        "Il tenta de gloze over le délai manqué avec un vague discours sur des « unforeseen challenges ».",
        "une glose, une explication",
        "commenter — puis lisser",
    ),
    "incipient": (
        "À un stade précoce, qui commence à peine.",
        "À peine en train de se montrer — le tout premier stade, presque invisible, de quelque chose de plus grand.",
        "Les médecins saisirent les signes incipient de la maladie avant qu’elle ne se répandît.",
        "sur, dans",
        "prendre (entreprendre, commencer)",
    ),
    "afflatus": (
        "Inspiration créatrice, surtout divine.",
        "Une poussée soudaine d’inspiration plus grande que soi — comme si l’idée vous avait été soufflée d’ailleurs.",
        "Le poète raconta que toute la pièce arriva d’un burst of afflatus à trois heures du matin.",
        "vers, sur",
        "souffler (un souffle sur)",
    ),
}
