# Dutch overlays: (definition, friendly, exampleGloss, root1, root2)
WORDS = {
    "edulcorate": (
        "Zoeten of zuiveren; de scherpte uit iets halen.",
        "De angel of bitterheid uit iets halen — letterlijk zoeter maken, of figuurlijk een harde gedachte verzachten zodat die makkelijker binnenkomt.",
        "De redacteur verzachtte de harde recensie voordat die naar de druk ging.",
        "uit, grondig",
        "zoet",
    ),
    "pietistic": (
        "Overdreven of geaffecteerd godsdienstig of vroom.",
        "Beschrijft iemand wiens vroomheid naar show ruikt: meer opvoering dan echt geloof.",
        "Zijn pietistische gezucht tijdens de preek irriteerde de rest van de bank.",
        "vroomheid, plichtsbesef",
        "het karakter hebbend van",
    ),
    "amphiboly": (
        "Dubbelzinnigheid door de zinsbouw — een zin die op twee manieren te lezen is.",
        "Een zin die grammatisch klopt, maar op twee heel verschillende manieren te lezen is, zoals „Visiting relatives can be tiring.”",
        "„Visiting relatives can be tiring” is een klassieke amfibolie — zijn de familieleden vermoeiend, of is het bezoek dat?",
        "beide, aan beide kanten",
        "werpen",
    ),
    "trenchant": (
        "Scherp, treffend, recht op de man af.",
        "Snijdt dwars door het rumoer heen — een snijdende opmerking of geest raakt meteen de kern, zonder overbodige woorden.",
        "Haar snijdende kritiek liet geen ruimte voor de gaten in het filmplot.",
        "snijden",
        "doend, de hoedanigheid hebbend van",
    ),
    "inchoative": (
        "Net begonnen; in een vroeg of rudimentair stadium.",
        "Nog in de openingsminuten — een plan, gevoel of proces dat pas net vorm begint te krijgen.",
        "De beginnende fasen van het verdrag waren veelbelovend, maar veel details bleven open.",
        "beginnen, starten",
        "neigend naar",
    ),
    "panegyric": (
        "Een formele toespraak of tekst die iemand hoog prijst.",
        "Een volle, plechtige lofzang — denk aan een stralende lijkrede of een speech die iemands verdiensten van de daken schreeuwt.",
        "De vertrekkende hoogleraar werd uitgezwaaid met een lofrede van haar naaste studenten.",
        "al, geheel",
        "bijeenkomst, vergadering",
    ),
    "ontic": (
        "Betreffende het werkelijke bestaan, in tegenstelling tot abstracte theorie.",
        "Over dingen zoals ze werkelijk zijn, niet alleen als ideeën of theorieën erover.",
        "Filosofen debatteren of getallen enige ontische status hebben of alleen in ons hoofd bestaan.",
        "zijn, dat wat bestaat",
        "betrekking hebbend op",
    ),
    "fructify": (
        "Vrucht dragen, of productief worden.",
        "Eindelijk vrucht afwerpen — een inspanning, idee of investering die vrucht draagt is van zaad tot iets nuttigs uitgegroeid.",
        "Jaren van stil onderzoek droegen uiteindelijk vrucht in een werkend vaccin.",
        "vrucht",
        "maken, veroorzaken",
    ),
    "proleptical": (
        "Iets voorstellen alsof het al gebeurd is voordat het werkelijk plaatsvindt.",
        "Op een literaire manier op de zaken vooruitlopen — een toekomstig feit beschrijven alsof het al klaar is, zodat de punt harder aankomt.",
        "De anticiperende toost van de generaal op „de overwinning” werd een volle week vóór de slag uitgebracht.",
        "vóór",
        "nemen, grijpen",
    ),
    "pneumatic": (
        "Werkend op luchtdruk; ook betrekking hebbend op geest of adem.",
        "Meestal: aangedreven door perslucht — een boor, een busrem — maar dezelfde Griekse wortel spreekt ook over adem en geest.",
        "De pneumatische remmen sisten toen de bus bij de stoeprand stopte.",
        "wind, adem, geest",
        "betrekking hebbend op",
    ),
    "cataphatic": (
        "God of het goddelijke beschrijven met bevestigende uitspraken — het tegenovergestelde van apofatisch.",
        "Over God spreken door te zeggen wat God ís — „God is liefde”, „God is rechtvaardig” — in plaats van alleen wat God niet is.",
        "Katafatische theologie spreekt vol vertrouwen over God als liefdevol, rechtvaardig en barmhartig.",
        "neer, volgens",
        "spreken, zeggen",
    ),
    "fiducial": (
        "Gebaseerd op vertrouwen of geloof; ook: een vast ijkpunt.",
        "Iets dat je op vertrouwen neemt en daarna als anker gebruikt — een ijkmerk is de vaste plek waartegen al het andere wordt afgemeten.",
        "Landmeters plaatsten een vast referentieteken in het gesteente voordat ze de plek in kaart brachten.",
        "vertrouwen",
        "vertrouwen, zekerheid",
    ),
    "theodicy": (
        "Een verdediging van Gods goedheid ondanks het bestaan van kwaad.",
        "De eeuwenoude poging om te antwoorden: als God goed is, waarom is er dan kwaad? — zonder een van beide claims op te geven.",
        "Haar scriptie onderzocht de theodicee door de lens van het boek Job.",
        "god",
        "gerechtigheid",
    ),
    "circumincession": (
        "Wederzijds inwonen — een theologische term voor hoe de personen van de Drie-eenheid in elkaar bestaan.",
        "Een theologisch woord voor een drie-in-een-saamhorigheid zo volledig dat elk deel de anderen bevat én erin bevat is.",
        "De leer van de circumincessie probeert uit te leggen hoe Vader, Zoon en Geest onderscheiden én onscheidbaar zijn.",
        "rondom",
        "gaan, lopen",
    ),
    "redound": (
        "Een gevolg hebben dat iemand ten goede komt of op iemand terugvalt.",
        "Wanneer eer (of blaam) terugkaatst naar wie er verantwoordelijk voor is — goede daden die je tot eer strekken komen later weer bij je terug.",
        "Het succes van het team zal strekken tot eer van de stille, hardwerkende coach.",
        "terug, opnieuw",
        "golf",
    ),
    "ineluctable": (
        "Niet te vermijden of te ontkomen.",
        "Het gebeurt hoe dan ook — aan een onontkoombare uitkomst wring je je niet los.",
        "De ouderdom komt voor iedereen; het is eenvoudigweg onontkoombaar.",
        "niet",
        "zich eruit worstelen",
    ),
    "periphrastic": (
        "Omslachtige, woordrijke formulering in plaats van een directe vorm.",
        "De lange weg met woorden: in een hele zin zeggen wat één woord zou dekken.",
        "Zijn omslachtige e-mails hadden in één regel kunnen zeggen wat drie alinea’s kostte.",
        "rondom",
        "verklaren, vertellen",
    ),
    "hebetude": (
        "Geestelijke botheid of lethargie.",
        "Die mistige, trage gemoedstoestand waarin denken voelt als waden door siroop.",
        "Een golf van suffigheid sloeg vlak na de lunch over de klas.",
        "bot, stomp",
        "toestand of hoedanigheid",
    ),
    "unpropitious": (
        "Niet gunstig; een slecht voorteken.",
        "Een slecht teken — omstandigheden of timing die al tegen je werken voordat je begonnen bent.",
        "Grijze luchten en een dode accu maakten een ongunstig begin van de roadtrip.",
        "niet",
        "gunstig, genadig",
    ),
    "fricaseed": (
        "Vlees gestoofd of gesmoord in saus — eigenlijk gespeld „fricasseed”.",
        "Een knusse, oude kookterm voor vlees dat is klein gesneden en langzaam in de eigen saus gaar gesudderd.",
        "Grootmoeders gefricasseerde kip was het hoogtepunt van elk zondags diner.",
        "braden, bakken",
        "breken (in stukken)",
    ),
    "ersatz": (
        "Een kunstmatige of mindere vervanging.",
        "Een namaak die voor het echte moet doorgaan — het doet het werk, maar iedereen ziet dat het niet de echte is.",
        "In oorlogstijd namen winkeliers genoegen met surrogaatkoffie van geroosterde cichorei.",
        "uit, vervangingsvoorvoegsel",
        "zetten, plaatsen",
    ),
    "reify": (
        "Een abstract idee behandelen alsof het een tastbaar ding is.",
        "Een idee vast en echt laten voelen — iets vaags, zoals „de markt”, tot een ding maken waar je naar kunt wijzen.",
        "De „geest” van een natie tot een wezen uitroepen verdinglijkt iets dat in werkelijkheid miljoenen losse keuzes zijn.",
        "ding",
        "maken",
    ),
    "eluded": (
        "Behendig ontsnapt of ontweken.",
        "Schoon weggeglipt — iets ontweken, vaak slim of nipt, of het nu een vangst, een vraag of een antwoord is.",
        "Het antwoord ontglipte haar urenlang tot het ineens klikte onder de douche.",
        "uit, weg",
        "spelen",
    ),
    "aporetic": (
        "Twijfel, verbijstering of een onopgeloste tegenspraak uitdrukkend.",
        "Vastgelopen op een echt doodlopend pad van denken — niet uit luiheid, maar omdat de vraag zelf geen net antwoord toelaat.",
        "Socrates eindigde zijn dialogen vaak op een aporetische toon, met meer vragen dan antwoorden.",
        "zonder",
        "doorgang, weg",
    ),
    "metonymy": (
        "Een stijlfiguur waarbij iets wordt benoemd met een bijbehorend woord, bijvoorbeeld „de kroon” voor de vorst.",
        "Een verwant woord laten staan voor het echte — „Wall Street” zeggen als je de beurs bedoelt.",
        "„Wall Street had a rough day” is metonymie — het betekent eigenlijk dat de aandelenmarkt het zwaar had.",
        "verandering, na",
        "naam",
    ),
    "deracinate": (
        "Ontwortelen; wegrukken uit een natuurlijke omgeving.",
        "Iets (of iemand) met wortel en al uittrekken, weg van de plek of cultuur waar het thuishoort.",
        "Oorlog ontwortelde een hele generatie en verstrooide families over de grenzen.",
        "weg, af",
        "wortel",
    ),
    "euphonious": (
        "Aangenaam klinkend.",
        "Gewoon fijn om te horen — een welluidend woord of zin rolt soepel, bijna muzikaal, het oor in.",
        "„Murmuring brook” is een welluidend klein zinnetje, zacht en makkelijk uit te spreken.",
        "goed, wel",
        "klank, stem",
    ),
    "putative": (
        "Algemeen aangenomen of verondersteld.",
        "Wijd en zijd voor waar gehouden, ook al is het niet bewezen — de vermeende of veronderstelde versie van iets.",
        "De vermeende auteur van de brief bleek later een volslagen vreemde.",
        "denken, beschouwen",
        "het karakter hebbend van",
    ),
    "neologism": (
        "Een nieuw bedacht woord of een nieuwe uitdrukking.",
        "Een splinternieuw woord — net verzonnen, nog (nauwelijks) in het woordenboek.",
        "„Doomscrolling” begon als neologisme en werd snel alledaags slang.",
        "nieuw",
        "woord, spraak",
    ),
    "splenetic": (
        "Boos of slechtgehumeurd.",
        "In een chagrijnige, prikkelbare bui — snel van de keten, zoals men vroeger dacht dat de milt je humeur bestuurde.",
        "Hij vuurde binnen seconden een gallig antwoord op de e-mail af.",
        "milt (zetel van woede)",
        "aangetast door",
    ),
    "sententious": (
        "Geneigd tot moraliseren op een pompeuze of geaffecteerde manier.",
        "Deelt graag kleine levenslessen uit alsof elke zin een fortune cookie is.",
        "Zijn moraliserende toost over „de ware betekenis van vriendschap” liet iedereen op zijn horloge kijken.",
        "mening, spreuk",
        "vol van",
    ),
    "garrulous": (
        "Overdreven praatziek, vooral over kleinigheden.",
        "Stopt gewoon niet met kletsen — raaskalt over klein spul lang nadat de rest is uitgesproken.",
        "De praatzieke taxichauffeur vertelde zijn hele levensverhaal voordat we het vliegveld uit waren.",
        "kletsen, babbelen",
        "geneigd tot",
    ),
    "fatuity": (
        "Dwaasheid, onnozelheid.",
        "Gewone dwaasheid — een opmerking of plan zo onnozel dat het nauwelijks een serieus antwoord verdient.",
        "De pure dwaasheid van het plan werd duidelijk zodra ze het probeerden.",
        "dwaas, onnozel",
        "toestand van zijn",
    ),
    "peroration": (
        "Het slot van een toespraak, vaak samenvattend.",
        "De grote finale van een speech — het slot waarin de spreker alles samenraapt en de punt thuisbrengt.",
        "Bij de slotrede stond de helft van het publiek op de been.",
        "door, tot het einde",
        "spreken, bepleiten",
    ),
    "tautology": (
        "Overbodige herhaling van dezelfde gedachte in andere woorden.",
        "Hetzelfde twee keer zeggen zonder iets nieuws toe te voegen, zoals „gratis cadeau” of „it is what it is.”",
        "„It is what it is” is een favoriete tautologie van mensen die een echte uitleg ontwijken.",
        "hetzelfde",
        "woord, spraak",
    ),
    "laconism": (
        "Het gebruik van zeer weinig woorden; korte, bondige spraak.",
        "Veel zeggen met heel weinig — de kunst van het korte, botte antwoord, genoemd naar de notoir korte Spartanen van Laconië.",
        "„Molon labe” — „kom ze maar halen” — is het beroemdste staaltje laconisme uit de geschiedenis.",
        "een Spartaan uit Laconië",
        "gewoonte, wijze",
    ),
    "pabulum": (
        "Tamme, overgesimplificeerde ideeën; oorspronkelijk: smakeloos voedsel of brij.",
        "Dun, aangelengd denken — inhoud zo veilig en eenvoudig dat ze geen voedingswaarde voor de geest heeft.",
        "De speech van de politicus was vooral gebakken lucht: vage beloften waar je niets aan vast kon pinnen.",
        "voeden",
        "middel of werktuig",
    ),
    "soporific": (
        "Slaap of slaperigheid veroorzakend.",
        "Zo saai — of zo letterlijk verdovend — dat je er slaperig van wordt. Denk aan warme melk, of een begrotingsvergadering van drie uur.",
        "De slaapverwekkende dreun van de lezing liet de helft van de zaal vechten om de ogen open te houden.",
        "diepe slaap",
        "makend, veroorzakend",
    ),
    "unctuous": (
        "Overdreven vleiend of olieachtig in omgang.",
        "Zo glad charmant dat het glibberig voelt — vleierij zo dik aangezet dat je de olie bijna voelt.",
        "De zalvende verkoper bleef mijn „uitstekende smaak” prijzen vóór elke extra verkoop.",
        "zalven, oliën",
        "vol van",
    ),
    "captious": (
        "Snel in het bekritiseren, overdreven op triviale dingen.",
        "Muggenzifterig tot in het absurde — het type dat overal een probleem in ziet, ook als het er niet toe doet.",
        "Zijn muggenzifterige aantekeningen bij het rapport gingen alleen over kommagebruik.",
        "grijpen, nemen",
        "een valstrik, een drogreden",
    ),
    "torpid": (
        "Traag, geestelijk of lichamelijk inactief.",
        "Langzaam en half in slaap, als een beer in winterslaap — nauwelijks bewegend, nauwelijks denkend.",
        "Het kantoor viel loom in de zware augustushitte.",
        "verdoofd zijn, traag zijn",
        "in een staat van",
    ),
    "seneschal": (
        "Een hofmeester of beambte die een middeleeuws huishouden bestuurde.",
        "De middeleeuwse versie van een hoofd personeel — de vertrouwde beambte die het huis en landgoed van een heer dagelijks runde.",
        "De hofmeester van het kasteel regelde alles, van de oogstrekeningen tot de gastenlijst.",
        "oud, senior",
        "dienaar",
    ),
    "expatiate": (
        "Uitvoerig over een onderwerp spreken of schrijven.",
        "Echt op gang komen over een onderwerp — er eindeloos over praten of schrijven, van alle kanten.",
        "Vraag hem naar oldtimers en hij zal er een vol uur over uitweiden.",
        "uit",
        "ruimte",
    ),
    "nugatory": (
        "Zonder waarde, futiel; ook ongeldig of zonder effect.",
        "Zo goed als niks waard — een nietige clausule in een contract doet in de praktijk niets.",
        "De rechter verklaarde de oude verordening krachteloos, omdat ze nooit was gehandhaafd.",
        "kleinigheden, onzin",
        "behorend tot",
    ),
    "sagacity": (
        "Wijsheid, scherp oordeel.",
        "Scherpe, praktische wijsheid — het soort goed oordeel dat uit ervaring komt, niet alleen uit boeken.",
        "De schranderheid van de oude kapitein hield de bemanning meer dan eens uit de problemen.",
        "scherp van reuk, schrander",
        "hoedanigheid van",
    ),
    "canaille": (
        "Het gewone grauw of het volk, minachtend gebruikt.",
        "Een snobistisch, denigrerend woord voor gewone mensen, alsof ze een roedel honden zijn.",
        "De graaf grijnsde naar het gepeupel dat zich buiten de paleispoorten verzamelde.",
        "hond",
        "collectief, roedel",
    ),
    "contumely": (
        "Beledigende, vernederende behandeling of taal.",
        "Wrede, spottende behandeling die bedoeld is om te kleineren — de belediging die moet steken.",
        "Hij verdroeg jaren van hoon van critici voordat zijn werk eindelijk erkend werd.",
        "met, grondig",
        "zwellen (van trots)",
    ),
    "askance": (
        "Met argwaan of afkeuring; een zijdelingse blik.",
        "De scheve blik die je iets geeft dat je niet helemaal vertrouwt — een blik vol twijfel.",
        "De leraar keek wantrouwig naar het verdacht netjes gemaakte huiswerk.",
        "naar, tot",
        "scheef, vooringenomen",
    ),
    "clodpate": (
        "Een stommerik; een sul.",
        "Een ouderwetse, bijna affectueuze belediging voor iemand die traag of bot is — een sul.",
        "„Jij uilskuiken,” lachte ze, „je houdt de kaart de hele tijd al ondersteboven.”",
        "kluit aarde",
        "hoofd",
    ),
    "actuate": (
        "In beweging of tot handelen brengen; motiveren.",
        "De vonk zijn die iets in beweging zet — of het nu een machine is die aangaat of iemand die eindelijk naar een idee handelt.",
        "Angst om het contract te verliezen zette het hele team aan tot een weekend overwerk.",
        "een doen, een drijven",
        "drijven, doen",
    ),
    "peculation": (
        "Verduistering van toevertrouwde gelden.",
        "Stilletjes geld stelen dat je moest bewaken — verduistering in een ouderwetse jas.",
        "De verduistering van de penningmeester bleef bijna tien jaar onopgemerkt.",
        "privébezit",
        "vee, rijkdom",
    ),
    "demi-monde": (
        "Een groep aan de rand van de fatsoenlijke samenleving.",
        "De glamourachtige maar schimmige onderwereld van de salon — mensen die net buiten de regels van het fatsoen leven.",
        "De roman volgt een zangeres in de halfwereld van de cabarets van de jaren twintig.",
        "half",
        "wereld, samenleving",
    ),
    "extant": (
        "Nog bestaande; niet uitgestorven of vernietigd.",
        "Vandaag de dag nog in leven — gebruikt voor oude dingen (handschriften, soorten, gebouwen) die het hebben gered.",
        "Er zijn slechts drie bewaard gebleven exemplaren van de eerste druk bekend.",
        "uit",
        "staan",
    ),
    "perfidy": (
        "Bedrieglijkheid; verraad van vertrouwen.",
        "Diep, opzettelijk verraad — een vertrouwen breken dat iemand terecht van je verwachtte.",
        "De generaal vergaf het verraad van zijn oude vriend aan de onderhandelingstafel nooit.",
        "door, tegen",
        "geloof, vertrouwen",
    ),
    "patois": (
        "Een streektaal, vooral een niet-standaard variant.",
        "De eigen, lokale manier waarop mensen in een streek praten — vol woorden en ritmes die een buitenstaander mist.",
        "Haar grootmoeder sprak bij familiemaaltijden nog altijd het dialect van het eiland.",
        "ruwe spraak, dialect",
        "poot — stuntelige praat",
    ),
    "prerogative": (
        "Een bijzonder recht van een persoon of groep.",
        "Een voorrecht dat van jou alleen is — een recht dat bij je rol, positie of status hoort.",
        "De vakantiebestemming van de familie kiezen is opa's voorrecht, en iedereen weet dat.",
        "vóór",
        "vragen, stemmen",
    ),
    "hardihood": (
        "Durf, stoutmoedigheid; ook taaiheid of uithoudingsvermogen.",
        "Ruige, dappere veerkracht — de durf om door te zetten en de taaiheid om vol te houden als je eenmaal onderweg bent.",
        "Er was echte onverschrokkenheid voor nodig om de pas in een sneeuwstorm zonder kaart over te steken.",
        "stout, taai",
        "staat, gesteldheid",
    ),
    "effloresce": (
        "In bloei uitbarsten; ook: zich ontwikkelen of geleidelijk verschijnen.",
        "Openbloeien tot volle uitdrukking — als een bloem die opengaat, of een idee dat eindelijk tot zichzelf komt.",
        "Haar stille talent voor schilderen kwam pas tot bloei toen ze een eigen atelier had.",
        "uit",
        "beginnen te bloeien",
    ),
    "plumb-line": (
        "Een verzwaard snoer om de loodrechte lijn te bepalen; figuurlijk: een maatstaf.",
        "Een gewicht aan een touw dat loodrecht naar beneden hangt, om te checken of iets écht verticaal is — en bij uitbreiding elke vaste maatstaf waartegen je de rest afzet.",
        "Hij gebruikte de eerlijkheid van zijn grootvader als een soort schietlood voor elk besluit.",
        "lood",
        "koord, maat",
    ),
    "fain": (
        "Graag, gewillig (archaïsch).",
        "Een ouderwetse manier om „graag” of „met plezier” te zeggen — wie iets „fain” doet, doet het dolgraag.",
        "„Ik zou hier maar al te graag een poos rusten,” zuchtte de reiziger.",
        "blij, vreugdevol",
        "graag, gewillig",
    ),
    "opprobrium": (
        "Harde publieke kritiek of schande.",
        "Openbare schande die iemand groots en zichtbaar wordt nagedragen — de smaad van wijdverbreide afkeuring.",
        "Het schandaal bracht publieke schande over het hele kantoor.",
        "tegen",
        "schande, verwijt",
    ),
    "mordant": (
        "Scherp sarcastisch, bijtend in geest of kritiek.",
        "Humor met echte tanden — een bijtende opmerking steekt juist omdat ze zo raak is gericht.",
        "Haar bijtende filmrecensies werden gevreesd door regisseurs en geliefd door lezers.",
        "bijten",
        "bijtend, doend",
    ),
    "pronunciamento": (
        "Een formele proclamatie, vaak politiek of militair.",
        "Een groot, officieel bericht — meestal een die een nieuwe regering, opstand of groot decreet afkondigt.",
        "De machtsverklaring van de generaal kondigde bij dageraad de nieuwe regering aan.",
        "voorwaarts",
        "aankondigen",
    ),
    "sciolist": (
        "Iemand met oppervlakkige kennis die zich als deskundige voordoet.",
        "Iemand die over de oppervlakte van een onderwerp is geschampt en dan praat alsof hij het handboek schreef.",
        "De schijngeleerde op het diner corrigeerde vol vertrouwen de echte astrofysicus aan tafel.",
        "weten",
        "verkleinwoord — een klein-weter",
    ),
    "dotage": (
        "Achteruitgang van de geestelijke vermogens op hoge leeftijd.",
        "De mistige, vergeetachtige late ouderdom waarin de scherpte van de geest begint te tanen.",
        "In zijn kindsheid vertelde hij bij elk bezoek dezelfde drie verhalen, telkens alsof ze nieuw waren.",
        "dwazen, suf zijn",
        "toestand of gevolg",
    ),
    "lee-side": (
        "De zijde die uit de wind ligt.",
        "De luwe, beschutte kant van iets — een heuvel, een schip, een muur — waar de wind je net niet bereikt.",
        "De wandelaars sloegen hun tent op aan de lijzijde van de rug om de vlagen te ontwijken.",
        "beschutting, bescherming",
        "flank, zijde",
    ),
    "parry": (
        "Een slag, vraag of argument afweren of omleiden.",
        "Iets soepel wegslaan — een zwaardslag, een lastige vraag, een beschuldiging — zonder een tel te missen.",
        "Ze pareerde de lastige vraag van de verslaggever met een luchtige grap.",
        "afweren",
        "voorbereiden, verdedigen",
    ),
    "mephitic": (
        "Stinkend, giftig van geur.",
        "Walgelijk ruikend op een bijna giftige manier — een stank zo erg dat ademen gevaarlijk lijkt.",
        "Een verpestende geur dreef bij zonsondergang op uit het moeras.",
        "schadelijke damp",
        "het karakter hebbend van",
    ),
    "sybarite": (
        "Iemand die zich wijdt aan luxe en genot.",
        "Iemand die leeft voor comfort en wellust — fijn eten, zachte bedden, makkelijk leven — genoemd naar de Griekse stad Sybaris, beroemd om haar overdaad.",
        "Een echte sybariet, hij weigerde elke hotelkamer zonder badkuip.",
        "oude Griekse stad beroemd om luxe",
        "inwoner van",
    ),
    "prescind": (
        "Opzettelijk een deel van iets terzijde schuiven of negeren.",
        "In gedachten een stuk van de puzzel bewust apart zetten, zodat je schoon op de rest kunt focussen.",
        "Laten we even afzien van de kosten en alleen vragen of het plan überhaupt werkt.",
        "vóór, weg",
        "snijden",
    ),
    "excoriate": (
        "Hard bekritiseren; ook: de huid afstropen.",
        "Iemand met harde kritiek villen — alsof je letterlijk de huid eraf haalt.",
        "De critici fileerden het vervolg omdat het alles verraadde waar fans van het origineel van hielden.",
        "af",
        "huid, vel",
    ),
    "adduce": (
        "Aanhalen als bewijs of bewijsgrond.",
        "Een feit of voorbeeld naar voren brengen om je punt te stutten — dat waar je naar wijst als iemand om bewijs vraagt.",
        "De advocate voerde drie getuigen aan ter ondersteuning van het alibi van haar cliënt.",
        "naar, richting",
        "leiden",
    ),
    "peregrinations": (
        "Reizen of omzwervingen, vooral lange of uitgebreide.",
        "Lange, zwervende tochten — het soort omzwerving dat je een hele poos ver van huis houdt.",
        "Zijn omzwervingen over drie continenten vulden een hele plank met reisdagboeken.",
        "door",
        "veld, land (peregrinus: vreemdeling)",
    ),
    "mendicant": (
        "Een bedelaar, of iemand die van aalmoezen leeft.",
        "Iemand die leeft van gevraagde liefdadigheid — historisch ook monniken die armoede beloofden en van giften leefden.",
        "De bedelbroeders bezaten niets en leefden geheel van de goedheid van dorpelingen.",
        "bedelen",
        "bedelaar",
    ),
    "munificent": (
        "Buitengewoon gul.",
        "Gul op een groots, bijna theatraal formaat — het soort gift waarbij mensen even naar adem happen.",
        "De vrijgevige gift financierde de hele nieuwe vleugel van de bibliotheek.",
        "gift, dienst",
        "makend, gevend",
    ),
    "inanition": (
        "Uitputting door gebrek aan voeding; ook een gebrek aan levenskracht.",
        "Een slappe, leeggezogen staat van niet gevoed of gevoed te zijn — letterlijk van honger, of figuurlijk van niets meer over te hebben.",
        "Aan het eind van het beleg waren de soldaten nabij uitputting.",
        "leeg, ijdel",
        "de daad of het gevolg van",
    ),
    "vituperation": (
        "Bittere, scheldende kritiek.",
        "Kritiek die allang het eerlijke voorbij is en in een boze, bittere tirade is veranderd.",
        "De online reacties losten binnen minuten op in pure scheldpartijen.",
        "fout, gebrek",
        "bereiden, verschaffen",
    ),
    "inimical": (
        "Vijandig, schadelijk van uitwerking.",
        "Tegen je inwerkend, al is het stilletjes — omstandigheden of houdingen die je belangen niet vriendelijk gezind zijn.",
        "Het nieuwe beleid was schadelijk voor kleine bedrijven, ook al was dat niet de bedoeling.",
        "niet",
        "vriend",
    ),
    "invidious": (
        "Waarschijnlijk wrok of onvrede veroorzakend, vaak door oneerlijke vergelijkingen.",
        "Gegarandeerd dat iemand zich tekortgedaan voelt — meestal omdat mensen of dingen oneerlijk tegenover elkaar worden gezet.",
        "Broers en zussen rangschikken naar „wie mama het liefst vindt” is een hatelijk spel dat niemand moet spelen.",
        "nijd",
        "aanzien (met kwade wil)",
    ),
    "subaltern": (
        "Iemand van lagere rang of status; een ondergeschikte.",
        "Iemand lager in de commando- of sociale ladder — een junior, werkend onder iemand met meer macht.",
        "Als jonge ondergeschikte nam hij lang bevelen aan voordat hij ze ooit gaf.",
        "onder",
        "alternatief, ander",
    ),
    "execrate": (
        "Sterke haat voelen of uiten.",
        "Iets zo verafschuwen dat je het hardop vervloekt — pure, luidruchtige afkeer.",
        "De dorpelingen vervloekten de belastinginner telkens als zijn kar door het dorp rolde.",
        "uit",
        "heilig (vervloeken, uit het heilige stoten)",
    ),
    "integument": (
        "Een natuurlijke buitenste bedekking, zoals huid of een schelp.",
        "De eigen beschermende verpakking van de natuur — huid, schelp, dop of schil, wat een levend wezen bedekt en beschermt.",
        "Het schild van een schildpad is een opmerkelijk taaie bedekking.",
        "op, over",
        "bedekken",
    ),
    "ingenuous": (
        "Onschuldig, naïef, van kinderlijke eenvoud; het tegenovergestelde van hinterlistig.",
        "Openlijk vertrouwend en een tikje naïef, zonder verborgen agenda — makkelijk te verwarren met „ingenious”, dat slim betekent.",
        "Haar argeloze vraag — „waarom zou iemand daarover liegen?” — liet zien hoe weinig sluwheid ze had.",
        "in, inheems",
        "verwekken (vrijgeboren, oprecht)",
    ),
    "pedantry": (
        "Overdreven aandacht voor kleine details of regels.",
        "Verdwaald in de kleine regels en het grotere plaatje missen — piekeren over de kleine lettertjes waar niemand anders om geeft.",
        "Zijn muggenzifterij over Oxford-komma’s ontspoorde de hele vergadering.",
        "leermeester van kinderen",
        "praktijk of hoedanigheid",
    ),
    "perscrutation": (
        "Een grondig, zorgvuldig onderzoek.",
        "Een diepe, geen-steen-onberoerd-latende blik — elk detail met echte zorg nalopen.",
        "Pas na een zorgvuldige doorlichting van de grootboeken kwam de afwijking boven.",
        "door, grondig",
        "zoeken, onderzoeken",
    ),
    "demur": (
        "Bezwaar maken; aarzeling tonen.",
        "Beleefd tegensputteren of aarzelen in plaats van meteen mee te gaan — een zacht „wacht even”.",
        "Toen haar werd gevraagd te tekenen zonder te lezen, maakte ze bezwaar.",
        "van, weg",
        "uitstellen",
    ),
    "specious": (
        "Op het oog aannemelijk, maar in werkelijkheid onjuist.",
        "Klinkt in eerste instantie overtuigend, maar valt uit elkaar zodra je het echt nagaat.",
        "„Everyone's doing it” is een schijnbaar overtuigend argument dat onder de loep nooit helemaal standhoudt.",
        "uiterlijk, aanzien",
        "vol van (schoon-schijnend)",
    ),
    "cant": (
        "Onechte, hypocriete praat, vaak moraliserend.",
        "Prekerige taal die deugdzaam klinkt maar door geen echt gevoel wordt gedragen — moreel poseren op de automatische piloot.",
        "Hij was de holle bedrijfspraat over „familie” zat van een bedrijf dat niemand vrijaf gaf.",
        "zingen (later: dreunend jargon)",
        "jankerige spraak van bedelaars, daarna hypocrisie",
    ),
    "pusillanimous": (
        "Zonder moed, laf.",
        "Schuchter tot op het ruggengraatloze af — te bang om op te staan, ook als het er duidelijk toe doet.",
        "De lafhartige stilte van het bestuur liet het schandaal uit de hand lopen.",
        "zeer klein",
        "geest, moed",
    ),
    "vulpine": (
        "Vosachtig; sluw, listig.",
        "Sluw en slim zoals een vos — bijdehand, een tikje sneaky, altijd een stap voor.",
        "Hij gaf een sluwe grijns zodra hij het achterdeurtje zag.",
        "vos",
        "van of als",
    ),
    "seriatim": (
        "De een na de ander, in volgorde.",
        "Strikt één voor één, op volgorde — niet vooruit springen, niet twee tegelijk.",
        "De rechter behandelde elk van de twaalf claims één voor één.",
        "rij, reeks",
        "één voor één",
    ),
    "parsimony": (
        "Extreme zuinigheid; gierigheid.",
        "Strak zijn met geld (of woorden, of middelen) ver voorbij redelijke spaarzaamheid.",
        "Zijn zuinigheid was legendarisch — hij gebruikte theezakjes drie keer.",
        "sparen, zuinig zijn",
        "staat of praktijk",
    ),
    "emendation": (
        "Een correctie, vooral in een tekst.",
        "Een herstel in een stuk tekst — een geleerde bijstelling die een fout in een oude of belangrijke tekst rechtzet.",
        "De nieuwe uitgave bevat tientallen tekstverbeteringen aan het oorspronkelijke handschrift.",
        "uit",
        "fout, vergissing",
    ),
    "abstemious": (
        "Matig in eten en drinken.",
        "Bewust terughoudend rond eten en drinken — nooit te veel, altijd een beetje op het bord laten liggen.",
        "Zijn matige gewoonten hielden hem scherp lang nadat zijn leeftijdgenoten waren vertraagd.",
        "weg van",
        "bedwelmende drank",
    ),
    "solecism": (
        "Een grammaticale fout of een inbreuk op de etiquette.",
        "Een uitglijder in grammatica of manieren — het soort kleine fout waar een pietje-precies van ineenkrimpt.",
        "„Between you and I” is een veelvoorkomend solecisme waar grammatici nog altijd van huiveren.",
        "Cilicische stad bekend om ‘slecht’ Grieks",
        "gewoonte, wijze",
    ),
    "internecine": (
        "Betreffende conflict binnen een groep; wederzijds vernietigend.",
        "Intern gekibbel dat een groep van binnenuit verscheurt — een gevecht waarin iedereen verliest, omdat het familie tegen familie is.",
        "Het onderlinge geruzie van de partij deed meer schade dan welke buitenstaander ook kon.",
        "tussen, onder",
        "doden",
    ),
    "pococurante": (
        "Onverschillige, achteloze houding.",
        "Een schouderophalen tot persoonlijkheid verheven — zo weinig geven om wat ooit telde dat niets de moeite meer lijkt.",
        "Zijn onverschillige houding tegenover de prijsuitreiking verraste iedereen die wist hoe hard hij had gewerkt.",
        "weinig",
        "geven om",
    ),
    "imbroglio": (
        "Een verwarde, ingewikkelde situatie of ruzie.",
        "Een verknoopte, rommelige situatie die lastig te ontwarren is — deels misverstand, deels drama, allemaal verwarring.",
        "Het hele imbroglio rond de tafelschikking begon met één verkeerd geplaatst naamkaartje.",
        "in",
        "verwarren, in de knoop brengen",
    ),
    "minatory": (
        "Dreigend, onheilspellend.",
        "Met een onmiskenbare zweem van dreiging — een dreigende blik of brief maakt heel duidelijk dat er iets naars kan volgen.",
        "De dreigende toon van de brief maakte de huurder nerveus voordat ze de envelop zelfs maar had geopend.",
        "dreigen",
        "dienend tot",
    ),
    "obloquy": (
        "Harde publieke kritiek of verbale smaad.",
        "Luid, openbaar afkeuren — de soort bijtende kritiek die zich voor ieders ogen afspeelt.",
        "De klokkenluider kreeg jaren van publieke smaad voordat de geschiedenis haar gelijk gaf.",
        "tegen",
        "spreken",
    ),
    "paroxysm": (
        "Een plotselinge hevige uitbarsting, van emotie of handeling.",
        "Een plotselinge, intense golf die je in één klap overspoelt — een lachbui, woede of hoest die als een golf toeslaat.",
        "Ze werd gegrepen door een paroxisme van lachen die ze niemand anders in de kamer kon uitleggen.",
        "voorbij",
        "scherp, acuut",
    ),
    "adscititious": (
        "Van buitenaf toegevoegd, niet inherent.",
        "Van buiten vastgeschroefd in plaats van van meet af aan ingebouwd — een extra, geen kern.",
        "Het commentaar voelt aangeplakt, alsof het aan een al voltooide tekst is vastgeplakt.",
        "naar, bovendien",
        "goedkeuren, aannemen",
    ),
    "nescience": (
        "Gebrek aan kennis, onwetendheid.",
        "Gewoon niet-weten — een gat in kennis, zonder oordeel eroverheen.",
        "Hij gaf zijn onkunde over Franse wijn toe en liet de sommelier kiezen.",
        "niet",
        "weten",
    ),
    "prurience": (
        "Overdreven belangstelling voor seksuele zaken.",
        "Een te gretige, gluiperige nieuwsgierigheid naar alles wat pikant is — interesse die het gezonde voorbij is en bemoeizuchtig wordt.",
        "De wellustige nieuwsgierigheid van de boulevardkrant naar het privéleven van het stel grensde aan obsessie.",
        "jeuken, verlangen",
        "toestand van",
    ),
    "fuliginous": (
        "Roetig, donker, troebel.",
        "Donker en rookachtig, alsof alles met een dunne laag roet is overtrokken.",
        "Een roetzwarte nevel hing bij schemering over de fabrieksstad.",
        "roet",
        "vol van",
    ),
    "gainsay": (
        "Ontkennen of tegenspreken.",
        "Botweg ingaan tegen wat iemand anders zei — zeggen dat het niet zo is.",
        "Niemand durfde de oude kapitein tegen te spreken over zijn verhaal van de storm.",
        "tegen",
        "spreken",
    ),
    "ignavia": (
        "Luiheid, traagheid (uit het Latijn).",
        "Een oud Latijns woord voor pure luiheid — de sleep van nergens zin in hebben.",
        "De monniken preekten tegen traagheid als een van de stille gevaren van de ziel.",
        "niet",
        "bezig, vlijtig",
    ),
    "escutcheon": (
        "Een schild dat een wapen toont.",
        "Het schildvormige embleem met het familiewapen — het heraldische kenteken.",
        "Het wapenschild van de familie hangt nog altijd boven de voordeur van het oude landhuis.",
        "schild",
        "verkleinwoord / voorwerp",
    ),
    "superannuated": (
        "Verouderd, achterhaald, of wegens leeftijd buiten dienst.",
        "Voorbij de nuttige bloei en op non-actief gezet — te ouderwets of versleten om het werk nog te doen.",
        "De afgeschreven printer werd eindelijk vervangen na vijftien jaar vastlopen.",
        "voorbij",
        "jaar",
    ),
    "succedanea": (
        "Vervangmiddelen, vooral in de geneeskunde.",
        "Plaatsvervangende middelen als de echte behandeling er niet is — medische understudies, eigenlijk.",
        "Oorlogsartsen steunden vaak op surrogaten als de echte medicijnen opraakten.",
        "in plaats van",
        "gaan, wijken",
    ),
    "rodomontade": (
        "Opschepperig, blufferig gepraat.",
        "Groot, blazerig opscheppen — luide praat over je eigen grootsheid die vooral hete lucht is.",
        "Zijn grootspraak over het project „eigenhandig” redden fopte niemand die er echt bij was geweest.",
        "opscheppende ridder in Orlando Furioso",
        "handeling, vertoon",
    ),
    "chicane": (
        "Met listen of bedrog iets bereiken.",
        "Je doel bereiken met slinkse trucjes in plaats van eerlijk spel.",
        "Hij chicaneerde zich de deal in met een contract vol kleine lettertjes.",
        "harrewarren, bedriegen",
        "list; later een scherpe bocht",
    ),
    "mathesis": (
        "De zuivere of abstracte wetenschap van leren of kennis, vaak wiskunde.",
        "Leren in zijn puurste, abstractste vorm — de diepe structuur van kennis zelf, vooral de wiskundige.",
        "De filosoof droomde van een universele mathesis die elk kennisgebied zou verenigen.",
        "leren",
        "de daad van leren",
    ),
    "pedantic": (
        "Overdreven begaan met formele regels of triviale details.",
        "Te streng op de kleinigheden — kleine technische punten corrigeren die niets wezenlijks veranderen.",
        "Het voelde een beetje pedant om in een appbericht te twisten over „who” versus „whom”.",
        "kinderbegeleider, tutor",
        "de manier hebbend van",
    ),
    "coruscation": (
        "Een flitsend, sprankelend licht.",
        "Een snelle, glinsterende lichtflits — zonlicht op water, of een diamant die het licht vangt.",
        "De fonkeling van de kroonluchter strooide licht over elke hoek van de balzaal.",
        "glinsteren, flitsen",
        "de daad van",
    ),
    "tyro": (
        "Een beginner, een nieuweling.",
        "Iemand splinternieuw in een vaardigheid of vak — nog bezig de kneepjes te leren, nog geen kenner.",
        "Zelfs een beginnende schaakspeler ziet die blunder.",
        "rekruut, nieuweling",
        "een groene jonge soldaat",
    ),
    "execrable": (
        "Uiterst slecht, verfoeilijk.",
        "Slecht op een manier die echte afkeer verdient — niet alleen matig, maar werkelijk afschuwelijk.",
        "De recensent noemde het vervolg abominabel, en de kassa gaf hem gelijk.",
        "vervloeken",
        "waardig om, in staat tot",
    ),
    "incarnadine": (
        "Bloedrood van kleur.",
        "Een diep, fel rood — de kleur van vers bloed, beroemd gemaakt door Shakespeares Macbeth.",
        "De zonsondergang zette de hele hemel in een bloedrode gloed.",
        "in",
        "vlees (vleesrood)",
    ),
    "interstice": (
        "Een klein gat of tussenruimte.",
        "Het kleine tussenruimte dat je makkelijk over het hoofd ziet — de kier tussen de planken, het gaatje in een agenda.",
        "Onkruid duwde omhoog door elke voeg in het oude bakstenen pad.",
        "tussen",
        "staan",
    ),
    "animadversion": (
        "Kritische of afkeurende opmerkingen.",
        "Puntige, afkeurende commentaren — de soort kritiek die een tikje berispend klinkt.",
        "De berispingen van de professor op het essay vulden de kantlijnen met rode inkt.",
        "geest",
        "zich toewenden",
    ),
    "irrefragable": (
        "Onweerlegbaar, onloochenbaar.",
        "Zo stevig bewezen dat er niet tegenin te gaan valt — de zaak is simpelweg gesloten.",
        "Het DNA-bewijs was onweerlegbaar, en het proces was binnen het uur voorbij.",
        "niet",
        "zich verzetten, weerstaan",
    ),
    "involution": (
        "Complexiteit, ingewikkeldheid; ook een naar binnen krullen.",
        "Een verknoopte, in-zichzelf-gevouwen complexiteit — dingen zo strak in elkaar gewikkeld dat ze lastig los te trekken zijn.",
        "De verwikkeling van het plot liet de helft van het publiek na de aftiteling nog ontwarren.",
        "in, naar binnen",
        "rollen, keren",
    ),
    "dint": (
        "Kracht of inspanning, zoals in „by dint of”.",
        "Puur krachtvertoon of inzet — overleeft vooral in de uitdrukking „by dint of”.",
        "Hij slaagde voor het examen door louter koppig oefenen.",
        "een slag, een stoot",
        "krachtens",
    ),
    "mortised": (
        "Verbonden met een pen-en-gatverbinding; stevig in elkaar gepast.",
        "Op de ouderwetse timmermansmanier in elkaar gezet — het ene stuk glijdt precies in een gat dat er speciaal voor is uitgezaagd.",
        "De balken van de oude schuur waren met pen-en-gatverbindingen in elkaar gezet zonder één spijker.",
        "een holte, een gat",
        "een beet, een greep",
    ),
    "apposite": (
        "Uiterst treffend, passend.",
        "Precies de juiste vondst voor het moment — een opmerking, citaat of voorbeeld dat keihard raak is.",
        "Haar treffende opmerking vatte het hele debat in één zin samen.",
        "naar",
        "plaatsen",
    ),
    "lambent": (
        "Zacht gloeiend of flikkerend (licht); ook: lichte geestigheid.",
        "Zacht gloeiend in plaats van fel — een flikkerend licht, of een geest die speels is in plaats van scherp.",
        "Kaarslicht wierp een zacht flakkerende gloed over de oude eetkamer.",
        "likken",
        "doend (licht dat ‘likt’)",
    ),
    "anchorite": (
        "Een religieuze kluizenaar die in eenzaamheid leeft.",
        "Iemand die zich helemaal uit de wereld terugtrekt om alleen in gebed en overdenking te leven.",
        "De kluizenaar woonde meer dan dertig jaar in een kleine cel tegen de kerk aan.",
        "terug, weg",
        "zich terugtrekken",
    ),
    "slake": (
        "Dorst lessen; blussen.",
        "Een hunkering helemaal stillen — meestal dorst, maar figuurlijk ook elke diepe behoefte.",
        "Één koud glas water laafde zijn dorst na de lange wandeling.",
        "slap, los",
        "verslappen, stillen",
    ),
    "acicular": (
        "Naaldvormig.",
        "Lang, dun en puntig als een naald — de vorm van een dennennaald of een scherp kristalletje.",
        "Dennen zijn makkelijk te herkennen aan hun naaldvormige bladeren.",
        "naald",
        "klein",
    ),
    "effete": (
        "Uitgeput van levenskracht, zwak, oververfijnd.",
        "Versleten en week — de oorspronkelijke kracht kwijtgeraakt door te veel comfort of verfijning.",
        "Critici noemden het ooit gedurfde tijdschrift uitgeblust, een schim van zijn brutale beginjaren.",
        "uit",
        "vruchtbaar, gedragen hebbend",
    ),
    "appurtenance": (
        "Een bijzaak of klein aangehecht item of recht.",
        "Een klein extraatje dat bij iets groters hoort — de accessoires en aanhangsels bij het hoofdzaken.",
        "De huurovereenkomst omvatte de garage en al haar aanhorigheden.",
        "naar",
        "behoren",
    ),
    "gloze": (
        "Een fout wegmoffelen of kleiner maken.",
        "Een misser met zachte woorden gladstrijken, zodat hij kleiner klinkt dan hij is.",
        "Hij probeerde de gemiste deadline te verbloemen met vage praat over „onvoorziene tegenslagen”.",
        "een glosse, een uitleg",
        "commentariëren — daarna gladstrijken",
    ),
    "incipient": (
        "In een vroeg stadium, net beginnend.",
        "Net zichtbaar aan het worden — het allereerste, nauwelijks merkbare begin van iets groters.",
        "Artsen vingen de beginnende tekenen van de ziekte voordat die zich kon verspreiden.",
        "op, in",
        "nemen (opnemen, beginnen)",
    ),
    "afflatus": (
        "Creatieve inspiratie, vooral goddelijke.",
        "Een plotselinge golf van inspiratie die groter voelt dan jij — alsof het idee je van elders is ingeblazen.",
        "De dichter beschreef hoe het hele stuk in één vlaag van ingeving om drie uur ’s nachts arriveerde.",
        "naar, op",
        "blazen (een aanblazing)",
    ),
}
