# Spanish (Spain) overlays: (definition, friendly, exampleGloss, root1, root2)
WORDS = {
    "edulcorate": (
        "Endulzar o purificar; quitar a algo su aspereza.",
        "Quitar el aguijón o la amargura — endulzar de verdad, o suavizar en sentido figurado una idea dura para que baje mejor.",
        "El redactor suavizó la crítica dura antes de mandarla a imprenta.",
        "fuera, a fondo",
        "dulce",
    ),
    "pietistic": (
        "Excesiva o fingidamente religioso o piadoso.",
        "Describe a alguien cuya devoción huele a espectáculo: más pose que fe de verdad.",
        "Sus suspiros pietistas durante el sermón molestaron al resto del banco.",
        "piedad, sentido del deber",
        "que tiene el carácter de",
    ),
    "amphiboly": (
        "Ambigüedad nacida de la estructura gramatical: una frase que se lee de dos maneras.",
        "Una frase gramaticalmente correcta, pero que se puede leer de dos modos del todo distintos, como «Visiting relatives can be tiring».",
        "«Visiting relatives can be tiring» es una anfibología clásica: ¿cansan los parientes o el hecho de visitarlos?",
        "ambos, a ambos lados",
        "lanzar",
    ),
    "trenchant": (
        "Agudo, incisivo, que va al grano.",
        "Corta de lleno el relleno: una observación o una mente incisiva llega al meollo enseguida, sin palabras de más.",
        "Su crítica incisiva no dejó recoveco donde se escondieran los agujeros del guion.",
        "cortar",
        "haciendo, que tiene la cualidad de",
    ),
    "inchoative": (
        "Que acaba de empezar; en una fase temprana o rudimentaria.",
        "Aún en los primeros instantes: un plan, un sentimiento o un proceso que apenas empieza a tomar forma.",
        "Las etapas iniciales del tratado eran prometedoras, pero quedaban muchos detalles en el aire.",
        "empezar, dar comienzo",
        "que tiende hacia",
    ),
    "panegyric": (
        "Un discurso o escrito formal que alaba a alguien con esplendor.",
        "Un homenaje en toda regla: pensad en un elogio fúnebre luminoso o en un discurso que pregonara los logros de alguien a los cuatro vientos.",
        "A la profesora que se jubilaba la despidieron con un panegírico de sus alumnos más cercanos.",
        "todo, entero",
        "asamblea, reunión",
    ),
    "ontic": (
        "Relativo a la existencia real, frente a la teoría abstracta.",
        "De las cosas tal como existen de verdad, no solo como ideas o teorías sobre ellas.",
        "Los filósofos discuten si los números tienen algún estatus óntico o existen solo en nuestra mente.",
        "ser, lo que existe",
        "relativo a",
    ),
    "fructify": (
        "Dar fruto, o volverse productivo.",
        "Por fin dar fruto: un esfuerzo, una idea o una inversión que fructifica ha pasado de semilla a algo útil.",
        "Años de investigación callada fructificaron al fin en una vacuna que funciona.",
        "fruto",
        "hacer, causar",
    ),
    "proleptical": (
        "Anticipar o presentar algo como ya hecho antes de que ocurra.",
        "Adelantarse de un modo literario: describir un hecho futuro como si ya estuviera cerrado, para que el golpe llegue más hondo.",
        "El brindis proléptico del general a «la victoria» se pronunció una semana entera antes de la batalla.",
        "antes",
        "tomar, asir",
    ),
    "pneumatic": (
        "Accionado por presión de aire; también relativo al espíritu o al aliento.",
        "Lo más habitual: movido por aire comprimido —un taladro, un freno de autobús—, pero la misma raíz griega habla también de aliento y de espíritu.",
        "Los frenos neumáticos silbaron cuando el autobús se detuvo en el bordillo.",
        "viento, aliento, espíritu",
        "perteneciente a",
    ),
    "cataphatic": (
        "Describir a Dios o lo divino con afirmaciones positivas: lo contrario de apofático.",
        "Hablar de Dios diciendo lo que es —«Dios es amor», «Dios es justo»— en vez de solo lo que no es.",
        "La teología catafática habla con confianza de Dios como amoroso, justo y misericordioso.",
        "abajo, según",
        "hablar, decir",
    ),
    "fiducial": (
        "Basado en la confianza o la fe; también: un punto de referencia fijo.",
        "Algo que se toma a crédito y luego sirve de ancla: una marca fiduciaria es el punto fijo contra el que se mide todo lo demás.",
        "Los topógrafos colocaron un marcador de referencia en la roca antes de cartografiar el lugar.",
        "confiar",
        "confianza, seguridad",
    ),
    "theodicy": (
        "Una defensa de la bondad de Dios ante la existencia del mal.",
        "El intento de siempre: responder «si Dios es bueno, ¿por qué hay mal?» sin renunciar a ninguna de las dos afirmaciones.",
        "Su tesis exploraba la teodicea a través del prisma del Libro de Job.",
        "dios",
        "justicia",
    ),
    "circumincession": (
        "Inhabitación mutua: término teológico para cómo las personas de la Trinidad existen unas en otras.",
        "Una palabra de teología para un conjunto tres-en-uno tan completo que cada parte contiene a las otras y es contenida por ellas.",
        "La doctrina de la pericóresis intenta explicar cómo Padre, Hijo y Espíritu son distintos y a la vez inseparables.",
        "alrededor",
        "ir, andar",
    ),
    "redound": (
        "Tener una consecuencia que beneficia a alguien o recae sobre él.",
        "Cuando el crédito (o la culpa) rebota hacia quien es responsable: las buenas obras que redundan en tu nombre vuelven luego como premio.",
        "El éxito del equipo redundará en crédito de su entrenador callado y trabajador.",
        "atrás, de nuevo",
        "ola",
    ),
    "ineluctable": (
        "Que no se puede evitar ni de lo que no se puede escapar.",
        "Va a ocurrir hagas lo que hagas: de un desenlace ineludible no te escabulles.",
        "La vejez llega para todos; es sencillamente ineludible.",
        "no",
        "forcejear para salir",
    ),
    "periphrastic": (
        "Que usa un rodeo verboso en lugar de una forma directa.",
        "Tomar el camino largo con las palabras: decir en toda una frase lo que bastaría una sola palabra.",
        "Sus correos perifrásticos podrían haber dicho en una línea lo que le ocupó tres párrafos.",
        "alrededor",
        "declarar, contar",
    ),
    "hebetude": (
        "Embotamiento mental o letargo.",
        "Ese estado de mente brumosa y lenta en el que pensar es como vadear jarabe.",
        "Una oleada de embotamiento cayó sobre la clase justo después de comer.",
        "romo, embotado",
        "estado o cualidad",
    ),
    "unpropitious": (
        "Poco favorable; de mal agüero.",
        "Mal signo: condiciones o un momento que ya parecen ir contra ti antes de haber empezado.",
        "Cielo gris y batería del coche muerta hicieron un arranque poco propicio para el viaje.",
        "no",
        "favorable, gracioso",
    ),
    "fricaseed": (
        "Carne estofada o braseada en salsa; bien escrito «fricasseed».",
        "Un término de cocina antiguo y hogareño para carne troceada y cocida a fuego lento en su propia salsa hasta que queda tierna.",
        "El pollo en fricasé de la abuela era lo mejor de cada comida del domingo.",
        "freír",
        "romper (en trozos)",
    ),
    "ersatz": (
        "Un sustituto artificial o de menor calidad.",
        "Una imitación que hace las veces de lo auténtico: cumple, pero todo el mundo ve que no es el original.",
        "En tiempo de guerra, los compradores se apañaban con sucedáneo de café de achicoria tostada.",
        "fuera, prefijo de reemplazo",
        "poner, colocar",
    ),
    "reify": (
        "Tratar una idea abstracta como si fuera una cosa concreta.",
        "Hacer que una idea se sienta real y sólida: convertir algo borroso, como «el mercado», en un objeto al que se puede señalar.",
        "Llamar «espíritu» de una nación a un ser propio cosifica algo que en realidad no son más que millones de decisiones sueltas.",
        "cosa",
        "hacer",
    ),
    "eluded": (
        "Escapado o evitado con habilidad.",
        "Escurrirse limpio: esquivar algo, a menudo con astucia o por los pelos, sea una captura, una pregunta o una respuesta.",
        "La respuesta se le escapó durante horas hasta que, de pronto, encajó bajo la ducha.",
        "fuera, lejos",
        "jugar",
    ),
    "aporetic": (
        "Que expresa duda, perplejidad o una contradicción sin resolver.",
        "Atascado en un callejón de verdad del pensamiento: no por pereza, sino porque la pregunta misma se resiste a una respuesta limpia.",
        "Sócrates solía terminar sus diálogos en una nota aporética, con más preguntas que respuestas.",
        "sin",
        "paso, camino",
    ),
    "metonymy": (
        "Figura que nombra algo por un término asociado, p. ej. «la corona» por el monarca.",
        "Usar una palabra afín en lugar de la cosa misma: decir «Wall Street» cuando se quiere decir la bolsa.",
        "«Wall Street had a rough day» es metonimia: en realidad significa que la bolsa lo pasó mal.",
        "cambio, después",
        "nombre",
    ),
    "deracinate": (
        "Desarraigar; arrancar de un entorno natural.",
        "Arrancar algo (o a alguien) de raíz, lejos del lugar o de la cultura a los que pertenece.",
        "La guerra desarraigó a toda una generación y dispersó familias a través de las fronteras.",
        "lejos, fuera",
        "raíz",
    ),
    "euphonious": (
        "De sonido agradable.",
        "Simplemente agradable de oír: una palabra o una frase eufónica resbala, casi con música, en el oído.",
        "«Murmuring brook» es una frasita eufónica, suave y fácil de decir.",
        "bueno, bien",
        "sonido, voz",
    ),
    "putative": (
        "Generalmente supuesto o tenido por tal.",
        "Tenerse por cierto a gran escala, aunque no esté demostrado: la versión presunta o supuesta de algo.",
        "El autor putativo de la carta resultó ser más tarde un desconocido total.",
        "pensar, considerar",
        "que tiene la naturaleza de",
    ),
    "neologism": (
        "Una palabra o locución de nuevo cuño.",
        "Una palabra flamante: recién inventada, aún (apenas) en el diccionario.",
        "«Doomscrolling» empezó como neologismo y enseguida se volvió jerga cotidiana.",
        "nuevo",
        "palabra, habla",
    ),
    "splenetic": (
        "Enfadado o de mal genio.",
        "De humor agrio e irritable, pronto a saltar: como se creía antaño que el bazo gobernaba el temperamento.",
        "Disparó una respuesta airada al correo a los pocos segundos de leerlo.",
        "bazo (sede de la ira)",
        "afectado por",
    ),
    "sententious": (
        "Dado a moralizar de modo pomposo o afectado.",
        "Le encanta soltar leccioncitas de vida, como si cada frase fuera una galleta de la fortuna.",
        "Su brindis sentencioso sobre «el verdadero sentido de la amistad» hizo que todos miraran el reloj.",
        "opinión, máxima",
        "lleno de",
    ),
    "garrulous": (
        "Excesivamente hablador, sobre todo de nimiedades.",
        "No para de charlar: divaga sobre minucias mucho después de que los demás se hayan quedado sin tema.",
        "El taxista parlanchín nos contó toda su vida antes de que saliéramos del aeropuerto.",
        "charlar, parlotear",
        "inclinado a",
    ),
    "fatuity": (
        "Necedad, tontería.",
        "La necedad lisa: un comentario o un plan tan tonto que apenas merece una respuesta seria.",
        "La pura necedad del plan se hizo evidente en cuanto lo probaron.",
        "necio, tonto",
        "estado de ser",
    ),
    "peroration": (
        "La parte conclusiva de un discurso, a menudo recapitulativa.",
        "El gran final de un discurso: el tramo en el que el orador lo reúne todo y clava el punto.",
        "En la peroración, la mitad del público estaba en pie.",
        "a través, hasta el final",
        "hablar, alegar",
    ),
    "tautology": (
        "Repetición innecesaria de la misma idea con otras palabras.",
        "Decir lo mismo dos veces sin añadir nada, como «regalo gratis» o «it is what it is».",
        "«It is what it is» es una tautología favorita de quien esquiva una explicación de verdad.",
        "lo mismo",
        "palabra, habla",
    ),
    "laconism": (
        "El uso de muy pocas palabras; un hablar escueto.",
        "Decir mucho con muy poco: el arte de la réplica corta y seca, llamado así por los espartanos de Laconia, famosos por su brevedad.",
        "«Molon labe» — «ven y tómalas» — es el trozo de laconismo más famoso de la historia.",
        "un espartano de Laconia",
        "práctica, manera",
    ),
    "pabulum": (
        "Ideas insípidas y demasiado simplificadas; en origen, comida sosa o papilla.",
        "Pensamiento aguado: un contenido tan simplificado y tan seguro que no nutre la mente.",
        "El discurso del político era sobre todo palabrería hueca: promesas vagas a las que no se podía agarrar nada.",
        "alimentar",
        "medio o instrumento",
    ),
    "soporific": (
        "Que provoca sueño o somnolencia.",
        "Tan aburrido —o tan literalmente sedante— que te entra el sueño. Pensad en leche caliente, o en una reunión de presupuestos de tres horas.",
        "El zumbido soporífero de la conferencia tenía a la mitad de la sala luchando por no cerrar los ojos.",
        "sueño profundo",
        "que hace, que causa",
    ),
    "unctuous": (
        "Excesivamente halagador o aceitoso en el trato.",
        "Tan suave de encanto que resbala: una lisonja tan espesa que casi se nota la grasa.",
        "El vendedor empalagoso no paraba de elogiar mi «excelente gusto» antes de cada venta extra.",
        "ungir, aceitar",
        "lleno de",
    ),
    "captious": (
        "Pronto a hallar falta, demasiado crítico con lo trivial.",
        "Tiquismiquis hasta el exceso: el tipo que le encuentra pegas a todo, aunque no importe.",
        "Sus notas quisquillosas al informe se centraban por completo en las comas.",
        "asir, tomar",
        "una trampa, un sofisma",
    ),
    "torpid": (
        "Lento, inactivo de mente o de cuerpo.",
        "Lento y a medio dormir, como un oso en hibernación: apenas se mueve, apenas piensa.",
        "La oficina cayó aletargada bajo el calor pesado de agosto.",
        "estar entumecido, estar perezoso",
        "en un estado de",
    ),
    "seneschal": (
        "Un mayordomo o oficial que administraba una casa medieval.",
        "La versión medieval de un jefe de personal: el oficial de confianza que llevaba al día la casa y la hacienda de un señor.",
        "El senescal del castillo gestionaba desde las cuentas de la cosecha hasta la lista de invitados.",
        "viejo, senior",
        "siervo",
    ),
    "expatiate": (
        "Hablar o escribir por extenso sobre un tema.",
        "Ponerse en marcha de verdad: hablar o escribir sin parar, recorriendo el asunto por todos los lados.",
        "Preguntadle por coches de época y va a explayarse durante una hora entera.",
        "fuera",
        "espacio",
    ),
    "nugatory": (
        "Sin valor, fútil; también inválido o ineficaz.",
        "Que no vale casi nada: una cláusula nugatoria en un contrato, en la práctica, no hace nada.",
        "El tribunal declaró nulo el viejo reglamento, pues nunca se había aplicado.",
        "fruslerías, disparates",
        "perteneciente a",
    ),
    "sagacity": (
        "Sabiduría, juicio perspicaz.",
        "Una sabiduría viva y práctica: el buen juicio que viene de la experiencia, no solo de los libros.",
        "La sagacidad del viejo capitán sacó a la tripulación de apuros más de una vez.",
        "de olfato fino, perspicaz",
        "cualidad de",
    ),
    "canaille": (
        "El vulgo o la masa, usado con desprecio.",
        "Una palabra snob y despectiva para la gente corriente, como si fueran una jauría.",
        "El conde se mofó de la chusma reunida fuera de las puertas del palacio.",
        "perro",
        "colectivo, jauría",
    ),
    "contumely": (
        "Trato o lenguaje insolente y humillante.",
        "Un trato cruel y desdeñoso pensado para humillar: el insulto hecho para escocer.",
        "Soportó años de afrentas de los críticos antes de que su obra fuera por fin reconocida.",
        "con, a fondo",
        "hincharse (de orgullo)",
    ),
    "askance": (
        "Con recelo o desaprobación; una mirada de soslayo.",
        "La mirada de reojo que se le echa a algo en lo que no se confía del todo: una mirada cargada de duda.",
        "La maestra miró con recelo los deberes sospechosamente limpios.",
        "hacia, a",
        "sesgo, inclinación",
    ),
    "clodpate": (
        "Un zoquete; un cabezota.",
        "Un insulto antiguo, casi cariñoso, para alguien torpe o denso: un zoquete.",
        "«Serás zoquete», se rió ella, «has llevado el mapa del revés todo el rato.»",
        "terron de tierra",
        "cabeza",
    ),
    "actuate": (
        "Poner en movimiento o en acción; motivar.",
        "Ser la chispa que pone algo en marcha: una máquina que se enciende o una persona que por fin actúa sobre una idea.",
        "El miedo a perder el contrato impulsó a todo el equipo a un fin de semana de horas extra.",
        "un hacer, un impulsar",
        "impulsar, hacer",
    ),
    "peculation": (
        "Malversación de fondos confiados a su cuidado.",
        "Robar en silencio el dinero que se debía custodiar: la malversación, vestida a la antigua.",
        "El desfalco del tesorero pasó desapercibido casi una década.",
        "propiedad privada",
        "ganado, riqueza",
    ),
    "demi-monde": (
        "Un grupo considerado en los márgenes de la sociedad respetable.",
        "El bajo mundo glamoroso y turbio: gente que vive justo fuera de las reglas del decoro.",
        "La novela sigue a una cantante en el mundo galante de los cabarets de los años veinte.",
        "medio",
        "mundo, sociedad",
    ),
    "extant": (
        "Que aún existe; no extinguido ni destruido.",
        "Sigue aquí hoy: se dice de cosas viejas (manuscritos, especies, edificios) que han logrado sobrevivir.",
        "Solo se conservan tres ejemplares de la primera impresión.",
        "fuera",
        "estar de pie",
    ),
    "perfidy": (
        "Engaño; traición de la confianza.",
        "Una traición honda y deliberada: romper una confianza que alguien tenía derecho a esperar de ti.",
        "El general nunca perdonó la perfidia de su viejo amigo en la mesa de negociación.",
        "a través, contra",
        "fe, confianza",
    ),
    "patois": (
        "Un dialecto regional, sobre todo no estándar.",
        "El modo propio, local, de hablar en una comarca: lleno de palabras y ritmos que un forastero no coge.",
        "Su abuela aún hablaba el dialecto de la isla en las comidas familiares.",
        "habla tosca, dialecto",
        "pata — habla torpe",
    ),
    "prerogative": (
        "Un derecho especial de una persona o un grupo.",
        "Un privilegio que es solo vuestro: un derecho que llega con el papel, el puesto o el rango.",
        "Elegir el destino de las vacaciones familiares es la prerrogativa del abuelo, y todo el mundo lo sabe.",
        "antes",
        "preguntar, votar",
    ),
    "hardihood": (
        "Osadía, audacia; también tesón o aguante.",
        "Una resistencia recia y valiente: el nervio de seguir adelante y el tesón de aguantar una vez en marcha.",
        "Hizo falta un arrojo de verdad para cruzar el puerto en una nevada, sin mapa.",
        "osado, recio",
        "estado, condición",
    ),
    "effloresce": (
        "Estallar en flor; también desarrollarse o aparecer poco a poco.",
        "Abrirse hasta expresarse del todo: como una flor que se abre, o una idea que por fin da con su forma.",
        "Su talento callado para la pintura floreció en cuanto tuvo un estudio propio.",
        "fuera",
        "empezar a florecer",
    ),
    "plumb-line": (
        "Un hilo con peso para juzgar la vertical; en sentido figurado, un criterio.",
        "Un peso en un hilo que cuelga a plomo, para ver si algo está de verdad vertical — y, por extensión, cualquier medida fija contra la que se compara el resto.",
        "Usaba la honestidad de su abuelo como una especie de plomada para cada decisión.",
        "plomo",
        "cuerda, medida",
    ),
    "fain": (
        "De buen grado, con gusto (arcaico).",
        "Un modo antiguo de decir «con gusto» o «de buena gana»: quien hace algo «fain» lo hace de muy buen grado.",
        "«De buena gana descansaría aquí un rato», suspiró el viajero.",
        "alegre, gozoso",
        "de buen grado, con gusto",
    ),
    "opprobrium": (
        "Crítica pública dura, o deshonra.",
        "La vergüenza pública echada encima de alguien a lo grande: la deshonra de una desaprobación general.",
        "El escándalo trajo oprobio público sobre toda la firma.",
        "contra",
        "deshonra, reproche",
    ),
    "mordant": (
        "Agudamente sarcástico, mordaz en el ingenio o la crítica.",
        "Ingenio con dientes de verdad: un comentario mordaz pica precisamente porque apunta tan bien.",
        "Sus críticas de cine mordaces las temían los directores y las amaban los lectores.",
        "morder",
        "mordaz, haciendo",
    ),
    "pronunciamento": (
        "Una proclamación formal, a menudo política o militar.",
        "Un anuncio grande y oficial: suele ser el que declara un gobierno nuevo, un alzamiento o un decreto mayor.",
        "El pronunciamiento del general anunció el nuevo gobierno al amanecer.",
        "adelante",
        "anunciar",
    ),
    "sciolist": (
        "Persona de saber superficial que se hace pasar por experto.",
        "Alguien que ha rozado la superficie de un tema y luego habla como si hubiera escrito el manual.",
        "El sabihondo de la cena corrigió con aplomo al auténtico astrofísico de la mesa.",
        "saber",
        "diminutivo: un pequeño sabedor",
    ),
    "dotage": (
        "El declive de las facultades mentales en la vejez.",
        "El tramo brumoso y olvidadizo de la vejez avanzada, cuando la agudeza de la mente empieza a apagarse.",
        "En su chochez, contaba las mismas tres historias en cada visita, cada vez como si fueran nuevas.",
        "chochear, ser necio",
        "estado o resultado",
    ),
    "lee-side": (
        "El lado resguardado del viento.",
        "El lado calmo y abrigado de algo —una colina, un barco, un muro— donde el viento ya no os alcanza del todo.",
        "Los excursionistas plantaron la tienda a socaire de la cresta para escapar de las ráfagas.",
        "abrigo, protección",
        "flanco, cara",
    ),
    "parry": (
        "Desviar o rechazar un golpe, una pregunta o un argumento.",
        "Apartar con soltura: un tajo de espada, una pregunta incómoda, una acusación, sin perder el compás.",
        "Ella esquivó la pregunta tramposa del reportero con una broma fácil.",
        "rechazar",
        "preparar, defender",
    ),
    "mephitic": (
        "De olor nauseabundo, nocivo.",
        "Hediondo de un modo casi tóxico: un tufo tan malo que parece peligroso respirar.",
        "Un olor mefítico subió del pantano al ponerse el sol.",
        "vapor nocivo",
        "que tiene la naturaleza de",
    ),
    "sybarite": (
        "Persona entregada al lujo y al placer.",
        "Alguien que vive para el confort y el deleite —buena mesa, camas blandas, vida fácil—, llamado así por la ciudad griega de Síbaris, famosa por su exceso.",
        "Un verdadero sibarita, rechazaba cualquier habitación de hotel sin bañera.",
        "antigua ciudad griega famosa por el lujo",
        "habitante de",
    ),
    "prescind": (
        "Dejar de lado o ignorar a propósito una parte de algo.",
        "Apartar a propósito, en la mente, una pieza del rompecabezas para mirar limpio el resto.",
        "Prescindamos un momento del coste y preguntemos solo si el plan funciona de verdad.",
        "antes, lejos",
        "cortar",
    ),
    "excoriate": (
        "Criticar con dureza; también, despellejar.",
        "Desollar a alguien a palos de crítica: como si se le arrancara la piel de verdad.",
        "Los críticos vapulearon la secuela por traicionar todo lo que los fans amaban del original.",
        "fuera",
        "piel, cuero",
    ),
    "adduce": (
        "Citar como prueba o como evidencia.",
        "Traer un hecho o un ejemplo para sostener el punto: aquello a lo que se señala cuando alguien pide pruebas.",
        "La abogada adujo tres testigos en apoyo de la coartada de su clienta.",
        "hacia",
        "conducir",
    ),
    "peregrinations": (
        "Viajes o andanzas, sobre todo largos o extensos.",
        "Largos periplos errantes: esa clase de deambular que os tiene lejos de casa una buena temporada.",
        "Sus peregrinaciones por tres continentes llenaron toda una estantería de diarios de viaje.",
        "a través",
        "campo, tierra (peregrinus: extranjero)",
    ),
    "mendicant": (
        "Un mendigo, o quien vive de limosnas.",
        "Alguien que vive pidiendo caridad: históricamente, también frailes que hicieron voto de pobreza y vivían de donativos.",
        "Los frailes mendicantes no poseían nada y dependían por entero de la bondad de los aldeanos.",
        "mendigar",
        "mendigo",
    ),
    "munificent": (
        "Extremadamente generoso.",
        "Generoso a una escala casi teatral: el don que arranca un pequeño «ah».",
        "La donación munificente sufragó toda el ala nueva de la biblioteca.",
        "don, servicio",
        "haciendo, dando",
    ),
    "inanition": (
        "Agotamiento por falta de alimento; también falta de vitalidad.",
        "Un estado débil, vaciado, por no estar alimentado: en lo literal por hambre, o en lo figurado por no quedar combustible.",
        "Al final del asedio, los soldados estaban cerca de la inanición.",
        "vacío, vano",
        "el acto o el resultado de",
    ),
    "vituperation": (
        "Crítica amarga e injuriosa.",
        "Una crítica que ha dejado atrás lo justo y se ha vuelto una diatriba airada y amarga.",
        "Los comentarios en línea se disolvieron en puro vituperio en cuestión de minutos.",
        "falta, defecto",
        "preparar, suministrar",
    ),
    "inimical": (
        "Hostil, dañino en sus efectos.",
        "Que trabaja en contra, aunque sea en silencio: condiciones o actitudes poco amigas de vuestros intereses.",
        "La nueva política era perjudicial para los pequeños negocios, aunque esa no fuera la intención.",
        "no",
        "amigo",
    ),
    "invidious": (
        "Propenso a causar rencor, a menudo por comparaciones injustas.",
        "Seguro que alguien se siente menospreciado: casi siempre porque se pone a gente o a cosas en competencia desigual.",
        "Clasificar a los hermanos por «a quién quiere más mamá» es un juego odioso que nadie debería jugar.",
        "envidia",
        "mirar (con mala voluntad)",
    ),
    "subaltern": (
        "Persona de rango o estatus inferior; un subordinado.",
        "Alguien más abajo en la cadena de mando o en la escala social: un junior, bajo alguien con más poder.",
        "Como joven subalterno, recibió órdenes mucho tiempo antes de darlas.",
        "bajo",
        "alternativo, otro",
    ),
    "execrate": (
        "Sentir o expresar un odio intenso.",
        "Aborrecer algo tanto que se maldice en voz alta: una detestación pura y sonora.",
        "Los aldeanos execraban al recaudador cada vez que su carro cruzaba el pueblo.",
        "fuera de",
        "sagrado (maldecir fuera de lo sagrado)",
    ),
    "integument": (
        "Una cubierta natural exterior, como la piel o un caparazón.",
        "El envoltorio protector de la naturaleza: piel, concha, cáscara o corteza, lo que cubre y resguarda a un ser vivo.",
        "El caparazón de una tortuga es un tegumento notablemente recio.",
        "sobre, encima",
        "cubrir",
    ),
    "ingenuous": (
        "Inocente, ingenuo, de simplicidad infantil; lo contrario de taimado.",
        "Abiertamente confiado y un poco ingenuo, sin agenda oculta: fácil de confundir con «ingenious», que significa ingenioso.",
        "Su pregunta ingenua —«¿por qué mentiría alguien sobre eso?»— mostraba lo poca astucia que tenía.",
        "en, nativo",
        "engendrar (de nacimiento libre, cándido)",
    ),
    "pedantry": (
        "Preocupación excesiva por detalles menores o reglas.",
        "Perderse en las reglas chicas y fallar el cuadro grande: obsesionarse con la letra pequeña que a nadie más le importa.",
        "Su pedantería con las comas de Oxford descarriló toda la reunión.",
        "preceptor de niños",
        "práctica o cualidad",
    ),
    "perscrutation": (
        "Un examen minucioso y cuidadoso.",
        "Una mirada honda, que no deja piedra por mover: recorrer cada detalle con verdadero cuidado.",
        "Solo tras un escrutinio atento de los libros apareció la discrepancia.",
        "a través, a fondo",
        "buscar, examinar",
    ),
    "demur": (
        "Poner objeciones; mostrar reticencia.",
        "Echarse atrás con cortesía o dudar en vez de seguir de primeras: un suave «un momento».",
        "Cuando le pidieron firmar sin leer, ella puso reparos.",
        "de, lejos",
        "demorar",
    ),
    "specious": (
        "Plausible en apariencia, pero en realidad falso.",
        "Suena convincente a primera vista, pero se deshace en cuanto se comprueba de verdad.",
        "«Everyone's doing it» es un argumento especioso que nunca aguanta del todo el escrutinio.",
        "apariencia, aspecto",
        "lleno de (de bello parecer)",
    ),
    "cant": (
        "Charla insincera e hipócrita, a menudo moralizante.",
        "Un hablar de púlpito que suena virtuoso sin sentimiento verdadero: pose moral en piloto automático.",
        "Estaba harto de la jerga piadosa de empresa sobre la «familia» en una compañía que nunca daba un día libre.",
        "cantar (luego: jerga cantarina)",
        "habla quejumbrosa de mendigos, luego hipocresía",
    ),
    "pusillanimous": (
        "Falto de valor, cobarde.",
        "Tímido hasta no tener columna: demasiado asustado para alzarse, incluso cuando claramente importa.",
        "El silencio pusilánime del consejo dejó que el escándalo se desbocara.",
        "muy pequeño",
        "espíritu, valor",
    ),
    "vulpine": (
        "De zorro; astuto, ladino.",
        "Taimado y listo como un zorro: vivo de mente, un poco taimado, siempre un paso por delante.",
        "Dio una sonrisa vulpina en cuanto vio la laguna.",
        "zorro",
        "de o como",
    ),
    "seriatim": (
        "Uno tras otro, en secuencia.",
        "Tomado estrictamente de uno en uno, en orden: sin saltar, sin hacer dos a la vez.",
        "El juez abordó cada una de las doce pretensiones una por una.",
        "fila, secuencia",
        "uno a uno",
    ),
    "parsimony": (
        "Frugalidad extrema; tacañería.",
        "Andar corto de dinero (o de palabras, o de recursos) mucho más allá de un ahorro razonable.",
        "Su tacañería era legendaria: reutilizaba las bolsitas de té tres veces.",
        "escatimar, ser frugal",
        "estado o práctica",
    ),
    "emendation": (
        "Una corrección, sobre todo en un texto.",
        "Un arreglo en un escrito: un retoque erudito que corrige un error en un texto viejo o importante.",
        "La nueva edición incluye decenas de enmiendas al manuscrito original.",
        "fuera de",
        "falta, error",
    ),
    "abstemious": (
        "Moderado en el comer y el beber.",
        "Deliberadamente contenido en mesa: nunca en exceso, siempre dejando un poco en el plato.",
        "Sus hábitos sobrios lo mantuvieron lúcido mucho después de que sus pares se hubieran ralentizado.",
        "lejos de",
        "bebida embriagante",
    ),
    "solecism": (
        "Un error gramatical o una falta de etiqueta.",
        "Un resbalón de gramática o de maneras: el pequeño error que hace encogerse a un quisquilloso.",
        "«Between you and I» es un solecismo común que aún hace estremecer a los gramáticos.",
        "ciudad cilicia conocida por su griego «malo»",
        "práctica, manera",
    ),
    "internecine": (
        "Relativo a un conflicto interno a un grupo; mutuamente destructivo.",
        "Riñas internas que desgarran un grupo desde dentro: una pelea en la que todos pierden, porque es familia contra familia.",
        "Las rencillas intestinas del partido hicieron más daño que cualquier rival de fuera.",
        "entre, en medio",
        "matar",
    ),
    "pococurante": (
        "Actitud indiferente, descuidada.",
        "Un encogimiento de hombros vuelto personalidad: importar tan poco lo que antaño importaba que nada parece ya merecer el esfuerzo.",
        "Su actitud displicente hacia la gala de premios sorprendió a cuantos sabían lo duro que había trabajado.",
        "poco",
        "cuidar de",
    ),
    "imbroglio": (
        "Una situación o disputa confusa y enrevesada.",
        "Un lío enmarañado, difícil de desentrañar: parte malentendido, parte drama, todo confusión.",
        "Todo el embrollo del plano de mesas empezó con una tarjeta de nombre mal puesta.",
        "en",
        "enredar, confundir",
    ),
    "minatory": (
        "Amenazador, de mal presagio.",
        "Con un aire inconfundible de amenaza: una mirada o una carta conminatoria deja muy claro que puede venir algo feo.",
        "El tono conminatorio de la carta puso nerviosa a la inquilina antes incluso de abrir el sobre.",
        "amenazar",
        "que sirve para",
    ),
    "obloquy": (
        "Fuerte crítica pública o abuso verbal.",
        "Una condena ruidosa y pública: la crítica abrasadora que se representa ante todos.",
        "La denunciante soportó años de descrédito público antes de que la historia le diera la razón.",
        "contra",
        "hablar",
    ),
    "paroxysm": (
        "Un estallido súbito y violento de emoción o de acción.",
        "Un empujón intenso que os cubre de golpe: un ataque de risa, de ira o de tos como una ola.",
        "La acometió un paroxismo de risa que no podía explicar a nadie más en la sala.",
        "más allá",
        "agudo, acerado",
    ),
    "adscititious": (
        "Añadido desde fuera, no inherente.",
        "Atornillado desde fuera en vez de ir de serie: un extra, no un núcleo.",
        "El comentario se siente añadido, como pegado a un texto ya terminado.",
        "hacia, además",
        "aprobar, asumir",
    ),
    "nescience": (
        "Falta de saber, ignorancia.",
        "El simple no-saber: un hueco en el conocimiento, sin juicio pegado encima.",
        "Admitió su desconocimiento del vino francés y dejó elegir al sumiller.",
        "no",
        "saber",
    ),
    "prurience": (
        "Interés excesivo por asuntos sexuales.",
        "Una curiosidad demasiado ansiosa, un tanto lúbrica, por todo lo picante: un interés que ha pasado lo sano y se ha vuelto cotilla.",
        "La lascivia del tabloide sobre la vida privada de la pareja rayaba en lo obsesivo.",
        "picar, anhelar",
        "estado de",
    ),
    "fuliginous": (
        "Holliniento, oscuro, turbio.",
        "Oscuro y ahumado, como si todo llevara una capa fina de hollín.",
        "Una bruma fuliginosa pendía al anochecer sobre el pueblo fabril.",
        "hollín",
        "lleno de",
    ),
    "gainsay": (
        "Negar o contradecir.",
        "Hablar en contra, de frente, de lo que otro ha dicho: decir que no es así.",
        "Nadie se atrevió a contradecir el relato del viejo capitán sobre la tormenta.",
        "contra",
        "hablar",
    ),
    "ignavia": (
        "Pereza, holgazanería (del latín).",
        "Una palabra latina antigua para la pereza pura: el lastre de no querer hacer nada.",
        "Los monjes predicaban contra la desidia como uno de los peligros callados del alma.",
        "no",
        "ocupado, diligente",
    ),
    "escutcheon": (
        "Un escudo que muestra un blasón.",
        "El emblema en forma de escudo con las armas de una familia: su insignia heráldica.",
        "El escudo de armas de la familia sigue colgado sobre la puerta del viejo señorío.",
        "escudo",
        "diminutivo / objeto",
    ),
    "superannuated": (
        "Anticuado, obsoleto, o jubilado por la edad.",
        "Pasado su buen tiempo y apartado: demasiado viejo de moda o gastado para seguir haciendo el trabajo.",
        "La impresora obsoleta fue por fin sustituida tras quince años de atascos.",
        "más allá",
        "año",
    ),
    "succedanea": (
        "Sustitutos, sobre todo en medicina.",
        "Remedios de recambio cuando falta el tratamiento de verdad: dobles médicos, en el fondo.",
        "Los médicos de guerra solían apoyarse en sucedáneos cuando se acababan las medicinas de verdad.",
        "en lugar de",
        "ir, ceder",
    ),
    "rodomontade": (
        "Charla jactanciosa y fanfarrona.",
        "Fanfarronería grande y ruidosa: un hablar alto de la propia grandeza que es, sobre todo, aire caliente.",
        "Su fanfarronada de haber salvado el proyecto «él solito» no engañó a nadie que hubiera estado allí de verdad.",
        "caballero fanfarrón en Orlando furioso",
        "acción, despliegue",
    ),
    "chicane": (
        "Usar astucia o engaño para lograr algo.",
        "Llegar al objetivo con trucos en vez de con juego limpio.",
        "Se coló en el trato con un contrato lleno de letra pequeña.",
        "tergiversar, engañar",
        "artimaña; luego un recodo cerrado",
    ),
    "mathesis": (
        "La ciencia pura o abstracta del aprender o del saber, a menudo las matemáticas.",
        "El aprender en su forma más pura y abstracta: la estructura honda del saber mismo, sobre todo la matemática.",
        "El filósofo soñaba con una mathesis universal que uniera todos los campos del saber.",
        "aprender",
        "el acto de aprender",
    ),
    "pedantic": (
        "Excesivamente ocupado con reglas formales o detalles triviales.",
        "Demasiado estricto con lo chico: corregir minucias técnicas que no cambian nada de fondo.",
        "Resultaba un poco pedante discutir «who» frente a «whom» en un mensaje de texto.",
        "guía de niños, preceptor",
        "que tiene el modo de",
    ),
    "coruscation": (
        "Un destello de luz chispeante.",
        "Un relámpago rápido y brillante: el sol en el agua, o un diamante que coge la luz.",
        "El centelleo de la lámpara de araña esparcía luz por cada rincón del salón de baile.",
        "brillar, destellar",
        "el acto de",
    ),
    "tyro": (
        "Un principiante, un novato.",
        "Alguien flamante en un oficio o un campo: aún aprendiendo las mañas, todavía no un experto.",
        "Hasta un jugador de ajedrez novato puede ver ese gazapo.",
        "recluta, novato",
        "un soldado joven y verde",
    ),
    "execrable": (
        "Extremadamente malo, detestable.",
        "Malo de un modo que merece asco de verdad: no solo mediocre, sino francamente atroz.",
        "El crítico llamó detestable a la secuela, y la taquilla le dio la razón.",
        "maldecir",
        "digno de, capaz de ser",
    ),
    "incarnadine": (
        "De color rojo sangre.",
        "Un rojo hondo y vivo: el color de la sangre fresca, famoso por el Macbeth de Shakespeare.",
        "El atardecer tiñó todo el cielo de un resplandor encarnado.",
        "dentro",
        "carne (rojo de carne)",
    ),
    "interstice": (
        "Un pequeño hueco o espacio entre cosas.",
        "El entremedio mínimo que se pasa por alto: la grieta entre las tablas, el hueco en una agenda.",
        "Las malas hierbas empujaban por cada intersticio del viejo camino de ladrillo.",
        "entre",
        "estar de pie",
    ),
    "animadversion": (
        "Observaciones críticas o censuradoras.",
        "Comentarios punzantes, de desaprobación: la crítica que suena un poco a regañina.",
        "Las reprensiones del profesor al ensayo llenaron los márgenes de tinta roja.",
        "mente",
        "volverse hacia",
    ),
    "irrefragable": (
        "Imposible de refutar, innegable.",
        "Tan sólidamente probado que no hay argumento en contra: el caso está cerrado.",
        "La prueba de ADN era irrefutable, y el juicio terminó en la hora.",
        "no",
        "oponerse, resistir",
    ),
    "involution": (
        "Complejidad, enredo; también un recogerse hacia dentro.",
        "Una complejidad enmarañada, plegada sobre sí: cosas tan apretadas que cuesta despegarlas.",
        "La complicación de la trama dejó a la mitad del público desenredándola tras los créditos.",
        "dentro, hacia adentro",
        "enrollar, volver",
    ),
    "dint": (
        "Fuerza o esfuerzo, como en «by dint of».",
        "Pura fuerza o empeño: sobrevive sobre todo en la locución «by dint of».",
        "Aprobó el examen a fuerza de práctica tozuda, pura y simple.",
        "un golpe, un envite",
        "a fuerza de",
    ),
    "mortised": (
        "Unido con ensamble de caja y espiga; encajado con firmeza.",
        "Trabado a la manera antigua del carpintero: una pieza entra justa en un hueco cortado para ella.",
        "Las vigas del viejo granero estaban ensambladas a caja y espiga, sin un solo clavo.",
        "una caja, un hueco",
        "una dentellada, un agarre",
    ),
    "apposite": (
        "Altamente pertinente, adecuado.",
        "Exactamente lo que pedía el momento: un comentario, una cita o un ejemplo que da en el blanco.",
        "Su observación atinada resumió todo el debate en una frase.",
        "hacia",
        "colocar",
    ),
    "lambent": (
        "De un resplandor suave o vacilante; también, un ingenio ligero.",
        "Un brillo manso en vez de un incendio: una llama que juega, o un ingenio juguetón más que cortante.",
        "La luz de las velas tendía un resplandor trémulo sobre el viejo comedor.",
        "lamer",
        "haciendo (luz que «lame»)",
    ),
    "anchorite": (
        "Un recluso religioso que vive en soledad.",
        "Alguien que se retira del mundo por completo para vivir solo en oración y reflexión.",
        "El anacoreta vivió más de treinta años en una celda pequeña adosada a la iglesia.",
        "atrás, lejos",
        "retirarse",
    ),
    "slake": (
        "Saciar la sed; apagar.",
        "Satisfacer del todo un anhelo: casi siempre la sed, pero en lo figurado cualquier necesidad honda.",
        "Un vaso de agua fría sació su sed tras la larga caminata.",
        "flojo, suelto",
        "aflojar, aliviar",
    ),
    "acicular": (
        "En forma de aguja.",
        "Largo, delgado y puntiagudo como una aguja: la forma de una aguja de pino o de un cristalito agudo.",
        "Los pinos se reconocen fácilmente por sus hojas aciculares.",
        "aguja",
        "pequeño",
    ),
    "effete": (
        "Agotado de vitalidad, débil, demasiado refinado.",
        "Gastado y blando: habiendo perdido el vigor primero a fuerza de confort o de refinamiento.",
        "Los críticos llamaron agotada a la revista antaño osada, sombra de sus años bravos.",
        "fuera",
        "fecundo, que ha dado fruto",
    ),
    "appurtenance": (
        "Un accesorio o un pequeño elemento o derecho anejo.",
        "Un extra pequeño unido a algo mayor: los accesorios y anexos que van con lo principal.",
        "El arrendamiento incluía el garaje y todos sus anexos.",
        "hacia",
        "pertenecer",
    ),
    "gloze": (
        "Pasar por alto o minimizar una falta.",
        "Alisar un error con palabras suaves, para que suene más pequeño de lo que es.",
        "Intentó encubrir el plazo perdido con un vago discurso de «dificultades imprevistas».",
        "una glosa, una explicación",
        "comentar — luego alisar",
    ),
    "incipient": (
        "En una fase temprana, que apenas empieza.",
        "Apenas empezando a mostrarse: el primer estadio, casi invisible, de algo más grande.",
        "Los médicos captaron los signos incipientes de la enfermedad antes de que se extendiera.",
        "sobre, hacia dentro",
        "tomar (emprender, empezar)",
    ),
    "afflatus": (
        "Inspiración creativa, sobre todo divina.",
        "Un empujón súbito de inspiración más grande que uno: como si la idea os hubiera sido soplada desde otra parte.",
        "El poeta contó que toda la pieza llegó en un arrebato de inspiración a las tres de la madrugada.",
        "hacia, sobre",
        "soplar (un soplo sobre)",
    ),
}
