# Italian overlays: (definition, friendly, exampleGloss, root1, root2)
WORDS = {
    "edulcorate": (
        "Addolcire o purificare; togliere a qualcosa la sua asprezza.",
        "Togliere il pungiglione o l’amarezza — addolcire sul serio, o ammorbidire in senso figurato un’idea dura perché scenda meglio.",
        "Il redattore edulcorated la recensione tagliente prima che andasse in stampa.",
        "fuori, a fondo",
        "dolce",
    ),
    "pietistic": (
        "Eccessivamente o affettatamente religioso o pio.",
        "Descrive qualcuno la cui devozione sa di spettacolo: più posa che fede vera.",
        "I suoi sospiri pietistic durante il sermone infastidirono il resto del banco.",
        "pietà, senso del dovere",
        "che ha il carattere di",
    ),
    "amphiboly": (
        "Ambiguità nata dalla struttura grammaticale — una frase leggibile in due modi.",
        "Una frase grammaticalmente in regola, ma che si può leggere in due modi del tutto diversi, come «Visiting relatives can be tiring».",
        "«Visiting relatives can be tiring» è una amphiboly classica — sono i parenti a stancare, o il fatto di visitarli?",
        "entrambi, da entrambi i lati",
        "gettare",
    ),
    "trenchant": (
        "Tagliente, incisivo, che va dritto al punto.",
        "Taglia di netto il superfluo — un commento o una mente trenchant arriva al nocciolo in fretta, senza una parola di troppo.",
        "La sua critica trenchant non lasciò nascondiglio ai buchi di trama del film.",
        "tagliare",
        "facendo, che ha la qualità di",
    ),
    "inchoative": (
        "Appena cominciato; in uno stadio precoce o rudimentale.",
        "Ancora nei primissimi istanti — un piano, un sentimento o un processo che sta appena prendendo forma.",
        "Le fasi inchoative del trattato erano promettenti, ma molti dettagli restavano aperti.",
        "cominciare, avviare",
        "che tende verso",
    ),
    "panegyric": (
        "Un discorso o uno scritto formale che loda qualcuno con splendore.",
        "Un omaggio in grande stile — pensate a un elogio funebre luminoso, o a un discorso che canta le gesta di qualcuno dai tetti.",
        "La professoressa in pensione fu accomiatata con un panegyric dei suoi studenti più vicini.",
        "tutto, intero",
        "assemblea, raduno",
    ),
    "ontic": (
        "Relativo all’esistenza reale, opposto alla teoria astratta.",
        "Delle cose come esistono davvero, non solo come idee o teorie su di esse.",
        "I filosofi discutono se i numeri abbiano uno status ontic qualsiasi o esistano solo nelle nostre teste.",
        "essere, ciò che esiste",
        "relativo a",
    ),
    "fructify": (
        "Portare frutto, o diventare produttivo.",
        "Finalmente dare frutto — uno sforzo, un’idea o un investimento che fructifies è passato dal seme a qualcosa di utile.",
        "Anni di ricerca silenziosa fructified infine in un vaccino che funziona.",
        "frutto",
        "fare, causare",
    ),
    "proleptical": (
        "Anticipare o rappresentare qualcosa come già fatto prima che accada.",
        "Anticipare in modo letterario — descrivere un fatto futuro come se fosse già chiuso, perché il colpo arrivi più a fondo.",
        "Il brindisi proleptical del generale a «victory» fu pronunciato una settimana intera prima della battaglia.",
        "prima",
        "prendere, afferrare",
    ),
    "pneumatic": (
        "Azionato dalla pressione dell’aria; anche relativo allo spirito o al respiro.",
        "Di solito: mosso dall’aria compressa — un trapano, un freno d’autobus — ma la stessa radice greca parla anche di respiro e di spirito.",
        "I freni pneumatic sibilarono quando l’autobus si fermò al marciapiede.",
        "vento, respiro, spirito",
        "pertinente a",
    ),
    "cataphatic": (
        "Descrivere Dio o il divino con affermazioni positive — il contrario di apofatico.",
        "Parlare di Dio dicendo ciò che è — «Dio è amore», «Dio è giusto» — invece di solo ciò che non è.",
        "La teologia cataphatic parla con fiducia di Dio come amorevole, giusto e misericordioso.",
        "giù, secondo",
        "parlare, dire",
    ),
    "fiducial": (
        "Fondato sulla fiducia o sulla fede; anche: un punto di riferimento fisso.",
        "Qualcosa che si prende in fiducia e poi si usa come ancora — un segno fiducial è il punto fisso rispetto al quale si misura tutto il resto.",
        "I geometri posero un marcatore fiducial nella roccia prima di mappare il sito.",
        "fidarsi",
        "fiducia, sicurezza",
    ),
    "theodicy": (
        "Una difesa della bontà di Dio di fronte all’esistenza del male.",
        "Il tentativo antico di rispondere: se Dio è buono, perché c’è il male? — senza rinunciare a nessuna delle due affermazioni.",
        "La sua tesi esplorava theodicy attraverso la lente del Libro di Giobbe.",
        "dio",
        "giustizia",
    ),
    "circumincession": (
        "Inabitazione reciproca — termine teologico per come le persone della Trinità esistono l’una nell’altra.",
        "Una parola di teologia per un insieme tre-in-uno così completo che ogni parte contiene le altre ed è da esse contenuta.",
        "La dottrina di circumincession cerca di spiegare come Padre, Figlio e Spirito siano distinti eppure inseparabili.",
        "intorno",
        "andare, camminare",
    ),
    "redound": (
        "Avere una conseguenza che giova a qualcuno o ricade su di lui.",
        "Quando il merito (o la colpa) rimbalza su chi è responsabile — le buone azioni che redound al tuo nome tornano poi come premio.",
        "Il successo della squadra redound al credito del suo allenatore silenzioso e laborioso.",
        "indietro, di nuovo",
        "onda",
    ),
    "ineluctable": (
        "Che non si può evitare né da cui si può fuggire.",
        "Succederà comunque — da un esito ineluctable non ti sfili.",
        "La vecchiaia arriva per tutti; è semplicemente ineluctable.",
        "non",
        "dibattere per uscire",
    ),
    "periphrastic": (
        "Che usa un giro di parole verboso invece di una forma diretta.",
        "Prendere la strada lunga con le parole — dire in una frase intera ciò che coprirebbe una sola parola.",
        "Le sue e-mail periphrastic avrebbero potuto dire in una riga ciò che gli occupava tre paragrafi.",
        "intorno",
        "dichiarare, raccontare",
    ),
    "hebetude": (
        "Ottusità mentale o letargia.",
        "Quello stato d’animo nebbioso e lento in cui pensare è come avanzare nello sciroppo.",
        "Un’ondata di hebetude colpì la classe subito dopo pranzo.",
        "ottuso, spuntato",
        "stato o qualità",
    ),
    "unpropitious": (
        "Poco favorevole; di cattivo auspicio.",
        "Un brutto segno — condizioni o un momento che sembrano già lavorare contro di te prima ancora di cominciare.",
        "Cielo grigio e batteria dell’auto scarica fecero un inizio unpropitious per il viaggio.",
        "non",
        "favorevole, grazioso",
    ),
    "fricaseed": (
        "Carne stufata o brasata in salsa — correttamente scritto «fricasseed».",
        "Un vecchio termine di cucina accogliente per carne tagliata e cotta lentamente nella propria salsa fino a diventare tenera.",
        "Il pollo fricasseed della nonna era il clou di ogni pranzo della domenica.",
        "friggere",
        "rompere (a pezzi)",
    ),
    "ersatz": (
        "Un sostituto artificiale o di qualità inferiore.",
        "Un’imitazione che sta al posto del vero — fa il suo mestiere, ma tutti vedono che non è l’originale.",
        "In tempo di guerra, i clienti si accontentavano di caffè ersatz di cicoria tostata.",
        "fuori, prefisso di sostituzione",
        "porre, collocare",
    ),
    "reify": (
        "Trattare un’idea astratta come se fosse una cosa concreta.",
        "Far sentire un’idea reale e solida — trasformare qualcosa di vago, come «il mercato», in un oggetto a cui si può puntare il dito.",
        "Chiamare «spirito» di una nazione un essere a sé reifies qualcosa che in realtà è solo milioni di scelte isolate.",
        "cosa",
        "fare",
    ),
    "eluded": (
        "Sfuggito o evitato con abilità.",
        "Sgusciare via puliti — schivare qualcosa, spesso con astuzia o per un pelo, che sia una cattura, una domanda o una risposta.",
        "La risposta eluded per ore finché, d’improvviso, scattò sotto la doccia.",
        "fuori, via",
        "giocare",
    ),
    "aporetic": (
        "Che esprime dubbio, perplessità o una contraddizione irrisolta.",
        "Bloccati in un vero vicolo cieco del pensiero — non per pigrizia, ma perché la domanda stessa rifiuta una risposta netta.",
        "Socrate chiudeva spesso i dialoghi su una nota aporetic, con più domande che risposte.",
        "senza",
        "passaggio, via",
    ),
    "metonymy": (
        "Figura che nomina qualcosa con un termine associato, p. es. «la corona» per il sovrano.",
        "Usare una parola affine al posto della cosa stessa — dire «Wall Street» quando si intende la borsa.",
        "«Wall Street had a rough day» è metonymy — in realtà significa che la borsa l’ha passata male.",
        "cambiamento, dopo",
        "nome",
    ),
    "deracinate": (
        "Sradicare; strappare da un ambiente naturale.",
        "Strappare qualcosa (o qualcuno) con le radici, lontano dal luogo o dalla cultura a cui appartiene.",
        "La guerra deracinated un’intera generazione, disperdendo famiglie oltre i confini.",
        "via, fuori",
        "radice",
    ),
    "euphonious": (
        "Di suono gradevole.",
        "Semplicemente bello da sentire — una parola o una frase euphonious scivola, quasi in musica, nell’orecchio.",
        "«Murmuring brook» è una frasetta euphonious, morbida e facile da dire.",
        "buono, bene",
        "suono, voce",
    ),
    "putative": (
        "Generalmente supposto o ritenuto tale.",
        "Ritenuto vero da molti, anche se non è dimostrato — la versione presunta o supposta di qualcosa.",
        "L’autore putative della lettera si rivelò poi un perfetto sconosciuto.",
        "pensare, considerare",
        "che ha la natura di",
    ),
    "neologism": (
        "Una parola o locuzione di nuovo conio.",
        "Una parola nuovissima — appena inventata, ancora (quasi) fuori dal dizionario.",
        "«Doomscrolling» è nato come neologism e in fretta è diventato gergo quotidiano.",
        "nuovo",
        "parola, discorso",
    ),
    "splenetic": (
        "Arrabbiato o di cattivo umore.",
        "Di umore agro e irritabile, pronto a scattare — come un tempo si credeva che la milza governasse il temperamento.",
        "Sparò una risposta splenetic all’e-mail pochi secondi dopo averla letta.",
        "milza (sede dell’ira)",
        "affetto da",
    ),
    "sententious": (
        "Propenso a moraleggiare in modo pomposo o affettato.",
        "Ama spifferare lezioncine di vita, come se ogni frase fosse un biscotto della fortuna.",
        "Il suo brindisi sententious su «the true meaning of friendship» fece guardare l’orologio a tutti.",
        "opinione, massima",
        "pieno di",
    ),
    "garrulous": (
        "Eccessivamente loquace, soprattutto su inezie.",
        "Non smette di chiacchierare — divaga su quisquilie molto dopo che gli altri non hanno più niente da dire.",
        "Il tassista garrulous ci raccontò tutta la sua vita prima che lasciassimo l’aeroporto.",
        "chiacchierare, cianciare",
        "incline a",
    ),
    "fatuity": (
        "Stoltezza, sciocchezza.",
        "La stoltezza semplice — un commento o un piano così sciocco da meritare a malapena una risposta seria.",
        "La pura fatuity del piano apparve nel momento in cui lo provarono.",
        "stolto, sciocco",
        "stato di essere",
    ),
    "peroration": (
        "La parte conclusiva di un discorso, spesso riassuntiva.",
        "Il gran finale di un discorso — il tratto in cui l’oratore raccoglie tutto e pianta il chiodo.",
        "Alla peroration, metà del pubblico era in piedi.",
        "attraverso, fino in fondo",
        "parlare, perorare",
    ),
    "tautology": (
        "Ripetizione inutile della stessa idea con altre parole.",
        "Dire due volte la stessa cosa senza aggiungere nulla, come «regalo gratis» o «it is what it is».",
        "«It is what it is» è una tautology preferita di chi evita una spiegazione vera.",
        "lo stesso",
        "parola, discorso",
    ),
    "laconism": (
        "L’uso di pochissime parole; un parlare laconico.",
        "Dire molto con pochissimo — l’arte della replica corta e secca, così chiamata dagli Spartani della Laconia, famosi per la brevità.",
        "«Molon labe» — «come and take them» — è il pezzo di laconism più famoso della storia.",
        "uno spartano della Laconia",
        "pratica, maniera",
    ),
    "pabulum": (
        "Idee insipide e troppo semplificate; in origine, cibo scialbo o pappa.",
        "Pensiero annacquato — un contenuto così semplificato e sicuro da non nutrire la mente.",
        "Il discorso del politico era soprattutto pabulum: promesse vaghe a cui non si poteva aggrappare nulla.",
        "nutrire",
        "mezzo o strumento",
    ),
    "soporific": (
        "Che provoca sonno o sonnolenza.",
        "Così noioso — o così letteralmente sedativo — da far venire sonno. Pensate al latte caldo, o a una riunione di bilancio di tre ore.",
        "Il ronzio soporific della lezione teneva metà della sala a lottare per tenere gli occhi aperti.",
        "sonno profondo",
        "che fa, che causa",
    ),
    "unctuous": (
        "Eccessivamente lusinghiero o oleoso nei modi.",
        "Così liscio di fascino da scivolare — una lusinga così spessa che quasi se ne sente il grasso.",
        "Il venditore unctuous non smetteva di lodare il mio «excellent taste» prima di ogni vendita extra.",
        "ungere, oliare",
        "pieno di",
    ),
    "captious": (
        "Pronto a trovare difetti, troppo critico sulle inezie.",
        "Pignolo all’eccesso — il tipo che trova un problema in tutto, anche quando non conta.",
        "Le sue note captious al rapporto erano tutte sulla punteggiatura delle virgole.",
        "afferrare, prendere",
        "una trappola, un sofisma",
    ),
    "torpid": (
        "Lento, inattivo di mente o di corpo.",
        "Lento e mezzo addormentato, come un orso in letargo — quasi non si muove, quasi non pensa.",
        "L’ufficio cadde torpid nel caldo pesante di agosto.",
        "essere intorpidito, essere pigro",
        "in uno stato di",
    ),
    "seneschal": (
        "Un maggiordomo o ufficiale che gestiva una casa medievale.",
        "La versione medievale di un capo del personale — l’ufficiale di fiducia che teneva giorno per giorno la casa e la tenuta di un signore.",
        "Il seneschal del castello gestiva tutto, dai conti del raccolto alla lista degli ospiti.",
        "vecchio, anziano",
        "servo",
    ),
    "expatiate": (
        "Parlare o scrivere a lungo su un argomento.",
        "Mettersi davvero in moto su un tema — parlarne o scriverne senza fine, da ogni angolo.",
        "Chiedigli delle auto d’epoca e lui va a expatiate per un’ora intera.",
        "fuori",
        "spazio",
    ),
    "nugatory": (
        "Senza valore, futile; anche invalido o inefficace.",
        "Che non vale quasi niente — una clausola nugatory in un contratto, in pratica, non fa nulla.",
        "Il tribunale dichiarò nugatory il vecchio regolamento, poiché non era mai stato applicato.",
        "inezie, sciocchezze",
        "appartenente a",
    ),
    "sagacity": (
        "Saggezza, giudizio perspicace.",
        "Una saggezza viva e pratica — il buon giudizio che viene dall’esperienza, non solo dai libri.",
        "La sagacity del vecchio capitano tenne l’equipaggio fuori dai guai più di una volta.",
        "di olfatto fine, perspicace",
        "qualità di",
    ),
    "canaille": (
        "La canaglia o la massa, usato con disprezzo.",
        "Una parola snob e sprezzante per la gente comune, come se fosse un branco di cani.",
        "Il conte sogghignò alla canaille raccolta fuori dai cancelli del palazzo.",
        "cane",
        "collettivo, branco",
    ),
    "contumely": (
        "Trattamento o linguaggio insolente e umiliante.",
        "Un trattamento crudele e sprezzante fatto per umiliare — l’insulto pensato per bruciare.",
        "Sopportò anni di contumely dei critici prima che il suo lavoro fosse finalmente riconosciuto.",
        "con, a fondo",
        "gonfiarsi (d’orgoglio)",
    ),
    "askance": (
        "Con sospetto o disapprovazione; uno sguardo di traverso.",
        "Lo sguardo di sbieco che si dà a ciò di cui non ci si fida del tutto — uno sguardo carico di dubbio.",
        "L’insegnante guardò askance i compiti sospettosamente in ordine.",
        "verso, a",
        "obliquità, pregiudizio",
    ),
    "clodpate": (
        "Uno zuccone; una testa di legno.",
        "Un insulto un po’ antico, quasi affettuoso, per qualcuno tardo o denso — una testa di legno.",
        "«You clodpate», rise lei, «you've had the map upside down the whole time.»",
        "zolla di terra",
        "testa",
    ),
    "actuate": (
        "Mettere in moto o in azione; motivare.",
        "Essere la scintilla che mette qualcosa in cammino — una macchina che si accende o una persona che infine agisce su un’idea.",
        "La paura di perdere il contratto actuated tutta la squadra in un weekend di straordinari.",
        "un fare, un spingere",
        "spingere, fare",
    ),
    "peculation": (
        "Peculato di fondi affidati alla propria custodia.",
        "Rubare in silenzio il denaro che si doveva custodire — il peculato, vestito all’antica.",
        "La peculation del tesoriere passò inosservata per quasi un decennio.",
        "proprietà privata",
        "bestiame, ricchezza",
    ),
    "demi-monde": (
        "Un gruppo ritenuto ai margini della società rispettabile.",
        "Il demi-monde glamouroso e losco — gente che vive appena fuori dalle regole del decoro.",
        "Il romanzo segue una cantante nella demi-monde dei cabaret degli anni Venti.",
        "mezzo",
        "mondo, società",
    ),
    "extant": (
        "Ancora esistente; non estinto né distrutto.",
        "Ancora qui oggi — si dice di cose vecchie (manoscritti, specie, edifici) che sono riuscite a sopravvivere.",
        "Si conoscono solo tre copie extant della prima stampa.",
        "fuori",
        "stare in piedi",
    ),
    "perfidy": (
        "Inganno; tradimento della fiducia.",
        "Un tradimento profondo e deliberato — spezzare una fiducia che qualcuno aveva il diritto di aspettarsi da te.",
        "Il generale non perdonò mai la perfidy del vecchio amico al tavolo delle trattative.",
        "attraverso, contro",
        "fede, fiducia",
    ),
    "patois": (
        "Un dialetto regionale, soprattutto non standard.",
        "Il modo proprio, locale, di parlare in una zona — pieno di parole e ritmi che un estraneo non coglie.",
        "Sua nonna parlava ancora il patois dell’isola alle cene di famiglia.",
        "parlare rozzo, dialetto",
        "zampa — parlare goffo",
    ),
    "prerogative": (
        "Un diritto speciale di una persona o di un gruppo.",
        "Un privilegio che è solo tuo — un diritto che arriva con il ruolo, la posizione o lo status.",
        "Scegliere la meta delle vacanze di famiglia è la prerogative di Grandpa, e lo sanno tutti.",
        "prima",
        "chiedere, votare",
    ),
    "hardihood": (
        "Arditezza, audacia; anche resistenza o sopportazione.",
        "Una resilienza ruvida e coraggiosa — il fegato di andare avanti e la tenacia di tenere una volta in cammino.",
        "Ci volle una hardihood vera per attraversare il passo in una tormenta, senza mappa.",
        "ardito, resistente",
        "stato, condizione",
    ),
    "effloresce": (
        "Schiudersi in fiore; anche svilupparsi o apparire a poco a poco.",
        "Aprirsi fino a esprimersi del tutto — come un fiore che si schiude, o un’idea che trova finalmente la sua forma.",
        "Il suo talento silenzioso per la pittura effloresced non appena ebbe uno studio tutto suo.",
        "fuori",
        "cominciare a fiorire",
    ),
    "plumb-line": (
        "Un filo a piombo per giudicare la verticale; in senso figurato, un criterio.",
        "Un peso su un filo che cade a piombo, per vedere se qualcosa è davvero verticale — e, per estensione, qualsiasi misura fissa contro cui si confronta il resto.",
        "Usava l’onestà del nonno come una sorta di plumb line per ogni decisione.",
        "piombo",
        "corda, misura",
    ),
    "fain": (
        "Volentieri, di buon grado (arcaico).",
        "Un modo un po’ antico di dire «volentieri» o «di buon grado» — you would fain fare qualcosa se ti fa piacere.",
        "«I would fain rest here a while», sospirò il viaggiatore.",
        "lieto, gioioso",
        "volentieri, di buon grado",
    ),
    "opprobrium": (
        "Critica pubblica aspra, o disonore.",
        "La vergogna pubblica versata su qualcuno in grande — il disonore di una disapprovazione generale.",
        "Lo scandalo portò opprobrium pubblico su tutta la ditta.",
        "contro",
        "disonore, rimprovero",
    ),
    "mordant": (
        "Vivamente sarcastico, mordace nell’ingegno o nella critica.",
        "Ingegno con denti veri — un commento mordant punge proprio perché mira così bene.",
        "Le sue recensioni cinematografiche mordant erano temute dai registi e amate dai lettori.",
        "mordere",
        "mordace, facendo",
    ),
    "pronunciamento": (
        "Una proclamazione formale, spesso politica o militare.",
        "Un grande annuncio ufficiale — di solito quello che dichiara un nuovo governo, una rivolta o un decreto maggiore.",
        "Il pronunciamento del generale annunciò il nuovo governo all’alba.",
        "avanti",
        "annunciare",
    ),
    "sciolist": (
        "Una persona di sapere superficiale che si finge esperto.",
        "Qualcuno che ha sfiorato la superficie di un argomento e poi parla come se ne avesse scritto il manuale.",
        "Lo sciolist della cena corresse con disinvoltura il vero astrofisico a tavola.",
        "sapere",
        "diminutivo — un piccolo sapiente",
    ),
    "dotage": (
        "Il declino delle facoltà mentali nella vecchiaia.",
        "Il tratto nebbioso e smemorato della tarda vecchiaia, quando la lucidezza della mente comincia a svanire.",
        "Nella sua dotage, raccontava le stesse tre storie a ogni visita, ogni volta come se fossero nuove.",
        "vaneggiare, essere stolto",
        "stato o risultato",
    ),
    "lee-side": (
        "Il lato riparato dal vento.",
        "Il lato calmo e riparato di qualcosa — una collina, una nave, un muro — dove il vento non ti raggiunge più del tutto.",
        "Gli escursionisti piantarono la tenda sul lee side della cresta per sfuggire alle raffiche.",
        "riparo, protezione",
        "fianco, faccia",
    ),
    "parry": (
        "Deviare o respingere un colpo, una domanda o un argomento.",
        "Scostare con disinvoltura — un fendente, una domanda scomoda, un’accusa — senza perdere un attimo.",
        "Lei parried la domanda subdola del reporter con una battuta facile.",
        "respingere",
        "preparare, difendere",
    ),
    "mephitic": (
        "Di odore nauseabondo, nocivo.",
        "Puzzolente in un modo quasi tossico — un tanfo così brutto che sembra pericoloso respirare.",
        "Un odore mephitic salì dalla palude al calar del sole.",
        "vapore nocivo",
        "che ha la natura di",
    ),
    "sybarite": (
        "Una persona votata al lusso e al piacere.",
        "Qualcuno che vive per il comfort e l’indulgenza — buona tavola, letti morbidi, vita facile — così chiamato dalla città greca di Sibari, famosa per l’eccesso.",
        "Un vero sybarite, rifiutava qualsiasi camera d’albergo senza vasca.",
        "antica città greca famosa per il lusso",
        "abitante di",
    ),
    "prescind": (
        "Mettere da parte o ignorare di proposito una parte di qualcosa.",
        "Accantonare di proposito, nella mente, un pezzo del puzzle per guardare pulito il resto.",
        "Prescind un attimo dal costo e chiediamoci solo se il piano funziona davvero.",
        "prima, via",
        "tagliare",
    ),
    "excoriate": (
        "Criticare aspramente; anche, scorticare.",
        "Scorticare qualcuno a colpi di critica — come se gli si strappasse davvero la pelle.",
        "I critici excoriated il sequel per aver tradito tutto ciò che i fan amavano dell’originale.",
        "via",
        "pelle, cuoio",
    ),
    "adduce": (
        "Citare come prova o come evidenza.",
        "Portare un fatto o un esempio a sostegno del punto — ciò a cui si punta quando qualcuno chiede le prove.",
        "L’avvocata adduced tre testimoni a sostegno dell’alibi della cliente.",
        "verso",
        "condurre",
    ),
    "peregrinations": (
        "Viaggi o peregrinazioni, soprattutto lunghi o estesi.",
        "Lunghi peripli erranti — quel genere di girovagare che ti tiene lontano da casa per un bel po’.",
        "Le sue peregrinations attraverso tre continenti riempirono un intero scaffale di diari di viaggio.",
        "attraverso",
        "campo, terra (peregrinus: straniero)",
    ),
    "mendicant": (
        "Un mendicante, o chi vive di elemosine.",
        "Qualcuno che vive chiedendo carità — storicamente, anche frati che fecero voto di povertà e vivevano di doni.",
        "I frati mendicant non possedevano nulla e dipendevano interamente dalla bontà dei paesani.",
        "mendicare",
        "mendicante",
    ),
    "munificent": (
        "Estremamente generoso.",
        "Generoso su una scala quasi teatrale — il dono che strappa un piccolo «ah».",
        "La donazione munificent finanziò l’intera nuova ala della biblioteca.",
        "dono, servizio",
        "facendo, dando",
    ),
    "inanition": (
        "Esaurimento per mancanza di nutrimento; anche mancanza di vitalità.",
        "Uno stato debole, svuotato, per non essere nutrito — in senso letterale per fame, o in senso figurato perché non resta carburante.",
        "Alla fine dell’assedio, i soldati erano vicini all’inanition.",
        "vuoto, vano",
        "l’atto o il risultato di",
    ),
    "vituperation": (
        "Critica amara e ingiuriosa.",
        "Una critica che ha lasciato da tempo il giusto e si è fatta una tirata furiosa e amara.",
        "I commenti online si sciolsero in pura vituperation in pochi minuti.",
        "colpa, difetto",
        "preparare, fornire",
    ),
    "inimical": (
        "Ostile, dannoso negli effetti.",
        "Che lavora contro di te, anche in silenzio — condizioni o atteggiamenti poco amici dei tuoi interessi.",
        "La nuova politica era inimical per le piccole imprese, anche se quella non era l’intenzione.",
        "non",
        "amico",
    ),
    "invidious": (
        "Propenso a suscitare rancore, spesso per confronti ingiusti.",
        "Sicuro che qualcuno si senta sminuito — quasi sempre perché si mettono persone o cose in concorrenza iniqua.",
        "Classificare i fratelli secondo «who Mom loves best» è un gioco invidious che nessuno dovrebbe giocare.",
        "invidia",
        "guardare (con malanimo)",
    ),
    "subaltern": (
        "Una persona di rango o status inferiore; un subordinato.",
        "Qualcuno più in basso nella catena di comando o nella scala sociale — un junior, sotto qualcuno con più potere.",
        "Da giovane subaltern, ricevette ordini a lungo prima di darne.",
        "sotto",
        "alternativo, altro",
    ),
    "execrate": (
        "Provare o esprimere un odio intenso.",
        "Detestare qualcosa tanto da maledirlo ad alta voce — una detestazione pura e sonora.",
        "I paesani execrated l’esattore ogni volta che il suo carro attraversava il paese.",
        "fuori da",
        "sacro (maledire fuori dal sacro)",
    ),
    "integument": (
        "Un rivestimento naturale esterno, come la pelle o un guscio.",
        "L’involucro protettivo della natura — pelle, guscio, buccia o corteccia, ciò che copre e protegge un essere vivo.",
        "Il guscio di una tartaruga è un integument notevolmente tenace.",
        "su, sopra",
        "coprire",
    ),
    "ingenuous": (
        "Innocente, ingenuo, di semplicità infantile; il contrario di subdolo.",
        "Apertamente fiducioso e un po’ ingenuo, senza secondi fini — facile da confondere con «ingenious», che significa ingegnoso.",
        "La sua domanda ingenuous — «why would anyone lie about that?» — mostrava quanta poca astuzia avesse.",
        "in, nativo",
        "generare (di nascita libera, candido)",
    ),
    "pedantry": (
        "Preoccupazione eccessiva per dettagli minori o regole.",
        "Perdersi nelle regole piccole e mancare il quadro grande — ossessionarsi della lettera piccola di cui a nessun altro importa.",
        "La sua pedantry sulle virgole di Oxford fece deragliare tutta la riunione.",
        "precettore di bambini",
        "pratica o qualità",
    ),
    "perscrutation": (
        "Un esame minuzioso e accurato.",
        "Uno sguardo profondo, che non lascia pietra non girata — passare ogni dettaglio con vera cura.",
        "Solo dopo una perscrutation attenta dei libri spuntò la discrepanza.",
        "attraverso, a fondo",
        "cercare, esaminare",
    ),
    "demur": (
        "Sollevare obiezioni; mostrare riluttanza.",
        "Tirarsi indietro con cortesia o esitare invece di seguire subito — un dolce «un momento».",
        "Quando le chiesero di firmare senza leggere, lei demurred.",
        "da, via",
        "indugiare",
    ),
    "specious": (
        "Plausibile in apparenza, ma in realtà falso.",
        "Sembra convincente a prima vista, ma crolla non appena si verifica sul serio.",
        "«Everyone's doing it» è un argomento specious che non regge mai del tutto al controllo.",
        "apparenza, aspetto",
        "pieno di (di bel parere)",
    ),
    "cant": (
        "Discorso insincero e ipocrita, spesso moraleggiante.",
        "Un parlare da pulpito che suona virtuoso senza sentimento vero — posa morale in pilota automatico.",
        "Era stanco del cant aziendale sulla «family» di un’azienda che non dava mai un giorno di ferie.",
        "cantare (poi: gergo cantilenante)",
        "parlare lamentoso dei mendicanti, poi ipocrisia",
    ),
    "pusillanimous": (
        "Privo di coraggio, codardo.",
        "Timido fino a non avere colonna — troppo spaventato per alzarsi, anche quando conta chiaramente.",
        "Il silenzio pusillanimous del consiglio lasciò lo scandalo sfuggire di mano.",
        "molto piccolo",
        "spirito, coraggio",
    ),
    "vulpine": (
        "Di volpe; astuto, furbesco.",
        "Furbo e sveglio come una volpe — vivo di mente, un po’ subdolo, sempre un passo avanti.",
        "Fece un sorriso vulpine nel momento in cui vide la scappatoia.",
        "volpe",
        "di o come",
    ),
    "seriatim": (
        "Uno dopo l’altro, in sequenza.",
        "Preso strettamente uno alla volta, in ordine — senza saltare, senza farne due insieme.",
        "Il giudice affrontò ciascuna delle dodici pretese seriatim.",
        "fila, sequenza",
        "uno alla volta",
    ),
    "parsimony": (
        "Frugalità estrema; spilorceria.",
        "Andare stretti di soldi (o di parole, o di risorse) ben oltre un risparmio ragionevole.",
        "La sua parsimony era leggendaria — riusava le bustine di tè tre volte.",
        "risparmiare, essere frugale",
        "stato o pratica",
    ),
    "emendation": (
        "Una correzione, soprattutto in un testo.",
        "Un ritocco in uno scritto — un intervento erudito che ripara un errore in un testo vecchio o importante.",
        "La nuova edizione include decine di emendations al manoscritto originale.",
        "fuori da",
        "colpa, errore",
    ),
    "abstemious": (
        "Moderato nel mangiare e nel bere.",
        "Di proposito contenuto a tavola — mai troppo, sempre un po’ lasciato nel piatto.",
        "Le sue abitudini abstemious lo tennero lucido molto dopo che i coetanei avevano rallentato.",
        "lontano da",
        "bevanda inebriante",
    ),
    "solecism": (
        "Un errore grammaticale o una mancanza di etichetta.",
        "Uno scivolone di grammatica o di maniere — il piccolo errore che fa accigliare un pignolo.",
        "«Between you and I» è un solecism comune che fa ancora rabbrividire i grammatici.",
        "città cilicia nota per il greco «cattivo»",
        "pratica, maniera",
    ),
    "internecine": (
        "Relativo a un conflitto interno a un gruppo; reciprocamente distruttivo.",
        "Liti interne che squarciano un gruppo da dentro — una lotta in cui tutti perdono, perché è famiglia contro famiglia.",
        "Le beghe internecine del partito fecero più danni di qualsiasi avversario esterno.",
        "tra, fra",
        "uccidere",
    ),
    "pococurante": (
        "Atteggiamento indifferente, negligente.",
        "Un’alzata di spalle diventata personalità — importare così poco di ciò che un tempo contava che niente sembra più valere lo sforzo.",
        "Il suo atteggiamento pococurante verso la cerimonia dei premi sorprese chi sapeva quanto avesse lavorato.",
        "poco",
        "curarsi di",
    ),
    "imbroglio": (
        "Una situazione o una disputa confusa e intricata.",
        "Un groviglio disordinato, difficile da sbrogliare — parte malinteso, parte dramma, tutta confusione.",
        "Tutto l’imbroglio della pianta dei tavoli cominciò con un cartoncino nome messo male.",
        "in",
        "ingarbugliare, confondere",
    ),
    "minatory": (
        "Minaccioso, di cattivo presagio.",
        "Con un’aria inconfondibile di minaccia — uno sguardo o una lettera minatory rende chiarissimo che può seguire qualcosa di brutto.",
        "Il tono minatory della lettera mise nervoso l’inquilina prima ancora che aprisse la busta.",
        "minacciare",
        "che serve a",
    ),
    "obloquy": (
        "Forte critica pubblica o abuso verbale.",
        "Una condanna rumorosa e pubblica — la critica feroce che si recita davanti a tutti.",
        "La denunciante sopportò anni di obloquy pubblica prima che la storia le desse ragione.",
        "contro",
        "parlare",
    ),
    "paroxysm": (
        "Un accesso improvviso e violento di emozione o di azione.",
        "Una spinta intensa che ti sommerge d’un colpo — un attacco di riso, di rabbia o di tosse come un’onda.",
        "Fu colta da un paroxysm di riso che non poteva spiegare a nessun altro nella stanza.",
        "oltre",
        "acuto, acerbo",
    ),
    "adscititious": (
        "Aggiunto dall’esterno, non inerente.",
        "Avvitato da fuori invece che incorporato dall’inizio — un extra, non un nucleo.",
        "Il commento sembra adscititious, come attaccato a un testo già finito.",
        "verso, in più",
        "approvare, assumere",
    ),
    "nescience": (
        "Mancanza di sapere, ignoranza.",
        "Il semplice non-sapere — un buco nella conoscenza, senza giudizio appiccicato sopra.",
        "Ammise la sua nescience del vino francese e lasciò scegliere al sommelier.",
        "non",
        "sapere",
    ),
    "prurience": (
        "Interesse eccessivo per questioni sessuali.",
        "Una curiosità troppo ansiosa, un po’ lubrica, per tutto ciò che è spinto — un interesse passato il sano e diventato ficcanaso.",
        "La prurience del tabloid sulla vita privata della coppia rasentava l’ossessione.",
        "prudere, anelare",
        "stato di",
    ),
    "fuliginous": (
        "Fuligginoso, scuro, torbido.",
        "Scuro e fumoso, come se tutto portasse un sottile strato di fuliggine.",
        "Una foschia fuliginous pendeva al crepuscolo sulla città di fabbriche.",
        "fuliggine",
        "pieno di",
    ),
    "gainsay": (
        "Negare o contraddire.",
        "Parlare contro, di fronte, ciò che un altro ha detto — dire che non è così.",
        "Nessuno osò gainsay il racconto del vecchio capitano sulla tempesta.",
        "contro",
        "parlare",
    ),
    "ignavia": (
        "Pigrizia, ozio (dal latino).",
        "Una vecchia parola latina per la pigrizia pura — il peso di non voler fare niente.",
        "I monaci predicavano contro ignavia come uno dei pericoli silenziosi dell’anima.",
        "non",
        "occupato, diligente",
    ),
    "escutcheon": (
        "Uno scudo che mostra uno stemma.",
        "L’emblema a forma di scudo con le armi di una famiglia — il suo distintivo araldico.",
        "L’escutcheon della famiglia pende ancora sopra la porta del vecchio maniero.",
        "scudo",
        "diminutivo / oggetto",
    ),
    "superannuated": (
        "Antiquato, obsoleto, o ritirato per età.",
        "Passato il suo utile primavera e messo da parte — troppo fuori moda o consumato per fare ancora il lavoro.",
        "La stampante superannuated fu infine sostituita dopo quindici anni di inceppi.",
        "oltre",
        "anno",
    ),
    "succedanea": (
        "Sostituti, soprattutto in medicina.",
        "Rimedi di ripiego quando manca la cura vera — doppi medici, in fondo.",
        "I medici di guerra si appoggiavano spesso a succedanea quando finivano le medicine vere.",
        "al posto di",
        "andare, cedere",
    ),
    "rodomontade": (
        "Discorso vanaglorioso e spaccone.",
        "Spavalderia grande e rumorosa — un parlare alto della propria grandezza che è, soprattutto, aria calda.",
        "La sua rodomontade di aver salvato il progetto «single-handedly» non ingannò nessuno di chi c’era stato davvero.",
        "cavaliere spaccone in Orlando Furioso",
        "azione, ostentazione",
    ),
    "chicane": (
        "Usare astuzia o inganno per ottenere qualcosa.",
        "Arrivare allo scopo con trucchi invece che con gioco leale.",
        "Chicaned l’ingresso nell’affare con un contratto pieno di caratteri piccoli.",
        "cavillare, ingannare",
        "inganno; poi una curva stretta",
    ),
    "mathesis": (
        "La scienza pura o astratta dell’apprendere o del sapere, spesso la matematica.",
        "L’apprendere nella forma più pura e astratta — la struttura profonda del sapere stesso, soprattutto quella matematica.",
        "Il filosofo sognava una mathesis universale che unisse ogni campo del sapere.",
        "apprendere",
        "l’atto di apprendere",
    ),
    "pedantic": (
        "Eccessivamente occupato di regole formali o dettagli triviali.",
        "Troppo stretto sulle piccolezze — correggere minuzie tecniche che non cambiano nulla di sostanziale.",
        "Sembrava un po’ pedantic discutere «who» contro «whom» in un messaggio.",
        "guida di bambini, precettore",
        "che ha il modo di",
    ),
    "coruscation": (
        "Un lampo di luce scintillante.",
        "Un lampo rapido e brillante — il sole sull’acqua, o un diamante che prende la luce.",
        "La coruscation del lampadario spargeva luce in ogni angolo della sala da ballo.",
        "scintillare, lampeggiare",
        "l’atto di",
    ),
    "tyro": (
        "Un principiante, un novizio.",
        "Qualcuno nuovissimo in un’arte o in un campo — ancora a imparare i trucchi, non ancora un esperto.",
        "Anche un giocatore di scacchi tyro può vedere quella cantonata.",
        "recluta, novizio",
        "un soldato giovane e verde",
    ),
    "execrable": (
        "Estremamente cattivo, detestabile.",
        "Cattivo in un modo che merita un vero disgusto — non solo mediocre, ma francamente atroce.",
        "Il recensore chiamò il sequel execrable, e il botteghino gli diede ragione.",
        "maledire",
        "degno di, capace di essere",
    ),
    "incarnadine": (
        "Di colore rosso sangue.",
        "Un rosso profondo e vivo — il colore del sangue fresco, reso famoso dal Macbeth di Shakespeare.",
        "Il tramonto tinse tutto il cielo di un bagliore incarnadine.",
        "dentro",
        "carne (rosso di carne)",
    ),
    "interstice": (
        "Un piccolo interstizio o spazio tra le cose.",
        "Il piccolo in-mezzo che si passa facilmente — la fessura tra le assi, il buco in un’agenda.",
        "Le erbacce spingevano su da ogni interstice del vecchio sentiero di mattoni.",
        "tra",
        "stare in piedi",
    ),
    "animadversion": (
        "Osservazioni critiche o censorie.",
        "Commenti pungenti, di disapprovazione — la critica che ha un po’ di sgridata.",
        "Le animadversions del professore sul saggio riempirono i margini di inchiostro rosso.",
        "mente",
        "volgersi verso",
    ),
    "irrefragable": (
        "Impossibile da confutare, innegabile.",
        "Così solidamente provato che non c’è argomento contrario — il caso è chiuso.",
        "La prova del DNA era irrefragable, e il processo finì entro l’ora.",
        "non",
        "opporsi, resistere",
    ),
    "involution": (
        "Complessità, intrico; anche un ripiegarsi verso l’interno.",
        "Una complessità aggrovigliata, ripiegata su sé stessa — cose così strette che costa staccarle.",
        "L’involution della trama lasciò metà del pubblico a sbrogliarla dopo i titoli di coda.",
        "dentro, verso l’interno",
        "rotolare, volgere",
    ),
    "dint": (
        "Forza o sforzo, come in «by dint of».",
        "Pura forza o impegno — sopravvive soprattutto nella locuzione «by dint of».",
        "Superò l’esame by dint of una pratica ostinata, pura e semplice.",
        "un colpo, una botta",
        "a forza di",
    ),
    "mortised": (
        "Unito con incastro a tenone e mortasa; incastrato con fermezza.",
        "Bloccato all’antica maniera del falegname — un pezzo entra giusto in un buco tagliato per lui.",
        "Le travi del vecchio fienile erano mortised insieme senza un solo chiodo.",
        "una cavità, un buco",
        "un morso, una presa",
    ),
    "apposite": (
        "Altamente pertinente, adatto.",
        "Esattamente ciò che il momento chiedeva — un commento, una citazione o un esempio che centra in pieno.",
        "La sua osservazione apposite riassunse tutto il dibattito in una frase.",
        "verso",
        "collocare",
    ),
    "lambent": (
        "Di un bagliore morbido o vacillante; anche, un ingegno leggero.",
        "Un bagliore mite invece di un incendio — una fiamma che gioca, o un ingegno giocoso più che tagliente.",
        "La luce delle candele gettava un bagliore lambent sulla vecchia sala da pranzo.",
        "leccare",
        "facendo (luce che «lecca»)",
    ),
    "anchorite": (
        "Un recluso religioso che vive in solitudine.",
        "Qualcuno che si ritira del tutto dal mondo per vivere solo in preghiera e riflessione.",
        "L’anchorite visse oltre trent’anni in una piccola cella addossata alla chiesa.",
        "indietro, via",
        "ritirarsi",
    ),
    "slake": (
        "Saziare la sete; spegnere.",
        "Soddisfare del tutto un desiderio — quasi sempre la sete, ma in senso figurato qualsiasi bisogno profondo.",
        "Un bicchiere d’acqua fredda slaked la sua sete dopo la lunga camminata.",
        "lento, allentato",
        "allentare, lenire",
    ),
    "acicular": (
        "A forma di ago.",
        "Lungo, sottile e appuntito come un ago — la forma di un ago di pino o di un cristallino acuto.",
        "I pini si riconoscono facilmente dalle foglie acicular.",
        "ago",
        "piccolo",
    ),
    "effete": (
        "Esaurito di vitalità, debole, troppo raffinato.",
        "Consumato e morbido — avendo perso il vigore primo a forza di comfort o di raffinatezza.",
        "I critici chiamarono effete la rivista un tempo audace, ombra dei suoi anni bravi.",
        "fuori",
        "fecondo, che ha portato",
    ),
    "appurtenance": (
        "Un accessorio o un piccolo elemento o diritto annesso.",
        "Un piccolo extra unito a qualcosa di più grande — gli accessori e gli annessi che vanno con il principale.",
        "Il contratto d’affitto includeva il garage e tutte le sue appurtenances.",
        "verso",
        "appartenere",
    ),
    "gloze": (
        "Sorvolare o minimizzare una colpa.",
        "Lisciare un errore con parole morbide, perché suoni più piccolo di quanto è.",
        "Tentò di gloze over la scadenza saltata con un vago discorso di «unforeseen challenges».",
        "una glossa, una spiegazione",
        "commentare — poi lisciare",
    ),
    "incipient": (
        "In uno stadio precoce, che sta appena cominciando.",
        "Appena in procinto di mostrarsi — il primissimo stadio, quasi invisibile, di qualcosa di più grande.",
        "I medici colsero i segni incipient della malattia prima che potesse diffondersi.",
        "su, dentro",
        "prendere (intraprendere, cominciare)",
    ),
    "afflatus": (
        "Ispirazione creativa, soprattutto divina.",
        "Una spinta improvvisa di ispirazione più grande di te — come se l’idea ti fosse stata soffiata da altrove.",
        "Il poeta raccontò che l’intero pezzo arrivò in un burst of afflatus alle tre del mattino.",
        "verso, su",
        "soffiare (un soffio sopra)",
    ),
}
